### ISSUE TITLE
Still exists: argc=1 even after specifying args in launch.json in VS code

### ISSUE THREAD

**Issue by WinfredHuang** [microsoft/vscode-cpptools#10086]
### Environment

- OS and version: Anolis OS 8.6 (based on CentOS/RHEL)
- VS Code: 1.72.2
- C/C++ extension: 1.12.4
- GDB / LLDB version: RHEL 9.2

### Bug Summary and Steps to Reproduce

Bug Summary:
While I wrote `args` in launch.json, it shows that argv=1 when debugging with gdb.

Steps to reproduce:
1. Write a C++ program that needs to read arguments from `argv`. These arguments should be paths (e.g. "/home/user/file1.txt").
2. Use the configuration file attached below. 
3. Start debugging with gdb inside VS Code. 
4. In the left panel, value of `argc` will be shown as 1. 

### Debugger Configurations

```shell
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/abs/path/to/program",
            "args": [
                "/abs/path/to/file1",
                "/abs/path/to/file2",
                "/abs/path/to/file3"
            ],
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description":  "Set disassembly flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

### Debugger Logs

```shell
no error messages found
```

### Additional Information

This is related to #2182, but happens on the latest version I get.

**Comment by WardenGnaw** [comment]
Can you add `"logging": { "engineLogging": true, "traceResponse": true, "trace": true }` to your launch.json config and share the output from the Debug Console?

**Comment by AurusHuang** [comment]
=thread-group-added,id="i1"
GNU gdb (GDB) Red Hat Enterprise Linux 9.2-7.0.2.an8
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, main (argc=1, argv=0x7fffffffd698) at ../src/AUX_METEO_SWH.cpp:19
19		if (argc < 4)
Loaded '/lib64/libnetcdf_c++4.so.1'. Symbols loaded.
Loaded '/lib64/libstdc++.so.6'. Symbols loaded.
Loaded '/lib64/libm.so.6'. Symbols loaded.
Loaded '/lib64/libgcc_s.so.1'. Symbols loaded.
Loaded '/lib64/libc.so.6'. Symbols loaded.
Loaded '/lib64/libnetcdf.so.15'. Symbols loaded.
Loaded '/lib64/libmfhdf.so.0'. Symbols loaded.
Loaded '/lib64/libdf.so.0'. Symbols loaded.
Loaded '/lib64/libjpeg.so.62'. Symbols loaded.
Loaded '/lib64/libsz.so.2'. Symbols loaded.
Loaded '/lib64/libhdf5_hl.so.100'. Symbols loaded.
Loaded '/lib64/libhdf5.so.103'. Symbols loaded.
Loaded '/lib64/libdl.so.2'. Symbols loaded.
Loaded '/lib64/libz.so.1'. Symbols loaded.
Loaded '/lib64/libcurl.so.4'. Symbols loaded.
Loaded '/lib64/libtirpc.so.3'. Symbols loaded.
Loaded '/lib64/libaec.so.0'. Symbols loaded.
Loaded '/lib64/libnghttp2.so.14'. Symbols loaded.
Loaded '/lib64/libidn2.so.0'. Symbols loaded.
Loaded '/lib64/libssh.so.4'. Symbols loaded.
Loaded '/lib64/libpsl.so.5'. Symbols loaded.
Loaded '/lib64/libssl.so.1.1'. Symbols loaded.
Loaded '/lib64/libcrypto.so.1.1'. Symbols loaded.
Loaded '/lib64/libgssapi_krb5.so.2'. Symbols loaded.
Loaded '/lib64/libkrb5.so.3'. Symbols loaded.
Loaded '/lib64/libk5crypto.so.3'. Symbols loaded.
Loaded '/lib64/libcom_err.so.2'. Symbols loaded.
Loaded '/lib64/libldap-2.4.so.2'. Symbols loaded.
Loaded '/lib64/liblber-2.4.so.2'. Symbols loaded.
Loaded '/lib64/libbrotlidec.so.1'. Symbols loaded.
Loaded '/lib64/libpthread.so.0'. Symbols loaded.
Loaded '/lib64/libunistring.so.2'. Symbols loaded.
Loaded '/lib64/librt.so.1'. Symbols loaded.
Loaded '/lib64/libkrb5support.so.0'. Symbols loaded.
Loaded '/lib64/libkeyutils.so.1'. Symbols loaded.
Loaded '/lib64/libresolv.so.2'. Symbols loaded.
Loaded '/lib64/libsasl2.so.3'. Symbols loaded.
Loaded '/lib64/libbrotlicommon.so.1'. Symbols loaded.
Loaded '/lib64/libselinux.so.1'. Symbols loaded.
Loaded '/lib64/libcrypt.so.1'. Symbols loaded.
Loaded '/lib64/libpcre2-8.so.0'. Symbols loaded.
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)

**Comment by AurusHuang** [comment]
The main program is as follows:
`int main(int argc, char *argv[])
{
	if (argc < 4)
	{
		cout << u8"Error message" << endl;
		return -2;	// Error: not enough arguments
	}
	return ...;
}`

**Comment by AurusHuang** [comment]
Solved. Looks like the ladybug button on the bottom status bar is not the right option to start a debug with arguments. I should press F5 instead.

**Comment by ZoellaB** [comment]
> Solved. Looks like the ladybug button on the bottom status bar is not the right option to start a debug with arguments. I should press F5 instead.

This still exists in Ubuntu 22.04.3 LTS ARM in VM inside of MacBook Air M2 chip. Is this a bug or intended feature?
