### ISSUE TITLE
In 'lanch.json', How to remove  the personal configure in 'sourceFileMap'?

### ISSUE THREAD

**Issue by Jiaguan** [microsoft/vscode-cpptools#1010]
This is my 'sourceFileMap' in 'lanch.json'
          "sourceFileMap": {
                "/export/home/z00292338/dtcenter/demo" : "${workspaceRoot}"
            }

'z00292338' is my personal card ID, but we need  global configure.
 We change it to '{env:USERNAME}', but then vs code report 'can not find file'.
Does anybody know how to get a global configure?

**Comment by frost-see** [comment]
same problem when debuging with pipeTransport.

**Comment by pieandcakes** [comment]
We don't do any preprocessing for variables. whatever VSCode passes us is what we use. If VSCode has a mechanism to have a variable, then as long as it is replaced with the right value before the debugger is called, it will work.

**Comment by frost-see** [comment]
@pieandcakes Thanks for your reply, I added some details,   
On my computer, it seems that VSCode has already parsed the variables. But Debugger does not recognize.   
And VSCode pops up the following message box:     

"Error: Unable to open 'main.cpp': File not found (\usr1\pDTest\demo\main.cpp).    Create File     Cancel"       
   
The sourceFileMap is very simple:  
```
"sourceFileMap": {
    // "remote": "local"
    
    // This way works well
    // "/usr1/pDTest/demo" : "D:\\demo"
    
    // This way does not work
    "/usr1/{env:USERNAME}/demo" : "D:\\demo"
},
```

**Comment by pieandcakes** [comment]
@Jiaguan  @nbstar When using {env.USERNAME} in your sourceFileMap (or in pipeTransport) VSCode does not replace env.USERNAME with your username (pDTest). That means that we get the literal string `{env.USERNAME}` when we get your `launch.json` config and not `pDTest`. This would need to be something VS Code would take as a feature request and would need to replace the parameter of `{env.USERNAME}` with your username during processing because we don't have a mechanism to process those tags. This is similar to using `${workspaceRoot}` in the string. When we get the value, `${workspaceRoot}` is already replaced with the workspace root by VS Code. 

You can file an issue with VS Code at https://github.com/Microsoft/vscode.
