### ISSUE TITLE
Intellisense not triggering

### ISSUE THREAD

**Issue by amecareth** [microsoft/vscode-cpptools#1012]
Hello,
I'm running vscode 1.15.1 on a Debian Jessie, kernel version is 3.16.0-4-amd64 with the extension version 0.12.3.
It seems that the intellisense is never triggered as I don't get the green highlight on my include and nothing happens when I invoke the setting file myself. If checked all the extension dependencies as well as the vscode ones with ldd and everything is good on that side.
Any idea on that?
Best regards

**Comment by maelvls** [comment]
Did you solve your issue? I have a similar problem (macOS, vscode 1.16.0, vscode-cpptools 0.12.4, clang-800.0.42.1). I didn't see anything special in the logs when running

    VSCODE_CPP_LOGDIR=$PWD VSCODE_CPP_LOGFILE_LEVEL=5 code .

**Comment by amecareth** [comment]
Yes, I solved it. I don't know if you have the same setup as I did, my
installation was made on a Linux connected to internet and i then copied
the installation on another Linux machine that couldn't be connected to it.
The fact is that the copy changed the rights on some of the binaries in the
extension folder, you just have to put back the executions rights on the to
files called Microsoft.something inside the bin folder of the cppextension

Le jeu. 14 sept. 2017 à 12:12, Maël Valais <notifications@github.com> a
écrit :

**Comment by maelvls** [comment]
Ok; apparently, my extension is loading correctly so I must have a different problem.
Thank you for your answer!

**Comment by amecareth** [comment]
But the extension loaded for me also it was only these two binaries that
are in charge of the intellisense that were not working

Le jeu. 14 sept. 2017 à 12:23, Maël Valais <notifications@github.com> a
écrit :

**Comment by amecareth** [comment]
Just check it to be sure ;)

Le jeu. 14 sept. 2017 à 12:23, Maël Valais <notifications@github.com> a
écrit :

**Comment by maelvls** [comment]
I finally found what was going wrong. In the [April 2017 vscode-cpptools update](https://blogs.msdn.microsoft.com/vcblog/2017/04/25/visual-studio-code-cc-extension-april-2017-update/), they explain that the _error squiggles_ can only work when the 'Intellisense' (aka 'Default') engine is enabled. But in the logs, I could see that the engine was falling back to 'Tag parser'.

So I forced the 'Default' mode:

```json
    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Disabled"
```

And tadaa! It works. This quirk should really be mentioned somewhere in the documentation of vscode-cpptools!

![capture d ecran 2017-09-14 a 16 13 48](https://user-images.githubusercontent.com/2195781/30434481-b94c8d00-9967-11e7-86f8-2368648b98c6.png)

**Comment by sean-mcmanus** [comment]
@amecareth Yeah, it's recommended that you use tar to maintain the executable rights when copying the binaries to another machine (otherwise you have to run a chmod again, which we normally do during installation).

@maelvalais We show in the Problems window a warning that says it's falling back to the Tag Parser due to headers not being found. We also show a popup info box the 1st time. There's a "Force semantic IntelliSense" code action that appears in the lightbulb on a missing include that causes a fallback...it's documented at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md , but it doesn't mention the intelliSenseEngineFallback setting itself.
