### ISSUE TITLE
How to exclude folders?

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#1021]
If I do peek declaration on an item, the peek window opens showing me instances in a folder I have included in the _files.exclude_ settings. If I search manually (Find in Files) it doesn't find them.

Is there a way to exclude folders from the _browse.path_, or should the extension respect the _files.exclude_ setting?

It would be great if it could do one or the other, especially as doing a control click to visit an item opens the wrong instance **and** opens the peek view... a double whammy, when it could just take me to the one I want... 8-)

In fact, why on earth does it open the first file it finds and then shows the peek view? Surely the point of the peek view is that it opens within the file you started from?

**Comment by bobbrow** [comment]
Did you set the files.exclude before or after you opened your folder?  If you set it after, you might be hitting a bug in the extension where we don't ever remove paths that have already been indexed.  If you use the "Reset IntelliSense Database" command, it should re-index your folder and take the files.exclude into account.

**Comment by sean-mcmanus** [comment]
We do have code that should remove all the excluded files/folders after the files.exclude setting changes, but it's possible there might be scenarios where it doesn't complete (i.e. if VS Code is closed right after the setting changes). If you make some additional change to files.exclude, do you see the flame appear in the bottom right and does it get fixed? Resetting the database should also work, but it might take longer to finish, since we have to reparse all the files.

**Comment by Gruntfuggly** [comment]
Resetting the data seems to have worked. Thanks!

**Comment by Gruntfuggly** [comment]
Sorry - I closed this too early because it looked like it was working - it still returns results from a file which is in the excludes. In fact, it's even worse. If I reset the database, it now opens the file that is in the excluded folder, and doesn't give me the option to select the file in the correct folder...
