### ISSUE TITLE
On installing extension manually, it shows "One or more extensions are for Visual Studio Code." 

### ISSUE THREAD

**Issue by Niraj2003** [microsoft/vscode-cpptools#10242]
### Environment

- OS and version:
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

### Additional Information

![image](https://user-images.githubusercontent.com/90129030/206102214-ba06e5a1-554c-496e-b962-7f60e51a2676.png)

There is no more information for deleting another extension or any other thing to remove another extension

**Comment by sean-mcmanus** [comment]
You're not supposed to double-click the vsix. That causes the Visual Studio installer to try to load the vsix instead of VS Code. See the instructions


"Install it via using the Extensions view in VS Code or download a vsix that matches your OS from Assets section below (or the "Download" dropdown in the "Version History" tab section on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) website) and then use the Extensions: Install from VSIX... command in VS Code (don't double-click the vsix or another app like VS might try to open it incorrectly).:
