### ISSUE TITLE
What does gcc tell you the include path should be?  Run this command and make sure all of the paths printed out are listed in your c_cpp_properties.json: `gcc -v -E -x c++ -`

### ISSUE THREAD

**Issue by tejangupta** [microsoft/vscode-cpptools#10279]
What does gcc tell you the include path should be?  Run this command and make sure all of the paths printed out are listed in your c_cpp_properties.json: `gcc -v -E -x c++ -`

_Originally posted by @bobbrow in https://github.com/microsoft/vscode-cpptools/issues/1041#issuecomment-330885162_
      
I am facing issues and would appreciate the help :)

**Comment by crytek12** [comment]
![image](https://user-images.githubusercontent.com/89571912/207557940-11fcc486-2239-4d3c-9435-29fbabd442e4.png)
![Screenshot 2022-12-14 145604](https://user-images.githubusercontent.com/89571912/207557793-f5a70c40-fb40-4312-bd52-bb18e2ce14b9.png)

**Comment by Colengms** [comment]
Hi @crytek12 .  Are you seeing an issue on a Windows machine or a Linux machine?  The gcc output you posted refers to Ubuntu, but the configuration from the `c_cpp_properties.json` you posted refers to `Win32` and `windows-msvc-x64`.

Are you trying to use a compiler from a WSL instance?  If so, I would suggest using the `WSL` extension to open a workspace hosted remotely under the WSL instance.  Similarly, if you're trying to use a compiler from a Docker container, you could use the `Dev Containers` extension to open a workspace hosted in the container.

Or, if you're trying to use a compiler (such as MinGW or Cygwin gcc) from a unix-like shell (such as MSYS2 or Cygwin) hosted on Windows, I'd suggest specifying the Windows path to the compiler in a `compilerPath` field instead of explicitly specifying compiler include paths in `includePath`.  The C/C++ Extension should correctly reinterpret the paths it internally queries from those compilers.

**Comment by crytek12** [comment]
> Hi @crytek12 . Are you seeing an issue on a Windows machine or a Linux machine? The gcc output you posted refers to Ubuntu, but the configuration from the `c_cpp_properties.json` you posted refers to `Win32` and `windows-msvc-x64`.
> 
> Are you trying to use a compiler from a WSL instance? If so, I would suggest using the `WSL` extension to open a workspace hosted remotely under the WSL instance. Similarly, if you're trying to use a compiler from a Docker container, you could use the `Dev Containers` extension to open a workspace hosted in the container.
> 
> Or, if you're trying to use a compiler (such as MinGW or Cygwin gcc) from a unix-like shell (such as MSYS2 or Cygwin) hosted on Windows, I'd suggest specifying the Windows path to the compiler in a `compilerPath` field instead of explicitly specifying compiler include paths in `includePath`. The C/C++ Extension should correctly reinterpret the paths it internally queries from those compilers.

I am using a windows machine. I am not sure how to have the .json file set up. And yes I am using gcc from a WSL instance. Sorry, I am new to VS Code, but from what you're saying, my remote workspace is already WSL Ubuntu 22.04 (this is the default for me)

**Comment by Colengms** [comment]
Hi @crytek12 .  The two VS Code images you posted appear to be from an instance that was not connected via the WSL extension.  There are a couple ways to open a WSL instance.  One of those ways is to run the command `WSL: New WSL Window` via the command pallete (which can be opened using Control+Shift+P, by default).

![image](https://user-images.githubusercontent.com/49173979/207946892-55346d8b-bd7e-4e6d-9492-2a55118fcba3.png)

Once you're in a WSL window, you can use `Open Folder...` to open a folder within the WSL instance.

You may not even require `c_cpp_properties.json` at all, as gcc should be chosen by default and system headers from gcc automatically detected.
