### ISSUE TITLE
Run Code Analysis on Active File ignores headers

### ISSUE THREAD

**Issue by pr8x** [microsoft/vscode-cpptools#10360]
### Environment

- OS and Version:  Windows 11
- VS Code Version:  1.74.2
- C/C++ Extension Version: 1.13.9
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Running "Run Code Analysis on Active File " ignores currently opened header file and instead executes on some random(?) .cpp file.

Steps to reproduce:

Configure clang-tidy, open header and call "Run Code Analysis on Active File". It only reports issues about my *.cpp files. When I check clang-tidy args it is invoked with the .cpp not the .h I called it from.

Interestingly for some headers it also complains about "#pragma once in main.cpp" (`clang-diagnostic-pragma-once-outside-header`) even when it's clearly a header.

Expected behavior:

Should be called with the header not some random cpp. 

### Configuration and Logs

```shell
Debug Output:

c:\Users\x\.vscode\extensions\ms-vscode.cpptools-1.13.9-win32-x64/bin/../LLVM/bin/clang-tidy.exe
--extra-arg=--target=arm-none-eabi-gcc
--config-file=C:\Users\x\y\.clang-tidy
--export-fixes=C:\Users\x\AppData\Local\Temp4342951776578068893\fixes21416.yaml
--quiet
C:/Users/x/y/src/application.cpp

((...))
```

**Comment by sean-mcmanus** [comment]
That is "by design". When you open a header file, we'll look for a source file to associate with that header and then code analysis will run on that. The errors in the header file may not be being reported if you don't have the `HeaderFilterRegex: ` property set correctly (it should be a pattern that matches the header that you want to have clang-tidy errors reported for).'

I've seen the `"#pragma once in main.cpp"` occur if the database hasn't been built yet and it isn't able to locate the correct source file for the header.

After opening the header, run the C/C++: Log Diagnostics command it'll show what source file is getting associated with the header.

Are you able to get it to work?
