### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by DustinCampbell** [microsoft/vscode-cpptools#1038]
_From @zhangmn799 on September 15, 2017 10:31_

## Environment data
VS Code version:1.16.1
C++ Extension version:0.13.0

## Steps to reproduce
1.Install preinstall ~~[redacted]~~
2.Install vscode
3.Install cingwin32
4.install c++ extension ~~[redacted]~~
5.Create a folder named test, create a file named main.cpp in test as following:
#include<iostream>
using namespace std;
int main()
{
cout<<"hello world"<<endl;//set a bp
return 0;
}
6.Compara project with command "g++ -g -o main.exe main.cpp"
7.Open vscode, open test folder, configure launch.json file
8.Set a bp in line cout<<"hello world"<<endl of main.cpp.
9.F5

## Expected  behavior
It will hit bp

## Actual behavior
It will pop an picture similar to Debug->configure->c++(GDB/LLGDB), F5(or hit mouse) it will pop a error as following:
![4](https://user-images.githubusercontent.com/26423555/30478401-7d8387a6-9a43-11e7-9bee-82ef453d372d.PNG)

_Copied from original issue: OmniSharp/omnisharp-vscode#1757_

**Comment by DustinCampbell** [comment]
This repo is for C++ for VS Code. I'll go ahead and move your issue over to https://github.com/Microsoft/vscode-cpptools/issues.

**Comment by bobbrow** [comment]
Does VS Code give you a callstack for that error in the Output window?  Please post that here.

**Comment by pieandcakes** [comment]
@zhangmn799 Please provide launch.json configuration and also when you installed the C++ extension, did you restart VSCode twice? After restarting VSCode, as @bobbrow mentions above, a download was supposed to start in the output window and should have completed. did that give you an error?

**Comment by zhangmn799** [comment]
launch.json  as following:
{
        "version": "0.2.0",
        "configurations": [
            {
                "name": "(gdb) Launch",
                "type": "cppdbg",
                "request": "launch",
                "program": "${workspaceRoot}/main.exe",
                "args": [],
                "stopAtEntry": false,
                "cwd": "${workspaceRoot}",
                "environment": [],
                "externalConsole": true,
                "MIMode": "gdb",
                "miDebuggerPath": "C:\\cygwin\\bin\\gdb.exe",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        ]
    }

I restart vscode several times. It can be repro each time. And there is no error in Output window.
Note: C++ extension install path is c++ extension for c++ auto test, due to it is Microsoft internal paths, I can't provide here.

**Comment by pieandcakes** [comment]
@zhangmn799 Can you confirm that `"type": "cppdbg",` in your launch.json does not have squiggles underneath it? It looks like your extension is not properly installed. Can you send me an email about this?

Thanks

**Comment by zhangmn799** [comment]
There is no squiggles underneath "type":"cppdbg"

**Comment by pieandcakes** [comment]
@zhangmn799 I can't duplicate this. My steps are:

* Install VSCode 
* Install extension using the install from vsix option in VSCode from the share you provided.
* Restart VS Code. Notice that when VS Code restarts, there are downloads happening in the Output window.
* Restart VS Code again because of the prompt
* launch your included app. 

Can you try those steps and see if they work or let me know which of those steps you are not performing?

**Comment by zhangmn799** [comment]
- **Install preinstall**
- Install VSCode
- Install extension using the install from vsix option in VSCode from the share you provided.
- Restart VS Code. Notice that when VS Code restarts, there are downloads happening in the Output window.
- Restart VS Code again because of the prompt
- **Open test folder, configure launch.json file. Set a bp in line "cout<<"hello world"<<endl;",  F5 , The issue repro.**
- **Restart VS Code, F5 ,It is hit bp and no problem.**
- **Close VSCode, delete .vscode under test folder.**
- **Restart VSCode, Open test folder, configure launch.json file. F5 , The issue repro.**

**Comment by zhangmn799** [comment]
Add bold text area is different between you and me.

**Comment by pnloyd** [comment]
@DustinCampbell Are we sure this is specific to the C++ extension. Ironically, since this was originally mistakenly posted posted under the C# extension issue tracker, I have experienced a seeemingly identical issue with the C# extension.
```
> dotnet new console
> launch vscode and open newly created project...
> Confirm creation of build / debug assets...
```
Produces..
![image](https://user-images.githubusercontent.com/22247793/30930730-6bd0c3b0-a377-11e7-8c25-b37e57a9c1a8.png)
### Environment
vscode: 1.16.1;
vscode.csharp: 1.13.0 beta3
dotnet SDK: 2.0.0

Edit: Possibly this is unrelated.. because despite the error I'm still able to start the db and hit breakpoints.

**Comment by DustinCampbell** [comment]
I have no idea. I moved the issue because of the repro. I have not seen a report for C#

**Comment by pieandcakes** [comment]
@pnloyd  That's good to know. We do have shared typescript code between C++ and C#. I'm still not getting a repro but I'm setting up more machines to see if I'm just lucky with my current one.

**Comment by pieandcakes** [comment]
@pnloyd @DustinCampbell @zhangmn799 So this looks like a VSCode issue:
https://github.com/Microsoft/vscode/issues/35163 and it looks like it is fixed.

**Comment by DustinCampbell** [comment]
> We do have shared typescript code between C++ and C#.

This is news to me. What code is being shared?

**Comment by pieandcakes** [comment]
@DustinCampbell from what I remember, we share the code to do process picking for attach and also the downloading logic for the downloading after installing.

**Comment by DustinCampbell** [comment]
Ah yes, the process picking. I'm not familiar with that code.

For the downloading logic, I think we diverged quite a bit when I used the C++ extension's code.

**Comment by pieandcakes** [comment]
This is now fixed in VS Code.
