### ISSUE TITLE
How to force semantic IntelliSense

### ISSUE THREAD

**Issue by BrianSipple** [microsoft/vscode-cpptools#1039]
The [`Language Server FAQ`](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#force-semantic-intellisense) documentation contains the following instruction: 

> If you want IntelliSense to operate on your files even when all #include directives do not resolve, then you can choose the option to always use the new IntelliSense engine.

Unfortunately, there's nothing explaining how to "choose the option to always use the new IntelliSense engine", so I'm a bit stuck.

Apologies if I'm missing something obvious, but it seems like this could use some elaboration.

**Comment by maelvls** [comment]
Hi,

I found out that you could use these settings in order to _force_ the new engine (see https://github.com/Microsoft/vscode-cpptools/issues/1012): 
```
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Disabled"
```
I'm not really sure if it is the way to go, but it has worked for me!

**Comment by sean-mcmanus** [comment]
Text is referring to the "Force semantic IntelliSense" code action: "You can select any of the problems in the window to navigate to the line when the problem was detected and a lightbulb will appear in the editor with some options to help you resolve the problem.". I've updated the FAQ to try to explain this better and added a comment about the setting mentioned by @maelvalais .

**Comment by naseer** [comment]
Is there a way to enable this behaviour globally by default?

**Comment by sean-mcmanus** [comment]
@naseer By "globally" do you mean for the user? If so, you can just set the setting in the user settings, which applies globally for the uesr.

**Comment by naseer** [comment]
` "C_Cpp.intelliSenseEngineFallback": "Disabled",` didn't seem to work for me - the error about the missing includes disappears then comes back when trying to complete a class member with a `.`

**Comment by sean-mcmanus** [comment]
Yeah, it's intentional to show the cannot find include path as an error -- the IntelliSense should be run though and you should see squiggles, etc., right? Any code that relies on definition in the missing include file won't work though, as expected.

For example,
![image](https://user-images.githubusercontent.com/19859882/50862183-cf228180-134f-11e9-8643-3a6a7017272e.png)

**Comment by sean-mcmanus** [comment]
@naseer If buggy behavior starts to occur after invoking completion after "." it's possible the IntelliSense process is crashing, and then falling back to the Tag Parser. You should be able to check the logging for the crash/disconnecting message, see https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md .

Using 0.21.0-insiders3 might have a fix for the crash, and is recommended for anyone posting to GitHub: https://github.com/Microsoft/vscode-cpptools/releases (or set C_Cpp.updateChannel to "Insiders"). It is identical to what we intend to ship with 0.21.0, minus some additional changes we're still working on.

**Comment by naseer** [comment]
You're right - with verbose logging, I'm hitting this
`IntelliSense engine is not responding. Using the Tag Parser instead.`

I'll try to update to 0.21

**Comment by naseer** [comment]
Can confirm that 0.21 fixes that issue - thanks for the quick solution!
