### ISSUE TITLE
"Create declaration/definition" removes 'struct' keyword from function parameters

### ISSUE THREAD

**Issue by skarasov** [microsoft/vscode-cpptools#10433]
Type: <b>Bug</b>

C language. Example code.
main.c
```
#include <stdio.h>
#include "main.h"

void func(struct ONE* lo)
{
    printf("%d", lo->i);
}

int main(void)
{
    struct ONE o = {0};

    func(&o);
    return 0;
}
```
main.h
```
struct ONE
{
    int i;
    int j;
};
```
RMB on definition of func() in main.c and select "Create declaration/definition". In main.h will be created function declaration but witout 'struct' keyword.

Extension version: 1.13.9
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by browntarik** [comment]
The root cause of this issue is actually a bug within Visual Studio and not our extension. We have already filed a bug against Visual Studio and this issue can be tracked here: https://developercommunity.visualstudio.com/t/CC-IntelliSense-incorrectly-treats-s/456439

This issue will be closed until further notice.

**Comment by michelleangela** [comment]
Adding reference to the GitHub duplicate issue https://github.com/microsoft/vscode-cpptools/issues/4383.

To increase priority of the issue on Visual Studio, please upvote https://developercommunity.visualstudio.com/t/usage-of-struct-foo-f-in-c-incorrectly-generates-a/759968
