### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by zajo** [microsoft/vscode-cpptools#1048]
This is not so much a bug report as feedback. The C++ Intellisense is still completely useless in VSCODE. I went through the trouble of giving it all the correct include directories and it still fails to find even simple function definitions, nevermind things like finding the correct function template specialization, etc.

This is in contrast to Intellisense in Visual Studio which works marvelously. Perhaps you should contact Microsoft and ask them to license that code. :)

**Comment by bobbrow** [comment]
Thank you for your feedback.  If you can provide us with more information to help us reproduce your issues in-house, we would be happy to take a look.  Otherwise I will close this issue.

**Comment by sean-mcmanus** [comment]
@zajo Go to Definition requires setting the "browse.path" setting. It sounds like you set the includePath setting (which is used for other features like error squiggles and hover). This extension is implemented by Microsoft and we re-use some of the same code that's in Visual Studio, but it's still in Preview and all the features haven't been ported yet.

**Comment by zajo** [comment]
Here is an example:

`set_options(*inst,model_inst_options::debug_draw_joints,true);`

Looking up `debug_draw_joints` says it can't find it, even though the name is qualified with the only namespace in the universe that contains it (yes, the file is on the include.path and the browse.path list, I have no include errors from Intellisense), while trying to locate `set_options` itself digs up an unrelated member function by the same name from `boost/asio/ssl/old/detail/openssl_context_service.hpp`, which the calling compilation unit does not include (the correct `set_options` is a free function bound by ADL).

As another example, looking up the definition of a local variable `v` digs up a local variable `v` from a member function in `QtWidgets.framework/Versions/5/Headers/5.9.0/QtWidgets/private/qcolumnview_p.h`, which not only the calling compilation unit does not include, but this path is Mac-specific (found only in the "Mac" configuration in c_cpp_properties.json), and I did this on Windows (the correct `v` is a local variable defined just 2 lines up from where I clicked).

**Comment by sean-mcmanus** [comment]
@zajo I'm not able to repro the problem you're describing. What is the type of model_inst_options and debug_draw_joints. I used this and Go to Definition works:
`namespace model_inst_options
{
    int debug_draw_joints;
}`.
If `model_inst_options::debug_draw_joints` is not the fully qualified name, then it will fail due to a bug that will be fixed in our pending update.

Go to Definition is using the Tag Parser now (symbol engine), which will bring in "too many" results that are invalid and it won't work for local variables (your second example) -- we're still working on porting the code from VS that uses the IntelliSense engine. The fact that it was pulling in symbols from the Mac config is because we don't do symbol database cleanup when the config changes, but that will be fixed in our pending update (doing a Reset IntelliSense Database command should also fix that).

Also, hover and autocomplete using . -> :: uses the IntelliSense engine, so you should be able to see the correct type of the variables and the available members.

**Comment by zajo** [comment]
I was under the impression that the VS Intellisense is used for browsing, if it isn't then obviously it won't work because C++ is unparsable. :)

Given that the "tag parser" will never work properly I'm not sure how useful this info would be, but in case it helps, the relevant definitions as seen in that example are:

```
namespace sm {
  struct model_inst;
  namespace model_inst_options {
    unsigned const debug_draw_joints=1;
  }
  void set_options( model_inst &, unsigned model_inst_options, bool on );
}
using namespace sm;
```
