### ISSUE TITLE
lldb debugger: Not able to specify a -- (double hyphen) as args in launch.json

### ISSUE THREAD

**Issue by thecoder138** [microsoft/vscode-cpptools#1050]
* MacOS 10:12.6
    * VS Code Version 1.16.1 (1.16.1)
    * C/C++ extension version: Version 0.12.4: September 12, 2017
    * In launch.json, lldb debug, provide following:
                "args": ["arg1 -- sub_arg1"]
    * Above double hyphen is not accepted as an argument to the program binary.

  Thank you!

**Comment by pieandcakes** [comment]
@thecoder138 I think what you want is `"args": [ "arg1", "--sub_arg1" ]` ? Or are you trying to specify it as one entire argument? I created a test app and I see that entire string (in your example) as argv[1] being passed through.

**Comment by WardenGnaw** [comment]
Closing issue.

Please file another issue if you have any other questions using the latest extension.

**Comment by MatthiasFH** [comment]
I have an issue similar to this, But I really want to pass a double hyphen to my program. I have a subprogram which needs parameters from the caller.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "build debug and run",
            "type": "cppdbg",
            "request": "launch",
            "program": "program_name",
            "args": 
            [
                "--all", 
                "{workspaceFolder}/sw/build/main.ao", 
                "--", 
                "-s"
            ],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "osx":
            {
                "MIMode": "lldb",
            }
        }
    ]
}
```

Debugging itself works just fine, but I need the double hyphen. Some where between by definition and the lldb call, the double hyphen gets removed.
In my opinion it is somewhat a vscode tool problem, because in the console it works just fine.
`> lldb program_name -- --all main.ao -- -s`
