### ISSUE TITLE
C intellisense suggesting methods from another file

### ISSUE THREAD

**Issue by le0n** [microsoft/vscode-cpptools#1056]
I'm trying to start a brand new C project, but whenever I type something intellisense will suggest methods or variables from another file which I did not include nor use. Is there a setting that I can toggle to stop it from doing that? Thanks

**Comment by bobbrow** [comment]
There are a couple of ways to change the behavior:
1. Disable our autocomplete and use VS Code's (which is only based on words in the current file):
    * Add `"C_Cpp.autocomplete": "Disabled"` to your settings.json
2. Turn off "Quick Suggestions" an only get the popups when you type `.`, `->`, `::`, or `#`:
    * Add ```"editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
    }``` to your settings.json
3. Improve the relevance of suggestions when you type `.`, `->`, or `::`:
    * Add `"C_Cpp.intelliSenseEngine": "Default"` to your settings.json

\# 3 is the recommended setting, but we haven't turned it on for quick suggestions yet, because of performance reasons.  We are tracking the issue with #13.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
