### ISSUE TITLE
Add support for configuration with clang-cl version 7 or older that don't support /clang: arguments

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10624]
See the thread at https://github.com/microsoft/vscode-cpptools/issues/10529#issuecomment-1451965990

**Comment by sean-mcmanus** [comment]
Unfortunately, this appears to be unsupportable -- unless someone knows of an equivalent of `/clang:` with clang 7, which there doesn't appear. to be.

**Comment by Colengms** [comment]
We would use `/clang:` to pass-through down a couple gcc-like args to get the compiler to output its system includes and system defines.  So what we're blocked on here is some/any way to query system includes and system defines from.  Without that capability, the compiler path is not useful to us, and the user would have to add system includes and defines to their `c_cpp_properties.json` configuration directly, as well as set the IntelliSenseMode.

**Comment by emptyVoid** [comment]
@sean-mcmanus @Colengms 
The following command yields the same output in version 7.0.0 as does `/clang:-E /clang:-dM nul` in version 8.0.1:
`"C:\Program Files (x86)\LLVM\bin\clang-cl.exe" -Xclang -E -Xclang -dM /E -c dummy.cpp`
I couldn't find a way to feed **nul** as input though.

**Comment by Colengms** [comment]
Reopening.  It looks like it might be possible to make this work clang-cl 7 with `-Xclang` instead of `/clang:`.  Some of the GGC args we need to pass in don't appear to be accepted by `-Xclang`, such as bitness args (-m32, -m64) and compiler flags (clang:-fno-blocks).  And it doesn't accept `nul` or `/dev/null` output, so we would need to create a dummy source to compile, in a directory we can write to.
