### ISSUE TITLE
#include highlight issue

### ISSUE THREAD

**Issue by longyn** [microsoft/vscode-cpptools#1064]
See the highlight of "#inlcude <asset.h>"

``` code
#ifndef TEST_H_
#define TEST_H_
#include <assert.h>
```

* Wrong.

![image](https://user-images.githubusercontent.com/5205838/30839935-2c73ebc8-a2a7-11e7-9e8d-0a949f828858.png)

* Normal

![image](https://user-images.githubusercontent.com/5205838/30839944-339e5208-a2a7-11e7-94d0-b140f1dbd3e5.png)

**Comment by sean-mcmanus** [comment]
The root cause is Microsoft/vscode-textmate#40 . Our extension doesn't provide keyword colorization for C/C++. It's implemented via vscode-textmate and atom/language-c packages. They said they had a fix a few months ago, but it's still reproing. If more people would complain to the VS Code team, maybe they'd give it more priority.
