### ISSUE TITLE
Customise references colour?

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#1065]
I like the new references highlight on hover, but is there a way to customise the colour? I use a dark theme and the highlights are a dark blue which makes them hard to see...

**Comment by bobbrow** [comment]
This can be customized with the following settings, but it seems they don't work correctly with our extension right now because we don't mark occurrences as read or write.  I don't know why VS Code doesn't expose a setting for general occurrences.

![image](https://user-images.githubusercontent.com/12818240/30870414-a4869796-a298-11e7-9abc-fc5f43c345a4.png)

I'll talk with the team about this, but my first inclination is to just mark everything as a "read" occurrence to unblock theme customizations in the near term.

**Comment by michelleangela** [comment]
We are currently unable to address this feature request since we are focusing on higher priority features and bugs right now.  We'll tag this for follow up in case it receives more interest from the community, but to keep our issue count manageable, we're closing this issue for now.
