### ISSUE TITLE
errorSquiggles 'user-defined literal operator not found' for macro

### ISSUE THREAD

**Issue by startup73** [microsoft/vscode-cpptools#1069]
Operating Sytem:Win7 X86_64
VS Code: V1.17.0-insider
C/C++ extension version: 0.13.0

only if 
* macro has parameters
* call the macro with "%s" 
* the macro defined with do while
* the `do{` in the same line with define

a.h
```cpp
#define LOG_ERROR(format, argv...) do {    \
                printf("[%s|%d]"format, __FILE__, __LINE__, ##argv); \
} while (0)
````
a.cpp
```cpp
#include "a.h"
...
LOG_ERROR("%s", "abc");
...
```

**Comment by bobbrow** [comment]
Thanks for reporting this.  I also saw it last week while getting a demo ready for CppCon, but forgot to log an issue for it.  I was able to work around the issue by adding whitespace between the quoted text and the argument (e.g. "format" in your case)

**Comment by katjie** [comment]
I have noticed this as well, still now. When I use catch2 (c++ testing framework), all of my REQUIRE macros will be underlined with this "error".

**Comment by sean-mcmanus** [comment]
The bug repros with Visual Studio as well. I've reported bug https://developercommunity.visualstudio.com/content/problem/377739/c-intellisense-reports-invalid-user-defined-litera.html .

As a workaround, you could use `"[%s|%d]"##format` or `"[%s|%d]" format` as Bob suggested.

You also need a comma before the "...".

**Comment by pedzed** [comment]
> When I use catch2 (c++ testing framework), all of my REQUIRE macros will be underlined with this "error".

I am using Catch2 as well and it is driving me crazy. What have you done in the mean time? Disable error squiggles altogether?

![image](https://user-images.githubusercontent.com/8146593/61867944-9fe0f580-aed8-11e9-9239-9e242e877f06.png)

**Comment by katjie** [comment]
Hi @pedzed  
I reported issue #2786 which relates a little bit more to my specific case with Catch2. Maybe you can try some of the suggestions made in there, however I found them unsuccessful. However, for unrelated reasons, we have since decided to use GoogleTest instead. GoogleTest did not have this problem.

**Comment by colinaaa** [comment]
I'm using Catch2, and I'm getting the same problem!

**Comment by shehabattia96** [comment]
Upvote, it's driving me insane too. Using Catch2!

**Comment by sean-mcmanus** [comment]
@shehabattia96 Upvotes to this issue may not be "counted", because the issue is being tracked by https://developercommunity.visualstudio.com/content/problem/377739/c-intellisense-reports-invalid-user-defined-litera.html , but that requies a Microsoft account to upvote.

I've filed a request to enable GitHub users to upvote VS issues without a Microsoft account at https://developercommunity.visualstudio.com/idea/869998/enable-vs-code-users-with-github-accounts-to-upvot.html

**Comment by shehabattia96** [comment]
@sean-mcmanus Thanks for creating a ticket and for letting me know! HNY!

**Comment by sean-mcmanus** [comment]
A potential workaround is to use
```
#if __INTELLISENSE__
#pragma diag_suppress 2486
#endif
```

**Comment by boid-com** [comment]
Great solution, is this documented anywhere?

**Comment by sean-mcmanus** [comment]
I don't know. Might not be. I'm not sure where a good place would be to document that though.

**Comment by boid-com** [comment]
On this page:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

**Comment by Colengms** [comment]
I no longer reproduce this issue with a recent version of the extension (1.23.1).  I get no squiggle, provided the user-defined literal operator is defined, without requiring whitespace to work around the issue.  Closing as fixed.
