### ISSUE TITLE
Raspian ARM OS v10 -> v11 upgrade causes...

### ISSUE THREAD

**Issue by craigarno** [microsoft/vscode-cpptools#10706]
### Environment

- OS and Version: 

    PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
    NAME="Debian GNU/Linux"
    VERSION_ID="11"
    VERSION="11 (bullseye)"
    VERSION_CODENAME=bullseye
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"

- VS Code Version: 

 Version: 1.76.0
    Commit: https://github.com/microsoft/vscode/commit/92da9481c0904c6adfe372c12da3b7748d74bdcb
    Date: 2023-03-01T10:23:02.008Z
    Electron: 19.1.11
    Chromium: 102.0.5005.196
    Node.js: 16.14.2
    V8: 10.2.154.26-electron.0
    OS: Linux arm64 5.15.84-v8+
    Sandboxed: No

- C/C++ Extension Version
   1.76.2

**_Error Message_: "The C/C++ extension installed is compatible with but does not match your system."**

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1.    Install Code under Raspian v10
2.    Add C/C++ extension
3.    Upgrade OS to Raspian v11
4.    Start Code
5.    The C/C++ extension installed is compatible with but does not match your system.
6.    I tried the "Update/Restart" button, which didn't resolve the issue.
7.    When I try to use the Web .deb upgrade it tries to install the AMD64 instead of the ARM64 package. That obviously isn't going to work. So now I'm stuck while trying to get setup for ARM64 Code Debug.

- C/C++ Extension Version: 
1.76.2

### Configuration and Logs

**_Error Message_: "The C/C++ extension installed is compatible with but does not match your system."**

### Other Extensions

.

**Comment by sean-mcmanus** [comment]
This sounds like a VS Code bug, because our extension isn't responsible for installing itself. Can you file an issue at https://github.com/microsoft/vscode/issues ? They may need to know which version of the cpptools extension is being installed (it usually would say in the path). Its sounds like the x64 version might be getting installed instead of the arm64 version or vice versa, it's also possible there could be an issue with your VS Code install itself being x64 instead of arm64.

The code that checks this is at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/main.ts#L217 so you could possibly debug that to see what is going wrong.

You may be able to work around it by manually downloading/install the correct vsix: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.4, i.e. https://github.com/microsoft/vscode-cpptools/releases/download/v1.14.4/cpptools-linux-aarch64.vsix .

**Comment by craigarno** [comment]
Thank you, I posted my issue here https://github.com/microsoft/vscode/issues/177682#issue-1632467581

**Comment by Colengms** [comment]
Closing as external.
