### ISSUE TITLE
Extension doesn't use editor's language settings for tooltips

### ISSUE THREAD

**Issue by KrkiCZ** [microsoft/vscode-cpptools#10701]
### Environment

- OS and Version: Windows 10 pro (Czech version)
- VS Code Version: Version: 1.76.2
- C/C++ Extension Version: v1.14.4

### Bug Summary and Steps to Reproduce

Bug Summary:
The tool tips are displayed in language of the Windows not in language of the VS Code.

Steps to reproduce:
1. Windows for different country (eg. Czech version) should be installed
2. VS Code should be set to English display
3. When hovering over the symbol the Windows native language is used instead of language set in VS Code

![ToolTipErrorOnHover](https://user-images.githubusercontent.com/82330128/226123432-982cf2dc-0c30-4d32-982b-c3bdabb1b01a.png)

Expected behavior:
The tool tips should use language set by VS Code.

### Configuration and Logs

```shell
Configuration:
"C_Cpp.default.compileCommands": "${workspaceFolder}/.vscode/compile_commands.json",
"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"

Logs:
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/activeDocumentChange: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h
LSP: cpptools/getCodeActions: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 62)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getFoldingRanges: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 63)
LSP: cpptools/getInlayHints: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 64)
LSP: cpptools/getCodeActions: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 65)
LSP: textDocument/hover: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 66)
LSP: textDocument/hover: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 67)
čekací cyklus: aktivní dokument se znovu parsuje
Kontrolují se chyby syntaxe: D:\DEV_PROJECT\Atlas_SoC\PlayGround\Test_project\os\Os_Types.h
Do fronty se zařazuje aktualizace IntelliSense pro soubory v jednotce překladu: D:\DEV_PROJECT\Atlas_SoC\PlayGround\Test_project\os\task\Os_Task_Services.c
Počet podtržení chyb vlnovkou: 0
Počet podtržení chyb vlnovkou: 0
Počet podtržení chyb vlnovkou: 0
Čas aktualizace IntelliSense (sek.): 0.293
LSP: cpptools/getSemanticTokens: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/task/Os_Task_Services.h (id: 68)
LSP: cpptools/getSemanticTokens: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/task/Os_Task_Services.c (id: 69)
LSP: cpptools/getSemanticTokens: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 70)
LSP: textDocument/hover: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 71)
LSP: cpptools/getFoldingRanges: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 72)
LSP: textDocument/hover: file:///d%3A/DEV_PROJECT/Atlas_SoC/PlayGround/Test_project/os/Os_Types.h (id: 73)
```

### Additional context

I found closed issue [4442](https://github.com/microsoft/vscode-cpptools/issues/4442) which describe same problem.
I follow the suggested fix with the [Configure the Display Language](https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language) which doesn't help me.
I tried to install and change the display language to Czech `(this wasn't present at my PC before)` and then back to English but this doesn't help either.

**Comment by sean-mcmanus** [comment]
This seems like the same issue reported at https://github.com/microsoft/vscode-cpptools/issues/10632, but the VS Code issue should be fixed with 1.76.2.

**Comment by KrkiCZ** [comment]
The pull request #10669 looks like it could be related to this issue.

**Comment by sean-mcmanus** [comment]
Yeah, but I think we decided to submit that PR because we determined it wouldn't fix the issue. I'm not sure why that PR is still open and we might close it later this week.

**Comment by Colengms** [comment]
This is almost certainly a VS Code issue.  For some of our strings, we use `vscode-nls` (essentially VS Code itself).  For (native) strings where we can't use `vscode-nls`, we are determining the language in the same way as `vscode-nls`.  This type of issue has been seen before in situations where VS Code informs us (and `vscode-nls`) of a language ID that VS Code itself does not have a language pack installed for, causing VS Code to fall back to English, yet we will still display strings in that language because we bundle our own strings within the extension and don't use the language pack.  A similar VS Code bug: https://github.com/microsoft/vscode/issues/82791

In your log, the string, `Čas aktualizace IntelliSense (sek.)` was chosen by `vscode-nls` (essentially VS Code), and not by the C/C++ extension.  It's the result of call to `localize` from `vscode-nls`.

https://github.com/microsoft/vscode-cpptools/blob/e5b80da312efc8b091a9e46b0b2e5d5a975976ea/Extension/src/LanguageServer/client.ts#L2337

So, as far as I can tell, the information you provided us proves this is a VS Code (`vscode-nls`) issue.  Could you please open an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues) for this?  If you still have an active repro, that may be very helpful to them.

**Comment by Colengms** [comment]
Closing as external.  I've sent an email internally to someone on the VS Code team to let them know that https://github.com/microsoft/vscode/issues/82791 was not fixed as expected.

**Comment by Colengms** [comment]
I just synced up with Tyler Leonhardt on the VS Code team.  This should be fixed by https://github.com/microsoft/vscode/pull/177426 , which should now be available in VS Code Insiders.  If you're still able to repro in VS Code Insiders (and subsequent VS Code versions), please let me know.
