### ISSUE TITLE
Goto to function definition

### ISSUE THREAD

**Issue by PatrikMoberg** [microsoft/vscode-cpptools#1071]
When using goto definition you are always presented with both options even when function signature differs.

sample.h

void func(int var1);
void func(int var1, double var2);

sample.cpp

void func(int var1)
{
}

void func(int var1, double var2)
{
}

**Comment by bobbrow** [comment]
This is currently expected.  Issue #255 is tracking an updated implementation of go to definition using the new IntelliSense engine which is aware of the context in which the operation is requested.

**Comment by sean-mcmanus** [comment]
@PatrikMoberg Also, hover is expected to show only 1 function signature when the intelliSenseEngine is set to "Default" (and it doesn't fall back to the Tag Parser due to missing include paths).

**Comment by sean-mcmanus** [comment]
0.19.0 added IntelliSense-based Go to Definition which was expected to fix this, but there's a bug in which we incorrectly return all the overloads instead the matching one -- should be easy to fix for 0.19.1-insiders.

UPDATE: The overloads issue is fixed with https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders .
