### ISSUE TITLE
linux-gcc-x64 intellisenseMode seems to be wrong....

### ISSUE THREAD

**Issue by like955** [microsoft/vscode-cpptools#10745]
### Environment

- OS and Version: (windows11)wsl2-ubuntu22.02
- VS Code Version: latest
- C/C++ Extension Version:latest 
- If using SSH remote, specify OS of remote machine:no 

### Bug Summary and Steps to Reproduce

Bug Summary:
I had included the new header file and used "using namaspace std;".
while I use the locate new operator ,about "int * a = new [buffer[ int;" the intellisense produce a error log:no instance of new operator matching parameter list.However, I can compile this file correctly use g++ compiler and if I change the intellisenseMode to be windows-gcc-x64,the log will disappear.

Steps to reproduce:
1. witer a cpp file
2. include <new>
3. use a statement like "int * a = new [buffer[ int;"
4. See error "no instance of new operator matching parameter list"

Expected behavior: no error log
<img width="775" alt="the code" src="https://user-images.githubusercontent.com/112792583/227787438-4c85ed7e-f0e2-4aba-9930-d7c35027f61e.png">

### Configuration and Logs

```shell
"C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c17",
    "C_Cpp.default.intelliSenseMode": "linux-gcc-x64",
    "C_Cpp.clang_format_fallbackStyle": "Visual Studio",
    "C_Cpp.default.defines": ["_DEBUG", "UNICODE", "_UNICODE"],
    "C_Cpp.default.compilerPath": "C:/msys64/mingw64/bin/g++.exe",
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
    "C_Cpp.default.windowsSdkVersion": "10.0.19041.0",
    "C_Cpp.default.includePath": ["${workspaceFolder}/**"]

while I compile the file, the compile didn't produce error log.So I think it maybe the error of intellisense engine.
```

**Comment by Colengms** [comment]
Hi @lingkerio .  Your issue mentions using "OS and Version: (windows11)wsl2-ubuntu22.02", however settings you included all appear to be specific to Windows.

Using a simple example of the general scenario, I was unable to reproduce the issue on either Ubuntu 22 via WSL or on Windows using MinGW.  I used the following:

```
#include <new>

class test
{
    int i;
};

const int BUF = 512;

void foo()
{
    char buffer[BUF];
    test* p = new (buffer) test;
}
```

Does that reproduce the issue for you?

Can you provide a self-contained repro that I might use to reproduce the issue, perhaps in the form of a file attachment or a GitHub repo?

Also, when the issue is repro'ing, can you run "C/C++: Log Diagnostics" and provide that output?

**Comment by lingkerio** [comment]
Hi，Colengms . I'm sorry that my settings are specific to Windows using MinGW. However, the file I mentioned was correctly compiled in the wsl2 by the command "gcc filename.cpp". Actually, I just used the "linux-gcc-x64" intellisenseMode. Your example can reproduce the issue.&nbsp; I think maybe this issue resulting from that I used the wrong IntellisenseMode? But I can't make sense.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-cpptools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 凌晨5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] linux-gcc-x64 intellisenseMode seems to be wrong.... (Issue #10745)





 
Hi @lingkerio .  Your issue mentions using "OS and Version: (windows11)wsl2-ubuntu22.02", however settings you included all appear to be specific to Windows.
 
Using a simple example of the general scenario, I was unable to reproduce the issue on either Ubuntu 22 via WSL or on Windows using MinGW.  I used the following:
 #include <new&gt; class test {     int i; }; const int BUF = 512; void foo() {     char buffer[BUF];     test* p = new (buffer) test; }  
Does that reproduce the issue for you?
 
Can you provide a self-contained repro that I might use to reproduce the issue, perhaps in the form of a file attachment or a GitHub repo?
 
Also, when the issue is repro'ing, can you run "C/C++: Log Diagnostics" and provide that output?

**Comment by lingkerio** [comment]
Hi，Colengms . I'm sorry that my settings are specific to Windows using MinGW. However, the file I mentioned was correctly compiled in the wsl2 by the command "gcc filename.cpp". Actually, I just used the "linux-gcc-x64" intellisenseMode. Your example can reproduce the issue.&nbsp; I think maybe this issue resulting from that I used the wrong IntellisenseMode? But I can't make sense. Could it be that different modes cause instance in the file not to be found?




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "microsoft/vscode-cpptools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 凌晨5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] linux-gcc-x64 intellisenseMode seems to be wrong.... (Issue #10745)





 
Hi @lingkerio .  Your issue mentions using "OS and Version: (windows11)wsl2-ubuntu22.02", however settings you included all appear to be specific to Windows.
 
Using a simple example of the general scenario, I was unable to reproduce the issue on either Ubuntu 22 via WSL or on Windows using MinGW.  I used the following:
 #include <new&gt; class test {     int i; }; const int BUF = 512; void foo() {     char buffer[BUF];     test* p = new (buffer) test; }  
Does that reproduce the issue for you?
 
Can you provide a self-contained repro that I might use to reproduce the issue, perhaps in the form of a file attachment or a GitHub repo?
 
Also, when the issue is repro'ing, can you run "C/C++: Log Diagnostics" and provide that output?

**Comment by Colengms** [comment]
Hi @lingkerio .  When configured to use MinGW on Windows, you'll want to use a `windows-gcc.*` IntelliSense mode.  That would be used automatically, based on your `compilerPath`, if you remove `C_Cpp.default.intelliSenseMode`, as the C/C++ Extension will automatically interrogate most compilers to determine that information.  Setting the IntelliSense mode to `linux-gcc-x64` in that scenario may not provide a proper IntelliSense configuration, as the headers (i.e. `new`) on that local machine will be specific to MinGW and may contain content that will only be parsed correctly if the IntelliSense mode matches.

Whenever configured to use a compiler, you'll want the `windows`/`linux`/`mac` part of the IntelliSense mode to match the host platform.  If your code depends on system includes (i.e. `new`), which is usually the case, you'll need to configure a compiler in order for IntelliSense to find them.

I'd suggest using the VS Code WSL extension.  That would allow you to 'remotely' open a folder in WSL in the Windows UI.  In that scenario, the C/C++ Extension would run under the Linux instance and can be configured using the compiler available there.  Though, one consideration in that scenario is that your Windows-specific `C_Cpp.default.*` settings would not work correctly in the Linux instance, so you may want to ensure those are not being set in your global user settings file.

**Comment by lingkerio** [comment]
thank you, Colengms ! I understand where my mistake lies. it's your detailed explanation that I benefit a lot from.
