### ISSUE TITLE
vscode-cpptools extension is not available to install

### ISSUE THREAD

**Issue by zabereer** [microsoft/vscode-cpptools#10831]
In extensions view when searching for "c++" or "cpptools" only C/C++ Themes by ms-vscode is visible.
When installing manually as per https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools :
```
$ code --install-extension ms-vscode.cpptools
Installing extensions...
Extension 'ms-vscode.cpptools' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: ms-vscode.cpptools
```

**Comment by zabereer** [comment]
Installed from VSIX file and works fine (Linux-x64). So the issue is with vscode not finding or being able to search for C++ extensions from Microsoft, other extensions are there including cmake, just not the core C++ ones from ms-vscode.

**Comment by bobbrow** [comment]
Are you using the "official" VS Code from Microsoft, or some other build of it (e.g. VSCodium or Code - OSS?)  Off-brand distros of VS Code are not licensed to use the Microsoft Marketplace to install extensions and use Open-VSX.org instead.  The C++ extension is not published in Open-VSX.org because it is not licensed for use outside of the official Microsoft version of VS Code.

**Comment by zabereer** [comment]
I am using https://archlinux.org/packages/community/x86_64/code/ - it did not occur to me it is not "official".
