### ISSUE TITLE
Can not open head file

### ISSUE THREAD

**Issue by pardner0** [microsoft/vscode-cpptools#10921]
Type: <b>Bug</b>

> OS: Ubuntu 22.04.2 LTS
> Extension Pack: C/C++ v1.15.4;C/C++ Extension Pack v1.3.0;CMake v0.0.17;CMake Tools v1.14.31;Makefile Tools v0.8.1;C/C++ Themes v2.0.0
> c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/include/",
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}

All cpp source files in ${workspaceFolder}/src/, All cpp head files in ${workspaceFolder}/include/. 
The IDE workspace "#include <xxx.h>" line show "Can not open source file 'xxx.h'"

Extension version: 1.3.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.26GB (5.90GB free)|
|Process Argv|--crash-reporter-id 1a0560e6-7338-464b-96f6-c9798fb0677a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics (16 x 3194)|
|Memory (System)|7.39GB (6.30GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30731978

```

</details>

**Comment by Colengms** [comment]
Hi @pardner0 .  Use of `configurationProvider` in your configuration will essentially take precedence over all other settings in your `c_cpp_properties.json`.

It's possible that CMake Tools registered with the C/C++ extension due to detecting a `CMakeLists.txt` file in your workspace folder.  If it was the only custom configuration provider to register, the C/C++ extension will use it by default.  If you then generate your `c_cpp_properties.json` (by opening it for the first time via `C/C++: Edit Configuration` commands), it would get automatically populated there.

So, if you didn't intend to use CMake for your project, I'd suggest removing the `configurationProvider` entry.  Or, if your project does use CMake, and you've configured your CMake build using `CMake: Configure` (a required step for CMake Tools to start providing configurations), the issue may be with your `CMakeLists.txt` file not specifying that include directory using `target_include_directories` or `include_directories`.
