### ISSUE TITLE
Can't Go to Definition of Enumeration

### ISSUE THREAD

**Issue by LeThiHyVong** [microsoft/vscode-cpptools#1096]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
Bookmarks|ale|0.16.0
code-gnu-global|aus|0.2.2
githistory|don|0.2.3
gitlens|eam|5.4.1
macros|ged|1.2.0
CppSnippets|har|0.0.12
output-colorizer|IBM|0.1.2
auto-comment-blocks|kev|1.0.1
cpptools|ms-|0.13.0
partial-diff|ryu|0.3.3
surrounding|sif|1.2.0

(2 theme extensions excluded)

---
Suppose I have an headers enum.h in V:/vscode/inc:
```
enum SAMPLE {
    E1,
    E2
}
```
 and main.cpp in V:/vscode/sample
```
#include "enum.h"

int main() {
    E1;
    return 0;
}
```
The current project points to V:/vscode/sample and the c_cpp_properties.json:
```
{
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "V:/vscode/inc"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
 }
```

When I hover the E1 in main.cpp it still preview correctly. However, when I choose Go to Definition on E1 or "enum.h" it announces 'No definition found for E1/enum.h'.

If I open enum.h once (Ctrl+O) in that session, Go to Definition work correctly. 

![vscode1](https://user-images.githubusercontent.com/19317679/31159036-370c40d6-a8f0-11e7-8fde-e2be1312beb8.jpg)
![vscode2](https://user-images.githubusercontent.com/19317679/31159035-3708666e-a8f0-11e7-8a45-9da286c60572.jpg)

**Comment by bobbrow** [comment]
In the c_cpp_properties.json, you need to add `"${workspaceRoot}/../inc"` (or `"V:/vscode/inc"` - it's the same thing) to the `"browse.path"` array.  The extension didn't know about it because it doesn't search outside of this folder list.

The reason it works after opening the file is because we currently add loose files to the browsing database too.  It probably won't work that way in the future (to avoid polluting your database from random files you looked at in the past), so I recommend updating your `"browse.path"`.
