### ISSUE TITLE
Auto-formatting causing compile error for nested template types

### ISSUE THREAD

**Issue by dhhoang** [microsoft/vscode-cpptools#1102]
Auto-formatting  makes put '>' brackets in nested template types close together which causes compile error.
   For example, this declaration:
![image](https://user-images.githubusercontent.com/11325809/31259531-6491da0e-aa15-11e7-9dfe-0805a1b181b6.png)
   Will become this after auto-formatting:
![image](https://user-images.githubusercontent.com/11325809/31259557-9db1312c-aa15-11e7-9905-0f04db010e8d.png)

    * Ubuntu 16.04
    * Vscode 1.17.0 (stable)
    * C/C++ extension version: 0.13.1
    * Other extensions you installed and if the issue persists after disabling them: none

    
Relevant settings 
```json
{
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Enabled",
}
```

**Comment by sean-mcmanus** [comment]
This is "by design". Add `Standard: Cpp03` to your `.clang-format` file, `clang_format_style`, or `clang_format_fallbackStyle` (depending on where the settings are coming from) to change the behavior to match what you desire. The formatting is provided by clang-format. See http://releases.llvm.org/4.0.0/tools/clang/docs/ClangFormatStyleOptions.html for additional settings.

vector<vector<int>> v: (without the space between >) is valid as of C++11. I would recommend upgrading to a C++11 or newer compiler, and your hover tooltip provider is configured for C++03 as well (it's possible your compiler is newer, but the tooltip provider is out of date).
