### ISSUE TITLE
F-Secure detect a malware in microsoft.vscode.cpp.intellisense.msvc.exe

### ISSUE THREAD

**Issue by pypardo** [microsoft/vscode-cpptools#1103]
Hi,

Win7
VSCode 1.17.0
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

C/C++ 0.13.1

Since this morning release, my F-Secure anti virus program alerts ,me about 
`W32/Malware!DeepGuard.n in microsoft.vscode.cpp.intellisense.msvc.exe` 

Do you have the same kind of detection ?

Hope this may help.

Regards
pp

**Comment by pypardo** [comment]
Sorry for false alert,
after many virus detection (local and online), it seems it a false positive of my av software.

**Comment by sean-mcmanus** [comment]
This was actually a real issue  -- starting with 0.13.1 our binary started getting built without the Microsoft Digital signature (due to accidental changes to our build definition). Without the Microsoft digital signature, some virus scans (e.g. 3-6 out of 70) will incorrectly detect a problem (seems somewhat random). The binaries do not have any viruses, but without the digital signature, virus scans-related apps aren't able to verify that the binary is published by Microsoft.

**Comment by sean-mcmanus** [comment]
Our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases) has the Microsoft digital signature so it should no longer be incorrectly flagged by virus scanners.

Setting `C_Cpp.updateChannel` to `"Insiders"` is another way to get the update.
