### ISSUE TITLE
Find all references does not work

### ISSUE THREAD

**Issue by Miklak93** [microsoft/vscode-cpptools#11040]
Type: <b>Bug</b>

Enable most recent C++ extension for VSCode
Try "Find all references"
Output - errors, high cpu usage, no references found

Extension version: 1.15.4
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Connection to 'wsl+ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (3.08GB free)|
|Process Argv|--crash-reporter-id 7ac3a617-95ba-463b-971b-5282f4bc6b1f|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpathcf:30739705
pythonnosmt12:30757131

```

</details>

**Comment by Colengms** [comment]
Hi @Miklak93 .  We're not currently tracking any general issues with 1.15.4 impacting that functionality. If the issue is accompanied by an error indicating `Connection to 'wsl+ubuntu' could not be established`, that would seem to be coming from VS Code itself, not the C/C++ Extension.  You might considering following up in [the VS Code repo](https://github.com/microsoft/vscode/issues).  The C/C++ Extension runs natively on the remote system when remoting, and is agnostic to the entire remoting process.

If that's not directly related to the issue you are seeing with Find All References, could you provide more information, such a repro steps and/or log output, as described [in our issue reporting template](https://github.com/microsoft/vscode-cpptools/issues/new?assignees=&labels=&projects=&template=1_language-service.yml)?
