### ISSUE TITLE
No doc comment on function overloads

### ISSUE THREAD

**Issue by Rydial** [microsoft/vscode-cpptools#11071]
### Feature Request

When I hover over a non-overloaded function with a documentation comment above it, it displays the documentation.

However, when I hover over an overloaded function with a documentation comment above it, it displays all the overloaded functions, but not their corresponding documentation.

I want to choose whether or not those overloads are displayed, and/or would like to see the documentation regardless of whether or not there are overloads.

Screenshots:
![Screenshot from 2023-06-11 11-59-15](https://github.com/microsoft/vscode-cpptools/assets/40509594/248d3d26-d451-4917-8e23-3fffeda2a5b2)
![Screenshot from 2023-06-11 11-59-31](https://github.com/microsoft/vscode-cpptools/assets/40509594/ee982d6e-1dcb-4e3b-b1a4-ad9f6efba339)

**Comment by Colengms** [comment]
Hi @Rydial .  I'm not seeing that behavior.

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/bc5a7c8a-e660-4ef5-932f-2438925d1bc5)

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/e0865035-d056-4f2b-8974-ff9e4113ec33)

Is it possible you have another extension installed that is offering information on hover?

I do notice similar behavior if I set `"C_Cpp.intelliSenseEngine": "Tag Parser"`.  And, a hover request may use the tag parser results instead of IntelliSense, if the translation unit is still in the process of its initial update.  Is it possible that this issue resolves itself, if IntelliSense is given a moment to completely refresh?

If this doesn't clear up confusion about the behavior, could you provide a self-contained repro and/or the contents of the C/C++ output channel leading up to the repro, with the setting `"C_Cpp.loggingLevel": "Debug"` set?

**Comment by Rydial** [comment]
My apologies, you are right. At first, I was confused as the intelliSenseEngine mode was clearly set to "default' in the synced settings.json file for my account. But I failed to notice the settings.json file that existed locally in the project directory, with the line: "C_Cpp.intelliSenseEngine": "Tag Parser". Thanks for the help.

**Comment by starball5** [comment]
Related?: #6008

Related on Stack Overflow: [Why doesn't the VS Code Cpptools extension show function doc comments for functions with overloads?](https://stackoverflow.com/q/76421376/11107541)
