### ISSUE TITLE
Code folded in the wrong position at when file is unsave in Walkthrough

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#11087]
This issue was found through internal test pass.

**Actual Result:**
When file is unsave:
 
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/b5de64ce-1a30-4d06-8384-e360a7f13cb8)

**Expected Result:** 
After file is saved:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/35c75529-85d7-48a8-9e29-214e7cc1bf81)

Unsave when in 'Open Folder' mode:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/97c9626f-bab2-4950-9e5d-111b46c2e3d2)

Unsave when ‘Create a single file’ mode:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/50b8d539-aff4-46af-8806-65ecbbb3ca49)

**Comment by Colengms** [comment]
Unfortunately, this is a limitation of VS Code.  Although the file is being created already associated with the correct language ID (so it gets C/C++ syntax colorization from VS Code), no `didOpen` is delivered to extensions until the file is saved.  It's not possible for the C/C++ extension to provide language services for the file if there is no notification that it exists.

We could perhaps open an issue against VS Code to asking for didOpen for unsaved files, with some sort of temporary file path (which we may need to make changes to handle).  Otherwise, this is 'by-design'.
