### ISSUE TITLE
Setup debug environment from shell script?

### ISSUE THREAD

**Issue by JamesRamm** [microsoft/vscode-cpptools#1117]
I have a shell script which sets up various environment variables for debugging, this script is generated automatically by our pre build tool. It also conditionally sets variables depending on the chosen configuration

Is it possible to set up the environment used for debugging (in `launch.json`) from this shell script, rather than explicitly setting variables with the "environment" key?

**Comment by pieandcakes** [comment]
@JamesRamm You can set `miDebuggerPath` to point to a script that takes parameters to pass to `gdb` and then have that script possibly call your script and then gdb, passing the parameters to gdb.

**Comment by JamesRamm** [comment]
@pieandcakes Thanks. Is there anywhere I can see the standard call to `gdb` thats made? (what parameters vscode passes, if any). I'd like to keep the default behaviour after setting the environment

**Comment by pieandcakes** [comment]
@JamesRamm Sure. We pass only one parameter to gdb on the command line directly, `--interpreter=mi` which puts gdb in MI Mode. Everything else we wait until gdb is running and then issue setup commands.

You can find the relevant source code here:
https://github.com/Microsoft/MIEngine/blob/master/src/MICore/Transports/LocalTransport.cs#L28

**Comment by joelspadin** [comment]
I have a similar situation, and I tried setting up a script but wasn't able to get it to work. Our toolchain's version of GDB depends on the PYTHONHOME environment variable being set to a Python 2.7 installation, but setting the variable globally breaks Python 3.x installations, so our build tools generate the following Python script:

```Python
#! /usr/bin/env python
import os, subprocess, sys
os.environ['PYTHONHOME'] = 'C:\\Python27'
try:
    subprocess.call(['D:\\common\\archive\\extract\\win32-tools\\f03860e\\bin\\arm-poky-linux-gnueabi-gdb.exe'] + sys.argv[1:])
except KeyboardInterrupt:
    pass
```

The relevant portions of my `launch.json` are:

```JSON
{
    "name": "(gdb) Debug",
    "type": "cppdbg",
    "request": "launch",
    ...
    "MIMode": "gdb",
    "miDebuggerPath": "${workspaceFolder}/gdb.py", // the script from above
    "miDebuggerArgs": "--command gdbinit-linux.py",
    ...
}
```

When I try to start the debugger, I get

> Unable to start debugging. There was an error starting the pipe program 'path/to/project/gdb.py'. The specified executable is not a valid application for this OS platform.

I also tried setting `miDebuggerPath` to python.exe and putting the script at the start of `miDebuggerArgs`, but VSCode adds `--interpreter=mi` as the first argument, so it is treated as an argument to Python instead of to the script, which fails.

Is there another way I could set up a script for this that would work?

**Comment by borbmizzet** [comment]
I have a similar issue to @ChaosinaCan.  Is there any way around it?

**Comment by pieandcakes** [comment]
@borbmizzet Can you add a `"setupCommand"` to [set the environment variable](https://sourceware.org/gdb/current/onlinedocs/gdb/Environment.html) for gdb? Or are you saying you need it set before gdb starts?

If you want to try what @ChaosinaCan was doing, you can try specifying `python.exe` in a `pipeTransport` block as the `pipeCmd` and use `pipeArgs`. The debugger is the last command that will be appended. 

You can also create an `.sh` script and specify it in `miDebuggerPath`. It will need to call `gdb` at the end and pass the argument(s) we pass in to your script directly to `gdb`, which will be `--interpreter=mi`.

**Comment by joelspadin** [comment]
An update on the problem I was having: 

The older version of GDB I was using appeared to crash immediately before it would process any arguments if `PYTHON_HOME` wasn't set, but that is no longer happening after upgrading to a newer version of GDB. I am now able to set `miDebuggerPath` to the .exe and set up any other environment variables I need with `-ex "set PATH=VALUE"` arguments.

I was previously using a workaround similar to the `.sh` script method you suggested, but using a `.bat` file instead. That did work well.

Out of curiosity since you mentioned it, I experimented with using `pipeTransport` but wasn't able to get it to work. It would neither fail nor start debugging, and I couldn't see any output from it so I couldn't tell what it was doing or waiting for. I probably didn't set it up correctly, but it would be nice to have a better way to debug that.

**Comment by pieandcakes** [comment]
@ChaosinaCan The `pipeTransport` was a way to provide the ability to debug over SSH. We have had users use it for different other projects but the command arguments need to end with the ability to pass the debugger path in the `pipeTransport` block. 

Our [logging block](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) should give some information but if you want to debug it, you will need to follow our [MIEngine instructions](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/Debugger/How%20To%20Debug%20MIEngine.md).

**Comment by fbs2016** [comment]
> -ex "set PATH=VALUE"

What's the meaning of "-ex set PATH=Value"? How to set it in launch.json? Thanks
