### ISSUE TITLE
 #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\user\Downloads\Marlin-2.1.2.1\Marlin\src\MarlinCore.cpp).

### ISSUE THREAD

**Issue by Kurtis250** [microsoft/vscode-cpptools#11171]
### Environment

- OS and version: Windows 11 Pro
- VS Code: Unknown What ever is newest (7/9/23)
- C/C++ extension: Auto Build Marlin v2.1.45, PlatformIO v3.2.0, C/C++ Extension Pack v1.3.0
- OS and version of remote machine (if applicable):
- GDB / LLDB version: 

### Bug Summary and Steps to Reproduce

Bug Summary: Trying to Build marlin 2.1.2.1 for my CR-10 but keeps giving me (#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\user\Downloads\Marlin-2.1.2.1\Marlin\src\MarlinCore.cpp)) Iv tryed what was said to do in (https://github.com/microsoft/vscode-cpptools/issues/6165) but this did not fix the problem.

Steps to reproduce:
1. Load Marlin2.1.2.1 to workspace
2. open Configuration.h and Configuration.Adv.h
3. wait 10-15 seconds for errors to correct
4. see error (  #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\user\Downloads\Marlin-2.1.2.1\Marlin\src\MarlinCore.cpp)  )

### Debugger Configurations

```shell
Don't know where to find this
```

### Debugger Logs

```shell
Don't know where to find this
```

### Other Extensions

Auto Build Marlin v2.1.45
PlatformIO v3.2.0
C/C++ Extension Pack v1.3.0

### Additional Information

tried to use older version of marlin (marlin2.0.9.7) has the same problem

**Comment by Colengms** [comment]
Hi @Kurtis250 .  It looks like you chose the "Debugger" new issue form.  The [Language Service new-issue form](https://github.com/microsoft/vscode-cpptools/issues/new?assignees=&labels=&projects=&template=1_language-service.yml) requests some logs that would be useful to investigate this type of issue.  For example, If you run the `C/C++: Log Diagnostics` command, it will indicate how IntelliSense is configured for open files.  Could you provide the rest of the information requested there?

VS Code is an editor, and not a fully featured IDE.  Many IDEs are able to provide language services based on their own build configuration.  With VS Code, it's necessary to either directly configure the C/C++ Extension or use another extension (often which provides a build environment, such as CMake Tools or Makefile Tools) to configure the C/C++ Extension for you.

I'm not familiar with Marlin.  It looks to be related to embedded development.  I'm guessing the C/C++ Extension just needs to be configured with information about how files are compiled.  Since Marlin appears to be an embedded architecture, I'm assuming you'll at least need to provide your embedded compiler in the `compilerPath`.

It looks like Auto Build Marlin and Platform IO may facilitate configuring the C/C++ Extension, and perhaps some step is necessary to make that happen. You might consider contacting support for Platform IO and/or Auto Build Marlin.
