### ISSUE TITLE
cpptools client: couldn't create connection to server

### ISSUE THREAD

**Issue by SpaceCowboy321** [microsoft/vscode-cpptools#11182]
### Environment

- OS and Version: Windows 10 version 22H2
- VS Code Version: 1.80.0 (user setup)
- C/C++ Extension Version: 1.16.3
- If using SSH remote, specify OS of remote machine: No

### Bug Summary and Steps to Reproduce

Bug Summary:
When I run VS Code normally, there is a popup that says "cpptools client: couldn't create connection to server" and there is no Intellisense functionality.  However, if I start VS Code as an administrator, then there is no error and Intellisense works fine.  It seems like it's probably a permissions issue.  I am running the program on a work provided PC that has limited privileges, so while I can get temporary privileges to run programs as an administrator, I can't really change file permissions or anything like that.  However, I installed the program using the user setup version, so I would expect it to still work even without admin privileges.

As people have suggested in previous similar issues, I have tried uninstalling the extension, deleting the extension folders, and reinstalling the extension, but the issue still occurs.  I even tried a complete reinstall of VS Code with no other extensions installed, but the same issue occurs.

Steps to reproduce:
1. Start VS Code as normal user (not admin).
2. Open a C source file.
3. Popup displays saying "cpptools client: couldn't create connection to server."
4. Intellisense operations don't work.

Expected behavior:
No error occurs and Intellisense works properly.

### Configuration and Logs

```shell
I was unable open the c_cpp_properties.json (the "C/C++: Edit Configurations (JSON)" command had no effect).  I also tried the "C/C++: Log Diagnostics" command, but it also seemed to have no effect.  Below is the output error message with "C_Cpp.loggingLevel" set to "Debug", though that didn't seem to change anything.

Output error message:
[Error - 2:37:23 PM] cpptools client: couldn't create connection to server.
Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:441:11)
	at Object.spawn (node:child_process:752:9)
	at c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.16.3-win32-x64\dist\main.js:87539:46
	at async LanguageClient.createConnection (c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.16.3-win32-x64\dist\main.js:78534:28)
	at async LanguageClient.start (c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.16.3-win32-x64\dist\main.js:78080:32)
```

### Other Extensions

I uninstalled all other extensions, and the issue still occurred.

**Comment by Colengms** [comment]
Hi @SpaceCowboy321 .  It seems like a native binary in the C/C++ Extension may have become corrupted.  Could you try entirely deleting the installed C/C++ Extension directory and reinstalling the extension cleanly?  That path would be something like:

```
C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-1.16.3-win32-x64
```

It's necessary to completely remove the directory to cleanly reinstall.  Otherwise, VS Code will simply the existing directory.

If that doesn't address the issue, could try enabling the setting `"C_Cpp.loggingLevel": "Debug"`, and providing any output logged to the C/C++ output channel leading up to the issue?

**Comment by Colengms** [comment]
Hi @SpaceCowboy321 .  Sorry, I overlooked that you had already tried deleting the extension directory.

Could you verify that the following binaries are present?

```
C:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.16.3-win32-x64\bin\cpptools.exe
C:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.16.3-win32-x64\bin\cpptools-srv.exe
```

If you try executing these directly, do they launch without error?  (They won't function properly but shouldn't produce an error).

Is it possible you have anti virus/malware software that is effectively blocking the native components of VS Code extensions?

**Comment by libTorrentUser** [comment]
Running Alpine Linux here. and got the same error. And when I tried to manually execute `cpptools-srv`, I got a `not found`. And then ldd showed me some libs were missing. Turns out (probably) another glibc compatibility problem. I was so happy vscode was finally working on Alpine Linux :{

Installing the glibc hacky compatibility mumbo-jumbo kind of fixed the problem. At least now I don't see errors anymore when manually starting `cpptools-srv` and that particular `cpptools client: couldn't create connection to server.` error message disappeared from vscode. But I'm still getting `The C/C++ extension installed does not match your system` and, as expected, intelliSense is not working on my "hello world" program.

**Comment by Colengms** [comment]
This might be addressed in our next release (1.17.x). We're planning on shipping fully statically linked native binaries, using musl instead of glibc (as there are some issues with fully statically linking against glibc).  That should expand the Linux distros and versions supported by the extension.

**Comment by Colengms** [comment]
Hi @SpaceCowboy321 , @libTorrentUser .  Are you still seeing this issue with 1.17.5?

**Comment by libTorrentUser** [comment]
> We're planning on shipping fully statically linked native binaries, using musl instead of glibc

[Mr. Burns]Excellent![/Mr. Burns]

Just tried v1.17.5 on a Alpine Linux vm.
- intelliSense is working. Yay!
- but, weirdly enough, I'm still getting the `The C/C++ extension installed does not match your system` pop-up message.

Now if only someone could make the debugger work... But, to be honest, that doesn't really seem to be a `cpptools` problem since I also cannot debug python code in vscode. Probably another Alpine Linux incompatibility. But if any of you could come in on Saturday to take a look at that, that would be great... :)

**Comment by Colengms** [comment]
Hi @libTorrentUser .  I just tried installing 1.17.5 on Alpine Linux x64, through the marketplace (VS Code UI), and did not get a `The C/C++ extension installed does not match your system` pop-up message.  Can you clarify any details about your system or how you installed the extension that might differ from what I tried?

Can you also confirm the name of the extension folder that got installed to your Alpine system's `.vscode-server/extensions` directory?  I get: `ms-vscode.cpptools-1.17.5-alpine-x64`

My understanding is that our debugger should work on Alpine.  Another team supports our debugging experience. (I work on the Language Services, specifically).  I'd recommend opening a separate GitHub issue here for debugging, with details on what you've tried.

**Comment by libTorrentUser** [comment]
Ah, I think I found the problem - I've just realized there is a `cpptools-alpine.vsix'! All this time I've been using `cpptools-linux.vsix' and that was what was causing all this mess. Not sure why I get `The C/C++ extension installed does not match your system` when using Linux stuff on Linux but, hey, if you guys went through all that trouble to generate a release specific to Alpine, I don't see a reason not to use it :)

Now intelliSense is working, the error message is gone and... **THE DEBUGGER IS WORKING TOO!!!**

And to think all I had to do was to use the release created specifically for my system... I blame society!

**Awesome**!

**Comment by SpaceCowboy321** [comment]
> Hi @SpaceCowboy321 , @libTorrentUser . Are you still seeing this issue with 1.17.5?

Sorry for the delay.  I'm still hitting this issue even with version 1.17.5 (see error log below).  However, I think I know what the issue is.  My company's IT has restrictions on running any programs on our PCs that aren't approved.  If you try to run an unapproved executable, it's prevented from starting and doesn't even give you any sort of warning.  However, they also give us a mechanism to run a program temporarily as an administrator, which lets you bypass that check.  I think VS Code must be approved since I am able to run that fine even without being an administrator.  However, I think the extension executables are not considered approved, so they are prevented from starting.  I believe I confirmed that by trying to run cpptools.exe and cpptools-srv.exe manually, and they both didn't start.  When I run VS Code temporarily as an administrator, then I think that causes the extension's executables to also be run as an administrator, which bypasses the approval checks and lets it work as expected.  Using the temporary admin mechanism, I was able to run cpptools.exe manually, but cpptools-srv.exe closed immediately, which maybe is expected.

I'm assuming since the executables are being prevented from running, there is really nothing that can be changed in the extension to make it work, but let me know if you have any ideas or suggestions.  I can try to work with my company's IT to see if they will allow running the extensions executables, but I don't have high hopes that it will be any time soon.

VS Code Output:
`[Error - 10:46:29 AM] cpptools client: couldn't create connection to server.
Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:817:9)
	at c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\dist\main.js:76486:46
	at async LanguageClient.createConnection (c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\dist\main.js:67440:28)
	at async LanguageClient.start (c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\dist\main.js:66980:32)
	at async DefaultClient.createLanguageClient (c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\dist\main.js:47997:9)
	at async DefaultClient.init (c:\Users\omathcor\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\dist\main.js:47692:9)`

**Comment by Ashutosh-017** [comment]
I am using Windows 10. I am also facing same problem all of sudden. Please help me how to remove this error.  
[Error - 12:07:37 PM] cpptools client: couldn't create connection to server.
Launching server using command c:\Users\ashutosh\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe failed. Error: spawn c:\Users\ashutosh\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe ENOENT

**Comment by Colengms** [comment]
Hi @Ashutosh-017 .  Have you tried following the guidance in this issue?  We've seen that sometimes extension installation may fail, perhaps due to terminating VS Code while installation is in progress, or perhaps VS Code bugs, or perhaps files being blocked/deleted by antivirus software.  In your case, it appears that a required file is not present.  I'd suggest deleting the entire cpptools extension directory from your installed extensions (usually `%USERPROFILE%/.vscode/extensions`), and reinstalling it.

Though, the paths you referred to appear to be corrupted.  There should be a `\` between your username and `.vscode`.  Perhaps that was a copy-and-paste error?  Or, do you perhaps have a special character in your username that might be confusing VS Code?  (That part of the path would be composed by VS Code itself and passed to the C/C++ Extension in an `extensionPath` field of an `ExtensionContext` object).

**Comment by Ashutosh-017** [comment]
@colengms Thank you bro for your response. But I already clear that error by my own.  :-)
