### ISSUE TITLE
format cuda files

### ISSUE THREAD

**Issue by w-y-z** [microsoft/vscode-cpptools#11223]
### Feature Request

I want to format cuda files (. cu&. cuh), but I cannot use cpptools formatting properly. Is there any way to do this

**Comment by w-y-z** [comment]
I found a way to do it. I used clang-format plug-in unit &  set ' clang-format. fallbackStyle ':' WebKit '

**Comment by michelleangela** [comment]
@w-y-z 
The Clang-Format executable that is included with the cpptools extension should be able to format cuda files. Could you enable the language server logging (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and try formatting a cuda file and then share the logs here? The logs will show if there is any error from the Clang-Format executable.

Also, do you have any `C_Cpp.*` format settings modified, such as `C_Cpp.formatting` or `C_Cpp.clang_format*`?

**Comment by w-y-z** [comment]
I am using the Clang Format executable from cpptools, which is called by the Clang Format plugin. Only WebKit is set, and formatting looks consistent

**Comment by michelleangela** [comment]
>I am using the Clang Format executable from cpptools, which is called by the Clang Format plugin. 

The C++ extension has capabilities to run the Clang Format executable (which is the same executable from LLVM) and apply the Clang Format output to files. We're curious to know if there are specific features this other Clang Format plugin has that the C++ extension doesn't provide. Could you share a link to this other Clang Format extension (I see there are various ones for VS Code)?

**Comment by Colengms** [comment]
Hi @w-y-z .  In a simple example, in which I create a `test.cu` file and have only the C/C++ Extension installed, I'm able to successfully format that file by right-clicking within it and selecting, "Format Document".  Does this work for you?   Note that this scenario utilizes a copy of clang-format that is bundled with the C/C++ Extension.  You can override that using the setting: `C_Cpp.clang_format_path`.

> which is called by the Clang Format plugin

Perhaps you are encountering an issue specifically with that plugin?  I don't believe it's required when also using the C/C++ Extension, since this is built-in.  Or, if you need to disable the C/C++ Extension's handling of this feature, you could try setting `C_Cpp.formatting` to `disabled`.
