### ISSUE TITLE
Add setting to control whether or not to add `#include` for refactoring actions (i.e. create declaration/definition)

### ISSUE THREAD

**Issue by oldbitsnbytes** [microsoft/vscode-cpptools#11271]
### Environment

- OS and Version: latest/any
- VS Code Version: latest/any
- C/C++ Extension Version:latest/any 
- If using SSH remote, specify OS of remote machine: not applicable.

### Bug Summary and Steps to Reproduce

Bug Summary: 
You shall/must NOT assume:
1-  include is "local include" 
2-  might never been already chain-included.

Steps to reproduce:
1. any c++ project
2  new class/struct method member.
3. ctrl+. "Create definition of $funcname in ... $file.cc"
4. .cc: 

#include "$file.h" -> You cannot assume that you systematically have to add this!

Expected behavior:
Please, ** Let the programmer decides where and how to include the file. **

### Configuration and Logs

```shell
not applicable.
```

### Other Extensions

not applicable.

### Additional context

not applicable.

**Comment by bobbrow** [comment]
We include the file if it's not present as a nod to this guideline: [Avoid dependencies on implicitly included names](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf10-avoid-dependencies-on-implicitly-included-names)

We also offer an option to copy the definition/declaration to the clipboard so that you can insert it any way you want.  This does not add any `#include` lines.  Does this address your need?
![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/95590846-8787-4c84-b8d4-8efebf93ef69)

**Comment by oldlonecoder** [comment]
My apologies for me been rude. I feel that this issue might be closed and put it under the carpet. [To be taken with a grain of salt]; 

Changing the title to "Don't add #include to source file" is a brilliant one for describing the idea. 

What else can I say?

**Comment by michelleangela** [comment]
Draft PR for this issue.
Pull request 496507: cpptools - do not add #include if header or source file exists - Repos (visualstudio.com)<https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/496507>

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.18.0 (via the C_Cpp.refactoring.includeHeader setting).
