### ISSUE TITLE
IndentWidth: 8, TabWidth: 8 are not working in C_Cpp.clang_format_fallbackStyle

### ISSUE THREAD

**Issue by mudassirHus** [microsoft/vscode-cpptools#11327]
### Environment

- OS and Version: Linux Mint 21.2                    
- VS Code Version: 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794) x64
- C/C++ Extension Version: v1.17.2

### Bug Summary and Steps to Reproduce

Bug Summary:

Modified `C_Cpp: Clang_format_fallback Style` to take custom key-value pair settings as shown in below first two screenshots. Even though I format the file by right clicking and selecting the `Format Document (CTRL + SHIFT + I)` but Indent still takes only 4 spaces instead of 8. 

I assume `Editor: Tab Size` is taking precedence over fallback style.

Note: This happens only for Tab Indent, the other rule `PointerAlignment: Left` is applied as expected upon formatting the document. So I'm sure the fallback key-value pairs are applying. The issue is only when applying the rules `UseTab: Always, IndentWidth: 8, TabWidth: 8`.

![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/e9d1e16f-87c6-4d8c-9886-6e63319d4439)
![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/eea8533f-01f5-4186-a264-026ef5cffcd4)
![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/78eedfee-55b2-4e16-990e-44f3f665aec5)

Steps to reproduce:
1. Go to 'Settings' 
2. Set `"C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: LLVM, UseTab: Always, IndentWidth: 8, TabWidth: 8, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All, FixNamespaceComments: false , PointerAlignment: Left}"`
3. Past sample c code in text editor 
`#include <stdio.h>
int Count(int number)
{
int *somePointer = NULL;
int count = 0;
while (number > 0)
{
    count++;
    number = number / 10;
}
return count;
}
int main()
{
return 0;
}`
3. Right Click on document and select `Format Document`

Expected behavior:
![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/fbd6741b-2f11-4a27-9b23-27b12c6d4516)

Current behavior:
![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/8b1bd121-dcde-4bd3-bf5a-b1d2170772f3)

### Configuration and Logs

```shell
No errors on output window of c/c++
```

### Other Extensions

I only have basic C/C++ extensions installed as shown below:
![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/e7e2c5e0-3e63-42b2-b2ea-85ce6ee4cc24)

### Additional context

I even tried using custom .clang-format file but Tab spaces are not intended to 8 spaces. I scoped the issue to using custom key-value pair in fallback.

**Comment by michelleangela** [comment]
@MdMudassirHussain 
Just to clarify, is this with using tabs or tabs with spaces?

Here are examples with the setting `"editor.renderWhitespace": "all"` to show what is used for tabs.

Example with using tabs:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/945e459a-d825-488d-92fc-0582887940e5)


Example using tab with spaces:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/1bad23d6-3657-47d9-96d9-4aa51a26d928)

**Comment by MdMudassirHussain** [comment]
Hi @michelleangela 

Currently, my code file uses Tab characters (\t) instead of spaces. I have added screenshot including other options as well which might be dependent on this issue.

![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/8ca41bbb-3de5-4624-935d-7c5b887b0338)

**Comment by sean-mcmanus** [comment]
With Detect Indentation set and tabs in the document, it'll treat it as using tabs for formatting and your tabSize is 4 so that's what it'll be used. The editor.tabSize is controlled by VS and controls how tabs are rendering, so the current behavior is "by design". You need to change the editor.tabSize setting to 8 if you want to view tabs as having 8 spaces. The output of clang-format is the same you would get when running it on the command line, such as via `<pathTo>/vscode-cpptools/Extension/bin/../LL
VM/bin/clang-format.exe "-style={ BasedOnStyle: LLVM, UseTab: Always, IndentWidth: 8, TabWidth: 8, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All, FixNamespaceComments: false , PointerAlignment: Left}" -fallback-style=LLVM --Wno-error=unknown <pathTo>/test.c > <pathTo>/test.out.c`

**Comment by MdMudassirHussain** [comment]
@sean-mcmanus Thank you for the clarification. I'm interested in knowing if there's a way to completely disable the editor.tabSize setting. My goal is to ensure that all formatting options are exclusively sourced from the .clang-format file, including the tab size.

I attempted to disable the "Detect Indentation" feature in the document, but unfortunately, it didn't yield the desired outcome. The editor still doesn't utilize the tab size specified in the .clang-format file. The inconsistency of obtaining the tab size from the editor settings while other formatting options come from .clang-format is bit confusing.

It would enhance the clarity and organization of settings if we could establish a single source of truth for formatting settings, which would be applied when the "Format Document" action is triggered.

![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/9aafc4e4-7b3f-45f8-b989-420b4fcb5fef)

**Note:** In the above screenshot, the description of _"C_Cpp.clang_format_fallbackStyle"_ clearly indicates that .clang-format will be used when provided, along with the 'file' argument in "C_Cpp.clang_format_style". Thus, it's confusing that the tabSize is still extracted from editor.tabSize instead of the .clang-format file. My first reaction was that it was a bug.

couple of ideas to address this issue:
1. Allow users to set editor.tabSize = 0 (currently not possible) so that the tab size setting can be fetched from the .clang-format file.
2. When the user selects "C/C++" as the default formatter in the editor (as shown in the screenshot below), the tabSize setting could be sourced from the .clang-format file.?
![image](https://github.com/microsoft/vscode-cpptools/assets/7047675/aaacac21-7d52-4e8a-9da4-a980c771683b)

I would greatly appreciate it if you could inform me if there's a viable approach to achieving a single source of truth for formatting settings via the .clang-format file. Please let me know.

**Comment by sean-mcmanus** [comment]
Formatting only affects the raw contents of a file, but the editor.tabSize setting doesn't affect the contents of a file -- it just affects the rendering. Different viewers of the same file with different editor.tabSize settings will see different results, which is one reason why tabs are not recommended to use. You may want to try to format it to not use tabs, i.e. change UseTab: Always (if that doesn't work, you may need to also change editor.detectIndentation and/or editor.insertSpaces).

As I said previously, I get the same results when I run clang-format on the command line, so the issue is not really related to our extension or the editor.tabSize setting. There are situations when we do read the editor.tabSize to modify a clang-format style, but it doesn't appear that you're hitting that.
