### ISSUE TITLE
Thanks a lot . I have been able to do what I wanted.

### ISSUE THREAD

**Issue by Swami12354** [microsoft/vscode-cpptools#11358]
Thanks a lot . I have been able to do what I wanted.

_Originally posted by @siddharthvaddem in https://github.com/microsoft/vscode-cpptools/issues/6191#issuecomment-699535034_
  
Hello,

I've been trying to add sound as well to my project and saw the same exact vid as you. But I am new to coding. The other link that helped you, I cant understand that. Do you mind helping me, and explain step by step. Thank you

**Comment by bobbrow** [comment]
Hi there @Swami12354, this support forum is for issues with configuring IntelliSense and Debugging in the C++ extension.  If you are using a specific library (open source or otherwise) to provide sound functionality, you should consult that library's documentation as to how to build your code to include it.  If you are having problems with getting IntelliSense or Debugging configured, let us know and we can try to help.
