### ISSUE TITLE
1.17 and above shows a lot of wrong errors

### ISSUE THREAD

**Issue by light-and-ray** [microsoft/vscode-cpptools#11351]
### Environment

- OS and Version: Kubuntu 22.04.3 LTS x86_64
- VS Code Version: 1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
- C/C++ Extension Version: 1.17.2+
- If using SSH remote, specify OS of remote machine: -

### Bug Summary and Steps to Reproduce

Bug Summary:
1.17  and above shows a lot of wrong errors in kind of "must be a namespace name", "is not definded", "don't have member" etc

I tried everything: clear vscode cache, intellisecne db, reinstalling vscode, diffetent gcc versions form 9 to 12 in c_cpp_properies.json - even after install system from scratch it had the same problem. Only rollback to 1.16.3 and below could solve this problem

![5873425324](https://github.com/microsoft/vscode-cpptools/assets/33491867/1ebadf3e-db79-42d5-8838-b6186576e024)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/src",
                "${workspaceFolder}/**",
                "${workspaceFolder}/src/**",
***
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}



-------- Diagnostics - 8/22/2023, 2:30:02 PM
Version: 1.17.2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
*
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/bin/gcc",
    "mergeConfigurations": false,
    "browse": {
        "path": [
*
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.17.2.0
Translation Unit Mappings:
```

### Other Extensions

no

**Comment by Colengms** [comment]
Hi @light-and-ray .  Thanks for reporting this.  Would it be possible to also provide the same configuration and logs from a previous version in which this did not repro, so we can compare them?

It's possible the issues you are seeing are due to regressions in the IntelliSense engine.  If the configuration information from 1.16.x matches what are get with 1.17.x, the issue could be related to some segment of code that the prior version was able to process successfully and the newer version is no longer able to.  If so, if you can isolate that into an example you can share with us, in the form of a zip file or github repo, that could help us investigate the issue and validate a fix.

**Comment by light-and-ray** [comment]
Okey, 1.16.3:

### Environment
the same
- OS and Version: Kubuntu 22.04.3 LTS x86_64
- VS Code Version: 1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
- C/C++ Extension Version: 1.16.3-
- If using SSH remote, specify OS of remote machine: -


### Bug Summary and Steps to Reproduce

Bug Summary:
No bug



### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/src",
                "${workspaceFolder}/**",
                "${workspaceFolder}/src/**",
*
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}



-------- Diagnostics - 8/23/2023, 3:44:11 AM
Version: 1.16.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
*
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/bin/gcc",
    "mergeConfigurations": false,
    "browse": {
        "path": [
*
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.16.3.0
Translation Unit Mappings:

```


----------------------
I will think is it possible to isolate that into an example

**Comment by rubiot** [comment]
This is most probably the same problem reported in #11326.

**Comment by Colengms** [comment]
Hi @light-and-ray .  This issue does appear very similar to https://github.com/microsoft/vscode-cpptools/issues/11326 , in that both appear to involve identical IntelliSense configurations between 1.16 and 1.17, and the errors reported don't seem to include errors regarding headers that could not be found.  That would seem to suggest the issue is with some code that is not being parsed by the IntelliSense parse correctly, impacting subsequent code. If you can isolate this into an example you can send us, that could be very useful to us to investigate further and validate a fix.

**Comment by rsarrazin2** [comment]
@Colengms as I'm facing a very similar issue in a similar context (IntelliSense errors appearing on all versions >= 1.17.2 with vscode 1.81.1), I don't open a new issue. Only difference: I'm working on Ubuntu 20.04 @ WSL @ Windows 11.

I have created a [minimum viable example](https://github.com/rsarrazin2/cmake_workspace_for_vscode_c_cpp_extension) that shows the following IntelliSense errors (compilation is fine):
![image](https://github.com/microsoft/vscode-cpptools/assets/108058522/9d96c815-1bb5-491c-831c-572d3d44c2a7)

They don't appear if I downgrade to 1.16.3. I hope this minimal example helps (and is actually related to #11326 and #11351). If the access and/or the build cause issues, don't hesitate to come back.

**Comment by Colengms** [comment]
Hi @rsarrazin2 .  Thanks for reporting this.  We're aware of the issue and already have an internal bug for it (1839628).  It doesn't appear to be the same as the issue reported in this thread.  You're welcome to create a new GitHub issue to track it.
