### ISSUE TITLE
Need to validate TypeScript types returned from VS Code before passing them to native process

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#11375]
The repro I'm aware of involves invalid entries in `files.associations`.  i.e.

```
	"files.associations": {
		"goodStringEntry": "cpp"
		"badBoolEntry": false
	}
```

If specified in a settings file, VS Code is giving us the same content, despite that it doesn't match what VS Code itself expects.  Sending this in our LSP initialization message causes it to fail.  The native JSON deserializer expects `files.associations` entries to be strings.  The mismatch causes the deserializer to reject the request, preventing the initialization message from being processed.  Lack of proper initialization causes subsequent messages to fail, triggering crashes due to unexpected state such as lack of any entry in the list of workspace folders (at least 1 is always expected, even in single file mode).

Any values that we received from VS Code (at least from user-editable settings) that we include in LSP JSONs messages to the native process, should first go through some sort of type validation.

**Comment by sean-mcmanus** [comment]
Yeah, I saw a user report of this scenario at https://github.com/microsoft/vscode-cpptools/issues/11192#issuecomment-1689172499 , but the logging shows `workbench.desktop.main.js:sourcemap:620  WARN Ignoring configured 'files.associations' for 'editor.trimAutoWhitespace' because its type is not a string but 'boolean'`, which implies that VS Code maybe handling this for us? I don't remember reproing a cpptools failure when using that files.associations.

**Comment by Colengms** [comment]
Should be addressed by: https://github.com/microsoft/vscode/issues/125422  (Some day)

**Comment by sean-mcmanus** [comment]
Another crash case is https://github.com/microsoft/vscode-cpptools/issues/11426

**Comment by Colengms** [comment]
Resolving this as fixed as it refers to "before passing them to native process", though the issue has actually been addressed on the native side.  There is still more potential work here to validate settings values read and used specifically on the TypeScript side.
