### ISSUE TITLE
Add function name for Other References

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-cpptools#11392]
Type: <b>Feature Request</b>

 please add

-     function names
-     up-down buttons
    to c/c++ other references, same way as Eclipse has it:
![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/359b0c81-8b51-45b2-92b9-d4dd368c3373)

currently  looking:
![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/8c5f8b4b-484f-490d-9cdc-aa2b5cb76206)

Extension version: 1.17.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by Colengms** [comment]
Hi @mrx23dot .  Thanks for your feature request. We'll add it to the backlog for consideration.

**Comment by sean-mcmanus** [comment]
@mrx23dot We do not have control over the main/confirmed references panel -- someone would have to file a feature request on VS Code itself. We previously did implement our own references view for confirmed references, but then switched to use the VS Code one, I think since that's what the VS Code team recommended.

It sounds like you might be suggesting another change in behavior in regards to function declarations being omitted from references? That would be better tracked as a separate feature request.
