### ISSUE TITLE
Syntax Highlighting disappears after removing space between lamda return type and body

### ISSUE THREAD

**Issue by GrubbyHalo** [microsoft/vscode-cpptools#11406]
### Environment

- OS and Version: Linux x64 6.4.11-arch2-1
- VS Code Version:  1.81.1
- C/C++ Extension Version: v1.17.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Syntax Highlighting disappears after removing space between a lamda explicit return type and body

1. Type out some lambda. e.g.  `
    auto ml=[]()->void{
        std::cout<<"I am alive"<<std::endl;
    };`
2. Notice that all code below it has syntax highlighting removed.
3. Add a space between the return type and body. 
4. Notice that all syntax highlighting has returned.

Expected behavior:
For Syntax Highlighting to work regardless of the whitespace formatting.

https://github.com/microsoft/vscode-cpptools/assets/3902125/26d2a43c-b86b-43ab-82d3-451ba9c11403

### Configuration and Logs

```shell
-------- Diagnostics - 9/5/2023, 12:26:46 PM
Version: 1.17.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/garf/dev/retail_dynamics/logger/led_server/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compilerPathInCppPropertiesJson": "/usr/bin/clang",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "/home/garf/dev/retail_dynamics/logger/led_server/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/garf/dev/retail_dynamics/logger/led_server/thrift_rpc",
        "/home/garf/dev/retail_dynamics/logger/led_server/src"
    ],
    "compilerPath": "/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        " -std=c++11 -Wall -Wno-long-long -pedantic -Wno-reorder -g"
    ]
}
cpptools version (native): 1.17.5.0
Translation Unit Mappings:
[ /home/garf/dev/retail_dynamics/logger/led_server/src/led_service_worker.cpp ]:
    /home/garf/dev/retail_dynamics/logger/led_server/src/led_service_worker.cpp
Translation Unit Configurations:
[ /home/garf/dev/retail_dynamics/logger/led_server/src/led_service_worker.cpp ]:
    Process ID: 33037
    Memory Usage: 153 MB
    Compiler Path: /usr/bin/c++
    Includes:
        /usr/include/c++/13.2.1
        /usr/include/c++/13.2.1/x86_64-pc-linux-gnu
        /usr/include/c++/13.2.1/backward
        /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include
        /usr/local/include
        /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed
        /usr/include
    Standard Version: c++11
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=130201
Total Memory Usage: 153 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 74816
Number of files parsed: 7263
```

**Comment by Colengms** [comment]
Hi @GrubbyHalo .  I can repro the issue.  Though, it appears to be an issue with syntax highlighting, as you suggested, which is not actually provided by the C/C++ Extension.  That is provided by VS Code itself.  (The textmate grammer is contributed by the repo here: https://github.com/jeff-hykin/better-cpp-syntax )  I'd suggest opening an issue there.

There is a command in VS Code: `Developer: Inspect Editor Tokens and Scope`.  Running that command and clicking on text will reveal whether the current colorization for that text is coming from VS Code ('textmate scope'), or from the C/C++ Extension ('symantic token type')

In your case, it would appear that the code is being incorrectly colorized without the space, leading to the "I am alive" string (and sometimes the whole line?) being interpreted as the syntax token "storage.type.return-type.lambda.cpp" instead of "string.quoted.double.cpp" (etc) (with the space).  That would indeed appear to be an issue with syntax highlighting and not the C/C++ Extension's semantic token provider.

Could you open an issue in the better-cpp-syntax repo?  Closing this one as external.

**Comment by GrubbyHalo** [comment]
> Could you open an issue in the better-cpp-syntax repo? Closing this one as external.

Will do. Thanks.
