### ISSUE TITLE
Add possibility to pause parser

### ISSUE THREAD

**Issue by devlay** [microsoft/vscode-cpptools#1141]
Feature Request - Add possibility to pause parser. It can at times be inconvenient that VSCode is using system resources for parsing code. For example, it would be great if one could switch between branches without the parser beginning to indexing the code after each checkout.

**Comment by bobbrow** [comment]
Thank you for the feedback. I'm putting it on the backlog.

**Comment by MathiasMagnus** [comment]
While I think that complicating the UI for such a rare corner case might be an anti-feature, perhaps the info icon of the parser being used (the flame icon), could be clickable, in which case it could turn into crossed-out flame, or a pause icon.

**Comment by bobbrow** [comment]
It actually is clickable starting in 0.14.1.  We don't have a lot of options for what the icon looks like since it's actually a sort of emoji (we can't put an image there right now because VS Code only allows text).  We considered changing the color but didn't end up doing it.  For now all we do is update the tooltip when you hover over.

**Comment by bobbrow** [comment]
And actually, this issue should be closed since we did add the feature in 0.14.1.
