### ISSUE TITLE
Default build task command doesn't support punctuation in path. And default cppbuild is useless.

### ISSUE THREAD

**Issue by benben233** [microsoft/vscode-cpptools#11410]
### Feature Request

C/C++ extension version: 1.17.5
For example, if I put g++.exe under the folder "(test)" the default build task would be` "command": "C:\\(test)\\mingw64\\bin\\g++.exe" ` which can not run, it should be` "\"C:\\(test)\\mingw64\\bin\\g++.exe\""`

And it has detected task C/C++: cpp.exe build and debug active file, But cpp.exe is a preprocessor that replaces macros etc. which cannot run and debug by default.

**Comment by Colengms** [comment]
Hi @benben233 .  I'm not sure I understand why the contents of `C:\(test)\mingw64\bin\g++.exe` would require escaping in order to be processed correctly on a command line on Windows.  Assuming you're referring to use of a path that does include some text that would be misinterpreted by a shell, perhaps this is the same issue as https://github.com/microsoft/vscode-cpptools/issues/11422 ?
