### ISSUE TITLE
Build command ignores puncutations in source path

### ISSUE THREAD

**Issue by shashwatrathod** [microsoft/vscode-cpptools#11422]
### Environment

- OS and Version: Windows 11 with WSL 2 running Ubuntu 20.04.4
- VS Code Version: 1.81.1
- C/C++ Extension Version: 1.17.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
If the source path contains punctuation, the extension's build command ignores the punctuation in that path. Since the entered file path doesn't exist a 'No such file or directory' error is thrown. 

Steps to reproduce:
1. Create a new directory `Sept'23` (Notice the `'`).
2. Create a new `.cpp` file inside this directory (`helloworld.cpp`)
3. Try to trigger the build using the 'Run' button on the top-right corner of VSCode's nav bar.

The build will fail and you should see a 'No such file or directory' error in the terminal.

Expected behavior:
The build command uses the source path `/path/to/Sept23/helloworld.cpp` instead of `/path/to/Sept'23/helloworld.cpp` due to which it fails. The punctuation should have been taken into account.

### Configuration and Logs

```shell
{
  "configurations": [
    {
      "name": "Linux",
      "includePath": ["${workspaceFolder}/**"],
      "defines": [],
      "compilerPath": "/usr/bin/g++",
      "cStandard": "c17",
      "cppStandard": "gnu++14",
      "intelliSenseMode": "linux-gcc-x64"
    }
  ],
  "version": 4
}
```

### Additional context

Here is part of the terminal output:
```
Starting build...
/usr/bin/g++ -fdiagnostics-color=always -g /mnt/d/Shashwat/Fall'23/main.cpp -o /mnt/d/Shashwat/Fall'23/main
g++: error: /mnt/d/Shashwat/Fall'23/main.cpp -o /mnt/d/Shashwat/Fall'23/main: No such file or directory
g++: fatal error: no input files
compilation terminated.

Build finished with error(s).

 *  The terminal process failed to launch (exit code: -1). 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

**Comment by Colengms** [comment]
Hi @shashwatrathod .  Thanks for reporting this.  It looks like this path is not properly escaped to account for shell command-line special characters before being used in a shell command line.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.2

**Comment by Colengms** [comment]
Hi @shashwatrathod .  With 1.19.5, we're aligning the behavior of `args` and `command` fields in `tasks.json` with the behavior of VS Code's `shell` task type, which is documented [here](https://code.visualstudio.com/docs/editor/tasks).  When upgrading to 1.19.5, I believe you'll need to modify the generated `tasks.json` to provide an explicit `quoting` behavior, as described in that documentation.

Aligning this behavior with VS Code's default task type should provide a consistent user experience, and allow us to drive any shortcoming of that approach as issues with VS Code itself, and not behavior specific to the extension.  If the new behavior turns out to be problematic for you, I'd suggest following up with an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).
