### ISSUE TITLE
Is there a way to reuse the existing database?

### ISSUE THREAD

**Issue by xulion** [microsoft/vscode-cpptools#1172]
It seems every time when I start the code the extension is trying to regenerate the database (the code project I'm browsing is huge, the database generated is over 500M). Even after I set the databaseFilename within c_cpp_properties.json it still regenerate everything when reopen. Is there a setting allow me to reuse the existing db?

My version info:
code: 1.17.2
cpp extension version: 0.14.0

**Comment by jophippe** [comment]
The database should automatically be reused, although we still have to rescan all the directories to make sure our database is up to date. To check if the database is being recreated, go to settings and change the C_Cpp.loggingLevel to "Information". Reload VS Code, and look for the message "Warning: Database safety check failed. Recreating database". If you see this message, then you're running into a known issue where our process gets killed by VS Code before we mark the database as safe to write to, so we have to remake it. If you don't see that message, then then what it's actually doing is searching your directories for file changes, not recreating the database. There's nothing we can do about the time spent searching the folders, although if you don't want all the folders searched, you edit the browse.path property in the c_cpp_properties.json file to point towards specific folders you want searched, rather than the entire workspace root. Note that browse.path paths are searched recursively, unless you add a /* to the end of the path.

**Comment by xulion** [comment]
Thanks. Where can I find the log file? I'm using Linux and seems [Enabling logging.md](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) does not really tell where to find it.
It might fall into the situation you mentioned. This time after it finished build the database I closed the code after wait for a while, seems this time the db file is still there (last time the folder size went to almost 0).

**Comment by jophippe** [comment]
The logging should be sent to the Output window. If you don't see it there, click on the dropdown box on the right side of the Output window and there should be a C/C++ option you can click on to see the logging. That database safety check failed message should be near the top of the log, before the folders to index list

**Comment by sean-mcmanus** [comment]
With 0.14.0, we have to abort processing within 1 second or the database will be regenerated. Our next update will increase this to 5 seconds, so the database should never reset (unless there's some other bug).

**Comment by xulion** [comment]
@jophippe I can see it now. This time it's not resetting the datatbase. I think it might because the database is not done yet when I closed the project.

@sean-mcmanus Thanks for clarification!
