### ISSUE TITLE
Support CMake preset version 6 and above

### ISSUE THREAD

**Issue by nhbusch** [microsoft/vscode-cpptools#11863]
### Feature Request

Currently, it seems parsing a CMake preset file using fields introduced in version 6 and above, notably workflow and package presets, fails resulting in not recognizing any valid configure and build presets.

It would be great if this extension would support preset schema versions 6 and above or at least ignore any fields that were introduced in a version later than the one supported by this extension It would be even greater if workflow and package presets were supported (if it makes sense to map a workflow preset to the way this extension handles configure and build steps/targets).

**Comment by bobbrow** [comment]
Hello @nhbusch,
Thank you for your feedback. I believe this issue is tracked by https://github.com/microsoft/vscode-cmake-tools/issues/2871, so we will close as a duplicate instead of moving it over to the CMake Tools repository.  In the meantime, you should be able to get past the unsupported elements of your presets by enabling the `cmake.allowUnsupportedPresetsVersions` setting.
