### ISSUE TITLE
The C/C++ extension includes native binaries.  When installed via the marketplace UI in VS Code, the correct native binaries should be included. If incompatible binaries were detected and the C/C++ extension had been installed via the marketplace UI in VS Code, please report the issue.

### ISSUE THREAD

**Issue by Davejavu4u** [microsoft/vscode-cpptools#11895]
Type: <b>Bug</b>

Start VS Code on M1 Macbook Pro

Extension version: 1.18.5
VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|92, 194, 204|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id f924a571-bc93-4db2-95f6-9e9885036643|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by bobbrow** [comment]
@Colengms is this the installation issue you were talking about yesterday?

**Comment by sean-mcmanus** [comment]
@Davejavu4u Can you provide more details? I'm not understanding (maybe others on my team do). Is the Mac x64 vsix getting installed? Does a warning/error popup appear?

**Comment by bobbrow** [comment]
> @bobbrow I thought Colen was talking about Windows arm64 versus x64.

Yes, but I thought mac arm64 vs x64 would be almost the same issue.

**Comment by Colengms** [comment]
Hi @Davejavu4u . I believe the text you provided in the title of this issue was copied from the contents of a document opened when clicking on "More Info..." after receiving an error message about having installed the C/C++ extension for a mismatching architecture. In that document, if you had clicked on the "[please report the issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md)" link, it would have navigated you directly to create a New Issue in the VS Code repo.  If you had installed via the VS Code in-app marketplace UI, it would be a VS Code marketplace issue that resulted in the wrong version of the extension being installed.  Can you confirm if that's what you encountered? If so, that's not something we can address here in the context of the extension itself. It would need to be reported to VS Code folks directly.
