### ISSUE TITLE
Add support for multi-byte characters in Doxygen comments

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11910]
Doxygen comments should render the below input:

`/// @param P\uAB701, P\uAB992 D\uAB9D3\uAB7D00`

**Comment by Colengms** [comment]
Is there documentation to back this up?  I'm not able to find anything in Doxygen specs that suggests these should be interpreted in any way other than exactly as they are.  The `\u` syntax is specific to C++ string literals, not comments.  Instead of encoding multi-byte the characters this way, I don't believe there is any reason they can't be specified directly, provided the source file supports encoding them (i.e. UTF-8).

Maybe someone is asking that we interpret this text the same way some other particular documentation generator does, unrelated to the spec?  If so, this would seem to be a feature request / enhancement, and not a bug.  If there is more to the story, it'd be good to include that in the issue.  :)
