### ISSUE TITLE
externalConsole on windows doesnt launch/work anymore on vscode 1.86

### ISSUE THREAD

**Issue by iAroc** [microsoft/vscode-cpptools#11931]
### Environment

- OS and Version: Win11
- VS Code Version: 1.86 (it works fine on 1.85)
- C/C++ Extension Version: 1.18.5
- If using SSH remote, specify OS of remote machine: -

### Bug Summary and Steps to Reproduce

Bug Summary:
External Console cannot be open'd anymore. 
Had an Issue for this on the vscode repo, and they sent me here.

https://github.com/microsoft/vscode/issues/204073

### Configuration and Logs

```shell
-
```

**Comment by WardenGnaw** [comment]
@iAroc Sorry, I will have to send this back to VS Code because I believe it is an error on their side and has caused the externalTerminal case to regress. 

This comment explains the issue https://github.com/microsoft/vscode/issues/204039#issuecomment-1923458804
I'll be working with the VS Code team on that issue ticket to resolve this.

**Comment by Wolfleader101** [comment]
This is on the vs team not you guys.
