### ISSUE TITLE
Allow configuring the shell environment (in cppbuild tasks as well as compiler queries)

### ISSUE THREAD

**Issue by deribaucourt** [microsoft/vscode-cpptools#11994]
### Feature Request

Hello

Many VSCode extensions that run shell commands provide an option to configure the shell environment.
The configuration is usually a dictionnary of variables/values:
```json
{
    "PATH": "{env:PATH}:/opt/arm64-linux"
}
```
As illustrated in this example, it can be useful to add the directory where an external compiler is defined. In this case, I cannot use the absolute path in the "compilerPath" settings. I'm using a generated `compile_commands.json` that expects the compiler to be in the $PATH.

I tried editing the various "terminal.integrated" settings, but none take effect on the compiler commands spawned by vscode-cpptools. It seems to rely on child_process.spawn which doesn't go through the VSCode terminals.

Would it be possible to add an option to edit the shell environment, notably the $PATH when vscode-cpptools is launching the compiler shell commands?

Another alternative that would work in my scenario would be to fall back to the compilerPath with absolute path if the on specified in compiler_commands.json is not found.

**Comment by Colengms** [comment]
Hi @deribaucourt .  I believe with the latest C/C++ extension prerelease (1.19.3 - which should be fully released shortly), it's currently possible to accomplish what you suggested as an alternative.  If using a `compile_commands.json` file, and a `compilerPath` is set in your `c_cpp_properties.json` file, it should be used instead of the compiler specified in `compile_commands.json`, yet the arguments provided in `compile_commands.json` should continue to used. Note that we do plan to change this behavior in the future, to provide a separate setting for this purpose, as overloading the `compilerPath` field may prevent the base configuration from being useful as a fallback for files not found in `compile_commands.json`.  Some discussion of that issue is here: https://github.com/microsoft/vscode-cpptools/issues/11889

We can also keep this request open to track providing a way to override the PATH and/or other environment variables in `cppbuild` tasks.

**Comment by deribaucourt** [comment]
Thanks for answering so quickly,
This `compilerPath` does perfectly fulfill my need! 
Awesome, thank you.
