### ISSUE TITLE
My program compiles fine but I get the following error in vscode only "identifier "K32GetProcessMemoryInfo" is undefined"

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/vscode-cpptools#12031]
### Environment

- OS and Version:  Windows 11
- VS Code Version: 1.85.2
- C/C++ Extension Version: 1.19.4
****

### Bug Summary and Steps to Reproduce

Write the following c++ code

``` c++
#include <Psapi.h>

int get_app_ram_usage() {
    HANDLE current_process =
        OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
    GetProcessMemoryInfo(current_process, &memory_counters, sizeof(memory_counters));
    return memory_counters.WorkingSetSize / 1024 / 1024;
}
```

Compile this code using LLVM clang and see it works fine.

Now vscode should report the error "identifier "K32GetProcessMemoryInfo" is undefined"

### Configuration and Logs

```shell
"C_Cpp.default.cppStandard": "c++20",
  "C_Cpp.suggestSnippets": false,
  "C_Cpp.default.forcedInclude": [
    "src/pch.hpp"
  ],
  "C_Cpp.default.includePath": [
    "lib/windows/include",
    "include",
    "."
  ],
  "C_Cpp.default.compilerPath": "C:\\Program Files\\LLVM\\bin\\clang++.exe",
```

**Comment by Colengms** [comment]
Hi @dortamiguel . Using the configuration you provided here (though, without files you did not provide), I get working IntelliSense and no squiggles using your example code (provided I also add `#include <Windows.h>` and the missing: `PROCESS_MEMORY_COUNTERS memory_counters;`).

I think we would need more information to assist you. Can you provide a self-contained example that reproduces the issue?

Also, I'd suggest always prefixing include paths that are within your workspace folder with `${workspaceFolder}/` rather than using relative paths.  That would rule out these paths ever being interpreted incorrectly if evaluated while your workspace folder is not the current working directory.

**Comment by felsokning** [comment]
I believe this is expected behavior, defined in the documentation:

>If `PSAPI_VERSION` is 2 or greater, this function is defined as K32GetProcessMemoryInfo in Psapi.h and exported in Kernel32.lib and Kernel32.dll. If `PSAPI_VERSION` is 1, this function is defined as GetProcessMemoryInfo in Psapi.h and exported in Psapi.lib and Psapi.dll as a wrapper that calls K32GetProcessMemoryInfo.

See [here](https://learn.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getprocessmemoryinfo).
