### ISSUE TITLE
C++ debugger not working properly since I updated C/C++ extension to v1.19.8

### ISSUE THREAD

**Issue by TimeMachine777** [microsoft/vscode-cpptools#12110]
Type: <b>Bug</b>

-> This is my directory structure:
D:\Coding\Programs\Competitive Coding & Practice\Codeforces\932\B.cpp

-> I tried to run the c++ debugger on this file (B.cpp) as I usually do but today this error popped up:
Executing task: C/C++: g++.exe build active file 

Starting build...
cmd /c "chcp 65001>nul && "E:\Compiler mysys2\ucrt64\bin\g++.exe" -fdiagnostics-color=always -g "D:\Coding\Programs\Competitive Coding & Practice\Codeforces\932\B.cpp" -o "D:\Coding\Programs\Competitive Coding & Practice\Codeforces\932\B.exe""
E:/Compiler mysys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find D:\Coding\Programs\Competitive: No such file or directory
E:/Compiler mysys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Coding: No such file or directory
collect2.exe: error: ld returned 1 exit status
The filename, directory name, or volume label syntax is incorrect.
The system cannot find the path specified.

Build finished with error(s).

-> This never happens and I use these files daily. It was working fine till yesterday, and yesterday night I updated the C/C++ extension to v1.19.8 and from today this started to happen.
![image](https://github.com/microsoft/vscode-cpptools/assets/133058473/9d87fc2f-2d7a-4f89-bc50-8263dc88bb2c)

Extension version: 1.19.4
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.92GB (5.98GB free)|
|Process Argv|--crash-reporter-id 8faec4a9-c3a8-4e71-9818-7cdd0ba8240f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30986170
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30991134
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30958156
dsvsc020:30976470
666c4381:30973075
gee8j676:30988843

```

</details>

**Comment by browntarik** [comment]
It looks like the command line is incorrectly parsing your file path because it has a space in it. It says "cannot find D:\Coding\Programs\Competitive: No such file or directory" which leads me to believe that quote escaping was incorrectly applied to your command line. 

Could you provide a copy of your tasks.json file? The behavior for shell quoting was recently updated to reflect the general vs code behavior: https://code.visualstudio.com/Docs/editor/tasks and could be causing the issue.

A quick work around would be to rename your folders to eliminate spaces from the directory names.

**Comment by TimeMachine777** [comment]
Sure, here is the copy of tasks.json 
[tasks.json](https://github.com/microsoft/vscode-cpptools/files/14639618/tasks.json)

**Comment by Colengms** [comment]
Hi @TimeMachine777 . As of 1.19.5, the C/C++ Extension will process arguments in a `cppbuild` task in the same way as VS Code processes arguments in a `shell` task.  The code involved from VS Code is replicated in the C/C++ Extension, so the behavior should be identical.

According to: https://code.visualstudio.com/docs/editor/tasks

> If a command and arguments are provided, the task system will use single quotes if the command or arguments contain spaces. For cmd.exe, double quotes are used. 

In your case, spaces seem to be handled correctly (as it finds your compiler fine, despite the space in that path. The nested set of quotes in the call to `cmd /c` appears unusual, but is by-design).  But you appear to have a path with a `&` in it, which is also a special character when used as part of a `cmd.exe` command line. It looks like VS Code's quoting approach does not handle this by default.  It looks like some of your arguments may need to be updated to explicitly specifying the quoting/escaping to use, like so:

```
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                {
                  "value": "${file}",
                  "quoting": "escape"
                },
                "-o",
                {
                  "value": "${fileDirname}\\${fileBasenameNoExtension}.exe"
                  "quoting": "escape"
                }
            ],
```

In fact, we should probably do this by default, when generating a task.json.

Unfortunately, VS Code does not appear to properly support "escape" (or a proper "strong") quoting here, for `cmd.exe`.  This functionality appears to only be robust for Linux, but lacking for Windows.  If you were to change your task to a `shell` task instead of a `cppbuild` task, I believe you would see similar behavior.

One reason we switched to using the same implementation here for args as VS Code was to drive the complex issues that arise here as VS Code issues rather than specific to the C/C++ Extension.  As such, I believe what you're seeing here is effectively a VS Code bug. Would you like to open an issue to track this, in [the VS Code repo](https://github.com/microsoft/vscode-cpptools/issues) ?

**Comment by TimeMachine777** [comment]
Yes, opening an issue and fixing this bug would be great. 
But I want to point out that , when I reported this issue after that I tried rolling back to previous versions of this extension and as I reached v1.19.4 that debugging started working just fine like before. 
I think that the recent update has to do something with it as I have been using the same directory structure since nearly 2 years, and I never faced an issue. 
The only time I used to face an issue while debugging was when the file on which I was going to run the debugger had a whitespace char in it. So I have been avoiding that, but having a whitespace character in the folders enclosing the file have never caused an issue before.

**Comment by Colengms** [comment]
Hi @TimeMachine777 .  To clarify, the current behavior (that is works exactly as `shell` tasks do) is by-design for the C/C++ Extension.  Could you confirm that the same issue occurs with your command line if you change the task type from `cppbuild` to `shell`?  If so, we'll need to pursue this as a VS Code bug,within the context of the behavior of a `shell` task.

**Comment by TimeMachine777** [comment]
I changed the task type to `shell` and now everything is working as before.

**Comment by browntarik** [comment]
I will now close this issue, but it will be available for future reference.
