### ISSUE TITLE
Apparently, wrong code execution

### ISSUE THREAD

**Issue by ukaluzhny** [microsoft/vscode-cpptools#12436]
### Environment

- OS and Version: Windows_NT x64 10.0.19045
- VS Code Version: 1.90.2 (system setup)
 Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
- C/C++ Extension Version: 
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33521 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Compiler Passes:
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\cl.exe:        Version 19.39.33521.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\c1.dll:        Version 19.39.33521.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\c1xx.dll:      Version 19.39.33521.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\c2.dll:        Version 19.39.33521.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\c1xx.dll:      Version 19.39.33521.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\link.exe:      Version 14.39.33521.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\mspdb140.dll:  Version 14.39.33521.0
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\1033\clui.dll: Version 19.39.33521.0
```

### Bug Summary and Steps to Reproduce

Bug Summary:
The following code:
``` C
void main() {
    unsigned long long int i = 1ull << 33;
    unsigned short int j = 1 << 15;
    printf("%llx+%x=%llx\n", i, j << 16, i + (j << 16));
}
```

gives the following output (cl.exe build):
`200000000+80000000=180000000`

Steps to reproduce:
```json
{
        "command": "cl.exe",
         "args": [
             "/Zi",
             "/EHsc",
             "/nologo",
             "/Fe${fileDirname}\\${fileBasenameNoExtension}.exe",
               "${file}"
          ]
}
```

Expected behavior:
Of course, the correct output would be 
`200000000+80000000=280000000`

### Configuration and Logs

```shell
NA
```

### Other Extensions

NA

### Additional context

NA

**Comment by Colengms** [comment]
Hi @ukaluzhny .  I believe the issue you are seeing is by design (and related to your sample code and the compiler, not the C/C++ Extension for VS Code).

The issue is specifically with `j << 16`.  The result of this operation winds up being negative.  As such, what you have printed is technically correct, provided `0x80000000` is recognized as having its sign bit set, making the addition operation effectively subtraction.

When you perform certain operations with a type smaller than an int, the compiler will promote the operand prior to the operation.  In your case, the value of your operand will fit in a signed int.  Also, bit shifting is not a sign-aware operation, so the compiler does not assume the result must be unsigned.  (Historically, it's been important to be careful when mixing binary and arithmetic operations.  There may actually still be some systems out there for which arithmetic operations are not twos-compliment.)

I see the same behavior with gcc and clang, as well as MSVC.  

To get the behavior you probably expect, I'd suggest casting the operand to a sufficiently large unsigned int type.

I suppose there would seem to be a good argument that int promotions in the context of bit-shift operations should retain the unsigned-ness of the left operand.  But that's a debate you may need to take up with the language standard committee. :)
