### ISSUE TITLE
Configurable C_cpp_properties.json Location

### ISSUE THREAD

**Issue by hacantorcooke** [microsoft/vscode-cpptools#12494]
### Feature Request

Allow a workspace setting to point to the c_cpp_properties.json rather than requiring it to always live in the root of the folder. Or allow the entire c_cpp_properties.json to be embedded in the workspace JSON

Maybe this is already possible and I missed it?

**Comment by sean-mcmanus** [comment]
@hacantorcooke We have C_Cpp.default.* settings that correspond to the properties in c_cpp_properties.json -- is using those sufficient for you?

**Comment by hacantorcooke** [comment]
@sean-mcmanus Default settings don't include `configurations` so doesn't work for me. Basically looking for a way to get configurations to be specific to the workspace (or let the workspace point to the configurations).

Letting it live in the workspace JSON also works.

I see there's "configurationProvider" which could maybe work if it could be told to point to a JSON with the configs? It seems like it has to be an extension currently

**Comment by johndv7** [comment]
We work on a team, and it would be extremely helpful to have workspace information follow the workspace, instead of each developer having to individually setup their include paths, compilers, etc. When you have 20 projects, with different compilers and configurations, it's a real problem keeping everything working well.

There seems to be a lot of resistance to this, but I don't really understand why.

I'm not sure how the C_Cpp.default.* file would help. Perhaps a lot of us just don't understand how it's intended to be used?
