### ISSUE TITLE
The extension takes CPUs to 100%, even the extension is disabled.

### ISSUE THREAD

**Issue by LarryDong** [microsoft/vscode-cpptools#12805]
### Environment

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.94.0
- C/C++ Extension Version:  1.21.6, and 1.22
- If using SSH remote, specify OS of remote machine: No.

### Bug Summary and Steps to Reproduce

Bug Summary:
When C/C++ IntelliSense is disabled, the vscode can auto-complete my class's function or class's member in my cpp file, but cannot jump to the header. 

But when I enabled C/C++, the auto-complete fails.
I also notice that the vscode state bar, the intelliSense is always "updating", and `top` in terminal shows that this extension takes several CPUs to 100%.

![image](https://github.com/user-attachments/assets/c21be9ea-6c69-417d-b474-628a83018e5e)
![image](https://github.com/user-attachments/assets/dab5c156-622d-4c01-a290-d061f193d865)

The CPU cannot be released if I just disable the extension. Only close the vscode can stop the CPU usage.

### Configuration and Logs

```shell
{
  "configurations": [
    { 
      "name": "ROS",
      "browse": {
        "databaseFilename": "${default}",
        "limitSymbolsToIncludedHeaders": false
      },
      "includePath": [
        "/home/larry/voxel_map_ws/src/VoxelMap/include/**",
        "/home/larry/voxel_map_ws/src/VoxelMap/src/**",
        "${workspaceFolder}/**",
        "/home/larry/ros_catkin_ws/install_isolated/**",
        "/usr/include/eigen3/**",
        "/usr/include/**"
      ],
      
      "defines": [],
      "compilerPath": "/usr/bin/gcc",
      "cStandard": "c11",
      "cppStandard": "c++14",
      "intelliSenseMode": "linux-gcc-x64"
    }
  ],
  "version": 4
}
```

### Other Extensions

No. I disabled all other extension.

**Comment by sean-mcmanus** [comment]
@LarryDong You need to click the Restart extensions button to cause VS Code to kill the cpptools process.

![image](https://github.com/user-attachments/assets/7efccd22-a2ab-4328-bbb8-b54f2c175236)

The parsing of the TU can potentially take a really long time if the TU is not configured correctly. Your usage of "**" recursive includes may be causing the wrong folder to be placed first, which can lead to errors and restarting of our IntelliSense parser. If you run C/C++: Log Diagnostics you can see what includePaths are being used. If you can't compile your code using that set of include paths then your project is probably misconfigured. This misconfiguration is likely to occur if your workspace folders have files with the same name as a system include, since it will cause your workspace file (e.g. string) to be selected before the gcc string file.

You may want to try using a smaller file first and with less includes to see if that finishes parsing without any IntelliSense errors.

**Comment by LarryDong** [comment]
Hi, thanks for your advice. I removed some **, and it works now.
