### ISSUE TITLE
The newest version can not recursive parse file included by the #include file

### ISSUE THREAD

**Issue by aaa45190** [microsoft/vscode-cpptools#12878]
### Environment

- OS and Version:  win11
- VS Code Version:  1.9.42
- C/C++ Extension Version: 1.22.10
- If using SSH remote, specify OS of remote machine: centos8

### Bug Summary and Steps to Reproduce

Bug Summary:
There are server files: `fa.h, fb.h, fb.cc fc.h, fc.cc` 

fa.h:
```
class AA
{
};
```

fb.h:
```
#include "fa.h"

#define log(args...) LOG(AA, args..) 
```

fc.h:
```
#include "fb.h"
class C{
int logc();
};
```
fc.cc:
```
int C::logc()
{
   log("aaaa"); // ERROR REPORT HERE
}

```
The Report Error is c/c++(833), even the macro could be expanded. 
For same case, it works good in `C/C++ Extension Version: 1.21.6`, but in version 1.22.x will report error
Currently I already rollback to 1.21.6

### Configuration and Logs

the log can not provide

**Comment by sean-mcmanus** [comment]
@aaa45190 What is the definition of LOG or what can we use to for the repro?

**Comment by sean-mcmanus** [comment]
@aaa45190 Also, what compiler are you using? I'm guessing gcc or clang?

**Comment by sean-mcmanus** [comment]
@aaa45190 With `#define LOG(args...)` and gcc I'm not getting an error.

**Comment by aaa45190** [comment]
1. Log is just one of the demo and report more.

**Comment by aaa45190** [comment]
1. Log is just one of the demo and report more.

**Comment by aaa45190** [comment]
1. Log is just one of the demo and report more.
2. I tried C/C++: Reset IntelliSense Database, but error still exist. The  C/C++: Log Diagnostics also looks good.

**Comment by aaa45190** [comment]
Maybe I can provide another example to if it is useful.

**Comment by aaa45190** [comment]
I can provide another example to see if it's helpful
base.h
```
class Base {
virtual int fun1() { return 0; }
};
```
derived.h
```
#include “base.h”
class D: public Base {
      int fun1();
}
```
derived.c
```
#include “derived.h”
int D::fun1() { // Error Report Here: class "D" has no member "fun1" c/c++(833)
// something
return 0;
}
```

**Comment by schattenmann80** [comment]
I have a problem that is maybe releated, because if i downgrade to 1.21.6, like @aaa45190  did, it is gone.

I get the following error message: pointer or reference to incomplete type is not allowed C/C++(833)
But I directly include the file where the type is defined. I can open the file with "Go to Definition" without a problem.
And when I open the file, where the type is defined, than the error goes away.
But as soon as I close the file the error comes back. 

It looks like as if he does not find the inlcuded file. But the directory with the included file is specified "includePath".
Is there somewhere a log with the files he did find and added into the intellisense Database ?

I tried C/C++: Reset IntelliSense Database, but error still exist.

Environment

I',m using gcc.

    OS and Version: win11
    VS Code Version: 1.9.42
    C/C++ Extension Version: 1.22.10
    If using SSH remote, specify OS of remote machine: debian 12

**Comment by sean-mcmanus** [comment]
@aaa45190 The code you provided doesn't compile as written. It doesn't use the ASCII `\"` character for the include statement and it's missing a semicolon after the class definition, and the file extension is .c, which may cause it to be associated with C instead of C++ by default. When I fix those issues, I don't get any errors: 
![Image](https://github.com/user-attachments/assets/c24faaea-102a-4197-ae2c-4f85caf5fa0e)

@schattenmann80 Can you try running C/C++ Log Diagnostics when the error occurs and when the file with the type is opened and compare them? The TU used could be changing. Another thing to try is to set C_Cpp.intelliSenseCacheSize to 0 to make sure it's not an invalid cache bug. The TU could also be missing the type info if an include or define is incorrect. You may try running something like `g++ -std=c++20 -I<includes> -D<defines> -E -dD <file>` to generate a preprocessed file (where the -I and -D are what are shown in the log diagnostics results). Or are you able to provide a repro sample code?

**Comment by Telly-S** [comment]
> [@aaa45190](https://github.com/aaa45190) The code you provided doesn't compile as written. It doesn't use the ASCII `\"` character for the include statement and it's missing a semicolon after the class definition, and the file extension is .c, which may cause it to be associated with C instead of C++ by default. When I fix those issues, I don't get any errors: ![Image](https://github.com/user-attachments/assets/c24faaea-102a-4197-ae2c-4f85caf5fa0e)
> 
> [@schattenmann80](https://github.com/schattenmann80) Can you try running C/C++ Log Diagnostics when the error occurs and when the file with the type is opened and compare them? The TU used could be changing. Another thing to try is to set C_Cpp.intelliSenseCacheSize to 0 to make sure it's not an invalid cache bug. The TU could also be missing the type info if an include or define is incorrect. You may try running something like `g++ -std=c++20 -I<includes> -D<defines> -E -dD <file>` to generate a preprocessed file (where the -I and -D are what are shown in the log diagnostics results). Or are you able to provide a repro sample code?

I encountered a similar problem. I added `"includePath": ["${workspaceFolder}/**"]`  in `. vscode/c_cpp_properties.json` . But in fact, when I use the #include in my `. c` file, it can't find the header file, At the same time, I can't jump to the definition and  find the symbol in the outline. This situation only happened after I recently upgraded the version. 

environment:
Version: win11
VS Code Version: 1.9.42
C/C++ Extension Version: 1.22.10

**Comment by schattenmann80** [comment]
To set C_Cpp.intelliSenseCacheSize to 0 did not help.
I did run C/C++ Log Diagnostics but the only differents was that in
Translation Unit Configurations:
    ....
    Includes: ...
The order of the directory, where the missing include is, was different.

**Comment by schattenmann80** [comment]
If i run  C/C++ Log Diagnostics than the difference is 
In the good case:
    The include file is pressend in "Translation Unit Mappings:"
    The last line ist Number of files parsed: .... 
In the bad case:
    The line "Number of files parsed:.." is missing
    The following is insted there:
------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

But the missing include is not in include path issues.

**Comment by sean-mcmanus** [comment]
@schattenmann80 The missing include wouldn't necessarily need to be in the "include path issues" if one of those issues causes the wrong header to be used and then either parsing to fail catastrophically or for the include with the definition to be used. Is there any difference in the include paths that are logged for the TU? The translation unit mapping would only show the include file if the file were opened.

**Comment by schattenmann80** [comment]
"Is there any difference in the include paths that are logged for the TU? " Yes the order is different, but only from the directory where the missing include is inside. But only the order of this one directory everything else is the same.

**Comment by aaa45190** [comment]
@sean-mcmanus I tried the cache, it did not help. I also tried C/C++ Log Diagnostics and running compile command, they still did not help.

**Comment by sean-mcmanus** [comment]
@aaa45190 So you don't repro the issue with base.h/derived.h/derived.c with a small workspace? What does `["path_to_pro/base", "path_to_pro/derived"]` mean? Which property is that? includePath? Are you saying they're in different folders? Using C/C++: Log Diagnostics won't fix the issue, but it could show what source file is getting associated with base.h. They should be associated with the derived.c file and not some other file in your workspace. Also, are you sure all the files are getting processed as C++ and not C?
