### ISSUE TITLE
Error appeared after latest update on include files: cannot open source file "stdlib.h"

### ISSUE THREAD

**Issue by philave** [microsoft/vscode-cpptools#12896]
### Environment

- OS and Version: MS Win 10 Enterprise
- VS Code Version: 1.94.2 (user setup)
- C/C++ Extension Version: v1.22.10
- If using SSH remote, specify OS of remote machine: Oracle Linux 9.4

### Bug Summary and Steps to Reproduce

Almost each custom include file marked red with error: cannot open source file "stdlib.h". Of cause '/usr/include/' which contains stdlib.h is added to includePath. The problem appeared with the latest update. 

### Configuration and Logs

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/",
                "/usr/include/libxml2",
                "/usr/include/json-c"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "linux-gcc-x64",
            "compileCommands": "",
            "configurationProvider": "ms-vscode.cmake-tools",
            "forcedInclude": [
                "/usr/include/stdlib.h"
            ]
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
@philave You should remove the system includes from your include path and instead rely on the compiler to supply those with -isystem. You may be hitting bug https://github.com/microsoft/vscode-cpptools/issues/12842. If you run the C/C++: Log Diagnostics command you want to  make sure no system includes are in the normal includes list -- otherwise the ordering of system includes will be incorrect.
