### ISSUE TITLE
CMake Server vs. compile_commands.json

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vscode-cpptools#1303]
As part of a discussion regarding LaTeX reciving the same love and care of CMake as the C++ extension did, @bradking [has pointed out](https://www.mail-archive.com/cmake-developers@cmake.org/msg18327.html) that compile_commands.json was not intended to be used for tracking compiler invocations, but rather [CMake server mode](https://cmake.org/cmake/help/latest/manual/cmake-server.7.html) should be used for that, the feature driving big brother VS' CMake integration.

I wanted to ask the opinion of cpptools devs as well as @vector-of-bool to figure out a way of set an example to other language services as well in a way so that not every extension will have to run a CMake server of their own only to extract the information relevant to them.

Do you imagine that in this scenario cmake-tools is "only" the host to the CMake server instance and only provides hooks to the UI? Is it even possible for one extension to use the CMake Server of another extension? (I am not aware how extensions are able to communicate with each other.)

**Comment by bobbrow** [comment]
If an extension exports an API (which the CMake Tools extension does), then it is possible for another extension to consume that API.  We may choose to consume this API at some point, but regardless of the direction we take, we will continue to support compile_commands.json going forward since CMake is not the only tool capable of generating it - it simply makes it convenient.

In an ideal world, CMake would detect duplicate server instances and consolidate to conserve resources and protect against concurrent generate steps, or perhaps expose a way to query whether a server already exists so that it can be shared.

**Comment by MathiasMagnus** [comment]
Consuming that API would allow for functionality like automatic rebuild when an out-of-date target is debugged. Cpptools knows what the target being debugged is, but CMake knows whether it's out-of-date or not.

Also, how does the [VS Language Service Protocol](https://blogs.msdn.microsoft.com/visualstudio/2017/11/21/announcing-language-server-protocol-preview-release/) relate to cpptools? Does it mean that sometime in the future VS and Code C++ language services might share a common codebase?

**Comment by bobbrow** [comment]
VS and the VSCode extension already share a lot of common code.  I can't really comment on future plans for the VS C++ component though.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
