### ISSUE TITLE
Sugestions from IntelliSense doesn't help

### ISSUE THREAD

**Issue by johnfercher** [microsoft/vscode-cpptools#1331]
* Linux Mint 18.2
* Latest version of vscode from website
* Only have your extension installed

My IntelliSense isn't working properly, the suggestions are all the same. 

Example 1:
If I have a class called Car, with a public method called move. When I type . after an object car, the IntelliSense suggest a huge list of things ordered by methods name.

Example 2: 
When I type . after a variable of type std::string, the IntelliSense show the same huge list from example 1.

**Comment by michaelllh** [comment]
I have suffer the same problem .this is annoying!

**Comment by sean-mcmanus** [comment]
You must be falling back to the tag parser behavior due to missing include paths. You can view the Problems window to see which include paths are missing, possibly use code actions to automatically add the paths, or you can change the C_Cpp.intelliSenseEngineFallback to "Disabled". Are you able to get it to work now?

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
