### ISSUE TITLE
Show additional overloads for completion

### ISSUE THREAD

**Issue by Rakuyo007** [microsoft/vscode-cpptools#1360]
When I want to enter a function, intellisense will give me the name of function and simple description, I just want to show more descriptions, such as overload
like the function        float sin(float) with "+3 overload" below it,
Can show the other threes together?

**Comment by sean-mcmanus** [comment]
We show the overload text for hover and auto-completion. Our behavior matches what VS 2017 does. The individual overloads should be visible when you start entering in parameters via the signature help that appears. Showing all the overloads would cause the results to be slower and it doesn't seem like it'd be particularly valuable to show in most scenarios, although we could have users opt-in via a setting. I think most users would want us to add comments first.

**Comment by GeraldNDA** [comment]
I second this feature request.
JS and PHP (and probably others in VSCode) parse JSDoc/PHPDoc comments and show really meaningful descriptions on hover.
Examples: 
- Python (first picture) - https://marketplace.visualstudio.com/items?itemName=ms-python.python
- PHP (first 2 pictures and Hover section) - https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense
- JavaScript (2nd picture) - https://code.visualstudio.com/docs/languages/javascript
Maybe you could add a setting to support doc hints for CppDoc or Doxygen.

**Comment by sean-mcmanus** [comment]
@GeraldNDA It sounds like you're asking for https://github.com/Microsoft/vscode-cpptools/issues/399 , and not the feature @WellTai asked for.

**Comment by deitry** [comment]
It will be nice to have a key-bindable action to switch between different overloads description. Or all overloads could be displayed in Intellisense list, each with its own description, like it is implemented in QtCreator.

Anyway, it could be very useful feature, because you often want to check what you can pass to a function _before_ you start entering something in parameters.

**Comment by bobbrow** [comment]
We decided not to do this.  The only way to show multiple overloads in the completion list is to add all of them to the list.  This would result in N duplicate entries.  For auto-complete, we feel that this is overkill and doesn't align with the implementations of other language servers.  We will show the overloads after the `(` token is typed so that you can scroll through them and pick the right one to guide you while filling in the parameters.
