### ISSUE TITLE
Support for relative path for sources when gdb set-substitution is used

### ISSUE THREAD

**Issue by 0x00deaf** [microsoft/vscode-cpptools#1370]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.14.4-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vsc-material-theme|Equ|1.1.2
material-icon-theme|PKi|3.2.0
vscode-docker|Pet|0.0.22
code-settings-sync|Sha|2.8.7
jupyter|don|1.1.4
json-tools|eri|1.0.2
vscode-text-pastry|jkj|1.2.0
cppcheck|mat|0.2.1
vscode-clang|mit|0.2.2
hg|mrc|1.2.3
python|ms-|0.9.1
cpptools|ms-|0.14.5
autodocstring|njp|0.1.2
vscode-icons|rob|7.19.0
trailing-spaces|sha|0.2.11
vscode-hexdump|sle|1.6.0
change-case|wma|1.0.0

(2 theme extensions excluded)

---

When using gdb its quite often that path substitution is used that uses relative path instead of absolute path (e.g something like set path-substitution /workspace/cpp ./cpp)

This works in GDB but seems to be not working in visual studio. I would expect this to be resolved relatively to the workspace directory which is specified in debugger launch.json.

This would be expected behavior I suppose. Thanks.

**Comment by sean-mcmanus** [comment]
@pieandcakes I seem to recall you fixed a similar issue with paths not expanding?

**Comment by pieandcakes** [comment]
@sean-mcmanus this seems to be a bug for Visual Studio and not VS Code? @0x00deaf Can you comment? If this is for Visual Studio, please file it through the feedback option within Visual Studio. This `issues` page is for VS Code. 

If this is indeed for VS Code, please use `"sourceFileMap"` within your `launch.json` to configure your mapping.

Thanks

**Comment by lmapii** [comment]
I seem to have the same issue - in VS Code. I've put together a demo project including a description on GitHub: https://github.com/lmapii/vscode-gdb

Even a simple "back and forth" path is not resolved correctly and VS Code won't open the corresponding file anymore. I've put a full description into the repository: https://github.com/lmapii/vscode-gdb/blob/master/issue.md

Any help appreciated. I can't rely on the build-environment to be placed in a specific folder since it depends on the test environment or release/build environment, even Jenkins etc. might use a different setup. Hope it helps!

**EDIT:**
Using VS Code Version 1.19.1 (1.19.1) on mac OS V 10.13.2; used `launch.json`

**Comment by lmapii** [comment]
no news on that one ?

**Comment by pieandcakes** [comment]
@lmapii If your issue is that it can't open the source file, setting the sourceFileMap should help it resolve. If you want VSCode to resolve it on its own, you can verify that we get relative paths back from `gdb` by enabling `"logging": { "engineLogging": true, "trace": true, "traceResponse": true }` and seeing the stopping event that we fire and send back to VSCode. If this is a relative path, then the bug needs to go to [VSCode](https://github.com/microsoft/vscode) as they are not handing the relative path. 

the C++ debugAdapter uses sourceFileMappings to send a more complete path back to VS Code so it can find the source file to open.
