### ISSUE TITLE
C/C++ extension always ignore my My own clang-format config 

### ISSUE THREAD

**Issue by philong6297** [microsoft/vscode-cpptools#1390]
* Windows 10 Education, 10.0.16299 Build 16299
* VS Code version 1.19.1
* C/C++ extension version 0.14.5
* LVVM version: 5.0.1
* I tried both ways too use my own format :
Using:
 ``` json
  "C_Cpp.clang_format_path": "C:/Program Files/LLVM/bin/clang-format.exe",
    "C_Cpp.clang_format_style": "file",
    "[cpp]": {
        "editor.autoIndent": true,
    },
   "C_Cpp.clang_format_fallbackStyle": "{Language: Cpp,  BasedOnStyle: Chromium, AccessModifierOffset: 0, ...}", 
// ^ ... is for example, there are so many keys i cant list all of it.
```
Or set specifics parameters like this:
``` json
"C_Cpp.clang_format_path": "C:/Program Files/LLVM/bin/clang-format.exe",
    "C_Cpp.clang_format_style": "{Language: Cpp,  BasedOnStyle: Chromium, AccessModifierOffset: 0, ...}",
// ^... is for example, there are so many keys i cant list all of it.
    "[cpp]": {
        "editor.autoIndent": true,
    },
    "C_Cpp.clang_format_fallbackStyle": "{Language: Cpp,  BasedOnStyle: Chromium, AccessModifierOffset: 0, ....}",
// ^... is for example, there are so many keys i cant list all of it.
```
But none of them works.
I can only use default support styles from this extension like Chromium, Google, Visual Studio,...
* My current user settings:
```json
    "sublimeTextKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    //format and save options
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 5000,
    "editor.tabCompletion": true,
    "explorer.confirmDelete": false,
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Dracula Soft",
    "C_Cpp.clang_format_path": "C:/Program Files/LLVM/bin/clang-format.exe",
    "C_Cpp.clang_format_style": "file",
    "[cpp]": {
        "editor.autoIndent": true,
    },
    "C_Cpp.clang_format_fallbackStyle": "{Language: Cpp,  BasedOnStyle: Chromium,AccessModifierOffset: 0,...}",
// ^... is for example, there are so many keys i cant list all of it.
    "explorer.confirmDragAndDrop": false,
```
* Other extensions:
![extension](https://user-images.githubusercontent.com/29605147/34460241-935626d2-ee3b-11e7-99ef-a91518415555.PNG)
* My .clang-format location:
![location](https://user-images.githubusercontent.com/29605147/34460256-f11323c4-ee3b-11e7-8160-2cca525de01b.PNG)
* My .clang-format configuration base on [Clang-Format Style Options from LVVM](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) :
Caption from this file:
![caption](https://user-images.githubusercontent.com/29605147/34460368-8714215a-ee3e-11e7-98bd-463784897991.PNG)

**Comment by sean-mcmanus** [comment]
The file needs to be named ".clang-format" without a filename in front (or _clang-format)...at least that's what we currently support (since that's what the clang-format docs said it supported at the time we added this feature). Can you rename your file? I think file explorer on Windows doesn't like it when a file doesn't have a name, but you can create the file via a command line. If it's supposed to work with a filename let us know and we might be able to fix that.

**Comment by philong6297** [comment]
I changed it to ".clang-format" like what you said , but its still not work yet.

**Comment by sean-mcmanus** [comment]
When formatting doesn't work, does hover work? If your .clang-format file has some error in it, we won't report the failure and will silently fail, so you should make sure formatting via the command line works. Change you change the "C_Cpp.loggingLevel" to `"6"` and see what the "Formatting input/raw output/diffed output" results are? You don't have to include the result, I just need to know where the problem is coming from.

**Comment by philong6297** [comment]
I found the problem today and it was from me, my  `.clang-format` file didn't use the correct YAML format. Thanks for your supports.
