### ISSUE TITLE
VSCode's C/C++ extension keeps reparsing files in project driving the CPU to 99%

### ISSUE THREAD

**Issue by bitsmaker** [microsoft/vscode-cpptools#1393]
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Version 1.20.0-insider
Commit f9115349ef09cfef2bed669680d10ac58b490dce
Date 2017-12-22T06:14:07.615Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

C/C++ extension 0.14.5

Vim, CMake; problem persists when these extensions are disabled

Load a large project into VSCode. The first time I understand it has to parse 75,695 files. However after they are parsed I checked the size of browse.vc.db and it is under 1GB. I exited VSCode and the .shm & .wal were gone as well. I restarted VSCode and its started parsing the same files again!

[settings.tar.gz](https://github.com/Microsoft/vscode-cpptools/files/1595588/settings.tar.gz)

I did not see any messages in the Output window.

I should mention that the second time it was done parsing, the size of browse.vc.db stayed the same

**Comment by omern1** [comment]
I am experiencing something similar on `MacOS v10.13.2, VSCode Insiders v1.20, C/C++ tools v0.14.5`.

My project is not nearly as large but I can't format documents and I have no intellisense, only tag parser results. The CPU usage isn't 99%, instead its 0%. The process keeps running infinitely though.
<img width="797" alt="screen shot 2018-01-01 at 8 11 16 pm" src="https://user-images.githubusercontent.com/11234616/34468494-f6641d52-ef2f-11e7-905d-a7cb810dbde6.png">
*Activity Monitor showing the process*

The following text appears in the output window:
```
Failed to read response from server: 4
Shutdown request failed.
Failed to read response from server: 4
Failed to send request to server: 17
IntelliSense client has disconnected from the server - /Users/nabeelomer/Projects/Guacamole/src/Lexer.cpp
Shutdown request failed.
Failed to read response from server: 4
Shutdown request failed.
Failed to read response from server: 4
Shutdown request failed.
```

**Comment by sean-mcmanus** [comment]
@bitsmaker We have fixed this already in our pending January update (still testing it though). The "parsing" status message is actually incorrect (we fixed that), but we had another issue that made it take way too long due to repeatedly searching through the same include paths, so we've reduced the processing by an order of magnitude (e.g. 6 minutes to 6 seconds).

@nabeelomer Your issue is completely different. It would be better if you filed a new issue. It sounds like the IntelliSense process is crashing.

**Comment by omern1** [comment]
@sean-mcmanus #1396

**Comment by bitsmaker** [comment]
Thanks for the quick response and that's great news! Is the fix available as part of VSCode insiders?

**Comment by sean-mcmanus** [comment]
@bitsmaker VS Code doesn't have an insider mechanism for extensions (extensions always ship the same bits for insiders and non-insiders unless they happen to require a version number equal to the insider version number). We can post the .vsix online to do "insider" type releases, but I'm not sure if we'll be doing that (my guess is that we're just going to ship normally). The fix that reduces the processing time by ~92% is ready to go, but the change to ~98% isn't ready yet, not sure yet if we'll wait till that is ready or not before shipping.

**Comment by sean-mcmanus** [comment]
We have a pre-release with the fix if you want to try it out (https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.14.6-insiders) and let us know if there are any fixes we should make before our release next week.

You should notice that the database icon says "Discovering files" and it should run a little faster, but now the Parsing phase should be completely eliminated if the database has already been built so it should be an order of magnitude faster; otherwise, it'll parse files at 50% CPU usage by default, but the status number is actually accurate now (the max number of files to parse will increase as it search #include for more files to parse) -- you can change that to 100% if you don't mind or 25% if that's still too much by changing the workspaceParsingPriority. Parsing of open files still happens at 100% CPU so that symbols are available, so the background parsing is mostly for finding lower priority workspace symbols. We made major changes to the code, so be on the look out for any regressions related to missing symbols.

**Comment by mmahimtura** [comment]
Thank you so much, i will try the fix out. I will be on the lookout for any regressions I see.

**Comment by mmahimtura** [comment]
I just noticed this...I am able to find symbols, until the red flame at the bottom right shows up. The CPU is running at 25%. Now when I try to jump to definitions I get the sliding short line under all the tabbed file names, indicating some type of processing is going on. If I were to quit VScode and go back in I can find definitions again till the red flame comes on.
Funny thing is that when this happens it cannot find definitions it found just seconds before the red flame came on

**Comment by sean-mcmanus** [comment]
@mmahimtura Yeah, the red flame is a different issue -- it's the IntelliSense thread blocking our main input thread, which can block the Go to Definition. This issue has existed since we released IntelliSense. Changing the intelliSenseEngine to "Tag Parser" would fix it, but the enhanced features would be lost. Many users have complained about this (including me), so it would be great to fix. To the user it's a performance issue, but it's really thread blocking issue. Our next release just improves the performance of the tag parser (database icon processing).

**Comment by sean-mcmanus** [comment]
@bitsmaker We fixed the database icon performance problems. If the red flame is blocking operations, that's a different issue (I think another issue is tracking that). https://github.com/Microsoft/vscode-cpptools/releases/latest
