### ISSUE TITLE
${configurationName} variable - support

### ISSUE THREAD

**Issue by witM** [microsoft/vscode-cpptools#1444]
Microsoft, please do support for variable that holds current configuration name selected from cpp_property.json file for Visual Studio and Visual Code available in tasks This for example be: ${configurationName}. This is very needed and I wonder why you didn't do that (maybe did?) Do that should be simple update so please to make this.

**Comment by sean-mcmanus** [comment]
I don't think extensions have a way of adding task variables, so someone would need to get VS Code to add this ability. You may be able to work around this by using an environment variables of the form ${env:configurationName} and then somehow changing the value of the environment variable when a configuration changes, such as via adding code in onSelectedConfigurationChanged in https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts , but if we want this change to be shipped in the product, it seems like the name of the environment variable would need to be a setting so that it's customizable.

**Comment by sean-mcmanus** [comment]
This can be implemented in our open source code via adding a C_Cpp.configuration setting and the using ${config.C_Cpp.configuration} in your task.json. The config index is currently saved in the workspace "persistent state". I agree it would be good to add, but I'm not sure when we'll get around to it yet due to higher priority tasks.

**Comment by witM** [comment]
Thanks  for informations, I'll be look for future updates for this. It
seems to be natural to be something like this variable.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by bobbrow** [comment]
You can use `${command:cpptools.activeConfigName}` to get the value of the active configuration.  Is that what you were asking for?
