### ISSUE TITLE
Add a setting to set the language standard used by IntelliSense

### ISSUE THREAD

**Issue by lumonix** [microsoft/vscode-cpptools#1448]
Ubuntu 17.10
gcc 7
VS code 1.19.2

Steps:
In any C program put:
#include <stdatomic.h>

A perhaps related bug post on llvm with possible solution?
https://bugs.llvm.org/show_bug.cgi?id=22740

**Comment by sean-mcmanus** [comment]
What fails? Your code fails to compile? That would be a compiler bug. Do you see `identifier "__auto_type" is undefined` from our IntelliSense?

**Comment by lumonix** [comment]
Hi @sean-mcmanus 

The code compiles fine.
The Microsoft IntelliSense plugin fails to handle it correctly.

**Comment by sean-mcmanus** [comment]
I'm unfamiliar with stdatomic.h. Is there a reason you are not using `#include <atomic>` instead? Where is stdatomic.h located on your machine? Are all the includePaths set up correctly?

**Comment by lumonix** [comment]
@sean-mcmanus 

'stdatomic.h' is for C11, where 'atomic' is for C++11.
http://en.cppreference.com/w/c/atomic

The MS compiler is behind in C11 support, but GCC supports it and installs stdatomic.h in one of its folders. You can include this folder in the VS code project and then it will find it and compiling works.

But Intellisense fails with previous mentioned errors.

I believe that perhaps the Clang compiler that VS Code uses for Intellisense needs to be configured differently to handle this. But that is just a guess.

Happy to help if there is anything else I can clarify or provide.
Thanks.

**Comment by sean-mcmanus** [comment]
We default to C11 mode and are supposed to work with the C _Atomic types.

Your intelliSenseMode is "clang-x64" and you have `__GNUC__=7` in your defines, right? Those might be required.

I'll see if I can repro it...

**Comment by lumonix** [comment]
@sean-mcmanus 

You can see my vscode project here:

https://github.com/lumonix/motif

It has a vscode sub-folder and configured for clang.

If you use that project to try and reproduce, then you might have to update the gcc include folder to make sure it points to somewhere that has gcc stdatomic.h file.

"/usr/lib/gcc/x86_64-linux-gnu/7/include"

main.c is the file showing the intelli problems.
e.g. atomic_load

Hope that helps.

**Comment by sean-mcmanus** [comment]
Looks like we need to add an additional intelliSenseMode (and maybe version) for gcc because of differences in the C _Atomic handling compared to clang.

As a workaround, you can try modifying the `~/.vscode/extensions/ms-vscode.cpptools-0.14.6/bin/msvc.json` file by replacing `"--c\n--c11"` with `"--c\n--c11\n--gcc\n--gnu_version=70000"`.

This fixed the issue for me with 60300 (min version required is 40900).

**Comment by sean-mcmanus** [comment]
We're adding some sort of compilerPath option, which should fix this issue when set to the gcc path. Later we might add more IntelliSenseMode options, but the intelliSenseMode shouldn't be needed if the compilerPath is set and is valid, because it should take precedence.

**Comment by lumonix** [comment]
Sounds good!

**Comment by sean-mcmanus** [comment]
@bobbrow This bug isn't fixed -- it requires that we enable passing --gcc and --gnu_version flags.

**Comment by sean-mcmanus** [comment]
Ooops, user error on my part. It is fixed with https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders2 if the compilerPath is set to /usr/bin/gcc instead of the clang path. It's possible there could be additional configuration we need to add to fix other gcc issues though (I just verified that atomic_load worked).

@lumonix Let us know if you're still seeing an issue.
