### ISSUE TITLE
includePath code action can add duplicate paths

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1489]
We might already have an issue on this, but the includePath code action shouldn't prompt to add paths that already exist in the includePath (causing duplicate entries). Interestingly, adding the duplicate includePath appeared to fix the missing includePath I was seeing, I believe because it forced a refresh of the squiggles.

The workaround is to remove the duplicate path, and we remove the duplicates anyway, so it doesn't really matter too much.

**Comment by Colengms** [comment]
Do we have a way to repro this?  "the includePath code action shouldn't prompt to add paths that already exist in the includePath"

My understanding is that if the path already existed in the includePath, intelliSense should have found the file, and shouldn't have squiggled.  Removing duplicates would seem to be addressing a symptom.  Perhaps the real issue is lingering of stale squiggles (from before the path was added to the includePath?), as Sean mentioned that using the code action probably resolved the issue because it triggered a squiggle refresh.

It's possible there was an issue in early 2018 that resulted in stale squiggles.  I think if we can't repro now, we should consider this fixed or no-repro.

**Comment by Colengms** [comment]
It was suggested that this may be due to use of an include_next.  However, testing with include_next, I'm still not able to repro this issue.  It may have been fixed.

Since we no longer have a repro for this, and there hasn't been traffic for a couple years, I'm going to close this.  If someone has a repro, please let me know.
