### ISSUE TITLE
Find all references (Experimental Version)

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#15]
Would be great to have _Find all references_ working. Huge helper in large projects.

**Comment by eddy-geek** [comment]
Continuing #404 discussion, couldn't something be achieved with cscope (which seems to be the ctags equivalent for references /call hierarchy)? 

I like the current lightweight ctags-based approach, as real "intellisense" is often hard to make work on projects using custom build systems, less error-resilient, and slower especially on network filesystems.

**Comment by sean-mcmanus** [comment]
We don't use cscope or ctags and are not planning to. We expect the IntelliSense implementation to work.

**Comment by nevion** [comment]
I was also surprised this feature was not available while trying VSCode again starting today, for the 3rd time in the last 3 years...  Given this issue has been opened for over a year, is there a great deal of effort getting it done or is it motivation or priority related?  Features like this shouldn't be kicked down the line and I believe the Go project for VSCode has the feature working.  Given the length of time this has been opened I just want to make sure this is on developer's minds to get done, with that daily nagging feeling from knowing it's been on the todo list too long.

30 people have thumbs up'd, clearly this issue is important to users.

**Comment by sean-mcmanus** [comment]
@nevion We have recently started doing work that is expected to enable the Find All References feature, along with other VS 2017 C++ features that are not currently available, such as comments in hover and parameter help. We don't have an ETA.

**Comment by agauniyal** [comment]
@sean-mcmanus 'comments in hover' refer to documentation about certain methods present inside comments or something else? If it's the former, will it be tied to certain style like doxygen or standardese?

**Comment by sean-mcmanus** [comment]
@agauniyal It refers to showing the comments next to the definition/declaration of code, similar to what VS 2017 (you can try that to see how we expect it to behave). The internal style of the comments won't matter and we'd just show it as a comment.

**Comment by BryanDiLaura** [comment]
Really looking forward to this feature. Is there any sort of ETA?

**Comment by sean-mcmanus** [comment]
@BryanDiLaura There is no ETA for Find All References. Finding references that occur in different translation units requires additional infrastructure/porting work. Once we have an ETA, we'll post it in a milestone: https://github.com/Microsoft/vscode-cpptools/milestones .

**Comment by techwoes** [comment]
While it's not as awesome as intellisense based symbols/tags, vscode-ag (silver searcher) is pretty fast to do searches. Although I wish it was more configurable, such as only searching cpp/c/h files like the command line version. Currently it searches everything in the folder. It might be an acceptable work around until the intellisense feature is available.

**Comment by Yanpas** [comment]
BTW there is very powerful C++ extension cquery (https://marketplace.visualstudio.com/items?itemName=cquery-project.cquery)

It is blazingly fast, has all IDE features, including this one. I guess it's more reasonable to make this extension an official C++ one
![aa](https://camo.githubusercontent.com/f8ab4941b43a02e326422726a87b85ea6d1e94b9/68747470733a2f2f707470622e70772f476c53512e706e673f7261773d74727565)

**Comment by agauniyal** [comment]
What do you mean by official?

**Comment by Yanpas** [comment]
Default suggested one with green star label

**Comment by aenima1891** [comment]
I'm very interested in this feature.
It would be very useful

**Comment by xgalaxy** [comment]
RE: cquery

It would be nice if `"C_Cpp.intelliSenseEngine"` supported `"None"` or `"Disabled"`. Right now I can't run both VSCode-cpptools and cquery extensions without a lot of performance degradation as both try to do intelligent indexing of the symbols. However, VSCode-cpptools provides useful features beyond just the intellisense such as debugging, so it would be nice if we could disable the intellisense engine.

**Comment by sean-mcmanus** [comment]
@xgalaxy Setting the intelliSenseEngine to "Tag Parser" and the browse.path to [] should eliminate most indexing of symbols. Is there a reason that is not sufficient? That would only be a per-project fix, but when we expose a global setting for this, then you could set the global setting to be blank as well. We also have issue https://github.com/Microsoft/vscode-cpptools/issues/785 tracking this.

**Comment by decimad** [comment]
Yes, I switched to cquery too for its find all references, renaming etc. However even with Tag-Parser only you will get duplicate hover-tooltips for all local types. Also I did not find a way to suppress the warning squiggles that the parser could not find the header files.

**Comment by sean-mcmanus** [comment]
@decimad Yeah, the include path warning isn't currently disable-able, which would be fixed by https://github.com/Microsoft/vscode-cpptools/issues/785 . Duplicate items with tag parser is "by design" -- if cquery has hover support, you can clear the browse.path to reduce the amount of symbols, although we still parse symbols on open file, so there might be some symbols found anyway.

Our typescript is open source, so I believe it would be relatively easy to add a disable setting -- there's a comment in https://github.com/Microsoft/vscode-cpptools/issues/785 that suggests one way to disable the extension via modifying the javascript.

**Comment by daltonhildreth** [comment]
It's been over two years since this issue opened, does this have any sort of priority or ETA? It's not even on the backlog of your milestones.

This feature's presence in other language extensions, the number of thumbs on this issue, and the frequency of duplicate issues highly suggests the demand for fixing this issue -- thus the need for a higher priority than has been given to it. Is there a component that is blocking the development of this feature that is unique to C++?

**Comment by sean-mcmanus** [comment]
@fiblit The feature requires multi-translation unit IntelliSense, which requires a lot of infrastructure work (it's implemented in Visual Studio 2017, but the component hasn't been ported). We may start on the infrastructure work soon, and that work also includes improving our multithreaded processing so IntelliSense operations don't block all other threads. We are aware that is one of the most desired features. We don't have an ETA, but we'll add it to our milestones once we do. The "backlog" milestone is stuff we don't plan to fix.

**Comment by nevion** [comment]
@sean-mcmanus I can understand that the feature requires some good deal of work to get done.

Can you provide some details on why the VS component in 2017 hasn't or won't be ported?  From the outside observer there's alot of shared underlying technologies and provided that on marketplace some extensions cover both, I am interested in hearing some of the deeper details technical or otherwise.

Also I poked this topic about 1 year and 1 week from today.  What words can I say to provide kind motivation and understanding that this is not responsible to not have an ETA still?

What are the steps to make it happen?  Can the community help, in some way?  Does a microsoft project need community based bounties to provide the work time to get it done?

**Comment by ronglums** [comment]
@nevion, We are aware that this is a highly requested feature, and it has been relatively high on our backlog. However, we have a small team working on this extension, and our priority in the past year has been improving IntelliSense, especially making it easier to configure IntelliSense. Now we've finally got around to look at code navigation features, including to enhance GoToDefinition ( [#255](https://github.com/Microsoft/vscode-cpptools/issues/255)) and to add Find All References. Like @sean-mcmanus mentioned above, the implementation is non-trivial, so it may take a little bit of time, but we will get there and it won't be another two years :) You can expect an updated version of GoToDef next, and Find All References will come shortly after.

**Comment by dbsquared** [comment]
2 years since open... Hard to call an IDE supports c++ if it can't navigate the function callers.
Is there any WIP branch we could help? Really need to get this working since moving from C# to C++ project, really don't want to move to eclipse.

**Comment by Yanpas** [comment]
Use cquery

**Comment by sean-mcmanus** [comment]
@dbsquared The code that implements Find All References isn't open source, but you could possibly help with some of the issues in our open source TypeScript stuff (https://github.com/Microsoft/vscode-cpptools/labels/help%20wanted ). We may start work on Find All References in November, depending on how many Go to Definition issues we want to fix now or postpone till later.

**Comment by sguillia** [comment]
@sean-mcmanus Why isn't the code open source?

**Comment by sean-mcmanus** [comment]
@sguillia The main reason is our C++ front-end/parser is licensed/developed by a Third Party (see https://blogs.msdn.microsoft.com/vcblog/2009/05/27/rebuilding-intellisense/ ).

**Comment by dbsquared** [comment]
man, pls dont worry abt go to definition, it works just fine for me. Even if it doesnt work for some corner case, string search can easily workaround it. but find all reference is not easily get around in object oriented language. imagine how many class es could define add(), get() functions etc

if i were the PM, i would fill the blank area first before fixing minor bugs.

**Comment by sean-mcmanus** [comment]
@dbsquared Some of the implementation is shared -- find all references on a symbol can't work correctly until we're able to obtain the correct symbol declaration, which is why we decided to do the IntelliSense-based Go to Definition work first; however, I think that shared code is already finished as of 0.19.1-insiders2. I was also thinking about switching to Find All References "right now", but the additional bug fixes for Go to Definition (i.e. overloads not defined in the TU, https://github.com/Microsoft/vscode-cpptools/issues/2677 ) is not expected to take "too long".

**Comment by dbsquared** [comment]
> @dbsquared Some of the implementation is shared -- find all references on a symbol can't work correctly until we're able to obtain the correct symbol declaration, which is why we decided to do the IntelliSense-based Go to Definition work first; however, I think that shared code is already finished as of 0.19.1-insiders2. I was also thinking about switching to Find All References "right now", but the additional bug fixes for Go to Definition (i.e. overloads not defined in the TU, #2677 ) is not expected to take "too long".

Fair enough. Thanks for your patient and quick response!

**Comment by hungys** [comment]
Will the "Find All References" feature be available under "Tag Parser" mode?

I have tried another extension called "C++ IntelliSense", which is based on GNU Global tagging system and it works well. I think it's also possible to be implemented in "Tag Parser" mode.

**Comment by bobbrow** [comment]
Tag Parser mode won't be accurate enough, so we do not have plans to implement it in tag parser mode.  Tag parser mode would give you results similar to VS Code's global search.

**Comment by hungys** [comment]
@bobbrow In a large project, global search and "Go to Symbol in Workspace" are both SLOW to use. I have tried other GNU Global based extension (e.g., C++ IntelliSense) which implements "Find All References" feature, and it's blazing fast and really convenient when browsing code. Without "Find All References", it's hard for me to choose "Tag Parser" mode of C/C++ extension over other tag-based extensions.

**Comment by sean-mcmanus** [comment]
@hungys Sure, we can check if our implementation of Find All References is faster or better than VS Code's global search -- I believe the Tag Parser scenario would be the same code (so no significant additional work), just omitting the IntelliSense symbol filtering/checking, so it'll get results that are "unconfirmed", which matches VS's behavior.

**Comment by LeThiHyVong** [comment]
AFAIK, VSCode is implementing [List All References](https://code.visualstudio.com/updates/v1_29#_references-view).
I don't know the principles behind, but in my view as a user, it quite duplicates this issue in some way.
Find All References = List All References + filter comment
and Find All References in the whole project and include, while List All References in the workspace(?)
I just hope that you can reuse or refer to save time when implement Find All References in this extension.

**Comment by sean-mcmanus** [comment]
@LeThiHyVong List All References is available in VS Code Insiders and it's just a UI layer over the Find All References results that we return, i.e. any extensions that registers "Find All References" support gets "List All References" auto-added, just like "Peed Definition" is auto-added. However, we need support for async Find All References that dynamically updates as we get more/better results (like Visual Studio's C++ UI does) so VS Code's UI is currently insufficient (we're looking into a solution).

UPDATE: We got Find All References working for unconfirmed references (symbols with a matching name, but potentially not the correct type), but "confirming" the references hasn't been implemented and our priorities are shifting back to improving the configuration experience and improving performance, because too many new users are complaining about having problems configuring IntelliSense (and performance), so finishing this will be delayed.

**Comment by lijiaocn** [comment]
2 years... 

i find "C++ IntelliSense"，it works.

**Comment by metal4people-zz** [comment]
Hi everyone,

If one needs to understand how real project on C++ works, then code explore is absolutely necessary.
It is needed even before you start writing something.

Visual Studio Code works nice, automatically reads compilation_commands.json generated by cmake.
But when you need just to fine the all places where the C++ method is used, which is basic action while exploring code, then you find that you cannot do it. You cannot. Dot.
Searching is not suitable at all, because it gives a dozen of entries where "initialize" method is called, for example.

I am writing to you because I want Visual Studio Code to be usable. Really.
Hope for understanding and hope to see find all references soon.

Best regards,
Taras

**Comment by gmmybu** [comment]
“C++ IntelliSense” seems conflict with this.
I hope cpptool can add this feature. Its quite useful when read and write c++ code

**Comment by lunxian** [comment]
need this feature!!!

**Comment by osemmler** [comment]
I have stopped using VSCode due to the absence of this feature.
I recommend QtCreator for C ++ development.

**Comment by Yanpas** [comment]
@osemmler you can use ccls extension instead of this one, it has support for this

https://github.com/MaskRay/vscode-ccls

**Comment by martinakos** [comment]
I have the "Find All References" in my context menu, but it always produces "No results found" even if there is references in the same file. Disappointing!

**Comment by sean-mcmanus** [comment]
@martinakos Our extension does not add "Find All References" to the context menu. I think another C/C++ extension must be adding it. But either way, we haven't finished implementing it yet.

**Comment by WoolenWang** [comment]
Except to support the c/c++ , really love this plugin's idea and deeply need this.

**Comment by leosdad** [comment]
The command "Change all occurrences" highlights all occurrences in the same file in the scroll area, which can be helpful. However I also find this to be the most needed feature in the C/C++ extension.

**Comment by Jekton** [comment]
> @martinakos Our extension does not add "Find All References" to the context menu. I think another C/C++ extension must be adding it. But either way, we haven't finished implementing it yet.

I think It's added by the VS Code

**Comment by sean-mcmanus** [comment]
@Jekton It's added by VS Code only when an extension reports that they support the "referenceProvider" capability which our extension reports "false".

**Comment by LeThiHyVong** [comment]
@martinakos Some extension like cquery or C++ Intellisense can add the Find all references to right click menu but doesn't relate to VS Code API. They have even added the functionality for years, rely on gtag or so.

**Comment by AlexanderAmelkin** [comment]
3 years ago: issue created.

A year later, 2 years ago:
> @sean-mcmanus:
> We don't use cscope or ctags and are not planning to.
> We expect the IntelliSense implementation to work.

Two more years later, now:
> either way, we haven't finished implementing it yet

I think I will just continue using vim+cscope.
VSCode without 'Find all references' is useless for C/C++ projects, and at this pace it looks like it will never become usable.

**Comment by eszlari** [comment]
Tip: Just install the `vscode-clangd` extension (supports renaming too) and set `"C_Cpp.intelliSenseEngine": "Disabled"`, so you can keep using cpptools for debugging.

Get the `clangd` binary from LLVM: https://llvm.org/builds/

edit: You need a build system, that generates `compile_commands.json` like cmake or meson, to make this work and adjust `settings.json`:
```
    "C_Cpp.intelliSenseEngine": "Disabled",
    "clangd.arguments": [
        "-compile-commands-dir=build"
    ],
    "cmake.configureSettings": {
        "CMAKE_EXPORT_COMPILE_COMMANDS": "ON"
    },
```

**Comment by XobSod** [comment]
@AlexanderAmelkin 
As my predecessor said, try using clangd with its extension. I have "configured" it few days ago and it works quite well, of course you have to disable this microsoft addon, and allow [clangd](https://clang.llvm.org/extra/clangd/) do the stuff ;)

**Comment by starship863** [comment]
So vscode-cpptools is actually the best plugin for and **only** for cpp debugging, lesson learned.

**Comment by liudonghua123** [comment]
I installed clang/clangd with the following command in my msys2.
```
pacman -S mingw-w64-i686-llvm mingw-w64-i686-clang mingw-w64-i686-clang-analyzer mingw-w64-i686-clang-tools-extra
```

**Comment by csorvagep** [comment]
I tried clangd with the above mentioned way, but it seemed less effective. Maybe this is because of the cmake-tools extension, but the intellisense wasn't working properly. I suspect this is my fault, so I do not say don't try this, although it can be true the other way around. When I use the cpptools with cmake-tools it works really nicely, except the rename feature of course.

**Comment by eszlari** [comment]
@csorvagep I updated my comment with full instructions!

**Comment by csorvagep** [comment]
@eszlari, Thanks for your help, but it still not works properly. I created an example project for this and used cairo which worked but give me no intellisense at all. I also tried Eigen, but it showed 'file not found' for the include and there was squiggly line under every Eigen namespace.
After that I created a test class, but it gave me the same error.

I checked the generated compile_commands.json and it should be fine. The log showed me nothing useful about this. Any ideas?
I tried this on windows with mingw, but it should be the same for other systems.

Ps: Sorry if it's a little bit off topic.

**Comment by eszlari** [comment]
> used cairo which worked but give me no intellisense at all.

cairo's build system doesn't generate a `compile_commands.json`.

> I also tried Eigen, but it showed 'file not found' for the include and there was squiggly line under every Eigen namespace.

I also couldn't get Eigen to work, but other sources worked, e.g. try `libgit2`.

**Comment by ranqiyu** [comment]
when choose menu "Find All References", it always show "no results found."
when will add this feature offical.

**Comment by mmcru** [comment]
Really looking forward to June release - this is a killer feature!

**Comment by msandor93** [comment]
I am also waiting for this feature... My current setup is already quite complex, and installing some "non-official" additional programs is not manageable with simple scripts, that set's up the environment... Let's hope to see it in June :)

**Comment by RogerPanBUAAedu** [comment]
This issue is still not fixed until now. Both on my Win10 and Ubuntu platform.

**Comment by robotwxy** [comment]
> Would be great to have _Find all references_ working. Huge helper in large projects.

I find a solution, install and run "gtags" in your project folder, after "GPATH", "GRTAGS", "GTAGS" files are created in your folder, your "peek references" function will work normally.

**Comment by liushiqi9** [comment]
Really looking forward to it!!!

**Comment by zcgeng** [comment]
Looking forward to it, too.
But if you are super eager to use "Find all references" right now you can just install [scope4code](https://marketplace.visualstudio.com/items?itemName=xulion.codescope). It's very easy and works immediately without any configuration (except installing `cscope` by a single line of `sudo apt-get install cscope`).

**Comment by jiayuqicz** [comment]
please install C++ Intellisense extention
it has been solved

you also have to install gnu-global，And run command “gtags” in the root of project.
1. download: http://adoxa.altervista.org/global/
2. add /bin to your PATH
3. run command "gtags" in the root of project.

![image](https://user-images.githubusercontent.com/6240102/59522074-647a0100-8f00-11e9-8401-ed2a85c251d2.png)

![image](https://user-images.githubusercontent.com/6240102/59523112-0995d900-8f03-11e9-889a-91adab7a9dc4.png)

![image](https://user-images.githubusercontent.com/6240102/59522570-92ac1080-8f01-11e9-832d-6af1528e276a.png)

**Comment by fsaizwei** [comment]
> please install C++ Intellisense extention
> it has been solved

shift+F12 still not working for me with intellisense?

**Comment by windless0530** [comment]
> > please install C++ Intellisense extention
> > it has been solved
> 
> shift+F12 still not working for me with intellisense?

me either

**Comment by windless0530** [comment]
Eager to use this feature. This is the only issue that stops me from switching to Code from CLion.

**Comment by leosdad** [comment]
> please install C++ Intellisense extention
> it has been solved

I don't think so

**Comment by jiayuqicz** [comment]
> > please install C++ Intellisense extention
> > it has been solved
> 
> shift+F12 still not working for me with intellisense?

you also have to install gnu-global，And run command “gtags” in the root of project.
1. download: http://adoxa.altervista.org/global/
2. add /bin to your PATH
3. run command "gtags" in the root of project.

![image](https://user-images.githubusercontent.com/6240102/59522074-647a0100-8f00-11e9-8401-ed2a85c251d2.png)

**Comment by bobbrow** [comment]
We're getting closer to having a preview available for this feature.  However, it doesn't look like it will be ready in time for our current release.  We plan to have it ready for Insiders in the first half of July.  Thank you for your patience and understanding.

**Comment by Alonzzzo2** [comment]
> > > please install C++ Intellisense extention
> > > it has been solved
> > 
> > 
> > shift+F12 still not working for me with intellisense?
> 
> you also have to install gnu-global，And run command “gtags” in the root of project.
> 
> 1. download: http://adoxa.altervista.org/global/
> 2. add /bin to your PATH
> 3. run command "gtags" in the root of project.
> 
> ![image](https://user-images.githubusercontent.com/6240102/59522074-647a0100-8f00-11e9-8401-ed2a85c251d2.png)

I installed Global (apt install) version 6.6.2 and ran gtags, the GPATH, GRTAGS, GTAGS files were created, restarted VSCode but still 'Find All References' doesn't work. 
Can you tell me what I'm missing?
Thanks

**Comment by CanCanZeng** [comment]
@jiayuqicz what platform do you use, windows or Linux?

**Comment by jiayuqicz** [comment]
> @jiayuqicz what platform do you use, windows or Linux?

windows

**Comment by jiayuqicz** [comment]
> > > > please install C++ Intellisense extention
> > > > it has been solved
> > > 
> > > 
> > > shift+F12 still not working for me with intellisense?
> > 
> > 
> > you also have to install gnu-global，And run command “gtags” in the root of project.
> > 
> > 1. download: http://adoxa.altervista.org/global/
> > 2. add /bin to your PATH
> > 3. run command "gtags" in the root of project.
> > 
> > ![image](https://user-images.githubusercontent.com/6240102/59522074-647a0100-8f00-11e9-8401-ed2a85c251d2.png)
> 
> I installed Global (apt install) version 6.6.2 and ran gtags, the GPATH, GRTAGS, GTAGS files were created, restarted VSCode but still 'Find All References' doesn't work.
> Can you tell me what I'm missing?
> Thanks

eh…，I don't know，it just work on my computer. maybe you can try to read the instruction of the extention and try again

**Comment by Lennon925** [comment]
@sean-mcmanus 
when this feature is finished, I hope cpptools can support this commands: getReferencesCommand.
When I pass file uri, line and column as parameters of this command, it can return all references location to me regardless of this file is opened or not.
Could you add this feature to "Find all references" for me ?

**Comment by Timmmm** [comment]
Until this is ready, I have things working pretty well with the vscode-clangd extension and this extension both enabled. Here are the key things you need to add to your settings:

```
    "C_Cpp.autocomplete": "Disabled",  // So you don't get autocomplete from both extensions.
    "C_Cpp.errorSquiggles": "Disabled", // So you don't get error squiggles from both extensions (clangd's seem to be more reliable anyway).
    "clangd.path": "/usr/local/opt/llvm/bin/clangd", // Path to clangd. Note it might be clangd-8 on Linux. Also you need version 8 at least.
    "clangd.arguments": [
        "-background-index" // So Find All References actually works properly.
    ],
    // Don't disable the intellisense engine otherwise switch header/source (Alt-O) doesn't work.
```

Also I then symlink `compile_commands.json` from my source directory to the build directory.

It is a *little* flaky. Sometimes clangd seems to get stuck and I have to reload the window. Also while error squiggles, Find All Reference, and Go To Definition work pretty reliably, Find Symbol doesn't. Still I think it is the best option until this extension supports it properly.

**Comment by cstrahan** [comment]
To add to what @Timmmm said, **note** that `--background-index` was introduced in `clangd-8`. I found out the hard way that `clangd-7` doesn't expect that argument, and the completion server will crash inside of vscode with no indication of why (I had to write a wrapper script that redirected stderr/stdout to a file to inspect later in order to find out what was going on).

**Comment by HunterZ** [comment]
> We're getting closer to having a preview available for this feature. However, it doesn't look like it will be ready in time for our current release. We plan to have it ready for Insiders in the first half of July. Thank you for your patience and understanding.

Is this implementation going to work without requiring installation of external tools? It's hard for me to get tools, and Eclipse CDT provides this feature without them.

**Comment by dschaefer** [comment]
> Is this implementation going to work without requiring installation of external tools? It's hard for me to get tools, and Eclipse CDT provides this feature without them.

:). Yes, indexing has been a core feature of CDT since the beginning. It's hard to do right enough and fast enough so I appreciate the time cpptools is taking to get there.

**Comment by sean-mcmanus** [comment]
@HunterZ No external tools will be required.

**Comment by legal-username** [comment]
is it usable or not now?

**Comment by sean-mcmanus** [comment]
@pig-peppa We're currently doing functionality and performance testing -- we might be able to release an Insider vsix next week or so.

**Comment by tooyangtoonaive** [comment]
up

**Comment by Timmmm** [comment]
For those following this eagerly like me, this is the pull request: #4016.

It is only the VSCode configuration part of the change though. I think the meat of the work is in the closed-source intellisense engine, so I don't think we can try it out yet. Getting closer though!

**Comment by MichaelDu9226** [comment]
fixed?when will  be  released?Can't wait for it!Thanks~

**Comment by Lennon925** [comment]
> For those following this eagerly like me, this is the pull request: #4016.
> 
> It is only the VSCode configuration part of the change though. I think the meat of the work is in the closed-source intellisense engine, so I don't think we can try it out yet. Getting closer though!

This branch was deleted……

**Comment by starship863** [comment]
> fixed?when will be released?Can't wait for it!Thanks~

Great! Let's celebrate!

**Comment by sean-mcmanus** [comment]
Find All References (and Peek References) is available via setting C_Cpp.updateChannel to "Insiders" (or manually install it from https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders ), and then setting the C_Cpp.experimentalFeatures setting to "Enabled" -- we hid the feature behind this setting so that we could get feedback on the feature from a smaller audience.

A bunch of "known issues" with the feature can be found at https://github.com/microsoft/vscode-cpptools/labels/Feature%3A%20Find%20All%20References . Please upvote the existing issues or file new issues if you encounter them. We would prefer you not to add the bugs to this issue, because it makes it harder to track.

**Comment by yamcenutzer** [comment]
nice..
However, it doesn't seem to install on remote (ssh) sessions

**Comment by yaroslavsadin** [comment]
Would you plan to get Change All Occurences work along with Find All References for refactoring?

**Comment by cjolivier01** [comment]
Yes, I also get constantly asking to reload the window on a remote session (after installign insiders version)

**Comment by bobbrow** [comment]
We're tracking #3833 and #3874 for the issues with Insiders in Remote workspaces.

**Comment by sean-mcmanus** [comment]
We shipped Find All References (Experimental Version) with 0.25.0. A list of known enhancements/bugs can be found at https://github.com/microsoft/vscode-cpptools/labels/Feature%3A%20Find%20All%20References . Our current plan for 0.26.0 is to add rename and to move the Output window non-confirmed results to the References tree view [#4079](https://github.com/microsoft/vscode-cpptools/issues/4079). The main feedback we've gotten is for improving the performance.

UPDATE: I renamed the issue with "Experimental Version" to try to prevent people from thinking we're 100% done with the feature (since this issue is "closed"), aka "Version 1".

**Comment by Konstantin6487** [comment]
Still not working. VScode finds for example
 `import { loader }` but doesn't find `import { loader as basicLoader }`
I created `jsconfig`, installed 0.25.0-insiders and nothing :(
It works in small project, but not in large.

**Comment by LeThiHyVong** [comment]
@Konstantin6487 what are you looking for?
This repo is C/C++ support extension of VSCode, not for other languages.

**Comment by Konstantin6487** [comment]
I'm sorry. I made a mistake. My problem is only with js.

**Comment by XobSod** [comment]
Hi all,

You guys did something to C_Cpp.PeekDeclaration command? After updating the extension error appears:
`command 'C_Cpp.PeekDeclaration' not found`

**Comment by sean-mcmanus** [comment]
@XobSod Yeah, it's removed -- we use the built-in Peek Declaration command now.
