### ISSUE TITLE
Support C++ alternative tokens for binary operator `and`, `or`, `not` etc.

### ISSUE THREAD

**Issue by palotasb** [microsoft/vscode-cpptools#1589]
I am not sure if this is a valid bug report here or not, but using `"intelliSenseMode": "msvc-x64"` the tokens mentioned in the title cause parsing errors. I can switch to `clang-x64` but that intellisense-mode is less smart, so I prefer not to do it.  One possible fix for me as a user is that I can add a bunch of defines to support code that has these alternative tokens while using MSVC intellisense mode. Is there any other way (like adding a compiler switch?), and is the current behavior (not enabling the standards-compliancy switch for msvc-x64 by default) intentional?

To reproduce on Windows:
* Open a new folder
* Create a `test.cpp` and enter the following code:
```c++
int main() {
    if (not true) {
        return 1;
    }
    if (true and false) {
        return 1;
    }
}
```

Observe that `identifier "not" is undefined` error appears for the `not` keyword and for `and` it says `expected a ')'`. I think this is caused by the issue described here: https://stackoverflow.com/questions/24414124

**Comment by palotasb** [comment]
I accidentally hit Ctrl+Enter before typing _"Support C++ alternative tokens for binary operator `and`, `or`, `not` etc."_ and then realizing that is MSVC default behavior. So I am not sure if this is a valid bug report here or not, but using `"intelliSenseMode": "msvc-x64"` the tokens mentioned in the [fixed] title cause parsing errors. I can switch to `clang-x64` but that intellisense-mode is less smart, so I prefer not to do it.  One possible fix for me as a user is that I can add a bunch of defines to support code that has these alternative tokens while using MSVC intellisense mode. Is there any other way (like adding a compiler switch?), and is the current behavior (not enabling the standards-compliancy switch for msvc-x64 by default) intentional?

(Sorry again for the original bad title.)

**Comment by palotasb** [comment]
To reproduce on Windoews:
* Open a new folder
* Create a `test.cpp` and enter the following code:
```c++
int main() {
    if (not true) {
        return 1;
    }
    if (true and false) {
        return 1;
    }
}
```

Observe that `identifier "not" is undefined` error appears for the `not` keyword and for `and` it says `expected a ')'`. I think this is caused by the issue described here: https://stackoverflow.com/questions/24414124

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem. Are you using a .c or .cpp file? I get the error with a .c file.

**Comment by ghost** [comment]
I'm hitting this as well, with a `.cpp` file. I'm using VS Code 1.20.1 and vscode-cpptools 0.15.0. Right now I'm just working around this by defining these keywords as preprocessor defines in the `c_cpp_properties.json` file.

I feel like we should be able to specify compiler flags in the `c_cpp_properties.json` file, so we could just specify `/Za` or `/FI ciso646` when using these alternative keywords. I think being able to specify compiler options would also be useful for setting `/std:c++latest` or whatever the project requires.

**Comment by ghost** [comment]
> I think this is caused by the issue described here: https://stackoverflow.com/questions/24414124

I think this is correct. At least Visual Studio 2015 does not support these alternative keywords out of the box (even though they're standard), and requires you to specify either `/Za` or `/FI ciso646` to get them.

**Comment by sean-mcmanus** [comment]
We plan to add a cVersion and cppVersion setting, but we don't plan to add support for other compiler flags yet until we know of ones that are important enough and that can be translated into flags our parser understands. No one on our team is able to repro the problem you two are seeing (on multiple machines) so there must be something different with your environment. It's possible another extension is interfering. Maybe something is incorrect in your `bin/msvc.json` or `msvc.32.intel.json` files. It could be because we have VS 2017 15.6 Preview headers installed. What VC headers are you using?

![image](https://user-images.githubusercontent.com/19859882/36445246-8b540a7a-1632-11e8-9184-b9c84008a939.png)

**Comment by ghost** [comment]
I'm using the VS 2017 15.3.5 headers. This is what I'm seeing:

![image](https://user-images.githubusercontent.com/3168386/36447589-79dcaf1c-168d-11e8-892c-0fe0ad188871.png)

**Comment by sean-mcmanus** [comment]
Ah, okay, I'm reproing the problem now (my settings were messed up).

You can workaround this issue by changing the `bin/msvc.64.intel.json` file's contents so that lines 5-13 match:
`      "--no_ms_permissive",
      "--microsoft_bugs",
      "--microsoft_version",
      "1910",
      "--pack_alignment",
      "8",
      "-D_CPPUNWIND=1",
      "-D_MSC_VER=1910",
      "-D_MSC_FULL_VER=191024210",`
The changes are the `--no_ms_permissive" flag is added and the version is increased to 1910. It looks like we should add an option to configure this more easily.

**Comment by sean-mcmanus** [comment]
With 0.23.0, you can add `/permissive-` to the cl.exe compilerPath to enable that.
