### ISSUE TITLE
In .gitignore: ".vscode/*.db" should be ".vscode/*.db*"

### ISSUE THREAD

**Issue by ssilverman** [microsoft/vscode-cpptools#1622]
The .gitignore file is modified to include ".vscode/&ast;.db". Instead, because of the ".browse.c_cpp.db-shm" and ".browse.c_cpp.db-wal" files, should the .gitignore contain ".vscode/&ast;.db&ast;"?

VSCode Version: 1.120.1

**Comment by sean-mcmanus** [comment]
Where is this .gitignore file? Is this something you added or that we add?

**Comment by ssilverman** [comment]
VS Code automatically updates an existing .gitignore file with some .vscode/*xxx* additions. I was referring to one of the lines it added.

**Comment by domingguss** [comment]
I even opt for ignoring the whole `.vscode` folder!

Because the only file that will not be ignored is `settings.json`, but in my setup (using the Platform IO plugin) it contains a hardcoded path which other users obviously don't need.
 
Is this folder being re-generated by VSCode? 
If so, then it seems to me that `.vscode` in your `.gitignore` will suffice.

**Comment by ssilverman** [comment]
Personally, I add the whole .vscode folder too because of all the hardcoded paths.

**Comment by ssilverman** [comment]
I’ll add that I was asked to put this issue here. It was originally issue [#44474](https://github.com/Microsoft/vscode/issues/44474) in the /vscode repository.

**Comment by bobbrow** [comment]
VSCode has acknowledged this is their issue.  Closing...
