### ISSUE TITLE
'No' is not a helpful Intellisense error message

### ISSUE THREAD

**Issue by draeger-charles-wilson** [microsoft/vscode-cpptools#1624]
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS Windows 7

C/C++ Output message (info level set):

`Checking for syntax errors: file:///e%3A/Users/wilsonch/Documents/projects/wilsonch_M540_VG7.0_int/PMAComps/iris_include/cord_rcdr_interface.h`

Output:

![intellisense message](https://user-images.githubusercontent.com/33490168/36797045-f3752afe-1c9e-11e8-95ec-5cb4298489e7.PNG)

Offending line:

![intellisense bad line](https://user-images.githubusercontent.com/33490168/36797127-1cdf2034-1c9f-11e8-8117-820796406fb9.PNG)

This is not a production quality message.

**Comment by sean-mcmanus** [comment]
As far as I can tell, the "No" message is not from our extension. Do you have another extension installed that could be outputting that?

**Comment by draeger-charles-wilson** [comment]
That's the only extension of note. (Python, Markdown PDF) I can't imagine what else would be stuffing an Intellisense error message at the exact location of the ~~~~~ marker.

**Comment by sean-mcmanus** [comment]
We always report the "#include errors detected..." message as the 1st message, so there shouldn't be any message beforehand. What happens if you change the C_Cpp.intelliSenseEngineFallback to "Disabled"? Or C_Cpp.errorSquiggles to "Disabled"? Or C_Cpp.intelliSenseEngine to "Tag Parser"?

If you can clone our GitHub repo and Launch Extension from VS Code you should be able to see the message we send to VS Code in the C/C++ Debug Protocol section in the Output panel (it's "textDocument/publishDiagnostics" -- so if the "No" message is not in that list then it must be coming from another source).

**Comment by draeger-charles-wilson** [comment]
Is it possible that the message is being truncated?
`
No such file or directory (77, 1)`

**Comment by sean-mcmanus** [comment]
All of our IntelliSense error messages begin with lowercase letters, such as "no" (and we never show a "no such file or directory" message, which is the ENOENT message that VS Code itself sometimes shows), so "No" is either from another source or there is something really bizarre occurring like a memory corruption, but I've never seen a memory corruption leading to garbage messages. If you can provide a small repro or the textDocument/publishDiagnostics message we send that would help.

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
