### ISSUE TITLE
F12(Go to defination) is invalid in c++ project.

### ISSUE THREAD

**Issue by zhangmn799** [microsoft/vscode-cpptools#1657]
**Environment data**
VS Code version: 1.21.0
C++ Extension version: 0.16.0-insiders
Debugger: cygwin64
OS: Win10 RS2

**Steps to reproduce**
1.Create a folder named test, create a file named main.cpp in test as following:
int Sum(int a,int b)
{
    return a+b;    
}
int main()
{
    int a =10;
    int b =20;
    cout<<Sum(a,b)<<endl;
    return 0;
}
2.Compara project with command "g++ -g -o main.exe main.cpp" with cygwin64.
3.Move the cursor to Sum in main function.
4.F12(go to Definition)

**Expected behavior**
It will skip to Sum function.

**Actual behavior**
It show "No definition found for 'Sum'".
![f12](https://user-images.githubusercontent.com/26423555/37203760-bae448aa-23c9-11e8-80e0-2985781b386d.png)

**Comment by bobbrow** [comment]
Are there unsaved changes in the file?  This is currently the expected behavior if you haven't saved the file since the "Sum" function was added.  We will be working on making this experience better in the future though.

**Comment by zhangmn799** [comment]
I have saved the file include "Sum" function. Then F12. And some customers also meet this issue.

**Comment by sean-mcmanus** [comment]
We're not able to repro a problem. Can you provide any more repro details? What does it show when you hover over the Sum method? Is the intelliSenseMode "Default"? I assume this repros with 0.15.0 as well, right?

It's possible another extension could be interfering. It's possible there's some problem with the database (the Reset IntelliSense Database command might help).

![image](https://user-images.githubusercontent.com/19859882/37304522-09908212-25ef-11e8-8d12-1e2df47bd69c.png)

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

**Comment by Noctis-AKM** [comment]
I have the same problem when navigating in linux kernel source code.

Environment data
VS Code version: 1.32.3
C++ Extension version: 0.22.1
OS: Manjaro 18

Steps to reproduce
1. Download source code -- linux-4.9.166 tarball (any linux-4.9 is OK)
2. Extract linux-4.9.166.tar.xz
3. cd  linux-4.9.166 && code .
4. press F12 on function put_prev_task_fair()，vscode shows "No definition found for 'put_prev_task_fair'"

Expected behavior
Find the definition correctly.

Actual behavior
show "No definition found for 'put_prev_task_fair'"

![image](https://user-images.githubusercontent.com/38934793/55288944-102bae80-53f2-11e9-9d97-77f96a5d010f.png)

BTW, although F12 "go to definition" doesn't work, Ctrl + Shift + F is able to find the symbol --  put_prev_task_fair()

![image](https://user-images.githubusercontent.com/38934793/55288983-9d6f0300-53f2-11e9-8920-4dd798dac4fc.png)

**Comment by sean-mcmanus** [comment]
@Noctis-AKM You have 2 conflicting extensions installed. You should either disable the C++ IntelliSense extension or set the C_Cpp.intelliSenseEngine to "Disabled" to disable our extension. If you're still seeing a bug with our extension let us know, preferably in a new bug.

**Comment by Noctis-AKM** [comment]
@sean-mcmanus this problem still exists even if I removed C++ IntelliSense。I also tried on Ubuntu 18.04, F12 doesn't wrok on put_prev_task_fair(), enqueue_task_fair(), dequeue_task_fair(), .... But they actually have definition in the workspace.
![image](https://user-images.githubusercontent.com/38934793/55380147-de315e00-5551-11e9-841a-f13a4bbcd311.png)
![image](https://user-images.githubusercontent.com/38934793/55380153-eab5b680-5551-11e9-8406-8766637e5ea7.png)
![image](https://user-images.githubusercontent.com/38934793/55380166-f43f1e80-5551-11e9-8832-26ce3c382a5d.png)
