### ISSUE TITLE
Intellisense doesn't pickup overloaded class constructors' parameter list

### ISSUE THREAD

**Issue by Noah11012** [microsoft/vscode-cpptools#1664]
Operating System: Linux Mint Cinnamon Edition
Version of OS: 18.3
VS Code Version: 1.21.0
C/C++ Extension Version: 0.15.0

Zipped C/C++ Extension Settings:
[c_cpp_properties.zip](https://github.com/Microsoft/vscode-cpptools/files/1799635/c_cpp_properties.zip)

Intellisense doesn't show the available list of overloaded constructors for a class unless you first put a semi-color then type a parenthesis.

The GIF below will illustrate my problem more easily.
![tacky_intelli](https://user-images.githubusercontent.com/26338478/37245311-2a255c1e-2464-11e8-9179-cfff81774843.gif)

**Comment by sean-mcmanus** [comment]
VS 2017 has the same bug. I'll file an issue with them.

**Comment by sean-mcmanus** [comment]
This looks like it's a "design flaw" of the C++ language. At the point where you type the (, the C++ parser is unable to determine if you're typing a constructor for a variable or a function declaration (e.g. QFile file(int a);). I'll ask the VS team to double check.

A workaround in VS 2017 is to use Class var{} syntax to do the construction, but we don't implement that yet: https://github.com/Microsoft/vscode-cpptools/issues/1667 .

**Comment by sean-mcmanus** [comment]
This is https://en.wikipedia.org/wiki/Most_vexing_parse . The VS 2017 team has it on their backlog to improve (i.e. forcing the parser for signature help to interpret it as a constructor instead of a function declaration), but it's low priority (i.e. not expected to get fixed any time soon). You could try to file a VS 2017 issue if you want: https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us .

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
