### ISSUE TITLE
Inactive regions colorization doesn't work in certain header files

### ISSUE THREAD

**Issue by yaroslavsadin** [microsoft/vscode-cpptools#1666]
Hi,

While working on a project I noticed that some header files missing dim inactive regions feature. For example #ifdef and #else are both active at the same time. I reduced this to two simple test cases. In order to reproduce just open each folder in vs code and note that inactive region feature is broken in "dir1/header.h" for both cases. Although in the test2 the issue has gone after fixing includePath but should it affect the header itself?

OS: Windows 7
VS code: 1.21.0
Extension: 0.15.0 (Feb 15)

[test1.zip](https://github.com/Microsoft/vscode-cpptools/files/1799972/test1.zip)
[test2.zip](https://github.com/Microsoft/vscode-cpptools/files/1799971/test2.zip)

Appreciate your help.

Yaroslav

**Comment by sean-mcmanus** [comment]
Thanks a lot for the repro. We were already working on a related bug fix which may encompass this. The IntelliSense operations are all failing because it is mistakenly using the translation unit for main.c in the other directory, but then it later finds that the dir/header.h is not in that translation unit so it fails all IntelliSense ops. Renaming the main.c header to header2.h or adding the dir/header.h to a source file in the same directory are workarounds.

**Comment by Colengms** [comment]
This appears to have been addressed.  The examples provided no longer repro the issue.
