### ISSUE TITLE
stdio.h file not found

### ISSUE THREAD

**Issue by Marksuifeng** [microsoft/vscode-cpptools#1668]
windows version 1709
vscode version 1.21.0
![1](https://user-images.githubusercontent.com/16861930/37250167-4f96a8b8-2531-11e8-855d-f358d601d639.PNG)
![3](https://user-images.githubusercontent.com/16861930/37250169-51264eea-2531-11e8-817f-1a94267f9531.PNG)

**Comment by sean-mcmanus** [comment]
The "file not found" tooltip message is from the C/C++ Clang Command Adapter extension and not the C++ extension (see also #1352 ).

Once you deal with that, you may want to check out https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md, since I noticed your intelliSenseMode should be clang-x64.

If you still experience issues, you may want to try our insiders build, which supports adding a path to your mingw compiler for quering includes and system defines: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders .
