### ISSUE TITLE
Evaluation of 0.16 preview release

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-cpptools#1676]
OS: Solus 3 (Linux)
VSCode Version: 1.21
Ext Version: 0.16 (preview)

The autocomplete has been very hit or miss with this update. By that I mean it seems to be much slower, or doesn't show up at all some times. I will keep evaluating.

**Comment by sean-mcmanus** [comment]
I assume there's no red flame in the bottom right, right? Otherwise, that would block autocomplete results (usually, this should only occur when the file is newly opened or heavily modified). If you get no results and you also get no "(int)number" when hovering over a literal number that would mean IntelliSense is hitting some failure and falling back to the tag parser.

What level of "slowness" are you seeing? Seconds? I'm able to detect sub-second lags, e.g. a delay by 5 characters or so. I'm not sure how this translates on slower machines.

**Comment by tristan957** [comment]
I'm confirming <1 second lag. No red flame. Maybe I was blind yesterday. Everything seems pretty great today
