### ISSUE TITLE
Intellisense includePaths error

### ISSUE THREAD

**Issue by tsalinger** [microsoft/vscode-cpptools#1677]
>This issue has been moved from [Microsoft/vscode/](https://github.com/Microsoft/vscode/issues/45627)
Author is @TheKingdomScribe.
---
Issue Type: <b>Bug</b>

When using C, after configuring the include paths with all the gcc libaries, whenever I use <ctype.h>, many functions get the same problem. I get red squiggles with the problem, "identifier "_ISupper" is undefined" for the functions isupper, islower and isdigit. I believe this happens for most functions available in this library as well. The program runs fine, though intellisense still thinks that part of the header is undefined even though it doesn't cause any problems. Just a slight bug I thought I'd mention.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.13.0-21-generic

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

---

**Comment by sean-mcmanus** [comment]
@TheKingdomScribe The problem is probably that the required defines are missing. If you try https://github.com/Microsoft/vscode-cpptools/releases/download/v0.16.0-insiders/cpptools-linux.vsix (Install extension from VSIX command), you should be able to set the compilerPath (in c_cpp_properties.json) to /usr/bin/gcc (or whatever) and it'll pick up the compiler's default includePaths and defines (although the defines are hidden, because there can be hundreds). Let us know if doing that doesn't fix it.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
