### ISSUE TITLE
Unreal Engine on Mac

### ISSUE THREAD

**Issue by unoctanium** [microsoft/vscode-cpptools#1684]
I am using VSCode on MacOS to edit Unreal Engine 4.18 projects.

Building my solution with a Run Build Task works perfectly.

But I have some issues with IntelliSense for C++:

Following 1) is for information. 2) is my problem.

1) IntelliSense was not able to find `<new>`  in UE4s "CoreMinimal.h".
I solved this by adding missing include files in the c_cpp_properties.json.
This is definitely a problem of epic. They have to improve the way they build VSCode Projects.
In my case I added:

`"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
				"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks",
				"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1",
				"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/9.0.0/include",
				"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
				"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
`

2) Now, I have no problems any longer from missing includes, but:

IntelliSense is not able to parse the Unreal Header Tool specific decorations like
UCLASS()
USTRUCT()
UPROPERTY()
etc.

That results in a couple of IntelliSense errors.

Possible Workaround:

Maybe you should give us teh option to ignore these decorations in IntelliSense

Best regards
Odo

**Comment by bobbrow** [comment]
I do not see either of these problems in the latest version of the extension.

The first one can be addressed by setting `"compilerPath"` in `c_cpp_properties.json`. This is preferred over setting the system include paths manually.

The second one doesn't repro for me.  I looked at the header and I see `#if defined(__INTELLISENSE__)` around the definition of these macros which tells our engine to use the simple definition of these macros instead of the full definition.
