### ISSUE TITLE
Jump to declaration has two suggestions for enum, struct and unions when the type name and tag name are the same

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode-cpptools#1693]
I have a structure:
```c
typedef struct sParam_t {
    int a;
    int b;
} sParam_t;
```
I declare a variable of type sParam_t:
```c
sParam_t param;
```
Then I tray to jump to declaration of sParam_t. After jumping to declaration peek to declaration pops up and has to suggestions like this:
![image](https://user-images.githubusercontent.com/9738294/37506891-ab4b0d0e-28f4-11e8-8665-9a9c4df21a2a.png)

It is annoying because I am already at that place and I don't need extra view to see the same thing... I think the best way to handle this would be to jump like it is different names sParam_t and sruct sParam_t.

**Comment by sean-mcmanus** [comment]
This is because Go to Definition is implemented by the Tag Parser still and it should be fixed after switching to use the IntelliSense engine. Hover (from the IntelliSense engine) only shows 1 entry.

However, I noticed a different in issue in that hover is showing typedef sParam_t sParam_t instead of struct sParam_t (show by VS 2017), which seems like a bug.

**Comment by bobbrow** [comment]
This appears to be fixed in the latest version of the extension.
