### ISSUE TITLE
WSL has case-sensitive file system in pre-release builds

### ISSUE THREAD

**Issue by lilgrassin** [microsoft/vscode-cpptools#1694]
My system:
Windows 10.0.17115 (insider build)
VSCode 1.21.1
Cpptools 0.15.0

I've been using Intellisense under the WSL with no issue for a while now, but today when I opened up a C project (which was working the other day), Intellisense was able to find files in the project folder, but not those under WSL (e.g. `stdio.h`, `stdlib.h` etc). I've checked that the includepath for gcc/WSL hasn't changed, and I haven't touched my `c_cpp_properties.json` (which I'll include below). I also just updated Windows earlier this week and VSCode yesterday.

![image](https://user-images.githubusercontent.com/11161002/37534063-12e97cbe-291a-11e8-92dd-e2a8b38c2a5b.png)
![image](https://user-images.githubusercontent.com/11161002/37534085-24571ff6-291a-11e8-8cb4-d333e2427c66.PNG)

```
{
    "configurations": [
        {
			"name": "Win32",
			"intelliSenseMode": "clang-x64",
			"includePath": [
				"${workspaceRoot}",
				"${workspaceRoot}/gtest/include",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/7",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/7",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/7/backward",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
				"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include"
			],
			"defines": [
				"__linux__",
				"__x86_64__"
			],
			"browse": {
				"path": [
					"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/7",
					"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/7",
					"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include",
					"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
					"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
					"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
					"${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/*"
				],
				"limitSymbolsToIncludedHeaders": true,
				"databaseFilename": ""
			}
		}
    ],
    "version": 3
}
```

**Comment by sean-mcmanus** [comment]
Another user has also reported some issue with WSL failing to find the system headers. I haven't been able to repro a problem yet, but we could fail to find includePaths if the paths include symbolic links, because the links in the path don't exist on Windows. We're actively working on improving the WSL scenario via allowing users to just set the compilerPath and allowing symbolic links in the include path, which may fix this issue.

We haven't updated 0.15.0 in a while, so it seems like there was a change with the Windows insider build.

**Comment by lilgrassin** [comment]
If it helps, I just checked the logs and the specific error is:
```
Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/7. error = -1
Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/7. error = -1
Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include. error = -1
Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include. error = -1
Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed. error = -1
Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu. error = -1
Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/*. error = -1
```

**Comment by sean-mcmanus** [comment]
Our code is failing to find the path. Do they still exist?

**Comment by lilgrassin** [comment]
They do. (I checked both the linux packages and the filesystem directory)

**Comment by sean-mcmanus** [comment]
@bobbrow Any ideas? Could this be an Windows Insiders bug?

**Comment by bobbrow** [comment]
I have a laptop that was flighted to 17074 that I can try.  On 16299, I can verify that IntelliSense isn't working when there are symlinks in the includePath. (e.g. /usr/include/c++/5.4.0 which links to /usr/include/c++/5).  Using 5 instead of 5.4.0 resolves it for me.

![image](https://user-images.githubusercontent.com/12818240/37547718-a0e92e5e-2930-11e8-8e39-24629ac25b3f.png)

**Comment by bobbrow** [comment]
I'm not seeing any problem with 17074 either. ☹️

**Comment by lilgrassin** [comment]
I have an update pending for 17120.1, so I can see if that changes anything.

**Comment by lilgrassin** [comment]
No dice. Still seeing the same thing in 17120.

**Comment by cylonid** [comment]
> Unable to retrieve file system information for C:\Users\lillian\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/7. error = -1

Your log shows inconsistent usage of directory separators (slash vs backslash) @lilgrassin .

**Comment by bobbrow** [comment]
@uwe-h Windows doesn't actually care about the direction of the slashes, but we should probably unify them after the environment variable is evaluated.

**Comment by WSLUser** [comment]
Slash vs backslash won't matter in 17120. See this [blog](https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/). Just make sure it's all consistent (no mix and match in a path.)

As for environmental variables, `WSLENV` is your friend. See [this](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/).

**Comment by gregersn** [comment]
I experience this same problem on both Mac and with MSYS2/Mingw on Windows. 
Files that are "behind" symlinks are not found by Intellisense.

**Comment by sean-mcmanus** [comment]
@gregersn Your issue sounds completely different. Can you file a new bug and provide more repro details? Paths with symlinks work for me with includePath and browse.path and we haven't received any other reports of this. The only known issue with symlinks is with WSL, because the WSL symlinks are not natively traversable in Windows without calling into WSL (which is planned to be fixed in April). The files may not be found due to other issues, which may be fixed in our upcoming 0.16.0.

**Comment by Blealtan** [comment]
Here I repro this issue on multiple devices and multiple builds. Since build 17103 I think, I started to suffer from this issue on both my Windows Insider devices (slow ring for my PC, fast ring for my laptop), while VSCode and cpptools version both keeps latest, and remains this situation till now. RS4 has recently graduated to Release Preview status, and if anyone try the current Inside Release Preview (which I think is pretty safe even for development environment), the issue should be reproduced.

Also, here in my case (#1802), there is nothing to do with symlinks; every level in the path is able to be seen as a folder in Explorer.

**Comment by bobbrow** [comment]
I think I have a repro.  I installed 17133 and it didn't repro until I opened my bash prompt and it did a "one time upgrade".

**Comment by bobbrow** [comment]
It appears that the WSL filesystem is case-sensitive now, but since the extension is running on Windows it assumes that file casing doesn't matter.

**Comment by bobbrow** [comment]
A relevant article about this feature: https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/.  I just talked to Sven about this and it looks like there is no going back once a directory is converted and no workaround besides copying your `/usr/include` folder out of the Linux filesystem and into the Windows filesystem where it is case-insensitive until we can release a fix for this.

**Comment by WSLUser** [comment]
I was going to say something about that and did link it above. Personally I think we should have default case-sensitivity for everything just like in Linux and we only need to link legacy win32 things that still need case-insensitive file paths to whatever specifics they need.

**Comment by bobbrow** [comment]
Sorry, I didn't click on your link since I thought it was about slashes.

Ensuring case-sensitivity is a performance hit, which is why Visual Studio doesn't do it, except for user-facing content.  We are reusing their codebase.  I think we should be able to turn it on for people who need it, but there is a lot of code I need to go sift through.

**Comment by hacdias** [comment]
Same issue here after updating to April Creators Update.

**Comment by bobbrow** [comment]
I'm almost done with the fix for this. We're hoping to put out an insiders release with the fix this week. 🤞

**Comment by bobbrow** [comment]
We just published https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.0-insiders2 with a fix for this.  Please go give it a try and let us know if you have any issues with it.

NOTE: There is still an issue switching between WSL and non-WSL configs, so you may need to reload the VS Code window if you switch to/from a WSL-enabled config to a config not using WSL.

**Comment by lilgrassin** [comment]
Just tried the update and it seems to be fixed. No more errors and I'm able to peek/goto definitions/declarations and get suggestions. Linting is also working. Thanks for the prompt fix!

**Comment by lilgrassin** [comment]
SIDE NOTE: I just discovered the extension now auto-detects WSL/include paths without c_cpp_properties.json and it's working beautifully!

**Comment by hacdias** [comment]
Here's working too @bobbrow!

**Comment by flxflx** [comment]
Great, thanks a lot!

**Comment by ghost** [comment]
Major props, I was struggling for an hour to get this extension to recognize my WSL paths a week ago but couldn't make it work for the life of me. Now I just re-installed it and **it works out of the box!**. Amazing work.

**Comment by bobbrow** [comment]
Glad to hear this is working for everyone!  I'm going to close the issue now.
