### ISSUE TITLE
How to diagnose green squiggle appear under #include guard?

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1742]
Windows 10, VS Code 1.21.1, cpptools 0.16.0-insiders

I see a green squiggle under a #include guard:

![image](https://user-images.githubusercontent.com/7724321/37962993-d6a0a036-31b4-11e8-9034-67f4fbcfce6e.png)

In settings.json I do have:

`"C_Cpp.intelliSenseEngine": "Default"`

I don't know the reason for the squiggle and Intellisense gives little help.  

Please can you suggest how to identify the problem?

Could you improve the diagnostics in this area?

**Comment by bobbrow** [comment]
Open up `C:\SVNProj\Nepthys\trunk\Test\Nepthys_TestSource\Scenarios.cpp` and you will find green squiggles for the `#include` files that could not be located.  In a future release, you won't see this anymore since we'll stop trying to locate a .cpp file that includes your .h file to provide the IntelliSense context for that .h file.

**Comment by bobbrow** [comment]
Closing stale issue
