### ISSUE TITLE
go to definition not working with Scala projects

### ISSUE THREAD

**Issue by JonathanSchwob** [microsoft/vscode-cpptools#1758]
* OSX 10.12.6
    * VSCode Version 1.21.1 (1.21.1)
    * Scala support plugin 0.1.7
    * reproduce issue: open scala/play framework project with vs code, try to cmd click a definition

When using VS Code on Scala projects 'Go To Definition' functionality does not work at all. I have installed the Scala support plugin. Nothing highlights when holding CMD. Nothing appears when I type 'Go To Definition' in the cmd pallete.

If i open a javascript project this functionality works perfectly and holding CMD highlights words and I can jump to their definitions in other files.

Is this behavior intended? I'd really like to switch from IDEA to VScode for this project but this makes it difficult.

Thanks for your time, and please let me know if there are any additional details you might need from me.

**Comment by sean-mcmanus** [comment]
This the GitHub page for the C/C++ extension, which doesn't support Scala. I believe you have the wrong location. The scala extension you're referring to hasn't been updated since 2015, so you might want to try using the more recent https://marketplace.visualstudio.com/items?itemName=scala-lang.scala and filing issues at https://github.com/daltonjorge/vscode-scala/issues .
