### ISSUE TITLE
[CPPVSDBG] Debugger truncates long strings when inspecting values

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1786]
When inspecting values in the debugger, long strings are truncated, which, for example, makes it impossible to see the rest of this exception message here:

![image](https://user-images.githubusercontent.com/3168386/38302693-3c199dfc-380c-11e8-95b7-bffcb667ca43.png)

The value is also truncated if I right-click the message on the "variables" window and click "Copy Value". The value also gets truncated in the debug console, if I try printing it there. I don't think there's currently any way to view this string without it getting truncated.

I have the latest stable of VS Code (1.21.1) and vscode-cpptools (0.16.1) installed.

Right now I'm working around this by modifying the code to print the message to `std::cout` before throwing, but that's obviously not ideal..

**Comment by pieandcakes** [comment]
@aleksijuvani I assume you are using `gdb`. This looks like the default setting for `gdb` which is 200 characters. You can add a command to increase it to unlimited by using `set print elements <size>` where `size` is the number of elements and `0` being `unlimited`. 

So in your `launch.json`, add the following block to the `"setupCommands":` array:
```
                {
                    "text": "-interpreter-exec console \"set print elements 0\"",
                    "ignoreFailures": true
                }
```
to make it unlimited.

**Comment by ghost** [comment]
@pieandcakes Sorry, I forgot to mention this. I'm using the `cppvsdbg` debugger.

**Comment by callumdmay** [comment]
Was there ever a solution to this issue? Seems like the answer above is for gdb and not cppvsdbg. The truncation is a real issue when trying to copy long strings or byte arrays in the local variables list

**Comment by jemmy512** [comment]
@pieandcakes Is there any solution? LLDB also meets this problem, this is unacceptable

**Comment by pieandcakes** [comment]
@JemmyWong Any solution for truncation in `cppvsdbg` will be in the debugger itself and will not apply to `lldb`. You can try the solution for `gdb` for `lldb`

**Comment by JoffreyAlto** [comment]
Hello @pieandcakes : Is there any update about this issue ? I've also been using CPPVSDBG for a while and still can't copy large string values. Since I'm not using GDB, I couldn't figure out any kind of parameter that would allow to extend that characters limit. 

This is really annoying, since copying and analyzing data from the variables tab is one of the major features for a real-time debugger. Thanks in advance for your response !

**Comment by pieandcakes** [comment]
@JoffreyAlto I haven't had time to investigate yet, but it is on my list.

**Comment by laengand** [comment]
@pieandcakes  Any updates on this issue? :-)

**Comment by tklajnscek** [comment]
Just hit this issue myself. It's pretty bad that VS Code doesn't seem to have a nice multi-line string view, but then this just makes it completely useless when debugging strings :)

**Comment by bartwalczak** [comment]
Same here. `cppvsdbg`

**Comment by eshulankina** [comment]
Hi, Do you have any updates for this issue regarding `cppvsdbg`?

**Comment by mathforlife83** [comment]
@pieandcakes This is an important feature that is not working, first reported in 2018, what's the status update on it, and would it be possible to prioritize this bug?

**Comment by kushgh** [comment]
start debugger, in your debug console write:
`-exec set print elements 1000`

You can modify 1000 to any other number. 
0 signifies no limit(not recommended as some variables can be nasty).

![image](https://user-images.githubusercontent.com/110026629/191234722-e093d8ab-bd36-4e31-8392-9a26ea43de33.png)

**Comment by handledexception** [comment]
Is there a solution to this on Windows when debugging with cppvsdbg using the MSVC debugger?

**Comment by kushgh** [comment]
@handledexception 
What does writing 
`-exec set print elements 1000`
in the debug console of MSVC give?

**Comment by nallanavijayakumar** [comment]
Any update on this issue? Any workaround for cppvsdbg?

**Comment by sean-mcmanus** [comment]
@vijay-563 We don't have an update on this issue. One "workaround" may be to log the string value to stdout or a file.

**Comment by jay1975h** [comment]
@sean-mcmanus Any chance to prioritize this issue, a debugger should be able to inspect long strings. For me, it feels like a high-priority bug

**Comment by sean-mcmanus** [comment]
@jay1975h I'll let the debugger team know that this bug is the most upvoted debugger bug.

**Comment by JoffreyAlto** [comment]
To people here still looking for a resolution, since there's no update on the issue I figured out some kind of way to get copy large strings. Using the "Watch" or "Variable" tab when in debugging feature, identify the string you want to copy then click on the "View binary data" icon, at the right of the string value as showed below.

![CPPVSDBG - 01](https://user-images.githubusercontent.com/55133647/219594490-9cea6432-f31d-4716-b4ea-f49618edecec.jpg)

Then now the tab "memory.bin" is open, just copy your value from the "selected text" section using your mouse cursor or a simple click at the beginning of the string, and shift+click at the ending of your string.

![CPPVSDBG - 02](https://user-images.githubusercontent.com/55133647/219595024-be66ff78-0751-48eb-bc5f-39cc64fbc085.jpg)


Copy it, then you will be able to paste the string value to another text support.

**Comment by abdelmaged** [comment]
Any updates ? Please prioritize this.

**Comment by swayhead** [comment]
Same issue here.

**Comment by mathforlife83** [comment]
@pieandcakes @sean-mcmanus @vscode @Colengms

I don't understand this at all, you wrote that this is most upvoted debugger bug yet nothing happens. The bug was open Apr 4, 2018, why is not being fixed, how can the developers at Microsoft do nothing?

You are committed all kinds of useless stuff, for example -> Fix change "eg." to "e.g.".  Fix the things that are important instead.

**Comment by hharshada** [comment]
We have determined that your valuable suggestion has a broad community impact and will improve the product experience. We have added the feature to our roadmap and will keep you updated soon as we make progress. We highly appreciate your contribution in making our product better.

**Comment by tklajnscek** [comment]
Is this actually fixed? I still see strings truncated to ~200 characters in hovers, watch & when evaluating the string in the debug console... 

VSCode: 1.88.1
CppTools: 1.19.9

**Comment by sean-mcmanus** [comment]
@tklajnscek Are you using cppvsdbg or cppdbg? It's working for me with cppvsdbg. Are you referring to std::string? Which implemention? MSVC?

**Comment by tklajnscek** [comment]
@sean-mcmanus 

- cppvsdbg
- either std::string or a just a plain char*
- compiled with CMake/Ninja using MSVC 19.37.32824.0

![image](https://github.com/microsoft/vscode-cpptools/assets/8321194/6e6f70cf-916f-4ce3-aa3d-8bb8b679a0bf)
![image](https://github.com/microsoft/vscode-cpptools/assets/8321194/11bdd184-f768-4989-bf89-0b16c1590d59)
![image](https://github.com/microsoft/vscode-cpptools/assets/8321194/f3d3514b-4d7d-43d0-bc28-99c2a2489c1d)

**Comment by sean-mcmanus** [comment]
@tklajnscek I see -- I was looking at the data as an array of characters and the characters are all visible in the debugger that way. I'm not sure if that is intentional or not.

**Comment by tonyriviere88** [comment]
Any chance the original feature actually implemented?
For me, the main use case is primarily to be able to copy the whole string, like in Visual Studio.

**Comment by metacpp** [comment]
@sean-mcmanus 

Is there any plan to fix this issue ? The string value is still truncated when debugging with `cppvsdbg`.
