### ISSUE TITLE
Improve error message for missing ';' at end of class declaration?

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1788]
Windows 10
VS Code: 1.21.1
C++ Extension: 0.16.1

Just wondered whether the error message could be improved for this error (missing semi-colon after closing bracket of class declaration)?  Took me a while to work out what was wrong.

![image](https://user-images.githubusercontent.com/7724321/38313749-b05587f2-381c-11e8-865b-e0c11cb4c87b.png)

**Comment by sean-mcmanus** [comment]
I'm not reproing that error message. In normal conditions, we do show "expected a `;`". I believe the issue is the code the comes after the class is causing it to be parsed in some strange way. Can you provide that code so we can see the repro? Or maybe the code beforehand could be causing this as well...supposedly some could with the "inline" modifier?

![image](https://user-images.githubusercontent.com/19859882/38335059-fb9f1062-3811-11e8-9d69-465ebafd920b.png)

**Comment by daldr-ntml** [comment]
Hi Sean, yes it seems to be the code coming afterwards. Perhaps my syntax is incorrect but I don't believe so. Here is the rest of the code:

![image](https://user-images.githubusercontent.com/7724321/38357827-9043fa26-38bb-11e8-91a7-8e30d82b1f37.png)

**Comment by sean-mcmanus** [comment]
The "inline" is being associated with the class due to the missing ";". The "void" on the next line has the error about "expected a ';'". I agree that ideally the 1st error would not appear, but the behavior is inherited by (the same as) VS 2017 -- you or I could file a bug with them, but I doubt they would get it fixed because it's too low priority given the other more severe issues they're trying to fix.

**Comment by daldr-ntml** [comment]
Thanks for your reply. I'll just close the issue.
