### ISSUE TITLE
Add to "includePath" support for paths relative to the current opened file path 

### ISSUE THREAD

**Issue by esmirnov** [microsoft/vscode-cpptools#1796]
In my project many components are composed in following structure:
```
Component/
  Component.h
  impl/
    Component.cpp
```
in Component.cpp  
```#include "Component.h"```
Each file in component can include files from the same component without specifying path from the root.  I can't find a way to specify include path for this scenario. 
Thank you!

**Comment by bobbrow** [comment]
I'm not sure I understand exactly what you're asking, but if this folder structure is in your workspace folder, you should be able to click on `"Component.h"` in your source file and a lightbulb will appear.  Click on that lightbulb and it should give you the option to add `Component/` to the include path.

You wouldn't want to do `#include "../Component.h"` because that would require you to add `Component/impl/` to the include path, which probably isn't what you want.

**Comment by esmirnov** [comment]
Hello Bob,
That is exactly what I want to avoid. There are hundreds components. I wouldn't want to add all of them to include path. More detailed example,
```
Sources/
  Component1/
    Component1.h
    Types.h
    impl/
        Component1.cpp
  Component2/
    Component2.h
    impl/
      Component2.cpp
```
If Component1.cpp needs Component1.h (header from the same component) then it includes it as
```#include "Component1.h"```
If Component1.cpp needs Component2.h then it includes it as
```#include "Component2/Component2.h"```

If there is a known way to support this scenario I would be happy.

**Comment by sean-mcmanus** [comment]
This should be fixed after we implement recursive includes.
If you can generate a compile_commands.json (i.e. via cmake) that would be another workaround.
Did you have another idea for a solution? Automatically adding the parent path to the include path seems too unusual to do.

**Comment by esmirnov** [comment]
Recursive includes should work. Another option is to allow relative include paths, like ```..``` or ```${fileDirname}/..``` and use it only if searching file for the "Quoted form" include, but skip for "Angle-bracket form".

**Comment by fr43nk** [comment]
This would be very helpful. In my c_cpp_properties.json file I set the includePath as follows: 
`includePath : [
"../h",
"../../incs"
]`
So the path has to be interpreted relative to the current open cpp file.

**Comment by fr43nk** [comment]
Are there any news about this request?
Would be nice to have this working. Right now there are a lot "include not found" error messages although the file exists

**Comment by bobbrow** [comment]
@fr43nk, would `"${workspaceFolder}/**"` work for you?  This adds everything under `${workspaceFolder}` to the potential include path.  The original issue is resolved with recursive includes, but we can move your request to another issue if you think that recursive includes won't address it.

**Comment by fr43nk** [comment]
@bobbrow I'm not quite sure if this is the right solution for me. What I want (maybe that's not possible either): While editing a file, the intellisense should only show the files that are available from that file.

Let me explain what my folder structure looks like:
```
/Project/
/Project/incs/
/Project/module1/h
/Project/module1/src
/Project/module2/h
/Project/module2/src
```

So if I'm in ```/Project/module2/src/file.cpp``` Intellisense should only show things that are located in 
```
/Project/incs/
/Project/module2/h
/Project/module2/src
```

That's why my IncludePath configuration in the c_cpp_properties.json looks like:
```
"includePath": [
  "../h",
  "../../incs"
]
```

Or is there another way to achieve this with another configuration?

Thanks

**Comment by sean-mcmanus** [comment]
@fr43nk What do you mean by "intellisense should only show the files that available"? IntelliSense should already only show stuff that is accessible from the current translation unit, taking the include paths into account. Recursive includes relies on the "path" in #include "path" to be unique, otherwise it could choose the wrong file, but it will look relative to the current directory first.

**Comment by esmirnov** [comment]
Hello! Could you describe how the recursive includes will work in my scenario? Does it just look for the file inside each directory under ${workspaceFolder}? Thank you!

**Comment by sean-mcmanus** [comment]
Yeah, if you use ${workspaceFolder}/** then for every #include <path> it will go through and see if the existing non-recursive includes are able to find it; otherwise, it will recursively try to find a path that satisfies the include and add that path. If you set your C_Cpp.loggingLevel to "Debug" and then open a file that relies on recursive includes, you should see in the C/C++ section of the Output pane which include was chosen recursively. Our 0.17.5-insiders has some perf optimizations and 0.17.5 will have more optimizations if you notice performance issues.

**Comment by fr43nk** [comment]
So the recursive algorithm also finds the correct include file even if it is located parallel to the current directory? Like:
```
/Project/module2/h/myfile.hh
/Project/module2/src/myfile.cpp -> #include "myfile.hh"
```

**Comment by sean-mcmanus** [comment]
Yes. In that case, "/Project/module2/h" would be added to the include path -- only for the myfile.cpp though (or other source files that reference the file).

**Comment by harmic** [comment]
Was this closed as considered fixed by the use of recursive includes? I don't think that really fixes it. If you have two different header files with the same name in different directories, then it is likely that the wrong file will be included.

BTW: for gcc at least, if quotes are used around the name of the file being included, then the directory containing the source file is searched by default (https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html).

**Comment by sean-mcmanus** [comment]
@harmic Yes. Depending on the ordering of the includePath, the wrong includePath could be used. You could add particular paths manually to get them used before the recursive paths. You could create a new issue if you want.

**Comment by harmic** [comment]
@sean-mcmanus My use case is a little simpler than the OP of this issue - I have some files which are trying to include headers which exist in the same directory as the source file.

I started writing a new issue, but then I saw this one #2031. The last comment on this one says that "The IntelliSense engine already adds the current folder automatically so any file that uses #include "header.h" should find header.h if it's in the same directory as the source file.". Is that actually correct? It does not seem to be the case for me.

**Comment by sean-mcmanus** [comment]
@harmic Yes, the current directory is added by to the search path used by IntelliSense whenever the `#include ""` syntax is used (not `#include <>`). If that is not working, could you file a new bug with more repro details? In particularly, can you check if it actually is not able to find the file listed in the `#include ""` or if the missing file is a dependency of that.

**Comment by Spongman** [comment]
i'm having a similar issue. i have a folder that contains several sub-projects each with its own set of recursive Makefiles and each with its own set of include directories. when I'm editing a file "a/a.cpp" i need the includePath to be configured for sub-dir "a", when i'm editing "a/b/b.cpp" the includePath should be for "a/b", and completely different again when i'm editing "c/c.cpp". i have many include files with duplicate names (think 'stdafx.h') and i'm constantly frustrated when vscode opens the wrong one.

**Comment by bobbrow** [comment]
Yes, recursive includes don't work great when you have multiple headers with the same same in the project.  But if you use quote syntax for including these files, the search will start off relative to the source file.  I'm not sure how your project is organized, but if your "stdafx.h" file is in the same directory as your source files, you would just do this:
```
#include "stdafx.h"
```
instead of this:
```
#include <stdafx.h>
```
And recursive includes won't pick the wrong files.

You also mention Makefile...  We are working on an extension that extracts build information from Makefiles and uses it to supply the IntelliSense configuration for you (e.g. never mess with `c_cpp_properties.json` again).  If you would like sign up for early access, I can send you an invite to the private repository where this is being developed.  We are looking to get some feedback about how well it works for people before we publish it on the Marketplace.

**Comment by Spongman** [comment]
no, there are include directories that are specified in the Makefiles. i need to be able to specify which set of include directories to use for each subdir. I'm not interested in the auto-Makefile thing, sounds like trying to solve the halting problem... it's not going to work for me, i'd much rather have proper configuration than some mostly broken guessing game.

**Comment by sean-mcmanus** [comment]
@Spongman The Makefile Tools extension just reads the Makefile and sends the correct configuration for IntelliSense, similar to what the CMake Tools extension does for CMake builds. I tried it on a Linux repo that used Makefiles and it was working for me.

Another option might be to use a different workspace folder for each subdirectory.

**Comment by EricHripko** [comment]
Could I get access to the Makefile extension please? Would love to help out by giving it a test spin and providing feedback.

**Comment by bobbrow** [comment]
@EricHripko certainly.  Look for more details here: #1587
