### ISSUE TITLE
Error showing in problems though compilation occurs.

### ISSUE THREAD

**Issue by vamsis-adapa** [microsoft/vscode-cpptools#1831]
Below is a simple c  program.
After finishing typing the following error pops up in problems "expression must have a constant value(6,11)" with an error squiggle under 'n' in a[n].
However this compiles fine and shows no error.
I use a Mingw gcc compiler.
 

#include<stdio.h>
int main()
{
    int n;
    scanf("%d",&n);
    int a[n];
}

**Comment by ryan-feeley** [comment]
That is valid c99 code (variable length array with value determined at run-time, rather than compile time). As you may know, it is not valid c++ code. However, GCC will accept it when you are compiling for c++. See [6.19 Arrays of Variable Length](https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html).

Since you're using the Mingw gcc compiler, I assume you are developing on Windows. I don't know the details, but the error squiggles in vscode are generated by either a clang-based or msvc-based parser. They don't use your compiler directly. There is a setting in c_cpp_properties.json to specify the intelliSenseMode.

If your goal is write c99 compliant code, I think you can follow this link to figure out how to set up your system to show errors squiggles in that context: [MinGW.md ](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md)

**Comment by sean-mcmanus** [comment]
@leDarkKnight Were you able to get things working? @ryan-feeley gave good advice. I can also observe the error when my settings are incorrect, but it goes away after setting the intelliSenseMode to clang-x64 and setting the compilerPath to `"C:\\MinGW\\bin\\gcc.exe"` (or `"...\\mingw64\\bin\\gcc.exe"`. It looks like we should update our MinGW docs to take into account the new compilerPath setting (which will enable more compiler defines).

**Comment by vamsis-adapa** [comment]
Yes I was able to get things working. Thanks for the help.
