### ISSUE TITLE
compilerPath in c_cpp_properties.json: no effect?

### ISSUE THREAD

**Issue by wimalopaan** [microsoft/vscode-cpptools#1843]
I tried to modity the setting:

"compilerPath": "/usr/bin/g++ -fconcepts",

like this. But this doesn't seem to have any effect.

**Comment by bobbrow** [comment]
There could be a bug here.  Did you try reloading the window?

**Comment by sean-mcmanus** [comment]
-fconcepts is a flag that gcc understands, but our IntelliSense compiler doesn't have support for C++20 concepts yet, and when it does, we would have to translate the flag to a flag our compiler understands. If things like `__gnu_linux__` and `__GNUC__` are defined then it means the /usr/bin/g++ part was understood -- otherwise, it means your g++ compiler doesn't understand the -fconcepts flag (causing the define querying to abort).

**Comment by wimalopaan** [comment]
This is the test code:

```
#include <iostream>

int main() {
    std::cout << __PRETTY_FUNCTION__ << std::endl;

    std::cout << "clang:" << __clang_version__ << std::endl;
    std::cout << "gnu: " << __GNUC__ << std::endl;
}
```
Regardless the setting of "compilerPath" both symbols __clang_version__ and __GNUC__ looks defined in the editor. Clearly, compiling with g++ or clang++ gives an error in the one or the other line.

I tested it with restarting the vs-code.

Versions: vc-code: 1.22.
c-cpp-extension: 0.16.1

**Comment by sean-mcmanus** [comment]
That is because we force `__clang_version___` to be defined as part of the clang-x64 mode -- we have a work item to add a separate gcc mode that doesn't do this. If you manually remove the "--clang," flag from the msvc.*.json file that matches your OS you can force it to not use clang mode and `__clang_version__` won't be defined, but we haven't thoroughly tested that scenario yet.

UPDATE: Oh, wait , removing --clang puts it into msvc mode, which isn't what you want -- replacing it by either --gcc (for c) or --g++ for (c++) does it.

**Comment by wimalopaan** [comment]
Well I can't find a msvc.*.json file. I only have c_cpp_properties.json. In this file there is an option compilerPath which defaults to "/usr/bin/clang". 

Do you mean the option "intelliSenseMode": "clang-x64" which is also in this file?

I wonder what the purpose of the option "compilerPath" is. My first impression was, that this is the compiler that is called internally by the extension to check each file for errors. But it looks like this is not the case because changing it to g++ (with flags) doesn't do anything.

Do you have an "internal compiler" for the "on-the-fly" checking of the open files?

**Comment by sean-mcmanus** [comment]
The msvc.*.json files are next to the `Microsoft.VSCode.CPP.Extension.*` binary (your OS usually has a way to locate the path of a running binary). Our compiler runs in our binary and we pass flags to it to change it's behavior to conform to clang/gcc/cl/etc.. We use the compilerPath to get the correct compiler includes and defines.

**Comment by wimalopaan** [comment]
I suppose you are using the MS-Compiler? So, it is actually not possible to use concepts in the code because this isn't included into your compiler. As well as modules (included into the real clang). 

Is your (probably MSVC) compiler fully c++17 compliant? Does it implement features of c++2a?

Is there a way to use other compilers than yours?

**Comment by sean-mcmanus** [comment]
No, we don't use the Microsoft compiler cl.exe, we use the EDG compiler (see https://www.edg.com/c/features ). Concepts and modules are C++20 features that aren't implemented yet. We don't have 100% full C++17 support yet. We don't support other compilers currently.

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
