### ISSUE TITLE
Is IntelliSense working as expected?

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#189]
Here's a test case where I have `MotorIdxU8Ptr` which is a local U8\* variable and `CanOpenMyriad_Struct` which is a global struct.

With `"C_Cpp.autocomplete": "Disabled"`:

![disabled](https://cloud.githubusercontent.com/assets/1297882/18120842/092f34ac-6f62-11e6-822f-63143e615dac.gif)

In this example, fuzzy search helps me complete my symbol names but doesn't present me with any IntelliSense.

---

With `"C_Cpp.autocomplete": "Default"`:

![default](https://cloud.githubusercontent.com/assets/1297882/18120661/f28dee92-6f60-11e6-88e2-63d4b2bc6655.gif)

As you can see, fuzzy search doesn't work. But neither the local nor the global variable gets picked up even when I'm typing in CamelCase. All members (although not context aware) gets picked up after a dot, though.

Besides context awareness (which I reckon is still in the pipeline) I would expect my symbols to get picked up properly. Also, fuzzy search would be nice :)

---

Is this how it's supposed to work? Seems like it's lacking.

**Comment by MrTortoise** [comment]
i just asked this question
http://stackoverflow.com/questions/39251274/visual-studio-code-is-not-autocompleting-std-in-c-on-ubuntu
Appears i met the same issue, i get the same results from disabled

(how did you do that screen grab image?) (thanks!)

**Comment by csholmq** [comment]
(LICEcap)

**Comment by csholmq** [comment]
Still no context awareness. Is this coming along?

**Comment by sean-mcmanus** [comment]
Yes, it's being worked on.

**Comment by bobbrow** [comment]
I'm going to dupe this issue to #13.  As of 0.12.0 we support semantic autocomplete when `.`, `->`, or `::` is typed.  Global autocomplete is not ready yet and that's what issue #13 is tracking.

**Comment by bobbrow** [comment]
To clarify a bit, the first example here will work with the Tag Parser (which is the engine providing the suggestions), provided the document has been saved.  If you have just typed in a new function and haven't saved your changes yet, the new function will not appear in the suggestion list.

The second example will never work with the Tag Parser because we don't add local variables into the database.  This scenario will be enabled by the new IntelliSense engine in a future update.  If you are using the new IntelliSense engine already, we actually still get autocomplete results not prefixed with `.`, `->`, `::` from the Tag Parser.

**Comment by csholmq** [comment]
Is there a roadmap for these things? It would be nice to know what to expect for each release.
