### ISSUE TITLE
How to handle multiple projects in a common directory?

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1892]
I'm working on Windows with VS Code 1.22.2 and cpptools 0.17.0-insiders.

I have a project directory that looks like:

    /--proj--|--.vscode
                    |--c_cpp_properties.json
             |--Common
             |--ProjA
             |--ProjB

I have setup my include paths and defines in configuration Win32 of c_cpp_properties.json for ProjA, but I also want to be able to work on ProjB which has different paths and defines.  But, ideally, I want to open the entire tree shown above, whichever project I'm working on.

What features does cpptools provide to help me?

For example:
1) Can I specify more configurations and manually select a particular one?
2) Can I select a particular c_cpp_properties.json file, rather than the one in the project root?
3) Anything else?

**Comment by bobbrow** [comment]
Option 1 will work.  You can have as many configs in the root **c_cpp_properties.json** as you want.  The extension provides default configs named after the platforms we support when you open a folder, but I think many people have interpreted that to mean that you can't create any custom configs.  You can select which config is active by clicking the text in the status bar or using the "C/Cpp: Select a configuration..." command.  If you switch between configurations a lot, you may want to add a key mapping for that command.

Option 3.  You can also experiment with VS Code's multi-root feature and open both folders in the same window (each with their own **c_cpp_properties.json**).  That should give you automatic switching of configs when you open files under the respective folders, but that would require a **c_cpp_properties.json** for `Common` as well since you would also have to open that folder to see its contents.

**Comment by daldr-ntml** [comment]
Thanks for your answer. I am experimenting with your option 3 and it seems to fix my situation.  However, I am uncertain of the rules.  I tried having a c_cpp_properties.json in /proj/.vscode and in /proj/ProjB/.vscode but ProjB then didn't behave as expected. Deleting /proj/.vscode fixed ProjB.

Does cpptools search upwards from the opened file or downwards from workspace root for a c_cpp_properties.json?

Would it be appropriate to have c_cpp_properties.json in the workspace folder, to provide default include paths for folders not having one, for example, in my case, Common?

Is the behavior defined in any user documentation?

**Update:** Actually things are not working right. When I open a file in ProjB include paths were not resolved. Intellisense suggests adding paths to c_cpp_properties.json, which I accepted, but it adds them to /proj/.vscode/c_cpp_properties.json, not the one in ProjB.

**Comment by sean-mcmanus** [comment]
The expected scenario that we handle correctly is when all the workspaces folders are unrelated to each other and one workspace folder is not a child of another one (e.g. /proj/ProjA and /proj/ProjB should work). Maybe we could fix this via making sure the deepest child folder is chosen first. Should we change this to a feature request?

**Comment by daldr-ntml** [comment]
Thanks for your answer Sean.  I'm afraid I couldn't get the multiple c_cpp_properties.json file (one per folder) solution to work.  And I can't really report the problem easily.  

So I settled instead on using multiple configurations in a single c_cpp_properties.json file.  The disadvantage of that solution is that some problems are reported for files belonging to the deselected configuration.  But I think I will have to live with that.

**Comment by daldr-ntml** [comment]
Answered.
