### ISSUE TITLE
Inactive Regions coloring

### ISSUE THREAD

**Issue by Kronuz** [microsoft/vscode-cpptools#1907]
VSCode Version 1.22.2
C/C++ extension Version 0.16.1

`dimInactiveRegions` option should use the same coloring as comments in the active theme, when using `editor.renderWhitespace` that also should maintain theme coloring.

Inactive regions look awkward otherwise:

![coloring](https://user-images.githubusercontent.com/56894/39479515-1c9ae8a8-4d2b-11e8-9956-f710996c0e8f.png)

**Comment by sean-mcmanus** [comment]
I think we're going to use opacity to dim the text: https://github.com/Microsoft/vscode/issues/43004 .

**Comment by Kronuz** [comment]
That sounds reasonable... but if you use opacity as it is now, whitespaces will look differently from indentation guides. In the example above both indentation guides and whitespaces have a custom color (same color both), however indentation guides are currently keeping the color as they should, but not whitespaces.

**Comment by bobbrow** [comment]
When we switch to opacity we won't change the original color anymore.  But in that case I think the opacity would still affect those characters.  I think the case could be made that VS Code shouldn't apply decorations to whitespace characters since they are not technically part of the file contents.  I wonder if it's just something they overlooked.  It would be a real nuisance if we had to break up all of our text decorations into words.

**Comment by sean-mcmanus** [comment]
This is fixed with 0.17.5-insiders at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.5-insiders .

UPDATE: Fixed in 0.17.5.
