### ISSUE TITLE
IntelliSense is missing declarations of _builtin_* functions

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode-cpptools#1931]
I'm trying to get squiggle-free and one I have is `__builtin_ia32_pause` undefined (comes from gcc).

Previously I used to work around this by having in my `c_cpp_properties.json`:
```json
            "defines": [
                "__builtin_ia32_pause()"
            ],
```
and after I started using awesome `compileCommands` feature I got this error message back.

I ran with `C_Cpp.loggingLevel: "6"` and don't see this define sent to the engine.

Is this scenario supposed to work? Is there other way to fix such cases?

**Comment by bobbrow** [comment]
Which compiler are you using?  The extension attempts to query your compiler for the built-in defines, but there's a possibility that we're having trouble parsing the compile_commands.json file to get the compiler info.  If you can share one of the entries from the json file, that might help us see what is going wrong.  You can also try setting the `"compilerPath"` property in **c_cpp_properties.json**.  In the [insiders build](https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.0-insiders2) we published, there is additional logging that will show which compiler we ended up picking so that might help too.

**Comment by ytimenkov** [comment]
@bobbrow Sorry didn't and all info initially.

I use gcc and cpptools find it currently (we trying latest insiders build with fixed "arguments").

`__builtin_ia32_pause` is not a define but rather intrinsic function which generates `pause` assembly instruction. There are many such functions and it's not necessary that cpptools should understand them all: https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/X86-Built-in-Functions.html

Defining it seemed a reasonable workaround: I can't  define it in my build system (so it appears in defines sent to language server).

I need it only for Intellisense.

Hmm... Maybe I can put it into `cpp.hint`...

**Comment by bobbrow** [comment]
cpp.hint is for the code browsing service, so that won't affect squiggles.  It looks like our IntelliSense engine might have support for this, but it's not being compiled in.  I can try and see if that resolves this issue.

In the meantime, if you want a workaround for this issue, you could create a header file with the declaration for the \_builtin\_* functions you want and then use the `"forcedInclude"` property in **c_cpp_properties.json** to have that header auto-included for IntelliSense in all of your source files.

**Comment by bobbrow** [comment]
We added support for the \*\_builtin\_\* functions to IntelliSense last year, but lost track of this issue.  Please let us know if you need anything else.
