### ISSUE TITLE
Slow parsing and code completion for a huge codebase

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode-cpptools#1938]
Opening an issue per this twitter thread: https://mobile.twitter.com/darktears/status/992535283429097472

"Slow parsing and code completion for a huge codebase. I really try hard to use @code but it just doesn’t scale for a project like Chromium."

"Oh yes, you open chromium git checkout and then IntelliSense will use 100% CPU for the next hours. Then even when done, code completion takes 100% CPU usage to return most of the time nothing. @QtCreator parses  the code base with clang code model in ~4 minutes."

"And it gives me good enough (mostly accurate) code completion and navigation between symbols, file and headers is quick. That’s all I’m asking. In @code navigating to an header sometime take minutes (with progress blue bar). I love @code for all my web code."

**Comment by darktears** [comment]
This is the repository : git clone https://chromium.googlesource.com/chromium/src

Feel free to reach out if you have any question.

**Comment by sean-mcmanus** [comment]
I'm not reproing any perf problem with chromium. Are you using the 0.17.0-insiders2 build with recursive includes? Are you seeing the red flame or database taking a long time? I'm seeing CPU usage go to 0% after 15 seconds after the initial database is built. Code completion is instantaneous too. It finds about 340000 files. You could temporarily set the loggingLevel to the hidden value of "6" to see if it's parsing files in folders it shouldn't be (i.e. build output folders), which could be added to the files.exclude or search.exclude list.

**Comment by darktears** [comment]
I'm using the stable build. Also make sure your run gclient sync on the repo so you fetch all the dependencies.

I'll give you more details on Monday.

**Comment by darktears** [comment]
I'm on macOS btw.

**Comment by sean-mcmanus** [comment]
Yeah, I've never gotten gclient sync to run. It complains about "No SCM found" after I ran gclient config.

**Comment by darktears** [comment]
@sean-mcmanus 
Here are the instructions :
https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md

You can stop after Get the code. You don't need to run any gclient config anymore. Starts from a fresh checkout.

After you have a full checkout then here what I do : 
- Open VSCode
- File - Add Folder to Workspace
- Select the "src" directory of the chromium checkout
- Open chrome_content_browser_client.cc with ctrl+k
- On top of the file click on any header and try to navigate to it (Go to Definition). Then starts the progress bar in blue and you wait 1 minute or so. (You may need to fix the includePath but that doesn't help). See in the terminal the CPU usage.

Regardless of the manipulation above the indexing kicks in few minutes after adding "src".

![image](https://user-images.githubusercontent.com/739895/39723630-44b13dcc-51fb-11e8-8003-2ffb2461371a.png)

Here are my extensions : 

![image](https://user-images.githubusercontent.com/739895/39723729-8e3c33c0-51fb-11e8-9d34-186831cbd80b.png)

**Comment by darktears** [comment]
And yes I'm seeing the red flame.

Ignoring the build output is also not helping.

My version is 1.23.0 (1.23.0)

**Comment by sean-mcmanus** [comment]
Okay, thanks for reporting this bug and helping with the repro. I'm reproing the issue now -- it's not a "tag parser" (symbol database) issue. The 180k files in the workspace are parsed normally (~500-600k files are scanned in a few seconds after the initial parsing). The IntelliSense (red flame) parser is hitting a crash with that particular file on "file open" (after running for 1 minute and getting up to 1.6 GB) -- this is not what "normally" happens. The crash is a regression from VS 15.5 (last October), which I filed a bug for 7 months ago. It was the 3rd highest hitting crash for us a month ago when I sent the VC++ team an email asking them to fix it. We didn't have a repro before, so maybe this repro will help them fix it. If you check your ~/Library/Logs/DiagnosticReports folder you should see a crash log with "have_member_access_from_class_scope" on the crashing thread. It's possible the slowness before the crash occurs is "by design" for such a large translation unit (not sure yet). We've tested with chromium in the past, but I hadn't synced in a year or so and different files get different results so I haven't seen it this bad before. I'm not sure what the "using 100% CPU for hours" repro is though.

**Comment by darktears** [comment]
I think the bug is what fool me to think that it takes 100% for hours. Because I’m editing/navigating code it keeps trying to do what you describe eating up the CPU and memory and thus constantly spinning the fan.

Btw the bug is not located to this particular file (it was just an example). I’m unsuccessful in most files.

Can you also reproduce the slow “navigate to definition” whenever you click on a “#include”. This is a productivity killer for me.

Also are you able to have any completion working after the initial parsing? For e.g. in the file I mentioned. Or do you think it doesn’t work because of the bug you’re mentioning.

Thanks for the help btw, appreciated.

**Comment by sean-mcmanus** [comment]
I got IntelliSense working with about_flags_unittest.cc (auto complete and IntelliSense updating is fast), but lots of other files are having a hard time finding the #include headers, but aren't crashing. For example, I'm not able to locate "base/allocator/features.h" -- is that file created in the build process? Also, it can't find "content/public/common/window_container_type.mojom.h", etc. Looks like something needs to be done to get that file.

Go to definition will get blocked if the red flame is present (causing it to seem slow), but I think we plan to fix that soon (next release?).

Also, you probably want to keep the files you navigate to open instead of using the "Preview" mode which closes/opens files a lot, causing the IntelliSense to restart over and over.

Completion won't work if the IntelliSense process has crashed (and editing might respawn the IntelliSense process, causing more CPU usage until it crashes again). You can get the Tag Parser completion via changing the intelliSenseEngine to "Tag Parser" (you might have to do a reload window after making that settings change).

Also, I figured out a way to get it not to crash. I added this to my include path:
`
                "${workspaceFolder}/testing/gtest/include",
                "${workspaceFolder}/third_party/libxml/src/include",
                "${workspaceFolder}/third_party/libxml/linux/include"
`.
However, after that, I'm seeing a ton of include file not found errors (with intelliSenseEngineFallback set to Disabled), and auto-complete is initially fast when there's no red flame -- however, after an edit the red flame is kicking in and causes everything to stop working, which seems to be the performance problem you're hitting -- I suspect the slowness is caused by the include files not being found, causing the parser to have problems (so, the crash is a separate issue from the slowness). If you can't get the include paths set correctly so that it can find the files, I would use the "Tag Parser" mode.

Let me know if you see any cases of a slow "Updating IntelliSense" with a translation unit that has all the include files found.

**Comment by iron-man-forever** [comment]
does cpp_tools parse all directory if configure like this
"name": "Mac",
            "includePath": [
                "${workspaceFolder}/*",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/usr/include",
                "${workspaceFolder}",
                "${workspaceFolder}/cc",
                "${workspaceFolder}/cc/output"
            ],
            "defines": [
                "_DEBUG"
            ],

**Comment by sean-mcmanus** [comment]
@CaiHuan I don't understand what you're asking. You probably want to see your browse.path to ${workspaceFolder} as well. See https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md .

**Comment by Leedehai** [comment]
I'm sorry, but what do (1) the red flame and (2) database icons in the right bottom mean, respectively?
In my experience, IntelliSense for C++ files stopped working (with the red flame) when I'm studying the codebase of Clang (open the whole project, not just a single file, and I use peek/goto  definition/declaration a lot). The bug does not happen often, though. Restarting VSCode should be fine.

**Comment by sean-mcmanus** [comment]
@Leedehai Red flame is intellisense processing for the open file, database icon is the tag parser processing for the browse.path. 0.17.7 fixed some bugs that could intellisense failures and dangling processes.

**Comment by michelleangela** [comment]
Closing this issue.

If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate your issue.
