### ISSUE TITLE
updating intellisense 

### ISSUE THREAD

**Issue by changmu811** [microsoft/vscode-cpptools#1953]
cpptools 0.17.0  Open multiple  .cpp files at the same time.  updating intellisense  to stop working.

**Comment by sean-mcmanus** [comment]
@changmu811 What OS are you on? What do you mean by "stop working"? Is CPU usage 0% or 100% for Microsoft.VSCode.CPP.IntelliSense.Msvc? @bobbrow Have you gotten a repro yet?

**Comment by sean-mcmanus** [comment]
@changmu811 Are you using "**" recursive includes? If recursive includes is used and multiple files are opened quickly, the performance can be so slow that the IntelliSense processes get back logged. I see 1 process using 100% CPU and the rest using 0% CPU...eventually the process using CPU changes...and then finish.

@bobbrow Looks like we're not canceling the error squiggles requests after a file is closed, causing a backlog to build up if too many files are opened quickly.

**Comment by ronitt** [comment]
I know this issue is over two weeks old, but I am having the same issue on Windows 10 64-bit. The Microsoft.VSCode.CPP.IntelliSense.Msvc process is at 0% and the flame icon is visible in VSCode reporting that it is updating and seems to be doing so indefinitely. This seems to be a complete deadlock. Sometimes Intellisense is working for a short while and then the process seems to go into deadlock. This seems to be a recurring problem over several releases as I was browsing through them.

**Comment by bobbrow** [comment]
We fixed the major source of deadlocks in 0.17.1 (including the scenario mentioned by the OP). What you are reporting sounds like something different.  Can you open a new issue?  Let us know if you are using a recursive includePath or not.

**Comment by ronitt** [comment]
I have created a new issue. New issue: #2039

**Comment by bobbrow** [comment]
I believe we fixed this deadlock issue. Please let us know if you are still hitting this issue.
