### ISSUE TITLE
"-exec" GDB commands do not update VS Code's view

### ISSUE THREAD

**Issue by mooware** [microsoft/vscode-cpptools#1980]
I'm using this extension for debugging with GDB on Linux. When using "-exec" in the debug console, GDB commands that modify the debugger state do not seem to update VS Code's views.

For example, when stepping forward with "-exec next" or "-exec advance", VS Code will not show any change e.g. in source location until I perform another debug step with VS Code's controls.

Is there any way to tell VS Code to update its views? Should it maybe update automatically after every command?

**Comment by WardenGnaw** [comment]
Sending a `-exec` command comes from the debug console, which sends it directly to GDB. VS Code uses a request and response model to update the UI. When a breakpoint is set, it will send an request to GDB which will return a response on how to update the UI. Same with the other commands. At the moment in time, there is not a way for us to request to VS Code to update the UI. 

Is there a reason why you need to run `-exec next` instead of using the debugger controls that VS Code provides?

**Comment by mooware** [comment]
Well, initially I didn't notice that multiple threads are displayed in the callstack window, so I thought I'd need -exec to switch threads. But even now I'd think that commands like "nexti" and "stepi" to move instruction-wise would be useful.

**Comment by WardenGnaw** [comment]
You will want to submit a feature request to [VsCode](https://github.com/Microsoft/vscode/issues) for adding debug buttons for `step instruction` and `next instruction`.

**Comment by ismailhkose** [comment]
> You will want to submit a feature request to [VsCode](https://github.com/Microsoft/vscode/issues) for adding debug buttons for `step instruction` and `next instruction`.

Has this feature been implemented?
