### ISSUE TITLE
Debug/Spell Check Error?

### ISSUE THREAD

**Issue by LinshuH** [microsoft/vscode-cpptools#1989]
I am running VS Code 1.23.1 Version and have extension C/C++ IntelliSense, debugging, and code browsing for C++.
My code can successfully compiled by g++, but VS Code keep using Red underline to remind me the error in the code.
For example, like the one below
![vs code2](https://user-images.githubusercontent.com/28817501/39964504-a1f8d02e-563a-11e8-9bd0-5bf390772d3c.png)
However, I do have "Image Struct" defined in my .h file.
Also in my .h file, while I define the class Image, it shows "function type is not allowed".
My .h file is shown below.
![vs code](https://user-images.githubusercontent.com/28817501/39964517-26c4c1e6-563b-11e8-9575-b0547b309b7b.png)

I am really confused, if the code is able to been compiled, why there is error like this exist? What it really means?

Thanks

**Comment by sean-mcmanus** [comment]
It looks like you're using .C files but your struct has a constructor. Our IntelliSense parser is compiling the file as a .C file instead of C++. You can fix this via changing the language for the file to C++ in the bottom right status bar (which only lasts while the file is open) or via the files.associations setting:

```
    "files.associations": {
        "*.c": "cpp"
    }
```

If you still get problems you can't resolve, you can disable the errors via the C_Cpp.errorSquiggles setting.

**Comment by bobbrow** [comment]
I believe GCC and friends treat capitalized `*.C` as c++ by default.  VS Code probably doesn't take this into account.

**Comment by sean-mcmanus** [comment]
Unfortunately, it looks like VS Code's files.associations is case-insensitive, even on Linux. It's possible we could bypass VS Code's file associations and add our case-sensitive ".C" case.

**Comment by LinshuH** [comment]
Hi all,
Thanks for all the answers. After change .C to .cpp, the issue looks like been solved. Not really sure why, but after opening it for a while, the underline does not show up.

**Comment by bobbrow** [comment]
Fixed as part of #2558
