### ISSUE TITLE
In certain contexts identifiers that end with "_t" are highlighted as class/struct/namespace name

### ISSUE THREAD

**Issue by esmirnov** [microsoft/vscode-cpptools#2042]
Hello!
I notice that identifiers with "_t" at end are highlighted as a type name.  Is it a bug or feature?

![screen shot 2018-05-25 at 15 08 42](https://user-images.githubusercontent.com/576417/40543660-0839ec9a-602e-11e8-9ffa-729cb0dd20fb.png)

**Comment by xLobito** [comment]
I guess it's a feature (since several versions), 'cause normally when someone defines a new type or uses POSIX-like type, those types has the "_t" on its name. 

But taking that example in count, it would be nice for the extension to be able to recognize when it's a variable or a new type/POSIX-like type.

**Comment by sean-mcmanus** [comment]
Our extension doesn't implement any C++ colorization (other than the inactive regions). I think it's implemented in VS Code itself in `\Microsoft VS Code\resources\app\extensions\markdown-language-features\node_modules\highlight.js\lib\languages\cpp.js`, e.g. 

```
  var CPP_PRIMITIVE_TYPES = {
    className: 'keyword',
    begin: '\\b[a-z\\d_]*_t\\b'
  };
```

and files in `Microsoft VS Code\resources\app\extensions\cpp\syntaxes` might also be relevant.

**Comment by esmirnov** [comment]
Thanks! I will contact VS Code team.
