### ISSUE TITLE
macOS Framework search should only parse the "Current" framework

### ISSUE THREAD

**Issue by jamesrburgess** [microsoft/vscode-cpptools#2046]
I'm using the latest vs code (Version 1.23.1 (1.23.1)) on macOS 10.12. Intellisense is finding header files in arbitrary frameworks inside /Library/Frameworks before includePath which is not how compilers work on macOS. 

There are then two problems here:

- Paths in includePath come after macFrameworkPath which is the reverse in macOS compilers
- Arbitrary frameworks are searched in /Library/Frameworks which is unexpected/undesirable 

Steps to reproduce
- make a free empty workspace folder
- pick an arbitrary framework in /Library and a header file therein (example QtCore/QObject)
- make another header file of the same name (QObject) in some other folder (/Users/me/bar/QtCore/QObject)
- add that folder to includePath (/Users/me/bar)
- make a .cpp file in the workspace that includes that file with #include "QtCore/QObject"
- observe that the framework version gets parsed not the bar/QtCore/QObject as expected.

I happen to have an Application called Houdini installed I would not expect this location to be searched:

/Library/Frameworks/Houdini.framework/Versions/15.5.717/Resources/toolkit/include/QtCore

Unless I specifically added that framework into my properties.json.

**Comment by bobbrow** [comment]
@jamesrburgess, can you clarify what you mean by "parsed" in the last step?  (Essentially, which IntelliSense operations appear to be behaving incorrectly)

Based on what I'm reading here, this is what I expect to happen:
* For goto definition/symbol search, your duplicate header would not be considered, but the Framework one would.  Why?  Because goto definition/symbol search does not use the `includePath` property.  It uses only the `macFrameworkPath` and `browse.path` properties.  If you want your new header to be considered, you should add it to the `browse.path` property.
* For auto-complete, parameter hints, tooltips, your duplicate header should be chosen because the `includePath` takes precedence over the `macFrameworkPath`.  If that's not what you're seeing then we'll need to investigate further as to why this is not the case.

The split between which properties control which IntelliSense operations is an unfortunate consequence of the current implementation.  We are hoping to improve this in the near term though.  We would like to make the `browse.path` property optional going forward and have the includePath supply the paths for code browsing/navigation but have been concerned about the semantics since auto-complete, etc uses non-recursive paths and code navigation uses recursive paths by default.

**Comment by jamesrburgess** [comment]
@bobbrow seems like I'm having problems replying to this thread, apologies if I end up double posting.

Thanks for the reply and the great software!

So by "parse" I could tell that intellisense was reading the type information from a Framework file that happened to be on macFrameworkPath. It was telling me my destructors throw specifier was wrong or some such thing.

I didn't quite understand the difference between browse.path and includePath so that all makes sense at least, thank you for the explanation.

So, "too inclusive", I would have expected both a framework search path and a list of frameworks in the config file. This would be how a compiler/IDE likely present them. As another point, Frameworks can contain multiple versions. It seems peculiar that each would be searched. I can tell from my experience above that "Current" isn't the one that counted.  The "Current" feature is implemented with a symlink.

Regards,
 - James

**Comment by bobbrow** [comment]
So it sounds like you're saying the red squiggly underlines for errors are not correct.  The IntelliSense engine providing the error squiggles should be looking at the `includePath` so I may need to set up a repro project to see what is going on.  The engine should also be looking at the Current version, so that's something we'll need to investigate too.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.

**Comment by bobbrow** [comment]
This one is actually a bug.  We should just index the "Current" frameworks

**Comment by michelleangela** [comment]
**Fix:** When the "Headers" folder is not found under a framework folder, try to get and index the actual "Versions/Current" folder under the framework folder. Use the "Versions" folder as a fallback.

**Comment by sean-mcmanus** [comment]
The fix is available in https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders3
