### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by koliyo** [microsoft/vscode-cpptools#2050]
The CPP extension is leaking memory.

I'm afraid I do not have much information. My computer started swapping like crazy and was almost totally unresponsive. I managed to list processes in terminal and noticed the process

```/Users/nils/.vscode/extensions/ms-vscode.cpptools-0.17.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin```

taking 20GB of memory. 

After restarting VS code the extension CPP memory usage is down to 120MB.

**Comment by bobbrow** [comment]
Unfortunately, without any additional information this issue is not actionable for us.  Please let us know if you are able to get any additional information (e.g. is it an open source repo that we can clone? or a particular source file?) and we can reopen and look at it.  There's definitely a bug here as we've never seen one of those processes get up to anywhere near 20 GB before.

**Comment by rainwangsd** [comment]
Hi , I also saw mem leak issue for this cpp tools, below are the steps:
1) Use vs code open c/c++ project (a lot of code including Kernel, lib, etc)
2) after some time (maybe a few hours), then I saw the system is very slow and mem is used 25GB by the cop tools (my PC has 32GB memory).
Attached is the picture of htop for the process.

**Comment by rainwangsd** [comment]
[
![vs code cpptool mem leak issue - Rain Wang 2020](https://user-images.githubusercontent.com/49349644/78417239-0fb98b00-75e5-11ea-9ee5-fbe8519ef5e1.png)
](url)

**Comment by rainwangsd** [comment]
Could we reopen this ticket?  this issue is reproduced from the ubuntu system (18.04).

Thanks!
Rain

**Comment by sean-mcmanus** [comment]
@rainwangsd Did you see https://github.com/microsoft/vscode-cpptools/issues/2050#issuecomment-392877493 ?

Whether or not this issue remains open or closed, we need more repro info in order to figure out a cause/fix. If you can try to isolate what is special about your project/scenario that is causing the issue, that could help (i.e. certain files that trigger it?). The cpptools process does not normally use that much memory. It's possible under special conditions there could be some infinite memory data structure created.

Also, I can't tell from your screenshot if it's cpptools or cpptools-srv.
