### ISSUE TITLE
Sometimes it takes unusual longtime or forver to find definitions with C/C++ Extensions

### ISSUE THREAD

**Issue by RogFedex** [microsoft/vscode-cpptools#2119]
With C/C++ Intellisense extension, it takes long time or even hangs to go to defintion or when finding definitions. If we reload vscode and search again then it finds definition immediately.

**Comment by sean-mcmanus** [comment]
Is there a red flame in the bottom right when it hangs on Go to Definition? It could be the same as https://github.com/Microsoft/vscode-cpptools/issues/1928 .

If you can attach a debugger and get call stacks, that would show exactly what it's stuck on.

**Comment by RogFedex** [comment]
Ok. It sounds same as #1928. Do i need to change my setting - "C_Cpp.intelliSenseEngine" as temporary workaround ?

**Comment by sean-mcmanus** [comment]
You can if you want, but using the "Tag Parser" will have fewer features enabled. You might also want to make sure your includePath doesn't have "**" in it, in case that is causing the performance issues (which was somewhat fixed by https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.5-insiders ).

**Comment by bobbrow** [comment]
Closing as duplicate of #1928.  Thank you for the feedback.
