### ISSUE TITLE
Persist Debugger Terminal Window when Application crashes or terminates

### ISSUE THREAD

**Issue by iotathome** [microsoft/vscode-cpptools#2121]
Type: Debugger

OS and Version: Ubuntu 14.04
VS Code Version: 1.24
C/C++ Extension Version: 0.17.4

After starting an application the DebuggerTerminal is created and shows all output from the program, which is debugged. When the program crashes before the debugger can set a breakpoint the DebuggerTerminal is closed. It is not possible to read the information in from the terminal after the crash. 

Is it possible to leave this DebuggerTerminal open?

**Comment by pieandcakes** [comment]
@iotathome Currently, the terminal is a child process of the debugger and dies when the debugger terminates. I'll make this a feature request.

**Comment by iotathome** [comment]
btw: the gdb has a command line option to set up a running terminal as output window:
e.g. --tty=/dev/pts/28
may be this option can be configured in launch.json?

**Comment by pieandcakes** [comment]
@iotathome 
>btw: the gdb has a command line option to set up a running terminal as output window:
e.g. --tty=/dev/pts/28
may be this option can be configured in launch.json?

You can add the debugger arguments by specifying them in `miDebuggerArgs`.

We also added integratedTerminal support in 0.20.0. VS Code will keep the terminal window open so that should fix your issue. To use it, change `externalConsole` to false.
