### ISSUE TITLE
[gdb] Incorrect value of built-in type when running to the end of a while function

### ISSUE THREAD

**Issue by zhangmn799** [microsoft/vscode-cpptools#2125]
**Environment data**
Ubuntu:17.04
gdb version:7.12.50.20170314

**Steps to reproduce**
1. mkdir test && cd test
2. vi main.cpp and edit it as following then save it.
![code](https://user-images.githubusercontent.com/26423555/41335876-eebfc412-6f1c-11e8-8cfa-f1409c76b656.PNG)
3. g++ -g -o main.exe main.cpp
4. gdb main.exe

**Expected behavior**
It can show a value correctly.

**Actual behavior**
"p a" show a's value is incorrect.
![gdb](https://user-images.githubusercontent.com/26423555/41335924-1b8b5560-6f1d-11e8-975f-74cfa4e41526.PNG)

**Comment by WardenGnaw** [comment]
Are you noticing that the value of `a` in the VSCode C/C++ extension's locals windows is not being displayed correctly or is the issue GDB is not showing the value correctly?

From the actual scenario image, it seems like you are trying to print the value of the variable `a` when it has fallen out of scope since you do `n`.

**Comment by zhangmn799** [comment]
I don't use vscode. I try to C/C++ Attach for Linux(gdb) scenary with visualtudio in windows(Hyper-V) and Ubuntu 14.04. 
1.F5
2.F10
It will run "return 0". It seems  like gdb's issue. And I understand your meaning that I shouldn't print the value of the variable 'a' when it has fallen out of scope since I do 'n'. But 'a' show const number type 
is it  expected ?

![capture](https://user-images.githubusercontent.com/26423555/41386786-eb56b4b8-6fb5-11e8-8868-7ed61a7e812a.PNG)
