### ISSUE TITLE
Duplicate system include path in user config not being auto-removed

### ISSUE THREAD

**Issue by vincentmathis** [microsoft/vscode-cpptools#2177]
**Describe the bug**
- OS and Version: Windows 7 64bit
- VS Code Version: 1.24.1
- C/C++ Extension Version: Should be the newest.

IntelliSense didn't find stdlib.h in C:/MinGW/include
Other headers in this path were no problem though.

I changed the path to C:\\MinGW\\include and now it finds stdlib.h
Using forward slashes worked fine a few days ago.

```json
{
    "configurations": [
        {
            "name": "Windows",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "${workspaceFolder}\\include",
                    "C:\\MinGW\\include"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}\\include",
                "C:\\MinGW\\include"
            ],
            "defines": [],
            "compilerPath": "C:\\MinGW\\bin\\g++.exe",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "cStandard": "c89"
        }
    ],
    "version": 4
}
```
Changing it to
```
 "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}\\include",
                "C:/MinGW/include"
            ],
```
shows ```cannot open source file "stdlib.h" (dependency of "string")```
Other header in this path like C:/MinGW/include/SDL2/SDL.h don't produce this error.

**Comment by bobbrow** [comment]
The bug is that our duplicate path removal logic is failing to remove your `c:/MinGW/include` path.  The system include path requires very specific ordering for GCC/CLang because of the use of `#include_next` so when you provide the compilerPath we attempt to remove any duplicates so that your config does not accidentally disrupt the ordering.

This is a bug we should fix, but fortunately, you can fix your problem right now by just deleting the `c:/MinGW/include` line from your configuration.  We're already using that path internally.

**Comment by sean-mcmanus** [comment]
This should be fixed with the latest insiders: https://github.com/Microsoft/vscode-cpptools/releases (unless the includePath ends with "/").
