### ISSUE TITLE
[WSL] Intellisense does not work without g++ (e.g. only with gcc installed)

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode-cpptools#2178]
Type: LanguageService

**Describe the bug**
- OS and Version: Microsoft Windows [Version 10.0.17692.1000]
- VS Code Version: 1.24.1
- C/C++ Extension Version: 0.17.5
- Other extensions you installed (and if the issue persists after disabling them): N/A

**Probably documentation issue**, as in the docs: **vscode-cpptools/Documentation/LanguageServer/Windows Subsystem for Linux.md**, there is **no clear specification** about what "Prerequisites" are required so that vscode-cpptools (at least the newer versions) which assume system includes paths from gcc, are.
As a side comment, this information is provided in **vscode-cpptools/Documentation/Debugger/gdb/Windows Subsystem for Linux.md**, but there is a catch, from document one could understand that he could install either g++ or gcc, and both work, but thats not the case. I've found that actually g++ is needed to run [such command](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Archive/Windows%20Subsystem%20for%20Linux.md#release):
`gcc -v -E -x c++ - < /dev/null`

**To Reproduce**
1. Install WSL and GCC inside WSL (e.g. gcc-4.8)
2. run: `gcc -v -E -x c++ - < /dev/null``
3. there is no **"#include <...> search starts here:"** section
4. the vscode_cpptools extension cannot work without this information it seems,
 e.g. #include <stdio.h> is not found in the system.

**Expected behavior**
I believe the documentation must be update to explicit this behaviour. This can even be copied from GDB section and updated accordingly

**Comment by bobbrow** [comment]
Are you developing in C or C++?  It is my understanding that if you don't install g++ you won't have any c++ headers to work with so you wouldn't be able to compile your code either.  But we can update the documentation to be more explicit here, or you are welcome to submit a PR with the documentation changes and we'll happily review it.

But there is an actual bug in the extension here, so thank you for bringing this to our attention!  The code that detects whether we need to turn on case-sensitive file support for WSL is looking at the C++ compiler info to make the determination, but since the C++ detection fails without g++ installed, case-sensitive file support isn't being turned on for C files, so IntelliSense is currently broken for those too.  Installing g++ fixes it, but we did not intentionally add g++ as a requirement to work with C files.

**Comment by sean-mcmanus** [comment]
@bobbrow Were you going to update the docs?

**Comment by bobbrow** [comment]
I'm not sure that there's a need to update the docs after we fix the bug.  g++ shouldn't have been a pre-requisite.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.17.6.
