### ISSUE TITLE
Linux Debugging (gdb) - Cannot see program output in debug console

### ISSUE THREAD

**Issue by aaiyer** [microsoft/vscode-cpptools#218]
Trying to debug a simple C++ console app in Linux. When invoking the debugger, a DebugConsole xterm launches, and I am able to debug the program well, but the outputs from the console program are not being shown in the Debug Console. I have set logging.programOutput=true in my launch.json

Is there something I need to additionally for the program output to be shown correctly?

**Comment by HardSoft2023** [comment]
I have the same problem. Anyone have any idea is welcome!

**Comment by HardSoft2023** [comment]
@aaiyer you can set `"externalConsole": false,` in launch.json . Then the output will appear in debug console. It works for me . you can try.

**Comment by aaiyer** [comment]
@GuoLiuFang Tried that, still launches an xterm. What is your terminal.external.linuxExec configured to?

**Comment by jacdavis** [comment]
Thanks for reporting this. 

Unfortunately, on Linux we are forced to open the console regardless of externalConsole status. This is because of an issue with gdb where it would deadlock when sharing the same tty as vscode. 

At some point, we hope to support the built in console vscode just added, but this hasn't been completed yet. 

If your program output is not getting displayed in xterm, please reopen.
