### ISSUE TITLE
Increased messages with new Tools API

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2221]
I noticed with the new tools API in 0.17.6, there are a lot more messages that get popped up towards the user. The first is the message stating that my extension would like to configure IntelliSense for the folder. I know this is more on my end, because I start my extension up whenever any c or c++ file is opened because I have no easy way to detect otherwise, but I feel like this could cause other issues in the future with other providers. At least this message can be disabled, so its not as big of an issue.

The 2nd, and more glaring issue, is anytime there is a file that can't be provided for, the extension pops up a message that the file cannot be provided for. And with this message, there exists no way to turn it off, even with a setting. This is a much bigger issue, because if doing something like Go To Definition on a std type causes this message. There needs to be a way to disable this message.

**Comment by bobbrow** [comment]
Thanks for the feedback @ThadHouse.  We added the "allow" message to put the developer in control of who is providing their IntelliSense configurations.  The previous system was a free-for-all and non-deterministic.  As you stated, this message can be silenced on a per folder basis, so we don't expect it to be too big of a nuisance.  Though I think we'll need to add a command for developers to see the list of providers again later if they change their minds or a new extension comes out that will service them.  I'll put that on the backlog.

Regarding the messages, I noticed the same while experimenting with another extension.  At the very least this message should be removed for STD headers when compilerPath is set by the provider.  If we remove the message for all headers, then that will make the experience on par with the `compileCommands` experience.  Do you think that would be sufficient, or would you like these to be dismissable permanently per folder as well?  The reason for adding them is so that developers aren't surprised when IntelliSense doesn't work as expected.  Perhaps we could do that with an icon instead, but were concerned that it could be easily missed since many users turn off the status bar.

**Comment by ThadHouse** [comment]
For the second set of message, I think removing it for headers at all times would be ok. And then removing it for all files during debugging, as when debugging we will likely open library source files that wouldn't be directly configured. I'll keep thinking about things too, as I realized by using the API my extension has no way of providing intellisense for its own library headers without directly setting the settings, which I wanted to avoid.

**Comment by ThadHouse** [comment]
I think if possible, the first time in a folder no intellisense is provided pop up the message, and then change to a status bar icon? That might work.

**Comment by sherryyshi** [comment]
Can there also be a setting for users to disable the notifications for the current session, or current workspace, or permanently (whichever makes more sense)?

**Comment by sean-mcmanus** [comment]
Fixed with 0.17.7.
