### ISSUE TITLE
Allow setting of timeout for extension API provider.

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2229]
In one of my projects, the enumeration attempting to fine the header dirs for a specific file can take more then a second (it requires about 150 globs and takes about 1.5 seconds at the worst case. Either a user setting, or better a setting in the actual provider to set what it's longest expected parse time would be very helpful. I would agree with some sort of cap, but forcing 1 second might be slightly too low.

**Comment by bobbrow** [comment]
Is there any way you can pre-compute those and save them for later, or do you expect projects to be sufficiently large that this would be a resource hog?  With most CMake projects I've seen, the configurations are identical across multiple source files and can be aliased.  I don't know enough about your build system to say whether this works for you or not.

The problem with adding an API for this is that if we let you choose the cap you want, but have another internal cap that overrides it anyway, we're effectively just raising the cap and there's no point in exposing the API in the first place (e.g. why would anyone artificially limit themselves?).  We really want this to be fast because setting up IntelliSense for source files is generally slow and we want to get into a state where IntelliSense is available as soon as possible.  If you detect that you missed the deadline, you can still call didChangeCustomConfigurations and update the config.

**Comment by ThadHouse** [comment]
I'm trying to go through right now and see if there is anything I can do to speed up my side. Basically I have a project with over 80 binaries, and its finding which binary the uri matches that takes the time. But I'm working on seeing if I can speed up that loop enough to not matter.

Can I use the cancellation token to detect if a timeout happened, because that might also work too for my case. I do cache the result, so duplicate requests for the same file are fast.

**Comment by bobbrow** [comment]
Yes, you should be able to use the cancellation token to detect a missed deadline.

**Comment by ThadHouse** [comment]
@bobbrow I'm finding a couple more quirks in testing the API stuff. Should I just keep creating issues, or is there another channel to discuss things before creating full issues?

**Comment by bobbrow** [comment]
Feel free to email us here if you would like to discuss stuff offline: c_cpp_support@microsoft.com
