### ISSUE TITLE
Ctrl+Click should not navigate to itself - go to the decl or def instead

### ISSUE THREAD

**Issue by Flamefire** [microsoft/vscode-cpptools#2298]
Using 0.17.7 a bug was introduced, that CTRL+click on a function definition does not go to its declaration. The other way round and GoToDeclaration(CTRL+F12) does work though.

This is really annoying if you are working on a class source file and want to adjust the function signature. Using CTRL+F12 does work but is but is more effort.

Why not just make GoToDef work just as GoToDeclaration when you are already at the definition? GoToDef is useless at that point and simply being able to use F12 or CTRL+click would simplify the workflow.

**Comment by sean-mcmanus** [comment]
This is "by design" and I don't understand how it could be a regression unless previously the definition wasn't available (in which case we fallback to the declaration). Do you know of any other editor that behaves the way you describe? Can you provide a simple example that illustrates a regression in behavior?

We might be able to detect if the current symbol is already the definition and return the declaration instead (we have the info, but just don't return it).

You could also file a VS Code issue to allow customization of Ctrl+Click to make Go to Declaration easier to invoke. https://github.com/Microsoft/vscode/issues/29503 and https://github.com/Microsoft/vscode/issues/3130 seem like similar requests.

**Comment by bobbrow** [comment]
VS 2017 does this.  It's not an unreasonable request.

**Comment by bobbrow** [comment]
But like @sean-mcmanus said, this isn't "technically" a regression since we never implemented it that way.  The behavior you saw was likely due to the bug where we weren't parsing the definition, so the declaration was used instead.  Now that the bug is fixed it looks like a regression, but it was never coded to work that way.

**Comment by Flamefire** [comment]
Yes @bobbrow is right, VS does that and I think other IDEs I used did that too, but I don't have a current setup to test this. And yes it might have been that it used to work "by accident" only, but still the request stands.

Any reason NOT to have GoToDef change to GoToDecl when you are already at the definition? In the case where you are at either one the other is completely useless and even with the linked issues in VSCode it would be hard to fix because the Ctrl+Click has to change meaning whether you are on a definition or not. Changing the behaviour of GoToDef in that situation would be much easier.

Additionally having VSCode and VS behave similar is an advantage in my opinion (expectation: similar name->similar behaviour)

**Comment by bobbrow** [comment]
I didn't mean to sound like I was pushing back against the request.  I think it should be relatively simple to invoke the opposite command if the result coming back puts you at the same location as the cursor.

**Comment by sean-mcmanus** [comment]
Our 0.17.8-insiders release with the "Go to Definition on the definition going to the declaration" fix is available at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders .
