### ISSUE TITLE
Switch Source Header is very slow

### ISSUE THREAD

**Issue by djg** [microsoft/vscode-cpptools#231]
I'm using vscode + cpptools with a very large codebase. When switching from .cpp to .h and back, vscode is very slow to respond the first time when toggling between files, especially when switching from .h back to .cpp. It takes seconds to complete, which makes it feel like the feature isn't working.

Can we have fast switching, or a more prominent visual indicator that signals that the process of switching is still "working on it."?

**Comment by jyavenard** [comment]
+1 vote here.

It takes sometimes over 30s to switch between a .cpp and its corresponding header. Even though both are currently opened.

Typically the 2nd alt-O will be faster, but still far from instantaneous.

**Comment by jhasse** [comment]
I noticed that this happens only on Windows. On Linux with the same project (~400 source files) it switches instantly.

**Comment by jyavenard** [comment]
Seeing this on both a mac (10.11.6) and Linux (ubuntu 16.04).
 This is working with a rather big project (151870 files)

**Comment by sean-mcmanus** [comment]
Thanks for bringing this perf problem to our attention. I am able to repro it and I see the code that is taking a long time building a "file system tree", which doesn't scale well with lots of files. We'll investigate making this scenario faster in a future release.

**Comment by djg** [comment]
In all the setups I've used, the alternate file in either in the same dir or separated include/file.h,src/file.cpp. Maybe it would be faster to first check for those, before creating a file system tree?

**Comment by bobbrow** [comment]
This should be fixed in 0.10.2.  Please reopen if you continue to see the issue.

**Comment by jyavenard** [comment]
Version 1.11 has seriously regressed this feature. in fact switching between header/code almost never works now :(

**Comment by sean-mcmanus** [comment]
@jyavenard What was your previous version of cpptools that was working? Is it red in the bottom right and does it say "Searching..." for #include headers that can't be found? Are the source/target files in the same folder? I assume slowness or switching to the wrong file isn't the problem and that the symptom is that no switching ever occurs? What OS are you using? We're not able to repro a problem so we need more info. It'd be better if you created a new bug, because this bug was about the original implementation which could take a long time to switch. The new implementation will generally fail to switch if the target file isn't added to the browse database for some reason, so deleting your .browse.vc.db or changing the databaseFilename property in the c_cpp_properties.json may fix the issue and cause the target file to be correctly re-added.

**Comment by jyavenard** [comment]
@sean-mcmanus I don't know which version it was before. After reverting to 1.10 (due to issue #24052), it still no longer works.

The bottom of my window are all in blue.
Source/Target are in the same folder.

Using 10.12.4 ... Yes, I think it's no longer slow, it just doesn't work at all anymore :)

It was working a few days ago, nothing has been changed in my configuration in month..

will create a new bug

**Comment by jyavenard** [comment]
(FWIW, I have no .browse.vc.db on my home directory)

**Comment by sean-mcmanus** [comment]
@jyavenard On Mac, the default .browse.vc.db location should be under `/Users/<user>/Library/Application Support/Code/User/workspaceStorage` , but if the source/target are in the same folder, the switching should work without a browse database with 0.10.5...unless the entire language server process is failing. I'll follow up in the new bug...
