### ISSUE TITLE
LLDB: Continuing execution via -exec c gets VSCode into odd state

### ISSUE THREAD

**Issue by dkorbar** [microsoft/vscode-cpptools#2319]
Type: Debugger

**Describe the bug**
- OS and Version: macOS 10.13.3
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them): XML Formatter, TSLint, SQL Server (yes it still reproes after disabling other extensions
- After breaking into the debugger, when I use "-exec c" to continue execution I get into a weird state where the process is running again but VSCode still shows us broken into the debugger.

**To Reproduce**
1. Hit a breakpoint in a cpp app
2. Continue execution by executing `-exec c`

Expected: Execution is continued and VSCode shows all threads as running / clears current position in source code
Actual: Execution is continued but VSCode UI doesn't update (still shows up as paused and still shows the current position in code). When we click continue we get back to a normal running state and have this error in the debug output:
ERROR: error: Process is running.  Use 'process interrupt' to pause execution.

**Comment by pieandcakes** [comment]
@dkorbar This is expected. VS Code does not support you changing state except through the UI.

**Comment by dkorbar** [comment]
@pieandcakes are there any plans to change that in the future? Being a developer coming from XCode, it's very common for me to control quite a bit of the debugging flow directly through the lldb console in XCode (I know other developers on my team do as well).

**Comment by pieandcakes** [comment]
If you see my comment on the other issue regarding breakpoints that you filed, the REPL commands starting with `-exec` was introduced as workaround we put in place to allow you to query the debugger for more data and not meant to change state of debugging. VS Code's protocol expects a request/response system to control debugging where most requests start with the UI and we are allowed to send a response to it. Because of the design, we can't notify the UI that debugging state has changed. Therefore, this functionality is not supported.
