### ISSUE TITLE
Got a high CPU occupancy when using cpptools

### ISSUE THREAD

**Issue by quank123wip** [microsoft/vscode-cpptools#2358]
And when I shut the cpptools down ,it's lower than that

**Comment by sean-mcmanus** [comment]
We need more info to determine whether the high CPU usage is "by design" or not. When you open a new workspace (without files open), CPU usage will occur to build the browse database -- changing the "C_Cpp.workspaceParsingPriority" will reduce this background CPU usage, and if the database if already built then it should use less CPU usage next time -- hover over the database icon in the bottom right to see some status.

After opening a file, it may have to parse additional files as well as spawn an IntelliSense process which also uses more CPU (the red flame).

If you believe there is a bug in CPU usage, you could attach a debugger and provide us with the call stack you believe is using too much CPU when it shouldn't, or provide more repro details.

We also have a newer 0.17.8-insiders build you can try: https://github.com/Microsoft/vscode-cpptools/releases .

**Comment by quank123wip** [comment]
Got it:)
