### ISSUE TITLE
preLaunchTask is not documented in launch.json doc

### ISSUE THREAD

**Issue by graph** [microsoft/vscode-cpptools#2365]
https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md

I haven't tried it yet. I was looking for a way to do build & run automatically.

**Comment by pieandcakes** [comment]
@graph Prelaunchtask is a feature provided by VS Code and not by our adapter.

**Comment by graph** [comment]
Should I open an issue with vscode or will you handle it?

**Comment by pieandcakes** [comment]
@graph My comment that it isn't documented is because you are looking in our documentation for a feature implemented by VS Code. You can find the documentation they provide [here](https://code.visualstudio.com/Docs/editor/tasks). When looking for documentation for core features, please refer to their documentation.

**Comment by graph** [comment]
preLaunchTask is not documented there too

**Comment by pieandcakes** [comment]
@graph That was the documentation for creating `task.json`. The actual place to specify the task you created, `preLaunchTask` is in [this](https://code.visualstudio.com/docs/editor/debugging) document.

**Comment by graph** [comment]
thanks, I don't know how I missed it.
