### ISSUE TITLE
C variable explorer (recommendations) shows everything, including irrelevant stuff

### ISSUE THREAD

**Issue by schperplata** [microsoft/vscode-cpptools#2372]
Issue Type: <b>Bug</b>

I have a C project where a header of hardware mapped registers are defined in sfr.h file, including `typedef`-initions, `struct`-s, `union`-s, bitfields, defines, ... 
When I define a variable of a specific type (defined as `typedef{ }` ) and I try to explore elements of this typedef-ined variable, VS Code shows all defined elements, structs and members of all other available definitions/declarations. This is a big problem since recommendations are useless if I stilll have to remember all available members for a specifc variable type.  

I expect that variable explorer/recommendations (CTRL + SPACE) will display only available typedef members, class methods, ... **that are related to this variable.** Is my understanding correct, or is this a bug?

![variableexplorer](https://user-images.githubusercontent.com/8736111/43828096-d18d3874-9afb-11e8-89e7-4666d07168df.PNG)
On the picture above, I expect that members of `variable2_t` will not be recommended, since `my_var` is of type `variable1_t` and can't have `variable2_t` members.

Extension version: 0.17.7
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.90GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\BlueBox\fitIDEA\samples\src\CortexM-x\EFM32GG11|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
It works if you use "typedef struct" instead of just "typedef". What compiler and language flags are you using to get that code to compile and/or do you know where that syntax is described as being valid? You should get a squiggle after the "typedef {" about "expected an identifier". If you don't get squiggles then is your intelliSenseMode set to "Default", which is a requirement for the correct autocomplete and squiggles.

**Comment by schperplata** [comment]
Apparently I simplified an example a little bit too much, since this is not really our case. You are right, if I add `struct` after typedef, autocomplete works OK. I also managed to discover the root of our problem, and maybe an improvement for VS Code. This is an extract of our custom generated header file with bitfields for some specific CPU:
```
struct CPU_tag {
    union {
        uint32_t R;
        struct {
            uint64_t VARIANT:4;
            uint64_t PARTNO:12;
            uint64_t reservedSpace0:      
            uint64_t REVISION:4;
            uint64_t IMPLEMENTER:8;
        } __attribute__((packed)) B;
    } CPUID;
    /* ... */
} __attribute__((packed));
#define CPU  (*(volatile struct CPU_tag *) 0x4001c000)

/* ... */
#define ADC  (*(volatile struct ADC_tag *) 0x20002000)
/* ... */
```
There are many register definitions in this file. The problem is, that when we access this bitfields like:
`CPU.CPUID.B.VARIANT = 0x7;`
after each dot (example `CPU.xxx`) all structs of all included header files are recommended, even if `CPU` and `CPU_tag` is defined only in one header file, a single `#define` in all project/VS Code workspace files. Seems like `#define` statement doesn't parse `CPU_tag`.

Now, our "header file generation script" will be re-written (to use `typedef`) anyway, but, if this is possible, it would be great if `#define` statements would also be parsed for recomendations and autocomplete.

**Comment by sean-mcmanus** [comment]
"uint64_t reservedSpace0:" should end with a semicolon "uint64_t reservedSpace0;". It is working for me using WSL gcc/clang -- I need more info about what compiler/args you're using. Also if you could set C_Cpp.loggingLevel to "Debug" then you could see what errors are occurring. It appears that something is making it fall back to the "Tag Parser" instead of the IntelliSense engine.

![image](https://user-images.githubusercontent.com/19859882/43917696-dd549150-9bc5-11e8-9e5c-e6563668c51f.png)

**Comment by schperplata** [comment]
I didn't compile the code above since it is only an extract for example purposes. That is why all the mistakes are present :/ We use GCC for ARM in our projects. I use VS Code to write code which is later compiled and debugged in some obscure IDE with no autocomplete capabilities.
Anyway, this sentence make me think:  

> It appears that something is making it fall back to the "Tag Parser" instead of the IntelliSense engine.

So, I played around a little bit and discovered, that if a syntactically wrong code is present _somewhere_ in file, IntelliSense engine/Tag Parser don't work at all, which is OK I think. Pressing CTRL + SPACE shows all everything grayed out as expected.   
Anyway, since I use VS Code only to write code and I have never really set workspace include/browse paths (actually I don't really have workspace, I just opened folder with VS Code), missing or not included headers are (as it seems) accounted as _errors_.  See this example.
For this bug report I've created a folder with _variableExplorer.c_ (this) file, and I've copied our _sfr.h_ header file into the same folder. This works:
![ok](https://user-images.githubusercontent.com/8736111/43943235-1143480c-9c7b-11e8-830d-6ff750c356b6.PNG)
Now if I add some _#include_ statement of a file which can't be found in include/browse path, recommendations do things I reported as a bug:
![error](https://user-images.githubusercontent.com/8736111/43943321-71623ba8-9c7b-11e8-9abb-fe8521b430fd.PNG)
Note that all recommended variables are defined in our _sfr.h_ file, which is not included in this .c file

Is VS Code silently including all files that are in the same folder, even if they are not included?

**Comment by sean-mcmanus** [comment]
Adding the missingHeader.h makes it fall back to the Tag Parser -- you can change this behavior by setting the intelliSenseEngineFallback setting to "Disabled", which will make autocomplete behave "correctly". When the Tag Parser is used, it will return all matching results for all the symbols that have been parsed in the workspace, with only some filtering, i.e. after typing "." it'll show all members for all possible classes, because the Tag Parser doesn't have the type information for the code on the left of the ".". The code isn't silently include all the files -- only the IntelliSense engine actually tries to include/compile files that are opened.

**Comment by schperplata** [comment]
Great, setting Fallback to Disabled works as I want.  
Just for others with the same _problems_, this works for me the best:
```
"C_Cpp.intelliSenseEngineFallback": "Disabled",
"C_Cpp.default.browse.limitSymbolsToIncludedHeaders": true
```

Thank you, _Issue_ can be closed.
