### ISSUE TITLE
Missing .h hides *ALL* errors in .c source

### ISSUE THREAD

**Issue by nurbles** [microsoft/vscode-cpptools#2403]
Type: LanguageService
**----- Input information below -----**

**Describe the bug**
- VSCode Version:  1.26.0-insider
- Commit: 207ace21dfec3dccab52f1296a3880ac7644c978
- Date: 2018-08-10T06:45:40.008Z
- Electron: 2.0.5
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architexture: x64
- OS Version:  Ubuntu 18.04.1 shell on Windows 10 Pro
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them):
- C++ Intellisense Extension Version: 0.2.2
The issue existed before I installed this extension and persisted after this extension was installed.
- A clear and concise description of what the bug is.

**To Reproduce**
1. Open a .c file from a Windows project in a linux workspace that references a single header that does not exist
2. Notice that no errors are flagged.
3. Correct the name of the header to the project header for the workspace.
4. Notice that a large number of errors suddenly appear.
5. Change the header name back to a non-existent file.
6. Save the changed file.
7. Notice that the errors all immediately vanish!

**Expected behavior**
I expected to see at least ONE error flagged in a .c file that references a missing header file.

**Screenshots**
Two screenshots, one showing the missing header but no errors flagged, the other showing the correct header with many errors flagged.

![missing-header_no-errors](https://user-images.githubusercontent.com/14079927/44100664-92f3ee02-9fb3-11e8-9eae-46d324f72e61.png)
Missing Header but no errors shown for the file.

![correct-header_many-errors](https://user-images.githubusercontent.com/14079927/44100663-92de2338-9fb3-11e8-87a4-4421939ea3cf.png)
Almost instantly after saving with the corrected header file name, many errors appear (as expected).

**Additional context**
There appears to be a tiny little icon that appears at the lower left of the screen to indicate a missing header, but unfortunately that error is not included in the count of errors found in the file as I would expect (probably why I never noticed the teeny icon until writing this report.)

**Comment by bobbrow** [comment]
This is the expected behavior.  If you hover over the green squiggle in the first screenshot (with the "evil" missing header), you will see a message that explains the behavior.  If you click on the lightbulb that appears above the squiggle, an option will appear that lets you turn off this behavior so that you can get all the error squiggles even when an included header is missing.

The background for this behavior is that it used to be very difficult for users to get their folders configured and people complained about seeing a ton of red squiggles whenever they opened a new folder.  So we adopted the position that a missing header means that the folder is not configured and therefore we should turn off the squiggles.  But in the case that users didn't want this behavior, we added a setting that lets you turn it off: `"C_Cpp.intelliSenseEngineFallback": "Disabled"`.  Clicking on the lightbulb and choosing the option to disable this behavior effectively updates this setting for you.
