### ISSUE TITLE
Add `cpptools.enable` option

### ISSUE THREAD

**Issue by vilicvane** [microsoft/vscode-cpptools#243]
Most of my project has no C/C++ involved, so it would be convenient if I can globally disable this extension and enable it for only some projects.

**Comment by sean-mcmanus** [comment]
This would be trivial for us to add, but it seems like our extension should be made to not impact non-C++ projects. Is there a particular scenario or bug that is causing you to want to disable the extension? You only want to disable the language service and not the debugger service, right?

**Comment by vilicvane** [comment]
I just did a search against `.BROWSE.VC.DB`, it seems #211 addressed my issue.

**Comment by vilicvane** [comment]
Is it listing all the files under project folder for C/C++ detecting? I think it might be a small problem for project with many npm packages installed as well.

**Comment by sean-mcmanus** [comment]
From what I have seen so far with large projects, the directory search for C++ files is "fast enough" and it occurs in our language server process so I'm not yet aware of any observable negative performance impact (other than some bugs).

**Comment by vilicvane** [comment]
Anyway, it would still be good to have a related option to disable or ignore some directories (in my case node_modules, which contains packages with native code that I do not care about).

**Comment by sean-mcmanus** [comment]
We decided to switch to "lazy activation" instead of an enable/disable option (for 0.9.2 or 0.9.3). This will cause our extension to not load until:
1. A C/C++ file is opened.
2. A C/C++ or debugger command is executed.
3. A workspace with a .vscode/c_cpp_properties.json is opened.

If you still want an enable/disable option, you could try asking the VS Code team to provide this ability for all extensions instead of the current install/uninstall.

**Comment by vilicvane** [comment]
It sounds even better to have the lazy activation feature. ;)

**Comment by sean-mcmanus** [comment]
Lazy activation didn't make 0.9.2 (should be in the next version). But the browse db should no longer appear in the .vscode directory.
