### ISSUE TITLE
Error squiggles and not showing attributes for compounded anonymous struct

### ISSUE THREAD

**Issue by xLobito** [microsoft/vscode-cpptools#2433]
Greetings!

**Type: LanguageService**

- OS and Version: Windows 10 - 1803 w/WSL Ubuntu 14.04
- VS Code Version: 1.27.0-exploration
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): It's irrelevant, 'cause the related issue is based on C extensions. 
- A clear and concise description of what the bug is: When we use anonymous structures, if we compound the upper struct into another (Like inheritance), the extensions doesn't get the attributes. 

**To Reproduce**

1. Create a C source file 
2. Then make a new struct with some attributes (int x, int y, int z will suffice)
3. Make another struct and the first attribute shall be the "name" (like struct A, or A if typedef'd) of the upper struct.
4. Build the main function and access the attributes for the second struct.
5. Ctrl + Space to watch the suggestions for the last struct created and no attributes for the upper struct will be shown.
6. After select the attributes for the upper struct. Look up the squiggles reported for the extension.

**Expected behavior**
The squiggle shouldn't appear at all, 'cause this trick is allowed for GCC (with -fms-extensions). Also, the IntelliSense should show the attributes from the upper struct or at the very least, no report any squiggles.

**Screenshots**

![imagen](https://user-images.githubusercontent.com/16466974/44302983-32613800-a30b-11e8-8972-1d37a893e016.png)
![imagen](https://user-images.githubusercontent.com/16466974/44302992-7a805a80-a30b-11e8-8243-a795326108ba.png)
![imagen](https://user-images.githubusercontent.com/16466974/44303003-c3381380-a30b-11e8-9e19-f410955cdb8a.png)

**Comment by bobbrow** [comment]
Thanks for the bug report.  The extension doesn't instruct WSL compilers to use `-fms-extensions` by default, so that explains the squiggle.  And there's also a bug in the extension we just noticed on Friday that doesn't let us set additional compiler flags for WSL compilers when using linux-style paths.

You can workaround the bug and set the flag for your WSL compiler by pasting the Windows path to the compiler in the `compilerPath` variable like this (if you have Ubuntu 18.04 installed):
```
"compilerPath": "C:/Users/<username>/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin/gcc -fms-extensions"
```
instead of
```
"compilerPath": "/usr/bin/gcc -fms-extensions"
``` 
This will make the squiggle would go away, but IntelliSense will crash instead of giving you a broken member list after typing the arrow operator.  It does recover after additional typing, so if the squiggles are a real nuisance for you, you may consider accepting the crash so that the squiggles go away.

It crashes in a component that we share with Visual Studio, so I let them know about the issue (it repros in Visual Studio as well).  When they fix the crash, we can check up on the member list suggestions to make sure all the fields are showing up too.

**Comment by xLobito** [comment]
@bobbrow 

I appreciate your workaround for the bug. In fact, it's kinda annoying when you're working with a project which uses it a lot (In my case I use it quite often), so I will try to use this workaround and see how does it works. 

Kind regards!

**Comment by sean-mcmanus** [comment]
@xLobito This issue is "fixed" now, i.e. using -fms-extensions should work for this particular scenario. The other bug is for fixing other bugs that occur in this mode, such as typeinfo handling, which prevents us from setting -fms-extensions by default. I recommend trying -fms-extensions out if your code uses the extensions a lot, but if you hit more issues with it on, then turn it off.
