### ISSUE TITLE
"he C/Cpp Language Server server crashed 5 times in the last 3 minutes" if the Folder is on a Linux SMB Server

### ISSUE THREAD

**Issue by tilman22** [microsoft/vscode-cpptools#2437]
Hi,

our Sourcecode is stored on a linux/centos server accessible by Windows via an smbd service (mapped as a network drive t:). When I open a Folder (on Windows) on that drive which contains only a single and empty cpp-File, then the language server crashes immediately.

```
[Error - 12:23:51 PM] Connection to server got closed. Server will not be restarted.
[Error - 12:23:51 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at Socket.<anonymous> (C:\Users\SoTi\.vscode\extensions\ms-vscode.cpptools-0.18.1\node_modules\vscode-jsonrpc\lib\messageReader.js:188:62)
	at emitOne (events.js:121:20)
	at Socket.emit (events.js:211:7)
	at Pipe._handle.close [as _onclose] (net.js:554:12)
```

This does not happen when the folder resides on a Windows Network drive.

Any ideas? Please feel free to ask for more details.

Tilman

**Comment by yrpark99** [comment]
Hello,

I have exactly same issue, and eagerly looking for a fixed solution, but no luck.
Actually I have not seen this issue with old version (vscode + cpp tools).
 
Thank you.

**Comment by RoBaaaT** [comment]
Hi,

I also have the same issue, however I have mounted the network drive using SFTP Net Drive 2017 (i.e. using SFTP not SMB). Is there any way to debug it further? In the debug console I get the same error message as was posted above.

**Comment by sean-mcmanus** [comment]
@RoBaaaT If you could attach a debugger before the crash to get a call stack that might help (maybe before opening a file)? Maybe enabling logging might show some info: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md . I think we may just need to test with different mounted network drivers. The paths are probably not formatted as we expected, leading to the crash. Can you provide us a sample path that is crashing that we could plug into our path processing code to see if it crashes?

**Comment by RoBaaaT** [comment]
I am not getting any output in the log after setting the log level to debug and reloading the window. The C/C++ option doesn't even show up in the log filter selector.
Here is a sample path (obtained by clicking "copy path" in the context menu of the editor tab): D:\home\username\Test\Test.cpp. I don't see any obvious issues with that path. The extension crashes when I open the folder Test in VSCode and then open the Test.cpp file (which is empty). As the crash happens immediately after opening a cpp file, I don't know how to attach a debugger.

**Comment by sean-mcmanus** [comment]
@RoBaaaT If you're not getting any logging it sounds like it's crashing really early on during initialization. The path appears normal and not a strange network path. Using the 0.21.0-insider3 version is preferred (C_Cpp.updateChannel set to "Insiders"), since lots of crashes have been fixed with that and it's closer to what we plan to ship soon.

Oh, if the crash happens when opening the cpp file, you should be able to attach a debugger to the Microsoft.VSCode.CPP.Extension.exe process. We should probably create some walkthrough for how to do this, but a summary is -- Click the Debug button on the left of VS, click the gear icon, click the Add Configuration button, select "C/C++: Windows Attach", set the symbolSearchPath to "https://msdl.microsoft.com/download/symbols", click start debugging, start type the name of the process, select the process, repro the crash, look for the crash call stack in the Call Stack window, and right-click to copy that. Our parser code throws handled antlr exceptions when parsing so you can ignore that output. A screenshot is below -- let me know if you encounter a problem.

![image](https://user-images.githubusercontent.com/19859882/51274300-aae42780-1983-11e9-9948-b4939eb10ba5.png)

**Comment by RoBaaaT** [comment]
After updating to the insiders version, I am actually getting some output with logging set to high:

>initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
textDocument/didOpen
cpptools/queryCompilerDefaults
Attempting to get defaults from compiler found on the machine: ''

This exact output repeats five times (as the extension is started five times). So it turns out the problem was that I did not have a compiler installed on the machine VSCode is running on, as I use it for remote development only. Installing Visual Studio fixed the issue (although it seems like overkill). It would be nice if the extension notified the user that a compiler is required for IntelliSense to work. I was not aware of that.

**Comment by sean-mcmanus** [comment]
@RoBaaaT A compiler shouldn't be required. We have tested on machines without any compiler and haven't seen this crash. It shows:
```
Attempting to get defaults from compiler found on the machine: ''
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
```
and it doesn't crash afterwards.

**Comment by RoBaaaT** [comment]
@sean-mcmanus Does it maybe require some other part of the tools that are installed alongside Visual Studio? The only thing I changed to get it working was to install Visual Studio so I have no other idea why it would crash before that.

**Comment by sean-mcmanus** [comment]
@RoBaaaT We don't have any known non-OS external dependencies, i.e. we have "clean" VMs with just the OS for testing and our extension works, but it's possible in certain scenarios a dependency might exist, such as an a Visual C++ redistributable, possibly if the OS hasn't been updated to include it. We might be able to fix this if we had a crash call stack. This is the only report I remember of crashing after querying the default compiler so I suspect is it a rare issue.

**Comment by Colengms** [comment]
There hasn't been activity on this issue for quite a while.  We've since addressed some issue with opening folders on SMB shares.  If you are still seeing this issue, please reactivate or open a new issue.
