### ISSUE TITLE
Symbols are not found when using Visual Studio Windows Debugger.

### ISSUE THREAD

**Issue by aoyulong** [microsoft/vscode-cpptools#248]
I use  Visual Studio Windows Debugger after compiling my source code by using command `cl /Zi source.c /link /out:run.exe` .  It shows that some symbols are not found.  OS: win 10 64 bit and the VS code: 1.5.3.  However, the code can run correctly without debugging.
![qq 20160923153625](https://cloud.githubusercontent.com/assets/3069790/18778672/0c066d28-81a8-11e6-8ea9-791ef5707b00.jpg)

**Comment by jacdavis** [comment]
Thanks for reporting this. This is the way symbols work when debugging works on windows. System modules do not load symbols by-default as they constantly change. In order to obtain them, you can download them from the Microsoft public symbol server which is located here: https://msdl.microsoft.com/download/symbols

If you set the symbol search path to include the symbol server, they will download. Example:
"symbolSearchPath": "https://msdl.microsoft.com/download/symbols"

**Comment by uuf6429** [comment]
To whoever might see this in the future, `symbolSearchPath` is a key of `launch.json -> configurations[n]`.

**Comment by bsed** [comment]
```cmd
"symbolSearchPath": "C:\\Symbols",
_NT_SYMBOL_PATH = cache*c:\symbols;srv*http://msdl.microsoft.com/download/symbols
```
![image](https://user-images.githubusercontent.com/10845087/56336448-03210480-61d3-11e9-91ab-87d37133cf49.png)


see : [https://code.visualstudio.com/docs/languages/cpp](https://code.visualstudio.com/docs/languages/cpp)

**Comment by sean-mcmanus** [comment]
@bsed I don't understand. Where is that UI from? Our extension uses launch.json, but the text you're using isn't valid json.
