### ISSUE TITLE
when you define new struct  type without name, the ouline display _unnamed_struct_1afa_1 info

### ISSUE THREAD

**Issue by hawkinchina** [microsoft/vscode-cpptools#2494]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macos 10.13
- VS Code Version: 1.27.0
- C/C++ Extension Version: 0.18.1   

 **Detail Test Issue description** 
           When you define a new struct type without name, just like typedef struct { ... } MyNewBufferContext. the ouline of VS Code display _unnamed_struct_1afa_1 and  its field variables and MyNewBufferContext. is it ok? or just only display MyNewBufferContext and its field variables.

C source code:
```C
typedef struct {
    BufferContext base;
    Context *pAppCtx;
}MyBufferContext;
```

**Expected behavior**

only display MyNewBufferContext and its field variables.

**Screenshots**

![image](https://user-images.githubusercontent.com/8294642/45197051-d5193080-b291-11e8-8a71-4122a3d59080.png)

**Additional context**

None

**Comment by bobbrow** [comment]
This is expected.  The unnamed struct is the "definition" and `MyBufferContext` is the typedef alias.  Since there may be more than one unnamed struct in a translation unit, the IntelliSense engine assigns unique names to each one.  Perhaps we can make the unique name look less strange, but we followed Visual Studio's implementation for this.

**Comment by hawkinchina** [comment]
OK. thanks a lot..
