### ISSUE TITLE
cpp.hint is ignored

### ISSUE THREAD

**Issue by gbonacini** [microsoft/vscode-cpptools#2515]
**Type: LanguageService**

**Describe the bug**
- OS and Version: 10.11.6
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): vim, the issue persists
- A clear and concise description of what the bug is: VSC seems ignore to cpp.hint file

**To Reproduce**

1. Create a function declaration in an header file like:
int  func(void) anyexcept;
and the related definition. 
2. Create a  cpp.hint file  in Workspace root ( I also put cpp.hint in the sources subdir with no changes in behaviour);
3. Restart VSC
4. See error: VSC code doesn't override the macro with that one specified in cpp.hint, in this case with an empty string.

**Expected behavior**
Trying to disable a preprocessor macro that, if present, doesn't permit to Intellisense to individuate a function definition with the "Go to Definition" menu option,  I create an cpp.hint file in Workspace root with a single line: 
#define  anyexcept 
to disable that macro ,  but visual studio code seems ignore its presence, testified by the fact that if I move the mouse cursor on the macro in a Visual Studio Code editor, it show the original macro. I restarted VSC without changes in that behaviour.

**Screenshots**

**Additional context**
None

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I'm able to repro the bug. Features that use IntelliSense (hover) should show the actual value of the macro (not the cpp.hint), but the Go to Def and navigation at the bottom should use the cpp.hint. The IntelliSense compiler will expand all macros, but our symbol engine doesn't not, which is why the cpp.hint is required for those features.

**Comment by sean-mcmanus** [comment]
Actually, I think I was mistaken before. I'm not able to repro any bug. If you put your cursor in the function definition does the navigation bar update correctly? I'm seeing it work correctly. You may need to edit/save the file after modifying the cpp.hint to get it to reparse. Without the cpp.hint, the nav bar says (Global Scope):

![image](https://user-images.githubusercontent.com/19859882/45581359-42f4c780-b851-11e8-935e-bc1cd7da6fe1.png)

The squiggle on FOO is "by design", because it's defined to be "int", which is invalid after a method definition's signture.

**Comment by gbonacini** [comment]
Hi Sean,

as specified in your instruction ( "You may need to edit/save the file after modifying the cpp.hint to get it to reparse" ), I added a comment in my source code, saved the file, and now it work perfectly !
In cases like this one, is there a procedure to force the reparsing without add something in the source code ?
By the way, thank you for your effort, in the last times VSC code improved a lot, for example code navigation is very quick and fluid whereas the last winter it was a real pain. VSC is helping me a lot in a job involving a lot of legacy code not-so-well maintained, I really appreciate.

**Comment by sean-mcmanus** [comment]
We've already fixed the saving requirement in our September release, but it's not available to try out yet (it will auto-parse/update after around 3 seconds of idle): https://github.com/Microsoft/vscode-cpptools/issues/202 is the issue tracking that. UPDATE: Fixed with 0.19.0.
