### ISSUE TITLE
Syntax checker complains on C features (MSVC)

### ISSUE THREAD

**Issue by septag** [microsoft/vscode-cpptools#2545]
**Type: Syntax checker**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.18.1

I'm writing a C99 file that has designated initializers, the code compiles with no errors with msvc compiler, but the syntax checker complains: 

```c
mystruct s = {.x = 1.0f};
```

it complains ```expected an expression```

here's my c_cpp_properties.json:

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/include",
                "${workspaceFolder}/include/compat/msvc",
                "${workspaceFolder/3rdparty"
            ],
            "defines": [
                "_DEBUG",
                "_MBCS"
            ],
            "windowsSdkVersion": "10.0.14393.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
I'm not seeing any bug. I suspect the issue is that you're using MSVC 14.0's cl.exe. Is that what you're actually using to compile? Can you upgrade to VS 2017's compiler?

![image](https://user-images.githubusercontent.com/19859882/45981661-b2657680-c00a-11e8-85c1-a8acb25edf73.png)

**Comment by septag** [comment]
It's weird, I just opened the project today and noticed that errors are gone (still on msvc14) and I didn't change anything since last time.

Anyway, sorry to waste your time
Thank you for your support

**Comment by sean-mcmanus** [comment]
I was able to reproduce the bug -- it occurs when the file is mistakenly associated with the C++ language instead of C. I filed a bug in regards to IntelliSense not switching the language correctly (https://github.com/Microsoft/vscode-cpptools/issues/2557 ).

**Comment by sean-mcmanus** [comment]
There is another bug -- VS Code's files.associations setting can get `"*.C", "cpp",` added to it, but VS Code doesn't take the casing into account, incorrectly causing all .c files to be associated with C++ instead of C. I've filed a VS Code bug at https://github.com/Microsoft/vscode/issues/59369 and a bug on our side to attempt to workaround that bug at https://github.com/Microsoft/vscode-cpptools/issues/2558 .

**Comment by septag** [comment]
Is this issue fixed ?
my projects seems to be messed up again. C files interpreted as C++ by the syntax checker
tried reloading, restarting, clearing intellisense cache

vscode: 1.32.1
cpp: 0.21.0

**Comment by sean-mcmanus** [comment]
Can you check your files.associations setting to see if any `"*.C": "cpp"` got added? Does it show C or C++ in the bottom right for the files?

**Comment by septag** [comment]
No, I've checked it and there's no wrong association. also there is C in the bottom right. 
but I get many common cpp errors, like casting void* to other pointer types and designated initializers.

also in cpp_settings :
```
"cStandard": "c99"
```

**Comment by septag** [comment]
ah, there is one thing here in cpp_settings from `cmake-tools`:

```
"configurationProvider": "vector-of-bool.cmake-tools"
```

I removed it and replaced it with 
```
"compileCommands": "build/compile_commands.json" 
```

which seems to fix the problem.
So, I'm sorry to bother you, ... again. and I guess this would be `cmake-tools` bug

**Comment by sean-mcmanus** [comment]
It could be a bug with cmake-tools or a bug with our code when a custom configuration provider is used. We should probably look into this later.

**Comment by gdamore** [comment]
I have this same problem, and I am using cmake tools.  I would prefer to *keep* using cmake tools, because it offers me much better support for multiple cross compilation options (cmake toolchains) and better integration with CMake itself.  But it is somewhat annoying that I see warnings that only pertain to C++.  (C99 structure initialization, and also assignment of void * to typed pointers.) 

I have other workspaces which do not use cmake, and they are fine.

I am using VSC on Windows, with Visual Studio 2019, and also with a local copy of gcc set up for cross compilation.
