### ISSUE TITLE
Symbols from files included in "includePath" underlined in red

### ISSUE THREAD

**Issue by jjimenezg93** [microsoft/vscode-cpptools#2555]
**EDIT**: It looks like forcing the use of "C_Cpp.intelliSenseEngine": "Tag Parser" in the settings solves the issue...

---
**Type: LanguageService**

**Describe the bug**
- **Ubuntu 18.04**
- **VS Code Version 1.27.2**
- **C/C++ Extension Version 0.18.1 (August 17, 2018)**

I'm configuring an embedded C project which makes use of an SDK and, if I add to the "includePath" the SDK headers (so I can click on them on the "#include" clauses), I can indeed go to them simply by pressing Ctrl+LMB, but all their functions, which are proxied through "#define", are underlined in red (although I can also go to them with the shortcut). The same goes for some "#define" and one enum I have in my own .h file.

**To Reproduce**
1. Create a new VScode window.
2. Click "Add folder to workspace" and choose the root of the project.
3. Save workspace.
4. Open a .c file.
5. Clic on the lightbulb which appears on the green "#include" lines and choose to edit the "includePath" setting.
6. Add the tag "includePath" and set both your project's and the SDK's include directories as the value.
7. Go back to the .c file and you'll see the includes are now working, but symbols like defines from these files will be underlined in red (although Ctrl+LMB will take you to their declaration).

**Expected behavior**
I should be able to include the .h files like explained, and still have no false errors saying it can't find the symbols in these .h files.

**Comment by bobbrow** [comment]
Using the "Tag Parser" will make all squiggles go away, but the IntelliSense experience will be inferior.  Did you set the `"compilerPath"` property in your configuration?  Since you're working on an embedded project, I suspect that this may resolve some of your squiggle issues.

Take a look at [this documentation](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md#compilerpath-optional).  You can also pass in arguments to the compiler if selecting a specific board is possible or required to get IntelliSense working.

**Comment by jjimenezg93** [comment]
Hi @bobbrow , sorry for the late reply.
I indeed have the `compilerPath` property, this is my **`c_cpp_properties.json`**:
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "<sdk_submodule>/include",
                "<my_own_project>/def",
                "<sdk>/include",
                "/usr/local/include",
                "/usr/include"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

The problem is not with the default system libraries, but our own project's and given embedded SDK's.

Thanks.

**Comment by bobbrow** [comment]
The only thing I can think of is that perhaps the symbols from headers you've included are located within inactive preprocessor blocks.  If you open one of the headers, do you see the code grayed out or dimmed?  If so, you might need to add some preprocessor defines to your `"defines"` array in `c_cpp_properties.json`

If that's not it, I'm going to need a sample of your SDK in order to investigate this problem.  Is there anything you can share with us or is all of this code proprietary?  Another option would to replicate the format of one of the SDK headers and rename the defines/functions/structs such that they are unrecognizable so that we can at least investigate the possible cause.

**Comment by jjimenezg93** [comment]
Hi @bobbrow , once again sorry for the delay.
The symbols are not in inactive preprocessor blocks. Even weirder is that, for example, there's one macro in my x.h which is used in x.c 7 times in consecutive lines. It shows the first occurrence underlined in red and, if I comment out these 7 lines, the next use of this same macro (in the next function) doesn't show any red underlining...
However, with one SDK's function, a lot (but not all) of its occurrences appear underlined in red, not only the first one...

The code is proprietary, so I'd have to try to replicate this elsewhere. I'll add it here once I have enough time to.
Thank you for your replies.

**Comment by sean-mcmanus** [comment]
Are the symbols macros? If so, we have a known bug that can cause macro symbols to get undefined (if a #include duplicate occurs in a file).

**Comment by jjimenezg93** [comment]
Hi, sorry for the late reply.

Today I tried to configure it again, and I think I got to the problem. As mentioned, I'm using an embedded system's SDK. We are provided the headers and this is the `c_cpp_properties.json`:
``` {
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "<path>/SDK/include/**",
                "<path>/SDK/<subpath>/include/**",
                "<path>/SDK/<subpath>/<project>/def/**",
                "/usr/include/**",
                "/usr/local/include/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

So, their SDK's headers are in the first two paths, and project's own headers are in the third one.

Now, the project has also an `src/global.c`, where macros and typedefs from the SDK are used. It has something like:

```
#include <sdk_lib_log.h>
//...
TYPE_A P_LIB;
```

The header `sdk_lib_log.h` already includes the main library header `sdk_lib.h` (I've tried to include it explicitly in `global.c` anyway), although it uses `""` instead of `<>`, but I've also tried both in both places just in case the parser wouldn't look for it on user's include dirs instead of system's.

Now we get to the funny thing. This is the main lib header `sdk_lib_log.h`:

```
//...
typedef void* TYPE_A;
#if !defined(x) && !defined(y)
extern TYPE_A GLOBAL_MACRO P_LIB;
#endif
//...
```

IntelliSense says this about `TYPE_A`:

```
variable "TYPE_A" is not a type name
<error-type> TYPE_A
```

**I know** there could be a problem with P_LIB in my .c since it's inside a `#define`, however, the error is clearly that it's not recognizing the typedef for some reason, even though it's declared right before the global var. Besides that, `GLOBAL_MACRO` expands to `far` and IntelliSense seems to be aware of that since it's showed when I hover over it.

That typedef error drives me crazy. Any solution or could this be a bug?

Thanks.

**Comment by sean-mcmanus** [comment]
You should remove
```
                "/usr/include/**",
                "/usr/local/include/**"
```
and instead rely on the us querying /usr/bin/gcc for those paths.

You can [enable debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to make sure we're using the correct include paths and defines.

The "variable is not a typename" would occur if our parser believes that it's defined as a variable (or something else) instead of a type.

**Comment by jjimenezg93** [comment]
Hi @sean-mcmanus 
Indeed, I had already tried removing default locations, but it doesn't seem to affect the problem.

I understand what you say, but it seems like a bug to me, right? Since it's explicitly defined as a typedef just a couple of lines before:

```
typedef void* TYPE_A;
```

Thanks.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue with typedef void* TYPE_A. My guess is that code before hand causes the parser to enter a bad state, skipping the typedef definition. Are you able to provide a simple repro project I can download?

**Comment by jjimenezg93** [comment]
Hello again.

I have solved the issue. The problem was that there were two preprocessor definitions missing and for some reason it was not graying out the appropriate code.

I have it sort of working now.

Thanks and sorry for the inconveniences.
