### ISSUE TITLE
Find multiple definitions of stdlib.h on mac os x 10.13.6

### ISSUE THREAD

**Issue by idealvin** [microsoft/vscode-cpptools#2577]
**Type: LanguageService**

**Describe the bug**
- OS and Version: mac os x 10.13.6
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them): no

I think vscode-cpptools fail to work out the system include directories，and find multiple stdlib.h in different directories.

**To Reproduce**

1. In a .cpp file, add #include<stdlib.h>
2. Click go to definition

**Expected behavior**

Should find only one stdlib.h.

**Screenshots**

<img width="915" alt="vscode-cpp" src="https://user-images.githubusercontent.com/12691466/46238673-3def5680-c3c1-11e8-9c19-767234a1595b.png">
<img width="907" alt="cpp-prop" src="https://user-images.githubusercontent.com/12691466/46238678-421b7400-c3c1-11e8-919c-ce9e2b3559dc.png">

**Comment by sean-mcmanus** [comment]
We are working on this already -- see https://github.com/Microsoft/vscode-cpptools/issues/2564 . Once, that is fixed, I'll make sure this is also fixed.

**Comment by idealvin** [comment]
@sean-mcmanus Thanks. But please take a look at #2544 . It seems that cpp-tools do not support relative include.

**Comment by sean-mcmanus** [comment]
Sure, I suspect that is a duplicate too, but I'll keep it open for now.

**Comment by bobbrow** [comment]
There is also the issue of `#include_next` that we should take into consideration.  There are, in fact, multiple stdlib.h files that will be included in the translation unit.  In the screenshot above, `/usr/include/c++/4.2.1/tr1/stdlib.h` is not a part of this translation unit, but `/usr/include/stdlib.h` is.  The current problem is due to the fact that we do not pass `/usr/include/*` to the browse engine.

**Comment by sean-mcmanus** [comment]
We believe this is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders -- let us know if it's not.
