### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#2582]
@leslienguyn
copied from: #1041 

Hi! I'm new to C++, and am having trouble with changing my path with Intellisense. I've tried using different paths but it does not work. This may seem simple, however I've spent half of my day trying to fix this and have read up on numerous forums. When I try to run my .cpp file, it says "The active file is not a Python source code." What path should I be putting in here?

<img width="740" alt="help" src="https://user-images.githubusercontent.com/20496347/46241966-91888280-c376-11e8-866b-1434f165ba4f.png">

I'm having the same issue as the OP, but they are using a Mac while I have a Windows.

**Comment by bobbrow** [comment]
Hi @leslienguyn, where did you install your system headers?  VS Code doesn't come with a compiler or STD C++ headers, so you will need to get them either from Visual Studio, or some MinGW distribution.  Once you have installed them, you may add the `"compilerPath"` property to your configuration so that we can ask your compiler where the headers live.  In some cases we can find your compiler on our own, but it's best to set `"compilerPath"` anyway to ensure that you get what you are expecting.

To run a cpp file, you need to compile it first.  You would do this by adding a task to `tasks.json` in the .vscode folder.  To run the program you built, you would then need to add an entry to `launch.json` in the .vscode folder.  We are working on templates and a guide for this, but haven't finished them yet.

**Comment by leslienguyn** [comment]
@bobbrow Hi Bob, I downloaded MinGw and followed the steps [here](http://computing.southern.edu/halterman/Courses/Winter2018/124/Labs/vscode-setup-windows.html). However, I don't think it did anything. So, I installed the EPITECH C/C++ Headers extension from VSCode from your suggestion. I guess my system headers are from the extension? I don't know where everything is or how it can be found. How do you find the compiler or headers?

After searching on my computer, it turns out I don't even have a .vscode folder. Should I just uninstall the entire thing and try reinstalling? I've already done this once but it didn't make a difference.

Sorry for all the complications and newbie questions!

**Comment by bobbrow** [comment]
My guess is that your compiler lives somewhere in the `C:/MinGW` folder.  Do a `dir /s g++.exe` in a CMD window to find the compiler and then copy the full path (e.g. `C:/MinGW/bin/g++.exe`) to the `compilerPath` property in your `c_cpp_properties.json`.

To generate `tasks.json` and `launch.json`, open the command palete (CTL+SHIFT+P) and type `tasks` or `launch` to see the options.

**Comment by leslienguyn** [comment]
When I tried to find the compiler, it said "File not found." I'll try to reinstall MinGW and put it into the right set-up folder and try again.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
