### ISSUE TITLE
Syntax Highlighting and Templated Classes

### ISSUE THREAD

**Issue by KeithBallard** [microsoft/vscode-cpptools#2590]
**Type: LanguageService**

The syntax highlighter does not seem to pick up on types declared by the typename keyword.  For example, the code:

> template\<typename Node>
> class Face;
> 
> template\<typename Node>
> class Edge;
> 
> template\<typename Node>
> class Cell
> {
> public:
>     typedef Face\<Node> FaceType;
>     typedef Edge\<Node> EdgeType;
> };

produces this highlighting:
![image](https://user-images.githubusercontent.com/19842971/46351829-53b18580-c626-11e8-9389-73d71100a0d8.png)

The syntax highlighter should be highlighting Node within the templates as a type.  If there is a setting I am missing, please advise, but I think this might be a bug within the Language Service.

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.19.0

**Comment by bobbrow** [comment]
This is a problem with the TextMate language grammar which it looks like the Atom folks will no longer be updating.  This will have to be addressed with either #230, or https://github.com/Microsoft/vscode/issues/50140.

**Comment by bobbrow** [comment]
Closing this since there are other issues covering it already.

**Comment by EvgeniyPeshkov** [comment]
I've developed and published syntax highlighting extension based on Tree-Sitter. It provides universal syntax coloring engine for almost any programming language (currently, C and C++ are supported OOTB). 
Constructing entire syntax tree, Tree-sitter efficiently overcomes all limitations of built-in TextMate grammars. Being context-aware, it's able to parse complex language structures providing complete coverage of source code.
I've been using it by myself for a month, so I suppose it's ready for public use.

[You can install it from VSCode Marketplace.](https://marketplace.visualstudio.com/items?itemName=evgeniypeshkov.syntax-highlighter)
[Or download .vsix package from GitHub page and install it manually.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
[**Please note**, that extension published in VS Code Marketplace will only work in Windows-x64](https://github.com/EvgeniyPeshkov/syntax-highlighter#distribution).
[For other operating systems, please download pre-compiled .vsix package.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
This will be fixed in the near future with one of the next updates.
Alternatively, you can [build extension from sources](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/BUILD.md).

@KeithBallard , I've tried sample code you've posted. Coloring, provided by Syntax Highlighter, is right:
![templates](https://user-images.githubusercontent.com/50870158/58186265-361c5380-7cbd-11e9-8563-36bface9e5ed.png)
