### ISSUE TITLE
Completion stuck and not reslove header file normally

### ISSUE THREAD

**Issue by yutiny** [microsoft/vscode-cpptools#2619]
Hi, I'm new in cpp.
I know the best IDE is VS, but I only has linux, so i try to use vscode  with c++.

The problem is use with besat:
When `#include <boost/beast.hpp>`  and  continue to type some code, vscode completion stuck and cpu is up to 60%. There's something made vscode completion wrong, it can't reslove header file normally.
Here is the example
![picture](http://www.yutiny.com/images/Screenshot%20from%202018-10-07%2018-05-04.png)

When use `#include <boost/beast/http.hpp>` everything goes well with vscode.

My environment is:
System: Ubuntu 18.04
IDE: VSCode 1.27.2
Extentsion: vscode-cpptools 0.19.0
settings.json: 
```
    "C_Cpp.clang_format_path": "/usr/bin/clang-format-6.0",
    "C_Cpp.clang_format_style": "file",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Disabled",
    "C_Cpp.autoAddFileAssociations": false
```
c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${HOME}/vcpkg/installed/x64-linux/include",
                "${HOME}/include/linux",
                "${HOME}/include/c++/7",
                "${HOME}/include/c++/7/tr1",
                "${HOME}/include/x86_64-linux-gnu",
                "${HOME}/include/x86_64-linux-gnu/c++/7"
            ],
            "forcedInclude": [
                "${HOME}/include/stdlib.h"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": [
                    "${HOME}/vcpkg/installed/x64-linux/include",
                    "${HOME}/include/linux",
                    "${HOME}/include/c++/7",
                    "${HOME}/include/c++/7/tr1",
                    "${HOME}/include/x86_64-linux-gnu",
                    "${HOME}/include/x86_64-linux-gnu/c++/7"
                ]
            }
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Setting your C_Cpp.loggingLevel to "Debug" should allow you to see what compiler and include paths are being chosen by our tool. You should probably set your compilerPath correctly in case it's chosing the wrong one by default. Also, you should remove the system include paths (under "${HOME}/include") from your "includePath" if possible or set your compilerPath to "" in that case if you don't want us to query the compiler for the system includes. I think the problem is the ordering of the system includes is incorrect, because we remove the system includes that we detect and put them at the end in the "correct" order, which can cause the other system includes like "tr1" (which probably shouldn't be in your includePath) to be in the incorrect order.

**Comment by yutiny** [comment]
Thank you for your sugguestions. I set compilerPath to "", then the completion not work at all.
Finally I found that I miss includePath “${HOME}/include”.
It works normally now.
Sorry, my fault.
