### ISSUE TITLE
<typeinfo> must be included before typeid is used

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#2623]
- GCC: MinGW-W64 7.3.0
- IntelliSenseMode: gcc-x64

```c++
#include <typeinfo>
#include <iostream>

int main() {
    const std::type_info &info = typeid(int); //<typeinfo> must be included before typeid is used
}
```

Relative: #1067

**Comment by sean-mcmanus** [comment]
This error occurs when the typeinfo class can't be found (the "must be included" message is misleading).

One workaround should be to add " -fno-ms-extensions" to end of your compilerPath.

I think we should change the default mode for mingw back to the -fno-ms-extensions, because -fms-extensions causes more problems than it solves.

**Comment by sean-mcmanus** [comment]
This should be fixed with https://github.com/Microsoft/vscode-cpptools/releases/download/0.19.1-insiders/cpptools-win32.vsix .
