### ISSUE TITLE
still have “cannot open source file” after setting errorSquiggles to Disabled

### ISSUE THREAD

**Issue by chujinjin101** [microsoft/vscode-cpptools#2678]
After I set errorSquiggles to disabled， there still have “cannot open source file” error， how can I disable 
all Squiggles and disable problems presentation in the problems window

**Comment by sean-mcmanus** [comment]
Oh, yeah, I'm reproing this issue. I think it might be "by design". Setting intelliSenseEngine to "Disabled" and doing a Reload Window will get rid of it, but disable all our language service functionality.

**Comment by bobbrow** [comment]
Error squiggles for missing include files cannot be disabled because missing includes could have a major impact on the IntelliSense experience.  Can you update your includePath so that the squiggles go away?  Use the `"C/Cpp: Edit Configurations..."` command to get to your folder's configuration file.

**Comment by Colengms** [comment]
I believe this was addressed in 0.23.0.  From the change log:

* Change the `Disabled` value for `C_Cpp.errorSquiggles` to stop showing missing header squiggles. [#3361](https://github.com/Microsoft/vscode-cpptools/issues/3361)

* Add a new (default) value of `EnabledIfIncludesResolve` to `C_Cpp.errorSquiggles`, which only shows error squiggles if include headers are successfully resolved. [PR #3421](https://github.com/Microsoft/vscode-cpptools/pull/3421)
