### ISSUE TITLE
[Bug] Go To Declaration/Definition does not initialise properly

### ISSUE THREAD

**Issue by dariuszseweryn** [microsoft/vscode-cpptools#2728]
Not really sure if this should be reported here or on the [`CMake Tools`](https://github.com/vector-of-bool/vscode-cmake-tools/issues) site.

**Type: LanguageService**

**Describe the bug**
- OS and Version: `MacOS 10.13.6`
- VS Code Version: `1.28.2`
- C/C++ Extension Version: `0.19.0`
- Other extensions you installed (and if the issue persists after disabling them): 
    - `CMake` (No — without `CMake` `CMake Tools` cannot work)
    - `CMake Tools` (No)
    - `CMake Tools Helper` (Yes)
    - `Cortex-Debug` (Yes)
    - `Native Debug` (Yes)
    - `GitLens — Git supercharged` (Yes)
- A clear and concise description of what the bug is.
Right after opening a project and waiting the initialisation to settle the `Go To Declaration/Definition` functionality does not function properly for some functions. 

**To Reproduce**

1. Open the project (no tabs opened)
2. Wait for the project to initialise (DB icon disappear in the bottom right part of the `VSCode`)
3. Open file `long_write_service.c`
4. Wait for the flame icon to disappear
5. Float mouse over `sd_ble_user_mem_reply` function (68 LOC)
6. See error — no declaration/definition is suggested
Working scenario below:
7. Close the `VSCode` while `long_write_service.c` is opened
8. Open the project again (`long_write_service.c` is opened from the start)
9. Wait for the project to initialise (DB icon disappear in the bottom right part of the `VSCode`)
10. Wait for the flame icon to disappear
11. Float mouse over `sd_ble_user_mem_reply` function (68 LOC)
12. See declaration/definition suggestion

**Expected behavior**

The IntelliSense `Go To Declaration/Definition` and other helpers should work correctly no matter what is the the tab visible during startup.

**Additional context**

The project uses [`gcc-arm-none-eabi-7-2017-q4-major`](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads) compiler and [`nRF5_SDK_12.3.0_d7731ad`](https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v12.x.x/) Nordic Semiconductors SDK that are put _outside_ of the test project directory.

Attached files:
- Setup files with the test project 
[test_project.zip](https://github.com/Microsoft/vscode-cpptools/files/2519077/test_project.zip)
- Logs from the `C++` plugin for both failure and success scenario 
[intellisense_failure.txt](https://github.com/Microsoft/vscode-cpptools/files/2519073/intellisense_failure.txt)
[intellisense_success.txt](https://github.com/Microsoft/vscode-cpptools/files/2519074/intellisense_success.txt)
- The header file which contains `sd_ble_user_mem_reply` function description (added `.txt` extension) 
[ble.h](https://github.com/Microsoft/vscode-cpptools/files/2519072/ble.h.txt)

**Comment by dariuszseweryn** [comment]
Are there any news?

**Comment by sean-mcmanus** [comment]
The SVCALL macro causes our symbol parser to fail. You need to add "#define SVCALL(x, y, z) ?" where ? corresponds to the definition or something that compiles -- to a cpp.hint file at the location of the code that uses the SVCALL macros. You could be hitting other issues too, since the IntelliSense process is unable to find certain heades, so it's falling back to the tag parser for Go to Def (i.e. no IntellSense based symbol filtering). See https://msdn.microsoft.com/en-us/library/dd997977.aspx for more info on cpp.hint files.

**Comment by dariuszseweryn** [comment]
But why the inconsistency in initialisation?

**Comment by sean-mcmanus** [comment]
What do you mean by "inconsistency in initialization"? The symbol parser needs to work without compiling the #includes in a file and so the macros are not expanded.

**Comment by dariuszseweryn** [comment]
Forgive me if this is a noob question: Why the symbol parser works (Go to Def works) in the second scenario (points 7 to 12) but not in the first (points 1 to 6)? In both cases I was waiting for all activities of the IntelliSense to settle before trying the Go to Def but in one it worked and in other did not. It seems that in one scenario a `cpp.hint` file is obsolete

**Comment by sean-mcmanus** [comment]
Okay, sorry for the misunderstanding -- yeah the failure case is when it falls back to using the Tag Parser because it's using the seemingly incorrect results from the CMake Tools custom configuration provider, but when you start our extension with the file open, the CMake Tools provider isn't ready yet so it's getting the results from the compile_commands.json. That's what is shows in your logs. CMake Tools seems to think your compiler is clang, but your compile_commands.json is using gcc. Are you able to configure CMake Tools? So, you shouldn't actually need to add SVCALL to cpp.hint, unless you want Find Symbol or non-IntelliSense-based Go to Def to work.

**Comment by Colengms** [comment]
This issue appears to have been addressed.  If there is still an issue here, please re-open it.  :)  Thanks.
