### ISSUE TITLE
cannot open source file "map"

### ISSUE THREAD

**Issue by safield** [microsoft/vscode-cpptools#2918]
vscode version: 1.30.0
cpptools version: 0.20.1

I am using android ndk r18 on Windows 10.

Cpptools plugin is giving the error...

> cannot open source file "map"

on line..

`#include <map>`

Compiler path is correctly set to point to clang++.exe in the ndk folder.

Observe the attached project.

[vscNdkTest.zip](https://github.com/Microsoft/vscode-cpptools/files/2673938/vscNdkTest.zip)

**Comment by sean-mcmanus** [comment]
Add "C:\\AndroidTools\\android-ndk-r18b\\sources\\cxx-stl\\llvm-libc++\\include" and "C:\\AndroidTools\\android-ndk-r18b\\sysroot\\usr\\include\\x86_64-linux-android" to your C_Cpp.default.includePath. That fixed it for me. Let me know if there is still an issue. It looks like that android compiler is not setting those paths -- if you check your build process maybe there are flags or additional directories being passed to clang++.exe.

**Comment by safield** [comment]
Thanks, that worked. I was assuming the stl types would be working out of the box.

**Comment by safield** [comment]
Is this expected behaviour to have to include these default include directories for the compiler?

Is this a bug with the cpptools? I am curious if this should be a larger issue like "cpptools is not working with android-ndk clang".

Let me know if there is any further tests I could do to determine where the problem lies.

**Comment by sean-mcmanus** [comment]
Querying the compiler for the system includes works for most other compilers/scenarios, but that particular android tools compiler doesn't appear to send us the sufficient includePaths -- it is not "failing" and it does give us a legitimate clang include path, but it's missing those particular ones with map, etc. For us to improve the setup we would need to figure out if there's a way to get the android clang to provide us a better path, such as via passing it better command line args, or we could detect this particular compiler and auto-add certain directories. I don't think we have data on how many users are using that particular compiler though. If you're able to figure out how your build process itself is obtaining those directories that might help (otherwise, we'd probably have to investigate that).

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
