### ISSUE TITLE
autocomplete for function arguments can not be applied 

### ISSUE THREAD

**Issue by ctin** [microsoft/vscode-cpptools#2924]
**LanguageService**

VSCode Version: 1.27.2
OS Version: OS X 10.14.1
C/C++ extension version: 0.20.1
Other extensions: none
Steps to Reproduce:

Open keybindings.json
Add this key binding:
```
{ "key": "space", "command": "^acceptSelectedSuggestion", "when": "editorTextFocus && suggestWidgetVisible" }
```
or 
```
{ "key": "space", "command": "acceptSelectedSuggestion", "when": "editorTextFocus && suggestWidgetVisible" }
```
Open a code file "foo.h"
Type 
```
struct Foo {
    void foo(int a);
};
```
start typing `void Foo::foo(` below, and helper will show **int a**:
![image](https://user-images.githubusercontent.com/3718295/49948404-70aae480-ff04-11e8-8aea-c2c418324280.png)

Expected: 
By tab, enter, or space button **int a** will be inserted
Actual:
tab, enter or space inserted.
![image](https://user-images.githubusercontent.com/3718295/49948430-7f919700-ff04-11e8-92e2-7ee5fcdf3219.png)

**Comment by sean-mcmanus** [comment]
We're tracking a "Create definition" feature with https://github.com/Microsoft/vscode-cpptools/issues/664 .

The current signature help isn't supposed to autocomplete params from the declaration.

**Comment by ctin** [comment]
@sean-mcmanus can you please explain, why we can not just apply suggestion by pressing enter?
It appears correctly, so all what I need - is just to insert it to my code.

**Comment by sean-mcmanus** [comment]
Because the "suggestion" you are seeing is not a VS Code completion result -- it is a "signature help" result. There is no UI mechanism in VS Code to have a signature help result morph into a completion result. We just send VS Code the data and they handle all the UI and text replacement. You would need to file a feature request with VS Code itself to somehow enable a signature help result to also provide completions.

**Comment by ctin** [comment]
@sean-mcmanus Thank you for replying. I will follow this feature.
