### ISSUE TITLE
Implement advanced debugging features.

### ISSUE THREAD

**Issue by ci70** [microsoft/vscode-cpptools#2929]
- Parallel Watch
- Parallel Stacks
- Just My Code
- (Re)naming threads.
- Flag and Unflag Threads
- Debugging multiple processes
- Assembly view
- Memory view
- Extended register information
- Edit and Continue
- Time Travel Debugging (through WinDBG)
- Remote debugging

All these are present in VS2017 and since both use the same debugger engine it should 
not be difficult to add.

**Comment by jeremyong** [comment]
Just wanted to mention that this would be amazing, and add to the list:

- Modules view
- Hardware breakpoints

I currently maintain a completely set of launch tasks for Visual Studio because the C++ debugger in VSCode is a bit too spartan for most tasks. Occasionally I use WinDbg also but having feature parity between VSCode and the other tools would make VSCode a better "all-in-one" replacement.

**Comment by starball5** [comment]
Edit and continue is tracked in #7834
