### ISSUE TITLE
Add source language mapping to the Concord debug engine

### ISSUE THREAD

**Issue by rainers** [microsoft/vscode-cpptools#2932]
In Visual Studio the Concord debug engine can be configured to match custom expression evaluators to the source language (as embedded into the object/pdb file) via the "Debugger\CodeView Compilers" registry keys.

It seems the VS Code Concord engine scans extensions in the vsdbg\bin folder, but there does not seem a way to do the same source language mapping in VS Code? Could this be added and would it be enough to load the expression evaluator?

**Comment by gregg-miskelly** [comment]
Currently vsdbg hard codes these values, but it wouldn't be hard to change vsdbg to support reading these settings from some sort of .json/.xml file. The slightly trickier bit would be for vsdbg to know what directories it should probe to discover your EE.

Do you currently ship (or would expect to ship) as a VS Code extension?
Do you need to customize anything else about debugger launch besides adding new Concord components and adding to "Debugger\CodeView Compilers"?

**Comment by rainers** [comment]
> Do you currently ship (or would expect to ship) as a VS Code extension?

Not yet, but it could be made part of https://marketplace.visualstudio.com/items?itemName=webfreak.code-d as a better alternative to https://marketplace.visualstudio.com/items?itemName=webfreak.debug.

> The slightly trickier bit would be for vsdbg to know what directories it should probe to discover your EE.

For Visual Studio it is just installed into `<VS-Path>\Common7\Packages\Debugger`, but I guess that's not working with vsdbg being an extension itself.

> Do you need to customize anything else about debugger launch besides adding new Concord components and adding to "Debugger\CodeView Compilers"?

Nothing that I'm aware of right now...

**Comment by TurkeyMan** [comment]
I have a colleague who prefers VSCode to our company standard VS rollout, and this ticket would really help him with his workflow.

**Comment by gregg-miskelly** [comment]
@TurkeyMan is your scenario also for D language support? If not, can you elaborate a bit more on your scenario.

**Comment by TurkeyMan** [comment]
Yes, it is @rainers work (above) specifically that I refer to. He maintains an unusually high quality language integration to VS, and it would be nice to have that experience available to VSCode aswell.
Our studio uses VS primarily, but some users prefer VSCode.

**Comment by TurkeyMan** [comment]
Currently, those users have VS and VSCode both open, they edit in Code, and switch back to VS to build & run, which looks very annoying to me as a bystander ;)

**Comment by gregg-miskelly** [comment]
Makes sense. This is something we are interested in supporting, but we haven't yet found the cycles to go and implement it.

**Comment by ivanpovazan** [comment]
@gregg-miskelly is there any progress with vsdbg regarding this issue?

**Comment by Imperatorn** [comment]
Status?

**Comment by andre2007** [comment]
@gregg-miskelly i am also highly interested in this feature. I am using Visual Studio Code at work and this missing feature blocks blocks me from using a debugger on Windows.

**Comment by ivanpovazan** [comment]
After some discussions and really nice cooperation with @gregg-miskelly this is available from few months ago. You can find more information regarding the configuration and set up here: https://github.com/microsoft/ConcordExtensibilitySamples/wiki/Support-for-cross-platform-.NET-scenarios

**Comment by rainers** [comment]
> After some discussions and really nice cooperation with @gregg-miskelly this is available from few months ago.

This is great news. Is it already available in the ms-vscode-cpptools exension? I tried 1.3.1, but none of the documented files (e.g. $HOME/.dotnet/vsdbg-extensions/*) seem to be accessed (according to procmon).

**Comment by GavinRay97** [comment]
@rainers Hey Raniers -- huge fan of your work on D & VisualD.

I spent some time trying to figure this out so I could share with you a working example and then maybe we'll see the fruits of it in the D community.

Here's what I did in order to get it working (The toy "Iris" language compiler, and debug adapter + VS Code visualizer):

- Cloned https://github.com/microsoft/ConcordExtensibilitySamples
- Opened ConcordExtensibilitySamples/Iris/Iris.sln in Visual Studio 2019
	- _(From here follows along from the `xplat-package` README, with some manual tweaks)_
	- https://github.com/microsoft/ConcordExtensibilitySamples/blob/main/Iris/xplat-package/README.md
- I have the Microsoft C# extension for VS Code installed. To find out the version, I ran:
	- ```sh
		$ ls $HOME/.vscode-insiders/extensions | grep csharp
		ms-dotnettools.csharp-1.23.11/
	  ```
	- **Note that I use `vscode-insiders` so throughout this, remove the `-insiders` suffix if you don't**
- The placeholder version `1.2.3` is used in the template, search for `1.2.3` and substitute your version in these places:
	- ![image](https://user-images.githubusercontent.com/26604994/115970566-293fb480-a511-11eb-87f2-0357700cbe62.png)
- After these have been compiled, the project can actually be compiled. You must compile them all:
	- ![image](https://user-images.githubusercontent.com/26604994/115970638-b1be5500-a511-11eb-84b2-0d09c2c56683.png)
	- I _believe_ that the build process will attempt to run `xplat-package/CreateLinkFile.cmd.txt`, the script which creates the necessary "link" inside of ` $HOME/.dotnet/vsdbg-extensions/<Your-Company-and-Extension-Name>.link` which is required for VS/VS Code to be made aware of it through the debug driver.
	- Just to confirm, you may want to run it manually though.
- Now, start the `vsdbg` adapter debugger via the `Debug > xplat-package > Windows` debug configuration
	- ![image](https://user-images.githubusercontent.com/26604994/115970759-8c7e1680-a512-11eb-84db-ca06dd5be400.png)
	- ![image](https://user-images.githubusercontent.com/26604994/115970798-d49d3900-a512-11eb-8dfb-110dde2e4c32.png)


- Open `Iris/Programs` in VS Code
- As a quick hack, let's create a folder `.vscode` and make `.vscode/settings.json` to enable debugging symbols in any file (we haven't properly set up the language and debug adapter ID's in a packaged extension).
	- ![image](https://user-images.githubusercontent.com/26604994/115970816-f3033480-a512-11eb-90df-6e5560a49809.png)
- Now, open `Iris/Programs/TicTacToe.iris`, set a breakpoint somewhere.
- Press `Ctrl + Shift + P`, run `Tasks: Run Tasks`, then select `build` to compile the program with the toy `iris` compiler
	- ![image](https://user-images.githubusercontent.com/26604994/115970877-62792400-a513-11eb-95a3-f5794d972cd9.png)
- Last step, we need to edit the launch task for debugging so that it uses a regular console for `stdout`/`stdin` because the program is interactive, so we set `"console": "integratedTerminal"`inside of `.vscode/launch.json`:
	- ![image](https://user-images.githubusercontent.com/26604994/115971140-c223ff00-a514-11eb-9f2b-5c9bc4af4296.png)
- Finally, press `F5` in VS Code
	- (You can also put breakpoints in Visual Studio inside of anywhere in the `Iris/IrisExtension` or `Iris/IrisCompiler` to debug on the side of the debugger, too)
- It should break on the entrypoint, at `begin`:
	- ![image](https://user-images.githubusercontent.com/26604994/115970943-b84dcc00-a513-11eb-8d3b-81f8350cfa3c.png)
	- You should notice the extension has been loaded as the first line of the output:
		- ![image](https://user-images.githubusercontent.com/26604994/115971099-94d75100-a514-11eb-9529-7a205b93ab39.png)

- Press `F5` for continue, if you've set the same breakpoint I have. It'll ask for a tic-tac-toe move input on your terminal. Enter a random move, and then the breakpoint should be triggered. You will be able to see the locals in the `debug` info as well:
	- ![image](https://user-images.githubusercontent.com/26604994/115971202-23e46900-a515-11eb-9d77-8693fc7f1d04.png)

Ta-da!! 🥳 🎉 

The final steps would be to write the JSON configuration in a proper extension that registers the language, and the `vsdbg-config.json`:

- `vsdbg-config.json`:
	- https://github.com/microsoft/ConcordExtensibilitySamples/wiki/Support-for-cross-platform-.NET-scenarios#vsdbg-configjson-files
- Breakpoint registration:
	- https://github.com/OmniSharp/omnisharp-vscode/blob/f1f7096369299bd63aa2b5092d6c209a6349f637/package.json#L1030
- Language registration:
	- https://github.com/OmniSharp/omnisharp-vscode/blob/f1f7096369299bd63aa2b5092d6c209a6349f637/package.json#L3612

**Comment by rainers** [comment]
@GavinRay97 Thank you for the detailed description.

I installed the dotnet tools. When the coreclr debugger is spawned, the vsdbg-extension folder is searched and the linked vsdconfig is loaded. So it seems the extensibility is implemented in the C# debugger, but not the one that comes with the C++ tools.

For D, we need a native debugger, or one with a mixed mode (CLR+native). According to https://github.com/OmniSharp/omnisharp-vscode/issues/3068, the mixed mode is not available with the dotnet-tools.

I'm not really familiar with VS code, so I might be missing something. But as far as I can tell that means we have to wait for the extensibility to be available within the cpptools. Is that planned for the future, @gregg-miskelly ?

**Comment by GavinRay97** [comment]
I'm uncertain but you may want to ask @WardenGnaw, they are listed here as the maintainer of the `cpptools` stuff:

![image](https://user-images.githubusercontent.com/26604994/116109825-295fc180-a683-11eb-97ec-d74d53c2fee0.png)

> For D, we need a native debugger, or one with a mixed mode (CLR+native). According to OmniSharp/omnisharp-vscode#3068, the mixed mode is not available with the dotnet-tools.

Yeah I was afraid of this, since that tutorial is for debugging managed code.

I don't know anything about this (certainly much less than you having written VisualD + integrated MagoMI into it).

But poking around this repo, it looks like the `cppvsdbg` type is actually just `vsdbg` 🤔 
https://github.com/microsoft/vscode-cpptools/blob/d9551d2dcc21226ce4545c6d78c182ed13d9194b/Extension/src/Debugger/debugAdapterDescriptorFactory.ts

```ts
// Registers DebugAdapterDescriptorFactory for `cppdbg` and `cppvsdbg`. If it is not ready, it will prompt a wait for the download dialog.

// <snipped>

export class CppvsdbgDebugAdapterDescriptorFactory extends AbstractDebugAdapterDescriptorFactory {
    public static DEBUG_TYPE: string = "cppvsdbg";

    constructor(context: vscode.ExtensionContext) {
        super(context);
    }

    createDebugAdapterDescriptor(session: vscode.DebugSession, executable?: vscode.DebugAdapterExecutable): vscode.ProviderResult<vscode.DebugAdapterDescriptor> {
        if (os.platform() !== 'win32') {
            vscode.window.showErrorMessage(localize("debugger.not.available", "Debugger type '{0}' is not avaliable for non-Windows machines.", "cppvsdbg"));
            return null;
        } else {
            return util.isExtensionReady().then(ready => {
                if (ready) {
                    return new vscode.DebugAdapterExecutable(
                        path.join(this.context.extensionPath, './debugAdapters/vsdbg/bin/vsdbg.exe'),
                        ['--interpreter=vscode']
                    );
                } else {
                    throw new Error(util.extensionNotReadyString);
                }
            });
        }
    }
}
```

The only difference between `cppdbg` and `cppvsdbg` seems to be that `cppdbg` launched `OpenAD7.exe` as the debug adapter instead of `vsdbg.exe`.

The `cppvsdbg` tool says that it's run on MIEngine, and it looks like that repo is (almost) entirely C#.
I had a peek at the implementation, it seems to be interface-based, where the managed C# app is taking in data from another process and acting as a kind of frontend to it.


https://github.com/microsoft/MIEngine/blob/ff5e23813c218f894bb8a712478cfbdee12504dc/src/DebugEngineHost/HostMarshal.cs#L60-L76

```cs
namespace Microsoft.DebugEngineHost
{
    /// <summary>
    /// This class provides marshalling helper methods to a debug engine. 
    /// 
    /// When run in Visual Studio, these methods deal with COM marshalling.
    /// 
    /// When run in Visual Studio code, these methods are stubs to allow the AD7 API to function without COM.
    /// </summary>
    public static class HostMarshal
{

   <snipped>

    /// <summary>
    /// Obtains a function position interface given the specified IntPtr of the location.
    /// </summary>
    /// <param name="locationId">In VS, the IUnknown pointer to QI for a function position. In VS Code,
    /// the identifier for the function position</param>
    /// <returns>Function position object</returns>
    public static IDebugFunctionPosition2 GetDebugFunctionPositionForIntPtr(IntPtr locationId)
    {
        // TODO: It looks like the MIEngine currently leaks the native document position. Fix that.
        if (!Host.IsOnMainThread())
        {
            Debug.Fail("Operation should be on main thread.");
            throw new MethodAccessException("COM Operation must occur on main thread.");
        }

        return (IDebugFunctionPosition2)Marshal.GetObjectForIUnknown(locationId);
    }
```

![image](https://user-images.githubusercontent.com/26604994/116111257-7abc8080-a684-11eb-8d0c-556c4097588d.png)

Maybe it's possible that this debug adapter is more of a frontend and can be managed code and then you have another binary the debug adapter process is spawning and receiving data from, and this can be whatever you need?

I'm not really sure. I poked around the innards of the CPP debug extension. Here's what I found, at a quick glance:

- `debugAdapters/bin/vsdbg/CppDebug.dll` exports these methods:
	- ![image](https://user-images.githubusercontent.com/26604994/116119822-d7bc3480-a68c-11eb-9e4a-536fa0a35c36.png)
- It imports the CLR and initializes the runtime, and also imports the `Dkm` methods 
	- ![image](https://user-images.githubusercontent.com/26604994/116121546-b65c4800-a68e-11eb-9d50-006258c765df.png)
 	- ![image](https://user-images.githubusercontent.com/26604994/116121810-fb807a00-a68e-11eb-9fb1-9950d28a0547.png)
- `CppDebug.dll` implements the `Microsoft.VisualStudio.Debugger.ComponentInterfaces` methods and the `Microsoft.VisualStudio.Debugger.Evaluation.*` methods
	- ![image](https://user-images.githubusercontent.com/26604994/116122434-c7f21f80-a68f-11eb-8cc9-3fc46d5286fb.png)
	- ![image](https://user-images.githubusercontent.com/26604994/116122492-db04ef80-a68f-11eb-87c6-afe1142cc872.png)
    - ![image](https://user-images.githubusercontent.com/26604994/116122715-24edd580-a690-11eb-9b5f-1436f2f0994e.png)
    - `Microsoft.VisualStudio.Debugger.Evaluation.DkmVisualizedExpression` type displayed in the RTTI/Vtable return type info from CPP class method info above: ![image](https://user-images.githubusercontent.com/26604994/116122952-64b4bd00-a690-11eb-869b-a24de2e9a73c.png)

**Comment by gregg-miskelly** [comment]
@rainers Are you interested in cppvsdbg (Concord-based native debugging on Windows) or cppdbg (gdb/lldb-based native debugging)?

We don't have any plans to somehow support native expression evaluators on top of GDB/LLDB. The right way to solve that would probably be to somehow integrate support into GDB/LLDB itself, and modify launch.json to use this new build of GDB/LLDB.

For vsdbg: The support that has been built thus far is just for cross platform .NET expression evaluators. That said, I think I could find the cycles to make this work for expression evaluators for native code, or at least I would be interested in trying. So if you (or anyone else reading this) has the cycles to try out bits, let me know and I can see what I can do.

**Comment by rainers** [comment]
> @rainers Are you interested in cppvsdbg (Concord-based native debugging on Windows) or cppdbg (gdb/lldb-based native debugging)?

@gregg-miskelly I'm interest in the concord-based native debugging.

> So if you (or anyone else reading this) has the cycles to try out bits, let me know and I can see what I can do.

This would be great! The extension for the D language implements only a couple of interfaces, but probably a good start to test. See  https://github.com/rainers/mago/blob/master/EED/MagoNatCC/MagoNatCC.vsdconfigxml

Thanks, @GavinRay97 for your analysis, but I guess it's way more efficient if Gregg can add direct support for extensions into cppvsdbg.

**Comment by gregg-miskelly** [comment]
@rainers How do you register to `$RootKey$\Debugger\CodeView Compilers`? I couldn't find a .pkgdef from a few searches (though maybe I messed up or GitHub search is failing me).

**Comment by GavinRay97** [comment]
>  So if you (or anyone else reading this) has the cycles to try out bits, let me know and I can see what I can do.

I think there are a good handful of enthusiasts from the D community who could spare some time to help or test wherever might be useful (myself included) 👍

**Comment by rainers** [comment]
> @rainers How do you register to `$RootKey$\Debugger\CodeView Compilers`?

The extension is registered as part of the Visual D installation. The pkgdef is generated at install time here: https://github.com/dlang/visuald/blob/master/visuald/register.d#L845-L859

The resulting section in the pkgdef is then:
```
[$RootKey$\AD7Metrics\ExpressionEvaluator\{002A2DE9-8BB6-484D-9800-7E4AD4084715}\{002A2DE9-8BB6-484D-987E-7E4AD4084715}]
"Language"="D"
"Name"="D"

[$RootKey$\AD7Metrics\ExpressionEvaluator\{002A2DE9-8BB6-484D-9800-7E4AD4084715}\{002A2DE9-8BB6-484D-987E-7E4AD4084715}\Engine]
"0"="{449EC4CC-30D2-4032-9256-EE18EB41B62B}"
"1"="{92EF0900-2251-11D2-B72E-0000F87572EF}"
"2"="{3B476D35-A401-11D2-AAD4-00C04F990171}"

[$RootKey$\Debugger\CodeView Compilers\68:*]
"LanguageID"="{002A2DE9-8BB6-484D-9800-7E4AD4084715}"
"VendorID"="{002A2DE9-8BB6-484D-987E-7E4AD4084715}"
```

**Comment by gregg-miskelly** [comment]
Thanks. At least from my testing, enabling this turned out to be fairly simple. It will be a little while still before we put out bits, but in case anyone wants to get started, here is the preliminary documentation: https://github.com/microsoft/ConcordExtensibilitySamples/wiki/Support-for-VS-Code-cppvsdbg-Scenarios

**Comment by rainers** [comment]
@gregg-miskelly Cool, looks promising. Looking forward to trying it out :-)

**Comment by gregg-miskelly** [comment]
This will be addressed by https://github.com/microsoft/vscode-cpptools/pull/7467

**Comment by rainers** [comment]
@gregg-miskelly I just tried cpptools-1.4.0 and expression evaluation with mago works like a charm. I had a bit of trouble finding out how to enable breakpoints (I haven't written any extensions for VS Code myself yet), but figured it's pretty easy by adding the respective "breakpoints" option to any package.json.

Thanks a lot!

**Comment by gregg-miskelly** [comment]
@rainers Excellent! Glad to hear it.
