### ISSUE TITLE
Go to Definition feature does not always work for c++ files

### ISSUE THREAD

**Issue by dk1301** [microsoft/vscode-cpptools#2947]
VSCode Version: 1.30.1
cpptools version: 0.20.1
OS Version: Ubuntu 16.04 amd64
Steps to Reproduce:

Just right click a method and press go to definition most of the times it leads to declaration. Peek definition also doesn't wotk most of the times.
Does this issue occur when all extensions are disabled?: Yes

I have asked a revevant question in stackoverflow for 1.29.1 (https://stackoverflow.com/questions/53779636/neither-go-to-definition-nor-peek-definition-features-work-in-vscode-1-29-1-for) but I got no answer. As I mentioned there in version 1.29.1 some times it works only for a couple of times after shutting down and repoening the vscode and afterwards the same faulty behavior. The same occurs for 1.30.1.  Furthermore for some methods it works while for others it doesn't. I have also changed the  "C_Cpp.default.intelliSenseMode" field in user settings from clang-x64 to gcc-x64 but i got the same behavior. Even when I got to the header file at the declaration of the method and press goto definition the ide remains at the declaration.
 
The c_cpp_properties.json file I use is the following:

```
 {
   "configurations": [
       {
           "name": "Linux",
           "browse": {
               "path": [
                   "${workspaceFolder}"
               ],
               "limitSymbolsToIncludedHeaders": false
           },
           "includePath": [
               "${workspaceFolder}/include"

           ],
           "defines": [],
           "compilerPath": "/usr/bin/gcc",
           "cStandard": "c11",
           "cppStandard": "c++17",
           "intelliSenseMode": "clang-x64"
       }
   ],
   "version": 4
  }

```

**Comment by sean-mcmanus** [comment]
Our Insider version fixed some Go to Definition bugs: https://github.com/Microsoft/vscode-cpptools/releases , but it sounds like you're hitting some other issues. What happens when you open the file with the definition in it? Do you see the definition symbol in the Outline pane? If you hover over a number like 0 do you see ((int)0) -- that would mean IntelliSense is activated, which can give better Go to Def results.

**Comment by dk1301** [comment]
I have tested it with latest insider version as well. For the faulty cases when I open the file with the definition in it I see the definition symbol correctly. If I hover over a number  I see the (int) number. The issue is that for some case the goto Definition is behaving like Go to Declaration with the header file's symbols in the outline pane. And I haven't figured a pattern about these methods , e.x void or with no arguments.

**Comment by sean-mcmanus** [comment]
In order to diagnose the problem we need more info as to which scenario is buggy, and preferably a repro with some simple cases.

If you use Go To Def and the definition is in the same TU (source + #included files) then it will rely on the IntelliSense engine parser to get the definition. But if the definition is not in the current file, then it attempt to query our global "tag parser" database to try to find the file/location of the definition (but using the type info from IntelliSense). If that fails, then it can fall back to just going to the declaration in the TU.

We had a bug with Insiders that was omitting the "(declaration)" on symbols, but something like "(declaration) func" and "func" should appear if you click the status bar where it may say (Global Scope). So if you see the "func" there then you know that the global symbol was parsed correctly.

One potential source of problems that you might be hitting is that if the types of the definition is "too complicated" it's possible we are not comparing the types in our database and the types in the TU correctly, resulting in an incorrect "the types don't match". An example of a bug like this is https://github.com/Microsoft/vscode-cpptools/issues/2802 .

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
