### ISSUE TITLE
How to disable auto-complete in comments

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#295]
Auto-complete in comments can be annoying. Is there a way to disable it?

**Comment by sean-mcmanus** [comment]
```
"C_Cpp.autocomplete": "Disabled",
"editor.wordBasedSuggestions": false
```

The 1st disables our C++ autocomplete and the 2nd disables the VS Code's word based autocomplete. A future release is expected to disable C++ autocomplete in comments.

**Comment by daldr-ntml** [comment]
Thanks for your answer. Are these options documented anywhere?

**Comment by sean-mcmanus** [comment]
Sort of. File->Preferences->User/Workspace Settings brings up a Default Settings that lists the settings and has a link to some online docs for VS Code in general, and you get auto-complete with tooltips in the settings.json when you type.

**Comment by pushqrdx** [comment]
still an issue 4 years later :D

**Comment by trusktr** [comment]
> Auto-complete in comments can be annoying

Can I ask why? (Just curious). Is it because the `enter` key annoyingly auto-completes instead of making a new line?

What I find works is:

- disable `editor.acceptSuggestionOnEnter` so that enter key won't get in the way.
- disable `editor.acceptSuggestionOnCommitCharacter` so that typing certain sequences won't autocomplete

Basically, I like that to have _one and only one_ way to perform auto-complete (with the `Tab` key), so I disable all other ones. This way I am in control without time-wasting surprises.
