### ISSUE TITLE
Enable WSL compilerPath to work with compilers under /mnt

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2978]
See https://github.com/Microsoft/vscode-cpptools/issues/2968 for repro details.

Our code expects compilerPath to point to a WSL binary under the WSL rootfs and not under /mnt.

Not sure how common this scenario is.

**Comment by zhiayang** [comment]
I couldn't find out where in the code the extension calls the compiler, but if we need to go through `wsl.exe` to run (because ofc the compiler can't be run on windows), then shouldn't `/mnt` already be populated?

**Comment by sean-mcmanus** [comment]
The code that does this is in our closed-source part.

Yeah, we invoke the compiler from wsl.exe, but the results we take the results and append the Windows-path to the rootfs, which is incorrect for /mnt results, so we need to check for `/mnt/<drive>` and convert that to a windows path like `<drive>://`.

**Comment by zhiayang** [comment]
Is this on the roadmap to being fixed (in 0.21 maybe)? I'm getting a lot of false errors currently; for example because `unsigned long` is 32-bits on my host platform but 64 bits on the target.

If there are more pressing issues (understandably), I'll build a new toolchain outside of `/mnt` for the time being -- hopefully it'll be fixed eventually.

Thanks!

EDIT: hm, just realised this wouldn't work, because the sysroot needs to be inside the project path as well... (and because of WSL limitations the project folder needs to live in `/mnt`)

**Comment by sean-mcmanus** [comment]
Maybe for our February release...not sure yet. I think it would be "quick fix".

**Comment by zhiayang** [comment]
Hi there,

Any updates on this issue?

Thanks!

**Comment by sean-mcmanus** [comment]
I'm not sure yet what the priority is (i.e. this issue hasn't gotten any upvotes or reports from other users).

It seems like we'll be too busy with other stuff to get this in for the February/March release, but I could move it to April for us to consider then.

**Comment by bobbrow** [comment]
We're not likely to make any more changes to our WSL support now that the Remote-WSL extension is available.
