### ISSUE TITLE
A file that starts with undefined macro will influence the whole code window display

### ISSUE THREAD

**Issue by LiunxPaisley** [microsoft/vscode-cpptools#3008]
I'm using vscode through a VNC connection to Ubuntu. The desktop version is gnome.

![snipaste_2019-01-08_17-46-17](https://user-images.githubusercontent.com/23477633/50823061-128be880-136e-11e9-9ae1-8936c7390dcc.png)

After disabling the cpptool, the whole windows displays normally.

![snipaste_2019-01-08_17-54-29](https://user-images.githubusercontent.com/23477633/50823233-77dfd980-136e-11e9-95c3-366071bfffab.png)

Macro "USE_CUDNN" is the undefined macro.

**Comment by sean-mcmanus** [comment]
This is "by design" -- you can disable it by adding the undefined macro to the setting `"C_Cpp.default.defines": [ "USE_CUDNN" ]`, or setting the C_Cpp.default.forcedInclude setting to a header file that defines that (or you could modify the equivalent settings in your c_cpp_properties.json). You could also change the C_Cpp.dimInactiveRegions setting to false, but then you won't get IntelliSense features for code in the disabled regon.

There should be a code action icon with the disable option in it (it might be good to later add another option to auto-add the define as well): 
![image](https://user-images.githubusercontent.com/19859882/50855160-f66f5380-133b-11e9-8fa3-822b682c5ce4.png)

**Comment by LiunxPaisley** [comment]
Adding the undefined macro to the setting `"C_Cpp.default.defines": [ "USE_CUDNN" ]` indeed works. But I still think it is a GUI bug, because in another machine, the extension works well without this setting.

![snipaste_2019-01-09_15-49-23](https://user-images.githubusercontent.com/23477633/50884560-2bf06b80-1426-11e9-9dd8-4e9bd762223c.png)

**Comment by sean-mcmanus** [comment]
The most likely explanation for the code not being transparent on your other machine is that we disable transparency (inactive regions) when we fall back to the Tag Parser, such as due to `#includes` not being found in the includePath.

On the machine that is not rendering transparent, you could try hovering your mouse over USE_CUDNN to see if it shows it as a define or not, and if you hover over a literal integer like 0 and it doesn't show `(int)0` that means the region is disabled for IntelliSense (i.e. should normally be transparent).

Our extension doesn't control the GUI rendering itself. We just set the vscode.TextEditor.setDecorations with a transparency value and VS Code does the actual graphical rendering, so maybe there is a VS Code issue that is preventing transparent rendering on your other machine? The code that sets the transparent rendering is at https://github.com/Microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/client.ts if you want to debug the TypeScript (updateInactiveRegions function).
