### ISSUE TITLE
IntelliSense-based Go to Definition returns both const and non-const methods as results (instead of just the matching one)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3015]
After the fix for https://github.com/Microsoft/vscode-cpptools/issues/3014 ships.

struct foo
{
    int func() const; // These are defined in a different .cpp file.
    int func();
};

int main()
{
    foo f;
    f.func(); // Go to def doesn't take the const-ness into account and returns both.
}

This seems too low priority to worry about currently. If anyone wants this fixed, upvote it.

**Comment by michelleangela** [comment]
The following issue may be related. The scenario is not typical as user would not do a "go to definition" on a definition. 

Sample code:
```
int func1(); // declaration
int func1(float var1) // local param
{
    {
        double var1 = 0; // new local scope
        return var1;
    }
    return var1 + func1();
}

int func1() // overload. Returns confirmed and non-confirmed references.
{
    if (var1 == 0)
        return func1(0);
}
```

1. Do a "Go to definition" on definition of `int func1(float var1)`
2. It returns two results instead of just staying at the definition. 

![image](https://user-images.githubusercontent.com/38734287/125575632-3ec02c75-7b1c-4e24-b18d-31d9a07fd50a.png)

Does it return two results because it's an overloaded function?

**Comment by sean-mcmanus** [comment]
@michelleangela I think it's doing a Find All References. I think you can change the behavior via changing editor.gotoLocation.alternativeDefinitionCommand.

**Comment by bobbrow** [comment]
The original issue appears to be fixed now.
