### ISSUE TITLE
going to definition errors about struct ,class and enum variables

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3071]
**Type: LanguageService**

**Describe the bug**
- VS Code Version:  1.30.2
- C/C++ Extension Version:  0.21.0-insiders4
- Other extensions you installed (and if the issue persists after disabling them): 
- A clear and concise description of what the bug is.

when there are some errors before struct and class variables declaration, 'go to definition' about the member of this struct and class will be disabled. Codes are as below.

**structTest.h:**
typedef struct AA_STRUCT
{
    int WorkSecondsElapsed;
}AA_STRUCT;

**structTest.app**
#include <stdio.h>
#include "structTest.h"
**add some words**
AA_STRUCT g_struct;
int testd1()
{
    g_struct.WorkSecondsElapsed = 1;
    return 0;
}

**I added some words before AA_STRUCT g_struct this variable and then 'go to definition' about g_struct and WorkSecondsElapsed will be disabled.
Enum and Class variables have some same behavior with struct variables. The codes are as blow. **

**classTest.h**
class CLassA {
public:
    CLassA(){}
    int WorkSecondsElapsed;
    int test(){return 0;} 
};

**classTest.cpp**
#include <stdio.h>
#include "classTest.h"
int testd1()
{
    **add some words**
    CLassA *pCA = new CLassA();
    pCA->WorkSecondsElapsed = 1;
}

**enumTest.h**
**add some words**
enum MONTH_1 {
    JAN = 0,
    FEB = 1
}

**enumTest.cpp**
#include <stdio.h>
#include "enumTest.h"
int testd1()
{
  int i = MONTH_1::JAN;
}

When there are some errors(you can type  some words in 'add some words' region above) before struct, class and enum variables , 'go to definition' about these variables will be disabled.

Lennon

**Comment by Lennon925** [comment]
@sean-mcmanus 

Hi sean-mcmanus,

could you support these scenarios above？

Best Regards,
Lennon

**Comment by sean-mcmanus** [comment]
Yeah, this looks like a bug -- IntelliSense-based Go to Definition should fall back to the Tag Parser results, which is what Visual Studio does. It may be quick to fix for our next release.

**Comment by sean-mcmanus** [comment]
A workaround for this is to pass a forcedInclude.h file to the forcedInclude setting that has text "#include <non_existent>" -- then with the C_Cpp.intelliSenseEngineFallback set to Disabled it should cause Go to Definition to succeed (via falling back to the Tag Parser's results). Umm...but that will cause a "cannot open source file "non_existent"" error to occur in all your files, so that probably isn't what you want :)

**Comment by Lennon925** [comment]
local variables have the same behavior with them,too.

int testd1()
{
  xdsas
  int i = MONTH_1::JAN;
  int m = i+2;   /// variable 'i' can't go to definition.
}

**Comment by sean-mcmanus** [comment]
I believe the local variable case is "by design" and it isn't a regression, and repros with Visual Studio as well -- the reason is because the error before "int i" causes our IntelliSense parser to not recognize the "int i" definition. However, I have filed a bug with the Visual C++ team at https://developercommunity.visualstudio.com/content/problem/435720/go-to-definition-doesnt-work-with-local-variables.html, so people can upvote that an maybe they'll fix it, but my guess is that it won't be fixed.

**Comment by Lennon925** [comment]
@sean-mcmanus ，

Taking the liberty to ask，How long will you take to fix this issue ?

**Comment by sean-mcmanus** [comment]
Not sure. The fix should be quick, but I'm busy with other stuff. Hopefully for 0.22.0 in the next month.

**Comment by Lennon925** [comment]
> Not sure. The fix should be quick, but I'm busy with other stuff. Hopefully for 0.22.0 in the next month.

this issue will be fixed in march, right?

**Comment by sean-mcmanus** [comment]
Not the March official release (next week), but maybe for the March Insiders later. We'll have to move a bunch of the February tasks to the next milestone (due to unexpected delays/issues).

UPDATE: Probably won't have time to investigate Go to Def bugs until after April 15th.

**Comment by sean-mcmanus** [comment]
@Lennon925 I think this is fixed with 0.23.1, but I'm not 100% because your repro steps did not explicitly say what variable Go to Def is failing for in your second example.
