### ISSUE TITLE
feature that controls when the symbol database is updated

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3072]
Currently, cpptools will update symbol database automatically when you open project files and save files. When saving files, it will cause cpu usage percentage to raise because maybe too many extensions are monitoring 'Ctrl+S' this action. So could you provide some features that can control when the symbol database is updated. For example, I can create the symbol database by clicking a button manually and update it when I want.

**Comment by sean-mcmanus** [comment]
Are you using IntelliSense? We actually update the symbol database after every edit and not after saving when IntelliSense is used. Are you using recursive includes? Does the problem go away if you disable recursive includes? With recursive includes enabled, doing a save will trigger a parse to check for new #includes added, because it can affect which recursive include paths we use. Ctrl+S can also trigger an IntelliSense process parse to occur which could be what is taking a long time as well.

What process is using the CPU? Can you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see what messages appear after the saving occurs (and what message appears after the expensive processing is finished) to try to determine what operation is slow?

I'm not sure what the comment "too many extensions are monitoring Ctrl+S" is supposed to mean.
