### ISSUE TITLE
Add a way to edit/disable snippets.

### ISSUE THREAD

**Issue by Stypox** [microsoft/vscode-cpptools#3083]
Since commit c727ceca1b7d70868b34cbac124315f83cb247e5 snippets can't be neither edited nor disabled.
I use my personal snippets for C/C++, because I don't like the style used in the extension's snippets, so I disabled them using the ``C_Cpp.ToggleSnippets`` command.

I know snippets suggestion have recently been moved from ``cpp_snippets.json`` to the lexer (hardcoded) (see #2942 and #2945). I suggest that you put them in a configuration json file, where they can be edited/disabled (but NOT added, for that vscode has its own file). The lexer could then parse that file and do context-aware suggestions as it did before.

**Comment by sean-mcmanus** [comment]
Snippets can be disabled via the editor.snippetSuggestions to "none", but that would apply to all snippets (not what you want).

Yeah, it seems like we should add a setting to enable configuration of the snippet source, e.g. C_Cpp.snippetsSource "Disabled", "LanguageServer", "Custom", and a C_Cpp.customSnippetsPath to the cpp_snippets.json users want to use.

At the very least, we need a disable option so that users can get snippets via installing a different VS Code snippets provider.

**Comment by Rietty** [comment]
Just cause I can't seem to find the info anywhere else, what's the release cycle for new updates generally? 6 weeks? Or are the iterations shorter? Just curious when I can expect this and future changes in.

**Comment by sean-mcmanus** [comment]
@Rietty We plan to release this fix in an Insiders this week. The non-Insiders might not be till March (i.e. 6 weeks from the previous release). You can check https://github.com/Microsoft/vscode-cpptools/releases for our previous update schedules.

**Comment by Rietty** [comment]
@sean-mcmanus Thanks for the reply. Good to know. Might switch to Insiders just for this then.

**Comment by sean-mcmanus** [comment]
We added a "C_Cpp.suggestSnippets" that you can set to false with 0.22.0-insiders. You can get it via setting the C_Cpp.updateChannel setting to "Insiders", or downloading it manually from https://github.com/Microsoft/vscode-cpptools/releases .

Is that sufficient? It should enable you to use another snippet provider to paste in the old snippet file we used to use.

**Comment by Stypox** [comment]
Yes, that will do for me, thanks :-)
