### ISSUE TITLE
Completion overwrites text to the right of the cursor

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3098]
Have some code like:
```
int var1 = -1;
int var2 = std::a|var1; // Try to complete with the abs function.
```
Typing : triggers completion, and a completion character is entered at | and the result is std::abs or std::abs() with the "var1" part on the right deleted.

I fixed this last week, but Bob was saying this was "by design" -- does anyone else not like this? Maybe we could add a setting to enable this to be configured? I think Visual Studio has some smarter processing that sometimes doesn't replace the contents on the right, but sometimes it does.

**Comment by graphitemaster** [comment]
Yeah I don't like this. Ironically this issue wasn't actually happening for me until I updated today to insiders 3. The previous version I was using didn't have this problem. The way this is worded suggests it was always this way? Can we get an option for this. I don't see how this is "by design". There's nothing intuitive or useful about it.
