### ISSUE TITLE
Go to definition failed if included wrong head files

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3107]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:  1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

Code as below:

**classTest.h**
class CLassA {
public:
    CLassA(){}
    int WorkSecondsElapsed;
    int test(){return 0;} 
};

**classTest.c**
#include <stdio.h>
#include "classTest_XXXX.h"      //wrong head file

#define foo
int testd1()
{
    int mm = 0;
    int n = mm + 1;
    CLassA *pCA = new CLassA();
    pCA->WorkSecondsElapsed = 1;
}

go to pCA or mm definition and can't find its definition.

**Comment by sean-mcmanus** [comment]
This is currently "by design". You can change it via setting the intelliSenseEngineFallback setting to "Disabled"...we're planning to change the default setting to Disabled in a future release. Although, it's possible if the header has types that are required to parse, then Go to Def might still fail. Let us know if you're still seeing problems.

**Comment by Lennon925** [comment]
> This is currently "by design". You can change it via setting the intelliSenseEngineFallback setting to "Disabled"...we're planning to change the default setting to Disabled in a future release. Although, it's possible if the header has types that are required to parse, then Go to Def might still fail. Let us know if you're still seeing problems.

Thanks for your reply. After setting intelliSenseEngineFallback to disabled, it's ok.
