### ISSUE TITLE
Change C_Cpp.workspaceSymbols "Just My Code" to work for non-system directories outside the current workspace

### ISSUE THREAD

**Issue by fredijude** [microsoft/vscode-cpptools#3149]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Window 10
- VS Code Version: 1.31.0 or before
- C/C++ Extension Version: 0.21.0

- Open a c++ workspace with multiple folder paths and no files being opened at the beginning.  The "Go to Symbol in Workspace" doesn't work. Once when you open a cpp file in a folder path of the workspace, then the it works for that folder path. This is stopping us to move ahead to move to VS Code as a IDE for a commercial product.

**Comment by sean-mcmanus** [comment]
This is because our extension doesn't activate until a C/C++ file is open or a C/C++ command is used unless a .vscode/c_cpp_properties.json exists. The reason is because we don't want our extension wasting CPU for non-C++ projects users open. Is creating the .vscode/c_cpp_properties.json a sufficient workaround or did you have some other solution in mind?

**Comment by fredijude** [comment]
Apologies. Let me explain the problem a little more in detail.

Assume
- A workspace "WS"
- WS containing two folders under it - "FolderA" and "FolderB"
- Both the folders have 'c_cpp_properties.json' settings file under respective .vscode.
- FolderA has definitions of ClassA
- FolderB has definitions of ClassB
- Open the workspace WS

Problem Statement
- open "Go to Symbol in Workspace"
- search for "ClassA" definitions, it comes up very well and fine
- search for "ClassB" definitions, it doesn't show up at all. This is the problem.

**Comment by sean-mcmanus** [comment]
Oh, yeah, that's the multi-root workspace scenario, so our extension is activated but there is 1 language server process per folder with its own settings, so if you want to find symbols in FolderA from FolderB then you need to modify either the includePath or browse.path setting (in the c_cpp_properties.json or C_Cpp.default.* in settings.json). The default is "${workspaceFolder}" which only applies to the one folder. Let us know if you still need help configuring or if you think you've hit a bug.

**Comment by sean-mcmanus** [comment]
You can use `${workspaceFolder:FolderName}` in the settings to refer to the other folders (https://github.com/Microsoft/vscode-cpptools/issues/1774 ).

**Comment by fredijude** [comment]
@sean-mcmanus : I have around 25 folders in my multi root workspace. Is it possible to set the include path to all folders that is there in the workspace in a easy way. 

Also, I am not able to configure the above requirement too. I have tried includepath as well as browse.path settings.

**Comment by sean-mcmanus** [comment]
You mean you have 25 workspace folders? That would potentially cause 25 language server processes to be running and using CPU, which is not a scenario we have optimized for yet.

You can set the "C_Cpp.default.includePath" or "C_Cpp.default.browse.path" in your workspace folder settings and then the folders should use that by default, or if folders have additional includes you can use "${default}" to refer to the defaults.

What do you mean by "I am not able to configure the above requirements"? Do you mean Go to Symbol still isn't working?

**Comment by fredijude** [comment]
@sean-mcmanus : Yes i do have 25 workspace folder as my project itself consists of around 5k files and the codebase is pretty large enough.

Yes, the Go to Symbol still isn't working after the configuration.

**Comment by sean-mcmanus** [comment]
You also need to set limitSymbolsToIncludedHeaders to false.
```
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "${workspaceFolder:OtherFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
```

That causes the file in the other workspace to be parsed, but I'm still seeing a bug where Go to Symbol in Workspace is not returning symbols from other workspaces.

**Comment by sean-mcmanus** [comment]
I got it to work -- you need to change the setting "C_Cpp.workspaceSymbols": "All". I forgot that we recently added that. Then you need to make sure the symbol gets parsed (i.e. the database icon in the bottom right might need to finish or at least parse the file you want symbols for).

FYI, our pending builds have fixed some performance issues you may encounter due to symbol requests not being cancelable.

Let us know if you're still experiencing issues. Symbol search hasn't been fully optimized, so text search might be faster. And symbol search doesn't find uses of the symbols, which should get fixed via Find All References when we add that.

**Comment by bobbrow** [comment]
Be very careful about setting `"limitSymbolsToIncludedHeaders": false`.  It will cause the extension to parse all of the standard library (even the parts you don't use).  You don't want to do this 25 times.

**Comment by fredijude** [comment]
@sean-mcmanus : It works good but the problem now is, all the standard libraries also are appearing in the go to symbol search which i don't want to. Is there a way ?
Or Is there an option to show my workspace symbols first and then the symbols outside ?

**Comment by sean-mcmanus** [comment]
Yeah, the intention of the "C_Cpp.workspaceSymbols" setting was to remove the standard library symbols, but it's currently treating everything not under the workspace root as "not my code". We need some additional checks to differentiate a path as being user versus system or at least another workspace folder versus a non-workspace folder. Should I open a new issue to track this or change this issue into that?

**Comment by fredijude** [comment]
@sean-mcmanus : Sure, i can see that this ID has been used to track the defect :). Any estimate on when this will be picked up ?

**Comment by sean-mcmanus** [comment]
I don't know an ETA yet, but it probably won't be in the next 2 weeks because we're busy with other configuration work. @bobbrow added the setting -- I'm still waiting to hear what his thoughts were.

One idea is that we could send all the other workspace folders to the language server, like we currently do for the single root (which we use to check the "Just My Code") -- that change could be implemented in our open source if anyone wants to, then we would just do the same check over all the workspace folders in our language server process.

**Comment by bobbrow** [comment]
We could add a third option that includes code outside the workspace folder but excludes stuff from the system include path (now that we have a way to differentiate).  Or we may want to change our definition of "external" code to only include stuff in the system include path.

The complication here is for cases where external code is installed under a system include path. For example, how do we differentiate between `/usr/include/c++` (system includes) and `/usr/include/libpng`  (external library) when `/usr/include` is listed as part of the system include path?

**Comment by sean-mcmanus** [comment]
@fredijude Adding the paths to the standard libraries that you want to exclude to the "search.exclude" setting should remove those from the "Go to Symbol" results. Let us know if you have any problems with that workaround.

**Comment by fredijude** [comment]
@sean-mcmanus, it's not good to do such as project is worked by a team and it just could not be expected to be set up differently based on the SDK installation of each system of a team member.
