### ISSUE TITLE
exceptions in debug mode

### ISSUE THREAD

**Issue by reszes98** [microsoft/vscode-cpptools#3163]
Type: Debugger
**Input information below**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.17763
- VS Code Version:1.13.1.1
- C/C++ Extension Version: 0.21.0
- A clear and concise description of what the bug is.
I have codeblocks, visual studio, and visual studio code, when i'm debugging everytime in testclass.h at testclass2 and ~1 stops because an exception has occurred, but the other 2 ides dont stop, so the code needs to be okay.

**To Reproduce**
i will include all the project, and the .vscode directory
[hetero.zip](https://github.com/Microsoft/vscode-cpptools/files/2861449/hetero.zip)

1. build and debug.
2. see exeptions

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by pieandcakes** [comment]
@roland1998 What compiler/debugger are you using on Windows when this happens? What are the versions of the toolset? What exceptions are you seeing? 

From the looks of your project, you are using MinGW and my assumption is that you don't have the `bin` folder of the toolset in your path, so that when the program is launched it can't find it. This is a configuration issue related to your toolset and not an issue with the extension.

**Comment by reszes98** [comment]
@pieandcakes That's right i'm using mingw, thanks, i will try it.
![image](https://user-images.githubusercontent.com/1857244/53078758-39a11280-34f5-11e9-9ad6-0e7204a7ee60.png)

**Comment by pieandcakes** [comment]
Please comment/reopen if that doesn't get it working for you with specific steps. Thanks
