### ISSUE TITLE
Mixed tabs and spaces when editing C code, when a 'settings.jason' for the workspace is set

### ISSUE THREAD

**Issue by eliahonader** [microsoft/vscode-cpptools#32]
the settings.jason content is the following:
// Place your settings in this file to overwrite default and user settings.
{
    // The number of spaces a tab is equal to.
    "editor.tabSize": 3
}

when i open my C project (not a C++), then the tabSize is ignored. 
VSCode indicates that tab size is '6'. I have to manually change the tab size to the 'configured tab size'.

**Comment by delmyers** [comment]
@sridmad, is this an issue with the language service, or is it a vscode editor issue?

**Comment by sridmad** [comment]
This does not involve the C++ extension and seems to be VSCode issue

**Comment by eliahonader** [comment]
thank you for your reply :)

**Comment by sean-mcmanus** [comment]
If you think this is a bug, I need more exact repro details, because I don't see any bug (and if it repros without our extension then it's not our bug). VSCode will detect the tab settings of an existing document and use that instead of the settings file. If you have mixed tabs/spaces, you can run Format Code with the desired IndentWidth, TabWidth, and UseTab settings.
