### ISSUE TITLE
Why aren't issues closed when feature is finished?

### ISSUE THREAD

**Issue by Trevinlc1997** [microsoft/vscode-cpptools#3211]
This isn't related to cpptools per se but instead of the "fixed (release pending)". Couldn't you just close the issue all together to represent you are finished working on it, etc? I believe Visual Studio Code does it, but don't quote me on that lol. Just curious is all.

**Comment by bobbrow** [comment]
We could close it, but then the issue wouldn't show up in issue searches by default.  We follow a similar process as the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).  When we complete work on an issue we mark it as "fixed (release pending)" and then close it when the release goes public.

**Comment by sean-mcmanus** [comment]
We currently have 3 states:
1. Fixed with a non-released branch. (marked "Fixed (release pending)").
2. Fixed with the shipped Insiders. (also marked "Fixed (release pending)", but usually with a comment stating that the Insiders has the fix).
3. Fixed with the non-Insiders. Closed.

One advantage of "Closing" issues that have internally been fixed is that it allows the Milestone to show an accurate progress (e.g. 50% fixed), which is what VS Code does.

I don't really care either way if the issues are open or closed.
