### ISSUE TITLE
No peek definition and Go to definition available

### ISSUE THREAD

**Issue by icarus31** [microsoft/vscode-cpptools#322]
OS: openSuse 13.1
VS Code: 1.6.1 32 bits (rpm)

When opening a directory containing .c and .cpp files and right clicking on a function, there is not "Go to definition" and "Peek definition".

I tried a simple project with 2 .cpp files on Win10, Win7 and openSuse 13.1. The first one has the menus, but not the two other ones.

What am I doing wrong?

Missing components?

Thanks

**Comment by greazer** [comment]
Hi Icarus, I don't think you're missing components, you may just be running into a combination of expected behavior and possibly a bug.

You're saying you're running on 32-bit flavors of Win10, Win7 and openSuse.  Correct? 

Unfortunately, our extension does not currently support 32-bit Linux distros. As for Win7 32bit, it should work. I was able to create a folder with a cpp and h file. The features the extensions provide were working correctly.

**Comment by bobbrow** [comment]
We're tracking 32-bit Linux support with issue #424

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4, although from your description I'm not 100% sure.
