### ISSUE TITLE
Auto complete doesn't work in case of struct member type is under compilation flag

### ISSUE THREAD

**Issue by idanemergi** [microsoft/vscode-cpptools#3252]
**Type: LanguageService**

I'm working with the entire Linux kernel in my workspace and a lot of kernel structures and types defined
under compilation flags.
So when I use such structure or type, autocomplete doesn't work properly.
for example:
struct my_struct {
    struct list_head list;
    int num;
};

void foo(void)
{
    struct my_struct s;
    s. // here, autocomplete only shows num, ctrl+space doesn't help either.
} 

**Describe the bug**
- OS and Version: Ubuntu 14.04.5 LTS
- VS Code Version: 1.24.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense, issue persists.
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

Expect that autocomplete will ignore compilation flags.
**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
You need to set the compilation flags in the "defines" setting. Can you do that? Otherwise, our parser thinks list_head is undefined, causing it to break.

**Comment by idanemergi** [comment]
> You need to set the compilation flags in the "defines" setting. Can you do that? Otherwise, our parser thinks list_head is undefined, causing it to break.

I can, but the kernel has more than 1000....
it is not only that, it seems that he also consider the includes the file have.
Is there a way to disabling this behavior and ignore include files and compilation flags?
I'm not compiling the kernel via the vscode so I don't need it.
I just want to navigate quickly through the code.

**Comment by idanemergi** [comment]
Maybe I'll asked it differently.
I have a few repositories which 1 of them is the kernel.
the directory structure:
root
  -> kernel
  -> repo1
  -> repo2

repo1 and repo 2 uses the kernel APIs and definitions.
what is the correct way to create the workspace or project so vscode will not have undefined types like struct list_head, u32, u64 and many more?
cause if I'm adding only the root folder to my workspace, I get a lot of errors for undefined types.

**Comment by sean-mcmanus** [comment]
You can change the C_Cpp.intelliSenseEngine setting to "Tag Parser" so that defines and includePath aren't required, but the results won't be ideal (it will ignore the defines and includePath and just try to parse the global symbols). The "Default" intelliSenseEngine actually needs to be able to compile the code to give results.

Opening the root folder seems correct to me, but in order to get the types defined, you would need to locate where the files with the definitions are located and then add the correct path to the includePath and then make sure the defines are set correctly for that definition to be compiled.

**Comment by ghost** [comment]
Hi @idanemergi ,

I also facing the same issue with sth similar to Linux kernel config define flags.
My solution is to have a python script to parse kconfig then to append into c_cpp_properties.json.

If you are interested, I have attached my scripts and result here.
[kernel-config-vscode.tar.gz](https://github.com/Microsoft/vscode-cpptools/files/2964604/kernel-config-vscode.tar.gz)

**Comment by idanemergi** [comment]
> Hi @idanemergi ,
> 
> I also facing the same issue with sth similar to Linux kernel config define flags.
> My solution is to have a python script to parse kconfig then to append into c_cpp_properties.json.
> 
> If you are interested, I have attached my scripts and result here.
> [kernel-config-vscode.tar.gz](https://github.com/Microsoft/vscode-cpptools/files/2964604/kernel-config-vscode.tar.gz)

Thanks a lot, will try and update.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and there maybe a possible solution according to the last comment. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
