### ISSUE TITLE
.browse.VC.db is recreated every time with large projects such as chromium.

### ISSUE THREAD

**Issue by myrfy001** [microsoft/vscode-cpptools#326]
.browse.VC.db is is recreated every time when i use it to debug chromium project. The project can be pull from www.chromium.org and the whole project including git repo is about 20GB. The .browse.VC.db created by cpptools plugin can be about 1.7GB and it will be created everytime the workspace is opened. I work on a SSD and it will take me about five minutes before it finish.

The cpp-tools version is 0.92 , the VS Code version is 1.6.1 and work on Ubuntu 14.04 64-bit

**Comment by myrfy001** [comment]
Has any progress has been made for this problem?

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem as described. What do you mean by "recreated"? Is the file deleted and being regenerated? 5 minutes of "rescanning" on folder open sounds like normal behavior given the size of the project.

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension.  There is also a new `"C_Cpp.addWorkspaceRootToIncludePath": true` setting you can add to your settings.json to disable automatic parsing of the entire chromium project.  You can then specify which folders you want included in the browse DB using the `includePath` setting in c_cpp_properties.json.
