### ISSUE TITLE
About breakpoint

### ISSUE THREAD

**Issue by void-mian** [microsoft/vscode-cpptools#3268]
Issue Type: <b>Bug</b>

when there is two files have a same name,it can't Distinguish between each other.
the struct of flooders:
1
├── .vscode
├── floder1
│.       .└── A.cpp
└── floder2
 .           .└── A.cpp
the breakpoint in /floder1/A.cpp is at line a
the breakpoint in /floder2/A.cpp is at line b
and a>b

when I debug the file in floder1  it just goes to line b

Extension version: 0.21.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by WardenGnaw** [comment]
Could your share your [engine logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging)?

**Comment by void-mian** [comment]
Did that means a folder called "ipch"? And how can I send it to you?In this page?
Also, do you able to repro the problem?

**Comment by sean-mcmanus** [comment]
The ipch folder is unrelated to debugging (it's the IntelliSense cache folder).

**Comment by Lupum1001** [comment]
@WardenGnaw I just had the same problem with multiple main.cpp files in my project. It looks like the problem is that the extension isn't providing a path (relative or absolute) to the file.
So if I add a breakpoint in vscode, the engine output is:

> 1: (785) ->(gdb)
> 1: (785) 1022: elapsed time 0
> 1: (785) Send Event AD7BreakpointBoundEvent
> 1: (786) <-1023-break-insert -f main.cpp:53
> 1: (786) ->1023^done,bkpt={number="5",type="breakpoint",disp="keep",enabled="y",addr="0x00000000004218a1",func="SCT::run(int, char const**)",file="/home/user1/projectRoot/Common/Repositories/core_components_sct/SCT/src/SCT/main.cpp",fullname="/home/user1/projectRoot/Common/Repositories/core_components_sct/SCT/src/SCT/main.cpp",line="53",thread-groups=["i1"],times="0",original-location="main.cpp:53"}

Unfortunately, the main.cpp file that I added breakpoints to was actually:

> /home/user1/projectRoot/MyApp/AppControl/src/InitTask/main.cpp

I listed all the breakpoints using the debug console once the application was running, and gdb had created all of the breakpoints (from both main.cpp files) in that one main.cpp file.

**vscode version:** 1.37.1
**extension version:** 0.25.1
**Platform:** VS-Code running in Windows 10, using the "Remote Development" extension pack to compile/run everything on an Ubuntu V.M. (The extension is running in Ubuntu)

**Comment by WardenGnaw** [comment]
In v1.1.0, if you use `sourceFileMap` and `useForBreakpoint` it will use the full path to set a breakpoint instead of the file name.
