### ISSUE TITLE
Document error: Mac or Linux OS X

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-cpptools#3292]
In the following page,

https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/How%20To%20Debug%20MIEngine.md

The Install Prerequisites for Linux or Mac OS X are either wrong or out of date or has bad links. The Xamarin Studio v5.10.1.6 points to an msi installer not meant for a Mac? Install GTK link points to https://www.mono-project.com/download/stable/ which is okay I guess. But Xamarin is problematic. It has been deprecated and pointing to the wrong installer anyway.

If there is a better way to debug cpptools+MIEngine on a Mac, please let me know. Docs are wrong regardless I think.

**Comment by WardenGnaw** [comment]
The wording on that page is a bit weird, but it all assumes you are debugging from a Windows machine since you will need to build the Debug bits of MIEngine using Visual Studio. 

If you want to remotely debug MIEngine that is running on a Mac, you will need to install GTK and the MonoDevelop MSI on the Windows machine locally and remote attach to it using MonoDevelop. 

I however would recommend using [VS Code + Mono Extension](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/How%20To%20Debug%20MIEngine.md#with-vs-code--mono-debug)

**Comment by haneefdm** [comment]
Thanks, @WardenGnaw 

Oh, build on Windows with Visual Studio but use "VSCode + Mono Extension" to experiment/debug/test MIEngine locally on the Mac? I get it now. I think :-)
