### ISSUE TITLE
.h file with gcc and C language mode is defining the __cplusplus macro

### ISSUE THREAD

**Issue by hsupu** [microsoft/vscode-cpptools#3308]
**Type: LanguageService**

- OS and Version: Ubuntu 16.04
- VS Code Version: 1.32.1 05f146
- C/C++ Extension Version: 0.21.0

my vscode highlights .h files incorrectly.

I choose the language mode "C" for .h files and `c_cpp_properties.json` `configurations.compilerPath` is `/usr/bin/gcc`. But, `__cplusplus` in .h shows that it's defined as `201500L` and `#if defined(__cplusplus)` blocks are highlighted.

The pure C highlights are needed. Is this defined `__cplusplus` macro a bug in cpptools plugin?

**Comment by sean-mcmanus** [comment]
Our IntelliSense doesn't react to changes of the language mode from C to C++ or the reverse, and we don't use the C++-ness of the compiler to set the language used. Instead, we use the files.associations for the source file and then the header file uses the language of the translation unit (source file).

If you just create a .h file that isn't used by a .c file, then it will be associated with C++ instead of C. We could probably improve that (i.e. use this issue to track that). But in the normal case where the header is included by a .c file then we would use that language. Does the issue get fixed for you once you `#include` the header in a .c file and then doing a Reload Window?

UPDATE: If you see __cplusplus defined, then it means our IntelliSense is parsing the file as C++ and not C.

**Comment by hsupu** [comment]
Yes, .h file is parsed as C after be included in a C file. Thank you for your help.

But I think that it should be more customizable by user. I'll appreciate it if anyone add this feature!

**Comment by bobbrow** [comment]
You should be able to achieve this through the following setting:
```
    "files.associations": {
        "*.h": "c"
    }
```
This will force VS Code to classify all .h files as C files instead of C++ (which is the default).  However, if you include the header file by some other .cpp file, you will still get C++ language features defined.
