### ISSUE TITLE
right click menu: incorrect menu item

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-cpptools#3334]
version:
macOS 10.14.3(OS language Chinese Simplified), VSCode 1.32.3

installed from https://github.com/Microsoft/vscode-cpptools/releases/download/0.22.0/cpptools-osx.vsix

settings:
~/Library/Application Support/Code/User/locale.json
```
{
	// Defines VS Code's display language.
	// See https://go.microsoft.com/fwlink/?LinkId=761051 for a list of supported languages.
	
	"locale":"en" // Changes will not take effect until VS Code has been restarted.
}
```
Here is right click menu in c/cpp files:
<img width="314" alt="1" src="https://user-images.githubusercontent.com/11925432/54739092-c244c880-4bf1-11e9-95cf-bcc3bfc22658.png">

Now I have Chinese menu items and English menu items, but the setting in locale.json is en.

Here is right click menu in js files:
<img width="372" alt="2" src="https://user-images.githubusercontent.com/11925432/54739544-84e13a80-4bf3-11e9-8ecc-ed777a2ca31f.png">

**Comment by sean-mcmanus** [comment]
This appears to be VS Code bug https://github.com/Microsoft/vscode/issues/62623 . It should be fixed in the latest Insiders (or the pending March VS Code update).

It sounds like installing the Simplified Chinese language pack extension for VS Code might fix the issue as well, but I haven't verified that.
