### ISSUE TITLE
intelliSenseMode setting not working?

### ISSUE THREAD

**Issue by elegracer** [microsoft/vscode-cpptools#3345]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Mojave 10.14.3
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them): CMake, CMake-Tools

**To Reproduce**

1. Install gcc using homebrew, `brew install gcc`
2. Remember to `brew link gcc`
3. Ever use gcc for intellisense (e.g. use gcc for cmake kit)
4. Switch back to apple clang, and force intelliSenseMode to "clang-x64"

**Expected behavior**

The IntelliSense should be using clang, but from the debug logging, `/usr/local/Cellar/gcc...` is still used, and intelliSenseMode is gcc.

**Screenshots**

None

**Additional context**

Interestingly, when I `brew unlink gcc`, and remove the kit as the prompt showed up, and force the intelliSenseMode to clang-x64, and clean and reload, the log shows that clang is used now.

I guess whether the application of this setting could run into trouble? BTW the flame is almost always on the bottom right, and autosuggestions are too slow, even after many times of reinstallation of vscode (I think they were complete uninstallation, or maybe you could tell me how to do it, which would be appreciated).

**Comment by sean-mcmanus** [comment]
Changing the intelliSenseMode from gcc-x64 to clang-x64 just slightly changes how our parser behaves, but you'll still need to change your compilerPath to change from gcc to clang. It sounds like we're just picking a default compildr that we find due to a missing compilerPath setting.

UPDATE: We plan to add some more squiggles to the c_cpp_properties.json when we detect potential intelliSenseMode and compilerPath issues.

**Comment by elegracer** [comment]
Yeah, I think the inconsistency of intelliSenseMode and compilerPath is the problem here.

**Comment by Colengms** [comment]
This issue appears to have been addressed.  Closing.  Please let us know if there is still an issue here.
