### ISSUE TITLE
.vscode caching too much data since update

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3347]
I have noticed since the recent update that cpptools seems to be caching a lot of data (~1GB for a small project). This seems to be in an ".vscode/ipch" subdirectory.

![download_20190323_132636](https://user-images.githubusercontent.com/7434573/54860824-a36c4080-4d6f-11e9-85d4-82e471896b7a.png)

**Comment by sean-mcmanus** [comment]
That is "by design". You can reduce the size used by changing the intelliSenseCacheSize setting for either the current workspace or all workspace (i.e. the user setting).

**Comment by ghost** [comment]
Was this feature implemented in the most recent update? I feel that this could be a bit dangerous as the vscode directory is hidden. It is a significant amount of data to be generated on a per-project basis for a lightweight editor.

Just an opinion though, I appreciate the quick response.

**Comment by ThadHouse** [comment]
I think the choice of the .vscode folder might have been the wrong folder for this. I know the community is about 50/50 on if you should commit the .vscode folder to source control, and this is causing havoc in our source control setups. Why was the per workspace folders provided by vscode not used? And is there any way in the settings to change to that, as I would much prefer my store location to be there.

**Comment by tehKaiN** [comment]
> I know the community is about 50/50 on if you should commit the .vscode folder to source control

I'm one of those who commit .vscode ;)

Also, I think it would be better to have single cache for whole extension. I'm switching between 10+ large projects and ipch files are more and more consuming my disk space. It could be configurable to save it separately for a given project if one wants to have it that way (e.g. prevent deleting because of other projects hitting global cache size limit in the meantime), but having those files in every project is a) confusing, b) unreasonable for small disks.

**Comment by bobbrow** [comment]
@ThadHouse the VS Code per-workspace folders were not selected for the following reasons:
* Parity with Visual Studio. This is how Visual Studio works and they receive little to no feedback/complaints on the location.
* The workspace storage location provided by VS Code is somewhat obscure and we had reservations about writing GB's worth of files in this location where users may not see them or know where to find them.

With this in mind we knew that we wouldn't be able to please everyone, so we provided settings to allow you to customize this the way that works best for you.  We also figured that putting the files in the workspace folder would bring the issue to your attention quickly so that you can take action if you don't like the default behavior.

#### `"C_Cpp.intelliSenseCachePath": <string>`
This setting allows you to set workspace or global overrides for the cache path.
@tehKaiN, if you want a single cache for the whole extension, you just open the VS Code settings, and add a "User" setting for "IntelliSense Cache Path".

#### `"C_Cpp.intelliSenseCacheSize": <number>`
This setting allows you to set a limit on the amount of caching the extension does.  If you want to use a global cache and increase/decrease the limit, that's fine.  This is an approximation, but the extension will make a best effort to keep the cache size as close to the limit you set as possible.

**Comment by bobbrow** [comment]
Another thing we can potentially take away from this discussion is that perhaps the extension can prompt users to select a default behavior for caching before it begins doing it.  The toast messages can be ineffective since people will just click something or press <kbd>Esc</kbd> to make them go away, but it might address some of the concerns raised here.

**Comment by crazyBaboon** [comment]
Yep, this .vscode/ipch folder is a real pain.

**Comment by bobbrow** [comment]
@crazyBaboon, can you clarify why is it a pain for you? Are you able to use the settings to control the feature the way you want?

**Comment by MemoryChips** [comment]
Why is this a pain in any case? Is there a problem if I just .gitignore it?

Rob

**Comment by bobbrow** [comment]
There is no problem if you .gitignore it. That's what we expect most people to do, but in cases where you want customized behavior, we have provided additional settings which we hope will get you the behavior you want.  If this is insufficient, we'd like to understand how we can make it better.

**Comment by ThadHouse** [comment]
The java extension actually checks that it's plugin used files are in the vscode settings files.exclude list. It might do that with .gitignore too. Maybe that's something to look at doing. Check if that folder is properly ignored, and if not prompt the user to add it.

**Comment by ghost** [comment]
Git is not the only reason why it would be unacceptable to be able to use up to 5GB so liberally. It is not reasonable to assume a "lightweight editor" is going to produce a 1.3 GB precompiled header in a hidden folder just by opening an existing C++ project directory to do a quick edit on a file.

I understand that you have provided options to dial this down but I had to notice that 1/3 of my Google drive space had suddenly disappeared before investigating what was going on. I also have a laptop with a 256 GB SSD, the default 5GB setting is 2% of my total capacity.

Ultimately the thing that bothers me the most about it is that I use vscode because full blown VS is a bloated mammoth. I don't like that every VS project contained hidden folders with hundreds of megabytes of data for a single hello-world source file. This recent update now puts vscode in the same boat and is pushing vscode out of the powerful lightweight editor and more into the full blown IDE spectrum.

This seems excessive just for an intellisense improvement. Is there no other way? Was intellisense really that bad a couple of weeks ago?

I really hope this doesn't come across as being rude, I am just very passionate about vscode. I probably spend most of my day, every single day using it for work and hobbies. The work you guys are doing is amazing, but this has made me a little fearful that vscode may eventually end up half as bloated as it's big brother.

**Comment by bobbrow** [comment]
@unl1ght, I appreciate the candid feedback. If you haven't been experiencing any performance problems with previous versions of the extension, then that's great to hear. If you don't feel you need the caching, you can turn it off with the intelliSenseCacheSize setting (set it to 0).

We've been receiving a lot of feedback in our survey about performance problems with the extension. Aligning with VS in this respect is an attempt to address these reports. We continue to investigate other ways to improve performance too.

**Comment by newbrain** [comment]
Would it be possible to have the `.vscode/ipch` directory automatically added to `.git/info/exclude` when cloning a repository?

Rationale:
* Probably noone is willing to track and and commit them.
* `.gitignore` is IMO not the right place, as these are vscode artifacts (and not everyone is using it).
* I often clone repos to look at code I'm not allowed (or willing) to commit to, and having a number of untracked files showing up is mildly annoying.
* Since I have quite sane user defaults for this kind of projects, those are, in fact, the only things created in the `.vscode` directory.

Of course, doing it manually is not a big deal...

**Comment by sean-mcmanus** [comment]
We had the same sort of complaints when we originally placed our .browse.vc.db file in the .vscode folder (databaseFilename setting). We're considering changing the default intelliSesneCachePath setting to the workspace storage location (where our symbol database defaults to -- the "con" being it's harder to locate delete there) or the temp directory (where our pipe files are generated, the "con" being it might get deleted unintentionally).

**Comment by kckemper** [comment]
I work in a very resource limited embedded system and usually I edit the code directly on the little device by mounting it with my desktop over sshfs.  Before the update everything was fine but now the local ipch folder frequently grows large enough to consume the whole memory of my embedded system (~100 MB) and setting the "C_Cpp.intelliSenseCachePath" doesn't seem to default to the user setting when the workspace is recreated (which is frequently). I just wanted to point out a specific reason not to default the cache in the local working directory. After a while of deleting the ipch directory frequently I finally came here to figure out what the heck that directory was.

**Comment by sean-mcmanus** [comment]
@kckemper intelliSenseCachePath as a user setting is supposed to work, unless it uses an environment variable (it's a bug fix that we haven't shipped yet). Can you provide more info about that path you are using?

**Comment by kckemper** [comment]
"C_Cpp: Intelli Sense Cache Path"  is  "~/.vscode"

**Comment by sean-mcmanus** [comment]
@kckemper Yes, that is the bug we fixed (https://github.com/Microsoft/vscode-cpptools/pull/3368 ). We plan to ship a fix for that next week.

**Comment by crazyBaboon** [comment]
> @crazyBaboon, can you clarify why is it a pain for you? Are you able to use the settings to control the feature the way you want?

It should do the cache outside the git folder IMO, like in the .config or something like that.

**Comment by kckemper** [comment]
> @kckemper Yes, that is the bug we fixed (#3368 ). We plan to ship a fix for that next week.

Great! That'll help.

**Comment by sean-mcmanus** [comment]
@kckemper The latest extension Insiders has fixed the `~/.vscode` bug with the intelliSenseCachePath: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.22.2-insiders .

**Comment by RafaelQuirino** [comment]
Well, commiting .vscode is not the only issue here. You see, i save my documents, workspace etc., in the cloud, in services like MEGA. When this .vscode grows to GB it takes away my quota in these services. So yes, IT IS a pain. I understand you justifying/defending the feature, but to say it is not a pain, like if you have analysed all possible scenarios, is "a little arrogant", to say the least. And even if this was not the case, the feature is creating files that can be several orders of magnitude bigger than the files in the project. This can not be right...

**Comment by sean-mcmanus** [comment]
@RafaelQuirino You can change your intelliSenseCachePath setting though so it's not taking up quota in cloud services, right?

**Comment by mday64** [comment]
VSCode's default for the cache path works fine for me.  The only issue was not knowing what stuff was in there, and whether to commit it to source control.  (I have since added ".vscode/ipch" to my .gitignore file, and deleted files that were committed before I knew what they were.  That works for me.)

How about creating a ReadMe file inside .vscode/ipch to explain what's being stored there, that it's OK not to commit it to source control, and what settings you can change to modify the location and size of the cache?

**Comment by pedro-w** [comment]
Another case: I have source code in a directory on Dropbox, purely for reference, not for editing/development. Now I discover that these ipch files have been synched to everyone in the company, with little or no benefit to them.

**Comment by sean-mcmanus** [comment]
@pedro-w Can you change your intelliSenseCachePath to a different location and/or delete those files from Dropbox?

**Comment by pedro-w** [comment]
@sean-mcmanus Yes I can, and I've done both those things now, thanks. 
I just wanted to make the point that it's not purely a problem for source control users, so modifying .gitignore is not a solution for everyone.

**Comment by JavierReyes945** [comment]
Any reason why the discussion is not about having the "C_Cpp.intelliSenseCacheSize": 0 as default, and then the user can decide whether he wants to use the Intellisense and how? VScode is supposed to be a text editor that can have expanded functionality, not an almost-IDE that can be turned into a text-editor by changing the settings back to zero after checking the issue in github and finding what exactly is that ipch folder that the extension creates automatically by simply having a file opened.

**Comment by Lennon925** [comment]
Could you use the same folder path to storage cpptools database and ipch file?

such as :
User\workspaceStorage\461a22b28b7917e54e4c47c056e86663\ms-vscode.cpptools
User\workspaceStorage\461a22b28b7917e54e4c47c056e86663\ipch

If I can set workspaceStorage path, it will be better.

**Comment by bobbrow** [comment]
Copying comment from #3664 here for all followers of this issue to see:

<h3>Proposed changes to default path of IntelliSense cache path</h3>

We propose using the user directory as the new default IntelliSense cache path (see proposed new default path below). The proposed solution will, by default, reduce the disk space usage and alleviate implications on source control for users who have not configured the cache. 

As part of this proposed change, the extension will also automatically remove any caches previously added to the `${workspaceFolder}/.vscode` folder when the old default behavior was applied.


**Disk Space**
By using the user directory as the default path, it will create one cache location per user for the extension instead of creating a cache per workspace. As the cache size limit is applied to a cache location, having one cache location will also reduce the disk space usage of the cache for everyone using the default setting value. 


**Source Control**
Moving away from the workspace folder to the user directory as the default path will also address the concerns of the cache implications on source control for the workspace folder for everyone using the default path.

**New default path**
The new default path for `C_Cpp.intelliSenseCachePath` setting will be the following:

On Windows
`%USERPROFILE%/.cpptools`

On Linux and Mac
`~/.cpptools`

<h3>Please provide us with your feedback on this proposal.</h3>

**Comment by newbrain** [comment]
Would it be possible to use an already existing, Code related, path?
On Windows, the path for most of the settings and some cached data is `%APPDATA%/Code` and would be a better choice (saving stuff directly in `%USERPROFILE%` is not IMHO very Windows-like).
For Linux (and I suppose Mac) we already have the `.config/Code` and `.vscode` directories.

**Comment by bobbrow** [comment]
Our extension doesn't own the `%APPDATA%/Code` folder so it wouldn't be right for us to dump stuff in there.

Our choice for the user folder was motivated by discoverability and the trend of cross platform tools increasingly putting configuration and cached stuff in this location.  (e.g. Android Studio, Cocos Creator, Atom, Gradle, and Conan - just to name a few).  But we could also consider putting the folder under AppData instead.  If we did it this way, we would propose putting it in `%LocalAppData%` instead because these are files you don't need to have following you around across machines.

Does anyone else following this issue have an opinion on this?

**Comment by mday64** [comment]
(I mentioned this in #3664, too.)  How about you create a `cpptools` directory inside the `~/.vscode directory` (the one where your installed extensions go)?  That keeps the VSCode-related stuff together.  Sorry, I don't know what that would look like on Windows.

**Comment by pedro-w** [comment]
I would say that it's better to follow the platform-specific guidelines (see for example [what Chrome does](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md)) but doing what other VSCode extensions are doing is also a precedent for you. Tricky. At least it might be sensible to use a more specific directory name ( `.vscode.cpptools` ?) as your suggestion might not be obvious what it is.

**Comment by bobbrow** [comment]
Combining suggestions from this thread with the other one, how does this sound?

#### Windows
`%LocalAppData%\vscode-cpptools`

#### Linux/macOS
`~/.vscode-cpptools`

**Comment by michelleangela** [comment]
The other default path option for **Windows** can be `%LocalAppData%\Microsoft\vscode-cpptools` to further indicate that this folder and its contents is from a Microsoft component.

We would like to hear your feedback on any preference.

**Comment by KRMisha** [comment]
May I suggest that on Linux, the ipch folder be put under `~/.cache/vscode-cpptools`? (Or equivalently, `$XDG_CACHE_HOME/vscode-cpptools`.) That way, the cached files do not appear as configuration dotfiles in the user's home directory, reducing clutter and making their purpose more obvious, and can also be easily excluded when backing up or synchronizing files, for instance. This is more in line with the conventions followed by other programs when caching user-specific files on Linux.

**Comment by natet** [comment]
I for one would like a setting or command that would clear this cache from within VSCode (similar to the clean solution in Visual Studio). I'm an educator that frequently zips up my directories to post as examples for my students to look over. When this change was made I suddenly started getting zips that were too large to post to our LMS.

**Comment by bobbrow** [comment]
@natet, the setting that controls the cache size is `C_Cpp.intelliSenseCacheSize`.  Set this to 0 and the extension will delete the cache.  Starting in 0.24.0-insiders, we also changed the default cache location to be outside of your workspace folders, so you probably won't even need to do that anymore.

**Comment by natet** [comment]
@bobbrow I guess I wasn't clear in what I was asking. I don't want the cache to be eliminated, I simply want the ability to clear it at some point prior to preparing the zip file. But, if it's being stored outside the workspace, I guess that solves my problem.

**Comment by hb9tst** [comment]
Joining this discussion a bit late... I appreciate that there is a proposal to change this behaviour. I think that `%LOCALAPPDATA%` is the right choice on Windows, whereas `%USERPROFILE%` is NOT (I don't know why many programs write data there, it's not supposed to be used that way). For Linux, I'd strongly support using `$XDG_CACHE_HOME`, as for example here we have a setup with home directories on NFS (with disk quotas—it's a setup used by University students) and we regularly have issues with ipch folders causing users to exceed their disk quotas (`$XDG_CACHE_HOME` is set to use the local hard drive). I don't know what the best practice on MacOS would be.

As to whether put it in a `Microsoft` folder under `%LOCALAPPDATA%`, I don't have a preference. Maybe it could be a `VSCode` folder in `%LOCALAPPDATA`, that all VS Code components writing cache data should use...

And just to give another reason why I find that solving this issue is important: yesterday I double-clicked a .cpp file I wanted to edit (having .cpp files associated with VS Code), while I was using VS Code to edit a web site (therefore the root of the site was open as workspace). I later noticed a very big .vscode folder on the root of the web site! I'd call this behaviour "user data pollution"...

We also had students compressing their project folders, and handing in ZIP files for assignments what ere several dozens of MB instead of a few kB...

**Comment by pedro-w** [comment]
> I don't know what the best practice on MacOS would be.

I believe you would ideally use [URLsForDirectory:inDomain](https://developer.apple.com/documentation/foundation/nsfilemanager/1407726-urlsfordirectory) with [NSCachesDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nscachesdirectory?language=objc) and [NSUserDomainMask](https://developer.apple.com/documentation/foundation/nssearchpathdomainmask/nsuserdomainmask?language=objc) but it might be possible to just use `$HOME/Library/Caches`. In either case, append the VS Code bundle identifier as a subdirectory name.

**Comment by sean-mcmanus** [comment]
@hb9tst I created a new issue to track the $XDG_CACHE_HOME at https://github.com/microsoft/vscode-cpptools/issues/3860

**Comment by kylrth** [comment]
I appreciate how well the maintainers handled this issue. There were a lot of people frustrated about this, but you managed to find a solution that took a good middle ground. Thanks!

**Comment by cloudhan** [comment]
For now, I just simply move the directory to a large drive and symlink it.

**Comment by tomatac** [comment]
What about changing the default maximum cash to a reasonable amount: 100 MB and inform the user if more space is needed? What about purging some of the old cashed data?

**Comment by hb9tst** [comment]
I think that simply respecting the standard locations for cache data in each supported OS is the way to go. I say that as a sysadmin (although I'm also a developer using VS Code), because I have a lot of problems with students getting over disk quota in their homes due to VS Code cached data. Of course, they aren't aware at all of it. They are not professional developers, nor they have an in-depth knowledge of the problem. So if VS Code would ask them "can I put more data?" they would probably just click OK.

**Comment by sean-mcmanus** [comment]
@hb9tst We've already switched to using a shared location for the IntelliSense cache data at "standard locations". Is there still an issue with our caching behavior?

**Comment by lostmsu** [comment]
Can I safely remove subfolders of `vscode-cpptools\ipch`? Or should I do it by limiting the cache size?

**Comment by sean-mcmanus** [comment]
@lostmsu Ideally you should set your intelliSenseCacheSize to 0, which should cause it to be removed. If you try to remove it manually, that is "safe", but it might be in-use by a cpptools-srv process, and/or a cpptools-srv process might just recreate it.

**Comment by lostmsu** [comment]
@sean-mcmanus I am talking about individual folders, not the entire cache dir.

**Comment by sean-mcmanus** [comment]
Yeah, you can safely remove subfolders. If the cache is in use and you can't delete it, you can close VS Code and then delete the subfolders. A missing cache will just cause it to be regenerated again if it's needed later.
