### ISSUE TITLE
A wrong warning with "Path is not a directory" when "compilerPath" is used

### ISSUE THREAD

**Issue by ivankravets** [microsoft/vscode-cpptools#3383]
Type: General
**Describe the bug**
- OS and Version: macOS
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

Original: https://community.platformio.org/t/include-warnings/7188

```json
{
    "configurations": [
        {
            "name": "Mac",
            "macFrameworkPath": [],
            "includePath": ["..."],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/.vscode/.browse.c_cpp.db",
                "path": [""]
            },
            "defines": [
                "PLATFORMIO=40000",
                "..."
            ],
            "intelliSenseMode": "clang-x64",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "/Users/ikravets/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc -mlongcalls"
        }
    ],
    "version": 4
}
```

When a `compilerPath` option is used, extension treats it as a folder. As a result, warns about invalid PATH. 

**Expected behavior**

I don't know what to say here. A path to "binary" is not a "directory" :)

**Screenshots**

![Screen Shot 2019-03-29 at 20 58 41](https://user-images.githubusercontent.com/1760209/55256313-7636fb00-5265-11e9-8401-7d1ced033b99.png)

**Comment by sean-mcmanus** [comment]
I'm having problems reproing this (i.e. it's not a bug that repros in general). I'll try to get a repro using PlatformIO.

**Comment by sean-mcmanus** [comment]
I'm using the exact same compilerPath as shown in the screenshot but I don't get any squiggles (on Mac).

**Comment by sean-mcmanus** [comment]
I reproed the bug, after removing the 2nd workspace folder (we have a different bug that causes squiggles to not appear in that case).

**Comment by sean-mcmanus** [comment]
I tried our unpublished 0.22.2-insiders (or 0.22.0) that we plan to release next week and the bug appears to be fixed already.

**Comment by sean-mcmanus** [comment]
Nope, not fixed -- it's some strange timing issue caused by PlatformIO's writing of the c_cpp_properties.json in a way we do not expect, so when we process the file for squiggles it isn't working.

i.e. when I simply make a whitespace edit to the file, the squiggle goes away, and the bug doesn't repro if platformIO doesn't re-write the c_cpp_properties.json, such as via using the same config but with a different VS Code without the PlatformIO extension installed.

**Comment by sean-mcmanus** [comment]
I'm seeing garbage data from document.getText() -- i.e. the VS Code object is corrupt -- after the call to vscode.workspace.openTextDocument(this.propertiesFile).then((document: vscode.TextDocument))...so something really buggy is going on, as if VS Code is reading the document while it's being overwritten by another process.

**Comment by sean-mcmanus** [comment]
Can you guys change your extension to write a version? I'm seeing the version not existing in the c_cpp_properties.json that PlatformIO creates, which causes us to upgrade it from version 0 to 4 and then write the changed file -- so VS Code might have some bug if PlatformIO is still making changes to the file at the same time.

**Comment by sean-mcmanus** [comment]
The bug stops reproing if I add code that skips adding the `"version": 4` to our c_cpp_properties.json after PlatformIO creates the version without it, although it gives a "Missing property "version"" as expected. So, PlatformIO adding the version should fix the issue -- let us know if you expect some other fix. If you see a bug with our open source TypeScript let us know, but the upgrade/squiggle processing works fine as long as PlatformIO isn't installed, so it looks like either PlatformIO or VS Code is doing something buggy that causes the document object we receive to be corrupt. The corruption looks like:

```
...
],
            "intelliSenseMode": "clang-x64",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "/Users/ikravets/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc -mlongcalls"
        }
    ]
}eather\"",
            ""
            ],
            "intelliSenseMode": "clang-x64",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "/Users/ikravets/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc -mlongcalls"
        }
    ],
    "version": 4
}"
```

**Comment by ivankravets** [comment]
Just a simple question. Why did it work before? The only last updates to C/C++ extension brought these issues.

Who does generate this "Path is not a directory" message? VSCode or C/C++ extension? See https://github.com/Microsoft/vscode-cpptools/blob/77806f657fd69a0cf39545621caef2159e66dd1e/Extension/src/LanguageServer/configurations.ts#L879

This is a bug, would be good to fix it. Yes, we can update manifest with "version" field. However, the right solution is to fix the root of the problem.

**Comment by sean-mcmanus** [comment]
It worked before because we didn't have c_cpp_properties.json squiggles that did an open file of c_cpp_properties.json. Our extensions generates the message -- the code is correct under normal circumstances, but the document somehow becomes corrupted when the PlatformIO extension is used as I mentioned earlier. The root cause may be a VS Code bug, but I don't know exactly what PlatformIO is doing that could cause the corrupt document to occur (i.e. might be some simulatenous reading/writing to the same file).

Also, a better approach for an extension to provide us with includePath/defines is to use the custom configuration provider interface, instead of writing to the c_cpp_properties.json: https://github.com/Microsoft/vscode-cpptools-api . The CMake Tools Extension and some other extensions that provide build system support use that. PlatformIO might be the only extension we know of that writes to c_cpp_properties.json still. Let us know if that API is insufficient for your needs. You might want to check if any of the known bugs are an issue for your scenario: https://github.com/Microsoft/vscode-cpptools/issues?q=is%3Aopen+is%3Aissue+label%3Aapi

**Comment by ivankravets** [comment]
Thanks. I did fix on our side and added this `version` field. As for the C/C++ extension API, I'll take a look later. It does not make any sense for end developers how we provide this information: through c_cpp_properties.json or dynamic API. I prefer to stay with `c_cpp_properties.json`, it is clear for everyone, even for developers. They see which build options do we use per project.

**Comment by sean-mcmanus** [comment]
@ivankravets Okay, that sounds fine. The main benefit of using the custom configuration provider API is the ability to set the includePath and defines on a per-file basis (which may not be relevant to your scenario).
