### ISSUE TITLE
Linting error for EXPIMP_TEMPLATE template class DECLSPECIFIER std::string;

### ISSUE THREAD

**Issue by al-sabr** [microsoft/vscode-cpptools#3410]
**Type: LanguageService**

**Describe the bug**
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

- C/C++ Extension Version: 0.22.1: March 21, 2019
- Other extensions you installed (and if the issue persists after disabling them):

![image](https://user-images.githubusercontent.com/26530975/55587976-f1e4ec00-572c-11e9-91ea-2159d5aea317.png)

- A clear and concise description of what the bug is.

**To Reproduce**
Check the screenshot this is a simple header file for a DLL which export a class with STL.

**Expected behavior**
No error linted in red.

**Screenshots**
![image](https://user-images.githubusercontent.com/26530975/55588061-2062c700-572d-11e9-898a-f99b68e321a2.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
The root cause is with the parser code shared with Visual Studio. Can you file a Visual Studio C++ bug at https://developercommunity.visualstudio.com/content/problem/post.html?space=62 and then link the bug to this issue (they prefer users to report the bugs directly instead of me)? You should be able to login with your GitHub account. Otherwise, I can file the bug myself.

**Comment by al-sabr** [comment]
I filed the bug and linked it to this ticket.

**Comment by sean-mcmanus** [comment]
https://developercommunity.visualstudio.com/content/problem/520117/linting-error-for-expimp-template-template-class-d.html

**Comment by bobbrow** [comment]
The linked Visual Studio bug was closed as lower priority. Unfortunately, this means that we won't be getting a fix for VS Code either.
