### ISSUE TITLE
error-checking fails for a single file. corrupt ipch file ?

### ISSUE THREAD

**Issue by septag** [microsoft/vscode-cpptools#3426]
vscode: 1.33.0
cpp: 0.22.1

windows 10

I was modifying the source code, suddenly it brought many false errors in the file. finally I could fix it by deleting the ipch files in the `.vscode/ipch` directory and restarting.
But It keeps happening after some time. the compilation is ok, but the errors I get in the file are mostly:

- `expected an identifier`
- `undefined`
- `expected a filename` on includes
- `expected a ;`

unfortunately, the latest update has even more bugs than the previous one and most of my time is spent struggling with the intellisense and false error-checking of the extension.

log=debug:

```
Checking for syntax errors: file:///.../graphics.c
queue_update_intellisense for files in tu of: D:\...\GRAPHICS.C
errorSquiggles count: 0
errorSquiggles count: 104
```

**Comment by septag** [comment]
btw, I upgraded to *0.22.2-master* and false red-squiggles seems to fixed. I'll re-open this if it comes back

**Comment by sean-mcmanus** [comment]
@septag Using 0.22.2-master is not recommended and will likely break something, because it doesn't have our language server changes -- it just has our TypeScript changes, and it's unlikely that the TypeScript changes actually fixed anything involving IntelliSense squiggles, since that's implemented in the language server binary, which hasn't been updated yet. We will be releasing a 0.22.2-insiders soon, so you should check whether it's still fixed with that.

**Comment by septag** [comment]
yes, it was very buggy, I switched back to 0.22.1
