### ISSUE TITLE
Intellisense bugs

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3432]
**Type: LanguageService**

**Describe the bug**
- VS Code Version: 1.31
- C/C++ Extension Version: 0.21
- in msvc-x64 and clang-x64

1. Currently Intellisense can't check unused variables.

2. Don't show errors if you forget type convert,such as(int *m; char *n; m = n;). It's ok in cpp file but in .c file, it's wrong.

**Comment by sean-mcmanus** [comment]
This is "by design". We haven't enabled "warnings" yet, just actual compiler errors. It's being tracked by https://github.com/Microsoft/vscode-cpptools/issues/828. The feature is postponed until we can add a setting to disable particular warnings: https://github.com/Microsoft/vscode-cpptools/issues/2345 .
