### ISSUE TITLE
Wrong syntax highlighting for "deleted" in C++

### ISSUE THREAD

**Issue by gareth618** [microsoft/vscode-cpptools#3454]
Issue Type: <b>Bug</b>

If I have a variable like "deleted" or something that starts with "delete", this prefix is highlighted like it is a keyword, and the rest of the name is highlighted like a normal variable. Please fix that.

Extension version: 0.22.1
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:46.685Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by sean-mcmanus** [comment]
The bug isn't reproing for me. What version of VS Code do you have installed? Is this with a C or C++ file. What is the type of the variable? i.e. can you provide the complete text of the file? What theme are you using?

![image](https://user-images.githubusercontent.com/19859882/56005794-1b4ecc00-5c87-11e9-9ff7-5a6fbc7fe7bb.png)

**Comment by gareth618** [comment]
The bug is only in C++ files because the delete operator doesn't exist in C. I'm using Monokai, but it's available for any theme. I have the latest version of VSCode, and I think the problem appeared after this update.

![image](https://user-images.githubusercontent.com/24765842/56024644-1cc8d480-5d19-11e9-8e4b-d89f74633338.png)

**Comment by tat3r** [comment]
Can we just start using the compilers AST (libclang or whatever) instead of using regular expressions?

**Comment by sean-mcmanus** [comment]
That is strange, because I'm still not reproing with C++, Monokai, and the latest VS Code.
![image](https://user-images.githubusercontent.com/19859882/56063193-73d3a700-5d23-11e9-83fc-ab3cdd6fa0af.png)

Our C++ extensions does not implement the colorization. It's implemented by VS Code using the grammar at https://github.com/jeff-hykin/cpp-textmate-grammar . The grammar has been going through a lot of churn recently as they've been fixing bugs (and regressing certain cases as well). Using the latest "Better C++ Syntax" extension might fix the issue for you.

I don't know if using libclang for syntax highlighting is feasible or not. VS Code's infrastructure is setup to run the TextMate grammars currently. Other tools like Atom have switched to TreeSitter.

**Comment by tat3r** [comment]
Yeah the textmate grammar is just regular expressions, and will never work 100%, see: [`all of these`](https://github.com/jeff-hykin/cpp-textmate-grammar/issues?utf8=%E2%9C%93&q=label%3A%22%E2%98%A0%EF%B8%8F+provably+impossible%22+)

It's not a colorization problem, it's a language parsing problem, one that most compilers provide a solution for.

**Comment by sean-mcmanus** [comment]
@tat3r Porting over the parser/colorizer that Visual Studio uses is high on our list of major features -- it's being tracked by https://github.com/Microsoft/vscode-cpptools/issues/230 (semantic) and https://github.com/Microsoft/vscode-cpptools/issues/3460 (lexer).

**Comment by gareth618** [comment]
I've just installed Better C++ Syntax and now it's OK, thank you! :)
