### ISSUE TITLE
IntelliSense does not suggest generic template members

### ISSUE THREAD

**Issue by StefanFabian** [microsoft/vscode-cpptools#3548]
**Type: LanguageService**
Intellisense does not suggest static members of (templated) structs.
Possibly templated stuff in general as it also doesn't seem to understand an std:deque with a template parameter.
 

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1

**To Reproduce**

Create a templated struct with a static member and try to access it.

**Expected behavior**

IntelliSense should suggest the static member.

**Screenshots**

![Screenshot from 2019-04-27 10-17-57](https://user-images.githubusercontent.com/2090520/56846976-f2a91200-68d5-11e9-8387-867aff480e27.png)

**Comment by Lennon925** [comment]
It seems to be caused by template and generic instead of static.  IntelliSense can suggest the static member and you can test it like my attached picture. I think behavior about intellisense suggestion and 'go to definition' will go wrong when you use template and generic  together.

![2222捕获](https://user-images.githubusercontent.com/39362073/56862116-19507100-69da-11e9-9291-44307b9dcedf.PNG)

**Comment by sean-mcmanus** [comment]
We're tracking IntelliSense features inside templates with https://github.com/Microsoft/vscode-cpptools/issues/1946 .
