### ISSUE TITLE
Enhance symbol indexing

### ISSUE THREAD

**Issue by dfroze** [microsoft/vscode-cpptools#355]
I am working on multiple projects and every time i change the workspace from one to another, i have to wait a lot 20-25m for VSCode to finish indexing all the symbols. It would be great if he could store his indexing and just do a check whenever it opens the workspace (that is if the workspace has been opened before)

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension.  Please reopen if you are still seeing complete re-indexing of your workspaces every time you open them.  Large folders may still take a minute or so to validate, but if the timestamp of the files being indexed hasn't changed we shouldn't be re-parsing that file.
