### ISSUE TITLE
Debugger doesn't recognize "WinMain" or "wWinMain" as entry points

### ISSUE THREAD

**Issue by nadalaba** [microsoft/vscode-cpptools#3585]
Type: Debugger

- OS and Version: Windows 10 Pro 1809 x64
- VS Code Version: 1.33.1 (System Setup)
- C/C++ Extension Version: 0.22.1
- GNU gdb (GDB) Version: 8.2.1
- gcc (Rev2, Built by MSYS2 project) Version: 8.3.0

The debugger throws an error:
"Unable to open 'crt0_c.c': A system error occurred (UNKNOWN: unknown error, stat 'e:\mingwbuild\mingw-w64-crt-git\src\mingw-w64\mingw-w64-crt\crt\crt0_c.c')."
when starting a debug session in a C application that has a `WinMain` function instead of `main`, _and when the "StopAtEntry" option of the `launch.json` is set to `true`_.

It seems that instead of the debugger stopping at `WinMain` in the debuggee file, it's stopping at `main` in the file `crt0_c.c` (which doesn't exist on my machine) , leading to an error.

If the function was `wWinMain` (unicode version of `WinMain`) the debugger would run the program just _like if_ `StopAtEntry` was set to `false`, i.e, it would run without stopping anywhere, but without any errors.

I tried compiling the `WinMain` version as a WINDOWS application with multiple variations of flags but the problem persisted:
![cFinal](https://user-images.githubusercontent.com/37968805/57201494-32d95600-6fa2-11e9-8f0a-88b85c78192e.JPG)  
and when adding the flag `"-Wl,--entry=WinMain"` the error is gone but the debugger would continue without stopping, just like the `wWinMain` case.

The `WinMain` version was compiled with the commands shown in the image above.
The `wWinMain` version was compiled with this command:
`gcc -o <fileBaseName> -g -mwindows -municode <fileName>`

1. Open a C source file that has a `WinMain` or `wWinMain` function as an entry point.
2. Add "stopAtEntry": true, to `launch.json`
3. Start a debugging session with gdb.
4. Debugger would crash with an error (`WinMain` case), or it would continue without stopping at entry (`wWinMain` case) with no error.

launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug C/C++",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "internalConsoleOptions": "openOnSessionStart",
            "MIMode": "gdb",
            "miDebuggerPath": "C:/msys64/mingw64/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ],
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            }
        }
    ]
}
```

Debugger Console log in the `WinMain` version (it stops at crt0_c.c in line 354):
[debug.log](https://github.com/Microsoft/vscode-cpptools/files/3146134/debug.log)

**Comment by pieandcakes** [comment]
>The debugger throws an error:
"Unable to open 'crt0_c.c': A system error occurred (UNKNOWN: unknown error, stat 'e:\mingwbuild\mingw-w64-crt-git\src\mingw-w64\mingw-w64-crt\crt\crt0_c.c')."
when starting a debug session in a C application that has a WinMain function instead of main, and when the "StopAtEntry" option of the launch.json is set to true.

You can ignore that error as it is an error just saying it can't find the file. You can step/continue from it and continue debugging.

>It seems that instead of the debugger stopping at WinMain in the debuggee file, it's stopping at main in the file crt0_c.c (which doesn't exist on my machine) , leading to an error.

This happens because of [this](https://github.com/microsoft/MIEngine/blob/54a328b74d669fea7081219d679aa2be40066587/src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs#L866) line of code, where we tell the debugging session to stop at `main` so we can set up debugging. This is because every application has a `main()` method to stop at. Normally (when `stopAtEntry` is `false`) we silently stop and continue, but if you set `stopAtEntry` to `true`, that same stop is now visible as that is the entrypoint into the application. We aren't doing anything complex to determine the entry point. In your case, you are using `WinMain` and the behavior is not as expected. If you want to mimic the experience, you would want to set a breakpoint in your first line of code or add a function breakpoint on `WinMain`.
