### ISSUE TITLE
'Find all references'  not working

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#361]
_From @dfroze on November 22, 2016 11:56_

- VSCode Version: 1.7.1
- OS Version: Linux Mint

Hy,
Not sure if I should have posted here or in vscode-cpp. 
Regarding the the feature "Find all references", it doesn't work at all. Every time I use it I receive empty results.
Do I need to configure or install something?

_Copied from original issue: Microsoft/vscode#15881_

**Comment by BillDenton** [comment]
Issues #361, #404 and #388 appear to be the same.

**Comment by knetworx** [comment]
This issue keeps being closed because "these other issues are the same", but all those other issues were closed because this issue is the same. Every issue I can find about this is closed, but none of them are actually resolved - each one just references the other closed issues. And most of them have a reference to themselves as a matching issue. For example, @BillDenton referenced issue #361 in the current issue, which *is* issue #361.

EDIT: Finally found the original: #15

**Comment by sean-mcmanus** [comment]
Find All References is available in 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders , but you'll need to set the C_Cpp.experimentalFeatures setting to "Enabled".
