### ISSUE TITLE
No IL available with hover with sshfs

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3617]
Is there any updates for this?

I got the same error while hovering over the includes:

![image](https://user-images.githubusercontent.com/4453664/57349559-311fb600-718d-11e9-9b95-43d0affdc650.png)

Edit: the error seems to be similar to https://github.com/microsoft/vscode-cpptools/issues/1694

```
Unable to retrieve file system information for xxx. error = -1
```

_Originally posted by @garyng in https://github.com/microsoft/vscode-cpptools/issues/1046#issuecomment-490343184_

**Comment by sean-mcmanus** [comment]
@garyng

The "Unable to retrieve" is probably unrelated (it's not an IntelliSense error).

Can you run the C/C++: Log Diagnostics command, and/or share more repro info?

The "No IL available" means our IntelliSense parser wasn't able to compile any code for some reason.

**Comment by garyng** [comment]
The source files reside on a network drive mounted with `sshfs`, similar to https://github.com/microsoft/vscode-cpptools/issues/1046; but I'm using [sshfs-win](https://github.com/billziss-gh/sshfs-win) (which is based on [winfsp](https://github.com/billziss-gh/winfsp)) instead of [win-sshfs](https://github.com/feo-cz/win-sshfs) (https://github.com/microsoft/vscode-cpptools/issues/1046#issuecomment-330656624, which is based on [dokany](https://github.com/dokan-dev/dokany)).

There errors I'm getting are same as https://github.com/microsoft/vscode-cpptools/issues/1694#issuecomment-373818076 - lots of `Unable to retrieve file system information...` errors, is this an error related to the case sensitivity of filenames? (The remote system is a linux machine)

I then tried using [SFTP Net Drive](https://www.nsoftware.com/sftp/netdrive/), and it works, I was able to get intellisense, but sftp net drive was really slow...

I think this is mostly the issue of `sshfs`?

Hope that helps!

_Doesn't have the access to the machine now, will get back with the log afterwards._

**Comment by sean-mcmanus** [comment]
The issue could be case sensitivity or just our the lack of support for sshfs.

**Comment by garyng** [comment]
> 
> 
> The issue could be case sensitivity or just our the lack of support for sshfs.

[RaiDrive](https://www.raidrive.com/) seems to be working, so I think its safe to assume that this is a problem of `sshfs`?

_for others facing the same issue while using `sshfs`: probably just go for the [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension, which unfortunately doesn't work on my side..._

**Comment by Appendme** [comment]
`Quick info operation failed: FE: 'Compiler exited with error - No IL available'`

C++ Diagnostics:
https://gist.github.com/Appendme/db4ef611390ded0dc1a2e8f40a872eaf#file-vscode-uppercase-path-L48-L52

Vscode brings the path to uppercase?

**Comment by sean-mcmanus** [comment]
@Appendme We only preserve the case when we detect WSL mode on Windows. It looks like in your case we think it's a Windows case insensitive path. Can you file a new bug with more repro info? It looks like we don't handle paths with `"\\WSL$"` correctly. How did you get that path to be used?

**Comment by rgw3d** [comment]
@sean-mcmanus I'm running into the same issue here.

I'm on Windows 7, using https://github.com/billziss-gh/sshfs-win to get a sshfs file system on a Linux box. Both my Windows 7 and Linux box are offline otherwise I'd use the Remote Development extension. 

I've tested with v0.26.3, cpptools-win32.vsix


```
-------- Diagnostics - 2/7/2020, 11:05:14 AM
Version: 0.26.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe",
    "cStandard": "c11",
    "cppStandard": "c++11",
    "intelliSenseMode": "gcc-x64"
}
Translation Unit Mappings:
[ Q:\GIT\EXAMPLE\EXAMPLE\FILE.CPP ]:
    Q:\GIT\EXAMPLE\EXAMPLE\FILE.CPP
Translation Unit Configurations:
[ Q:\GIT\EXAMPLE\EXAMPLE\FILE.CPP ]:
    Process ID: 7312
    Memory Usage: 8 MB
    Compiler Path: C:/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe
    Includes:
        C:\MINGW-W64\X86_64-8.1.0-RELEASE-POSIX-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++
        C:\MINGW-W64\X86_64-8.1.0-RELEASE-POSIX-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\X86_64-W64-MINGW32
        C:\MINGW-W64\X86_64-8.1.0-RELEASE-POSIX-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD
        C:\MINGW-W64\X86_64-8.1.0-RELEASE-POSIX-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE
        C:\MINGW-W64\X86_64-8.1.0-RELEASE-POSIX-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\MINGW-W64\X86_64-8.1.0-RELEASE-POSIX-SEH-RT_V6-REV0\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=80100
Total Memory Usage: 8 MB
```

Where Q is my mapped drive. It looks like it is making the paths uppercase. It also provides a clickable link on those file paths, which fail to open

**Comment by sean-mcmanus** [comment]
@rgw3d FYI, with Win10 you can remote to a local Linux system using WSL, which we support better because our extension runs using our Linux binary with the correct case sensitivity.

Our support for other Linux scenarios running on Windows is not expected to improve. In particular, it appears you're hitting issues with our Windows code running in case insensitive mode. A similar issue for forcing case sensitivity is https://github.com/microsoft/vscode-cpptools/issues/1994 .

**Comment by rgw3d** [comment]
@sean-mcmanus thanks for the quick response

Yeah if I could use WSL with Win10 I would, but I'm stuck with an older machine on an air-gapped network, unfortunately.

That totally makes sense regarding support

**Comment by bobbrow** [comment]
This issue should be resolvable by using the more recent `C_Cpp.caseSensitiveFileSupport` setting.
