### ISSUE TITLE
/tmp/edg0_# Files Taking Up Memory

### ISSUE THREAD

**Issue by vindicatorr** [microsoft/vscode-cpptools#3633]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.34.0-insider
- C/C++ Extension Version: 0.23.0
- Other extensions you installed (and if the issue persists after disabling them):
- I run out of RAM due to /tmp/edg0_# files.

**To Reproduce**

1. Run "df" and take note of /tmp usage.
2. Open ANY cpp/c project.
3. Run "df" again and notice the immediate usage increase for /tmp.
4. Continue working on the project and "df" keeps showing an increase.
5. Run "lsof | grep edg0" at any of those other steps to see the files that are locked/deleted. In other words, the files aren't visible in /tmp, but are still taking up RAM.
6. Work on different files and see more edg files listed in lsof.

**Expected behavior**

Don't chew up all of the available memory.

**Screenshots**

**Additional context**

The pid in the lsof output points to "~/.vscode-insiders/extensions/ms-vscode.cpptools-0.23.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux".
My guess is that it has something to do with "history" so you can "undo", but I don't see why it would cause 1GB of usage.

**Comment by michelleangela** [comment]
Hi @vitosamson, thank you for your feedback.

Is the Linux OS setup to use the RAM as part of the disk cache by any chance? Is this the behavior you're seeing based on these articles:

- https://superuser.com/questions/903243/arch-linux-insane-memory-usage
- https://wiki.archlinux.org/index.php/Frequently_asked_questions#Why_is_Arch_using_all_my_RAM.3F

**Comment by vindicatorr** [comment]
Just to put it out there, I set "C_Cpp.default.intelliSenseMode": "gcc-x64" in settings.json instead of msvc-x64, and that appears to have fixed the ever-increasing size issue.
The change of course changes the program used to "~/.vscode-insiders/extensions/ms-vscode.cpptools-0.23.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux"

And yes, /tmp uses the tmpfs which uses RAM: http://man7.org/linux/man-pages/man5/tmpfs.5.html
I do see that Debian/Ubuntu purportedly has /tmp set to use the drive instead of RAM: https://en.wikipedia.org/wiki/Tmpfs while Arch and Gentoo set it to use RAM: https://wiki.gentoo.org/wiki/Tmpfs since it's meant to be cleared at every boot which makes it much faster.

**Comment by sean-mcmanus** [comment]
Yeah, if you're on Linux (or not compiling with cl.exe), you probably want the gcc-x64 (or clang-x64) mode. I don't know why msvc-x64 mode would trigger the behavior describe, unless it was causing lots of crashes maybe.

**Comment by michelleangela** [comment]
@vindicatorr, that's interesting for the behavior to change when the IntelliSense mode was set.

We'd like to understand more of what's happening with the repro. Could you provide the following when the issue occurred?

- A copy of your `c_cpp_properties.json` settings

- A copy of the output from running command `C/C++: Log Diagnostics`. Note that you will need a source file open prior to running the command, as the command takes logs on the current active document. Feel free to trim off any path locations.

- Did you have IntelliSense cache enabled? That is was `C_Cpp.intelliSenseCacheSize` set to a value greater than 0 for the workspace folder?

- How much RAM does the repro machine have and what is the processor?

**Comment by vindicatorr** [comment]
It's interesting that you mentioned the c_cpp_properties.json settings... I took a look and saw I ALREADY HAD "intelliSenseMode": "clang-x64", yet msvc was being used before I entered the intellisense setting to gcc in settings.json.

I didn't see any Log for C/C++ (which seems to be a good sign), so I went into settings and changed it from Error to Debug.
I saw "Attempting to get defaults from compiler found on the machine: '/bin/clang'", but this is odd since I removed the clang setting in the c_cpp_properties.json, and removed the intellisense setting (gcc) in settings.json.
Also, I see lsof is still showing the Msvc process pointing to the locked/deleted /tmp file. Again, with no intellisense setting set, the log shows reference to clang, but lsof is showing Msvc. So bizarre.

The default is set for the cache size of 5120MB.

I have an 8GB Haswell system. The point though is the msvc memory(/disk/tmp) usage grew to 1GB until I made the mode change, while after changing to gcc, the usage was negligible.

OK, now after all of that, I added the intellisense-mode setting for gcc-x64 back in c_cpp_properties.json, restarted, and the log still is referencing /bin/clang and no mention of gcc other than the includePath and browse:path locations.
```
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
```
Yup, I see "intelliSenseMode: clang" in the log even though it was set to "gcc-x64" in c_cpp....json.

ACK! I looked at my previous post and saw the line "The change of course changes the program...", but there is NO change in that post from my OP.
I was wondering why I wasn't seeing any change to Microsoft.VSCode.CPP.IntelliSense.Msvc.linux being used, and there's no reason there would be a change since that is the ONLY intellisense program in ~/.vscode-insiders/extensions/ms-vscode.cpptools-0.23.0/bin, and there isn't one for msvc, clang, and gcc.

What I do find interesting is that no matter what mode I choose, either in settings.json or c_cpp....json, clang is what's listed in the log.

I see when I switch to a file, another msvc process is applied to it and if I close that file, the process is disposed.

I find that edg0 files listed in the lsof are usually ~700KB, but at times I've encountered them being 20MB and just now I had started to autocomplete a defined variable, then peek it, then go to the file that the define is in and suddenly I get 1 msvc process (instead of 2 (the one I was writing in, and the one with the definition)) that went to 15MB, then 44MB, 59MB and now after removing that partially defined variable from earlier, I'm back at 2 processes, 1 is 118MB and the other is 15MB.
And now that I've undone everything I typed (ctrl+z), there are 2 processes for the 2 files I worked in and they are at 15MB and 59MB for those edg0 files.
This is all when I do NOT have the mode defined anywhere.

I don't know if you want the log files if there are no errors in them or if you want a different log mode other than the verbose "debug".

**Comment by michelleangela** [comment]
The process **Microsoft.VSCode.CPP.IntelliSense.Msvc.linux** is the IntelliSense process spawned per translation unit. So you will usually see one per source file that is currently opened for editing. 

For clarification, `intelliSenseMode` does not determine which IntelliSense process is used (and yes there is only one IntelliSense program). I think the confusion is from the name "msvc" in the process which coincidentally is also used for one of the option modes for `intelliSenseMode`. `intelliSenseMode` determines which mode the IntelliSense engine will run in to support either the Windows cl.exe compiler or Clang compiler or GCC compiler. If no mode is set or if the option `${default}` is used, then a mode will be chosen based on your OS. If you're on Windows, the mode defaults to `msvc-x64`; on Mac it defaults to `clang-x64`; and on Linux defaults to `gcc-x64`. If you are building your project with GCC, you would want to set the `intelliSenseMode` to `gcc-x64` so that IntelliSense engine will be able to process your code as if it's compiling for GCC.

What is interesting is that even if you set `intelliSenseMode` to `gcc-x64`, it's still showing clang on the log. Could you send over the full log with verbose "debug" that you are seeing this from? You can either send the log as as an attachment or copy it directly on the thread. Can you also send a copy of the output from running command `C/C++: Log Diagnostics`? Note that you will need a source file open prior to running the command, as the command takes logs on the current active document. **Feel free to trim off any path locations from the either of the logs before sending them.**

As for the edg0 files, these are generated when IntelliSense cache is enabled. If you disable IntelliSense cache, it should not generate any of those files. The size of the files should be based on the complexity of a translation unit or source file and will change as you edit a source file or do something that will cause some IntelliSense computations. Do the files get deleted or is the memory from the files freed after an IntelliSense process shuts down?

**Comment by vindicatorr** [comment]
Oof, I neglected this issue...
I really like intellisense, but I just don't know why the files would get so large.
I mean, 600+MB for a source file that is only 600 lines long seems excessive.
Oh geez, make that 150 lines long. I just figured it was the longer source file that I was working on more. I closed the smaller one, ran lsof again and saw the huge deleted file disappeared. Go figure.
Simply opening that smaller source file back up brings it to 700KB (not MB) of usage.

I'd prefer not to close the file I'm working on, to free up memory, because I make good use of Undo/Redo.

The lsof command shows there are "(deleted)" edg files while I'm working on their associated code files, and are finally released if I close the tab for the source file I was working on, or just closing vscode altogether.
I just don't like how it just keeps accumulating from 700KB to 600+MB... for EACH file I work on.

I don't recall ever having such and issue when I used Visual Studio years ago (though it was for VB code), and even now, using the CSharp extension doesn't even have that effect, yet I use intellisense there as well.

Again, settings.json has: "C_Cpp.default.intelliSenseMode": "gcc-x64"
I had closed vscode PRIOR to generating these log files.
I'll be sure to run diagnostics again later when the file gets huge again.
[cppDebugLog.txt](https://github.com/microsoft/vscode-cpptools/files/3439239/cppDebugLog.txt)
[cppDiagnosticsLog.txt](https://github.com/microsoft/vscode-cpptools/files/3439240/cppDiagnosticsLog.txt)

**Comment by vindicatorr** [comment]
And huge is what it just got...

You may notice I start off testing something in the c_cpp_properties.json file.
I noticed a problem with my #include "ili9225.h" having the red squiggle.
I saw someone already opened an issue regarding the includePath workspace/** having an issue with recursions, so for the moment, I just added /inc to make it work.

I was re-working a project I lost due negligence and where recovery gave me partials or corruption or nothing, so I was porting back a file from another project that was very similar.
After awhile, I started to type out a library command and the intellisense menu came up and my hard drive began to thrash. Lots of paging going on.

I had to relax and use the magic syskey to sync my drive to allow me to actually do something.
After probably 30+ minutes of trying, I managed to close a couple of unneeded programs to free up a little bit of memory which was enough for me to keep vscode open so I could copy out the logs:
[cppDebugLog_Huge.tar.gz](https://github.com/microsoft/vscode-cpptools/files/3464293/cppDebugLog_Huge.tar.gz)
[cppDiagnosticsLog_Huge.txt](https://github.com/microsoft/vscode-cpptools/files/3464294/cppDiagnosticsLog_Huge.txt)

While all of the memory usage was huge for just 3 files, I was shocked to see stm32f4xx_hal_msp.c be the largest since I barely did anything in that file and even undid what I was going to implement.
I'm talking working on a single function, adding maybe 20 lines of code, then removing them. That was it.

**Comment by michelleangela** [comment]
@vindicatorr, sorry for the delayed investigation on this issue and thank you for providing logs.

IntelliSense for C++ cannot be compared with IntelliSense for VB or CSharp as the languages are compiled and processed differently and use different IntelliSense.


**IntelliSenseMode**
From the logs, the IntelliSenseMode is `clang-x64` because the compiler that is found and used by IntelliSense engine is `/bin/clang`. If no value for `compilerPath` in `c_cpp_properties.json` is specified, then IntelliSense will try to get the default compiler found on the machine and set the IntelliSenseMode based on the compiler. I first assumed that you were already using a GCC compiler for the `compilerPath` because IntelliSenseMode was set to `gcc-x64`.

Suggestion: try setting `compilerPath` to a GCC compiler with IntelliSenseMode set to `gcc-x64`. IntelliSense should use GCC for compiler and IntelliSenseMode.

**Memory usage**
Based on the logs, the translation unit of `stm32f4xx_hal_msp.c` will use a lot of memory if it has a lot included headers in the file. Are there a lot of included headers in `stm32f4xx_hal_msp.c` or are the headers fairly large, like 1000+ lines? The temporary edg# files has to store data for a translation unit, which comprises of included headers and source code. As you edit within the class scope, the memory usage will increase. But if you make edits outside of the class scope, like add a global variable, the memory usage of IntelliSense should reset. To verify this do:
1. Make a lot of edits/hovers/selection in a class function in `stm32f4xx_hal_msp.c`
2. Run `Log Diagnostics` or make note of the memory usage.
3. Make an edit outside the class scope, such as adding a global variable `int x;`
4. Run `Log Diagnostics` or make note of the memory usage.
5. Did the memory usage reset or decrease?

You can also check the memory usage of editing a source file with no includes except for the header of the class and then add a lot of large header files and see if there is a difference in memory usage.

We have plans to to reset the memory usage of a translation unit when it grows to a certain size based on current memory available and/or total RAM.

As for the "(deleted)" temporary edg files, are you saying that they take up memory until the tab for the source file is closed even when the edg file is deleted? Closing the tab of the source file terminates the associated IntelliSense process, so the memory usage of that process should be released.

**Comment by vindicatorr** [comment]
> the IntelliSenseMode is clang-x64 because the compiler that is found and used by IntelliSense engine is /bin/clang. If no value for compilerPath in c_cpp_properties.json is specified, then IntelliSense will try to get the default compiler found on the machine and set the IntelliSenseMode based on the compiler.

Odd, because earlier:
> on Mac it defaults to clang-x64; and on Linux defaults to gcc-x64

I'm on linux and have both clang and gcc installed and I had Intellisensemode set to gcc-x64.
In any case, I did what you suggested and specified
"C_Cpp.default.compilerPath": "/usr/bin/gcc" along with
"C_Cpp.default.intelliSenseMode": "gcc-x64" and everything is copasetic.
The diagnostic log now states: "IntelliSense Mode: gcc-x64"

Though it may be nothing, the c++ log still does clang stuff even though it wasn't needed.
```
cpptools/queryCompilerDefaults: 1
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 11376
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 11409
cpptools/didChangeFolderSettings
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'
terminating child process: 11417
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'
terminating child process: 11430
  Folder: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/ will be indexed
```

I will say that ST probably does something with their SDK that would normally be a no-no (particularly in this translation/memory case), in that they provide a single header with defines for simplicity that reference other headers as needed.

In my particular case with my ST Discovery board, a single header of stm32f4_discovery.h is provided.
It, in turn, references "stm32f4xx_hal.h" and then to "stm32f4xx_hal_conf.h" which is the go-to for everything any of their chips might use, all in one place.
Within "stm32f4xx_hal_conf.h", you can uncomment any number of defines like HAL_GPIO_MODULE_ENABLED, HAL_I2C_MODULE_ENABLED, HAL_UART_MODULE_ENABLED and many more. Each of them will #include their relative header when enabled.
I think I have like 13 modules I make use of, each of which has their own header(s).
I just include that in my main.h and for any other files in my project, I just reference my main.h which will then have references via the stm32f4xx_hal_conf.h.

So if I have code dedicated to the usage of USART in a single file, I reference my main.h even though it has all those other headers available to it (like I2C) which go unused in that USART file.
Same thing with a single file I use for I2C work.

The take-away is that the stm32f4xx_hal_msp.c that had the most memory usage basically shares the same stm32f4xx_hal_conf.h that the smallest memory using file main.c, as well as ili9225.c which was a bit larger in memory usage than main.c but is the largest file in my project while the msp file is probably the smallest file.
And they ALL make SOME use of the modules (one or more) in stm32f4xx_hal_conf.h.

I know I could just specify the exact headers needed for any given file, like "stm32f4xx_hal_gpio.h" and "stm32f4xx_hal_spi.h" for the ili9225.c file, and "stm32f4xx_hal_usart.h" for my usart file. And all 3 for the msp file.

Well! I must say that is one interesting effect of dropping memory usage.
I did just what you suggested, by hovering/peeking and creating that global variable and memory started at 50MB, got up to 88MB and after adding that variable, it went down to 78MB (not 50MB, but still...).
I'll give that a go when I encounter such huge memory again.

I just now added "test.h/c" files and it starts at like 15MB with no other headers other than stdint and only a uint8_t variable.
After assigning the var, it's 16MB.
Adding the main.h (which again references that all-encompassing stm32f4xx_hal_conf.h), it jumps to 50MB. Still far from 1GB+.
Simply calling the HAL_Delay() function brings it to 65MB.
Calling HAL_SPI_Transmit() brings it up to 68MB (only 3MB).
Calling HAL_GPIO_TogglePin() makes no change, but then GPIO stuff is likely referenced in SPI anyway.

I can't say I understand much of what's going on.
You mention memory dropping/resetting simply by adding a global variable and that y'all plan to have basically what sounds like a garbage cleanup (using a dotnet term) for the translation unit.
I don't know if resetting the unit causes performance issues with intellisense, but I've never encountered any performance problems with intellisense to begin with (in terms of speed/responsiveness), other than when I encounter memory problems that my hard drives begins to thrash as paging increases.

Uhhhh, I just had a thought to try that global var again in that test.c file by just adding another uint8_t var and diagnostics showed it bump up to 83MB. I don't know if I'm running diagnostics too soon after making a change (5 seconds?), but I see the c++ log say "Update IntelliSense time" ranges from 0.250 to 0.500 (mostly around 0.250) seconds.

Correct, those edg files, even though marked as "(deleted)", are for some reason retained in the file handles. They just don't show under /tmp, but that memory is most definitely being used (as demonstrated by sluggishness of my system due to the HD thrashing from paging).
Looking again at the lsof output, I see 917505 is used for /tmp/edg0_3669 (deleted).
I see 3669 is also the PID for Microsoft.VSCode.CPP.IntelliSense.Msvc.linux and there are 7 threads referencing that one edg file.
I think the question is whether the edg files are being closed and then deleted.
Frankly, I don't know why they would be deleted if the files are still open and being worked on, but there are NO edg files found anywhere under /tmp.

So diagnostics shows 83MB used for test.c, but the edg file <1MB?

I just tested something else by calling another GPIO function and seeing if there were any thread changes in lsof. Same with adding a call to an I2C function which I hadn't done yet (different header in stm32f4xx_hal_conf.h), but no changes whatsoever.
Diagnostics jumped up to 99MB, but the lsof size didn't change.

EDIT0:
Uhhh, I just deleted the test.h/c files (move to trash), and the 3669 process is still up (files still open). The tabs are gone too obviously.
I just closed each of the other tabs individually, while checking lsof each time...
NO tabs are open, yet that 3669 process is still up.
Only now, after I closed vscode, did the process go away and lsof is clear of any edg files.

**Comment by michelleangela** [comment]
The `tmp/edg` files, which are used for caching, are only unlinked or "(deleted)" during runtime of IntelliSense process. The handles of the files are closed when the process terminates. Terminating of the IntelliSense process is delayed by a few seconds when a source file is closed on the VS Code editor. This is in case the file is opened immediately after closing and the same IntelliSense process can be reused. This is why you may see lingering `tmp/edg` after closing a tab and running `lsof` afterwards.

When [language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) is set to `Debug` level, it will log when the IntelliSense process of a translation unit is shutting down, like below:
```
Shutting down IntelliSense server: <path-to/source-file.cpp>
Closing the communication channel.
```

To shut down all IntelliSense process and rescan a workspace, you can run the command `C/C++: Rescan Workspace`. However, if there is an open source file, then a new IntelliSense process will be created for that file.

You can also manually shut down the IntelliSense process via `kill <PID>` if you want to do a force shut down. There's no need to close the VS Code application to shut down an IntelliSense process.

It seems for your case, you may not want IntelliSense to create `tmp/edg` files, so you can disable [IntelliSense caching](https://code.visualstudio.com/docs/cpp/faq-cpp#_what-is-the-ipch-folder) by setting IntelliSense cache size to 0:
```
C_Cpp.intelliSenseCacheSize": 0
```

Can you verify if any time an IntelliSense process fully shuts down that `tmp/edg` files are closed?

**Comment by michelleangela** [comment]
Concerning the Clang stuff you saw in the logs

```
cpptools/queryCompilerDefaults: 1
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 11376
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 11409
```
This is to only query default settings in case the user does not specify any compiler. It does not mean that Clang is used for the actual IntelliSense processing. It looks like it finds Clang as the default compiler for the machine.

**Comment by michelleangela** [comment]
Created issue #4119 to track growing size of memory usage while editing.

**Comment by vindicatorr** [comment]
I had my project open for quite awhile today before seeing your posts.
I had been adding code (ADC/DMA stuff) and rejiggering(/refactoring?) code from one place to another.
Pleasantly/surprisingly, the /tmp folder was <60MB.

I ran a test with your suggestion of just killing off one of those processes. SIGTERM (-15) didn't work and I had to SIGKILL (-9).
Whoof! Ok, what I was about to say but wiped out, I'll say again, because this second attempt did something different...
I ran lsof and df and ps to see those edg files and related process.
I also had ran c++ diagnostics before and after. When I went to delete the last pid in the lsof output, I had to SIGKILL, because SIGTERM didn't do it. The process simply showed it was still there (you'll see why I phrased it like that in a moment).
I wiped out that part of what I was going to say because it was plausible that particular process was tied to a more recently created file I made which "may" have come after the previous diagnostics was run.

BUT this time, I took note of the pid from diagnostics, made sure it was listed in lsof and ps and tried to do a regular (-15) kill on that.
This time ps is showing "[Microsoft.VSCod] \<defunct>" for that process, whereas before it simply didn't kill it whatsoever, nor was it "defunct".
It made me think that it's possible my first attempt was like yesterday where I cleared all of the tabs, but a process was somehow still alive.
I do see lsof no longer shows the file handle being held, so that's good... BUT I ran diagnostics again and it still shows an entry for it:
```
...
[.../<filename>.c]:
    Process ID: 11411
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/gcc
...
```
That was my second attempt. I also tried to SIGKILL it, but it made no difference.
A third attempt with another listed pid also resulted in a defunct process.
As well as a fourth attempt for yet another pid using SIGKILL (-9).

You mentioned cpptools querying the default compiler...
I don't know why that would need to be done since I now have the "C_Cpp.default.compilerPath" set.
In addition, I'm going to make the assumption that cpptools makes the claim that "clang" is the "**default**" compiler since it was the first one it found (alphabetical? though I also have arm-none-eabi-gcc as well). I wouldn't think that linux would know about default compilers.
Just checked if it might be an environment variable. It was not.

I don't know if you want me to continue posting here or on the new issue. I'm sure this one is already a mess, with me going all over the place, which is why a new one was created.
I'll leave that one alone unless you say otherwise.

**Comment by michelleangela** [comment]
If there are no IntelliSense process running, the `Log Diagnostics` will only print out the current configuration settings and state there are `No active translation units`. If `Log Diagnostics` is still showing an entry for a source file, then that means the file is still active or open, because the extension (`Microsoft.VSCode.CPP.Extension.*`) will try to spawn an IntelliSense process (`Microsoft.VSCode.CPP.IntelliSense.*`) for any active document that needs an IntelliSense process. As long as the handles of `tmp/edg` files are closed after the IntelliSense process is shut down, then there shouldn't be an issue. 

I wouldn't try to manually kill an IntelliSense process of a file that you recently closed on the VS Code editor, because the process could already be shutting down as you try to manually kill it too. I would only try to manually kill a process if it doesn't shut down for more than a minute, or if there is a dangling process when `Microsoft.VSCode.CPP.Extension.*` shuts down.

You can disable IntelliSense caching if you don't want IntelliSense process using `tmp/edg` files.

For issues related to `tmp/edg` not getting cleaned up or closed, I would continue to post on this thread. Otherwise, anything related to memory usage growing while editing should be posted at #4119. I would create a separete post for other issues like dangling IntelliSense process.

The extension will always query default values regardless if `C_Cpp.default.*` or settings in `c_cpp_properties.json` are set. The default values are queried first so they are available to use in case the user settings are not set or there is some error in the values a user specifies.
