### ISSUE TITLE
Bunch of bogus directories get created when editing the C_Cpp.intelliSenseCachePath setting

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3644]
Make edits to the intelliSenseCachePath setting, such as trying to change it to `C:/New Folder/${workspaceFolderBasename}` and it will create a bunch of bogus directories like `$`.

**Comment by michelleangela** [comment]
This issue only occurs when making edits on the VS Code settings UI editor. The text field of the UI editor auto saves too fast while typing. Therefore whenever it saves as a user is typing, the extension gets incomplete input value for the IntelliSense path.

This fast auto saving is due to VS Code issue [Auto save in new settings results in multiple validation errors when typing text]( https://github.com/microsoft/vscode/issues/59391)

**Comment by michelleangela** [comment]
Two workarounds:
- Edit the IntelliSense path in the settings.json file. The extension will only get a notification change when the json file is saved.
- Instead of typing the path on the VS Code settings UI editor, copy the complete value for the path into the input text field.

**Comment by bobbrow** [comment]
@michelleangela, but don't we delete the old path when it changes?  Is the problem that we're trying to delete the folder while the IntelliSense cache is still being built and we just give up because we don't have access?

**Comment by michelleangela** [comment]
> @michelleangela, but don't we delete the old path when it changes? Is the problem that we're trying to delete the folder while the IntelliSense cache is still being built and we just give up because we don't have access?

Correct, it's supposed to delete the previous path when it changes. I think the bug of the previous path not getting deleted was introduced when typescript sends `cpptools_updateIntelliSenseCachePath` to the extension, where it first updates the path before the check if it changed is executed.
