### ISSUE TITLE
gcc problem matcher does not catch fatal errors

### ISSUE THREAD

**Issue by wcscmp** [microsoft/vscode-cpptools#3712]
$gcc problem matcher does not match fatal errors
Possible solution would be:
"regexp": "^(.*):(\\d+):(\\d+):\\s+(?:fatal )?(warning|error):\\s+(.*)$"
It would be great to also catch linker errors, like undefined reference as an errors

**Comment by sean-mcmanus** [comment]
I fixed the fatal error. I don't know of a way to get the linker errors to match, because they don't have a column or severity in the message...well, it's easy to create a pattern that will match with a column/severity omitted, but I don't how to get the problem matcher to match the linker and non-linker styles at the same time.

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").
