### ISSUE TITLE
Not enough info in outline tab for typedefs 

### ISSUE THREAD

**Issue by Iipal** [microsoft/vscode-cpptools#3716]
**Type: LanguageService**

- OS and Version: macOS Mojave (10.14.5)
- VS Code Version: Insiders 1.35.0
- C/C++ Extension Version: 0.23.1

Not enough info in outline tab for typedefs. Typedef for what data type ? Please add more info for typedefs.
<img width="695" alt="Screen Shot 2019-05-31 at 12 37 13 PM" src="https://user-images.githubusercontent.com/31858171/58696994-6c369300-83a1-11e9-8d7f-1856db912583.png">

**Comment by sean-mcmanus** [comment]
The Outline view is not intended to provide detailed type info because it is just meant for navigating to the definition. It is only supposed to show the Name and an icon -- the only reason we added "(typedef)" is because VS Code doesn't currently support a dedicated icon for typedef.

In your example, the target type is short (size_t), but in other cases it could be a long string, which the Outline pane is not designed for.

The expected way to see the typedef info is to hover over Vector (or Go to Def).

**Comment by Iipal** [comment]
@sean-mcmanus Fully agree with you, thanks for answer.
