### ISSUE TITLE
I can't compile Visual Studio in linux. 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3745]
I have added sqlite and zmq libraries. The code I wrote with zmq works when I compile it on the console. but the same code is not compiled in visual studio.  I'm leaving a picture of the error. I'll be happy if you can help me. thank you for giving a time.

![IMG-20190531-WA0002](https://user-images.githubusercontent.com/38009153/59152235-bcb88b00-8a48-11e9-839b-e1370b953262.jpg)

**Comment by pieandcakes** [comment]
The error you are getting is a debugging error which is saying that it is expecting for `gdb` to start the program `/home/utku/Desktop/.vscode/launch` but it can't find that executable. What program are you trying to debug? If it is `launch` can you run `file launch` in that directory and tell me what it says?

If you are trying to compile the code, I need to see your `cpp build active file` task which should be in your `.vscode/task.json` file. @bobbrow 
 or @sean-mcmanus might be able to help more in knowing why you can't compile but I want to confirm if your issue is debugging your code or compiling it.
