### ISSUE TITLE
For Qt includes, it's always report  message: 'Include file not found in include directory'

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cpptools#383]
```
#include <QJsonArray>
#include <QFile>
#include <QJsonDocument>
#include <QDateTime>
#include <QCoreApplication>
```
severity: 'Info'
message: 'Include file not found in include directory'
at: '5,1'
source: ''

**Comment by bobbrow** [comment]
Does your code file have all those blank #includes?  Can you share a small repro file with us to help investigate?

**Comment by lygstate** [comment]
the qt header file does not have .h suffix， when vscode do auto complete， it's can not handling it properly

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug on Linux (although I am able to repro some other bugs). What is the exact QT header you are trying to include and what version of QT are you using and what folder are you opening? I'm seeing the headers are found like QList, QHash, etc., but the files.associations is not properly recognizing the file as C++ (seems like a VS Code bug, which stopped reproing after I copied the files.associations to my user settings) and even when qlist.h is included, the contents are not being parsed correctly, I believe due to the macros that QT uses, so the autocomplete list is missing stuff.

**Comment by lygstate** [comment]
maybe its fixed， I am testing under win32

**Comment by sean-mcmanus** [comment]
Yeah, we can re-open this if you're stilling hitting an issue...I remember we did install QT and fixed some bug a few months ago, but my trial license expired :(
