### ISSUE TITLE
Can't parse envFile

### ISSUE THREAD

**Issue by HyPNOTIQ** [microsoft/vscode-cpptools#3836]
Type: Debugger

- OS and Version: Windows 10 1809
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.23.1

"envFile" does not work if set path using variable substitution. "${workspaceFolder}/.env" results in "Can't parse envFile ${workspaceFolder}/.env". Works fine if set absolute path without variable substitution.

**Comment by pieandcakes** [comment]
@WardenGnaw Assigning to you. Is there a way to support sending each string to VS Code for variable parsing?

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.24.0-insiders3 . Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install the latest Insiders vsix. Or if that doesn't work (such as in the remote scenario), manually download and install the vsix that matches the target OS.
