### ISSUE TITLE
Question: intelliSense Cache

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3853]
Hi

1. If I set intelliSenseCacheSize=0, which function will be slower than before? Such as auto-completion, go-to-definition or colorization?

1. I noticed that every time I open or switch a file, the flame will occur on the right of status bar. I think cpptools is parsing something. it's right? what's parsed on this time? It's possible to stop parsing file or when you open code folder first, cpptools can parse all code file totally so that no need to parse again when open files .

**Comment by sean-mcmanus** [comment]
The initial creation of the TU will be slower, as well as any update that involves a change that visible in a global scope affecting the entire TU, e.g. edits outside of a method, as well as any time the active document changes (because we want to ensure a clean parsed state). Auto-complete in a function/method, go to def, and colorization generally aren't affected, unless the operation is blocked by a previously mentioned parse operation. The amount of speed up is the amount of time it takes to reparse the headers.

Open/switch parses the entire TU unless the cache is used. The cache doesn't cache the source file. Theoretically, it might be possible to avoid parsing in more scenarios where there are no edits, but that hasn't been implemented in Visual Studio either. I could convert this to a feature request if you want.

**Comment by Lennon925** [comment]
> The initial creation of the TU will be slower, as well as any update that involves a change that visible in a global scope affecting the entire TU, e.g. edits outside of a method, as well as any time the active document changes (because we want to ensure a clean parsed state). Auto-complete in a function/method, go to def, and colorization generally aren't affected, unless the operation is blocked by a previously mentioned parse operation. The amount of speed up is the amount of time it takes to reparse the headers.
> 
> Open/switch parses the entire TU unless the cache is used. The cache doesn't cache the source file. Theoretically, it might be possible to avoid parsing in more scenarios where there are no edits, but that hasn't been implemented in Visual Studio either. I could convert this to a feature request if you want.

OK. Thanks for your reply!
I think if avoid parsing in scenarios where there are no edits or change,it will be faster than before. I hope this feature can be convert to a feature.

**Comment by Lennon925** [comment]
Is it possible that after opening code folder first time cpptools parse the whole code files and store results, if no code change, cpptools can get results from results stored before. When code changed, re-parse related code files and update their results to db.

**Comment by sean-mcmanus** [comment]
It's "possible" but it would probably be a "major work item" and something that we would want to have the VS team implement in our shared low level parsing code, i.e. we'd file a feature request at https://developercommunity.visualstudio.com/spaces/62/index.html . My assumption is that they haven't done that because they expect users to edit the files and the open/activeDocChange scenarios are expected to be fast with reasonably sized code files, so the additional caching hasn't been a high priority.
