### ISSUE TITLE
renaming a variable renames all occurrences of its name

### ISSUE THREAD

**Issue by fraenky8** [microsoft/vscode-cpptools#386]
Want to rename the variable `app`, put cursor in it, pressed `ctrl`-`F2` and all occurrences are marked. See picture before and after renaming.

![before_renaming](https://cloud.githubusercontent.com/assets/4038800/20902138/1a070258-bb36-11e6-96df-c361fcddd908.PNG)

![after_renaming](https://cloud.githubusercontent.com/assets/4038800/20902139/1a07312e-bb36-11e6-978e-16114d1177eb.PNG)

![vsc_info](https://cloud.githubusercontent.com/assets/4038800/20902265/a727e99a-bb36-11e6-8095-97aff18a8f25.PNG)

installed extensions: Atom One Dark Theme, C/C++, cpp-symbols, Simple Icon Theme, Visual Studio classic icons, Visual Studio Dark Theme, VSCode Great Icons, vscode-icons

OS: Win10 x64

**Comment by sean-mcmanus** [comment]
This is "by design". Change All Occurrences is a feature of VS Code and our extension doesn't have any effect on this and it repros for other languages.

**Comment by BillDenton** [comment]
So this is a text search rather than variable search.  The documentation at https://code.visualstudio.com/docs/getstarted/keybindings  and keybinding name (editor.action.changeAll) makes this reasonably clear. 
Although this is useful function, a full variable/function/etc rename is required. However, this requires full reference search/Intellisense.  Hopefully this will arrive with full Intellisense.
