### ISSUE TITLE
C++ syntax highlighting

### ISSUE THREAD

**Issue by steamprodz** [microsoft/vscode-cpptools#3862]
**Type: LanguageService**

**Describe the bug**
- OS and Version: CentOS Linux release 7.3.1611
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.24.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): austin.code-gnu-global, jcmordan.mark-as-excluded, teabyii.ayu, thewolfs.cppcolorizationupgrade, ms-python.python
- A clear and concise description of what the bug is.
Shortly after start of VSCode, the extension colorizes the code and everything becomes of the same color. For example, with this extension disabled, variables' names are black (Solarized Light color theme). With this extension enabled, variables' names (and most of the code) become blue. **_When I used this plugin a month ago and before that, there was no such issue._** Now I can get rid of it only by disabling the plugin, which is inconvenient since it also provides code navigation.

**To Reproduce**

![a_bad_colorization](https://user-images.githubusercontent.com/9977075/60420347-cec0c000-9be7-11e9-92e0-bf38433cd624.png)
![b_good_colorization](https://user-images.githubusercontent.com/9977075/60420348-cec0c000-9be7-11e9-8238-2d43ae89a353.png)

c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/opt/b64/packages/base-12.1.0/include/",
                "/opt/b64/qt5/qt5-5.9.1/include/"
            ],
            "defines": [],
            "compilerPath": "/opt/b64/gcc/gcc-6.2.0/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "gcc-x64",
            "compileCommands": "${workspaceFolder}/build_qt5/compile_commands.json"
        }
    ],
    "version": 4
}

**Expected behavior**
Previously highlighting was not changing the color of all the code. Therefore, I expect to see normal highlighting.

**Screenshots**
There are two screenshots: a) plugin enabled - a lot of blue colorization; b) plugin disabled - normal colorization.

**Comment by bobbrow** [comment]
Thank you for your issue report.  This is actually the expected behavior.  Your theme has colors for user-defined types and variables, but the regex parser used previously couldn't identify them all.  We have now added a layer on top of this that correctly identifies the tokens in your code.

You have a few options as to how to work with this:
1. Disable the new colorization by setting the `"C_Cpp.enhancedColorization"` setting to `"Disabled"`.  This will give you the old behavior.
2. Check out [this documentation](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/colorization.md) that will teach you how to customize the colors to your liking.  We support many more token types than we did previously.
