### ISSUE TITLE
Incorrect squiggles after changing struct definition in header file

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#3883]
Using the following code as the starting point, you can get IntelliSense to tell you that type T cannot be assigned to type T if you change the definition of type T in the header file.

**1.h**

```
namespace N
{
    class C
    {
    public:
        struct Inner
        {
        };

        C();

    private:
        Inner m_inner;
    };
};
```

**1.cpp**

```
#include "1.h"

using namespace N;

C::C()
{
    m_inner = Inner{};
}
```

The way I repro this is by opening both files in the editor, adding some fields to `struct Inner`, and then switching focus to 1.cpp.  At that point, I get a squiggle on the equals sign telling me the assignment can't be done.

It repros with AutoPCH disabled, it does not repro in VS nor if the class is defined outside of the namespace (as far as I can tell).  It's not 100% repro, but it does appear quite frequently.  Just keep adding/removing fields in the struct and some combination of saving/not saving the header file after the edits will repro the issue.

**Comment by Colengms** [comment]
I think the error message and the code involved might not be related to the issue.  If I view these 2 files side-by-side, and type "i" within the Inner struct, I see this error on the assignment.  If continue editing until in a valid state, the error goes away.  On rare occasions, the error remains, but goes away after another edit.  I think the issue might be a race between edits and applying of received squiggles, in which we think the squiggles are up to date and they are not, or otherwise fail to process a request for new squiggles after the last edit.

The odd error message does repro in VS, if the members of Inner are invalid.

**Comment by TheJCAB** [comment]
I originally reported this, and the way it happens sometimes, it seems like no amount of edits will disuade the squiggles (and the nonsensical errors) from going away.

Today, for instance, I've been looking for over an hour (while I was editing the file) at a number of errors that say <Argument of type "A *" is incompatible with parameter of type "A *">. In this case, I didn't even modify struct "A" at any point.

It does look like some sort of race condition as stated is in play, where Intellisense accepts an analysis that was performed on now-stale source code, and the analysis persists until... something causes Intellisense to redo the analysis.

It also does look as if Intellisense is doing partial/incremental analysis, and sometimes, somehow, source changes that should obviously cause the analysis to be redone don't, which results in errors becoming "sticky" with no obvious way to get rid of them.

I haven't found a way to provoke any of this, but I see it happen with regularity.

**Comment by Colengms** [comment]
There may be multiple issues here.  The nonsensical error message does occur in VS, and appears to be related to fragment parsing.  I opened the following issue against VS:

https://developercommunity.visualstudio.com/content/problem/714374/intellisense-error-unable-to-assign-type-to-own-ty.html

That issue is transient, as it gets cleared up as soon as a full parse occurs (merely clicking on another file, or activating/deactivating the window).  It's possible the error could linger if a full reparse takes a long time, or results in another IntelliSense failure.  But, I don't think it would be the cause of persistently stale IntelliSense.

**Comment by Colengms** [comment]
I'm fairly confident this issue is covered by [this](https://developercommunity.visualstudio.com/content/problem/714374/intellisense-error-unable-to-assign-type-to-own-ty.html) VS issue.  It's related to fragment parsing, and a reparse of the TU causes the squiggle to resolve itself.  It does repro in VS, however VS will reparse the TU more aggressively than we do in VS Code.

**Comment by sean-mcmanus** [comment]
@Colengms The linked VS issue was marked "by design". Should this issue be closed?

**Comment by Colengms** [comment]
@sean-mcmanus The issue is definitely not by design.  Rather, Russell seems to have punted it because it's less offensive in VS (due to more frequent full parses), and has not provided sufficient guidance for us to address it.  I've followed up with multiple people, including Jim, and so far have not been unable to uncover what we are expected to do differently to cause a reparse at the right time to resolve the 'bug' that occurs with the fragment parse, without incurring a ton of unnecessary full reparses...

**Comment by sean-mcmanus** [comment]
This is a bug with our stuff -- it repros with
```
        struct Inner
        {
            int i;
        };
```
And deleting the ';' and adding it back, and then switching documents and cursor positions inside methods in both files.

It's not an issue with temporary results (or the issue with temporary results is a different issue).

**Comment by Colengms** [comment]
@sean-mcmanus I'm not sure what you're referring to specifically, but the issue I opened against VS repro's in VS.  And, IntelliSense should probably not ever generate an error that indicates `type A cannot be assigned to type A` (assuming there is a non-deleted assignment operator).

**Comment by sean-mcmanus** [comment]
It does generate that error, seemingly correctly, when there's no semi-colon -- that is considered "by design" due to the incompleteness of the statement. However, I'm seeing a bug AFTER the semicolon is added, as if an old document is being used to generate errors.

**Comment by sean-mcmanus** [comment]
@TheJCAB We believe this is fixed https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 . If you're still seeing an issue, your root cause could be different, so we'd need more repro info.
