### ISSUE TITLE
VSCode will crash when opening this cpp file

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-cpptools#3890]
```cpp
int init() {
   return (0);
}

int deinit() {
   if (WriteDebugLog) Print("************************** Deinitialization **************************");
   return (0);
}

```
[2.cpp.zip](https://github.com/microsoft/vscode-cpptools/files/3365815/2.cpp.zip)

**Comment by matter123** [comment]
@kzhui125 This should be fixed in the upstream textmate grammar with version v.12.15 of marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax.

if you want the changes immediately, install the Better C++ Syntax extension.
if you're okay with waiting a few days, you can use the VS Code Insider's release.
if you're okay with waiting a while, the changes will eventually be pulled into VS Code stable.

**Comment by kzhui125** [comment]
@matter123 
Thanks.
