### ISSUE TITLE
Stability about Cpptools behavior

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3892]
Currently cpptools behavior is not stable and it depends on configuration in c_cpp_properties.json. If I have set compile_command.json, its behavior is better and more stable. But in many cases, I have no the compile_command.json or project folder lacks of some header files, maybe codes can't compile correctly.
You can download linux source code in window and you will find cpptools have some obvious errors, especially "go to definition" and “Error Squiggles”.
In some cases, "go to definition" goes to wrong position. In some cases, it shows wrong error squiggles but it can go to definition correctly. I can't list all scenarios here, I think you can test in the linux source code which is located on [https://github.com/torvalds/linux](url)

**Comment by sean-mcmanus** [comment]
Do you mean the IntelliSense state becomes incorrect after making edits? Or do these issues happen without any edits? Do you know if the stability got worse at a certain release? Is this with the IntelliSense caching enabled or disabled? (e.g. we have seen some cases of cache corruption, see https://developercommunity.visualstudio.com/content/problem/627568/ipch-issue-after-file-moverename-intellisense-colo.html ). We have seen some problems after edits with our internal testing.

**Comment by Lennon925** [comment]
> Do you mean the IntelliSense state becomes incorrect after making edits? Or do these issues happen without any edits? Do you know if the stability got worse at a certain release? Is this with the IntelliSense caching enabled or disabled? (e.g. we have seen some cases of cache corruption, see https://developercommunity.visualstudio.com/content/problem/627568/ipch-issue-after-file-moverename-intellisense-colo.html ). We have seen some problems after edits with our internal testing.



> Do you mean the IntelliSense state becomes incorrect after making edits? Or do these issues happen without any edits? Do you know if the stability got worse at a certain release? Is this with the IntelliSense caching enabled or disabled? (e.g. we have seen some cases of cache corruption, see https://developercommunity.visualstudio.com/content/problem/627568/ipch-issue-after-file-moverename-intellisense-colo.html ). We have seen some problems after edits with our internal testing.

It has nothing with making edits. I think you can download linux source code and test this on it. There are many wrong scenarios. If your code can't be compiled correctly, some strange behivours occur. I think you should test linux source code project as much as possible and you will find these behivours unexpected.

**Comment by Lennon925** [comment]
Linux source code is using utf-8 and this issue is not related with encoding

**Comment by Colengms** [comment]
Hi @Lennon925 .  Can you provide a few repro scenarios?  Or, perhaps some screenshots?

I've cloned the Linux repo, set compilerPath to MinGW, and set intelliSenseMode mode to gcc-x64.  I am seeing various squiggles due to platform headers that aren't available (i.e. arpa/inet.h) and some headers that appear to be generated at build time.  Because of that, I'm seeing a lot of missing types and defines.  But, so far, I haven't been able to catch anything unexplainable.

You may be seeing some issues due to incomplete tag parsing.  Due to the huge number of files, and some huge individual files, tag parsing takes a very long time.  I'm seeing several minutes spent on inidividual files with >70K lines.  Features that rely on tag parsing may not have all symbol available, if tag parsing is not complete.

I've not yet been able to repro issues with Go To Definition leading to the wrong location.

I'll definitely include the linux repo in future testing.

**Comment by Colengms** [comment]
Hi @Lennon925 .  With recent versions, has this started working reliably for you?  As I mentioned above, I don't have repro's for specific issues.  If this is not actionable, I'd like to close it.  Thanks.
