### ISSUE TITLE
Symbol search not working

### ISSUE THREAD

**Issue by nimrod1802** [microsoft/vscode-cpptools#3900]
Just installed and configure VSCode with the cpptools on MAC (VSCode version 1.36.0).  
The symbol search (⌘T) does NOT work (the list is always empty).
The "Quick open" (⌘P) and "Go to definition" (F12) features work.  

Any suggestions?

Thanks!

**Comment by sean-mcmanus** [comment]
It's working for me. What is special about the variable you use for symbol search? Symbol search won't work on local variables (Go to Def will). Is this is a regression from 0.23.1? (it is unlikely since we didn't intentionally change code in that path).

Do you see any errors in the [debug log](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md).?

Does this repro with a simple file with just a `void main(){}` doing symbol search on the main?

**Comment by nimrod1802** [comment]
Installing ctags solved the problem. Thanks!
