### ISSUE TITLE
Code highlighting is incorrect in c/c++ 0.24.0

### ISSUE THREAD

**Issue by zhen8838** [microsoft/vscode-cpptools#3917]
Type: General
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: 18.04.1-Ubuntu
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.0
- Other extensions you installed (and if the issue persists after disabling them): 
    Chinese, one dark pro
- A clear and concise description of what the bug is.  
    When I use the latest plugin version, all my variables are rendered to red by default.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. install vscode
2. install c/c++ 0.24.0

**Expected behavior**

Variable highlighting should be correct

**Screenshots**

### When install c/c++ 0.23.1 , the c source code highlight is correct.

![](https://i.ibb.co/H2RV4cY/Screenshot-from-2019-07-12-10-12-43.png)

### When install c/c++ 0.24.0 , the c source code highlight is incorrect.
![](https://i.ibb.co/rx3DTvZ/Screenshot-from-2019-07-12-10-13-07.png)

**Comment by Colengms** [comment]
Hi @zhdn8838 .  In 0.24.0, we shipped semantic colorization.  https://github.com/microsoft/vscode-cpptools/issues/230  This feature leverages IntelliSense to colorize tokens the syntactic/lexical parser built into VS Code does not.  For example, VS Code does not color class types correctly when used (only when declared/defined).  You are likely seeing unfamiliar colors, but they should be what the theme author intended.  You might try comparing with files in other languages, such as JavaScript, to confirm.  Please let us know if you see otherwise.  You can disable "C_Cpp.enhancedColorization" to restore the original behavior.

**Comment by zhen8838** [comment]
I compare with javascript with c/cpp 0.24.0 they have the same highlight. So I set `C_Cpp.enhancedColorization=false` can solve it.

Thank you very much.
