### ISSUE TITLE
Start Debug Session Without Setting Up launch.json or tasks.json

### ISSUE THREAD

**Issue by zaboyle** [microsoft/vscode-cpptools#3928]
Type: Debugger
**Input information below**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.0

For every project, a new `launch.json` and `tasks.json` need to be created and correctly configured. Is it possible to implement a feature like Visual Studio that simply builds the main file and runs it upon hitting 'debug'? Perhaps behind the scenes it can do the same thing, but just do it automatically. I know myself and many others avoid using c++ in VSCode simply because they do not want to spend the time setting up these two files

**Comment by WardenGnaw** [comment]
Are you looking for a quick and easy way to generate the `tasks.json` and `launch.json` or just not have them at all?

We have `Build and Debug Active File`, which you can get to by right clicking on the *.c or *.cpp file editor page and you should see:
![image](https://user-images.githubusercontent.com/3953714/61237889-57fbea80-a6f0-11e9-998e-7a18e81242b1.png)

By selecting that menu item, it should auto generate those files for you.

For not having the files at all, VS Code does not allow you to compile or debug without them and it is difficult to debug C/C++ without minor property changes in those file due to the various ways C/C++ can be compiled and debugged.

**Comment by zaboyle** [comment]
Thank you, I didn't know about that feature!

I figured it would be difficult to remove the two files entirely, but that feature helps a lot!
