### ISSUE TITLE
Semantic colorization may linger while typing

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#3933]
Semantic colorization (C_Cpp.enhancedColorization, included in 0.24.0) currently extends the text decoration when text is added within or at the end of the range, until an IntelliSense pass has completed.  With large files, this may linger for quite a while. If the IntelliSense process crashes (and we give up restarting it), it will linger indefinitely.

![image](https://user-images.githubusercontent.com/49173979/61339070-f1aac100-a7f0-11e9-8c34-9d9e73b52d1b.png)

Alternatively, we could configure the decoration to not extend when text is added to the end, which could have the effect of not coloring the remainder of a token until the next update.  Some tokens would appear to 'catch up' their color, as new characters are not immediately decorated.

![image](https://user-images.githubusercontent.com/49173979/61339225-a6dd7900-a7f1-11e9-881a-78b47d1a10ff.png)

Ideally, we should end the decoration as soon as the user enters a space, or other character that denotes the end of a token.  This would probably need to be addressed in VS Code, however, as extensions are asynchronously responding to edits which may already show the wrong behavior.

**Comment by lumonix** [comment]
Yea had to switch off semantic colorization because it takes intelli-sense too long to catch up.

I wonder if it would be an option to use the default 'un-semantic' colorization while the user is typing and intelli-sense is still processing, and only use the cpp_tools semantic colorization when intelli-sense has managed to catch up?

I think there is value in having more intelligent colorization, but right now the document tends to be more of a mess until intelli-sense catches up (which can be quite a few seconds for some of our files)

**Comment by Colengms** [comment]
Considering this fixed with https://github.com/microsoft/vscode-cpptools/issues/4992 .  If this scenario still occurs, it would be an issue with VS Code's semantic highlighting support.

**Comment by sean-mcmanus** [comment]
@luminox This should be fixed with 0.29.0.
