### ISSUE TITLE
Intellisense highlights #pragma once as an error

### ISSUE THREAD

**Issue by kurarrr** [microsoft/vscode-cpptools#3952]
I found Intellisense highlights pragma once as an error.
I saw some issues but I couldn't fix it.
Does anyone know the solution?

![image](https://user-images.githubusercontent.com/26420854/61576551-6bef8400-ab16-11e9-9fb3-d97de8984d08.png)

**Describe the bug**
- OS and Version: mac
- VS Code Version: 1.36.0
- C/C++ Extension Version: 0.24.0

**Comment by visstro** [comment]
Sometimes I get the same on some header files. I am using completion based on compile_commands.json, which by design does not provide include directories for headers alone. This sometimes results in errors like this. It can be mitigated by manually adding "includePath" setting as a fallback for "compileCommands".

**Comment by sean-mcmanus** [comment]
If you use C/C++: Log Diagnostics you can see how that header is being compiled with other source files for the translation unit to find out what include files aren't being found.

The squiggle is not intended to be on the `#pragma once` but intended to be a "locationless" error at the start of the file.

**Comment by kurarrr** [comment]
@qneverless @sean-mcmanus 
Thank you for the replies!
As you point out, the error was due to the include path error.
There was include problem in the directory I don't use, and the problem was solved by excluding this from the include path in c_cpp_properties.json.
