### ISSUE TITLE
Disable column wrapping when using 'cout'

### ISSUE THREAD

**Issue by Matze693** [microsoft/vscode-cpptools#3959]
**Type: LanguageService [Question]**

**Describe the bug**
- OS and Version: macOS 10.14.5 (18F132)
- VS Code Version: 1.36.1 (1.36.1)
- C/C++ Extension Version: 0.24.0

**Question**
How can I disable column wrapping when using `cout`?

**To Reproduce**

1. Activate format on save with `"editor.formatOnSave": true`.
2. Create a file with following line
```
cout << "" << "" << endl;
```
3. Save the script.
4. Result is
```
cout << ""
     << "" << endl;
```

**Expected behavior**

None

**Screenshots**

None

**Additional context**

None

**Comment by sean-mcmanus** [comment]
I'm not sure -- the behavior is coming from clang-format. I don't see an option for configuring that behavior (see https://clang.llvm.org/docs/ClangFormatStyleOptions.html ). If anyone finds a way to stop that breaking from happening, we can update the default settings we use.

**Comment by huww98** [comment]
I'm interested in this. So I did some research on the source code of clang-format. This behavior is the result of the following code.

https://github.com/llvm/llvm-project/blob/b4806822d2d52e0e7a29ba1c15a435e2e97a82e7/clang/lib/Format/TokenAnnotator.cpp#L3007-L3010

So it seems if you write `cout << "abc" << "def" << endl;`, it assume you want to put these two string literals on different lines. And this only happens if you output two string literals in succession. If you don't want this behavior, why not just write `cout << "abcdef" << endl` (concatenate two string literals into one)?

**Comment by Matze693** [comment]
Thank you very much for your research! 😄

Of course to concatenate two string literals is a valid solution in this case. But sometimes I want to output a string and some other object of any type. In this case the `cout` syntax is komfortable, in my option.

Anyway this behavior is coming from clang-format, therefore I`d suggest to close this issue.

**Comment by huww98** [comment]
If you output a string and some other object, i.e. `cout << "abc" << 123 << endl`, clang-format will not break it into two lines. this behaviour is specific to two string literals in succession.

**Comment by Matze693** [comment]
Okay, my mistake, I only tested it with two string literals. :laughing:
