### ISSUE TITLE
Unable to compile program in Win 10 with MinGW

### ISSUE THREAD

**Issue by zhangxm2312** [microsoft/vscode-cpptools#3970]
I had met a bug like what https://github.com/microsoft/vscode-cpptools/issues/1329 mentioned, and I fixed it through change the code in task.json to:
```json
"label": "build",
            "type": "shell",
            "command": "C:/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++.exe",
            "args": [
                "-g",
                "-o",
                "FAIL",
                "FAIL.c",
            ],
```
(fix bugs is like torture, so I used FAIL as file name)
now,
1.how to make the filename in "args" is defined automatically?
2.after that, the powershell cmd returns it to me:
```
> Executing task: C:/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++.exe -g -o FAIL FAIL.c <

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
but I press F5, it sends me that the exe program has not been set up.How to fix it?

Sorry for my improper English and program level, but I am new in VSCode and not familiar with many basic operations, so maybe I will seek help to bugs in preparation of cpp here.

**Comment by pieandcakes** [comment]
@zhangxm2312 `task.json` configuration is handled by VS Code and not our extension. The [documentation](https://code.visualstudio.com/Docs/editor/tasks) for it shows you can use `${file}` and they will resolve it for you. 

I think your issue is that you are using `Mingw` and that your environment has not been configured properly. You will need to add `MinGW`'s `bin` folder to your `PATH` environment variable so it can resolve libraries it needs to compile against.

**Comment by pieandcakes** [comment]
I have updated the title to reflect your problem.
