### ISSUE TITLE
IntelliSense not working with compile_commands.json under linux

### ISSUE THREAD

**Issue by EagleChen** [microsoft/vscode-cpptools#3995]
Type: LanguageService

Describe the bug

OS and Version: centos 7.2
VS Code Version: 1.36.1
C/C++ Extension Version: 0.24.1
Other extensions you installed (and if the issue persists after disabling them): remote-development (0.15.0)

In a large c++ project, `compile_commands.json` is generated using `bazel`. I set the absolute path in "compileCommands" in `c_cpp_properties.json`, and then this extension will try to parse the file but fail to get 'IntelliSense' to work.

The debug output of 'c/c++' is like (this is a private project , so i hide the paths):
![c/c++ debug output](https://user-images.githubusercontent.com/1343797/62023319-ee590180-b202-11e9-86f5-c91549b1ca52.png)

The error message is :
```
#include errors detected. Consider updating your compile_commands.json or includePath. Squiggles are disabled for this translation unit (cpp_file_path).
```

I've no idea which header is missing.

Then I try to debug with the output of 'c/c++ diagnostics':
![c/c++diagnostics output ](https://user-images.githubusercontent.com/1343797/62023659-81466b80-b204-11e9-99c4-31879bd99bb1.png)

I use the include paths in the output to construct a bash command as following:
```
/usr/bin/gcc -Iinclude_path_1 -Iinclude_path_2 ..... -Dxxxx -Dyyyy -c cpp_file -o /tmp/output.o
```
This command can successfully generate a `.o` file. So I suppose the include paths are correct.

How can I see what's wrong with my config file or this extension?

**Comment by michelleangela** [comment]
@EagleChen, the logging you used are good ways to see which include paths are sent to the IntelliSense. Are the include paths shown in the logging the expected ones from the generated `compile_commands.json` file?   If the compile commands database does not contain an entry for the translation unit that corresponds to the file you opened in the editor, then the extension will fallback to using the `includePath` and `defines` in [c_cpp_properties.json](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference).

@sean-mcmanus, are there other logs to help determine the issue in a `compile_commands.json` file?

**Comment by EagleChen** [comment]
@michelleangela 

Are the include paths shown in the logging the expected ones from the generated compile_commands.json file? 
Yes

If the compile commands database does not contain an entry for the translation unit that corresponds to the file you opened in the editor, then the extension will fallback to using the includePath and defines in c_cpp_properties.json.
The file opened is in compile_commands.json.
I have set `includePath` and `browse`.

```
[
{...},
{"directory": "xxx", "commands": "/usr/bin/gcc -Ixxx -Iyyy .....", "file": "full path of the file that I opened"},
{...}
]
```

**Comment by michelleangela** [comment]
@EagleChen 

If the expected include paths are showing up in the logs, then that means `compile_commands.json` is parsed correctly.

If #include errors are detected, the error should also indicate which #include are missing (such as in the example below)
![image](https://user-images.githubusercontent.com/38734287/62155948-e6f72e00-b2be-11e9-98ce-3b5f4f5863d8.png)

Are there any other errors in the Problems window?

**Comment by EagleChen** [comment]
@michelleangela 

No. The error message is:
```
#include errors detected. Consider updating your compile_commands.json or includePath. Squiggles are disabled for this translation unit (cpp_file_path).
```

I don't know which #include are missing.

are there any other logs that I can check?

**Comment by bobbrow** [comment]
If you open (cpp_file_path) from the error message, it should tell you which header it failed to find.

**Comment by EagleChen** [comment]
@bobbrow 

as you can see in the screenshot, all I can get is this error message and it's shown on a comment line:
```
#include errors detected. Consider updating your compile_commands.json or includePath. Squiggles are disabled for this translation unit (this_cpp_file_path).
```

![error screenshot](https://user-images.githubusercontent.com/1343797/62354140-c5a47500-b53e-11e9-8cf7-23ae72a75648.png)

**Comment by bobbrow** [comment]
Yes, that is expected behavior because header files share the same IntelliSense server as the source files that include them.  We put the squiggle there (we don't really have a good spot for it) because the behavior of the header file is being affected by the errors in the source file that includes it.  So if you can please open (this_cpp_file_path) in the editor, you will be able to see which header is causing you problems for the related header files.

Unless you are saying that (this_cpp_file_path) is a bogus file reported by our extension.

We could probably improve the error message if it's causing a lot of confusion.

**Comment by EagleChen** [comment]
@bobbrow 

sorry, I don't quite understand what you mean.

In the previous screen shot, I've already opened that cpp file.  The error can show in this file, but it shows on the third line which is a comment.

There are many headers in this file. No error squiggles show under them.  I could not find out which headers are missing from the error message either.

![image](https://user-images.githubusercontent.com/1343797/62406053-aefe2c80-b5d7-11e9-86c2-b662a68eef31.png)

**Comment by bobbrow** [comment]
Let me try to explain with a screenshot.

![image](https://user-images.githubusercontent.com/12818240/62407052-06b07f80-b567-11e9-996e-f7075560b722.png)

main.cpp has the `#include` error.  main.cpp includes `include.h`.  If you run the `Log Diagnostics` command, you see that these two source files share the same translation unit (aka: IntelliSense server)

![image](https://user-images.githubusercontent.com/12818240/62407071-3b243b80-b567-11e9-8c8d-b95e42d7fa4d.png)

So, even though there are no problems with `include.h`, it is sharing a server that has a problem (`main.cpp`) so the squiggles are disabled for `include.h` too.  You have to open main.cpp to see which `#include` is failing to resolve.  That's what the error message is trying to tell you.

**Comment by EagleChen** [comment]
@bobbrow 

Thanks for your explanation.

As I pointed out in the previous comment, this cpp file is an entry in `compile_commands.json`
```
[
{...},
{"directory": "xxx", "commands": "/usr/bin/gcc -Ixxx -Iyyy .....", "file": "here is the full path of this cpp file"},
{...}
]
```
So maybe it's not the case you described.

But I do find some headers are missing by opening other cpp files, I will further investigate.

Thanks again.

**Comment by echoface** [comment]
same issue here
host: mac os
remote ssh: linux cent os 7.2
compile_commands.json generated by cmake

BTW:
clangd seems work ok

**Comment by sean-mcmanus** [comment]
@HuanGong Can you provide more repro details? Preferably in a separate bug? "IntelliSense not working with compile_commands.json" is a general symptom which could have many different causes.

**Comment by cstrahan** [comment]
I'd like to help with this. @sean-mcmanus what do I need to do to see a log of what `vscode-cpptools` extension is currently doing? E.g. how do I know if it's using the `compile_commands.json` that I specified, rather than (possibly) silently failing?

The competing [`vscode-clangd`](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) extension mostly "just works" (though the Outline support seems a bit broken).

Out of the box, `vscode-cpptools` seems to handle (and present) code analysis much better. _However_, the software I am working on uses Bazel for the build system, so I _must_ use the compile commands (generated via https://github.com/grailbio/bazel-compilation-database), otherwise a whole lot of source files can not be found.

I've tried poking around through vscode for the past hour or so, and I can't find anything that gives me any visibility into what the extension is doing, making debugging impossible.

Sadly, this extension is completely unusable in its current state for working on Bazel projects (at least on Linux; maybe the issue is host-specific).

**Comment by cstrahan** [comment]
I followed [this page](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) to set the language server debug level, and this is what I now see:

```
initialized
cpptools/queryCompilerDefaults: 1
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 10676
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 10700
cpptools/fileCreated
cpptools/didChangeCppProperties
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/clang-7'
terminating child process: 10806
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/clang-7'
terminating child process: 10866
  Folder: /usr/lib/llvm-7/lib/clang/7.0.1/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /home/cstrahan/src/envoy/ will be indexed
cpptools/getCodeActions: 2
textDocument/didOpen
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: 3
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
sending compilation args for /home/cstrahan/src/envoy/source/server/configuration_impl.cc
  include: /home/cstrahan/.cache/bazel/_bazel_cstrahan/ed7d8ee2a14ba629ab893f42297aa5e1/external/com_github_fmtlib_fmt/include
  include: /home/cstrahan/.cache/bazel/_bazel_cstrahan/ed7d8ee2a14ba629ab893f42297aa5e1/external/com_github_gabime_spdlog/include
  include: /home/cstrahan/.cache/bazel/_bazel_cstrahan/ed7d8ee2a14ba629ab893f42297aa5e1/external/com_google_protobuf/src
[...snip...]
```

I see nothing about reading the `compile_commands.json`, so maybe it is being read... or maybe it's not?

The thing that confuses me:

```
  Folder: /usr/lib/llvm-7/lib/clang/7.0.1/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /home/cstrahan/src/envoy/ will be indexed
```

Shouldn't these be ignored, if `compile_commands.json` is being used?

**Comment by sean-mcmanus** [comment]
When you run C/C++: Log Diagnostic with C/C++ file active (after the flame icon disappears), does the info appear to match your compile_commands.json?

The "Folder: ... will be indexed" is for our workspace database. If you see folders missing, you should add them to 
```
"browse": {
"path": [
"${workspaceFolder}",
…
}
```
because we don't generate that correctly from the compile_commands.json (there's an issue tracking that...I think we just use the workspaceFolder and system folders, but not other external folders). Not having that set correctly can cause symbols in those file to be missed for Go to Def or Find All References.

We've had other Bezel users (I don't recall them being blocked, but there were issues reported).

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
