### ISSUE TITLE
GCC problem matcher doesn't appear to work with Remote SSH

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-cpptools#4073]
I am using an out-of-tree build using RemoteSSH extension (SSH from Windows to a Linux box). The contents of my build command are roughly the following:

```
                {
                        "label": "Build",
                        "type": "shell",
                        "command": "make",
                        "args": [
                                "-C",
                                "${workspaceFolder}/../build/${workspaceFolderBasename}"
                        ],
                        "problemMatcher": ["$gcc"],
                        "group": {
                                "kind": "build",
                                "isDefault": true
                        }
                }
```

This matches, but the path appears to be wrong:

![ProblemMatcher](https://user-images.githubusercontent.com/37181601/62948761-e68d8580-bddc-11e9-9e47-8fae925f9524.PNG)

The paths i'm getting from the terminal look like `../../<src dir>/path/to/src.c`. Extending the problem matcher also doesn't fix the issue. I've attempted to do this:
```

                        "problemMatcher": [{
                                "base": "$gcc",
                                "fileLocation": [
                                        "relative",
                                        "${workspaceRoot}/../build/${workspaceFolderBasename}/"
                                ]
                        }],
```
This didn't help. I've tried modifying the regex pattern as well:
```

                        "problemMatcher": [{
                                "base": "$gcc",
                                "fileLocation": [
                                        "relative",
                                        "${workspaceRoot}/../build/${workspaceFolderBasename}/"
                                ],
                                "pattern": {
                                        "regexp": "^([^:]+):(\\d+):(\\d+):\\s+(.*)$",
                                        "file": 1,
                                        "line": 2,
                                        "column": 3,
                                        "message": 4
                                }
                        }],
```
The remote is Linux, so `([^:]+)` should match whatever path there is, and "relative" should take care of the base - but this too results in problem matcher reporting match at file `\`, as on screenshot above.

This may be related to #3751 or #2266 as it looks like a similar sort of issue.

**Comment by anatolyburakov** [comment]
This behavior has changed with recent versions: the path gets resolved correctly (it no longer shows up as "/"), but VSCode cannot find it when i try to go to the error, displaying the following error:

```
Unable to open 'eal.c': Unable to read file (Error: File not found (vscode-remote://ssh-remote+7b22686f73744e616d65223a2242616c6c7a227d/home/DPDK/lib/librte_eal/linux/eal/eal.c)).
```

EDIT: actually no, the path doesn't resolve correctly - it seems to resolve the GCC path from source tree, not from build tree (i have an out of tree build).

The path displayed by GCC is:

```
../../DPDK/lib/librte_eal/linux/eal/eal.c: In function ‘rte_eal_config_reattach’:
../../DPDK/lib/librte_eal/linux/eal/eal.c:435:9: warning: unused variable ‘b’ [-Wunused-variable]
  int a, b;
         ^
```

My build tree is under `/home/anatoly/build/DPDK/`, and the source tree is at `/home/anatoly/DPDK`. The path being resolved here is being resolved from the source tree rather than taking into account working directory of the compiler. Is there any way to fix that?

**Comment by sean-mcmanus** [comment]
This seems like a VS Code remote bug? Can you file a bug at https://github.com/microsoft/vscode-remote-release/issues/ ? I could also try to file the bug there for you, but their template is asking for more info:
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

**Comment by anatolyburakov** [comment]
@sean-mcmanus i've created one myself: https://github.com/microsoft/vscode-remote-release/issues/1623

**Comment by yeggles** [comment]
@sean-mcmanus 
I am running into this same issue. From what I can tell the whole issues is the fact that the problemMatcher is adding the "vscode-remote://ssh-remote+" to the front of the file path which I would think is where the file lives that is relative to my Windows PC since it is the one running VS Code. But after the Remote-SSH connection has been made the file path needs to be relative to the VM's directory and not have the "vscode-remote://ssh-remote+" on the front. I don't know who creates the links whether it is the problemMatch (gcc for my case) or remote-ssh, but whomever it is, is the one responsible for the issue.

If I use the following, then "some" of my files will open correctly when I click on the errors because the prefix listed above is not present:

"problemMatcher": { "base": "$gcc", "fileLocation": "relative" }

I say "some" because I am also running into issues where the problem matcher is tracking where my make files lives in relativity to my workspaceFolder. For instance if I had the following workspace structure: workspaceFolder/A/B and inside B there was a Makefile. If I call make on root/A/B/Makefile, then all of the errors that occur due to that call will link to root/B/* and forget that there was an A directory in the path. I hope that all makes sense.

**Comment by yeggles** [comment]
I deleted my comment since this issue appeared to be most relevant to what I am seeing:
[https://github.com/Microsoft/vscode-cpptools/issues/2266](url)

**Comment by anatolyburakov** [comment]
Yes, adding `fileLocation` directive to the problem matcher have fixed the issue for me.
