### ISSUE TITLE
C language development is not friendly enough, and the lookup reference is much worse than Source Insight.

### ISSUE THREAD

**Issue by senlinding** [microsoft/vscode-cpptools#4177]
C language development is not friendly enough, and the lookup reference is much worse than Source Insight.

**Comment by senlinding** [comment]
When there are hundreds of files. Finding is slow and difficult to use. Can't jump directly to the past with only one reference.

**Comment by senlinding** [comment]
Sometimes there are references but no results.

**Comment by sean-mcmanus** [comment]
Can you provide any more repro details? Are you referring just to "Find All References" or other features as well? What does "jump directly to the past" mean?

**Comment by senlinding** [comment]
> Can you provide any more repro details? Are you referring just to "Find All References" or other features as well? What does "jump directly to the past" mean?

Currently only Find All References. 
When looking for only one reference, I want to jump directly to the corresponding file.

**Comment by sean-mcmanus** [comment]
I don't think we can fix this without more specific details.

The closest thing to "jump directly" would be "Peek References" -- is that good enough?

**Comment by senlinding** [comment]
![image](https://user-images.githubusercontent.com/4864830/64791396-3f9e3400-d5aa-11e9-9793-1a5f15c19dc2.png)
Just 20 files, it took 5 seconds to peek references

**Comment by senlinding** [comment]
> I don't think we can fix this without more specific details.
> 
> The closest thing to "jump directly" would be "Peek References" -- is that good enough?

Peek References is really slow.

**Comment by senlinding** [comment]
> I don't think we can fix this without more specific details.
> 
> The closest thing to "jump directly" would be "Peek References" -- is that good enough?

Describe the bug

OS and Version: win10
VS Code Version: 1.38.1
C/C++ Extension Version: 0.25.1
Other extensions you installed (and if the issue persists after disabling them):
Disable other extensions, bug still exist

**Comment by senlinding** [comment]
Hope to optimize Peek References.

**Comment by sean-mcmanus** [comment]
Even with a small number of files in a workspace, the confirmation process usually has to compile the target files in order to "confirm" the reference, which can take a few seconds if the target file isn't open already. What does the status bar UI show? i.e. how many files is it searching and then confirming? We're tracking performance improvements with https://github.com/microsoft/vscode-cpptools/issues/4051 .

**Comment by bobbrow** [comment]
I cloned the repo and did Peek References on `wav_header`.  Like @sean-mcmanus says, it's fast if the files to confirm are already loaded.

![minimp32019-10-1010-08-58](https://user-images.githubusercontent.com/12818240/66590792-666a6e80-eb46-11e9-8fe9-01b163687066.gif)

If I add an additional reference in a new file, it slows down because we have to compile that extra file.

![minimp32019-10-1010-15-02](https://user-images.githubusercontent.com/12818240/66591212-48e9d480-eb47-11e9-9cb9-298b089762da.gif)

We're tracking improvements to this in #4051 like @sean-mcmanus said.
