### ISSUE TITLE
Intellisense partially works

### ISSUE THREAD

**Issue by lattice0** [microsoft/vscode-cpptools#4191]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.37.1
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them): no extra entensions
- A clear and concise description of what the bug is.

The Intellisense rarely works. Sometimes I just open vscode and it works, but the majority of times don't. I see no colors aside from the ones vscode alone does, and see no errors at all (no undefined variable errors for example, no wrong return types, etc).

**To Reproduce**

I'm using a newly update vscode, I don't know how to reproduce, it simply won't work
**Expected behavior**

Show C++ errors and color things
**Screenshots**

https://imgur.com/a/oJf1nli

**Additional context**

I also tried changing from default to gcc but it didn't work

**Comment by lattice0** [comment]
Nevermind, it looks like when there's one simple include error, the intellisense won't interpret the .cpp file at all

**Comment by Colengms** [comment]
Hi @lucazanella .  There is a setting for this: "C_Cpp.errorSquiggles".  By default, it's set to "EnabledIfIncludesResolve".  If you change this setting to "Enabled", it will show error squiggles even if includes do not resolve.  Though, since preceeding code was not found, there could potentially be a lot of squiggles.
