### ISSUE TITLE
If `compileCommands` is being used, then `defines` is ignored

### ISSUE THREAD

**Issue by smoofra** [microsoft/vscode-cpptools#4248]
**Type: LanguageService**

- OS and Version: Mac OS 10.15
- VS Code Version: Version: 1.38.1
- C/C++ Extension Version: 0.25.1

**Description**

If you are using `compileCommands`, then the language service ignores `defines`.

**To Reproduce**

`foo.c`:
```c
void foo() 
{
#if !VSCODE
    #error "VSCODE is not defined!"
#endif
}
```

<br>

`.vscode/c_cpp_properties.json`:
```json
{
    "configurations": [
        {
            "name": "Mac",
            "compilerPath": "/usr/bin/clang",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "/Users/lawrence_danna/Desktop/foo/compile_commands.json",
            "defines": ["VSCODE=1"]
        }
    ],
    "version": 4
}
```

<br>

`compile_commands.json`:
```
[
{
  "directory": "/Users/lawrence_danna/Desktop/foo",
  "command": "/usr/bin/clang -o /Users/lawrence_danna/Desktop/foo/foo.o -c /Users/lawrence_danna/Desktop/foo/foo.c ",
  "file": "/Users/lawrence_danna/Desktop/foo/foo.c"
}
]
```

<br>

1. make a workspace with those files.
2. the `#error` will show up in "Problems"

**Expected behavior**

The `#error` should not show up in problems because VSCODE should be defined.   If you remove the `compileCommands` line, the error goes away.

**Additional context**

Related problem: https://github.com/microsoft/vscode-cpptools/issues/4246

It would have been a useful workaround for that problem to define VSCODE in `c_cpp_properties.json`, and then ifdef out the troublesome lines based on that.    But I can't because it's incompatible with `compile_commands.json`.

**Comment by sean-mcmanus** [comment]
You can #ifdef stuff out with `__INTELLISENSE__`. Does that work as a workaround?

Ignoring "defines" when compile_commands.json is used is "by design" since the defines are expected to come from the compile_commands.json instead (except for files that are missing from the compile_commands.json, which fall back to the c_cpp_properties.json settings).

**Comment by smoofra** [comment]
That does work as a workaround.    If the behavior is by design, maybe there should be an error if you try to use "defines" and "compileCommands" at the same time?

**Comment by sean-mcmanus** [comment]
We can't tell if the defines in c_cpp_properties.json are intentional or not, because they are used in the cases where files are not included in the compile_commands.json...so I don't see how we could give an error or warning. i.e. we could add the warning, but then users who intentionally want the defines to be used as a fallback will get warned all the time, unless we added a separate setting like "definesFallback" to reduce the potential confusion.

**Comment by smoofra** [comment]
Ah, yea that makes sense.  Thanks.
