### ISSUE TITLE
C/C++ Find All Reference can't ignore the excluded folders

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#4262]
I have exclude one  folder(/files) of my workspaceFolder,
    "files.exclude": {
        "**/Boards/": true
    },
but the "find all references" still show the refs of  code in the exclude folder.

**Comment by sean-mcmanus** [comment]
It should work if you remove the "/" from the end of your exclusion pattern.

Using "/" in your pattern causes our code to treat the pattern like a file exclusion instead of a folder exclusion (which could be a bug), and by default, file-based exclusions are disabled for our language service features due to the performance impact -- you could also change the C_Cpp.exclusionPolicy to checkFilesAndFolders.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders . Let us know if it's not working for you.

**Comment by heartacker** [comment]
> The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders . Let us know if it's not working for you.

Hi, after Manual installation  and "Rescan C/C++ intellisense data". IT WORKS 👍

**Comment by ludishur** [comment]
It works fine if I exclude it from the user tab.
But, folders added to "files: exclude" in the remote and workspace  continue to be searched.
I use version 0.26.2

**Comment by sean-mcmanus** [comment]
@ludishur I am not reproing the issue you are describing -- setting files.exclude on the remote/workspace settings is working to exclude references. Did you try doing a Reset IntelliSense Database command?

**Comment by ludishur** [comment]
Thank you for reply.
 I did reset Intellisense database many times. Set workspace exclude, reset
intellisense database. Set user exclude, resst it again.
But still it searched in exclude path.


2019년 12월 21일 (토) 09:39, Sean McManus <notifications@github.com>님이 작성:

**Comment by sean-mcmanus** [comment]
And your exclude string works when it's used in the user setting? i.e., it's some issue with the remote/workspace setting and not the parsing of the exclude string, right? I don't know how we could be incorrect here, because we just call into the VS Code getConfiguraiton API at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/settings.ts#L127 (called from https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/client.ts#L899 ). I don't think we'll be able to fix this without a repro, but if you could clone our repo and debug that line yourself, then maybe you could report a bug to VS Code if the API is returning the wrong result for some reason. You're repro is with a workspace open and not just open file, right? It looks like you'll have to do a Reload Window after changing the files.exclude as well.
