### ISSUE TITLE
Unable to open cpp file when debugging

### ISSUE THREAD

**Issue by CfirTsabari** [microsoft/vscode-cpptools#4264]
Type: Debugger

**Describe the bug**
- OS and Version:
OS Name:                   Microsoft Windows 7 Ultimate
OS Version:                6.1.7601 Service Pack 1 Build 7601
- VS Code Version:
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
- C/C++ Extension Version:
Version 0.25.1: August 28, 2019
- GCC version
g++ (GCC) 9.1.0
- gdb version
GNU gdb (GDB) 8.2.1

When debugging an exe created by gcc after adding breakpoints to file the cpp file won't be found and you won't be able to see the breakpoints stopping.
according to the logs the breakpoint get hit but a pop up saying that the file doesn't exist.

1. build a cpp file using msys2 g++(tester file attached)
    g++ tester.cpp -o tester.exe -g
2. configure launch.json(attached)
3. add breakpoints
4. debug(F5)

The popup text:
`Unable to open 'tester.cpp': Unable to read file (Error: File not found (\c\test\tester.cpp)).`
when clicking create file the a file get created,the file path is :`"C:\c\test\tester.cpp"`

this is json file [launch.txt](https://github.com/microsoft/vscode-cpptools/files/3623277/launch.txt)
this is cpp file :[test.txt](https://github.com/microsoft/vscode-cpptools/files/3623280/test.txt)
[debug_console.log](https://github.com/microsoft/vscode-cpptools/files/3623281/debug_console.log)

**Comment by pieandcakes** [comment]
@CfirTsabari I don't know why your compiled symbol file has the wrong path. We get `\\c\\test\\tester.cpp` back from gdb and i assume that you need `c:` and not `\c\`. 
You can try and set a `"sourceFileMap"` mapping `\c\` to `c:\` and see if that fixes your problem. Otherwise you'll have to see why your toolset is compiling the directory paths wrong into the symbols.
