### ISSUE TITLE
Allow stepping from C# to C++ and vice versa when debugging

### ISSUE THREAD

**Issue by ddobrev** [microsoft/vscode-cpptools#4328]
I have a solution with both C# and C++ projects, the C# project invokes C++ code with P/Invoke. I want to be able to step in and out of the C++ code when debugging, just like Visual Studio can.

**Comment by pieandcakes** [comment]
@ddobrev You would need a VS Code debugger extension that can debug c++ and C#. This extension only supports C++.

**Comment by ddobrev** [comment]
@pieandcakes seriously? Really? How the hell is VS Code generally held in high regard if this is the way you "work" around here? [I reported the issue to VS Code itself first](https://github.com/microsoft/vscode/issues/81405) and the person "responsible" over there did absolutely nothing whatsoever but send me here without even making the effort to post the issue himself. Now you do identically the same, just in the opposite direction. Why is bug reporting in either project even allowed to begin with if this is the kind of attention you pay to people who cared enough for your product in order to make suggestions for improvement? Am I at all supposed to raise my concerns if you (as in all teams related to VS Code) do nothing but alleviate responsibility to each other in a doomed circle?

**Comment by pieandcakes** [comment]
I'm not sending you back to VS Code. I can take this as a Feature request but in all honesty, this is a `C/C++` extension and not a `C# and C/C++` extension so it isn't something that we will implement. I didn't mark it as a feature request because I don't want to mislead you. 

You are saying that you are reporting a bug but this isn't a bug. You are looking for an extension to fill the gap to provide both experiences and my comment explained what needs to happen. You are looking for someone to create an extension for you, which is fine, but that is not within the scope of what this extension is. 

I don't know the right place for you to suggest a new extension to cover this area but our issues page is not it. As for why VS Code pointed you here, I don't know why they did it as this is clearly a C++ extension.
