### ISSUE TITLE
Go to definition always open find all references

### ISSUE THREAD

**Issue by tinganho** [microsoft/vscode-cpptools#437]
I find it annoying when I <kbd>CMD</kbd> + <kbd>click</kbd> a reference, I go to declaration. But it always open up find all references window:

<img width="630" alt="screen shot 2017-01-08 at 12 51 18 pm" src="https://cloud.githubusercontent.com/assets/1324476/21749566/69930580-d5a1-11e6-9d07-913ba581445d.png">

I'm using other programming languages in vscode and they don't behave this way. They just go to definition and that's it.

**Comment by sean-mcmanus** [comment]
This is “by design” behavior. Whenever there are > 1 matches for a goto request, it shows a peek with all the matches on the right and a preview on the left (like a peek). This might be annoying when the 1st definition is the correct one, but the alternative would be not being able to navigate to the correct definition. And due to lack of access to the build system, we can’t be sure which is the correct definition. There isn’t any way to change this from our extension, other than always returning 1 result, even for a peek, which isn’t good. Maybe the VS code team could design a better interface for this that is less confusing/annoying. Also, if we can get access to the build system in the future, such as via processing cmake files, then we could show 1 result. It is not opening the Find All References window. It shows all the possible definitions, and we can't tell which is the correct one, so you can look through them to see which is the one you want, or just close the peek window if you want to keep the 1st one.

**Comment by tinganho** [comment]
@sean-mcmanus There is only one definition though. Clicking on the second file, it becomes a zero instantly:

![jan-09-2017 20-18-20](https://cloud.githubusercontent.com/assets/1324476/21779642/cef383e8-d6a8-11e6-8ea2-3d2912fa3093.gif)

**Comment by sean-mcmanus** [comment]
Yeah, it looks like the 1st item should not be there (or is missing). I'm interested in a repro, since I haven't seen that before. Can you expand the "Comma..." so I can see it says? The "Comma..." text is the file name, so it looks like it thinks there are 2 files with the same definition in it, but it's not actually there.

**Comment by tinganho** [comment]
Hmm, I renamed the folder `Source` to `src`:

<img width="640" alt="screen shot 2017-01-09 at 9 03 23 pm" src="https://cloud.githubusercontent.com/assets/1324476/21781371/5849a61c-d6af-11e6-8295-38bdea6863f8.png">

I have tried to restart vscode many times and it doesn't seem to remove `Source` folder.

**Comment by sean-mcmanus** [comment]
Yeah, our extension has problems with not always cleaning up the database when changes are made, so it accumulates old stuff. I've successfully reproed the bug. Deleting or renaming the database (databaseFilename property in c_cpp_properties.json) should be a workaround.

**Comment by tinganho** [comment]
How do I delete the database? Or I guess I need to wait for an update?

**Comment by sean-mcmanus** [comment]
The easiest way to delete the database is to rename it to a known location. Or search for the .browse.vc.db file. You shouldn't need to wait for an update (we are not planning to fix this issue by our next update).
