### ISSUE TITLE
Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by barynton** [microsoft/vscode-cpptools#4381]
Type: General
Error: Buffer() is deprecated due to security and usability issues.

- OS and Version: Windows X64 10.0.17763
- VS Code Version: 1.38.1
- C/C++ Extension Version:  0.25.1

Stack trace with NODE_OPTIONS=--throw_deprecation

Error: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
	at showFlaggedDeprecation (buffer.js:160:11)
	at new Buffer (buffer.js:175:3)
	at c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46500:18
	at pendGo (c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46747:3)
	at Pend.module.exports.Pend.go (c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46706:5)
	at ReadStream.module.exports.ReadStream._read (c:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:46498:21)
	at ReadStream.Readable.read (_stream_readable.js:452:10)
	at resume_ (_stream_readable.js:899:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Colengms** [comment]
Hi @barynton .  Are you seeing this at runtime?  Normally I would expect this to be a deprecation warning, not an error.  Note that cpptools does not invoke "new Buffer" anywhere.  However, there are _several_ common dependencies that have not yet addressed the deprecation of new Buffer().

**Comment by barynton** [comment]
Hi @Colengms. Yes you are right, it's a warning. I see it when debugging my extension. Haven't check other cases. I didn't know the source of the problem and I ran debug with --throw_deprecation option and breakpoint on uncaught exceptions, so it was marked as an error.

The main problem was that I didn't know what causes the warning. It looks like "(node:23508) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead." So it's a little bit сonfusing.

**Comment by Colengms** [comment]
Note: The action needed here for cpptools is to upgrade to newer versions of dependencies as they address the issue.

**Comment by sean-mcmanus** [comment]
@Colengms Do you know which dependencies?

**Comment by sean-mcmanus** [comment]
Looks like yauzl->fd-slicer->pend (maybe).

**Comment by tjx666** [comment]
similar error message...
![Snipaste_2019-12-04_16-32-43](https://user-images.githubusercontent.com/41773861/70126327-c4818100-16b3-11ea-8c12-1cf0dd5c8b27.png)

**Comment by tjx666** [comment]
Extension Host
extensionHost.ts:204 (node:6004) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead(node:6004) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

console.ts:137 [Extension Host] (node:18424) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

**Comment by Colengms** [comment]
This is blocked on: https://github.com/andrewrk/node-fd-slicer/issues/3

**Comment by Colengms** [comment]
The module we are using directly is yauzl, which has a dependency on fd-slicer.

**Comment by Colengms** [comment]
Our use of `yauzl` has been reduced to a single use case, where we are extracting a vcpkg database (a 2MB text file) from `VCPkgHeadersDatabase.zip`.  This could easily be compressed/uncompressed another way, such as with `lz-string`.  It's been 4 years since either of those packages were updated.  It's unlikely those will be fixed.

**Comment by sean-mcmanus** [comment]
Wasn't the vcpkg database supposed to be updated occasionally?

There isn't a compressions package that is being actively maintained?
