### ISSUE TITLE
Monaco stylesheet incorrectly overriding Theme colouring

### ISSUE THREAD

**Issue by LoveGlitchCoffee** [microsoft/vscode-cpptools#4410]
Type: General

**Describe the bug**
- OS and Version: MacOXS
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them): Oblivion++, C#, CMake Tools, Clock in Status Bar, Docker, Doxygen Documentation Generator, Emacs Friendly Keymap, GitLens, Markdown, Todo Tree, YAML. Problem persist even with only C++ and Oblivion++ extension enabled.
- A clear and concise description of what the bug is: Monaco stylising is overriding the colour intended by a theme.

**To Reproduce**
1. Install Oblivion++ and C++ extension
2. Disable all other extension
3. Open a reasonably sized C++ project (example [Halley](https://github.com/amzeratul/halley))
4. Open a file
5. Wait for intellisense to finish parsing (flaming icon dissapears)
6. you should see a colour change for quite a lot of things in the file, e.g. namespace resolution.

**Expected behavior**
A clear and concise description of what you expected to happen: Colour should not be overriden after intellisense finish parsing.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/10636469/66493095-5c486180-eaad-11e9-9e63-a09af2b26efa.png)

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by Colengms** [comment]
Hi @ParityB1t .  The colors applied by IntelliSense are due to a feature called 'semantic colorization'.  Theming documentation for semantic colorization can be found [here](https://code.visualstudio.com/docs/cpp/colorization-cpp).  Since semantic colorization requires some new theme 'scopes', it's possible the colors in some themes are not ideal.  You can customize the colors, or disable the feature by setting `C_Cpp.enhancedColorization` to `false`.  Note that the TextMate colors shown in `Inspect TM scopes' (in your screenshot) do not reflect the colors used by semantic colorization.  VS Code's TextMate colorization is solely based on syntax, and is applied first.  Semantic colorization is applied over that layer, using text editor decorations for semantically identified tokens.

**Comment by LoveGlitchCoffee** [comment]
perfect explanation. thank you
