### ISSUE TITLE
switch Header/Source doesn't account for files.exclude

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#4429]
If a header with the same name exists in multiple places in the workspace folder, the extension may not switch to the one you expect.  In the event that you attempt to work around this with the `files.exclude` setting, the extension won't actually take that into account for switch header/source.

Addressing #2635 might also improve this scenario without the need for `files.exclude` support.

**Comment by sean-mcmanus** [comment]
This should be working. How did you repro this? I suppose it could repro if the excluded file somehow ended up in the database when it shouldn't be...in that case, adding an extra exclusion check should fix it.

**Comment by bobbrow** [comment]
The repro is basically the same as #2635.  Just have multiple copies of the same file in different locations in the workspace folder.  Then try to exclude a subtree.

**Comment by Logonz** [comment]
I think i know why this is happening.
I configure files.exclude in the .vscode folder in settings.json.
If i open the folder as a workspace it selects the wrong header when using switch header/source.
But if i instead use Open Folder it selects the correct header and seems to exclude the files from Settings.json.

**Comment by sean-mcmanus** [comment]
Hmm...the files.exclude either applies to the workspace or the workspace folder...I'm not able to repro the bug with a workspace.

I did repro a bug where adding to the files.exclude is not updating the database, which could repro this bug, but doing a Reset IntelliSense Database fixes it.

**Comment by w0utert** [comment]
I have the same problem. Our build system is set up to create a workspace where the source files I'm editing are in a folder hierarchy that is actually symlinked to some other in-tree folder hierarchy containing a git checkout for each of the main components of the build. We do this so we can put every component in its own git repo, for various reasons that don't really matter here.

Now, when I'm editing a source file in lets say sources/component_1/something.cpp, where sources/component_1 is a symlink to repos/component_1, the switch header/source function will always switch to the something.h file in repos/component_1, instead of the one in sources/component_1, even though I explicitly list 'repos' in the files.exclude.  The files.exclude setting completely removes the 'repo' directory from the project explorer (just like I want), but switch header/source still considers the files in there, and even prioritizes them over those that *are* in visible in the project explorer. Obviously the contents of the 'sources' and 'repos' directories refer to exactly the same content on disk, but VS code doesn't recognize this and seems to treat them as completely different files.

This is extremely annoying because I inevitably end up with multiple buffers for the same file, and when making edits these buffers sometimes go out of sync. This happens for example when I execute the build task, which will automatically save one buffer for the file, but doesn't mark the other buffer as written. I've lost work because of this by accidentally reverting the saved filed to the unsaved buffer after building.

Ideally, switch header/source would simply ignore any files if they are in an excluded path, but I can imagine this could upset some other use cases where you only want to exclude stuff from the explorer but still be able to navigate to headers referred from source files (e.g. headers in some third party sources that are also in your build tree). At the very least I would say anything in files.exclude should be de-prioritized if there are multiple header/source matches. Some added intelligence to guess which match is closest based on the parent folder of the file you are currently working on would also go a long way.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders
