### ISSUE TITLE
"Switch header/source" in split view opens file always in left view.

### ISSUE THREAD

**Issue by bad-ed** [microsoft/vscode-cpptools#444]
Example: editor is split into two views. In the left view I have "file.h" opened, "file.cpp" is opened in right view. Issuing "C_Cpp.SwitchHeaderSource" command in "file.h" tab creates new tab "file.cpp" in _left view_. Seems like it should focus already opened "file.cpp" tab in right view. If there is no tab with corresponding source (or header) it should be created in the same view side by side with tab from which command has been issued.

**Comment by pieandcakes** [comment]
@bad-ed What operating system are you seeing this behavior on?

**Comment by bad-ed** [comment]
Windows 7. Attached screencast.

![vscode](https://cloud.githubusercontent.com/assets/24456989/21926730/165b3774-d994-11e6-80f0-1060f3ab447a.gif)

**Comment by danielrfraser** [comment]
This issue also effects MacOS client and Ubuntu. Really frustrating when you have a class implementation open on each tab, and you are trying to swap between header and footer. It will always open on the first pane, regardless of whether you have the file open in the other tab already.

**Comment by pieandcakes** [comment]
@bad-ed @danielrfraser This seems like an issue with VS Code not handling the opening of the file correctly. Can you file this issue with them at https://github.com/Microsoft/vscode/issues ?

**Comment by bpasero** [comment]
@pieandcakes VS Code will open the editor in the group of the currently active one and you have API to control where to open it. There may be some API missing to indicate that you would want to reveal an editor if it is already opened somewhere else.

**Comment by sean-mcmanus** [comment]
@bpasero We currently just do showTextDocument, without a viewColumn, which is why it always shows it in the 1st column, but in order to change this we would need to determine if the text document is already docked in another column, but there doesn't appear to be any API for determining this. In other words, we have visibleTextEditors, but not the non-visible ones, and we have a list of the open documents from onDidOpen/Close, but we can't determine which column the document is in. If we could pass some argument to showTextDocument to make it show in any column it's currently docked in that would work. However, the repro shown by @bad-ed in which the switch occurs between visible documents should be fixed in the next update (of the language service...the debugger team might release any earlier update).

**Comment by bpasero** [comment]
Yes, I think more API is needed to instruct to reveal an already opened document if any.

**Comment by sean-mcmanus** [comment]
0.10.0 fixes this for the case when the switch target is visible in another pane (which is the case for the repro provided by the user). The fix for non-visible documents is pending more API from VS Code. I'll close this for now.
