### ISSUE TITLE
Find All References (and Rename) gets stuck (doesn't work) after doing the operation on files belong to different workspaceFolders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4462]
With a multroot workspace, do Find All Refs (or Rename) with a file belonging to one workspace and then do an operation on a file in another workspace.

Bug: The Find All References gets stuck.

**Comment by nunojsa** [comment]
I'm not sure if it's the same cause but I'm experiencing the same result. So I have a saved workspace which sits on the root directory of my project. So the workspace has only one root folder in my case. Anyways, it's happening with some frequency, that doing a Find all Refs on some symbol just stucks... Restarting the editor makes it work again... It seems, at least, related with this issue. Hope to see a fix on this soon since this feature is __really__ helpful.

**Comment by sean-mcmanus** [comment]
@nunojsa Your issue sounds different -- this issue is only for the bug caused when there are > 1 workspace folder. Does your issue repro with 0.26.2-insiders2? If so, can you file a new bug with more repro info?

**Comment by nunojsa** [comment]
I don't think it happened with the latest update. The next time it happens, if it happens, I will fill a new bug for this...
