### ISSUE TITLE
Goto function using F12/alt-F12 show allow going to function definition or prototype

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#447]
Goto function using F12/alt-F12 show allow going to function definition or prototype.
This could a separate command as most of the time going to the function definition is the desired behaviour.

**Comment by sean-mcmanus** [comment]
We currently go to the definition if it's available. We also have the declaration info available but VS Code doesn't seem to provide an API for us to send the data appropriately. One potential solution would be to add a command to switch to "declaration mode", which causes the next GoTo/Peak Definition to go to the declaration instead (i.e. Ctrl+F12 and then F12 or Alt+F12). Going to the declaration instead of the definition is valuable when the declaration has more comments or has initial values set on the parameters, or when you need to modify the declaration, etc.

**Comment by bobbrow** [comment]
goto declaration was added in version 0.11.0.  We were tracking issue #271 for this feature and missed this duplicate issue.
