### ISSUE TITLE
Wrong type definition

### ISSUE THREAD

**Issue by Feresey** [microsoft/vscode-cpptools#4484]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Arch Linux x86_64
- VS Code Version:  1.39.2
- C/C++ Extension Version: 0.26.0

**To Reproduce**

highlight a variable of this type or type name

**Expected behavior**
size_t = unsigned long

**Screenshots**

![image](https://user-images.githubusercontent.com/33696249/67433969-d4f10700-f5f1-11e9-82ff-bb9f7c4147f0.png)

Version 0.25.1:
![image](https://user-images.githubusercontent.com/33696249/67436253-a32e6f00-f5f6-11e9-97f3-a42638baf52c.png)

**Additional context**

**Comment by Colengms** [comment]
Hi @Feresey .  I believe this behavior is by design.  This is aligned with the behavior of Visual Studio.  (We share common components of IntelliSense with VS).  However, I went ahead and created a ticket against Visual Studio code to consider your request.  That is here: https://developercommunity.visualstudio.com/content/problem/793033/display-original-type-instead-of-typedef.html

**Comment by Colengms** [comment]
Hi @Feresey , I think I misunderstood your issue in my previous reply.

It looks like you're seeing a difference between versions of the C//C++ Extension.  In the latest version, it's identifying size_t as an unsigned int, and in a previous version it was correctly identified as an unsigned long.  Is that correct?

I don't believe we do anything special in the C/C++ Extension regarding size_t.  We are reflecting what was parsed.  The difference would seem to be due to using a different configuration (different include paths, or different defines).  Can you confirm by providing the output from the "C/C++ Log Diagnostics" command in each scenario?  If the include paths or defines are different, it should be clear from that output, and we could try to identify why.

**Comment by Feresey** [comment]
[0.25.1.log](https://github.com/microsoft/vscode-cpptools/files/3775791/0.25.1.log)
[0.25.1.diagnostics.log](https://github.com/microsoft/vscode-cpptools/files/3775799/0.25.1.diagnostics.log)

[0.26.0.log](https://github.com/microsoft/vscode-cpptools/files/3775792/0.26.0.log)
[0.26.0.diagnostics.log](https://github.com/microsoft/vscode-cpptools/files/3775800/0.26.0.diagnostics.log)

**test file:**
[bluetooth.cpp.zip](https://github.com/microsoft/vscode-cpptools/files/3775793/bluetooth.cpp.zip)

**Comment by Feresey** [comment]
![image](https://user-images.githubusercontent.com/33696249/67634193-ba58af80-f8c9-11e9-8c3f-5412f6a3168d.png)

oh yes, I see the reason.
I don’t even know why the default version of gcc-x86 was chosen instead of gcc-x64.
Anyway thanks for the help!

**Comment by bobbrow** [comment]
We're glad you were able to resolve this!
