### ISSUE TITLE
C/C++: Configuration Edit (UI) not found 

### ISSUE THREAD

**Issue by sizeCPP** [microsoft/vscode-cpptools#4489]
I got an error on vscode when i look for the C/C++ ConfigurationEditUi an error occures 

> "command 'C_Cpp.ConfigurationEditUI' not found"

_Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362_

**Comment by Colengms** [comment]
Hi @sizeCPP .  Can you provide more information?  I can't repro by executing the command on the command palette.

Are you using the command palette to execute the command, or executing it programmatically?  If the command is offered on the command palette, it's unclear to me why it could not be found.  The C/C++ extension should always be registering that command.  You might try reinstalling the extension.  We have seen issues in the past in which VS Code did not completely install our extension.

Perhaps the error is due to the command failing, and not actually that it was 'not found'.  Do other commands from the C/C++ extension work for you?

What language is your display language set to in VS Code?  (Configure Display Language)    We show a translated configuration UI based on the current language setting.  Perhaps there is an issue with the specific language you are using.

**Comment by sizeCPP** [comment]
Hey, @Colengms i wanted to **open** the  `C/C++ IntelliSenseConfigurations`
 wich should start after i search  `Edit Configurations (UI`) in the **command palette** but when i try to run it, it shows me that **it can't be found**.  Edit: Other Extensions work fine (i tested 3 different)

**Comment by michelleangela** [comment]
@sizeCPP , can you provide detailed reproducible steps that includes whether you opened a workspace folder or opened a *.cpp file, or any other steps you did?

**Comment by Colengms** [comment]
Hi @sizeCPP ,

I understand that you are selecting this command from the command palette and it's simply not working.  Since this is not repro'ing for everyone, there may be something specific about your environment that we need to determine to investigate and address the issue.

* Does uninstalling and reinstalling the C/C++ extension correct the issue?

* You mentioned that 'other extensions' work fine.  Do other commands registered by the C/C++ Extension work?  (Other commands starting with C/C++, such as "C/C++ Log Diagnostics")  Do all commands associated with the C/C++ Extension fail, or just this one?

* What display language is VS Code currently set to?

**Comment by sizeCPP** [comment]
Thanks for the replies. 
My displayed language on vscode was C++ and i tried  all the C/C++ commands all worked fine.
I deinstalled all the extensions that include c/c++ and reinstalled only the one i really need thats the C/C++ extension by microsoft and it worked. I guess some of the extensions didnt work together.|
