### ISSUE TITLE
Task.ja=son for build 

### ISSUE THREAD

**Issue by KingLebron** [microsoft/vscode-cpptools#45]
Task.json is created as the followings:

```
{
    "version": "0.1.0",
    "command": "g++",
    "args": ["-g", "*.cpp", "-o", "a.out"],
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}
```

However it report the following error, though there are `MergeSort.cpp` and `test.cpp` in the working dicrectory:

```
clang: error: no such file or directory: '*.cpp'
clang: error: no input files
```

**Comment by delmyers** [comment]
@sridmad

**Comment by KingLebron** [comment]
Additional Information:
OS:  OS X 10.11.4
VSCode: 1.1.0
C/C++ Extension: 0.5.0

**Comment by sridmad** [comment]
The extension is not involved in dealing with tasks. The only reason I can think of for the files not to be found due to current directory not being set correctly.
- does invoking pwd as command show the correct directory?
- current working directory for the invoked tool should be the workspace root. You can also try explicitly setting the directory for the tool through options
  
  "options": {
      "cwd": "/path/to/directory"
  },

**Comment by pieandcakes** [comment]
@KingLebron Tasks are provided by VSCode. If this isn't resolved, can you try and file an issue on the [VSCode ](https://github.com/Microsoft/VSCode/issues)repo?
