### ISSUE TITLE
Rename (F2) function not working in certain scenarios

### ISSUE THREAD

**Issue by janwilmans** [microsoft/vscode-cpptools#4510]
Rename works for a local variable, dubble click on the name, edit the value and press enter.
![image](https://user-images.githubusercontent.com/5933444/67785672-e3b24080-fa6d-11e9-9e5b-407c6700d7d7.png)

Becomes :

![image](https://user-images.githubusercontent.com/5933444/67785696-ef056c00-fa6d-11e9-90a2-6cf6ca7878f4.png)

So far so good.

However, if the variable can't be looked up, like here:

![image](https://user-images.githubusercontent.com/5933444/67785906-473c6e00-fa6e-11e9-89aa-a7df13413843.png)

rename doesn't work, no message, just nothing.
so I'm guessing this a the scenario many people run into, if you have not configured the build system right (cmake?), the symbol lookup fails and just nothing happens, which is very confusing to people.

looks like https://github.com/microsoft/vscode-go/issues/1954
or https://github.com/microsoft/vscode-python/issues/1992

**Comment by Colengms** [comment]
Hi @janwilmans .  I believe what you are seeing is that the selected symbol has not been detected by IntelliSense.  Since there are no 'unconfirmed' matches, we do not display the Rename UI.  Instead, we immediately apply the rename.  In this case, we are applying the rename to all 0 of the found references.  We should probably display a message in this case that IntelliSense was unable to detect a symbol to rename.

Note that it shouldn't be necessary to configure a build system.  It should be sufficient that IntelliSense is configured in the C/C++ Extension.

**Comment by sean-mcmanus** [comment]
Yeah, VS shows "A definition for the symbol 'duck' could not be located."

**Comment by janwilmans** [comment]
Yes, vs2019 shows: 
![image](https://user-images.githubusercontent.com/5933444/67803890-33a0ff80-fa8e-11e9-8c23-b621c7087648.png)

when you try to 

![image](https://user-images.githubusercontent.com/5933444/67803954-54695500-fa8e-11e9-8580-d29916642f59.png)

doesn't even popup the rename edit box, which makes it at least very clear that nothing is going to be renamed :)

**Comment by michelleangela** [comment]
Rename experience improved in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.

**Comment by platocrat** [comment]
For anyone wondering about how to pass the _Rename Refactoring_ tutorial on Mac, first highlight the function or variable name, then press CMD + F2.
