### ISSUE TITLE
"Improved Member Function Completion" not working

### ISSUE THREAD

**Issue by SunXuan90** [microsoft/vscode-cpptools#4513]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windos 10 1903 18362.356
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

In https://devblogs.microsoft.com/cppblog/vs-code-cpp-extension-january-2019-update/ I see that the c/c++ vscode extension has a feature:

> With improved member function completion, the selected completion is committed after a parenthesis “(“ is entered.

But it's not working on my computer. I have the latest vscode and c/c++ extension, and I already turned on "Editor: Accept Suggestion On Commit Character". Is there any other options that I missed? Thanks!

This is intellisense suggestions:
![image](https://user-images.githubusercontent.com/27178583/67826380-43105f00-fb07-11e9-8642-9ab38ec782cf.png)
and this is after typing '('
![image](https://user-images.githubusercontent.com/27178583/67826422-63d8b480-fb07-11e9-926f-179f266d7ebd.png)

**Comment by sean-mcmanus** [comment]
That "feature" (a 1 line change) was removed because it caused unforeseen regressions -- the blog should be edited to remove mentioning that feature (I mentioned this to the blog author to do this at the time, but it looks like it didn't happen). A different design that adds ( automatically is being tracked at https://github.com/microsoft/vscode-cpptools/issues/882 .

**Comment by mluparu** [comment]
I've updated the blogpost to reflect the fact that the feature is no longer supported.
