### ISSUE TITLE
c_cpp_properties.json location

### ISSUE THREAD

**Issue by idanemergi** [microsoft/vscode-cpptools#4520]
The extension always creates the c_cpp_properties.json under "${workspaceFolder}.vscode" folder.
Is there a way of setting a different location to that file as with C_Cpp.default.browse.databaseFilename?

I like to keep my source code folders clean as much as possible

Extension version: 0.26.1
VScode version: 1.39.2
I'm working on windows 10.
Thanks.

**Comment by sean-mcmanus** [comment]
Not really. You can set some settings at the user level via C_Cpp.default.* settings (or the workspace folder level, but that is saved under `${workspaceFolder}/.vscode/settings.json`)

**Comment by bobbrow** [comment]
We do not plan to support placement of c_cpp_properties.json outside of the code folder at this time.

**Comment by wisepotato** [comment]
Why not? At my current company it's not allowed to set IDE specific stuff in the git repo and this seems like a bit of a let down :(

**Comment by sean-mcmanus** [comment]
@wisepotato c_cpp_properties.json was never designed to be checked into a git repro. Is there some problem with the .vscode/c_cpp_properties.json existing but not being in git? Is C_Cpp.default.* insufficient?

My guess is that Bob was saying that our team didn't have any intent on implementing support for c_cpp_properties.json outside of the workspace folder, given our other priorities and the low number of requests for it -- it's possible we might be able to accept PR for the change.

**Comment by bobbrow** [comment]
Correct, closing this issue was meant to be a courtesy so that folks don't get their hopes up that we'll work on this someday.  It doesn't mean we wouldn't accept a PR.

C_Cpp.default.* would write to `settings.json` which is also inside the .vscode folder of the repository (I'm assuming you wouldn't want to set it globally).  If you use CMake, you could take advantage of its integration with cpptools and not need a c_cpp_properties.json file at all.

**Comment by sean-mcmanus** [comment]
C_Cpp.default.* could also be set in the "local" workspace too (if a workspace is used).

**Comment by maxim-babenko** [comment]
I don't have c_cpp_properties.json.
C_Cpp.default.browse.path is set in my workspace file.

I don't believe VSCode just ignores browse.path since I see exactly these paths listed in "Folder ... will be indexed" and "Processing folder (recursive)" messages.

Still during Intellisense update (flame icon) strace + procfs clearly show that cpptools is touching "unwanted" folders, e.g.
lr-x------ 1 babenko 64 Aug  8 19:03 13 -> /yt/nvme1/babenko/arc/arcadia/junk/mesteno/
lr-x------ 1 babenko 64 Aug  8 19:03 14 -> /yt/nvme1/babenko/arc/arcadia/junk/mesteno/xurma_deploy/

I tried attaching gdb to cpptools, here's the backtrace of the thread doing that traversal:
https://gist.github.com/maxim-babenko/68846c5d5bf7b8e750cd79c9218ed15a
