### ISSUE TITLE
Platform-specific headers and analyzer

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-cpptools#4543]
We have a project that has a number of platform-specific headers that are enabled or disabled via the build system (rather than through `#ifdef`-ery). This confuses the code analysis, because an include like this:
```
#include <os_specific.h>
```
may include `windows/os_specific.h` or `linux/os_specific.h` or `freebsd/os_specific.h`, depending on the build configuration (the relevant path is included by the build system).

Some of the binaries/libraries are excluded from compile database for various reasons (wrong platform, missing dependencies, etc.), so the code analyzer falls back to `c_cpp_properties.json` contents with regards to include paths, etc., which is why this becomes a problem (because it includes all paths).

Is there a way to make code analysis to ignore certain header paths without resorting to "ignoring by omission" by explicitly spelling out each and every include path?

**Comment by Colengms** [comment]
Hi @anatolyburakov .  Which features are you getting incorrect results from?

There are 2 underlying technologies in the C/C++ Extension; IntelliSense and tag parser.  IntelliSense is based on a first pass compile of the source code, and leverages include paths.  The tag parser builds a database of all symbols, and leverages your browse path(s).  I believe both include and browse paths default to your entire workspace folder (recursively).

We don't currently have a way to exclude certain include or browse paths, but perhaps exclusion wouldn't be necessary if not using the recursive defaults?

Ideally, the C/C++ Extension would be configured to align with your build system, or configured _by_ your build system if using a configuration provider extension such as [cmake-tools](https://github.com/microsoft/vscode-cmake-tools).  If cmake-tools or another configuration provider is not an option, I'd suggest creating multiple configurations in `c_cpp_properties.json` that mirror the configurations of your build system, and explicitly specify `includePath` and `defines`.  (I use this approach with a project w/ platform-specific include paths).  You can also explicitly specify your browse paths per configuration, but it may be OK for tag parser related features to draw from a superset of symbols.

Assuming you are not cross-compiling, headers for other platforms are likely not available, so you could still get squiggles due to missing information for those platforms.

**Comment by bobbrow** [comment]
To add to this, if you are using recursive includePath for IntelliSense, we give priority to non-recursive paths, so you can create configurations for each platform in this manner which will allow you to get the squiggles right for each OS:

(pseudo-code)
```
{
  "name": "linux",
  "includePath": [
    "${workspaceFolder}/linux",
    "${workspaceFolder}/**"
  ],
  ...
},
{
  "name": "windows",
  "includePath": [
    "${workspaceFolder}/windows",
    "${workspaceFolder}/**"
  ],
  ...
},
...
```

**Comment by anatolyburakov** [comment]
> To add to this, if you are using recursive includePath for IntelliSense, we give priority to non-recursive paths, so you can create configurations for each platform in this manner which will allow you to get the squiggles right for each OS:
> 
> ```

This has actually fixed my issue! Thanks!
