### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by Menci** [microsoft/vscode-cpptools#457]
There's only issues here. Where can I find the source code?

**Comment by sean-mcmanus** [comment]
The source code is not available. It's not open source.

**Comment by goolic** [comment]
@sean-mcmanus Would open sourcing this extension be something microsoft considers? Could you explain how this project is different/better than youcompleteme ? 

From my ignorant position seems to me microsoft and the open source community would gain a lot from joining efforts with the youcompleteme folks.

**Comment by sean-mcmanus** [comment]
@goolic Microsoft (and its developer tools division) is a big organization with many teams/individuals that may not have the same view on what should and shouldn't be open sourced. Our Visual C++ team, which is developing this cpptools extension, does not intend to open source the extension, particularly because our code is tightly integrated with a parser that can't be open sourced due to licensing restrictions, and replacing that dependency would take a lot of work, and our focus is on making the C++ extension feature set closer to the non-open source Visual Studio C++ experience.

The team that develops Visual Studio Code itself may have a different view, but so far I have not seen any interest from them in an open source C++ extension (see https://github.com/Microsoft/vscode/issues/23126 ), but maybe they would change their mind if they receive enough user feedback?

I don't know anything about youcompleteme, but our extension does more than just completion. The C++ keyword colorization is open source (atom/language-c and textmate) along with all the core VS Code features.

**Comment by goolic** [comment]
2017-04-10 10:33 GMT-03:00 Sean McManus <notifications@github.com>:

> because our code is tightly integrated with a parser that can't be open
> sourced due to licensing restrictions, and replacing that dependency would
> take a lot of work, and our focus is on making the C++ extension feature
> set closer to the non-open source Visual Studio C++ experience.


Thx. I tought that was the reason.

I'd love if could provide a counter opnion on the value of open source
developer tools inside microsoft.

Thanks again.

**Comment by sean-mcmanus** [comment]
The typescript part of our extension has been open sourced: https://github.com/Microsoft/vscode-cpptools . The 2 language server processes that do parsing stuff haven't been open sourced.
