### ISSUE TITLE
C/C++ language server crash

### ISSUE THREAD

**Issue by bbkiwi** [microsoft/vscode-cpptools#4590]
**Type: LanguageService**

As requested by @sean-mcmanus in #3104, I'm filing a separate issue for this problem.

**Describe the bug**
- OS and Version: OSX Yosemite 10.10.5
- VS Code Version:

Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 14.5.0

- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them):
AStyle 0.9.0
Python 2019.10.44104

- A clear and concise description of what the bug is.

I'm trying to get C/C++ language support working in VSCode on macOS. Whenever I start VSCode, I get the following error:

```
[Error - 10:10:12 PM] Connection to server got closed. Server will not be restarted.
```

Sean suggested attaching a debugger to obtain a crash log, but I'm not sure how to do this. I have the following configuration in `launch.json`, but I'm not sure what to fill in for the process-related fields:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "enter program name, for example ${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb"
        }
    ]
}
```

The related issues I've seen for this have all been for VSCode on Windows, and obviously the program name is different on OSX. I'm also unsure what I want in `cwd` and `stopAtEntry` - I assume I want the process to pause at startup until the debugger is attached, but I'm not sure how to achieve that.

Once it's attached, should I just let the process run till it crashes? Do I need symbol info on OSX as I've seen described on Windows? If so, how do I specify it?

**Comment by sean-mcmanus** [comment]
If it's crashing on startup, then you won't be able to attach the debugger probably.

If you can get our Microsoft.CPP.Extension.darwin process to run without crashing, then you could attach a debugger via adding the (lldb) attach config, and setting the "program" field to the full path of that executable. You don't need a symbol path set.

One way to potentially pause the executable is to launch it from the TypeScript (Launch Extension) and set a breakpoint after the language client is created, but I'm not 100% if that will work still (it did at one point, but it might not currently): https://github.com/microsoft/vscode-cpptools/tree/release .

**Comment by sean-mcmanus** [comment]
If you could make sure no files are open or if you change your browse.path to be empty, that could potentially avoid the crash (long enough to attach a debugger).

**Comment by sean-mcmanus** [comment]
Actually, the Mac OS logs crashes at `<HOME>/Library/Logs/DiagnostiReports` so you might be able to get the crash call stack that way.

**Comment by bbkiwi** [comment]
Hi Sean, My son Colin who is a professional developer has been helping me. He wrote this bug report. I looked and found a crash report as above which I will attach. He is away now. Cheers, Bill
Note I upgraded to the lastest insider.

[Microsoft.VSCode.CPP.Extension.darwin_2019-11-13-132439_Guests-MacBook-Pro.crash.txt](https://github.com/microsoft/vscode-cpptools/files/3839157/Microsoft.VSCode.CPP.Extension.darwin_2019-11-13-132439_Guests-MacBook-Pro.crash.txt)

**Comment by sean-mcmanus** [comment]
The crash is occurring in the global scope constructor of an unordered_set:
0   Microsoft.VSCode.CPP.Extension.darwin	0x000000010603b1d3 std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::unordered_set(std::initializer_list<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) + 691
1   Microsoft.VSCode.CPP.Extension.darwin	0x00000001060504cb _GLOBAL__sub_I_message_handler.cpp + 3707

I believe it's some bug with the particular C++ runtime installed on your machine, perhaps due to the machine running such an old OS (Mac Yosemite from 5 years ago), so updating your OS might fix the issue, or you could try updating your XCode or somehow updating the C++ runtime.

We have users of Yosemite who are not hitting this crash, so something is unusual about your setup.

We (or you) could investigate more online to see if other apps are hitting a similar issue with the unordered_set constructor on Yosemite.

**Comment by bobbrow** [comment]
This does not appear to be an issue with the C++ extension.
