### ISSUE TITLE
How can I disable the limitation of reading a big compilation database JSON file?

### ISSUE THREAD

**Issue by WSUFan** [microsoft/vscode-cpptools#4642]
Hi,
Currently I'm using C/C++ extension to develop a big project. However, when I'm trying to use compilation database for the IntelliSense, the extension reports that only 5000 items of the JSON file can be processed. I believe this is kind of a limitation. So I'm wondering is there a way to disable that?

Thanks

**Comment by Colengms** [comment]
Hi @WSUFan .  By 'compilation database JSON file', are you referring to compile_commands.json ?  By default, the C/C++ Extension does not leverage compile_commands.json.  It must be specified in c_cpp_properties.json, like so:

```
"compileCommands": "${workspaceFolder}/build/compile_commands.json"
```

I don't believe we impose a limit of 5000 items, or report an error indicating how many we were successfully able to process.  Could you post a screenshot or log output?

**Comment by WSUFan** [comment]
Hi @Colengms. I have configured the c_cpp_properties.json to use compile_commands.json. But when VSCode is processing compile_commands.json, the extension reports there is a 5000 items limitation. Actually it is reported by JSON extension, not C/C++ extension. Here is the screenshot.
![image](https://user-images.githubusercontent.com/26418940/69378688-be2ae800-0c63-11ea-8b76-3ec0078de867.png)

**Comment by Colengms** [comment]
Since that error is coming from another extension, I don't believe it's referring to the C/C++ Extension's ability to parse compile_commands.json.  I assume it's referring to language server features of the JSON Extension being limited (in the editor) to 5000 entries.  If you need language server features in JSON files beyond the first 5000 entries, you might inquire in https://github.com/microsoft/vscode , as it looks like it's a bundled/default extension.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
