### ISSUE TITLE
C++ 0.26 fails on remote server

### ISSUE THREAD

**Issue by brevzin** [microsoft/vscode-cpptools#4663]
**Type: LanguageService**
C/C++

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.1. 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I'm running VSCode on Windows using a remote Linux server. When my extension updated to 0.26.1, every useful C++ aspect failed. No jump to definition, no code completion, nothing. The syntax highlighting was correct, but that's it.

Downgrading to 0.25.1 has the same behavior. 

Downgrading back to 0.24.1, things work beautifully. Code completion, jump to definition, everything. 

I don't have any kind of indication of failure on either 0.25.1 or 0.26.1, no output or anything.

**Comment by sean-mcmanus** [comment]
What do you mean exactly by "on Windows using a remote Linux server". Are you using a VS Code remote extension? Is our C/C++ language server process running on Linux or Windows (i.e. is the Microsoft.VSCode.CPP.Extension.linux or .exe process running)?

Have you tried 0.26.2-insiders3, it should be identical to the 0.26.2 we plan to release next week, unless we find any high priority issues that need fixing: https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders3

Can you enable debug logging: https://code.visualstudio.com/docs/cpp/enable-logging-cpp and look for any errors? The C/C++: Log Diagnostics command might also help. Or Toggle Developer Console and view the Console log for errors?

It sounds like the database is failing to get created for some reason, possibly due to your files.exclude setting or a configurationProvider issue...or the main process is crashing?

Syntax highlighting is provided by VS Code itself (we just add semantic colorization, which I assume is not working).

0.25.1 was released 3 months ago and we haven't seen reports like this from other users, so their might be something unusual in your setup.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
