### ISSUE TITLE
[Internal] The Quick Fix... link on wrong #include always jumps to the English interface

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#4677]
1. Install VSCode in a Chinese Simplified machine
2. Open VSCode and install extension "C/C++"
3. Open a folder which contain a cpp file 
4. Include a non-existing header file to the cpp file , like #include "TestHeader.h"
5. Hover the cursor on the #include "TestHeader.h"
6. Click "Quick Fix..." on the intellisense tips window
![image](https://user-images.githubusercontent.com/29274719/69846854-55212100-12b0-11ea-8d66-63deaf8497f3.png)

7.  Click "Learn how to install a library for this header with vcpkg" to open the web page

**Expected:**
The page "https://docs.microsoft.com/**zh-cn**/cpp/build/vcpkg?view=vs-2019" was opened
![image](https://user-images.githubusercontent.com/29274719/69847175-5868dc80-12b1-11ea-819c-484643c6a5cd.png)

**Actual:**
The English page "The page "https://docs.microsoft.com/**en-us**/cpp/build/vcpkg?view=vs-2019" was opened" opened
![image](https://user-images.githubusercontent.com/29274719/69847259-88b07b00-12b1-11ea-8eb8-554342f25472.png)

**Notes:**
Even if setting the explorer language to Chinese, the link still jump to English page

**Comment by sean-mcmanus** [comment]
We currently just use "https://aka.ms/vcpkg" -- looks like the fix would be to either generate a new aka link for every language or just use the target URI with the language part inserted.

**Comment by v-ericawu** [comment]
@bobbrow @sean-mcmanus A new related issue has arisen since version C/C++ 1.17.2:
The '**Learn how to install a library for this header with vcpkg**' option has disappeared from C/C++ extension 1.17.2 to the latest version now, **_so is this by design?_**

- If it's not by design, **_do we need to file a new GitHub issue to track this new issue?_**
- If it's by design, then **_should we close that Github issue?_** (because that github issue([4677](https://github.com/microsoft/vscode-cpptools/issues/4677)) needs to click on the 'Learn how to install a library for this header with vcpkg' option to reproduce it)

Latest C/C++ extension version: 1.20.5
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/27b44e74-e5c1-42ce-9447-a7b48544204b)

C/C++ extension 1.17.2:
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/94c7c6b7-5824-4e72-97b8-8b36e0f7e988)

C/C++ extension 1.16.3: 'Learn how to install a library for this header with vcpkg' option appear
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/48ddb237-c085-4e06-a0d2-c624d9539f40)

**Comment by sean-mcmanus** [comment]
@v-ericawu Yeah, I think there's a new bug caused by the PR https://github.com/microsoft/vscode-cpptools/pull/11280 . I think it was only supposed to exclude that code action for system headers.

**Comment by v-ericawu** [comment]
@sean-mcmanus Thanks for your confirmation! We have filed a new [issue ](https://github.com/microsoft/vscode-cpptools/issues/12413) to track the regression isue.

**Comment by v-ericawu** [comment]
Tested on C/C++ extension v1.22.0-dogfood1: Clicking on 'Learn how to install a library for this header with vcpkg' opens a link to **https://vcpkg.io/en/** and is still not localized:
![image](https://github.com/user-attachments/assets/ceb72911-0d3f-49ae-bdd4-bf3484e89b53)

**Comment by bobbrow** [comment]
The old site was removed and replaced with vcpkg.io which does not have translations for any other languages.  This is not an issue for the C++ extension to address right now.
