### ISSUE TITLE
IntelliSense does not recognize a constexpr variable used in another constexpr definition

### ISSUE THREAD

**Issue by hriekehof** [microsoft/vscode-cpptools#4736]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.2
- Intellisense Information is provided by: `cmake-integration` extension

If i use a previously defined `constexpr` variable in another. IntelliSense give the error message
`expression must have a constant value` which is case i think. gcc-8-2019-q1 compiles fine.

**To Reproduce**

1. Create a constexpr variable
2. Create a second constexpr variable and use the first one in it

**Expected behavior**
IntelliSense should not mark this as an error.

**Screenshots**

![Error Message](https://user-images.githubusercontent.com/9348635/70704704-db872b00-1cd2-11ea-8e9e-7806ef6d5ce2.png)

![Code](https://user-images.githubusercontent.com/9348635/70704927-4a648400-1cd3-11ea-9897-5895f1b1e917.png)

**Additional context**

**Comment by Colengms** [comment]
Hi @hriekehof .  In your example, expf() is not a constexpr.  Is that the issue?  Or, are you saying that after along1 and ashort1 failed to compile as constexpr, subsequent error messages that refer to them as non-constexpr should not be displayed?

**Comment by Colengms** [comment]
I think what's happening here is that although expf is not declared as a constexpr in math.h, gcc is replacing it with a compiler intrinsic (instead of a library call) and that's allowing it to be resolved as constexpr at compile time.  This may not be the case for all architectures gcc supports, but would seem to be the case for x86 and x64, so our gcc-x86 and gcc-x64 IntelliSense modes probably should not squiggle it.

I opened the following issue against VS (as we share common code for IntelliSense with VS).  https://developercommunity.visualstudio.com/content/problem/854941/intellisense-shows-squiggle-for-use-of-gcc-compile.html

**Comment by hriekehof** [comment]
@Colengms i think you are right. i totally missed that `along1, ashort1` also have already squiggle lines. 
Just for my interesset since i don't know much about it. At the moment i work on an embedded project. So my compiler is `arm-none-arm-gcc`. So far the gcc-x86 mode for intellisense works most of the time fine. But i think there are other build in functions specific for arm. Would it then be a good idea to have an intellisense mode for `gcc-arm` and `gcc-arm64` ?

**Comment by Colengms** [comment]
Hi @hriekehof .  Yes indeed.  We are tracking that with https://github.com/microsoft/vscode-cpptools/issues/4271

**Comment by twfry** [comment]
Why is this closed? We so ran into this and are waiting for a fix. Searching shows several other reported instances, all which were closed as duplicates to this. 

In our case we are using a constexpr function that contains std::pow(). Intellisense reports "cannot call non-constexpr function "__builtin_powf" (declared implicitly)". However g++ compiles fine. 

It appears this issue hits any constexpr function that contains math functions. 

This needs to be reopened and solved, its been 5 years.
