### ISSUE TITLE
About extension process block

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4768]
@sean-mcmanus Hi Sean, I want to discuss a question with you. I think you maybe have a lot of experience about this.

Currently vscode development team doesn't suggest to do something which takes long time, because this will block extension process. Sometime extension host will crash. If you use remote-ssh, it's easier to crash when doing these things.

This results in I can't use these API in extensions like：
1.  const data = await fs.readFile(dbpath); // In CMake Tool source code, at line 49 of vscode-cmake-tools\src\compdb.ts. If file is large, remote extension host will crash.(Currenly I am using remote-ssh.). I reported this issue on https://github.com/microsoft/vscode-cmake-tools/issues/970
2. vscode.workspace.findFiles(includePattern, excludePattern);  //if there are so many files, extension    
maybe can't be actived. This case occured on my own extension when I use remote-ssh.

Any suggesion to me? how do you solve these problem on your extension. CMake Tools has the same issue with me.

**Comment by sean-mcmanus** [comment]
Hmm...I don't believe we have ever hit any bugs like that with our C/C++ extension. My understanding is the await isn't supposed to block or crash the extension host process and is the same as wrapping the code in a .then block on a Promise.

I don't believe findFiles is a blocking method -- it returns a Thenable, so if you want code to use the results you would call .then((url)){…} to process the results.

Were you going to try to fix the CMake Tools bug?

Yeah, so if there is some code that is blocking synchronously it a spot when it shouldn't, the fix would be to change the blocking call to run asynchronously.

**Comment by Lennon925** [comment]
> Hmm...I don't believe we have ever hit any bugs like that with our C/C++ extension. My understanding is the await isn't supposed to block or crash the extension host process and is the same as wrapping the code in a .then block on a Promise.
> 
> I don't believe findFiles is a blocking method -- it returns a Thenable, so if you want code to use the results you would call .then((url)){…} to process the results.
> 
> Were you going to try to fix the CMake Tools bug?
> 
> Yeah, so if there is some code that is blocking synchronously it a spot when it shouldn't, the fix would be to change the blocking call to run asynchronously.

![12](https://user-images.githubusercontent.com/39362073/71144322-8f9b2f80-2258-11ea-9725-ae02da57a67b.PNG)

**Comment by Lennon925** [comment]
Extension host crash when I use CMake:Configure and member of CMake Tool team are on holiday. So I must solve this problem by myself. Expensive CPU operations maybe results in extension host crash, instead of code synchronization.

**Comment by sean-mcmanus** [comment]
FYI, our C/C++ team and the CMake Tools team are sort of the same team. I believe @andreeis is not on vacation, but she may be too busy with other stuff to respond to GitHub issues. @bobbrow might be able to help next week.

Yeah, it sounds like the CMake Tools operation is taking up too much CPU time in your scenario. Our C/C++ extension solves that problem via doing expensive long-running tasks in our Microsoft.VSCode.CPP processes. At one point our lexical colorization TypeScript code hit a similar problem where it would use too much CPU/memory and cause VS Code to freeze, but we ended up just removing that code. Another solution might be to break up the expensive task into multiple smaller tasks so that the extension host doesn't become unresponsive (not sure if that would work though).

**Comment by sean-mcmanus** [comment]
I have not debugged it, but from looking at the code, it looks like the vscode.window.withProgress API is blocking for the results of the "asysnc progress" method in cmake-tools.ts. The withProgress API is not designed to run the progress task asynchronously, so the entire call back is probably being awaited until it's finished. Our C/C++ uses that API for long-running Find All References operations (in references.ts), but we just report progress in that API and don't block.

So I believe the fix would be to somehow move that processing out of that withProgress callback so that only the progress is reported in that "progress" call back and not the blocking work, maybe via using setInterval to execute the long work in the timer call back thread? Not sure though.

**Comment by Lennon925** [comment]
> I have not debugged it, but from looking at the code, it looks like the vscode.window.withProgress API is blocking for the results of the "asysnc progress" method in cmake-tools.ts. The withProgress API is not designed to run the progress task asynchronously, so the entire call back is probably being awaited until it's finished. Our C/C++ uses that API for long-running Find All References operations (in references.ts), but we just report progress in that API and don't block.
> 
> So I believe the fix would be to somehow move that processing out of that withProgress callback so that only the progress is reported in that "progress" call back and not the blocking work, maybe via using setInterval to execute the long work in the timer call back thread? Not sure though.

Sean, Thank you very much for your suggestion. It's so useful~
