### ISSUE TITLE
Add a command to navigate to the matching #if/#ifdef/#else/#endif

### ISSUE THREAD

**Issue by llHoYall** [microsoft/vscode-cpptools#4779]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro 1903 18362.535
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

if I press the specific key, then the cursor moves to matching pair.
`#if` <-> `#endif`
`#if` <-> `#elif` <-> `#else` <-> `#endif`
`#ifdef` <-> `#endif`

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
This is similar to https://github.com/microsoft/vscode-cpptools/issues/2565 (highlight of matching preprocessors).

However, the fix for https://github.com/microsoft/vscode-cpptools/issues/407 (preprocessor code folding) may fix this via usage of VS Code's "Go to Bracket" command.

**Comment by yushiyangk** [comment]
#407 has been implemented, but it seems "Go to Bracket" does not work, nor afaict anything else.

**Comment by sean-mcmanus** [comment]
@yushiyangk Yeah, looks like we'd have to add a new command.

**Comment by Colengms** [comment]
This should be pretty simple to support.  The FoldingRangeProvider could keep a per-file mapping of folding ranges (instead of discarding them after they are returned to VS Code, which is what it currently does).  We might want to limit that to just S_BM_IFDEF and possibly S_BM_REGION range types.  A command could be added which checks the current cursor position, looks for a start/end on that line, and moves the cursor to the other line.  It might be necessary to adjust the end line by +1/-1, as I think ranges will end on the line prior to the `#endif`, `#else` or `#pragma endregion` statement.

**Comment by heartacker** [comment]
unfortunately， when in multifolder workspace, it will show a popup window which chosing the workspace when using command `GoToPrevDirectiveInGroup` and `GoToNextDirectiveInGroup`

**Comment by sean-mcmanus** [comment]
@heartacker I've moved that to https://github.com/microsoft/vscode-cpptools/issues/7283. It'll be fixed in our next 1.3.0-insiders4 release (some time next week).

**Comment by Colengms** [comment]
This feature was added in 1.3.0.
