### ISSUE TITLE
Failed to read response from server

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#4824]
I get a similar error today when running VSCode on a Remote Host using SSH.

![Bildschirmfoto von 2020-01-08 14-08-56](https://user-images.githubusercontent.com/193408/71980491-73b7f780-3220-11ea-91a3-e4046bfa7c9f.png)

No outliner works when I get this error.

The `cpptools:llvm` log holds this information: `[Error - 08:02:13] Connection to server got closed. Server will not be restarted.`

The `C/C++` log contains: `Failed to read response from server: 22`

## My workaround (poor)

When I restart VScode things work for a while.

## Specs
```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.12-300.fc31.x86_64 snap 
```

_Originally posted by @kwk in https://github.com/microsoft/vscode-cpptools/issues/2453#issuecomment-572044984_

**Comment by Colengms** [comment]
Hi @kwk.  Thanks for reporting this.  Could you confirm whether this repros with the [latest insiders build](https://github.com/microsoft/vscode-cpptools/releases)?

If this continues to happen, could you let us know if a pattern emerges?  It could be some particular feature you are leveraging at the time, or a particular file that is open at the time.

If you attach a debugger to the extension process (Microsoft.VSCode.CPP.Extension.linux) and catch it crashing, that might help isolate the problem to a specific call stack.

**Comment by sean-mcmanus** [comment]
This is most likely the same crash as https://github.com/microsoft/vscode-cpptools/issues/4770 (reproed with some LLVM projects), which we should have a fix out with 0.26.3-insiders3 later today.

**Comment by Colengms** [comment]
@kwk .  We believe this has been addressed.  If you are still seeing this, could you reply here?  We can reopen the issue if needed.

**Comment by dpernes** [comment]
Having the exact same issue with the C/C++ extension. "Failed to read response from server: 22" and error squiggles are not updated as errors are fixed. Restarting VS code fixes the behavior for a while.

**Comment by sean-mcmanus** [comment]
@dpernes 0.28.0 has some known regressions. We have a fix pending for one of them (that we believe accounts for ~75% of the crashes). If you can attach a debugger to cpptools-srv to get a crash call stack we could confirm whether that issue will be fixed in our next release or if we need more repro info.

**Comment by maikeriva** [comment]
Same issue on a cpp project I'm working on. On my platform (Fedora 31) this issue seems to block cross-referencing (ctrl+click) and similarly other intellisense features for a few seconds. Navigating within the code is impossibly slow.
C++ extension version is 0.28.3 and VSCode version is 1.46.1

I don't experience crashes so far though, only intense slowdowns while using intellisense fatures.

**Comment by sean-mcmanus** [comment]
@maikeriva What do you mean by "same issue"? Is Ctrl+Click doing a Find All References? What do you mean by "navigating"? How do you know you're not experiencing IntelliSense crashes? You don't see "failed to read response from server" in the C/C++ logs?

**Comment by maikeriva** [comment]
@sean-mcmanus Thanks for your reply. I am not an expert on the exact terminology of Intellisense or, more generally, development-aid features of VSCode, but I'll try to do my best to make my point.
When I ctrl+click on a function (with the intention to go to its declaration/definition) VSCode takes a very long time before performing such action, and that coincides with the message `Failed to read response from server: 22` in the C/C++ log.
I have moved on a separate project at the moment in which this does not seem to occur. As soon as I get back working on the troublesome one I will stay alert to find out more clues about the issue.

**Comment by sean-mcmanus** [comment]
@maikeriva  It sounds the the IntelliSense process (cpptools-srv) is crashing. https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders has fixed some high hitting crashes. Otherwise, we'd need to get a call stack (via attaching a debugger to cpptools-srv before it crashes, i.e after opening an empty file and the pasting in the crash causing code).
