### ISSUE TITLE
Features in Mingw C++ tutorial not present in C++ extension

### ISSUE THREAD

**Issue by slootmat** [microsoft/vscode-cpptools#4840]
Issue Type: <b>Bug</b>

--------------------------------------------------------------------------
1. g++ --version typed in fresh command prompt after setting PATH did not recognize command, but calling the mingw64 console from that windows command prompt did work. 
2. intellisense example, right click on msg. did not produce any response
3. Dropdown list for  Terminal > Configure Default Build Task did not produce "C/C++: xxx..." selections. Instead, it produced a single entry:"Create tasks.json from template" selecting this resulted in a dropdown list of inapplicable choices: MSBuild, maven, .net Core, others
---------------------------------------------------------------------------
https://code.visualstudio.com/docs/cpp/config-mingw
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Extension version: 0.26.2
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.55GB (54.76GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Issue 3 appears to be the same as https://github.com/microsoft/vscode-cpptools/issues/4834 -- setting your compilerPath to the mingw compiler (or any non empty-string) should be a workaround.

Not sure about issues 1 and 2. Using C/C++: Log Diagnostics with the desired file active may show what is wrong with the IntelliSense configuration.

**Comment by slootmat** [comment]
Hello, thanks for taking this up. My issue #3 was that of not finding  the
expected items on the menu dropdown list. I have done what the tutorial
instructed regarding setting PATH variable to the file path of the MINGW64
compiler. That step is not in question. I am able to launch the Mingw64
console from the windows command window after setting the PATH variable.
Please confirm or correct my understanding/guess that setting the PATH
variabel is the same as what you are referring to as setting the "
compilerPath"
Thanks,

**Comment by sean-mcmanus** [comment]
The compilerPath is a setting in c_cpp_properties.json (from C/C++: Edit Configurations) -- which is not normally necessary to use the build and debug feature, but there's a bug that is causing the feature to fail when the compilerPath is blank. Setting the C_Cpp.default.compilerPath may also work (but I haven't verified that). The bug is causing the compilers on the PATH to not be shown in the dropdown.

**Comment by michelleangela** [comment]
> g++ --version typed in fresh command prompt after setting PATH did not recognize command, but calling the mingw64 console from that windows command prompt did work.

@slootmat , how did you open VS Code? Was it through a Windows command prompt?

**Comment by slootmat** [comment]
I can open VS Code in three ways:
1. from the windows command prompt after using cd to e in the folder that
the project top level was.
2. By opening a file from the VS Code GUI already opened, but without
having been opened from a VS Code workspace  file.
3. By navigating to a defined VS code workspace file that I defined by
saving "Workspace as", when there was not yet a workspace file defined.

**Comment by michelleangela** [comment]
Initially I thought you'd have to open VS code from the Windows command prompt, but this is not necessary.

I was able to execute `g++ --version` in the [VS Code integrated terminal](https://code.visualstudio.com/docs/editor/integrated-terminal) when I restarted or reloaded VS Code after installing mingw64, otherwise the integrated terminal will not recognize it. I'm assuming you've also restarted VS Code and the command still does not work on VS Code? This seems like a VS Code terminal issue. Did you configure any terminal settings on VS Code?

As for IntelliSense not working when you right click on code sample `msg`, can you run `C/C++: Log diagnostics` from the VS Code command palette and share the logs here?

**Comment by Colengms** [comment]
Hi @slootmat , are you still seeing an issue mentioned here?

I believe we used to fail to probe MinGW if it's path was not also set in the environment path.  We worked around this internally, and recent versions of the extension should probe MinGW properly without requiring a work around.

If there is a remaining issue here you are still seeing, could you clarify with an example?
