### ISSUE TITLE
Unable to load schema 'c_cpp_properties.schema.json'

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode-cpptools#4841]
This is a problem. It costs me a lot of time and exhausted entheusiasm.

Warning:
{
	"resource": "vscode/c_cpp_properties.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Unable to load schema from 'cpptools-schema:/c_cpp_properties.schema.json': Request vscode/content failed with message: cannot open cpptools-schema:/c_cpp_properties.schema.json. Detail: resource is not available.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}

_Originally posted by @Ulysiss in https://github.com/microsoft/vscode-cpptools/issues/4837#issuecomment-573617353_

**Comment by Colengc** [comment]
Hi @Ulysiss .  What version of the cpptools extension are you using?

It looks like there is a file missing.  We have received reports that extension installation can fail if VS Code is exited while installation is in progress, leaving a partial install.  Could you try uninstalling and reinstalling the extension?  Before reinstall, delete the left over extension directory, so it gets fully repopulated instead of reused.  Let me know if that does not correct the issue.

**Comment by mfloriani** [comment]
Hi @Colengc ,
I was able to solve by doing as you recommended. First I uninstalled the extension, then I removed the extension folder in .vscode folder and finally I reinstalled the extension.
Thanks!

**Comment by Tblade-hui** [comment]
> Hi @Ulysiss . What version of the cpptools extension are you using?
> 
> It looks like there is a file missing. We have received reports that extension installation can fail if VS Code is exited while installation is in progress, leaving a partial install. Could you try uninstalling and reinstalling the extension? Before reinstall, delete the left over extension directory, so it gets fully repopulated instead of reused. Let me know if that does not correct the issue.

The same problem,  I have reinstalled vscode and extensions and before I reinstalled the extensions, I have deleted the extension files ,but it doesn't work. My extention version is c/c++0.27.0

**Comment by vlmillet** [comment]
Same issue here, even on reinstalling/cleaning (the file is present in the cpptools extension folder but seem not found by vscode)
It seems that executing Code as administrator fixes the problem, but it was not necessary yesterday so ..

**Comment by sean-mcmanus** [comment]
I hit this bug with 0.27.0, but then when I tried to debug it, it stopped reproing. I got a repro without debug bits, so I'll see if console logging can help diagnose the cause...

**Comment by vlmillet** [comment]
I think about some read/write rights issue inside the .vscode folder considering what happened in my case .. Having it run as admin solved definitely the problem even if I launch it as current user afterwards. I suspect some kind of "rights reset" code might be able to succeed as administrator mode (and fail otherwise) and then make it OK for next launches as current user. But it is only a blind guess. if that can help..

**Comment by sean-mcmanus** [comment]
This doesn't appear to be our extension's bug -- our register function gets called correctly, but VS Code never calls us back. I've filed a VS Code bug at https://github.com/microsoft/vscode/issues/95729 .

I found that clicking the warning icon in the status bar that says "click to retry" causes it to get fixed (until it repros again later on).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders .
