### ISSUE TITLE
[Feature Request] natvis ArrayItems length limited to 50. Make it user configurable.

### ISSUE THREAD

**Issue by kjpus** [microsoft/vscode-cpptools#4843]
Type: Debugger

**Describe the bug**
- OS and Version:
Windows 10
- VS Code Version:
1.42.0-insider
- C/C++ Extension Version:
0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
Remote-SSH 0.48.0
- A clear and concise description of what the bug is.
ArrayItems only displays up to 50 items.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

`test.cpp`:

```cpp
#include <memory>
#include <iostream>

using namespace std;

struct data
{
    unique_ptr<int[]> _data;
    int cnt;
};

int main()
{
    data a{make_unique<int[]>(100), 100};
    cout<<a._data[0];
}
```
`array.natvis`:
```natvis
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer
    xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
  <Type Name="data">
    <DisplayString>data {size={cnt}}</DisplayString>
    <Expand>
      <ArrayItems >
        <Size>cnt</Size>
        <ValuePointer>_data._M_t._M_t._M_head_impl</ValuePointer>
      </ArrayItems>
    </Expand>
  </Type>
</AutoVisualizer>
```

`launch.json`:
```json
{
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode":"gdb",
            "miDebuggerPath": "gdb",
            "visualizerFile": "array.natvis",
            "showDisplayString": true,
            "logging": {"engineLogging": true}
}
```

**Comment by pieandcakes** [comment]
@kjpus This is by design. Natvis is an expensive procedure as for each item, we need to make queries to the debugger to get information, we have capped this to 50. If you have a better suggestion on a size limit, please let us know.

Code:
[The size limit](https://github.com/microsoft/MIEngine/blob/f342bf345dbc5a896d767786b9fa9ef1ee641ead/src/MIDebugEngine/Natvis.Impl/Natvis.cs#L155) and [where its used for ArrayItems](https://github.com/microsoft/MIEngine/blob/f342bf345dbc5a896d767786b9fa9ef1ee641ead/src/MIDebugEngine/Natvis.Impl/Natvis.cs#L486).

**Comment by kjpus** [comment]
@pieandcakes Thanks for your response. I understand the reasoning but could this be made configurable (either in launch.json or as a user/workspace setting), rather than a hard-coded number?

**Comment by Trass3r** [comment]
I wonder if the elements could be loaded in chunks, maybe using [`indexedVariables`](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Variable).

**Comment by bradphelan** [comment]
How can this be by design. I am constantly frustrated in vscode that the debugger shows some N elements from the front of the vector and then just stops displaying them correctly.  The front end should not have to be querying the back end for *all* the items in the vector, only the items currently in the view. Virtual scrolling is a well understood concept in UI design. In the debugger  console itself you can ask it for an offset and count of items.
