### ISSUE TITLE
config includePath for project with generated code and NFS

### ISSUE THREAD

**Issue by andl** [microsoft/vscode-cpptools#4866]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04 
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): n/a
- A clear and concise description of what the bug is.

I'm trying to figure out what's the proper way to setup `includePath` in `c_cpp_properties.json` for an internal c++ project.

Here is my source code for a demo project. A protobuf schema file and a main file include both `common.h` and the to-be-generated `message.pb.h` file. 
```
$ tree ~/project/
/home/andl/project/
└── src
    ├── common.h
    ├── message.proto
    └── message_test.cc
```
After evoke the build script, it sync source code to NFS so our distcc cluster can access the source files; the build script also generate source files for protobuf. Here is what project looks like on NFS:
```
$ tree /nfs/build/project
/nfs/build/project
└── src
    ├── common.h
    ├── message.pb.cc
    ├── message.pb.h
    ├── message.proto
    └── message_test.cc
```
The problems is how to setup `includePath`, I have tired several configs while none seems optimal:
1. only include project folder `${workspaceFolder}/src` results can't find generated file message.pb.h. 
2. only include build folder ` /nfs/build/project/src` is not optimal. Developer only modify source code in their project folder, the files in build folder are not up to dated. 
3. include both folders results a duplicate header files `common.h` in search path. I find  "Go to definition" function seems confused, it randoms find definition from files in either project folder or build folder. 

May I ask advice on how to setup cpptools extension?

**Comment by sean-mcmanus** [comment]
There might not be an ideal solution, since our extension doesn't understand .proto files and doesn't have any mechanism to map that file to particular generated files.

You could try using the forcedInclude setting to add the specific generated headers to every TU. You could try changing the exclusionPolicy setting to checkFilesAndFolders and setting files.exclude to exclude the common.h, etc. files in the generated directory (you want the generated path to go after the source path in the includePath setting so it takes precedence). Maybe you could write some script in your build process that copies the necessary generated protobuf files to a different location for usage by our tool.

You may also try asking the protobuf community what their solution is (possibly with other editors). Our team uses msgpack, which is a header only lib without any generated files.

**Comment by andl** [comment]
after tried several suggestions, I found the best way that suit for our project is using build script to copy generated files from NFS back to project dir. Thanks a lot.
