### ISSUE TITLE
Debug console output to file on disk have different format

### ISSUE THREAD

**Issue by Rvadrabade** [microsoft/vscode-cpptools#4869]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): No
- A clear and concise description of what the bug is as follows.

**To Reproduce**
Default configuration for build and launch were used.
Steps to reproduce the behavior with sample CPP code and output is available on following repository.

https://github.com/Rvadrabade/gdb

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
This is due to the C++ extension debugger using`gdb` with the flag `--interpreter=mi`. 

The `~` before the output indicates that it is a [console output](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Output-Syntax.html#GDB_002fMI-Output-Syntax).
> console-stream-output →
"~" c-string nl

If you change the following commands to the associated [`mi` commands](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html), You will get the same output.
```
break 19    // for break point at line 19  
run 	    // run program upto break point  
pptrTest    // use custom macro  
continue    // let program finish 
```
Associated commands would be `-break-insert`, `-exec-run`..

**Comment by Rvadrabade** [comment]
So, is there any way of getting same output from vs code without '~' or such similar character as we get from usual terminal gdb commands. 
Main aim is to get output from vs code same as usual gdb like this https://github.com/Rvadrabade/gdb/blob/master/ptrArray_shell.txt instead of https://github.com/Rvadrabade/gdb/blob/master/ptrArray_vscode.txt

**Comment by Rvadrabade** [comment]
Thanks for investing time. Closing this issue.
