### ISSUE TITLE
Request a windows version!!!

### ISSUE THREAD

**Issue by 99FallenAngel99** [microsoft/vscode-cpptools#49]
Please i'm a new coder, please make a windows debugger version, it's so important

**Comment by delmyers** [comment]
Hi @99Minecrafter99 

Trust me, we have heard this feedback from many people over the past couple of months. This is our #1 ask, and we are listening :-)

I'm guessing that the thing that you are requesting here is debugging support on Windows, since we don't have it yet? We are planning on having GDB debugging available for binaries compiled with MinGW and Cygwin in the next release. That will move the dial a little. We are talking about what it would take to get full Windows debugging in the product right now.

**Comment by jacdavis** [comment]
@99Minecrafter99, we added full windows debugging support in our last release. This is in addition to our Cygwin/mingw support that was added in June. 

Thanks
