### ISSUE TITLE
Breakpoints jump when debugging ends

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-cpptools#4902]
Type: Debugger

Version: 1.42.0-insider (system setup)
Commit: f3dbcea32a6b52ce819dc863e778fb8517357f61
Date: 2020-01-24T05:38:14.538Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
C/C++ Extension Version: 0.26.3

The breakpoints I set jump when I start debugging (ok, this makes sense since they aren't resolved yet), and then jump back when I stop debugging. The "jump back" seems confusing and un-needed since at this point the C++ extension should have resolved the breakpoints to their actual location.

To reproduce, use the following sample code and set the break points as in the screen shot:
```c++
#include <iostream>

int doSomeCounting(int startAt)
{
    for (int i = startAt; i < 10; i++)
    {
        std::cout << i
                  << "\n";
    }
}

int main()
{
    std::cout << "Hello, Remote World!"
              << "\n";
    doSomeCounting(3);
    return 0;
}
```
Before debugging:
![image](https://user-images.githubusercontent.com/38270282/73184637-10cdc800-411d-11ea-975c-5206afed0575.png)

During debugging, the breakpoints jump. This seems ok since now the breakpoints are resolved:
![image](https://user-images.githubusercontent.com/38270282/73184734-34910e00-411d-11ea-8c19-3feb181bebb3.png)

But after debugging, they are back in the original place. This is confusing since they have already been resolved to their correct place.
After debugging:
![image](https://user-images.githubusercontent.com/38270282/73184864-63a77f80-411d-11ea-8d4c-23a5c36d1819.png)

**Comment by WardenGnaw** [comment]
The "jump back" happens because the VS Code UI saves where the user has placed the breakpoints.
During a debugging session, the debugger tells the UI where the breakpoint is bound to in a specific file / line and the UI will update based on the location. This location is based on the symbol file. 
Afterwards, the debugging session ends and VS Code restores the original location of the breakpoints. 

This design is based on VS Code keeping the location where the user wanted to put the break point and the movement during debugging is where the debugger actually put a break.
