### ISSUE TITLE
Colorization/Inactive-Regions not working in certain folders

### ISSUE THREAD

**Issue by tgrohens** [microsoft/vscode-cpptools#4959]
- VSCode Version: 1.42.0 (also tested with Insiders build)
- OS Version: macOS 10.15.3
- C/C++ Version: 0.26.3

Hi, I'm having an issue with the dimming of inactive regions in C++.

For the exact same (small) file in two different folders, in one case the dimming works and in the other it doesn't.
I'm not able to tell what the difference is, as there is no Workspace configuration or `.vscode` folder in either folder.

I'm attaching screenshots of both cases.
In this case, dimming works as expected:
<img width="1514" alt="ok" src="https://user-images.githubusercontent.com/302936/74357987-f94f3a00-4dc0-11ea-8c6e-3b0149e2e578.png">

In this case, it doesn't:
<img width="1514" alt="wrong" src="https://user-images.githubusercontent.com/302936/74357983-f8b6a380-4dc0-11ea-8505-46ab38bf2062.png">

I can't really reproduce the issue because when I create a copy of the same `test.cpp` file in a new folder, dimming does work properly.

Any idea what's going on?

Cheers,

**Comment by Colengms** [comment]
Hi @Juiblex .  One side of the #else should be dimmed, no matter what.  So, it look like you are not getting intelliSense for that file.  I suspect you are seeing an issue due to: https://github.com/microsoft/vscode/issues/88455 ( https://github.com/microsoft/vscode-cpptools/issues/4712 ).

One of your paths has the unicode sequence %C3%A9, the other has %C3%A8.  We are likely not remapping the later to the sequence VS Code is remapping it to.  Can you confirm that no files in that directory get intelliSense?

**Comment by tgrohens** [comment]
Hi @Colengms!

I've taken a look at the other issue and I'm not quite sure I'm facing the same problem.

I believe IntelliSense is running, even with accents in the path.
I've recreated a new folder with the same name as the offending folder `Thèse` in a `test` directory, and I've added the snippet from https://github.com/microsoft/vscode/issues/88455 for clarity.
There, I do get both dimming and squiggle, see the screenshot below:
<img width="1514" alt="IntelliSense works" src="https://user-images.githubusercontent.com/302936/74420858-66f47800-4e4c-11ea-9d21-30bd172a5d86.png">

However, in my original folder, I also get the squiggle but there's no dimming:
<img width="1514" alt="IntelliSense fails" src="https://user-images.githubusercontent.com/302936/74421300-16c9e580-4e4d-11ea-996a-4b63e631b59f.png">

One difference I've identified is that the original folder where the bug happens is being synced via [Seafile](https://www.seafile.com/en/home/), but I'm not sure how this would influence things.

**Comment by Colengms** [comment]
Hi @Juiblex .  That is odd.  Inactive and colorization ranges are generated as a result of the very same IntelliSense pass that generates squiggles.  (You are also not getting semantic colorization.  It's subtle, but the variable "x" in your repro is not the same color as the no-repro image).

Could you confirm based on the logs that the new folder you created uses the same encoding as the original one?  (i.e. %C3%A9, or %C3%A8)

Can you repro using a file synced by Seafile that is not within a folder with extended characters?

I noticed one of the images you posted is a .c file, and the other is .cpp .  Is the repro specific to the file extension?

I see that you are using the CMake Tools extension.  Are you using it as a `configurationProvider` in `c_cpp_properties.json`?  In case the repro has something to do with the configuration, can you confirm that both files in your repro either are or are not receiving a configuration from CMake Tools?  Are both files in your CMakeLists.txt, and does the issue persist after running `CMake: Configure`.

Another case in which we know colorization fails is when using VS Code's remoting features, which runs our extension on the remote machine where we do not have access to themes in order to look up colors.  (This will change soon, as we switch to VS Code's new Semantic Tokens API for colorization).  Though, it doesn't look like you're using remoting.

**Comment by tgrohens** [comment]
Hi @Colengms, thank you for taking the time to investigate this.

In order to reproduce everything clearly, I have the following folder structure:
```
./test.c (not Seafile-synced, colorization works)
./Thèse/test.c (Seafile-synced, colorization fails)
./test_thèse/test.c (not Seafile-synced, same %C3%A8 Unicode character in the path, colorization works)
./Livres/test.c (Seafile-synced, ASCII-only path, colorization works)
```

In all cases except in the folder `Thèse`, colorization works as intended, so I'm really not sure what is happening.
I was using the CMakeTools extension for other purposes and the problem remains even when it's uninstalled, and I'm not using remoting either.

I have also noticed a difference when opening the files independently or as part of a folder.
In the first case, the squiggle under the `@` character doesn't show, even though it's logged in the console, but only does when opened as a folder.
I'm not sure whether this is the intended behavior or not.

**Comment by Colengms** [comment]
Hi @Juiblex .  Since the issue is specific to the folder containing an extended character, I'm fairly confident you are seeing the same issue as: https://github.com/microsoft/vscode-cpptools/issues/4712 .  That issue can cause internal comparisons between 2 different representations of the same path to appear unequal.  That would explain why IntelliSense errors are reported to the problems pane, and will navigate to the correct file when clicked, but squiggles do not appear, and colorization is not applied (as some paths comparisons occurring internally fail).

The good news is; the issue has been addressed, and should be fixed in our next Insiders release.  In the meanwhile, you could work around the issue by avoiding use of extended characters in folder names.

**Comment by tgrohens** [comment]
Hi @Colengms. Thanks for fixing this!
I also realized I wasn't getting Git decorations, and it seems like this is the same issue.
I've been using that workaround and I'm looking forward to the next release!
Cheers,

**Comment by Colengms** [comment]
Closing this as a duplicate.
