### ISSUE TITLE
How to reload all symbols

### ISSUE THREAD

**Issue by ueqt** [microsoft/vscode-cpptools#497]
I add `*.pc` file association to `c`
and when I create a new pc file, symbols can load correct
but for my old pc files, no symbols loaded, I can't go to definition to these files
if I create a new file, and copy codes from old pc file, it works for new file

So do we have a command to reload all symbols?

**Comment by sean-mcmanus** [comment]
The behavior I'm seeing is that the symbols get loaded when the file is opened, so you could either open all your old *.pc files or delete/rename the browse database to start over (i.e. do an edit configuration and give the databaseFilename a new value, originally named .browse.vc.db ). We plan to change this in the future so that changing the files.associations will add/remove the symbols for the files.

**Comment by bobbrow** [comment]
This should be fixed in 0.10.2.  Please reopen if you continue to see the issue.
