### ISSUE TITLE
disable IntelliSense when vscode-clangd is detected

### ISSUE THREAD

**Issue by eszlari** [microsoft/vscode-cpptools#4979]
To simplify the setup, it would be nice, if IntelliSense was automatically disabled, when the [vscode-clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) extension is installed.

**Comment by aallrd** [comment]
Hello,
I am interested in this feature as well.
My main usage for the cpptools extenstion is for the debug configurations.
I would be fine with a simple flag to disable all the IntelliSense mechanism (files discovery, parsing, caching, ...).

**Comment by bobbrow** [comment]
It is already possible to disable our extension's IntelliSense with the `"C_Cpp.intelliSenseEngine": "Disabled"` setting.

This request is about automatically doing that when vscode-clangd is detected.  Adding this feature would require another setting to control it and we would not likely want to have it on by default.  Since you would have to go and fiddle with a setting to enable this feature and we already have a setting that does the same thing (albeit without any automatic detection logic), it doesn't seem to make sense for us to do this feature.

We appreciate the feature suggestion, but we will close it for now.

**Comment by aallrd** [comment]
Indeed, I actually found this setting today.  Thank you for pointing it out.

**Comment by Trass3r** [comment]
I've been using
```json
    "C_Cpp.intelliSenseEngine": "Disabled",
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.errorSquiggles": "Disabled",
```
Are the other 2 redundant?

**Comment by bobbrow** [comment]
Yes.  If IntelliSense is disabled, then autocomplete and errorSquiggles settings will not be processed.
