### ISSUE TITLE
Please support  Visual C++ Build Tools 2015.

### ISSUE THREAD

**Issue by MrMYHuang** [microsoft/vscode-cpptools#50]
Please support Visual C++ Build Tools 2015 for debugging:
https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/

**Comment by TurkeyMan** [comment]
Do the Visual C++ Build Tools include the debugger? I thought that was a common complaint/feature request?

**Comment by jacdavis** [comment]
Full windows debugging support was added in our last release. This is in addition to our existing mingw/Cygwin windows debugging support. Please reactivate if this doesn't meet your needs.

**Comment by delmyers** [comment]
@myhlivecom, VsCode is not a full IDE. It does not natively support build/deploy tasks. In order to build using the VC++ tools, you have to download the Windows SDK: 

https://msdn.microsoft.com/en-us/library/ms717422(v=vs.110).aspx

Once you use the SDK to build your application, you can debug it using VsCode.
