### ISSUE TITLE
"PROBLEMS" Tab click does not find a file, obviously there

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode-cpptools#5003]
![image](https://user-images.githubusercontent.com/145155/75174501-f80efd00-5730-11ea-82ac-a9511a2352e4.png)

Issue Type: <b>Bug?</b>

Code is up to date as is the C++ extension. Recently I started noticing this problem .. 

After CTRL+CHIFT+B , I go to "Problems" click to the offending line and message pops up: 

"Unable to open <file name here>: Unable to read file '\': "

Even if I see the said file in the edit above ...

I think this is a recent issue?

Please advise .... 

Extension version: 0.26.3
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @DBJDBJ .  Were these warnings generated by the C/C++ Extension, or were they generated by cl.exe?  Given the compiler warning codes (i.e. C4129), I suspect these are coming from the compiler.  If so, could you look at the build output to see if there is an anomaly with that error message?

You may be seeing an issue with the `$msCompile` problem matcher, which is part of VS Code, not added by the C/C++ Extension.

**Comment by DBJDBJ** [comment]
@Colengms Ignore the code please, it is irrelevant.  I click on the line and  V.Code does not behave as expected. I fail to see how this problem can come from the CL? I repeat: I go to "problem tab", I click on the file name (please see the image) and instead of focus being pushed to the edit window to that line I see the message as on the image.

**Comment by DBJDBJ** [comment]
Please peruse this image

![image](https://user-images.githubusercontent.com/145155/75247472-47593a00-57d2-11ea-9e3c-f06eb0ae9480.png)

VScode error message says "unable to resolve non existing file ....", while that same file is in the editor above ... Huh?

Lines 34, 35 in the code are deliberate mistake.

**Comment by Colengms** [comment]
>I fail to see how this problem can come from the CL? I repeat: I go to "problem tab", I click on the file name (please see the image) and instead of focus being pushed to the edit window to that line I see the message as on the image.

The C/C++ Extension is not the only source of items on the Problems tab.  Compile errors are also reported on the Problems tab.  When a problem is reported by the C/C++ extension, it is either followed by "C/C++", or just the line and column numbers.  i.e. :

![image](https://user-images.githubusercontent.com/49173979/75274807-57fcb680-57b8-11ea-8ad1-a13478d053a5.png)

![image](https://user-images.githubusercontent.com/49173979/75274239-5979af00-57b7-11ea-9129-446e61d5a068.png)

When a problem is the result of a compile error, it will be followed by the source of the error.  i.e. :

![image](https://user-images.githubusercontent.com/49173979/75274306-7c0bc800-57b7-11ea-87fb-302f3ac72669.png)

Given that your output indicates what appear to be a CL.exe error codes, (i.e. [C4129](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4129?view=vs-2019), [C4477](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4477?view=vs-2019), [C4530](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4530?view=vs-2019)), I suspect you are looking at compile errors.

Compile errors are shown in the Problems list using a 'problem matcher' ([Defining a Problem Matcher](https://vscode-docs.readthedocs.io/en/stable/editor/tasks/#defining-a-problem-matcher)).  In the case of CL.exe, the problem matcher is built into VS Code (not part of our extension).  (It is referred to here: [Processing task output with problem matchers](https://code.visualstudio.com/docs/editor/tasks#_processing-task-output-with-problem-matchers))

The failure to open a file would seem to be a problem with the `msCompile` problem matcher.  If you can identify the compile error message that is not being parsed correct, we could look more closely at the issue.  It looks like the issue may be related to an extended character in the path.

If you feel the issue is actually coming from the C/C++ Extension, could you provide a self-contained example that we can use to reproduce the issue?  This is not a known issue.

**Comment by DBJDBJ** [comment]
Thanks ... Your reply is informative but what might be the role of the "Create File" blue button in case of pure compilation errors? 

This info Might help: In case I actually click on that "Create File" button it creates the empty file, but in the root of the drive, in my case D:  ... 

It might be my setup, but VC builds and debugs completely OK in this and other projects...

ps: problem matcher is correctly set `"problemMatcher": "$msCompile"`

**Comment by DBJDBJ** [comment]
> 
> 
> Hey @Colengms, this issue might need further attention.
> 
> @DBJDBJ, you can help us out by closing this issue if the problem no longer exists, or adding more information.

I have not seen (and have forgotten about) this issue for  months. I might consider it closed.
