### ISSUE TITLE
Autocomplete not work correctly (std::cout for example)

### ISSUE THREAD

**Issue by eduluc12** [microsoft/vscode-cpptools#508]
Hi, I have a question when I typed std:: of the library iostream in VSC this not autocomplete correctly for example I need std::cout but this not appear.

**I use Visual C++ for the compilation** 

![image](https://cloud.githubusercontent.com/assets/20527692/23093842/8e430684-f5bb-11e6-9175-508e82b25edd.png)

![image](https://cloud.githubusercontent.com/assets/20527692/23093847/a304033e-f5bb-11e6-8b71-151c2d34598b.png)

Thanks and sorry for my english :)

**Comment by sean-mcmanus** [comment]
This is a bug (should be fixed in our next update). We are accidentally not shipping the "cpp.hint" file as part of our .vsix. As a workaround, you can add the file "cpp.hint" to Users/\<user\>/.vscode/extensions/ms-vcode.cpptools.-0.10.1 with contents:

#define _STD_BEGIN namespace std {
#define _STD_END } ;
#define _STD std::

Or on Linux:

#define _GLIBCXX_VISIBILITY(arg)

But you'll need to get your .browse.vc.db to be regenerated (via deleting it or renaming the databaseFilename).
That is not the complete cpp.hint file, but it's the most important part for getting STL stuff working correctly, and you can add more stuff if you find other issues (i.e. important macros not being processed).

**Comment by bobbrow** [comment]
This should be fixed in 0.10.2.  Please reopen if you continue to see the issue.
