### ISSUE TITLE
a question about symbols dispalyed in outline

### ISSUE THREAD

**Issue by culyee** [microsoft/vscode-cpptools#5092]
**Type: LanguageService**
Recently, I have been doing work about display in vscode's OUTLINE. Now, I meet a problem as described:
There is a single file, when Ido some changes, like deleting some lines:
delete the enum member `FRI`
![image](https://user-images.githubusercontent.com/56422381/76387820-b02fdd00-63a2-11ea-8aea-8224e9300f7d.png)
cpptools update data immediately and correctly in OUTLINE , but mine doesn't.
![image](https://user-images.githubusercontent.com/56422381/76387701-84acf280-63a2-11ea-8a81-2adf63879368.png)

so I wonder how cpptools tell OUTLINE to change, or whether there is an interface or a function in cpptools code?  
It bothers me for a long time. Look forward to your advice, thanks.

**Comment by sean-mcmanus** [comment]
I'm not sure what you mean by "mine", but an old version of our extension would not update the Outline view after an edit -- we added code a year or so ago in our language server process that reparses the file 3 seconds after an edit, i.e. if you set the C_Cpp.loggingLevel to "Debug" you should see something like:
```
cpptools/getDocumentSymbols
  tag parsing file: 
```
so that reparse allows us to send back the updated symbols.

The TypeScript that sends the message is at https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts#L692 .

**Comment by culyee** [comment]
@sean-mcmanus Hi sean, thanks for your answer. "mine" means the extension I developed. I have read the code you provided, but i didn't find any event that can notify language server process to reparse the  file. can you tell me  which event can lead to reparsing?

**Comment by sean-mcmanus** [comment]
The file is reparsed in response to https://microsoft.github.io/language-server-protocol/specification#textDocument_didChange .

...and also didClose in case the user edits a doc and then closes it without saving.

**Comment by culyee** [comment]
@sean-mcmanus  Hi sean, thank you very much. Based on  your advice,  I have solved my  problem.
