### ISSUE TITLE
clang-format stops working with 0.27.0-insiders2

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5095]
I'm encountering this bug on the latest VSCode and insiders CPP release. Clang format suddenly stops working until a restart. (not using multi-root)

_Originally posted by @jeremyong in https://github.com/microsoft/vscode-cpptools/issues/3145#issuecomment-597615083_

**Comment by sean-mcmanus** [comment]
@jeremyong That issue sounds different from our other clang-format issues -- most likely the main input thread is getting stuck -- does hover also get stuck saying "Loading..." when formatting fails?

Also, it sounds like 0.26.3 is reproing the issue so it's an existing issue. It could have been fixed by one of the many other fixes though, so maybe we should wait till we release 0.27.0-insiders3 to see if the issue still repros.

**Comment by jeremyong** [comment]
Thanks for opening this issue. Hover and other intellisense features seemed to work ok as far as I can remember. I'll keep an eye out the next time it happens.

**Comment by davidwin** [comment]
I used to run into this issue all the time with earlier release versions of VS Code, but since VS Code changed to showing the progress during save operations, the issue is now that save can suddenly start taking an unreasonably long time to complete. 

I don't know if this is the same issue or a new one, but now on VS Code 1.43.2 and C++ 0.27.0, saving a single file can take 20 seconds. During this time, the `cpptools` process consumes a whole CPU thread, and goes idle as soon as the save completes. However, the file is eventually formatted, which is a change from before when it appeared as if formatting just stopped working (but saving never took any noticeable time to complete then, because I believe that VS Code simply gave up and terminated long-running save/formatting operations).

The logs don't show anything terribly interesting while saving. I run the extension mostly in Remote WSL mode with a custom path to clang-format 4.0. The clang-format process never appears in the Task Manager.
![image](https://user-images.githubusercontent.com/9844625/78050480-915ab000-737c-11ea-928b-590bf7392422.png)

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
