### ISSUE TITLE
formatter stops working

### ISSUE THREAD

**Issue by Victrid** [microsoft/vscode-cpptools#5109]
**Type: LanguageService**

After I installed the new release 0.27.0-insiders2, my formatter stopped working. It prints error in log window as `libtinfo.so.5: cannot open shared object file: No such file or directory. ` Not occured to me while using older versions and when I falled back to older version 0.26.3, the formatter returned to normal.

**Describe the bug**
- OS and Version: Arch Linux (Kernel 5.5.8-arch1-1)
- VS Code Version: Code-OSS 1.42.1
- C/C++ Extension Version: 0.27.0-insiders2
- No other extensions are related to.
- Local run.
- Shows error in log `libtinfo.so.5: cannot open shared object file: No such file or directory. `
Single file, using "Format document", and formatter not working.

**Steps to reproduce**

1. Press Ctrl+Shift+I; or Ctrl+Shift+P, choose "Format document"
2. Popup like "formation cannot be done". Error mentioned above in C/C++ log.

**Expected behavior**

The file should be formatted.
This error starts after I received the test. When I rolled back to the old version 0.26.3 and it works well. The whole system and dependences are fully updated.

<details>
  <summary><strong>Logs</strong></summary>

```
libtinfo.so.5: cannot open shared object file: No such file or directory
```
</details>

**Comment by michelleangela** [comment]
@Victrid 

0.27.0-insiders3 has not been released yet. Did you mean 0.27.0-insiders**2**?

**Comment by Colengms** [comment]
Hi @Victrid .  There was an old build of clang-format bundled with our last insiders build.  It should be fixed with our next insiders build (very soon).  In the meanwhile, you should be able to work around the issue by:
 * Deleting the contents of: `~/.vscode/extensions/ms-vscode.cpptools-0.27.0-insiders2/LLVM/bin`
 * Deleting the `install.lock` file in `~/.vscode/extensions/ms-vscode.cpptools-0.27.0-insiders2`
 * Reloading VS Code

**Comment by Victrid** [comment]
My fault. It's 0.27.0-insiders2. （//▽//）
The formatter works well now.
