### ISSUE TITLE
Add check to ensure offline/insiders vsix is installed on correct platform

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#5119]
Installing a win32 cpptools vsix on Linux, for example, results in an error that the native binary is missing.  (Which is correct, as a different filename is used on each platform).  Perhaps existance of the wrong binaries could surface an indication of what is wrong, and fall back to downloading if possible.

**Comment by sean-mcmanus** [comment]
For Mac binary detection we can check for LLVM/bin/clang-format.darwin, because we forgot to rename that binary.

The downloading fallback is not a good option for Insiders, because the binary is most likely out-of-date (in fact, we should probably make that impossible or detect a mismatched binary version, in case the install.lock is somehow deleted).

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
