### ISSUE TITLE
Handle standard version (etc) appropriately depending on version of cl.exe

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#5127]
Currently, we don't probe cl.exe.  However, if the user specifies an intelliSense mode of `c++latest` (either via the setting, or command line arguments to the compiler), it may mean something different depending on what version of cl.exe they have installed.  We should check the compiler version, and map this to the correct intelliSense mode for the compiler.

**Comment by sean-mcmanus** [comment]
We don't allow c++latest in the settings yet, since it's a cl.exe-only value (only the command line, for 1.0), but maybe we could add that later.

It would also be good to change the --microsoft_version <val>, _MSC_VER, and _MSC_FULL_VER defines (they're currently hardcoded to the "latest" version in the msvc.*.json files).

**Comment by Colengms** [comment]
Although we don't allow `c++latest` in a cppStandard/cStandard setting, we do accept `/std:c++latest` as a compiler arg, in `compilerArgs`, `compile_commands.json`, or received as a compiler arg from a custom configuration provider, and should do the right thing.

**Comment by diablodale** [comment]
Hi. This topic I might be broader than just the specific case of the OP.
I suggest the broader is...

### How configure intellisense language compliance

* How to read `settings.json` to get the language compliance chosen there with the value from `cppStandard`. The declared settings in a settings file, I believe, should always and without exception, be the chosen compliance. Nothing is more important than the dev's explicitly chosen setting.
* Then a series of fallbacks in a predetermined order including such as (order unsure)
  * reading from `compile_commands.json`
  * reading from `cmake`
  * reading from `cl`
  * 🎲 etc.

I'll give an example. This cpp extension fails to correctly operate when compiling official OpenCV project. I'm a frequent contributor to that project. While working on a recent PR, I caught that this cpp extension was incorrectly allowing C++14 features when I had specifically declared I wanted C++11 language compliance using `cppStandard` in both locations. It was allowing `std::get<T>()` which is not in the C++11 standard. 11 only supports int index into a tuple.

```json
c_cpp_properties.json
{ ...
"cppStandard": "c++11",
}

settings.json for the workspace
{ ...
"C_Cpp.default.cppStandard": "c++11"
}
```

In the output c++ config window, I saw
```
[8/14/2021, 1:46:10 PM] For C++ source files, the cppStandard was changed from "c++11" to "c++14" based on compiler args and querying compilerPath: "cl.exe"
[8/14/2021, 1:46:10 PM] For C++ source files, the cppStandard was changed from "c++11" to "c++14" based on compiler args and querying compilerPath: "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe"
...
```

Naturally this is errant. While my compiler `cl` might support 14, 17, and latest...I have specifically chosen C++11. Why 11? Because the OpenCV project is designed to be compiled/used with any C++11 toolchain. Therefore, the code written within it can only be C++11. For big infrastructure projects...this is likely common. They are not coded with the newest language features to be compiled with the newest toolchain.

OpenCV project uses cmake. Here is some info from my toolchain on Windows 10 compiling OpenCV.

```
line from compile_commands.json
"command": "C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe  /nologo -DNO_FSEEKO -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_VARIADIC_MAX=10 -I..\\3rdparty\\zlib -I.  -DGLOG_NO_ABBREVIATED_SEVERITIES -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000005 /arch:AVX /Gw /QIntel-jcc-erratum /guard:cf /GS  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS         /arch:AVX /wd4267 /MDd /Zi /Ob0 /Od /RTC1  /Fo3rdparty\\zlib\\CMakeFiles\\zlib.dir\\gzwrite.c.obj /FdTARGET_COMPILE_PDB /FS -c C:\\repos-nobackup\\opencv\\3rdparty\\zlib\\gzwrite.c",

lines from CMakeVars.txt
CMAKE_CXX_STANDARD=11
CMAKE_CXX_STANDARD_COMPUTED_DEFAULT=14
CMAKE_CXX_STANDARD_DEFAULT=14

lines from OpenCVDetectCXXCompiler.cmake
  ocv_update(CMAKE_CXX_STANDARD 11)
  ocv_update(CMAKE_CXX_STANDARD_REQUIRED TRUE)
  ocv_update(CMAKE_CXX_EXTENSIONS OFF) # use -std=c++11 instead of -std=gnu++11
```
