### ISSUE TITLE
IntelliSense does not work in 0.27.0-insiders3 on Windows 10 1909

### ISSUE THREAD

**Issue by nilsgaebel** [microsoft/vscode-cpptools#5147]
Type: IntelliSense does not work after Update on 0.27.0-insiders3

**Describe the bug**
- Windows 10 Pro 1909:
- VS Code Version: 1.43.0
- C/C++ Extension Version: 0.27.0-insiders3
- IntelliSense does not work after the Auto-Update. After the Downgrade on 0.26.3 IntelliSense works again for C-Programming. I only installed the recommended Extension C/C++ and C++ Intellisense for C-Programming.

**To Reproduce**
1. Install the Extensions C/C++ and C++ Intellisense
2. IntelliSense works for C-Programming on my System.
2. After restarting VS Code I get automatically the Upgrade on Version 0.27.0-insiders3
3. IntelliSense does not work for C-Programming...

**Comment by Colengms** [comment]
Hi @nilsgaebel .   I suspect the issue you are seeing is due to installing multiple extensions that provide language services for C/C++.  Please uninstall any other extensions that provide IntelliSense for C++ when using the "C/C++" Extension for VS Code from Microsoft.

If that is not the cause of the issue you are seeing, could you please provide more information, including :
 * The contents of your `c_cpp_properties.json`, if any.
 * Enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, and provide the output of the C/C++ output channel leading up to the repro.
 * The results of invoking the command: `C/C++: Log Diagnostics`, while you have a file open that is not working as expected.
