### ISSUE TITLE
Where is the MFC example?

### ISSUE THREAD

**Issue by ruifortes** [microsoft/vscode-cpptools#5207]
Guess this is more of a "governance" related question but still...
Why can't I find a simple example for a MFC app?
I've installed the 2017 build tools and I want to use VSCode instead of the full blown VStudio.
I'm finding hard to believe that I'm going to have to understand all the nuts and bolts just to make a simple MFC app!?
It's just some (large number of) configs for crying out loud. Isn't there a json I can copy/paste?
I'm I being pushed to VStudio here??

**Comment by sean-mcmanus** [comment]
We don't have any MFC examples. There are samples for Visual Studio at https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-samples?view=vs-2019#mfc-samples---advanced . I have not see anyone use Visual Studio Code or our C++ extension for MFC. I think using Visual Studio is preferred for MFC apps. Otherwise, you'd have to setup all the build details yourself.

**Comment by ruifortes** [comment]
I understand it's the "preferred way" but nevertheless I don't understand the overhead justifying not providing a simple pathway to do so.
Actually I think the lack of that pathway is the main reason you don't see anyone use Visual Studio Code.
I don't need auto code generation UI stuff but I surely appreciate some way to manage the insane configuration necessary to call a "simple" command line program.
I'm not saying the compiler is a "simple program" but the way it is invoked.
I just want to understand the reason why there's no proper and simple documentation for this.
It could even be a commercial strategy, I'm just asking

**Comment by ruifortes** [comment]
Microsoft own github and consequently Atom right?
Also it owns Atom competitor VSCode and,  although with a community free version,  the full blown professional Visual Studio.
It's not far fetched to think there could be some commercial strategies involved.
At least some fine tuning of how much Microsoft would push development in each one of those packages.
I'm not a fan of highly automated mechanisms when they hide and prevent addressing unnecessary complexity  and also because they push for higher software lock.
I not a professional C++ developer buy I would like to use the more "simple and bare-bones VSCode to develop some C++ applications (actually plugins for other software that use MFC)
Although Microsoft might have the right strategize the users also have the right to ask and confront you.
I might be completely wrong in my assertions, last time I did something in C++ I'm not even sure there was MFC.
So.... if somebody care to tone down my conspiratorial theory tendencies I would appreciate  :-)
Thanks

**Comment by sean-mcmanus** [comment]
We have docs at https://code.visualstudio.com/docs/languages/cpp. From our team's perspective, MFC is just another external library framework, so it would be up to the MFC owner or community to provide samples/docs on specific setup. The same would apply other other libraries like QT, Direct3D, OpenCL, OpenCV, etc. Some libraries like PlatformIO provide a specific extension which deal with all the configuration for the library by writing a cpp_properties.json, and other libraries implement our configuraiton API: https://github.com/Microsoft/vscode-cpptools-api .

GitHub and Atom operate independently (or part of a different team, not sure). I'm not aware of any commercial strategy between the editors, although we do consider Visual Studio to be the premium solution for developers on Windows since it has more features implemented in it (and it has a more restrictive license).

**Comment by ruifortes** [comment]
Is it fair to assume that compiling C++ MFC will boilds down to calling cl.exe with a bunch of arguments and some environment variables defined?
Visual Studio, although premium, seams to lack a feature to export those settings VSCode, on the other side, seams to lacks the import ones.
Am I wrong? What am I missing here?

**Comment by sean-mcmanus** [comment]
I am not familiar with the details of compiling an MFC project. All the docs I've seen are based on compiling using Visual Studio. If you'd like documentation on how to use MFC with Visual Studio Code, you might try posting an issue at https://github.com/MicrosoftDocs/cpp-docs/issues .

There is no feature to transfer settings between Visual Studio and Visual Studio Code, but if you build using CMake and also use the CMake Tools extension then the build details can be shared that way, so you can open the same folder and build out of the box (or nearly so).
