### ISSUE TITLE
use LSP to send VisibleRanges from the client to server

### ISSUE THREAD

**Issue by culyee** [microsoft/vscode-cpptools#5246]
It seems that cpptools use `TextEditorVisibleRangesChangeEvent` to colorize a few dozen lines of one code file. 
I have been developing a extension colorizing symbols, and I use `lsp` to send VisibleRanges from the client to server. When I  scroll down/up, it will send couples of VisibleRanges to server, but in fact, I just need the last range data that I stop at last.

My question: I wonder how cpptools solves this problem, can you give me some suggestions?

**Comment by Colengms** [comment]
Hi @culyee .  We use the current visible ranges to provide color information for semantic tokens because providing color information for the entire file did not result in acceptable performance for large files.  The ranges we received at any given time seem to completely describe what is visible, and we return color information for everything described by those ranges.  I'm not sure I understand what you mean by "I just need the last range data that I stop at last.".

We will actually be moving away from colorizing ranges ourselves, when we switch to using the new VS Code API for semantic tokens.
