### ISSUE TITLE
no intellisense. please assist

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cpptools#527]
hi team.
vscode is up to date (latest), Win10/x64, c++/msvc2015 build tools.

I remember I was facing with the same issue a lot time ago , but don't remember how to solved this.
please remind:
no intellisense functionality for standard library , but build process is okay.
it just shows a tooltips with a symbols from current folder and subfolders only.
(CMakeTools is in use for the build)

just for sure: header files of the standard library are included and recognized by vscode, I can navigate throu these e.g. by Ctrl+click, but no symbols from those are showed

**Comment by sean-mcmanus** [comment]
Changing the c_cpp_properties.json setting limitSymbolsToIncludeHeaders to false will cause the files in the includePath to be parsed and symbols to be generated. Otherwise, it will only parse includePath files that have been #included by a C++ file under the ${workspaceRoot}. However, we have some random bugs we're currently fixing which may cause some files not to be parsed, if you think you're hitting that. Deleting the .browse.vc.db (or changing the databaseFilename property) will cause stuff to generate and things might be fixed.

**Comment by amigo421** [comment]
there is no file *.vc.db
how to generate this? 
by the way, I didn't use c_cpp_properties.json (was no such file) but , okay, let me try to generate this

**Comment by sean-mcmanus** [comment]
It should be under C:\Users\\<user\>\AppData\Roaming\Code\User\workspaceStorage . You can also give a new location with the databaseFilename setting (in c_cpp_properties.json). In some cases it might appear in the %tmp% directory.

**Comment by amigo421** [comment]
ah, I see, I previuosly thou that db file in .vscode like "large" VS keeps this in .vs subfolder.
and yes, cleaning up those folders (with db files) solved the problem. 
thank you!

**Comment by sean-mcmanus** [comment]
Yeah, we used to put the database in the workspace .vscode folder by default, but we changed it for some reason. And we're planning to fix problems that can cause the database to need to be deleted.
