### ISSUE TITLE
includePath setting on Win platform

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cpptools#534]
please add pre-set the paths to known include folders, VC+WinSDK.
I see you added to VC include folder (by the way, I have an installed VC 14 and 15, but only 14 was added into the paths),
but didn't do this for all (all means shared, um, ucrt, winrt)  folders from Windows Kits.
I believe you know this better than me how to detect the installations of WinSDKs.
I suppose this can be determined from registry and env variables, like it does "big" VS

please add this into auto-configuring of c_cpp_properties.json

Thank you!

**Comment by sean-mcmanus** [comment]
Yeah, it's been on our TODO list for a long time. We don't have an ETA yet.

**Comment by bobbrow** [comment]
@amigo421, how would you like for this to work?  Hard-coding specific paths into the extension doesn't always result in the behavior everyone expects (as you've noted above) and requires us to update the extension whenever new SDK versions are released.  Since both the VC and Windows SDKs update periodically and developers don't always want to target the latest SDK (perhaps they have a preview SDK installed) we're likely to pick the wrong SDK sometimes.

I was thinking that if we added a new command to the extension to help you select which common SDKs you would like to target, that would give you more control over what gets added to the include path.  Invoking the command would drop down a list of SDKs detected and selecting one would add it to the include path for you.  How far we want to go with the detection logic is a question for later, but on Windows we could start with the VC and Windows SDKs.

**Comment by amigo421** [comment]
thank you for the detailed reply. 
first of all, when I was talking about includePath , I kept in the mind a navigation (throu the sources) only, not a build process itself.
your extension (or vscode itself) doesn't support  c++ build systems like cmake/qmake/msbuild natively. so I suppose that a selection of the kit should be a responsibility of the build system setting.

you can see how cmake-tools perfectly works and provide a lot of abilities in the settings of the build, debug and testing. I'll try to ask the author for this ability as well, like cmake-tools expose the ability to select: c++ toolchain, cmake target to build, target to debug, to test.

![image](https://cloud.githubusercontent.com/assets/3259933/23625729/3886deac-02bb-11e7-90c6-11695703f8fc.png)

so my request here was about code navigation only, 
please look at the screenshot  you see a buttons to select e.g. c++ toolchain, so similar SDK selection would be useful.

from my persspective (user's one) ideal way is - if you could discuss with cmake-tools author to use the same buttons in the status line (to avoid a mess) for the selection toolchain (and standard library  headers) and SDK (windows headers respectively

**Comment by bobbrow** [comment]
In 0.11.0, we updated the default include paths to be more dynamic based on SDKs you have installed.  We detail the defaults a bit more here in the "Error Squiggles" section: https://blogs.msdn.microsoft.com/vcblog/2017/04/25/visual-studio-code-cc-extension-april-2017-update

**Comment by amigo421** [comment]
yes, thank you I saw this in the update. 
I think the request can be treated as done

**Comment by sean-mcmanus** [comment]
Okay, let us know if you encounter any further issues.
