### ISSUE TITLE
Localize some phrases/words in autocomplete info

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5370]
Localize following words/phrases:

- "preprocessor keyword"
![image](https://user-images.githubusercontent.com/38734287/80421599-946c9180-8891-11ea-93cb-145a72003771.png)

- "overloads"
![image](https://user-images.githubusercontent.com/38734287/80421648-a9e1bb80-8891-11ea-925d-f7f9de8d9a78.png)

- "specialization"

**Comment by Colengms** [comment]
Since these aren't log messages, we're either going to need a new request/response so the native code can ask the TypeScript side to provide a localized string, or we'll need to reroute completion through the equivalent TypeScript provider class to allow the TypeScript side an opportunity to do localized string replacement before returning the results.

**Comment by Colengms** [comment]
Since it's going to require the same solution, merging this issue with https://github.com/microsoft/vscode-cpptools/issues/5340.
