### ISSUE TITLE
C/C++ Intellisense failed at linux kernel "init/main.c" 

### ISSUE THREAD

**Issue by WittHickmanYoung** [microsoft/vscode-cpptools#5400]
I am working on linux kernel. After compile to generate essential header file. Intellisense start to analyse source file. But there are 177 problems in "init main.c". 
1. line 109: "extern void init_IRQ(void);", report: declaration is incompatible with "int init_IRQ()" (declared at line 888),  but it is  funcall at line 888.
2. line 119: "bool early_boot_irqs_disabled __read_mostly;", report: declaration is incompatible with "<error-type> early_boot_irqs_disabled" (declared at line 916), __read_mostly is a variable modifer.
3. line 132: "void (*__initdata late_time_init)(void);", report: expected a type specifier, __initdata is another modifer.
4. line 193: "bool had_early_param = false;", report: identifier "false" is undefined

**Comment by Colengms** [comment]
Hi @WittHickmanYoung .  I suspect the issue is due to various defines that are set by the build system (Makefile) that would need to be configured (in c_cpp_properties.json) in order for the extension to parse headers as expected.  You may be able to infer defines and include paths based on the command lines invoked by the build system.

In the future, we hope to make available a custom configuration provider (like CMake Tools) which can infer the appropriate configuration directly from make files.

**Comment by WittHickmanYoung** [comment]
It’s confusing to use C/C++ Intellisense under Linux Kernel developing, even after adding header files folder: /use/include/, /use/include/Linux/, /use/lib/gcc/$(gcc-version)/include/, $(workspaceFolder)/include/.

**Comment by mebuis** [comment]
I have the same problem
I want to use vscode to debug linux kernel....

**Comment by Colengms** [comment]
Hi @WittHickmanYoung @mebuis .  Could you give the [Makefile Tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools) extension a try?  Linux kernel is one of the projects we tested when developing that extension.  It should help you configure IntelliSense properly.
