### ISSUE TITLE
undefined variables in sub function (nested functions GCC extension)

### ISSUE THREAD

**Issue by stepan87-henesi** [microsoft/vscode-cpptools#5431]
let's say we have code.

int main()
{
 int a;
 void test()
 {
   a=0; 
 }
....
return 0;
}

will show error on line a=0; 
identifire "a" is undefined

**Comment by michelleangela** [comment]
Is defining a sub function valid code? I tried compilers GCC, Clang, and MSVC from https://godbolt.org/ and your example code does not compile. Is there a different compiler that compiles this code or is there a mistake in the provided example code?

The provided example code that I tried to verify:
```
int main()
{
    int a;
    void test()
    {
        a = 0;
    }
    return 0;
}

**Comment by michelleangela** [comment]
Nested functions are supported by GCC extension. There has been an issue reported on this as well. 
at https://github.com/microsoft/vscode-cpptools/issues/1035. 

Since the C/C++ extension IntelliSense component is shared with Visual Studio's, please up-vote the feature request at https://developercommunity.visualstudio.com/content/problem/794903/intellisense-in-gcc-mode-does-not-recognize-nested.html
