### ISSUE TITLE
File parsing hang at 2% (1728 files out of 76000)

### ISSUE THREAD

**Issue by phonenaing05** [microsoft/vscode-cpptools#5439]
**Type: LanguageService**

I have VS code version 1.45.0 on window 10 and C/C++ extension version 0.28.0-insider2 and disabled other extensions in my workspace.
When I hover the mouse over parsing file status, it seems to hang at 2% of 76k files. I can see cpu usage by C/C++ extension at ~30%. I think parsing is still ongoing, at very slow speed like +1 file every 2 mins..

**Comment by sean-mcmanus** [comment]
If you set C_Cpp.loggingLevel to "Debug" and check the "C/C++" pane you can see more diagnostic info. If you see "Processing folder (recursive)" on startup for a large folder you don't care about getting symbols for, you can add that to your files.exclude setting. Also, you could the same if you "tag parsing" messages for files that you want to skip.

Also, the 2% message or +1 file every minute is most likely a known deficiency with our status reporting caused by dependencies being tag parsed, so it sound like it's parsing include dependencies (you could confirm that via the logging).

**Comment by phonenaing05** [comment]
Sean thanks for your response. Yes, "tag parsing" is ongoing when I look at C/C++ logging output. 
Updating file.exclude speed thing up for me.
