### ISSUE TITLE
Intellisense only "sees" variables declared in included header files

### ISSUE THREAD

**Issue by majodi** [microsoft/vscode-cpptools#5448]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Cataline 10.15.4
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.28.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): all (except ms-vscode.cpptools) disabled
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Bug: my variable doesn't show up in intellisense (new hello world cpp file)

For a while I just accepted the fact that intellisense is not working very good with cpp as I just occasional use cpp but now I would like to know why. I'm used to good intellisense like for TypeScript (which works great). But with the cpp extension even a variable one line up isn't recognized. However a variable from a header file is. What could be the cause?
I read some old issues about local variables not being recognized or picked-up by design. But I can not believe that would still be the case after years.

**Steps to reproduce**

Create cpp file and start typing name of an existing variable

**Expected behavior**

Intellisense should provide a list of symbols with the existing variable in it while typing

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.

File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/*.js.map
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Search exclude: **/.vscode
Populate include completion cache.
Discovering files...
  Processing folder (recursive): /usr/local/Cellar/gcc/8.2.0/include/c++/8.2.0/
  Processing folder (recursive): /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin18.2.0/8.2.0/include/
  Processing folder (recursive): /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin18.2.0/8.2.0/include-fixed/
  Processing folder (recursive): /Users/majodi/Documents/PlatformIO/Projects/intellisense/
  Discovering files: 865 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Done parsing open files.
using Tag Parser for quick info
idle loop: reparsing the active document
  tag parsing file: /Users/majodi/Documents/PlatformIO/Projects/intellisense/helloworld.cpp
Offering completion
idle loop: reparsing the active document
  tag parsing file: /Users/majodi/Documents/PlatformIO/Projects/intellisense/helloworld.cpp

```
</details>

**Screenshots**

<img width="616" alt="Screenshot 2020-05-09 at 15 59 28" src="https://user-images.githubusercontent.com/15524886/81476194-cde9b900-9210-11ea-848c-c20309ff829e.png">
**Additional context**

**Comment by Colengms** [comment]
Hi @majodi .  I'm not able to easily repro.  There may be some detail about your configuration that is influencing the repro.  Can you run the `C/C++: Log Diagnostics` command, and post the output?  That should tell us how the file is configured.

Also, can you provide a complete example?  It may be that the parser is failing on something prior to this code, or in a header, causing the rest of the file not to be parsed.

Also, I see based on the output above that the file has not yet been parsed by the IntelliSense parser.  When that completes, you should see something like:

````
cpptools/finishUpdateSquiggles
Error squiggle count: 1
Update IntelliSense time (sec): 0.262
````

In fact, I don't see the following anywhere in your log:

```
Queueing IntelliSense update for files in translation unit of: <file>
```

Perhaps features of the extension are disabled via settings?  i.e. ` "C_Cpp.intelliSenseEngine": "Disabled"` or `"C_Cpp.errorSquiggles": "Disabled"` ?

If your log level is not set to "Debug", could you post a log with it set to "Debug" ?

Is it possible that you have another extension installed that is providing language services for cpp files instead of our extension?  (i.e. the "C++ Intellisense" extension.  It cannot be used simultaneously with our extension).  Or, perhaps the Language Mode (bottom of the window when editor is active) is not set to "C++" ?

**Comment by majodi** [comment]
Sorry for the late response, I only just saw your response.
Today with a fresh start I did not experience the problem so I think it must be something happening over time that triggers the behavior I described. At least I now know where to look for clues. So I will report back when it happens again.
