### ISSUE TITLE
Structural binding doesn't work (language standard needs to be set to c++17)

### ISSUE THREAD

**Issue by mdj982** [microsoft/vscode-cpptools#5478]
Issue Type: Bug

Got error "identifier not defined" in structrual binding in ver.0.28.0 
It has been worked well until ver.0.27.1

![Screenshot from 2020-05-13 15-52-54](https://user-images.githubusercontent.com/16437623/81780815-1c10fc00-9532-11ea-8cf0-afac6ebc8da6.png)

Extension version: 0.28.0
VS Code Version: 1.44.2  (commit: ff915844119ce9485abfe8aa9076ec76b5300ddd)
OS: Ubuntu 18.04 LTS (Linux x64 5.5.9)

**Comment by michelleangela** [comment]
Structural binding is in C++17, and the set default language standard is probably C++14 based on the default compiler's default language standard. If you set the cppStandard to "c++17" in c_cpp_properties.json this will resolve the issue.

**Cause of changes:**
Before version 0.28.0 of the extension, the language standard would just default to C++17. In 0.28.0, the extension will try to find the default compiler's default language standard and use that instead. This was done because some preferred to use the default language standard from the default compiler.

We'll need to revisit on what the default language standard should be, as for some cases it's preferred to get the compiler's default standard, and for some it is preferred to use maybe the highest version the default compiler supports.

**Comment by mdj982** [comment]
It works well now, thank you very much.

**Comment by ghost** [comment]
I noticed, however, that if you configure with compile_commands.json, it still defaults to c++14 -- even if the compile_commands.json specified c++17.  See https://github.com/microsoft/vscode-cpptools/issues/5463#issuecomment-627613637

**Comment by bobbrow** [comment]
@ryanpholt I moved your comment to a new issue.  The OP's issue has been addressed, so we will close this one.  Thanks!
