### ISSUE TITLE
Adopt use of CancellationError when rejecting requests to providers cancelled using CancellationToken

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5487]
[2020-05-13 14:04:53.007] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2020-05-13 14:04:53.007] [exthost] [error] undefined

I used the repro at https://github.com/microsoft/vscode-cpptools/issues/5481 and type "style::".

**Comment by Colengms** [comment]
It looks like VS Code issued the cancellation, so it's unclear why then calling reject() on that promise would cause an "error" to be reported.  We get a similar error with (not yet checked in) semantic tokens requests, when cancelling a request for the purpose of informing VS Code it should re-issue the request (a scenario that is supposed to be supported, by design) after edits have made the previous request stale.

I think this is actually a VS Code issue.  These scenarios are not errors.

**Comment by Colengms** [comment]
VS Code is tracking the need for rejection types that aren't considered errors, with this issue: https://github.com/microsoft/vscode/issues/93686

**Comment by Colengms** [comment]
It looks like the linked VS Code issue has been addressed, and we can now reject with a `vscode.CancellationError` to suppress logging of an error.
