### ISSUE TITLE
Can I have different include paths based on in which folder I am?

### ISSUE THREAD

**Issue by akshdeep-singh** [microsoft/vscode-cpptools#5560]
This is my project structure:
```
project
|----.vscode
|      |----c_cpp_properties.json
|----.git
|----general
|----private
```
Here is `c_cpp_properties.json` file:
```
{
    "configurations": {
        "includePath": {
            "some/path/common/...",
            "some/path/common/...",
            "some/path/common/...",
            "some/path/private/...",
            "some/path/private/...",
        }
    }
}
```
I want that `some/path/common/...` should be include by both folders `general` and `private`.
But the paths `some/path/private/...` should only be included by the folder `private`.
Rest of the `c_cpp_properties.json` file (contents not shown) is same for both folders.

**Comment by michelleangela** [comment]
The configurations in c_cpp_properties.json are applied per workspace folder. So whatever is defined in `includePath` will be applied to that entire workspace folder. 

If you want to only include certain paths for certain folders, you could try adding that certain folder as another workspace so that it will have its own c_cpp_properties.json configurations. This will turn your project into a multi-workspace environment. Here is an example:

![image](https://user-images.githubusercontent.com/38734287/83059663-1d9cf280-a00f-11ea-8fff-1a038bc6cfdc.png)

Is this what you're looking to do for your project?

**Comment by sean-mcmanus** [comment]
Yeah, that should work for the per-folder includes, and you could set C_Cpp.default.includePath in your .code-workspace settings to have the shared includes, and then use "${default}" in your workspace folder includePath to references the shared includes.
