### ISSUE TITLE
PlatformIO IDE not activating, missing CPPtools

### ISSUE THREAD

**Issue by Lyngbob** [microsoft/vscode-cpptools#5608]
Type: General

Been using VSCode/PlatformIO for awhile now to compile Marlin for 3D printing.
After an upgrade to MacOS Catalina PlatformIO will not activate.
Toggle Developers Tool gives me an error that it cannot find ms-vscode.cpptools and because of that cannot activate PlatformIO.
I have tried un-installing/re-installing PlatformIO and C/C++ but with no luck.
I cannot say for sure that the MacOS upgrade has anything to do with the failure… it can be that I have messed something up myself in VSCode… I am a novice user.
Please help.
I attach a screenshot of my TDT.
Thanks,
Henrik
![Skærmbillede 2020-06-02 kl  17 15 16](https://user-images.githubusercontent.com/65071776/83604070-cc907f80-a575-11ea-8c34-2ad600b718ca.png)

**Comment by Lyngbob** [comment]
Sorry... Don't know why the screenshot attached in the middle of the text

**Comment by Colengms** [comment]
Hi @Lyngbob.  It looks like cpptools failed to activate due to a missing file.  Could you try uninstalling the cpptools extension within VS Code, deleting the directory `/Users/henriklynbo/.vscode/extensions/ms-vscode.cpptools-0.28.2`, and reinstalling the extension?  We occasionally get reports of corrupted or incomplete installation, which we are still investigating.  A clean reinstall may work around the issue.
