### ISSUE TITLE
Linux (RedHat7)Extension simply does not work

### ISSUE THREAD

**Issue by carlhua** [microsoft/vscode-cpptools#563]
Linux version of this extension simply does not work (RedHat 7)

Vscode is installed via root, extension is installed via non-root user 

Extension simply does not work. Right click -> missing all the context menu items as well.

**Comment by sean-mcmanus** [comment]
Red Hat 7 or less is not a supported OS, because it doesn't have glibc 2.18 or later installed, which is a required dependency. If you can update the glibc on your machine you may be able to get our extension to work. See https://github.com/Microsoft/vscode-cpptools/issues/19 , although that thread mentions needing to add some scripts and other changes to the extension files.

**Comment by bobbrow** [comment]
Leave a comment

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
