### ISSUE TITLE
Including seemingly irrelevant header file breaks Intellisense

### ISSUE THREAD

**Issue by roversch** [microsoft/vscode-cpptools#5654]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux (Ubuntu 18.04)
- VS Code Version: `1.46.0
a5d1cc28bb5da32ec67e86cc50f84c67cc690321
x64`
- C/C++ Extension Version: v0.28.3
- Other extensions you installed (and if the issue persists after disabling them): I disabled all but vscode-cpptools, issue persists
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Autocomplete/suggest stops working after `#include`ing a certain header file (i.e. a ROS header file in this case)

**Steps to reproduce**

1. Intellisense autocomplete/suggest is working (see screenshots below) when pressing Ctrl+Space
2. I `#include` a certain header file
3. Press Ctrl+Space, now autocomplete says 'no suggestions found'. 

The complete, Intellisense-breaking file:

```
#include "nav_msgs/Odometry.h"
#include "ros/node_handle.h"    // <------ if I include this, autocomplete stops working
int main(int argc, char const *argv[])
{
    nav_msgs::Odometry::
    return 0;
}
```

**Expected behavior**
I expect that including extra headers does not break autocomplete.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 6/18/2020, 10:37:48 AM
Version: 0.28.3
Current Configuration:
{
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "<path/to/folder>/catkin_ws/devel/include/**",
            "/opt/ros/melodic/include/**",
            "/usr/include/**",
            "${workspaceFolder}"
        ]
    },
    "includePath": [
        "<path/to/folder>/devel/include/**",
        "/opt/ros/melodic/include/**",
        "/usr/include/**"
    ],
    "name": "Linux",
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu11",
    "cppStandard": "gnu++17",
    "compilerArgs": []
}
Translation Unit Mappings:
[ <path/to/folder>/src/test_intellisense.cpp ]:
    <path/to/folder>/src/test_intellisense.cpp
Translation Unit Configurations:
[ <path/to/folder>/src/test_intellisense.cpp ]:
    Process ID: 22869
    Memory Usage: 254 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /opt/ros/melodic/include
        /opt/ros/melodic/include/kdl
        /opt/ros/melodic/include/moveit
        /usr/include/bsd
        /usr/include/c++/7/ext
        /usr/include/boost/predef/os
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
Total Memory Usage: 254 MB
```
</details>

**Screenshots**

![Screenshot from 2020-06-18 10-24-11](https://user-images.githubusercontent.com/1436556/84998284-ec1bd080-b14f-11ea-81bb-9a17cee9b072.png)
![Screenshot from 2020-06-18 10-24-44](https://user-images.githubusercontent.com/1436556/84998287-ed4cfd80-b14f-11ea-9ac9-5b47837636da.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
This is mostly likely caused by the cpptools-srv (IntelliSense) process crashing, mostly likely by one of the high hitting bugs that we have fixed for our pending 0.29.0-insiders update, such as https://github.com/microsoft/vscode-cpptools/issues/5584 . If you see a failed to connect message in the C/C++ logs then that is a crash. If you can comment out the code in your source file, attach a debugger to the cpptools-srv process, uncomment the code, and then provide the call stack for the crashing thread, that would enable us to identify if the bug is the same as one of the known crashes. Or you could wait till we release 0.29.0-insiders to see if it's fixed or not (ETA isn't determined yet). Otherwise, we may need more repro info in regards to what in the header file is causing the breakage.

**Comment by roversch** [comment]
Thanks, Sean. I have some more info that might shed a light: for the working case, I see the following in the C/C++ extension logs (debug level):

```
Offering completion
completionItem/resolve (id: 215) 
```

For the broken case, it is just

 ```
Offering completion
```

without anything after it.

**Comment by roversch** [comment]
> If you can comment out the code in your source file, attach a debugger to the cpptools-srv process, uncomment the code, and then provide the call stack for the crashing thread

I tried this (I attached `gdb` to the running `cpptools-srv` process), but it does not seem to crash. From `gdb` I do see new threads being created when I save the file, so that's working seemingly fine.

**Comment by sean-mcmanus** [comment]
Yes, it doesn't appear to be crashing (the logs would show a "fail" message). It looks like the parsing just enters a bad state. The "completionItem/resolve" doesn't appear in the logging because that code only executes when the original completion request results results.

I think we need more info on what contents of node_handle.h are causing our parser to hit a problem, i.e. a repro.

**Comment by roversch** [comment]
Sure, I'm up for it if you can give me some guidance. Where should I start?

**Comment by sean-mcmanus** [comment]
Guidance on what? We need an isolated repro. Compiling your source file with the -E flag to generate a preprocessed TU can help (it might also show errors which are otherwise hidden in some header file).
