### ISSUE TITLE
Feature request: partial indexing

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-cpptools#5735]
**Type: LanguageService**

I work on an a very large monolithic codebase, but only a few folders are of interest to me. Currently indexing takes a few hours and never seems to truly finish (there are always glitches in the intellisense that seem to stem from an incomplete index). It may help if there was an option to set certian paths that I want to be indexed, instead of indexing the whole workspace.

**Comment by sean-mcmanus** [comment]
You should be able to control the indexing via setting the "C_Cpp.default.browse.path" (or the equivalent setting in c_cpp_properties.json). The paths are recursive by default, but you can add a "*" to the end of a path to make it non-recursive. Is that sufficient?

**Comment by BMBurstein** [comment]
@sean-mcmanus As far as I understand from the description of that parameter, that only controls where header files are searched for. I want to exclude whole parts of my workspace from having even the .cpp files indexed.

**Comment by sean-mcmanus** [comment]
browse.path doesn't control where headers are searched for in regards to IntelliSense (that is includePath) -- it controls where the workspace indexing occurs for the database for source file and when dependent `#include` are found it happens to search for headers at that location in order to tag parse them as well.

The description of browse.path is incorrect/misleading -- I'll create an issue to track improving that.
