### ISSUE TITLE
Revisit value of default language standard

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5740]
Since version 0.28.0, the extension's default value of a C or C++ language standard is obtained from the default compiler found on a user's machine. That is, if the default compiler returns `C++14` as the default language standard, this is the language standard version that will be used by the extension as default.

There has been reports of projects that require ` C++17` will show unexpected IntelliSense errors when the default IntelliSense configuration settings is used or rather when no customization of IntelliSense configuration is done because it is likely that the default language standard is not `C++17`. Previous to version 0.28.0, `C++17` was always used, so for most projects that require `C++17`, users did not experience any unexpected IntelliSense errors. 

This task is therefore to re-evaluate what the default C or C++ language standard should be to better support most projects and avoid unexpected IntelliSense errors due to mismatched IntelliSense configuration settings.

**Option:**
- Use the latest supported language standard version that a default compiler supports.

**Comment by sean-mcmanus** [comment]
Could you add more info?

**Comment by bobbrow** [comment]
I converted this from a note in the 0.29.0 project board.  @michelleangela, I think you created it.  Can you put more information here as to what this covers?

**Comment by michelleangela** [comment]
I added the details to the initial message of this thread.

**Comment by Colengms** [comment]
This seems to only apply to existing users who are crafting configurations directly, and not using a custom config provider or compile_commands.json.  In the later 2 cases, using the compiler default (if not present in the config or compile_commands.json) would more accurately reflect how the source is built.  If we decide to switch this back to using the latest instead of the default of the compiler, we should only revert that behavior for direct configs.  IMHO, it would be better to advise existing users to add the standard to their configs, than to revert this behavior as the new behavior is more intuitive for new users.

**Comment by bobbrow** [comment]
We haven't been receiving a ton of feedback about this.  We'll close this for now, but if we get more upvotes on it, we can consider a change here.

**Comment by sean-mcmanus** [comment]
Sounds like gcc 11 may set c++17 as the default, so it'll eventually not be an issue as users migrate to that.
