### ISSUE TITLE
Performance/memory issue with projects such as OpenCV

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5742]
Seem to be having the same issue here.  cpptools can easily run up 8GB of memory.
VSCode used only for editing, no compiling.
Also, I rarely use the Go-To-Definition feature and it hangs before I even hover over a variable.

Environment:
- Ubuntu 18.04, 
- 6 (12) core
- 16GB RAM
- v0.29.0-insiders

Some large, open source libraries used:

- OpenCV
- PCL

_Originally posted by @mgsteinkamp in https://github.com/microsoft/vscode-cpptools/issues/5227#issuecomment-653983601_

**Comment by sean-mcmanus** [comment]
@mgsteinkamp I'm not observing any performance/memory issue with OpenCV on Linux configured with CMake Tools. Can you provide repro steps in regards to how you're configuring your project, what file is opened, etc. The output of C/C++: Log Diagnostics might be helpful.

**Comment by mgsteinkamp** [comment]
@sean-mcmanus  Thank you for the response.
I was not using CMake Tools. 

From another user's comment, 
adding files to the exclude list seems to have helped immensely. 
In my case, I also had to set cpptools' `Exclusion Policy to`  `checkFilesAndFolders`.

I think the issue came up one more time after that, but I haven't been able to reproduce it since then. Sorry!
