### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SulthanNK** [microsoft/vscode-cpptools#5765]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `0.28.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 914,
		"activateCallTime": 4,
		"activateResolvedTime": 1269,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.cpptools",
				"_lower": "ms-vscode.cpptools"
			},
			"activationEvent": "onLanguage:c"
		}
	},
	"runtimeErrors": []
}
```

**Comment by michelleangela** [comment]
@SulthanNK 
Could you provide more information about the issue the extension is having? Or was this issue auto-generated?

**Comment by SulthanNK** [comment]
I just open this issue from the VS Code, what kind of information that you need?  @michelleangela

**Comment by michelleangela** [comment]
Could you fill out our bug template form below:

**Type: LanguageService**




**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**


1.
2.
3.
...

**Expected behavior**


**Logs from** 
1. Logs from the command `C/C++: Log Diagnostics`
2. Logs from [the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

<details>
  <summary><strong>Logs</strong></summary>


```
Insert logs here.
```
</details>

**Screenshots**


**Additional context**
