### ISSUE TITLE
C++ std::unordered_map insert std::pair bug

### ISSUE THREAD

**Issue by idealvin** [microsoft/vscode-cpptools#5770]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win10, Windows_NT x64 10.0.18362
- VS Code Version: 1.47.0 (system setup)
- C/C++ Extension Version: v0.29.0-insiders2

**Code**
```cpp
#include <unordered_map>

int main(int argc, char** argv) {
    std::unordered_map<int, int> m;
    int x = 1, y = 2;
    m.insert(std::make_pair(x, y));
    return 0;
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/12691466/87288218-a3c4b800-c52d-11ea-9aa5-67aee525bb44.png)

**Comment by Colengms** [comment]
Hi @idealvin .  I'm not able to easily repro this.  Since there is no error indicated when you hover, is it possible this red squiggle is due to a failed prior compilation?  Errors reported by a problem matcher (from compiler output) will linger until the next attempt to compile.

What is listed in your 'Problems' output?

Can you post your configuration (compilerPath, etc.)?

**Comment by idealvin** [comment]
> Hi @idealvin . I'm not able to easily repro this. Since there is no error indicated when you hover, is it possible this red squiggle is due to a failed prior compilation? Errors reported by a problem matcher (from compiler output) will linger until the next attempt to compile.
> 
> What is listed in your 'Problems' output?
> 
> Can you post your configuration (compilerPath, etc.)?

Hi @Colengms . This is my config:

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/include",
                "D:/app/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/include",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt"
            ],
            "defines": [
                "_WIN32",
                "_DEBUG"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "D:/app/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @idealvin . Your config looks fine.  Since there was not an error indicate when hovering, it's not yet clear to me what the squiggle is for, or if it's coming from the cpptools extension.

Can you provide the content of the "Problems" panel?  If should list the issue associated with that squiggle.

**Comment by idealvin** [comment]
@Colengms 

```cpp
insert

There is no overloaded function that matches the parameter list 
"std::unordered_map<_Kty, _Ty, _Hasher, _Keyeq, _Alloc>::insert [where 
    _Kty=int, _Ty=int, _Hasher=std::hash<int>, 
    _Keyeq =std::equal_to<int>, 
     _Alloc=std::allocator<std::pair<const int, int>>
]" 

-- parameter type is: 
    (std::pair<int, int>)

-- object type is: 
    std::unordered_map<int, int, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, int>>>
```

**Comment by Colengms** [comment]
@idealvin Sorry, I didn't recognize the localized text.

I'm not certain whether the squiggle is invalid or due to the MSVC standard library headers not being error-free if compiled with C++11.  But, since CL.exe does not support earlier standards than C++14, I believe you will want to set `cppStandard` to at least `c++14`.  That appears to remove the squiggle.

https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019

**Comment by idealvin** [comment]
Hi @Colengms 
I set the cppStandard to c++14 and it works well now. Thanks.

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/include",
                "D:/app/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/include",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt"
            ],
            "defines": [
                "_WIN32",
                "_DEBUG"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "D:/app/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe",
            "cStandard": "c99",
            "cppStandard": "c++14",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```
