### ISSUE TITLE
IntelliSense reports Problems that are not there.

### ISSUE THREAD

**Issue by xatian** [microsoft/vscode-cpptools#5794]
**Type: LanguageService**

**Describe the bug**
- OS and Version: **Debian Bullseye**
- VS Code Version: **1.46.1**
- C/C++ Extension Version: **0.29.0**
- Other extensions you installed (and if the issue persists after disabling them): **None**
- Does this issue involve using SSH remote to run the extension on a remote machine?: **No**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I am using g++ and std++17 for a small project of mine in which VSCode shows a lot of errors I don't get when compiling manually via the command line.
For this issue I picked 2 specific errors that I believe are the easiest to show and reproduce.
Consider this code:

```c++
#include <iostream>
#include <vector>
#include <string>

class Foo {
public:
    template<typename T = int>
    static void bar (T param);
};
template<typename T = int>
void Foo::bar (T param) {

}

int main () {
    int unix = 100;
    Foo::bar (100);

    std::vector<std::string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};
    for (const std::string& word : msg)
        std::cout << word << " ";
    std::cout << std::endl;
}
```

When I compile this via command-line I get no errors:
```
xatian@xatian-debian:~/devel/helloworld$ g++ --version
g++ (Debian 9.3.0-14) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

xatian@xatian-debian:~/devel/helloworld$ g++ -std=c++17 helloworld.cpp 
xatian@xatian-debian:~/devel/helloworld$ 
```
In Visual Studio Code I get 2 issues:
```json
{
	"resource": "/home/xatian/devel/helloworld/helloworld.cpp",
	"owner": "C/C++",
	"severity": 8,
	"message": "a default template argument cannot be specified on the declaration of a member of a class template outside of its class",
	"startLineNumber": 11,
	"startColumn": 19,
	"endLineNumber": 11,
	"endColumn": 20
}
```
```json
{
	"resource": "/home/xatian/devel/helloworld/helloworld.cpp",
	"owner": "C/C++",
	"severity": 8,
	"message": "expected an identifier",
	"startLineNumber": 19,
	"startColumn": 9,
	"endLineNumber": 19,
	"endColumn": 13
}
```

The first problem might even be correct ... I need to remove `= int` in line 11. If I remember correctly clang would report this issue too (although I haven't used clang in a while). So yeah ... I will fix that but still --> why does VSCode report the error when g++ does not?
The second problem is because your extension believes that unix is a macro defined to 1. When I hover the mouse over the issue it says:
```
#define unix 1
Expands to:

1
expected an identifier
```
But again ... this is not correct ... when I execute this to show all defined macros I get
```
xatian@xatian-debian:~/devel/helloworld$ g++ -std=c++17 -dM -E -x c++ - < /dev/null | grep unix
#define __unix__ 1
#define __unix 1
xatian@xatian-debian:~/devel/helloworld$ 
```
Indeed when I rename the variable to `__unix` g++ via command-line complains as well. Again naming the variable `unix` might not be the best idea but that is besides the point :-)

So why is this happening?
I searched a lot and tried to change some settings but was not able to reproduce the normal g++ behavior. For example when I change `C_Cpp.intelliSenseEngine` to `disabled` the Problems disappear but so does all Intellisense (which is not what I want obviously)

Here is the output of `C/C++: Log Diagnostics`
```
-------- Diagnostics - 7/17/2020, 2:56:01 PM
Version: 0.29.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "cStandard": "c11",
    "compilerPath": "/usr/bin/g++",
    "compilerArgs": [],
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/xatian/devel/helloworld/helloworld.cpp ]:
    /home/xatian/devel/helloworld/helloworld.cpp
Translation Unit Configurations:
[ /home/xatian/devel/helloworld/helloworld.cpp ]:
    Process ID: 20861
    Memory Usage: 47 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=90300
Total Memory Usage: 47 MB
```

Thank you!

**Comment by UberUser** [comment]
"The second problem is because your extension believes that unix is a macro defined to 1."

That is not a problem because "unix" is supposed to be a macro expanding to 1 (on Unix systems only of course -- it expands to 0 on non-Unix systems).

You admit "unix" is not the best name for a variable anyway, so why not just change it to something better? And what did you hope to prove by trying to use the reserved name __unix?

As for the first problem, which "might even be correct", in that case why are you reporting it here? Especially if a third opinion, Clang, says yep it's a problem. You slipped something by g++ but instead of being thankful that Intellisense found it for you you are wondering why it is reporting an error it found? Better you wonder why g++ didn't report it, which it might, if you used -Wall.

**Comment by xatian** [comment]
My issue is not about fixing or avoid errors. Instead, it is about inconsistent error-reporting between VSCode and g++ (errors VSCode shows me and errors that pop up when hitting build). I don't care which specific errors or warnings are reported. But I never encountered an IDE where the JIT-compiler (the one that runs all time) reports something different than the errors I get when hitting "build".
Further I always use -Wall + -Wextra when building stuff and no ... both error-examples are not reported by g++. If you had used your precious time to actually help (instead of telling me what to wonder about) you might have noticed that VSCode reports **errors** and -Wall would maybe shows more **warnings** (which is not the same thing right?)

I posted a command to print all defined macros on my system and it shows that "unix" is not one of them.
Is that according to spec? I don't care ... it is not defined when using g++.
Am I grateful that VSCode informed me about the bad name ... yes I am and I will change it but the fact remains that g++ does not report it.

> And what did you hope to prove by trying to use the reserved name __unix?

I hoped to prove that my command showing all reserved names works and that g++ indeed reports errors correctly when using such a reserved name. "unix" is just not one of them.

I never selected to use clang did I? As you can see in my `C/C++: Log Diagnostics` I opted for gcc-x64 so I was expecting that gcc-x64 is used to generate problems. Are you trying to tell me that clang is used to generate the problems shown by VSCode and that there is no way to change that?

By the way: welcome to GitHub. Try to be more helpful next time.
Thank you!

**Comment by UberUser** [comment]
> My issue is ... about inconsistent error-reporting between VSCode and g++ ...

Ah, well that's easy to fix: realize that since they are independent uncoordinated implementations of a very complex definition they are highly unlikely to be exactly in sync all of the time.

> Further I always use -Wall + -Wextra when building stuff and no ... both error-examples are not reported by g++

Commendations for using both -Wall and -Wextra. Though it's hard to measure, doing that probably saves time in the long run.

> If you had used your precious time to actually help...

I was trying to help. I still am.

> ... you might have noticed that VSCode reports **errors**...

Well, I'm new to it, but is it only pointing out "errors" or is it trying to show "problems"? I honestly don't know which. But, even if it's errors only, I see the source of the "unix" discrepancy here.

The system-defined macros from way back when (e.g. "unix") got modern parallel versions preceded by double underscores. With no standards options you should still see "unix" defined. But with a standards option (you used -std=c++17) the non-underscored versions aren't defined, as your example shows.

However what is Code supposed to do? Know all of the options that affect this for the many compilers that are in use, and accurately reflect that at all times? Or just go with "unix" as a predefined macro, and warn about it all of the time, since even if one's compiler options allow it, it's still strongly discouraged to use it? Clearly the latter is far easier and arguably better regardless of ease.

> I hoped to prove that my command showing all reserved names works and that g++ indeed reports errors correctly when using such a reserved name. "unix" is just not one of them.

Ok, fair enough. That's a good double-check on the macro report output.

> I never selected to use clang did I?

In your initial report you said "If I remember correctly clang would report this issue too" which is why I mentioned it. I have no idea about the correctness or not of this issue, but was just making the point that if Clang flagged it maybe/probably it's a real issue thus Code should be reporting it too.

> By the way: welcome to GitHub. Try to be more helpful next time.

Thanks! I'm being as helpful as I can, though I think you really meant more polite. There might be room for improvement there :), but ultimately if you don't like the message maybe it's hard to accept no matter how it's delivered.

> Thank you!

You're welcome, and happy coding.

**Comment by bobbrow** [comment]
Hey, sorry we're jumping in on this issue late!  Let's please be respectful here.  We expect this to be a safe place to collaborate on issues.  Our code of conduct guide can be found here: https://opensource.microsoft.com/codeofconduct/

Regarding the `unix` predefined macro, this is inherited from our front end parser that handles IntelliSense.  Tracing through the code, it looks like 'unix' is added to the list of predefined macros instead of `__unix`, though I'm not exactly sure why.  We'll need to dig into that.

For the template issue, gcc.godbolt.org shows an error for clang, a warning for msvc, and success for g++.  Our front end compiler emulates the different compilers but isn't 100% perfect. I believe the error is correct, but we'd have to go dig into the standard to confirm.

**Comment by UberUser** [comment]
> Regarding the `unix` predefined macro, this is inherited from our front end parser that handles IntelliSense. Tracing through the code, it looks like 'unix' is added to the list of predefined macros instead of `__unix`, though I'm not exactly sure why. We'll need to dig into that.

I think "unix" is still needed unless compiling to standard that says it should not be defined. In any case "\_\_unix\_\_" is the official variant now. Not sure if "__unix" is a also official or a nonstandard poor man's alternative. You might be standards-correct in not having "__unix" even though it's widely implemented.

> For the template issue, gcc.godbolt.org shows an error for clang, a warning for msvc, and success for g++. Our front end compiler emulates the different compilers but isn't 100% perfect. I believe the error is correct, but we'd have to go dig into the standard to confirm.

No matter what you do then you'll be right according to somebody. :)

More seriously, when you say "emulates the different compilers" are you saying that you use the compiler type that's set to try and match the behavior of that specific compiler? (Vs. some sort of union of their behaviors.) If so, wow, that's impressive, not to mention above and beyond the call of duty, and perhaps Xatian wasn't being so unreasonable in expecting a behavior match.

**Comment by sean-mcmanus** [comment]
Yeah, I'm 6 days late in noticing this issue -- can someone summarize if there's anything we should follow up on in regards to this? Do we need to file a bug on VS (for our shared parser code)?

**Comment by UberUser** [comment]
> Yeah, I'm 6 days late in noticing this issue -- can someone summarize if there's anything we should follow up on in regards to this? Do we need to file a bug on VS (for our shared parser code)?

I'm not sure if you're asking your co-workers or the world at large. If the latter, IMHO the answer is no (as the current behavior is baseline correct), unless you're committed at a high level to faithfully replicating the foibles of every compiler you support. In that case, you'd need to

1. Treat  "unix" as defined or not depending on the compiler options. E.g. it would be defined for "g++ t.c" and not defined for "g++ -std=c++17 t.c" (as well as for some other values for -std or -ansi).

2. Report an error, warning, or nothing for the "template\<typename T = int\>" construct depending on the compiler.

But even if you want to do that, may I suggest that changing the current behavior for either of these is nowhere near as important as addressing many other reported issues, such as #5797. :)

**Comment by xatian** [comment]
>  If so, wow, that's impressive, not to mention above and beyond the call of duty, and perhaps Xatian wasn't being so unreasonable in expecting a behavior match.

Yeah ... I think this issue is not unreasonable :-) I am aware that different compilers produce different errors/warnings but I thought that the setting "IntelliSense Mode" takes care of that. Meaning that the actual compiler that I specify is used to parse the code. If you use something else in the background than of course there will be discrepancies.

> can someone summarize if there's anything we should follow up on in regards to this? 

What purpose has the setting "IntelliSense Mode"? I thought it chooses the compiler to generate the problems shown in VSCode. I chose gcc (which is the compiler I happen to use for my current project) and I was expecting to get the same errors reported that gcc would report. This is not the case which is why I opened this issue.
The question is ... do you even want to report the same errors as gcc? If not ... what does this setting do?

Is it possible to just disable live-reporting of problems and keep everything else working (IntelliSense)? I noticed that when specifying `"problemMatcher":"$gcc"` in my tasks.json that you parse the output of gcc and highlight the errors/warnings it produces in VSCode which is very nice (yes not only does your extension report errors that gcc does not ... the other way around is also true).
This feature is enough ... I don't need live reporting of errors ... so if it can be disabled I am happy to hit "build" once in a while to get all current errors highlighted.

I hope this makes sense.
Thank you!

**Comment by bobbrow** [comment]
To disable the error underlines, set the `"C_Cpp.errorSquiggles"` setting to `"Disabled"`.

**Comment by xatian** [comment]
@bobbrow nice! This solves my problem.

Question is ... does it solve this issue here? You did not answer my question regarding the "IntelliSense Mode" - setting. Do you care about inconsistent error-reporting across compilers?

**Comment by bobbrow** [comment]
There are a number of settings we need to send to the IntelliSense compiler when we set it up: the compiler to emulate, the size of certain types, the include path, the defines, and various other switches.  The purpose of the values in the "configurations" section of `c_cpp_properties.json` is to give us the information we need to configure IntelliSense.

We do care about inconsistent error reporting across compilers. We license this compiler from another company and report bugs to them as we discover them, so we appreciate you letting us know when you encounter them.  I don't think their goal is "bug for bug compatibility", but rather to build up a functional code model that we can query to provide IntelliSense to customers.

**Comment by sean-mcmanus** [comment]
I've filed a bug on VS for the "unix" issue: https://developercommunity.visualstudio.com/content/problem/1124102/c-intellisense-incorrectly-defines-unix-in-stdcver.html . I could move that to a new issue if we're going to use this issue to track other issues.

**Comment by sean-mcmanus** [comment]
@bobbrow @Colengms Is Colen going to follow up on the template issue?

**Comment by Colengms** [comment]
I opened the following against VS for the template issue: https://developercommunity.visualstudio.com/content/problem/1124151/c-intellisense-error-involving-default-template-ar.html
