### ISSUE TITLE
Unable to compile C++ code

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-cpptools#588]
_From @bkeys on March 23, 2017 23:33_

Configured debug type 'cppdbg' is not supported.

- VSCode Version: 1.10
- OS Version: Fedora 25

Steps to Reproduce:

1. Try to compile a CMake project
2. You get an error "Configured debug type 'cppdbg' is not supported."

_Copied from original issue: Microsoft/vscode#23127_

**Comment by bkeys** [comment]
Mistake; you try to "debug" a C++ project and then the error propogates

**Comment by bkeys** [comment]
On one note, this happens even if you tell it to invoke the project without the debugger.
I installed the non free add on for C++ and it suddenly started working; it looks like you need the non free add on for basic C++ functionality. Maybe you guys could move the appropriate functionality from the non free extension to the code base for vscode?

**Comment by sean-mcmanus** [comment]
What do you mean by "non free add on"? Do you mean non open source? Which extension are you referring to?

**Comment by bkeys** [comment]
@sean-mcmanus yes I mean that the extension is not open source.
![selection_342](https://cloud.githubusercontent.com/assets/12195202/24381098/1fafadfa-1314-11e7-85c8-eed7ec08373c.png)
Here is the add on that is required for a C++ project; it is non free, however @mjbvz claimed in another issue that this extension is not needed to develop a C++ project in vscode. However I install the extension and everything works, without it the ability to debug a C++ program (or run it using the GUI) is removed. So it shows that vscode is not really usable without a non free add on.

**Comment by sean-mcmanus** [comment]
VS Code is primarily a lightweight editor, so as an editor for C++ it is usable without our extension. It is not expected to be a full IDE like Visual Studio. The extension is "free", just not open source. Why is open source a requirement for you? The debugger is largely based on open source technologies and you can view the javascript and the binaries in the extension folder (for example, see https://github.com/Microsoft/MIEngine ). Which binary specifically did you want the source code for?

**Comment by bkeys** [comment]
I suppose it does not make much sense to have an open source editor and then surround it with proprietary add ons. The Microsoft EULA is also quite a hefty agreement to make for something as small as C++ support. I would like to ask why is something like a C++ extension worth so much protection?
I would love to use vscode as my full time IDE however I do not want to be locked into using proprietary software.

**Comment by sean-mcmanus** [comment]
You can view the license at LICENSE.md in the root of the extension folder. There is nothing hefty about it as far as I can tell. What part of the license is problematic for you? Visual Studio 2017 does have a restrictive license and is different from the license in our extension. The parser we use has a restricted license and cannot be open sourced, which is primarily what is being protected. There is nothing about our software that locks you into using it...it's pretty lightweight, i.e. no proprietary formats. It sounds like you don't want to use any non-open source software? Many people have written their own open source extensions for C++, such as the LLDB Debugger...our C++ debugger just uses LLDB or GDB based on the open source ones, our formatter uses the open source clang-format, our keyword colorization uses the open source atom/language-c, etc..

**Comment by bkeys** [comment]
It is none the less a non free software license, and I would like to maintain a copr repository and see about getting vscode in the Fedora repos and maintaining a package for it. However I do not want to do this if it not functional without installing non free software IE the extension.
I get that vscode is lightweight and does not use proprietary formats (a big reason I want to use it). But I have a personal resolve against using proprietary software, and so do a numerically relevant amount of developers. I think making the C++ extentions FOSS can only help people adopt vscode.
I have seen the LLDB debugger however after installing it I still cannot run my C++ program I want to develop with vscode. The issue is that vscode cannot do basic C++ development without installing anything proprietary. So it seems like it lures people into installing proprietary add ons, because the standalone editor cannot do all that much without those add ons (which is good for it being lightweight), however it is problematic since it is crippled without the installation of proprietary software.

**Comment by bkeys** [comment]
Could you also point me to which setting defines "cppdbg" since that is what vscode is unable to find?

**Comment by bkeys** [comment]
Ah, I digged pretty deep and the issue lays with how the CMake extension integrates with VS (it depends on the non free add on). So I will post the issue there.
https://github.com/vector-of-bool/vscode-cmake-tools/issues/139

**Comment by bobbrow** [comment]
We are sorry that our extension will not meet your needs.  As Sean mentioned, we incorporate some code that we do not have a license to redistribute so unfortunately we do not have any plans in the immediate future to open source the entirety of this extension.
