### ISSUE TITLE
Use jsonc parser for c_cpp_properties.json

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#5885]
settings is using json with comment format,
c_cpp_p.json does not have the same bahavier as setting.json
hopes that Commas  `,` is supported in c_cpp_p json file to make it easier for users to write configurations
otherwise, some time it is very very annoying
```json
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "WIN32"
            ],
```
```json
            "defines": [
                "_DEBUG",
                "UNICODE",
                "WIN32"       //using alt + uparrow/downarrow to change position, it doesn't make sense, which is very bothered
                "_UNICODE",

            ],
```
![image](https://user-images.githubusercontent.com/1876302/89160957-7b683080-d5a4-11ea-8745-a6be7d6f66e3.png)

**Comment by sean-mcmanus** [comment]
This is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders. However, comments will give squiggles unless the default JSON file type is changed to "JSON with comments", which will be fixed in our next release (see https://github.com/microsoft/vscode-cpptools/pull/5911 ).
