### ISSUE TITLE
Handle system includes in includePath better or give better diagnostics

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5894]
We still keep getting reports of users adding system includes in includePath, most likely a result of the code action that prompts for that. This is causing the system includes to be in the wrong order so headers can't be found.

See https://github.com/microsoft/vscode-cpptools/issues/5866 for one example, but there are many more.

**Comment by Colengms** [comment]
TODO: Add telemetry and warnings around detecting when system includes from compiler probe are duplicated in includePath

**Comment by Colengms** [comment]
@sean-mcmanus Can you provide a repro of duplicates not removed and/or paths in the wrong order?  I'm not easily able to repro.  I'm seeing that canonicalized user includes paths that match canonicalized system include paths, are removed from their prior positions in the list.

**Comment by Colengms** [comment]
@sean-mcmanus #5866 appears to be due to use of `**` causing a path to be moved to the end, after system paths.  Is that by-design, or should we disregard a path with `**` if it's also a system path?  If by-design, I could add log output or a configuration warning.

Can you refer me to other instances that might be due to different causes?  I'm not seeing obvious problems that could cause reordering, or failure to remove user-specified duplicates.

**Comment by sean-mcmanus** [comment]
** moving to the end is "by design", but ** shouldn't be used with system paths. Maybe that's the only issue?

**Comment by Colengms** [comment]
I was mistaken in my previous comment.  I'm seeing use of `**` add subdirectories of system paths to the end of the list of includes, but the order of everything before that is maintained.  It's possible an issue arises when these paths are added, due to duplicate filenames and the wrong ones being found.  But, the order of paths should prevent that.  So, I'm still looking for a repro for an issue (or scenario to provide warnings for) that is specifically related to wrong system/user include path handling.
