### ISSUE TITLE
Semantic Highlighting Inconsistencies

### ISSUE THREAD

**Issue by gvcallen** [microsoft/vscode-cpptools#5941]
I have attached a screenshot which I feel explains what I am talking about best.

In issue 1. I believe the "#" symbol should also be the same color as the "include" text (I'm sure it was like this in previous versions so I am fairly certain this is a bug).

In issue 2 and 3, I believe the "*" and "&" symbols should be the same color (white in this case) as when used inside a function, as opposed to in a parameter. I am not sure, however, whether this is a feature or not, and if so I would like the option to turn it off.

![Semantic Highlighting Errors](https://user-images.githubusercontent.com/64086515/89731869-e5705200-da4a-11ea-89ea-ec25025fd01b.png)

Thanks!

**Comment by Colengms** [comment]
Hi @gvcallen .  I believe the colors you are referring to are coming from VS Code, and are not due to the semantic colorization done by the C/C++ Extension.

Though, I don't know why the "#" in the #include statement would not be the same color.  I'm not able to repro that.  Do you perhaps have another extension installed that could be changing the TextMate C++ grammar used by VS Code?

The TextMate C++ grammar in VS Code is contributed via this repo: https://github.com/jeff-hykin/cpp-textmate-grammar .  
That grammar is also made available in an extension called "Better C++ Syntax", which is often updated more frequently than VS Code.  I'd suggest trying that extension, and following up with an issue in that repo if it does not work as expected.

If you use the `Developer: Inspect Editor Tokens and Scopes` command, and click on an offending token, it should provide information about how that token was interpreted.  For all tokens provided by the C/C++ Extension, you will see a 'semantic' entry in that info.  All other tokens would be colored syntactically by VS Code.

Our semantic colorization feaure can be disabled using: `"C_Cpp.enhancedColorization":"Disabled"`.  Though, I suspect it's not the culprit.
