### ISSUE TITLE
Can't bind breakpoint while program is running on Windows

### ISSUE THREAD

**Issue by kevinmoran** [microsoft/vscode-cpptools#595]
When I add a breakpoint to my program as it's running, it appears as grey with the tooltip "Attempting to bind the breakpoint..." I can set breakpoints before running the program and they work fine. Only having this issue on my Windows machine.

**Comment by W4rlock34** [comment]
Take a look here: https://code.visualstudio.com/docs/languages/cpp#_known-limitations

> Known Limitations:
> Windows:
>    GDB on Cygwin and MinGW cannot break a running process. To set a breakpoint when the application > is running (not stopped under the debugger), or to pause the application being debugged, press Ctrl-C in > the application's terminal.

**Comment by pieandcakes** [comment]
@kevinmoran if you are using Cygwin or MinGW, what @W4rlock34 says is correct. Please confirm what your debug target is. You should be able to set breakpoints ahead of time or when you are stopped.

**Comment by kevinmoran** [comment]
Thanks folks, Ctrl C does the job

**Comment by justanotheranonymoususer** [comment]
What about a program without a console window?

**Comment by yakamoz423** [comment]
@justanotheranonymoususer Maybe you can run the program in a Terminal by typing its absolute path.

**Comment by justanotheranonymoususer** [comment]
But how do I debug it? If I type its path and run it, it runs without a debugger.
I think that the extension has to do what is mentioned here: https://github.com/microsoft/vscode-cpptools/issues/2771#issuecomment-435999303

**Comment by guntern** [comment]
Sorry for reusing this issue, but it seems to be the best place. As I see the information still holds, but has a new link: https://code.visualstudio.com/docs/cpp/cpp-debug#_known-limitations
I have configured the gdb under windows to attach to a program. This seems to work, because I do see the threads of the program. However its execution is not halted and thus the breakpoints are not bound. Using Ctrl+C in the program does not work, because it catches and handles it itself without stopping.

What puzzles me is, that when I use gdb in the terminal itself (without VS Code), gdb certainly halts the program when it gets attached. I can set breakpoints via the gdb command line and they are correctly used. To the overall statement under the above link, that gdb under MinGW (which I am using in both cases) cannot break a running process under Windows.

Where is the difference between the bare approach in the terminal and using VS Code?

**Comment by p00f** [comment]
> pause the application being debugged, press Ctrl-C in > the application's terminal.

this just quits the program

**Comment by guntern** [comment]
> this just quits the program (of course it quits the program, isn't that what Ctrl-C is supposed to do?)

Not really. Ctrl-C is caught by the debugger and thus halts the program, because the debugger shows you this as an exception. Without debugger of course Ctrl-C will kill the program (or at least parts of it, depending on the program itself)
