### ISSUE TITLE
Crash regression with completion starting with 0.30.0-insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5960]
See the repro at https://github.com/microsoft/vscode-cpptools/issues/5864 , i.e. the code at https://pytorch.org/cppdocs/frontend.html
do completion on the "forward" of "fc1->forward".

We need to see if this repros on Windows and with VS.

**Comment by sean-mcmanus** [comment]
I've filed VS bug https://developercommunity.visualstudio.com/content/problem/1170465/c-intellisense-crashes-from-completion-in-clang-mo.html .

**Comment by marco-fam** [comment]
I added additional comments on the issues on intellisense not working due to 
"Compiler exited with error - No IL available".
Perhaps it would be helpful to add additional debug info in the cpp extension when this situation occurs.
tested with 0.30.0-insiders4!

https://github.com/microsoft/vscode-cpptools/issues/6009#issuecomment-685323322

**Comment by sean-mcmanus** [comment]
@marco-fam If you're seeing "No IL available" it is not a crash, and it most likely caused by includePath or defines not being set correctly.
