### ISSUE TITLE
cpptools of aarch64 Starting client failed

### ISSUE THREAD

**Issue by ReputationZH** [microsoft/vscode-cpptools#5969]
I am now using remote SSH to connect to my raspberrypi4b, and the RPI is using Ubuntu 18.04. I downloaded the cpptools version of aarch64 from GitHub. After installing VISX, open the. C file and display the error：

error:Launching server using command /home/git/.vscode-server/extensions/ms-vscode.cpptools-0.30.0-insiders2/bin/cpptools failed.

**Comment by ReputationZH** [comment]
My device is on the Internet and would like to know how to solve this problem.

**Comment by AZMDDY** [comment]
me too.

**Comment by ReputationZH** [comment]
How do you have answer?


————————————————————————


 原始邮件 
发件人: AZMDDY<notifications@github.com>
收件人: microsoft/vscode-cpptools<vscode-cpptools@noreply.github.com>
抄送: ReputationZH<656982406@qq.com>; Author<author@noreply.github.com>
发送时间: 2020年8月16日(周日) 07:52
主题: Re: [microsoft/vscode-cpptools] cpptools of aacrh64 Starting clientfailed (#5969)


me too.

**Comment by sean-mcmanus** [comment]
This should be fixed with 0.30.0-insiders3 later this week -- 0.30.0-insiders2 shipped with 32-bit ARM binaries (instead of aarch64 binaries), so it only worked if your OS is able to run those.

**Comment by ReputationZH** [comment]
> This should be fixed with 0.30.0-insiders3 later this week -- 0.30.0-insiders2 shipped with 32-bit ARM binaries (instead of aarch64 binaries), so it only worked if your OS is able to run those.

Although raspberrypi officially only supports 32-bit operating system, I use the ubuntu of aarch64 architecture. Will aarch64 not be supported this week?

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders3 . If you have 0.30.0-insiders2, updateChannel set to Insiders, and autoUpdate set to true, it should auto-update.

Ubuntu 18 (glibc 2.27 minimum) support is planned for 0.30.0-insiders4: https://github.com/microsoft/vscode-cpptools/issues/5993
Ubuntu 16 or Debian 9 support is not currently planned, but you can upvote that at: https://github.com/microsoft/vscode-cpptools/issues/5984
