### ISSUE TITLE
C++ wrong syntax check

### ISSUE THREAD

**Issue by yihuajack** [microsoft/vscode-cpptools#6012]
Issue Type: <b>Bug</b>

I use C/C++ extension in Windows environment. Using CMake to build is successful and the executable file gives the correct answer, but it wrongly shows me four syntax errors. I have included <iostream> and using namespace std but it still tells me that cin is unrecognizable identifer, and the operator << also not matched. Besides, it tells me the class vector has no proper copy constructor and no matched operator for != of vector<int>. The program runs right in Visual Studio. Such error does not exist in WSL remote mode. I have tested the problem only occurs if C/C++ extension is enabled and not relevant to other extensions.

Extension version: 0.30.0-insiders3
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

Part of code:
```
int main() {
    int i, num;
    string output;
    vector<int> nums;
    for (i = 0; i < 3; i++) {
        cin >> num;
        nums.push_back(num);
    }
    Solution s;
    output =  s.judgePoint24(nums) ? "True"  : "False";
    cout << output << endl;
}
```

**Comment by sean-mcmanus** [comment]
We need more info. Most likely something configured incorrectly in regards to your system includes. Can you provide the output of running the C/C++: Log Diagnostics command?

**Comment by yihuajack** [comment]
[Log Diagnostics (CMake & CMake Tools Disabled).txt](https://github.com/microsoft/vscode-cpptools/files/5123400/Log.Diagnostics.CMake.CMake.Tools.Disabled.txt)
[Log Diagnostics (MSVC Clang 10.0.0).txt](https://github.com/microsoft/vscode-cpptools/files/5123401/Log.Diagnostics.MSVC.Clang.10.0.0.txt)
[Log Diagnostics (VS 2019 Release - amd64).txt](https://github.com/microsoft/vscode-cpptools/files/5123402/Log.Diagnostics.VS.2019.Release.-.amd64.txt)

**Comment by sean-mcmanus** [comment]
Are you compiling your code with cl.exe or clang-cl.exe? CMake Tools think you're using clang-cl.exe (you could use the CMake: Scan for Kits and Select a Kit to change that).

If you want to disable the CMake Tools extension, you'll also want to remove `"configurationProvider": "ms-vscode.cmake-tools",` because of issue https://github.com/microsoft/vscode-cpptools/issues/6024 .

**Comment by sean-mcmanus** [comment]
This issue looks similar to https://github.com/microsoft/vscode-cpptools/issues/5456 . Our extension or CMake Tools might not be handling the clang-cl scenario correctly. And https://github.com/microsoft/vscode-cpptools/issues/5031

And https://github.com/microsoft/vscode-cpptools/issues/3387 looks related.

**Comment by yihuajack** [comment]
It seems that this problem occurs both when using cl.exe (Visual Studio 2019 Release - amd64) and clang-cl.exe, and both compiler can successfully compile my program. In addition, I update MSVC Clang version to 10.0.1 and this problem also occurs. Besides, in my VSCode, the setting "configurationProvider" is blank and I do not know why it appeared in log diagnostics.

**Comment by Colengms** [comment]
Hi @yihuajack .  Your VS 2019 log diagnostics file indicates it's actually using clang-cl, not VS 2019, due to the file receiving a configuration from CMake Tools.  Your log titled ""Log.Diagnostics.CMake.CMake.Tools.Disabled.txt" does not appear to have CMake Tools disabled.  It is still configured to be used, and clang-cl was used.  Perhaps check if the setting, "C_Cpp.defaults.configurationProvider" is also set?  Also, you might try relaunching VS after changing these setting, to ensure they have taken effect.

Could you try again with the latest versions of the extension (currently 1.1.0-insiders4) and CMake Tools?  We should be providing much more verbose diagnostics about the configuration process.  Also, we've recently improved our handling of clang-cl, so that may now work properly.

If you are still seeing an issue, could you provide new logs, and perhaps a complete code example?  Your original example references a type that is not provided (Solution), and is missing some #includes.  Direct use of `cin` requires a previous use of `using namespace std;`, otherwise you would need to refer to it as `std::cin`.  If you are not `using namespace std`, the squiggle on cin would be correct.
