### ISSUE TITLE
Add telemetry around the database integrity check

### ISSUE THREAD

**Issue by iskettan** [microsoft/vscode-cpptools#6021]
Hello everyone,

I have recently started using vscode for c++ remote development.

I am facing an issue that I don't know if it's the normal behavior or not.

Every time I open vscode, it says discovering files, and it takes about 20 minutes to finish discovering my project files. Then, it starts parsing the files, and it takes about 10 hours to finish parsing 100,000 files.
The problem is that every time I open the application, it starts doing this process from scratch. 

Is that the normal behavior? or is there something wrong with my setup?

Thanks,

**Comment by sean-mcmanus** [comment]
What version of our extension are you using?

It's not normal. It means something prevented the database from shutting down cleanly, such as an abnormal shutdown of our extension. If you set C_Cpp.loggingLevel to "Debug" you can see database messages like "Database safe to open" or "Warning: Database safety check failed. Recreating database.".

You may want to add some paths to files.exclude to process less files (or modify the browse.path, see https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference#_browse-properties).

You also may want to make sure the files are available on the remote machine (i.e. same machine the extension is running on), otherwise the file access could be slow (e.g. accessing Windows file system /mnt locations in WSL2/Linux).

**Comment by iskettan** [comment]
Thank you for your response.
I am using C/C++ Intellisense, Debugging, and code browsing V0.30.0-insiders3

I noticed something, after it finishes parsing all the files, when I open any file, it says "updating intellisense", and I believe it gets stuck, and when I close it, it rebuilds its database.

I am wondering why would it get stuck at updating intellisense.

Thanks,
Ibrahim

**Comment by sean-mcmanus** [comment]
Do you see the cpptools or cpptools-srv processes using CPU when it says "updating IntelliSense"? If not, there could be a thread deadlock that is then causing shutdown to not properly occur.

One thing to try is to change the includePath setting from "${workspaceFolder}/**" to "${workspaceFolder}" in case there a problem handle the recursive includes feature when opening a file.

**Comment by iskettan** [comment]
The cpptools process was not using any cpu. However, I noticed that there was more than one cpptools process.

I did 4 things and it looks like it solved the issue. I am not sure which one of the steps is the one that solved it.

1) I killed all the cpptools processes.
2) I set limitSymbolsToIncludeHeaders to true.
3) I specified the databaseFilename to a location inside the ${workspaceFolder}.
4) I reset the database.

Now, parsing takes about 10 minutes (compared to the 10 hours it used to take), and updating IntelliSense does not block.

by the way, I am still using the recursive includes.

I hope that it continues to work, but @sean-mcmanus do you have any guess which of the 4 steps I took did this change?

Thanks,
Ibrahim

**Comment by sean-mcmanus** [comment]
Yes, a dangling cpptools process can maintain a lock on the database, which could cause the extension to try to create a new database file (i.e. starting over). limitSymbolsToIncludedHeaders is recommended to be true (if it was false, that could case a lot more parsing of all the system headers, potentially everything under /usr/include).

**Comment by bobbrow** [comment]
It looks like this issue is resolved.  We'll add telemetry to track how frequently this is a problem for people.

**Comment by sean-mcmanus** [comment]
We were able to repro the issue with the database getting deleted. The root cause is that shutdown was sometimes not getting executed. An issue on VS Code was filed at https://github.com/microsoft/vscode/issues/106433 . I filed a follow up issue at https://github.com/microsoft/vscode-cpptools/issues/6138 , since this issue morphed into adding telemetry.
