### ISSUE TITLE
Some C++ navigation commands are broken on my machine

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#607]
_From @TimCondon on April 4, 2017 0:45_

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 3.10.0-327.4.4.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1. I created a folder called test, and added two empty files (test.h & test.cpp)
2. I opened VSCode, then opened the newly created folder (/test)
3. I opened test.cpp, then right-clicked to select "C/Cpp: Switch Header/Source." Nothing happens.

More info: On my machine, switching between headers and source as well as the goto symbol and goto definition commands don't do anything. I did run code directly (just extracting and executing code without running the installation process) the first time I ran the application. I'm not sure if this could have broken some settings, or how to fix them.

_Copied from original issue: Microsoft/vscode#23875_

**Comment by sean-mcmanus** [comment]
What distro of Linux are you using? What do you mean that you ran the code directly without running the installation process? We download OS specific components at initialization time. You should see the download/install messages in the Output window.

**Comment by TimCondon** [comment]
I'm on Red Hat Enterprise v.7.2.

When I say I ran "code" directly, I mean that I initially downloaded the VSCode rpm, extracted it manually, then ran <extracted-dir>/usr/share/code/code directly on the command line, rather than using rpm/yum/some other package manager to install it first. Later, it was installed "properly" using a package management tool. I mention this only because this was an "unusual" thing about my setup process, and it seemed possible that failing to use a package manager *might* have led to some sort of invalid configuration.

**Comment by sean-mcmanus** [comment]
Our language server process which does the header switching and go to definition, Microsoft.VSCode.CPP.Extension.linux, doesn't run on RHEL7 out-of-the-box, because of the glibc 2.18 dependency which is missing. See https://github.com/Microsoft/vscode-cpptools/issues/19 for a workaround. I'm assuming RHEL7.2 has the same issue as RHEL7. If you see our language server process running then this would be a different issue.

**Comment by TimCondon** [comment]
Thanks, sean-mcmanus - that did it! (along with a "make all" prior to "sudo make install").

Is there an index or FAQ of workarounds where I should look in the future instead of filing a bug? Thanks!
--Tim

**Comment by sean-mcmanus** [comment]
No, we don't really have any FAQ (maybe we could add one later). You could search the existing GitHub issues, or filing bugs is fine too.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
