### ISSUE TITLE
IntelliSense messed up when ARM Toolchain include

### ISSUE THREAD

**Issue by zabeloliver** [microsoft/vscode-cpptools#609]
Hi, 

when i include my ARM Toolchain in my C Project, IntelliSense is messed up. 
Steps to reproduce:
1. Create a sample file with following content:

``` C
#include <stdint.h>

typedef struct _test {
    uint8_t ucValue;
    uint16_t uiValue;
} sTest;


int main(int argc, char *argv[]) {
    sTest a;
    
    return 0;
}
```
2.  Now type a. and it gives you correctly the right struct members.
![image](https://cloud.githubusercontent.com/assets/9071408/24693185/a6c22772-19dc-11e7-8538-d1396d48ed85.png)

3. Create a CPP config with a custom Toolchain. In my example i'm using an ARM toolchain provided by the Cypress PSoC Creator IDE 4.0
``` JS
        {
            "name": "Cypress ARM",
            "includePath": [
                "C:/Program Files (x86)/Cypress/PSoC Creator/4.0/PSoC Creator/import/gnu/arm/4.9.3/arm-none-eabi/include"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename" : "${workspaceRoot}/.vscode/browse.db"
            }
        }
```
4. Now repeat step 2 und you get the following list by typing a. :
![image](https://cloud.githubusercontent.com/assets/9071408/24693266/0725149e-19dd-11e7-8457-ed0d10f6d5fd.png)

What am i doing wrong?

Thanks for Help and best regards!

PS: 
Windows 7
VSCode 1.10.2
CPP Ext 0.10.5

**Comment by sean-mcmanus** [comment]
This is "by design" behavior that we intend to improve later (see https://github.com/Microsoft/vscode-cpptools/issues/13 ). The current non-IntelliSense engine version of autocomplete uses a "fuzzy" workspace symbol engine that doesn't fully parse the current document to determine the correct set of autocomplete values, so the list it provides is too large. ucValue eventually appears in the autocomplete, right? If not, that would be a bug. If you don't want certain symbols to appear in the autocomplete, you could add entries to the files.exclude setting (although those files also won't appear in the Explorer/Search for VS Code).

**Comment by csholmq** [comment]
@sean-msmanus Does that mean you should include the toolchain headers and then exclude them?

**Comment by sean-mcmanus** [comment]
@csholmq You would only include toolchain headers and then exclude some of them if you wanted a symbols for only the subset of non-excluded headers.
