### ISSUE TITLE
c++ build task repeat

### ISSUE THREAD

**Issue by hongfanmeng** [microsoft/vscode-cpptools#6095]
system : windows 10
plugin version: 0.30.0

when a try to config build task, there are repeat task there, can i remove them?
![image](https://user-images.githubusercontent.com/51071010/92537973-0a392e80-f270-11ea-8049-8fa7e28fd62f.png)

**Comment by sean-mcmanus** [comment]
They are from different compilers with the same name. I think we should add the full path so they can be distinguished. We're tracking already with https://github.com/microsoft/vscode-cpptools/issues/4278

**Comment by elahehrashedi** [comment]
There are two reasons that result in having multiple tasks with the same name:
1. The tasks are from different compilers with the same name and different paths. We are taking care of this by showing the compiler path in details, in this PR: https://github.com/microsoft/vscode-cpptools/pull/5659
2. There might be a task in the tasks.json with the exact same name. In order to avoid this confusion, go to tasks.json and customize your tasks' names (my guess is that you have a few tasks in tasks.json that are named as "C/C++: g++.exe build active file"). This might be solved in the future [https://github.com/microsoft/vscode/issues/105012], but for now, renaming is the best option.
