### ISSUE TITLE
No squiggles will appear if opening a folder on Windows that has the wrong casing

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6106]
Something can cause VS Code to open a folder with the wrong casing, causing IntelliSense errors to not appear. I don't know how to get VS Code to behave that way though. The workaround is to open the folder with the correct casing. Let me know if anyone knows how to cause the wrongly cased folder to be opened with VS Code. I'm not sure if there's a way we can fix this or we should file a VS Code bug.

![image](https://user-images.githubusercontent.com/19859882/92796962-7f872b00-f366-11ea-9e59-6a9687826783.png)

**Comment by sean-mcmanus** [comment]
Found a repro: use `code <path to workspace with the wrong casing>` (there could be other ways to repro this too).

**Comment by sean-mcmanus** [comment]
The code tries to use the "correct" casing instead of the "wrong" case that VS Code is using, so it is skipping the IntelliSense errors when it finds the cases don't match. Not sure if this is related to the recent VS Code changes related to casing, but from our side the issue has existed for a long time.

**Comment by bobbrow** [comment]
We think this might be a VS Code issue.  They were supposed to have addressed casing issues with URI's.

**Comment by sean-mcmanus** [comment]
@bobbrow Should I file a VS Code bug?

**Comment by bobbrow** [comment]
Yes, please.

**Comment by sean-mcmanus** [comment]
I don't think it's a VS Code bug. The VS Code issue was https://github.com/microsoft/vscode/issues/12448 . They fixed it, but the problem is that VS Code itself using only 1 URI casing, but the problem is that we're internally changing that casing. I think we'd need to change our code to respect that casing that VS Code uses.

**Comment by Colengms** [comment]
I believe this has since been addressed.  The different casing still confuses VS Code.  It uses the casing specified on the command line, causing it to lose persistent values (for all extensions).  Cpptools may still have some code that tries to convert from canonicalized paths to URIs, which could still cause problems.  However, I've since updated canonical-to-URI conversions for currently open files to  do lookup against the open files table instead, in order to preserve VS Code's casing. As a result, IntelliSense appears to be properly functional in this scenario and squiggles are properly displayed.
