### ISSUE TITLE
PlatformIO error Connection to server got closed. Server will not be restarted

### ISSUE THREAD

**Issue by t0maszduda** [microsoft/vscode-cpptools#6126]
after crash I have "Connection to server got closed. Server will not be restarted"

![Zrzut ekranu 2020-09-13 o 09 39 52](https://user-images.githubusercontent.com/56415244/93013071-6e782d00-f5a5-11ea-8989-98e8416167b4.png)
![Zrzut ekranu 2020-09-13 o 09 41 26](https://user-images.githubusercontent.com/56415244/93013074-6fa95a00-f5a5-11ea-87fa-c2dfe6ac1685.png)
![Zrzut ekranu 2020-09-13 o 09 41 36](https://user-images.githubusercontent.com/56415244/93013076-71731d80-f5a5-11ea-953e-ec859c609ca4.png)
![Zrzut ekranu 2020-09-13 o 09 41 48](https://user-images.githubusercontent.com/56415244/93013077-733ce100-f5a5-11ea-817a-a26b5af55ea6.png)

**Comment by sean-mcmanus** [comment]
I'm not able to repro. Does it repro with 1.0 still? Can you provide more repro details? Do you have a repro project you can provide?

Your first screenshot appears to show that cpptools crashed before the 1st screenshot. Were there other repro steps leading up to that?

**Comment by Veoramid** [comment]
I have the same problem. I am installing the program for the first time. I want to try, but the build of the project does not work.

**Comment by t0maszduda** [comment]
I'm not able to repro. I don't remember how did this happen but it was as first time as @Veoramid

**Comment by t0maszduda** [comment]
Today I've had one "Connection to server got closed. Server will not be restarted"

**Comment by bobbrow** [comment]
Just FYI, this is a message that a VS Code dependency of ours prints out when the extension process crashes.  The message is incorrect because we manage the restart of the extension instead of letting VS Code do it.  The message says "Server will not be restarted" because we tell VS Code not to do it for us and that's what they print out as a result.

Unless you see the message that says "The language server crashed 5 times in the last 3 minutes. It will not be restarted." the extension should be running.  Is IntelliSense (e.g. auto-complete, quick info tooltips, etc) working for you, or are you saying that the extension is broken?

**Comment by EMHacker-alt** [comment]
I have the same problem. "[Error - 4:01:28 PM] Connection to server got closed. Server will not be restarted." I cannot build project, download or start the serial monitor. Please help !!!

**Comment by EMHacker-alt** [comment]
IntelliSense isn't working at all

**Comment by Veoramid** [comment]
This is the first time I installed the program. I pressed "next", "next", "next" ...
When it failed, I uninstalled the program and installed it again. Again it didn't work out.
Then I noticed that C ++ was missing. After that, I installed the earliest version 0.22 - the program worked for me and I launched platformio for esp8266.
I tried updating C ++ but nothing worked. Is it because I removed Phyton?

**Comment by sean-mcmanus** [comment]
Is anyone able to attach a debugger to the cpptools process before it crashes to get a call stack? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

Or does anyone have complete repro steps?

**Comment by Veoramid** [comment]
It might be interesting:
If I downgrade C / C ++ to 0.25 the error goes away. Since version 0.26 - the error appears
![image](https://user-images.githubusercontent.com/16515589/93694125-c3b9be80-fb10-11ea-9256-a80b1dcc6296.png)
![image](https://user-images.githubusercontent.com/16515589/93694133-e9df5e80-fb10-11ea-8d31-3e2512be00fb.png)

**Comment by sean-mcmanus** [comment]
@t0maszduda 0.25.1 is a year old. It's not obvious what change in 0.26.0 could have caused it (without a call stack of the crash).

**Comment by t0maszduda** [comment]
> @t0maszduda 0.25.1 is a year old. It's not obvious what change in 0.26.0 could have caused it (without a call stack of the crash).

**Comment by t0maszduda** [comment]
> @t0maszduda 0.25.1 is a year old. It's not obvious what change in 0.26.0 could have caused it (without a call stack of the crash).

It is for @Veoramid

**Comment by Mingming-Git** [comment]
> Just FYI, this is a message that a VS Code dependency of ours prints out when the extension process crashes. The message is incorrect because we manage the restart of the extension instead of letting VS Code do it. The message says "Server will not be restarted" because we tell VS Code not to do it for us and that's what they print out as a result.
> 
> Unless you see the message that says "The language server crashed 5 times in the last 3 minutes. It will not be restarted." the extension should be running. Is IntelliSense (e.g. auto-complete, quick info tooltips, etc) working for you, or are you saying that the extension is broken?

I have the message"The language server crashed 5 times in the last 3 minutes. It will not be restarted.  source: C/C++(Extension)". Is there anyway can I recover or use cpptools? Try to uninstall and install vscode or uninstall c/c++ extension are not useful. 
I only want to recover my vscode envrionment, but It seems like no way, right?

**Comment by sean-mcmanus** [comment]
@Mingming-Git What version of the C/C++ extension are you using? Are you able to attach a debugger to cpptools before it crashes to get a callstack? Or are you able to provide repro steps that I can follow? I haven't been able to repro this crash yet.

**Comment by Mingming-Git** [comment]
@sean-mcmanus I'm sorry, my vscode is offline. I can't transfer the log to here. 

I use vscode ssh remote. It can't go to reference during i modify the code. And it just reports the problem when I restart vscode.
Just FYI: My code is git code, so I switch branch frequently. the problem are not exist when I just open local code by vscode.

The vscode version: 1.49.0(stable)
c/c++ intellisense extension: 1.0.0.

I change the c/c++ extension to 1.0.1(stable), now the problem is "The terminal process failed to launch: a native exception occured during launch(forkpty(3) failed)". This problem maybe affected by linux server,(create process limit?) I will check it.

thanks.

**Comment by Mingming-Git** [comment]
> @sean-mcmanus I'm sorry, my vscode is offline. I can't transfer the log to here.
> 
> I use vscode ssh remote. It can't go to reference during i modify the code. And it just reports the problem when I restart vscode.
> Just FYI: My code is git code, so I switch branch frequently. the problem are not exist when I just open local code by vscode.
> 
> The vscode version: 1.49.0(stable)
> c/c++ intellisense extension: 1.0.0.
> 
> I change the c/c++ extension to 1.0.1(stable), now the problem is "The terminal process failed to launch: a native exception occured during launch(forkpty(3) failed)". This problem maybe affected by linux server,(create process limit?) I will check it.
> 
> thanks.



@sean-mcmanus  I check the linux server and vscode has many same process. The vscode and extensions works normal when I killed all of them.

To all, FYI:
The problem of "Connection to server got closed. Server will not be restarted": maybe you can update the extension to solve it(remember to delete extension in vscode server and user/.vscode).
The problem of "The terminal process failed to launch: a native exception occured during launch(forkpty(3) failed)": maybe you should check the server process and kill them all.

**Comment by t0maszduda** [comment]
There is no problem with PlatformIO and VSCode now. I reinstalled VSCode and it helped.
