### ISSUE TITLE
edit focus lost after "rename symbol"

### ISSUE THREAD

**Issue by demidenko** [microsoft/vscode-cpptools#6144]
**Type: LanguageService**

- OS and Version: Ubuntu 18.04
- VS Code Version: 1.49
- C/C++ Extension Version: 1.0.0
- Other extensions you installed (and if the issue persists after disabling them): all off

Suppose simple c++ code
```
void f(int x){}

int main(){
	int x;	
}
```

1. Go to `x` in `main`
2. F2 to call "rename symbol"
3. hint said "enter to rename", "shift+enter" to preview
4. rename to `y` and hit "enter"
5. vscode ignores and shows preview
6. anyway, press "shift+enter" to apply
7. you can't edit code because of focus lost

Expected behaviour is:
Do not show preview after press "enter"
OR
Restore focus to editor after press "shift+enter" in preview

**Comment by sean-mcmanus** [comment]
We force a preview because of the "Not a Reference" found. If we had a setting to filter out those types of references (similar to https://github.com/microsoft/vscode-cpptools/issues/4042) then the preview could be skipped in this case.

The focus being lost is very strange because it doesn't repro in TypeScript. I'm not sure what the difference is. It might be a VS Code bug unless there's some way for us to restore the focus.

**Comment by demidenko** [comment]
Well,l I wrote not all: the way I described was with open bottom panel (with "Problems", "Output", "Terminal"...)
If I do it with closed panel it opens on preview then closes on shift+enter and focus is ok

**Comment by sean-mcmanus** [comment]
One "workaround" is to hit F6....there are other keyboard command combinations that work too.

I don't think our extension has a way of fixing this, and it repros with the Python extension too -- can you file a VS Code bug (https://github.com/microsoft/vscode/issues) and mention it repros with the C/C++ and Python extensions (when the preview is used) but not TypeScript? I could file the bug myself too, if you want.
