### ISSUE TITLE
"##" (concat) macro-replacement

### ISSUE THREAD

**Issue by epccs** [microsoft/vscode-cpptools#6159]
In c_cpp_properties.json I should be able to put 

```
            "defines": ["__AVR_DEV_LIB_NAME__ = avr128da28", "F_CPU = 16000000UL"],
```

and I think Intellisense should track it through #include <avr/io.h> which would then include "ioavr128da28.h". However Intellisense does not seem to know how to deal with this level of "##" (concat) macro-replacement.

```
#elif defined (__AVR_DEV_LIB_NAME__)
#   define __concat__(a,b) a##b
#   define __header1__(a,b) __concat__(a,b)
#   define __AVR_DEVICE_HEADER__ <avr/__header1__(io,__AVR_DEV_LIB_NAME__).h>
#   include __AVR_DEVICE_HEADER__
#else
#   if !defined(__COMPILING_AVR_LIBC__)
#       warning "device type not defined"
#   endif
#endif
```

I have been using forcedInclude for now

```
            "forcedInclude": [ "${workspaceFolder}/lib/AVR-Dx_DFP/include/avr/ioavr128da28.h" ],
```

for referance my c_cpp_properties.json and an io.h

https://github.com/epccs/MacGyver/blob/master/.vscode/c_cpp_properties.json
http://svn.savannah.gnu.org/viewvc/avr-libc/trunk/avr-libc/include/avr/io.h?revision=2499&view=markup

**Comment by bobbrow** [comment]
Real quick, can you try removing the whitespace around the `=` operator in your defines and see if that makes a difference?  I didn't think we supported adding defines like that (it's not something I remember testing).

**Comment by Colengms** [comment]
Hi @epccs .  As Bob mentioned, it looks like the white space is an issue.  I'm able to repro, but not if the macro name is immediately followed by the "=".

You should be receiving an IntelliSense error in the Problems pane due to the macro not being parsed properly.  i.e. "command line error: invalid macro definition: ...".  Are you seeing that?

**Comment by epccs** [comment]
I guess it is working. The mouse over was not showing the full evaluation, but the error looks correct. I just need to figure out how to make it look in the place I have the file.

![concat_macro-replacement](https://user-images.githubusercontent.com/12041339/93407666-8cfd5300-f847-11ea-8861-0b914c651c01.png)

**Comment by Colengms** [comment]
@epccs I believe it's a known issue that macros are only resolved 1 level deep on hover, not recursively.  (I'd be surprised if we don't already have an issue open for this, but am still searching for it.  I will mention it when/if I find it.  It's an issue in VS as well).  Otherwise, it sounds like your issue is resolved, so I'm going to close this.

**Comment by epccs** [comment]
Thank you. Also, I am very much enjoying VSCode.
