### ISSUE TITLE
"Switch Header/Source" doesn't find extensionless headers

### ISSUE THREAD

**Issue by IcedLance** [microsoft/vscode-cpptools#618]
- cpptools Version: 0.10.5

Steps to Reproduce:

1. Have a complicated folder structure with several classes of same name in different folders and different namespaces, but in files with the same name
2. Automatic Alt+O "Switch between Source/Header" jumps to a wrong header.

Example: 
https://github.com/openscenegraph/OpenSceneGraph/
Pressing Alt+O when at ./src/osg/Geode.cpp
jumps to ./src/osgPlugins/ac/Geode.h
instead of ./include/osg/Geode     [no .h at the end]

Doesn't work at all when in ./include/osg/Geode

**Comment by sean-mcmanus** [comment]
Header switching currently only works with a set of hard-coded header (and source) file extensions like .h, .hpp, .hh, and .hxx, so the extensionless "Geode" header will not work. We might be able to add this ability later, although even Visual Studio doesn't switch to extensionless headers. If you find another issue using headers with extensions, let us know.

**Comment by mjendruk** [comment]
I have similar issue. I have the following folder structure (simplified)

```
componentA/tests/inc/TestDataBuilder.h
componentA/tests/src/TestDataBuilder.cpp
componentB/tests/inc/TestDataBuilder.h
componentB/tests/src/TestDataBuilder.cpp
```

When `componentB/tests/inc/TestDataBuilder.h` is opened and I press Alt+O, the editor jumps to `componentA/tests/src/TestDataBuilder.cpp` instead of the source file in `componentB`. When I press Alt+O a second time, it jumps to `componentA/tests/inc/TestDataBuilder.h`. It seems that the algorithm simply picks the first header it finds in alphabetical order without considering locality.

**Comment by da2r-20** [comment]
I have the same issue as @mjendruk

**Comment by sean-mcmanus** [comment]
@mjendruk Your repro is different from the original issue. I've filed a new issue for you at https://github.com/Microsoft/vscode-cpptools/issues/2635 .
