### ISSUE TITLE
How do I add the linkers for a library in c++ in VS.CODE . I want to be able to play audio files using the lwinmm lib 

### ISSUE THREAD

**Issue by siddharthvaddem** [microsoft/vscode-cpptools#6191]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment]
@siddharthvaddem  is this a question on adding library dependencies to your build tasks.json? Or configuration the IntelliSense of the C++ extension to know where some libraries are?

**Comment by siddharthvaddem** [comment]
I need to use a library called lwinmm (to play wav files)  and add that dependency but don't know how to do it .Here is a link to the same in VISUAL STUDIO but I couldn't find a single source to do it in Visual Studio Code.

https://www.youtube.com/watch?v=9WeDQHi6sJs

There  is  LINKER option in the project properties in visual studio .How do we do that here in VSCODE. 
Im not familiar with changing properties in the JSON file 
Kindly help

**Comment by michelleangela** [comment]
Here's a tutorial for creating a "Hello world" program that uses the C++ extension for IntelliSense and the tasks.json of VS Code for compiling the program. The launch.json is used to launch and debug a compiled program.
https://code.visualstudio.com/docs/cpp/config-msvc

Note that the C++ extension configuration is only for configurating IntelliSense and not compiling/building a program. So if you want IntelliSense to recognize any third party libraries, you will need to add the path to the library in the c_cpp_properties.json file. In order to add the library when compiling the program, you will need to specify the path of the library in the task that compiles the program in the tasks.json file.

**Comment by siddharthvaddem** [comment]
Thanks a lot . I have been able to do what I wanted.
