### ISSUE TITLE
win32 in configuration UI shows double text

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#6200]
Type: General

**Describe the bug**
- OS and Version: Microsoft Windows [Version 10.0.19041.487]
- VS Code Version:

Version: 1.50.0-insider (user setup)
Commit: e80644fd7da69295b18e7f79403720dd1b155507
Date: 2020-09-22T10:11:29.896Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. Run select a configuration command
2. Select Edit configurations (UI)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/2193314/94053333-10123200-fd8f-11ea-9e61-f0f27eab2533.png)

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by michelleangela** [comment]
It looks like this got fixed in the latest VS Code insiders update.

Version: 1.50.0-insider (user setup)
Commit: 73b33dcbc8204c23ae30b53ce129b32c6da98197
Date: 2020-09-24T09:42:09.149Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/38734287/94185982-efafa980-fe5a-11ea-93b0-e5ac9bd495df.png)
