### ISSUE TITLE
No symbols found: scope/navigation UI and gotoSymbol failed on linux

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#621]
_From @alandawkins on April 9, 2017 1:18_

## System info
- VSCode Version: 1.11.1
- OS Version: Linux 4.4.0-72-generic, Ubuntu 16.04.2 LTS
  - this issue have been there at last several system updates. : (

## Steps to Reproduce:

1. open a .cpp file
2. ctrl+shift+o
3. NO symbols found, scope/navigation UI is always in global scope(no matter I'm in global function, member function or class declaration)

## Related settings(I think...maybe)
- "C_Cpp.autocomplete": "Disabled",
- "editor.renderWhitespace": "all",
- "files.encoding": "gbk",
- "[cpp]": {
        "editor.quickSuggestions": true
      },

## Other info
- I have also Windows installed beside Ubuntu(dual boot) and it seems works fine.

_Copied from original issue: Microsoft/vscode#24338_

**Comment by sean-mcmanus** [comment]
@alandawkins The language server process only works on 64-bit Linux. Are you using a 32-bit Linux? Does right-clicking in the file show "Go to Definition"? Does it work with UTF8 encoding? Our code expects UTF8 encoding and probably doesn't work with other encodings.

**Comment by alanldawkins** [comment]
## more info:
- 64-bit linux;
- Go to Definition & Peek Definition work;
- UTF-8 encoding file;

All the problem are (even **several minutes** after the file was opened): 1. "No symbols found";  2 always "(global scope)" on the status bar.
Really sorry about this if just I have this problem.

**Comment by sean-mcmanus** [comment]
@alandawkins Does Go to Definition just show up or does it actually work? If the (global scope) is always shown, it seems like Go to Definition wouldn't be working. You are probably not the only person having the problem, and it's supposed to work in general. Are you able to create a repro project for us? It's hard to diagnose the problem without a repro. What happens if you open a folder with just a single C++ file and some functions/variables? Our parser could be failing to parse a particular file, and/or the process could be crashing.

**Comment by alanldawkins** [comment]
## Steps to Reproduce:
1. open a .cpp file
2. ctrl+shift+o
3. No symbols found; always "global scope" in status bar, click it, "there are no entries to pick from "

## NOTE:
- Goto definition works fine
- Peek Definition works fine (I can edit file in the poped window)
- keyboard shortcut and mouse do not have difference
- hover on the function call, the function declaration does show up
- situation are same when there's only one .cpp in a folder or multi-file like .h with .cpp
- again. the dual booted Windows 10 works fine (both stable and insider version)

**Comment by sean-mcmanus** [comment]
@alandawkins I'm still not able to repro this on Linux. What does Ctrl+T give? I assume no symbols too? Do you have any search.exclude settings set? This combination of features failing is very unusual. What other extensions do you have installed? There must be something unusual that is causing the repro. You could try changing the databaseFilename setting to something like `${workspaceRoot}/.browse.vc.db` to regenerate the browse database which has the symbols, but usually the Go To Def and Hover would be failing too if symbols were missing.

**Comment by bobbrow** [comment]
If you have any additional info to share with us (e.g. an open source repo, a `c_cpp_properties.json` file, etc), we can attempt to investigate further.  Unfortunately, this issue is not currently actionable.  You can also try the latest version of the extension and see if the issue has been fixed already.
