### ISSUE TITLE
Add a way to enable a colon in includePath to be treated as a literal instead of a path separator (on Linux/Mac).

### ISSUE THREAD

**Issue by Rigel-Alves** [microsoft/vscode-cpptools#6237]
Hi,

Visual Studio Code's IntelliSense feature is not working for me, as it is unable to detect headers located in paths which include the ":" symbol, like e.g.:

/run/user/1000/gvfs/sftp:host=taurus.hrsk.tu-dresden.de,user=alves/lustre/ssd/ws/alves-paraview/v5.7.0/install/include/paraview-5.7

The path is split into two, before and after the ":" symbol, so IntelliSense never reaches the headers located there. That's what I see in my C/C++ settings in VS Code:

![Captura de tela de 2020-10-01 09-59-32](https://user-images.githubusercontent.com/35175087/94783705-5b4ec500-03cd-11eb-9988-7b073b5cb6fc.png)

I am using version 1.49.2 of VS Code (with v1.0.1 of the C/C++ extension) in an Ubuntu 20.04.1 LTS, but this issue -- which did not happen around 1 year ago -- has been present since Ubuntu 18.

Could you help me?

Thank you very much,

**Comment by bobbrow** [comment]
The behavior changed here: https://github.com/microsoft/vscode-cpptools/pull/5229.

If you need a quick fix, you can update the `dist/main.js` file in the extension's installation folder by changing line 50123.  Replace `util.envDelimiter` with `";"`.

![image](https://user-images.githubusercontent.com/12818240/94862269-94972d00-03ed-11eb-8b14-e53e79fc87f3.png)

**Comment by Rigel-Alves** [comment]
Thank you very much, @bobbrow. How can I get to that file (`dist/main.js`) in my Ubuntu system? I tried searching for it, without success.

**Comment by bobbrow** [comment]
It should be under `~/.vscode/extensions/ms-vscode.cpptools-1.0.1`

**Comment by Rigel-Alves** [comment]
Found it! Thanks!

**Comment by Colengms** [comment]
The colon character is used to delimit paths in includePath, similarly to how paths are delimited in the environment PATH (i.e. in `echo $PATH`) on both Linux and Mac (whereas a semi-colon is used as the delimiter on Windows).  Paths with colons in them are not supported or escapable in the env path, so similarly would seem unsupportable, unless we were to remove support for delimiters in includePath, add a setting to alter how they are handled, or deviate from the syntax used by the env.

From [SUSv7](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03): 
> Since \<colon\> is a separator in this context, directory names that might be used in PATH should not include a \<colon\> character.

As such, I'm inclined to consider this a feature request rather than a bug.

**Comment by Rigel-Alves** [comment]
Thanks @Colengms for your reply, but the problem is that it was working before, around 1 year ago. Then VS Code's behavior changed and it stopped working (see above).

**Comment by Colengms** [comment]
@Rigel-Alves The reason it started repro'ing is that we 'fixed' a bug in which the wrong path separator was used on Mac and Linux.  (We were using semi-colon, despite Linux and Mac using a colon instead).  The correct behavior you had previously seen was actually the consequence of a "bug", arguable.
