### ISSUE TITLE
C/C++ Configurations Warnings window steals focus every 2 seconds

### ISSUE THREAD

**Issue by jineens** [microsoft/vscode-cpptools#6308]
![image](https://user-images.githubusercontent.com/44418806/95927535-d7ed8600-0d73-11eb-81e5-05a405b8e754.png)

I updated the extension today and now have lost all intellisense and ability to use vscode without disabling the extension. Every 2 seconds, the C/C++ Configuraitons Warnings log shows the output window, an "new" (same as the last million) error. I tried to remove logging via the other c/c++ logging settings and that did not help.

**Comment by jineens** [comment]
@Colengms pretty sure this is from #6180

**Comment by Colengms** [comment]
I can definitely fix the focus stealing.  The number of errors appears to be due to attempting to probe the compiler for each of the entries in your `compile_commands.json`.  Normally, it should only probe once per compiler path + relevant args, but it looks like that isn't handled correctly on failure.  We should be able to fix that too.  You could also set `compilerPath` in your `c_cpp_properties.json` to override the compiler path found in `compile_commands.json`.  Or, if there isn't an equivalent compiler that we can successfully probe, you could set `compilerPath` to a blank string `""` to prevent compiler probing entirely.

**Comment by Colengms** [comment]
A fix for the focus stealing will be available in the next insiders.  Using this issue to track that.  The issue with probing the compiler excessively is a more difficult problem.  Currently only gcc, clang, and related/derived compilers can be probed.  (cl.exe doesn't count.  We don't need to probe it).  We know what args are relevant for those compilers, and can restrict probing to only when relevant args differ.  However, we don't know anything about gomacc.exe, and are likely not going to understand it's output when probing it.  In that case, I would suggest setting `compilerPath` to `""` to prevent probing of compilers from your compile_commands.json.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders2 (the Configuration Warnings should only appear once per session).
