### ISSUE TITLE
extension preview (marketplace) shows garbage

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode-cpptools#6364]
This is not only related to this extension, but very recognizable with it, so I'm posting it here.

This is what the extension preview looks like:
![preview](https://user-images.githubusercontent.com/6699539/96706994-983c2500-1397-11eb-93cc-062239ca4e46.png)

the "garbage descriptions" come from https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json and are normally translated at run-time, which isn't possible in the marketplace.

So I do wonder: Should there be two versions of package.json (the original and an additional one created via vscode-nls-dev containing only English strings)?
Should the marketplace (server-side) read a second file and send translated strings to the client?

**Comment by Colengms** [comment]
This is an issue in VS Code, currently tracked here: https://github.com/microsoft/vscode/issues/54111

**Comment by Colengms** [comment]
Since this is tracking a VS Code issue that is not specific to our extension, we're going to close this tracking issue.  Please follow up with the issue in the VS Code repo.

**Comment by GitMensch** [comment]
I agree that this is mainly an upstream bug. Do you see any possibility that the upstream issue may be tackled this year? It effects every extension that use localization in its package.json.

The workaround for the bug (which possibly should be applied here - and then it would be reasonable to keep it open) would be to temporarily remove the translation from this extensions package.json.

... and I've guessed that the tracking milestone is explicit about bugs in external components that aren't solved (otherwise all of the entries in this milestone should be closed).

**Comment by bobbrow** [comment]
If we remove translation then the commands and settings won't show the correct translations while being used in the product.  I would argue that that has priority over the explanation page in the Marketplace.

We review issues from time to time and make changes to our process periodically. This issue was more generic and didn't seem to be worth tracking here, so we decided to close it.  Most of the "Tracking" issues are linked to issues that affect just C++ developers.  Our process isn't perfect, but if this issue is important to you, we recommend subscribing to the VS Code issue and adding a 👍 reaction to it so that the VS Code team can prioritize it appropriately.
