### ISSUE TITLE
Discerning highlight portions of words is broken

### ISSUE THREAD

**Issue by wolf99** [microsoft/vscode-cpptools#6370]
Type: General

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): Almost any dark colour theme
- A clear and concise description of what the bug is: Symbol is highlighted when cursor is present within symbol, same colour used to highlight selected text within the symbol; thus impossible to discern the diference

**To Reproduce**
1. Install the C/C++ extension and any dark colour theme. I use (and it seems worst for) Dracula official. This occurs with other dark themes, some to a lesser extent and some to the same extent
2. Load a C `.c` source file
3. Select a portion of text within a symbol, such as a constant
4. Unable to see which text is selected and which is not

**Expected behavior**
Able to differentiate which text is selected and which is not

**Screenshots**
What selecting should look like (filetype set to Go, "bc" selected on line 3):
![image](https://user-images.githubusercontent.com/281700/96785974-7a96ac00-13e7-11eb-95cc-c4f5afb5c530.png)

What it actually looks like (filetype set to C, hint "FISH" is selected here)
![image](https://user-images.githubusercontent.com/281700/96785393-a5343500-13e6-11eb-8a66-b9d225946693.png)

**Additional context**
This seems a dupe of #5656, except the reason given their was basically "that's VS Code for you". I hope from the below information you can see that actually, it's not there's something else going on here.

This occurs with *only* this extension and a dark theme enabled.

This occurs *only* in `.c` and `.h` files. trying the same in files treated as other filetypes (e.g. GO, Python, etc) works as expected.

Setting the editor `"colorCustomization"` setting to adjust this behaviour via overriding the theme colors does not work. Or rather it works for a second, sometimes, then it seems like it gets overridden as the C/C++ extension asserts its dominance and forces the colors into submission and the highlighting disappears and doesn't come back for until about 3-4 selections later.
i.e. The editor and theme are both trying their darnedest to highlight properly, but the C/C++ extension says "No way Jose".

e.g.:
in a C file the same as above, while in a Go-type file:
![image](https://user-images.githubusercontent.com/281700/96786216-dbbe7f80-13e7-11eb-9e4c-f7f77c9bd568.png)

This is **intensely** frustrating

**Comment by wolf99** [comment]
Further testing shows it works for some things in a C file

![image](https://user-images.githubusercontent.com/281700/96787128-25f43080-13e9-11eb-9aea-c6c44c5eaa65.png)

Except here I have selected ASSERT using the shift and cursor keys
![image](https://user-images.githubusercontent.com/281700/96787199-43c19580-13e9-11eb-8a33-73b9b540a5c2.png)

**Comment by Colengms** [comment]
Hi @wolf99 .  The C/C++ Extension does not specify the colors involved in the scenarios you are describing, so this is external to us.  I'd suggest following up in the VS Code repo: https://github.com/microsoft/vscode   Or, with the authors of the themes you are seeing the issue with.

>highlighting disappears and doesn't come back for until about 3-4 selections later

What you describing sounds like it _might_ be related to semantic colorization.  Semantic tokens essentially require compilation to identify.  Their colors may update as the extension completes an IntelliSense pass, and identifies new tokens.  However, the C/C++ Extension does not control these colors either.  It's possible that the theme(s) you are using are providing non-ideal colors for these tokens.  Perhaps they predate the introductions of semantic colorization in VS Code?

https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

Colorization guidance for C/C++ specific semantic tokens: https://code.visualstudio.com/docs/cpp/colorization-cpp

Or, if not due to semantic tokens, I would suspect a VS Code bug.  Generally, the C/C++ extension does not directly set any specific colors in the editor, with the exception of style of inactive regions, which can be controlled using the settings: `C_Cpp.inactiveRegionBackgroundColor`, `C_Cpp.inactiveRegionForegroundColor`, `C_Cpp.inactiveRegionOpacity`.  All other colors are based on the theme, user color customizations, or are otherwise set by VS Code.

**Comment by wolf99** [comment]
Hmm sounds good... except that if I disable the C/C++ extension the problem goes away and, as mentioned I am testing with is with only the theme and the C/C++ extension enabled - so no other extensions causing it.
The theme and VS Code are still at work during this test, l so not the theme nor VS Code.

I'm sorry I'm not clear from your info if disabling the C/C++ extension will affect semantic colorization, but if not that onl;y leaves the extension as the culprit, right?

**Comment by Colengms** [comment]
@wolf99 There are a couple of features that involve the C/C++ Extension providing editor ranges to VS Code, such as semantic tokens (which I described above), and document highlighting - which occurs when you select a symbol and highlights all other occurences of that symbol in the file.  I suspect you are seeing the result of one of those 2 features.  However, the colors used in both of those features are not provided by the C/C++ Extension.  For document highlighting, we simply return a `DocumentHighlightKind`.  Might this be a dupe of? : https://github.com/microsoft/vscode/issues/100530

**Comment by wolf99** [comment]
Thanks for the added info!
You are correct about the dupe.
