### ISSUE TITLE
CMake extension interferes with symbol indexing/search on Linux

### ISSUE THREAD

**Issue by vritxii** [microsoft/vscode-cpptools#639]
I have installed the cpptool and some C++ plugins,In my C++ project,  the symbols search is working on windows but on linux isn't ok. My windows is win10 64bit, Linux is deepin 15 64bit which based on ubuntu, kernel is 4.4. There is also without browser.VC.db on .vscode though I have generate the c_cpp_propertity.json. After using a afternoon to find the solutions on google, it still can't working, oh my god! Please help me. @sean-mcmanus

**Comment by sean-mcmanus** [comment]
What are the versions of VS Code and the cpptools extension? Do you see "Go to Definition" when you right-click? What is the behavior of Microsoft.VSCode.Cpp.Extension.linux? Does symbol searching work on a simple project? FYI, we only show global symbols and not symbols local to functions. What other extensions do you have installed? If another extension is implementing symbol search for C++ files, the other extension could be failing.

**Comment by s-imphead** [comment]
(cpptools 0.11.0, April 24, 2017) 
The bug seems to be that on Linux, the Mac configuration is read. By stating all include paths in the "**Mac**" (not Linux!!!) configuration section of c_cpp_properties.json, I have intellisense working on Linux.  I'm a total newbie and couldn't figure out even how to see the selected configuration. Also, "C/Cpp: Select a Configuration" to "Linux" didn't help. (I also used the "default" setting forC_Cpp.intelliSenseEngine, see https://blogs.msdn.microsoft.com/vcblog/2017/04/25/visual-studio-code-cc-extension-april-2017-update/).

**Comment by sean-mcmanus** [comment]
Hmm, I'm not able to repro what you're describing. The configuration that is shown in the bottom right should be the one that is used.

**Comment by s-imphead** [comment]
I didn't see any configuration information where you describe it, so that's a clue!  I disabled CMake Tools and reloaded. Now, I see "Linux" in that corner. Even better, my C++ file is now parsed according to the c_cpp_properties.json, Linux section. So, this is a problem with CMake Tools.  Thanks for your help.

**Comment by sean-mcmanus** [comment]
Oh...if CMake Tools is somehow breaking us, then we should probably figure out if there's a way to work around them.
