### ISSUE TITLE
Add localization to strings in LanguageServer\cppBuildTaskProvider.ts

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6436]
I see several user facing strings that aren't localized, for example:
1. "compiler: "
2. "Generated task by Debugger".
3. "Starting build..."
4. "Build finished with error".
5. "Build finished successfully"

Not sure if " build active file" can be localized (it's possible it may intentionally be in English due to technical reasons, in which case a comment should be added).

**Comment by Jianchaoliang** [comment]
unsubscribe


| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/4/2020 08:07，Sean McManus<notifications@github.com> wrote：

I see several user facing strings that aren't localized, for example:

"compiler: "
"Generated task by Debugger".
"Starting build..."
"Build finished with error".
"Build finished successfully"

Not sure if " build active file" can be localized (it's possible it may intentionally be in English due to technical reasons, in which case a comment should be added).

**Comment by sean-mcmanus** [comment]
@Jianchaoliang Why are you spamming our issues? We may block you from posting.

**Comment by michelleangela** [comment]
@Jianchaoliang  to unsubscribe from a thread, please select the "Unsubscribe" button as shown in the screenshot

![image](https://user-images.githubusercontent.com/38734287/98059080-13bbbe80-1dfb-11eb-9b58-a3d31b3238c4.png)
