### ISSUE TITLE
Show wrong color on code block and can't autocomplete

### ISSUE THREAD

**Issue by ShiquanYu** [microsoft/vscode-cpptools#6443]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.48
- C/C++ Extension Version: 1.01
- Other extensions you installed (and if the issue persists after disabling them): vscode-icon
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
  project number: 2
  project size: 684M
  After I use vsc for a while(about half an hour), the color of param/func will show wrong colors! and it can't auto complate.
  When i put the mouse cursor on the wong color param, it will show another param's define
  This problem occurs when I'm using vsc, and the vsc is automatically updated, the computer was stuck for a long time, after that, the color will always show wrong color and can't auto complate.
I have reinstall vsc for several times, and i have try to delele  "/home/.cache/vscode-cpptools" "/home/.vscode" "/home/.config/Code" and re install vsc, but it's useless

**Steps to reproduce**

1. open vscode
2. coding for a while

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![Picture1](https://user-images.githubusercontent.com/19343656/98221396-87d89c80-1f8a-11eb-9416-a2b12c4abb70.png)
![Picture2](https://user-images.githubusercontent.com/19343656/98221854-1f3def80-1f8b-11eb-98a7-4cbf17ca6949.png)
**Additional context**

**Comment by Colengms** [comment]
Hi @ShiquanYu .  Would you be able to provide the output of the C/C++ output channel leading up to the repro?  Or, if that is difficult to capture, perhaps all contents of the C/C++ output channel after the repro occurs?  Also, after the repro occurs, can you provide the output of the `Log Diagnostics` command (if it works)?

I suspect there is a crash occurring, at which point auto-complete (and other language server features) stop working.  The mismatched colors may be an issue with VS Code trying to keep track of semantic tokens, which we are not longer providing updates for due to crashing.  Logs may provide us with some additional clues.

**Comment by ShiquanYu** [comment]
Hi @Colengms.
Thank you for your prompt reply, this problem almost drives me crazy.
I find a log under the path `/home/.config/Code/logs`, and i find some errors in file `renderer1.log` under the path
```
[2020-11-06 09:04:55.366] [renderer1] [error] Unable to install extension 'ms-vscode.cpptools' as it is not compatible with VS Code '1.48.2'.: Error: Unable to install extension 'ms-vscode.cpptools' as it is not compatible with VS Code '1.48.2'.
    at file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:578:712
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-11-06 09:06:26.192] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-11-06 09:06:28.205] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
```
Is this what you call `Log Diagnostics`? if not, how can i output the `Log Diagnostics`.
Thank you vvvvvery much!

**Comment by Colengms** [comment]
Hi @ShiquanYu .  As we update the C/C++ Extension, we sometimes rely on fixes and improvements made to VS Code itself.  It looks like we now require v1.49.0 of VS Code, which is more recent than the version you have installed.  Could you upgrade to a more recent version of VS Code?  On Ubuntu, that would seem to involve installing updates.  Or, if you did not install using a package manager, you may need to install a more recent version manually.  Could you try installing the latest VS Code version, and let us know if you are still seeing this issue?

**Comment by Colengms** [comment]
Hi @ShiquanYu .  We think the error message you posted may actually not be the root cause.  It looks like we are trying to install an Insiders version that does not apply to your version of VS Code, due to an incorrect version check.  But, perhaps would not lead to an issue with the version you already had installed.

Do you see an entry for "C/C++" in the `Output` view ('View' menu -> 'Output')?   If so, that is the 'output channel' I was referring to.  The "C/C++: Log Diagnostics" command should be available via the Command Palette (Control-Shift-P, by default, then start typing "Log Diagnostics").  Let me know if that command is not available.

**Comment by ShiquanYu** [comment]
Hi @Colengms. Sorry for my late reply, because of the problem disappeared after i install the version 0.29.0 of cpptools and update it to 1.01, but there is also show the same error message in file `renderer1.log` .
The first time this problem occurred is the VS Code 1.50, then i remove vscode, delete the folder `.config/Code` `.cache/vscode-cpptools` `.vscode`, reboot my computer, and download the latest version(1.50) of VS Code, and install cpptools, but the problem still there.
I will continue to test, and if the problem recurs again, I will post the `C/C++: Log Diagnostics` here.
Thanks for your work!

**Comment by ShiquanYu** [comment]
Hi @Colengms . I have been testing all day, the problem seem to have been fixed.

The following is how this problem happened and how it disappeared magically:

### Happend

1. I'm coding with vscode(both `c` and `python`, 4 vscode windows)
1. Use cv2.show to view images
1. The system stuck for several minute(memory is enough, maybe there is something upgrade background, now i close all autoupdate)
1. The code begin to show wrong color, and if put your mouse on param/func/def, it will show another define
1. Reinstall vscode with 1.50, the problem still exists
1. Delete folder `.config/Code` `.cache/vscode-cpptools` `.vscode`, reboot computer, reinstall vscode,  the problem still exists

### How it disappeared

1. Reinstall cpptools with version 0.29.0
1. Update cpptools to latest version
1. The problem disappeared magically!

Hope this can help those who have the same problem as me.

Thanks for your patient answer!

**Comment by Colengms** [comment]
Hi @ShiquanYu .  I'm glad to hear the issue has been addressed.  I suspect there was an issue with downloaded dependencies that failed to be fully installed.
