### ISSUE TITLE
VSCode with WSL - Debug mode of C won't show printf commands unless using /n

### ISSUE THREAD

**Issue by shirans7** [microsoft/vscode-cpptools#6451]
VSCode Version: 1.50.1
OS Version: Windows 10 (build 2004) with WSL enabled
When debugging a C language code with gdb there is no output showing if using the following print command:
printf("%d", i);  but using the same command with /n printf("%d\n", i) makes the output showed in the terminal.

I have created this sample code to show the differences:
![image](https://user-images.githubusercontent.com/74029967/98316326-dd409800-1fe2-11eb-8ff8-09b28fbb0a2c.png)

![image](https://user-images.githubusercontent.com/74029967/98316310-d7e34d80-1fe2-11eb-9605-77fb4ff2d5c0.png)

Adding my launch.json file:

![image](https://user-images.githubusercontent.com/74029967/98316304-d2860300-1fe2-11eb-8f4e-3dd57c3d35e3.png)

Any idea how can I fix it?

**Comment by calgagi** [comment]
Have you tried flushing stdout after printing?

printf writes to the output stream `stdout`, and then `stdout` waits to be flushed (so it can then be displayed in the terminal). It must be flushed to be displayed which is normally accomplished via newline characters (`\n`) since `stdout` is line-buffered.

You can also manually flush an output buffer with `fflush`. 

Try adding this after your printf statement: `fflush(stdout);`.
