### ISSUE TITLE
Color Theme for C++ Class Object

### ISSUE THREAD

**Issue by sstaub** [microsoft/vscode-cpptools#6507]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Catalina 10.15.7
- VS Code Version: 1.51.0
- C/C++ Extension Version: 1.1.1
- Other extensions you installed (and if the issue persists after disabling them): PlatformIO

The color of a class object (e.g. MyClass myObject) in C++ is interpreted as the color of a variable ("scope": "variable").
It should possible to give the class objects their own color definition in the color theme .json file
The same for the class method, in the moment the color of a class method is the same as the color for a function.
It will help to differ methods from functions

Here some screenshot for better understanding:
first I use a grey color for the scope "variable", then red for the second example.
<img width="352" alt="image" src="https://user-images.githubusercontent.com/6450325/98925322-235f9500-24d6-11eb-8614-72d07e3db650.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/6450325/98925104-e5627100-24d5-11eb-94b1-6b0e0e87be1f.png">

here what happens in the code when 'variable' is grey:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/6450325/98925388-370afb80-24d6-11eb-9a1f-abcf634cbe43.png">
now when red:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/6450325/98925432-40946380-24d6-11eb-8528-8ff5572d550a.png">
The color of the green marked 'variable' is changing together with cyan marked 'class object'.
I would expect that a 'class object' has a different color.
The same for the orange marked 'functions', the first function is real single 'function', the second one
is also a function but also a 'class member', therefore there should also different colors.

I made an issue on vscode https://github.com/microsoft/vscode/issues/105675
and was forwarded to https://github.com/jeff-hykin/cpp-textmate-grammar/issues/517

That's the answer, so I made an issue here, hope you can help me.

```
There should be some difference in the scope between the different colored boxes you can use 
the command palpate action > Developer: Inspect Editor Tokens and Scopes to examine the scope. 
However due to how textmate grammars work it's not always possible to determine the correct scope for each token. 
You may want to try the semantic coloring for the C/C++ extension.

Edit: After examining the provided examples, I can see that you are using the semantic coloratization. 
You may wish to file an issue with the cpptools extension.

With this grammer with regards to functions you can distinguish between:

function definitions: entity.name.function.definition
free function calls: entity.name.function.call
member function calls: entity.name.function.member
```

**Comment by Colengms** [comment]
Hi @sstaub .  The C/C++ Extension provides semantic colorization.  The underlying syntactic colorization is from VS Code (and the TextMate grammar you referred to).  You can confirm which colors are coming from us vs. VS Code by enabling/disable the C/C++ Extension, or the `C_Cpp.enhancedColorization` setting.  However, you will need to reload the window, due to https://github.com/microsoft/vscode/issues/97196 .  The semantic tokens we support are documented here: https://code.visualstudio.com/docs/cpp/colorization-cpp

Note that we do have distinct tokens for functions vs. member functions vs. static member functions.  If you provide a color for the member function semantic token scope (or the fallback TextMate scope for it), you should see it colored different from regular functions.

Class (type names) will be colored different from variables.  Currently, the only variation in colorization for variables is globals vs. locals vs. parameters.    It sounds like you are suggesting that variables that are instances of user-defined classes be colored differently from variables that are not instances of user-defined classes?  That might not be as simple as suggested, as the concepts of 'type' and 'class' are inherently blurred in C++.  C++ considers all types to be 'classes'.  (For instance, when you declare a template as `template <class T>`, types that are not user-defined classes can be provided).
