### ISSUE TITLE
Outliner not detecting variables in functions (C++)

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/vscode-cpptools#6570]
**Describe the bug**

Outliner not detecting variables in functions (C++)

- OS and Version: Win 10
- VS Code Version: 1.51.1

- C/C++ Extension Version:
1.1.2
- Other extensions you installed:
![image](https://user-images.githubusercontent.com/20190653/100011788-899bc000-2dd2-11eb-8214-5877ff262d30.png)

**Steps to reproduce**
Install the .cpp extension as well as WingW64 compiler, create a .cpp file and create a function with some variable in it. These variables wont appear in the outliner like you would expect.

**Expected behavior**
They should appear as a child object to the function they are declared in.

**Screenshots**
![image](https://user-images.githubusercontent.com/20190653/100011682-5e18d580-2dd2-11eb-8c7f-06a3ae9320b6.png)
-->

**Comment by Colengms** [comment]
Hi @ItsCubeTime.  It's currently by-design that the outline does not descend into functions.  We can use this issue as a feature request to track changing this behavior.  Feature requests are generally prioritized based on the number of upvotes.

**Comment by ItsCubeTime** [comment]
Thanks for your reply @Colengms .

Why not make it an option in the settings file? The extension API supports hierarchies and the Python extensions does make use of it already like so variables in functions are displayed in a tree.

Also in: https://github.com/microsoft/vscode-cpptools/issues/4124 (which was closed as a dup to #2230 ) it was said that "We just started work on this feature for 0.26.0. We are tracking with #2230. Thank you!". So there it seemed like this was supposed to have been implemented with #2230 ?

**Comment by sean-mcmanus** [comment]
We implemented the new document symbol API, but symbols in functions was never a part of that. Our paid product (Visual Studio 2019) doesn't support workspace/outline symbols for local variables either. The reason is that our symbol parser and doesn't run inside of function bodies. The functionality doesn't exist, so adding an option is not sufficient. If it's implemented, then we might not even need an option, because it'd just be the default.

Hover/go to def for local variables is handled by a different system (IntelliSense symbols), but those symbols are not accessible to the outliner implementation.

**Comment by ItsCubeTime** [comment]
Hi @sean-mcmanus , thanks for the insights.

Well I'm glad you seem to like the idea at least conceptually. For me personally I think it would be a rather big workflow improvement to be able to quickly be able to look up object names in the outliner when working with nested objects. 

I will just hope someone will be able to pick this up at some point (and that there will grow an interest for it from the community).
