### ISSUE TITLE
[C++ pointers/references] *s and &s shift from left to right, changing setting does nothing

### ISSUE THREAD

**Issue by RhittC** [microsoft/vscode-cpptools#6634]
Issue Type: <b>Bug</b>

+ Whenever I type `pointers` or `references` in C++ and tell vscode to format it, vscode shifts the `*` or `&` from `left` to `right`.
+ I've checked the following setting: `C_Cpp › Vc Format › Space: Pointer Reference Alignment`, but it's already set to `left`.
+ Just to check, I've changed the setting to `right` and rebooted my computer, but the bug still remains.

Extension version: 1.1.3
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.69GB free)|
|Process Argv|--crash-reporter-id 4551350c-dddc-4112-9cce-7a24132e8b8e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @Rhitt01 .  The C/C++ Extension supports two different formatting providers.  That formatting provider can be set using the `C_Cpp.formatting` setting.  By default, clang-format used.  Perhaps the issue is that you're currently configured to use clang-format?  If so, it can be configured using `C_Cpp.clang_format_style`.  Or, switching to vcFormat would allow you to configure formatting using the vcFormat related settings.

**Comment by RhittC** [comment]
Hi @Colengms. Thank you! It worked! I changed `C_Cpp.formatting` to `vcFormat` and it doesn’t change from left to right.
