### ISSUE TITLE
CppTools crashing every few seconds, pops up a "Attempting to reconnect" dialog

### ISSUE THREAD

**Issue by ridiculousfish** [microsoft/vscode-cpptools#6697]
Issue Type: <b>Bug</b>

I am using the official C/C++ extension alongside the Remote Development extension. I see an "Attempting to reconnect" dialog every few seconds. If I disable the C/C++ extension, I no longer see the dialog.

I have enabled Debug logging for the C/C++ extension; I see lots of "tag parsing file" in the "C/C++" output and no other output. I have confirmed this occurs with C/C++ version 1.0.0, 1.1.0, 1.1.2, and 1.1.3 (did not test on others).

Our source code base is large and not open source, so I cannot share it, but I am eager to try any steps or provide more information, to help resolve this issue.

Extension version: 1.1.3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.35GB free)|
|Process Argv|-psn_0_14114165 --crash-reporter-id eab1ff6e-8063-4af2-b050-c62c35cfb955|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bender|
|OS|Linux x64 5.4.0-58-generic|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (40 x 800)|
|Memory (System)|62.51GB (38.87GB free)|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
If you see "tag parsing" logging then the cpptools process isn't crashed. You can see what happens when cpptools crashes by running kill on the process id -- it should show "Connection to server got closed. Server will not be restarted.". Just because the issue doesn't repro with the C/C++ extension enabled doesn't mean our extension is the cause. Do you see errors when you do Help->Toggle Developer Tools->Console?

Does the issue repro in a simple/dummy project?

We haven't gotten any reports of "Attempting to reconnect" yet, and I'm not sure what could be causing that. It might be a vscode-remote issue, see https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+is%3Aopen+attempting+to+reconnect

**Comment by ridiculousfish** [comment]
Thank you for the reply. Unfortunately this stopped reproducing for me - I suspect there was a long-running resource leak of file descriptors or something. I will reopen if I see it again.
