### ISSUE TITLE
Compiler querying fails with compilers that do not output __STD_VERSION__ by default (gcc <=4.8.x)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6792]
Hi @Colengms I'm having a similar issue, since I updated **1.2.0-insiders** the `compilerPath` in the **c_cpp_properties.json** doesn't find the compiler, which is in my PATH, Output from C/C++ Warnings:
```
[15/01/2021, 14:14:45] Unable to resolve configuration with compilerPath "arm-openwrt-linux-gcc".  Using "/usr/bin/clang" instead.
[15/01/2021, 14:14:45] Unable to resolve configuration with compilerPath "arm-openwrt-linux-gcc".  Using "/usr/bin/clang" instead.
```
Not sure if it was fixed in 1.2.0.

_Originally posted by @pelco in https://github.com/microsoft/vscode-cpptools/issues/6746#issuecomment-760971715_

**Comment by Colengms** [comment]
Hi @pelco .  I'm not able to easily repro this.  If you specify a compiler path of just "gcc", does that work (assuming gcc is in your env path, which it usually is by default on Linux if installed) ?

**Comment by pelco** [comment]
Hi, @Colengms, Yes! It works with "gcc" and "clang" (both are in my path too).

**Comment by Colengms** [comment]
Hi @pelco .  Ok, that would seem to imply the issue isn't due to not finding an executable in the path.  I suspect the issue is actually that we tried to invoke the compiler to query system includes and system defines, and that failed.  Could you enable debug logging using: `"C_Cpp.loggingLevel": "Debug"`, reload the window, and check the `C/C++` output?  There should be something there related to querying the compiler, including the command line we attempted to use to do so.  Could you post that log output here?

**Comment by pelco** [comment]
Hi, @Colengms I didn't see any errors but maybe you can spot something.
[cpp_debug.log](https://github.com/microsoft/vscode-cpptools/files/5848352/cpp_debug.log)

**Comment by pelco** [comment]
@Colengms There a error when querying the compiler:
```txt
Querying compiler for default C language standard using command line: "/home/pcoliveira/workspace/gateworks/openwrt/staging_dir/toolchain-arm_cortex-a9+neon_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin//arm-openwrt-linux-gcc" -x c -E -dM /dev/null
terminating child process: 23541
Failed to query compiler at path "/home/pcoliveira/workspace/gateworks/openwrt/staging_dir/toolchain-arm_cortex-a9+neon_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin//arm-openwrt-linux-gcc" for default standard versions.  Compiler querying is disabled for this compiler.
Querying compiler's default target using command line: "/home/pcoliveira/workspace/gateworks/openwrt/staging_dir/toolchain-arm_cortex-a9+neon_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin//arm-openwrt-linux-gcc" -dumpmachine
```

**Comment by Colengms** [comment]
Hi @pelco .  I suspect `arm-openwrt-linux-gcc` has diverged from standard GCC and may not be reporting values/defines we depend on to detect its default C++ standard version.  Can you provide the output of invoking the compiler with those args?  (` -x c -E -dM /dev/null`).

**Comment by pelco** [comment]
Hi @Colengms here it is. It seems to be working fine in cpptools v1.1.3.
[arm-openwrt-linux-gcc.txt](https://github.com/microsoft/vscode-cpptools/files/5856231/arm-openwrt-linux-gcc.txt)

**Comment by bejota** [comment]
Same issue with g++ & v1.2.0-insiders2. Using remote development from Win10 to CentOS 7.4.

`[1/22/2021, 4:01:22 PM] Unable to resolve configuration with compilerPath "/usr/bin/g++".  Using "/usr/bin/clang" instead.`

```
bejota@system: which g++
/usr/bin/g++

bejota@system: g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Colengms** [comment]
Hi @pelco .  I found a compiler similar to the one you are using, here: http://dev.gateworks.com/openwrt/14.08/cns3xxx/

It looks like the issue is that this compiler does not fully adhere to the C standard.  The C standard requires the compiler define `__STDC_VERSION__`.  We use this define to detect the default version of the standard used by the compiler.  Specifying `-x c` does not appear to be sufficient to get this compiler to produce that define for C compilation.  We also use the existence of this define to infer whether we can successfully query the compiler at all, and we give up on the compiler if it is not present.  (This is a recent fix, to avoid repeatedly invoking compilers that we cannot successfully probe, which explains why this problem only recently arose).  Oddly, specifying a C standard (i.e. `-std=x1c) does result in this compiler properly specifying the standard define.  I did not see the same issue with the similar `gcc-5.2.0_musl-1.1.12` toolchain.

For now, we can work around the issue by only giving up on a compiler if both the C and C++ default detection fail.  But, this would appear to be a bug in that particular compiler.

**Comment by Colengms** [comment]
@bejota Please open a new issue.  This issue is related to a specific gcc compiler.  In your case, we will need more info, such as the log output that indicates what operation failed, and the command line used which failed.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders3

**Comment by pelco** [comment]
Yes, it works now! Thanks.
