### ISSUE TITLE
[Feature request] have IntelliSenseMode option with unknown platform, compiler and arch

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6813]
I'm working on a project that targets embedded systems.
- working on Macbook Pro
- target system: Arduino (tiny ARM board)

#6745 added definitions for Linux, macOS, WIndows, but no other definitions.

I think it would be nice to have a option that allows users to define their own settings for a particular system without automatically adding them. (like `"intelliSenseMode": "bare"`)

_Originally posted by @zakkie in https://github.com/microsoft/vscode-cpptools/issues/1083#issuecomment-761774115_

**Comment by sean-mcmanus** [comment]
@zakkie Would just the platform being unknown be sufficient, e.g. unknown-gcc-x64? I think our parser will require the compiler and architecture to be known.

**Comment by sean-mcmanus** [comment]
I'm seeing multiple users hitting this, e.g. https://github.com/microsoft/vscode-cpptools/issues/2086#issuecomment-395980343

**Comment by sean-mcmanus** [comment]
It should be possible to workaround this issue via removing the defines in the the `*.json` file (that matches the target intelliSenseMode) next to the extension binaries, but the modification would need to reapplied after any extension update.

**Comment by Colengms** [comment]
This looks very similar to https://github.com/microsoft/vscode-cpptools/issues/4653  This issue goes a bit further, but I suspect the up-votes on the other issue are in favor of what this issue is requesting.  So, closing this issue in favor of the other one.

@zakkie If there is something here that is not tracked by the other issue, please let us know.
