### ISSUE TITLE
Switch header/source may create a 2nd view on a file, potentially with stale content

### ISSUE THREAD

**Issue by nickion** [microsoft/vscode-cpptools#6855]
**Type: LanguageService**

**Describe the bug**
Context:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.18.0-147.8.1.el8_1.x86_64 snap
C/C++: 1.1.3
Other extensions: Awesome Emacs Keymap 0.24.1, Smart Semicolon 1.0.3, Task Explorer 1.27.0 (disabling has no impact on issue)
SSH: This does not involve SSH

Switching between header/source may cause a file to be opened in a new tab even when it is already open in a tab. This can lead to confusion, time wasted if changes are made in the new buffer before the duplication is realised, and may cause loss of work if there are changes in both buffers when files are saved. 

This happens when the path to a workspace directory has symlinks, and appears to be because the path associated with a file opened via the workspace is relative to the workspace directory without symlinks resolved, whereas a file opened via the extension is a realpath with symlinks resolved.  

**Steps to reproduce**

1. Add a directory to a workspace having a symlink. e.g. `~/projectA/src`, where `~/projectA` is a symlink to `/mnt/projects/projectA`, and where `src` contains two files, `file.cc` and `file.h`
2. Open `src/file.cc` via the workspace
3. Open `src/file.h` via the workspace
4. From `src/file.h`, invoke a switch header/source operation
5. A second tab for `file.cc` will open having a path of `/mnt/projects/projectA/src/file.cc`

The expected behaviour would be a switch to the existing tab for `file.cc`.

**Comment by sean-mcmanus** [comment]
The case where file.cc and file.h exist in the same folder would be trivial to fix because that's a special case that doesn't require looking in our database which has the files in the non-symlinked form. Would that be sufficient? If not, we'd have to figure out some way to either preserve the symlinked versions of the paths in our database or create some sort of mapping between them. The TypeScript side of the code that gets the path is from https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/extension.ts#L800 if you have any ideas how to convert the non-symlinked path to the symlinked path (VS Code doesn't offer any normalization API to do this).

**Comment by nickion** [comment]
It would with my file layout, and I'd imagine that would cover most cases.  If `editor.document` is the path, as a general solution perhaps `fs.realpath()` or `fs.realpath.native()` could be used on the paths before comparison in the code around line 804, with a fallback to current behaviour if they throw for some reason. Unnecessary operations could be avoided by comparing path basenames first and caching, however I doubt performance would be an issue in practice.

**Comment by sean-mcmanus** [comment]
Yeah, I've fixed the case where they're at the same location (via a cpptools change) and also if they're at different locations if the symlink is part of a workspace folder path (https://github.com/microsoft/vscode-cpptools/pull/6863), but if they're at different locations and the symlink is a subfolder in a workspace folder, then the bug would still exist because we don't build a mapping between all the realpaths and symlinked folders.

**Comment by Colengms** [comment]
@sean-mcmanus Did this make it into 1.2.1 ?

**Comment by sean-mcmanus** [comment]
Yeah, fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.1
