### ISSUE TITLE
Removing Windows' debugger option when creating launch.json on Mac

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cpptools#6862]
When a user "create a launch.json file" on Mac, they get the "C++ (Windows)" option.

**Comment by Colengms** [comment]
This also impacts Codespaces, so should probably be high priority.

**Comment by elahehrashedi** [comment]
follow up from here: https://github.com/microsoft/vscode/issues/120280

**Comment by Colengms** [comment]
We seem to be blocked on this.  Due to nuances related to remote(?) debugging, VS Code doesn't want to provide a way for us to indicate that one of our debuggers has prerequisites, so we can suppress display of that debugger as an option when those prerequisites are not met.  Perhaps someone who understands their constraints can comment on why that would be an issue.
