### ISSUE TITLE
Under Windows this Extension makes VSCode Almost Entirely Useless

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [microsoft/vscode-cpptools#6865]
It's simply not acceptable to force Windows users to have to run the Microsoft Visual Studio Developer Prompt batch file before this extension will work.

No "Open VSCode here" shell extensions - rendered useless!

VS code is great. It deserves a C++ extension that's equally great, not one that is annoying to use.

Please make it run the vsvars.bat when the extension loads or something?

**Comment by bobbrow** [comment]
Everything in the extension should work fine without running from developer command prompt with the exception of "Build and Debug Active File" which doesn't find the correct vars script for you currently.  It's certainly something we could revisit.  In the meantime you can edit launch.json and add the command to run the vars script before the build.

Are you having trouble with anything else?  Your issue report makes it sound like everything is broken, but we're not aware of such a problem, so if you could be a bit more specific, we can try to help debug what the problem is.

**Comment by sean-mcmanus** [comment]
This is being tracked by https://github.com/microsoft/vscode-cpptools/issues/4742 .

**Comment by sean-mcmanus** [comment]
@codewitch-honey-crisis This was added in https://github.com/microsoft/vscode-cpptools/releases/tag/v1.29.2
