### ISSUE TITLE
Unable to resolve configuration for cygwin64

### ISSUE THREAD

**Issue by franneck94** [microsoft/vscode-cpptools#6902]
Since the latest update i recieve the error/warning about the compiler path for gcc on cygwin64.

```
[4.2.2021, 08:25:46] Unable to resolve configuration with compilerPath "C:/cygwin64/bin/gcc.exe"
```
The compiler is correctly installed and works as expected.

Settings:

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/cygwin64/bin/gcc.exe",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}
```

When i downgrade the extension back to 1.1.3 everything works again.

Software versions:

![image](https://user-images.githubusercontent.com/20141069/106859356-35129c00-66c3-11eb-80fa-09b1ce3993cd.png)

![image](https://user-images.githubusercontent.com/20141069/106859287-1d3b1800-66c3-11eb-89fc-a0d9ba0c6497.png)

**Comment by Colengms** [comment]
Hi @franneck94 .  Could you enable logging with `"C_Cpp.loggingLevel": "Debug"`?  The extension should log what command line it's using te query the compiler (for system includes and system defines).   Then, could you run that same command line and provide it's output here?

I'm not able to repro this issue with my own installation of cygwin locally, so I suspect our versions differ.

**Comment by franneck94** [comment]
## Output in C/C++ Config Warnings

[4.2.2021, 20:41:55] Unable to resolve configuration with compilerPath "C:/cygwin64/bin/gcc.exe".  Using "C:\cygwin64\bin\gcc.exe" instead.
[4.2.2021, 20:41:55] Unable to resolve configuration with compilerPath "C:/cygwin64/bin/gcc.exe".  Using "C:\cygwin64\bin\gcc.exe" instead.

## Output in C/C++
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: 'C:/cygwin64/bin/gcc.exe'
Querying compiler for default C++ language standard using command line: "C:/cygwin64/bin/gcc.exe" -x c++ -E -dM nul
Querying compiler for default C language standard using command line: "C:/cygwin64/bin/gcc.exe" -x c -E -dM nul
Querying compiler's default target using command line: "C:/cygwin64/bin/gcc.exe" -dumpmachine
Compiler returned default target value: x86_64-pc-cygwin

Attempting to get defaults from compiler found on the machine: 'C:\cygwin64\bin\gcc.exe'
Querying compiler for default C++ language standard using command line: "C:\cygwin64\bin\gcc.exe" -x c++ -E -dM nul
Querying compiler for default C language standard using command line: "C:\cygwin64\bin\gcc.exe" -x c -E -dM nul
Querying compiler's default target using command line: "C:\cygwin64\bin\gcc.exe" -dumpmachine
Compiler returned default target value: x86_64-pc-cygwin

No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:/cygwin64/bin/gcc.exe'
Attempting to get defaults from compiler found on the machine: 'C:\cygwin64\bin\gcc.exe'
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
  Folder: C:/USERS/JAN/DROPBOX/_CODING/UDEMYC/ will be indexed
Populate include completion cache.
cpptools/fileCreated: file:///c%3A/Users/Jan/AppData/Roaming/Code/logs/20210204T204151/sharedprocess.log
Discovering files...
cpptools/fileCreated: file:///c%3A/Users/Jan/AppData/Roaming/Code/logs/20210204T204151/telemetry.log
cpptools/fileCreated: file:///c%3A/Users/Jan/AppData/Roaming/Code/logs/20210204T204151/userDataSync.log
  Processing folder (recursive): C:/USERS/JAN/DROPBOX/_CODING/UDEMYC/
  Discovering files: 203 file(s) processed
  3 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
cpptools/getSemanticTokens: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 2)
cpptools/getCodeActions: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 3)
textDocument/didOpen: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c
cpptools/activeDocumentChange: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 4)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 5)
sending compilation args for C:\USERS\JAN\DROPBOX\_CODING\UDEMYC\CHAPTER8_POINTERARRAYS\CALLOCREALLOC\MAIN.C
  include: C:\Users\Jan\Dropbox\_Coding\UdemyC
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  other: --gcc
  other: --gnu_version=100000
  stdver: c17
  intelliSenseMode: windows-gcc-x64
Checking for syntax errors: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c
Queueing IntelliSense update for files in translation unit of: C:\USERS\JAN\DROPBOX\_CODING\UDEMYC\CHAPTER8_POINTERARRAYS\CALLOCREALLOC\MAIN.C
cpptools/finishUpdateSquiggles
Error squiggle count: 5
Error squiggles will be disabled in: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c
Update IntelliSense time (sec): 0.482
cpptools/getSemanticTokens: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 6)
cpptools/getFoldingRanges: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 7)
idle loop: reparsing the active document
Checking for syntax errors: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c
Queueing IntelliSense update for files in translation unit of: C:\USERS\JAN\DROPBOX\_CODING\UDEMYC\CHAPTER8_POINTERARRAYS\CALLOCREALLOC\MAIN.C
cpptools/finishUpdateSquiggles
Error squiggle count: 5
Update IntelliSense time (sec): 0.252
cpptools/getSemanticTokens: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 8)
cpptools/getFoldingRanges: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 9)
Database safe to open
cpptools/activeDocumentChange: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c
Queueing IntelliSense update for files in translation unit of: C:\USERS\JAN\DROPBOX\_CODING\UDEMYC\CHAPTER8_POINTERARRAYS\CALLOCREALLOC\MAIN.C
cpptools/finishUpdateSquiggles
Error squiggle count: 5
Update IntelliSense time (sec): 0.253
cpptools/getSemanticTokens: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 10)
cpptools/getFoldingRanges: file:///c%3A/Users/Jan/Dropbox/_Coding/UdemyC/Chapter8_PointerArrays/CallocRealloc/Main.c (id: 11)

**Comment by Joshua-Jurgensmeier** [comment]
I just started getting this same error today, except with clang not gcc. After looking into it for a little while, it seems that the problem is with passing "nul" as the input to the compiler. The workaround in #2863 doesn't work for me, as my Null service is running. @franneck94 Do you get this same output when running these commands in cmd?

`C:\WINDOWS\system32>"C:/cygwin64/bin/gcc.exe" -x c++ -E -dM nul
gcc: error: nul: No such file or directory
gcc: fatal error: no input files
compilation terminated.

C:\WINDOWS\system32>"C:/cygwin64/bin/clang-8.exe" -x c++ -E -dM nul
clang-8: error: no such file or directory: 'nul'
clang-8: error: no input files

C:\WINDOWS\system32>echo hi > in.txt

C:\WINDOWS\system32>"C:/cygwin64/bin/clang-8.exe" -x c++ -E -dM in.txt
#define _GNU_SOURCE 1
#define _LP64 1
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_CONSUME 1
#define __ATOMIC_RELAXED 0
#define __ATOMIC_RELEASE 3
#define __ATOMIC_SEQ_CST 5
#define __BIGGEST_ALIGNMENT__ 16
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __CHAR16_TYPE__ unsigned short
#define __CHAR32_TYPE__ unsigned int
#define __CHAR_BIT__ 8
#define __CLANG_ATOMIC_BOOL_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR_LOCK_FREE 2
#define __CLANG_ATOMIC_INT_LOCK_FREE 2
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 2
#define __CLANG_ATOMIC_LONG_LOCK_FREE 2
#define __CLANG_ATOMIC_POINTER_LOCK_FREE 2
#define __CLANG_ATOMIC_SHORT_LOCK_FREE 2
#define __CLANG_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __CONSTANT_CFSTRINGS__ 1
#define __CYGWIN64__ 1
#define __CYGWIN__ 1
#define __DBL_DECIMAL_DIG__ 17
#define __DBL_DENORM_MIN__ 4.9406564584124654e-324
#define __DBL_DIG__ 15
#define __DBL_EPSILON__ 2.2204460492503131e-16
#define __DBL_HAS_DENORM__ 1
#define __DBL_HAS_INFINITY__ 1
#define __DBL_HAS_QUIET_NAN__ 1
#define __DBL_MANT_DIG__ 53
#define __DBL_MAX_10_EXP__ 308
#define __DBL_MAX_EXP__ 1024
#define __DBL_MAX__ 1.7976931348623157e+308
#define __DBL_MIN_10_EXP__ (-307)
#define __DBL_MIN_EXP__ (-1021)
#define __DBL_MIN__ 2.2250738585072014e-308
#define __DECIMAL_DIG__ __LDBL_DECIMAL_DIG__
#define __DEPRECATED 1
#define __EXCEPTIONS 1
#define __FINITE_MATH_ONLY__ 0
#define __FLT16_DECIMAL_DIG__ 5
#define __FLT16_DENORM_MIN__ 5.9604644775390625e-8F16
#define __FLT16_DIG__ 3
#define __FLT16_EPSILON__ 9.765625e-4F16
#define __FLT16_HAS_DENORM__ 1
#define __FLT16_HAS_INFINITY__ 1
#define __FLT16_HAS_QUIET_NAN__ 1
#define __FLT16_MANT_DIG__ 11
#define __FLT16_MAX_10_EXP__ 4
#define __FLT16_MAX_EXP__ 15
#define __FLT16_MAX__ 6.5504e+4F16
#define __FLT16_MIN_10_EXP__ (-13)
#define __FLT16_MIN_EXP__ (-14)
#define __FLT16_MIN__ 6.103515625e-5F16
#define __FLT_DECIMAL_DIG__ 9
#define __FLT_DENORM_MIN__ 1.40129846e-45F
#define __FLT_DIG__ 6
#define __FLT_EPSILON__ 1.19209290e-7F
#define __FLT_EVAL_METHOD__ 0
#define __FLT_HAS_DENORM__ 1
#define __FLT_HAS_INFINITY__ 1
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MANT_DIG__ 24
#define __FLT_MAX_10_EXP__ 38
#define __FLT_MAX_EXP__ 128
#define __FLT_MAX__ 3.40282347e+38F
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MIN_EXP__ (-125)
#define __FLT_MIN__ 1.17549435e-38F
#define __FLT_RADIX__ 2
#define __FXSR__ 1
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
#define __GLIBCXX_BITSIZE_INT_N_0 128
#define __GLIBCXX_TYPE_INT_N_0 __int128
#define __GNUC_GNU_INLINE__ 1
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC__ 4
#define __GNUG__ 4
#define __GXX_ABI_VERSION 1002
#define __GXX_EXPERIMENTAL_CXX0X__ 1
#define __GXX_RTTI 1
#define __GXX_WEAK__ 1
#define __INT16_C_SUFFIX__
#define __INT16_FMTd__ "hd"
#define __INT16_FMTi__ "hi"
#define __INT16_MAX__ 32767
#define __INT16_TYPE__ short
#define __INT32_C_SUFFIX__
#define __INT32_FMTd__ "d"
#define __INT32_FMTi__ "i"
#define __INT32_MAX__ 2147483647
#define __INT32_TYPE__ int
#define __INT64_C_SUFFIX__ L
#define __INT64_FMTd__ "ld"
#define __INT64_FMTi__ "li"
#define __INT64_MAX__ 9223372036854775807L
#define __INT64_TYPE__ long int
#define __INT8_C_SUFFIX__
#define __INT8_FMTd__ "hhd"
#define __INT8_FMTi__ "hhi"
#define __INT8_MAX__ 127
#define __INT8_TYPE__ signed char
#define __INTMAX_C_SUFFIX__ L
#define __INTMAX_FMTd__ "ld"
#define __INTMAX_FMTi__ "li"
#define __INTMAX_MAX__ 9223372036854775807L
#define __INTMAX_TYPE__ long int
#define __INTMAX_WIDTH__ 64
#define __INTPTR_FMTd__ "ld"
#define __INTPTR_FMTi__ "li"
#define __INTPTR_MAX__ 9223372036854775807L
#define __INTPTR_TYPE__ long int
#define __INTPTR_WIDTH__ 64
#define __INT_FAST16_FMTd__ "hd"
#define __INT_FAST16_FMTi__ "hi"
#define __INT_FAST16_MAX__ 32767
#define __INT_FAST16_TYPE__ short
#define __INT_FAST32_FMTd__ "d"
#define __INT_FAST32_FMTi__ "i"
#define __INT_FAST32_MAX__ 2147483647
#define __INT_FAST32_TYPE__ int
#define __INT_FAST64_FMTd__ "ld"
#define __INT_FAST64_FMTi__ "li"
#define __INT_FAST64_MAX__ 9223372036854775807L
#define __INT_FAST64_TYPE__ long int
#define __INT_FAST8_FMTd__ "hhd"
#define __INT_FAST8_FMTi__ "hhi"
#define __INT_FAST8_MAX__ 127
#define __INT_FAST8_TYPE__ signed char
#define __INT_LEAST16_FMTd__ "hd"
#define __INT_LEAST16_FMTi__ "hi"
#define __INT_LEAST16_MAX__ 32767
#define __INT_LEAST16_TYPE__ short
#define __INT_LEAST32_FMTd__ "d"
#define __INT_LEAST32_FMTi__ "i"
#define __INT_LEAST32_MAX__ 2147483647
#define __INT_LEAST32_TYPE__ int
#define __INT_LEAST64_FMTd__ "ld"
#define __INT_LEAST64_FMTi__ "li"
#define __INT_LEAST64_MAX__ 9223372036854775807L
#define __INT_LEAST64_TYPE__ long int
#define __INT_LEAST8_FMTd__ "hhd"
#define __INT_LEAST8_FMTi__ "hhi"
#define __INT_LEAST8_MAX__ 127
#define __INT_LEAST8_TYPE__ signed char
#define __INT_MAX__ 2147483647
#define __LDBL_DECIMAL_DIG__ 21
#define __LDBL_DENORM_MIN__ 3.64519953188247460253e-4951L
#define __LDBL_DIG__ 18
#define __LDBL_EPSILON__ 1.08420217248550443401e-19L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __LDBL_MANT_DIG__ 64
#define __LDBL_MAX_10_EXP__ 4932
#define __LDBL_MAX_EXP__ 16384
#define __LDBL_MAX__ 1.18973149535723176502e+4932L
#define __LDBL_MIN_10_EXP__ (-4931)
#define __LDBL_MIN_EXP__ (-16381)
#define __LDBL_MIN__ 3.36210314311209350626e-4932L
#define __LITTLE_ENDIAN__ 1
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __LONG_MAX__ 9223372036854775807L
#define __LP64__ 1
#define __MMX__ 1
#define __NO_INLINE__ 1
#define __NO_MATH_INLINES 1
#define __OBJC_BOOL_IS_BOOL 0
#define __OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES 3
#define __OPENCL_MEMORY_SCOPE_DEVICE 2
#define __OPENCL_MEMORY_SCOPE_SUB_GROUP 4
#define __OPENCL_MEMORY_SCOPE_WORK_GROUP 1
#define __OPENCL_MEMORY_SCOPE_WORK_ITEM 0
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
#define __PIC__ 2
#define __POINTER_WIDTH__ 64
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __PTRDIFF_FMTd__ "ld"
#define __PTRDIFF_FMTi__ "li"
#define __PTRDIFF_MAX__ 9223372036854775807L
#define __PTRDIFF_TYPE__ long int
#define __PTRDIFF_WIDTH__ 64
#define __REGISTER_PREFIX__
#define __SCHAR_MAX__ 127
#define __SEH__ 1
#define __SHRT_MAX__ 32767
#define __SIG_ATOMIC_MAX__ 2147483647
#define __SIG_ATOMIC_WIDTH__ 32
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_INT128__ 16
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG_DOUBLE__ 16
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_LONG__ 8
#define __SIZEOF_POINTER__ 8
#define __SIZEOF_PTRDIFF_T__ 8
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_SIZE_T__ 8
#define __SIZEOF_WCHAR_T__ 2
#define __SIZEOF_WINT_T__ 4
#define __SIZE_FMTX__ "lX"
#define __SIZE_FMTo__ "lo"
#define __SIZE_FMTu__ "lu"
#define __SIZE_FMTx__ "lx"
#define __SIZE_MAX__ 18446744073709551615UL
#define __SIZE_TYPE__ long unsigned int
#define __SIZE_WIDTH__ 64
#define __SSE2_MATH__ 1
#define __SSE2__ 1
#define __SSE_MATH__ 1
#define __SSE__ 1
#define __STDCPP_DEFAULT_NEW_ALIGNMENT__ 16UL
#define __STDC_HOSTED__ 1
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC__ 1
#define __UINT16_C_SUFFIX__
#define __UINT16_FMTX__ "hX"
#define __UINT16_FMTo__ "ho"
#define __UINT16_FMTu__ "hu"
#define __UINT16_FMTx__ "hx"
#define __UINT16_MAX__ 65535
#define __UINT16_TYPE__ unsigned short
#define __UINT32_C_SUFFIX__ U
#define __UINT32_FMTX__ "X"
#define __UINT32_FMTo__ "o"
#define __UINT32_FMTu__ "u"
#define __UINT32_FMTx__ "x"
#define __UINT32_MAX__ 4294967295U
#define __UINT32_TYPE__ unsigned int
#define __UINT64_C_SUFFIX__ UL
#define __UINT64_FMTX__ "lX"
#define __UINT64_FMTo__ "lo"
#define __UINT64_FMTu__ "lu"
#define __UINT64_FMTx__ "lx"
#define __UINT64_MAX__ 18446744073709551615UL
#define __UINT64_TYPE__ long unsigned int
#define __UINT8_C_SUFFIX__
#define __UINT8_FMTX__ "hhX"
#define __UINT8_FMTo__ "hho"
#define __UINT8_FMTu__ "hhu"
#define __UINT8_FMTx__ "hhx"
#define __UINT8_MAX__ 255
#define __UINT8_TYPE__ unsigned char
#define __UINTMAX_C_SUFFIX__ UL
#define __UINTMAX_FMTX__ "lX"
#define __UINTMAX_FMTo__ "lo"
#define __UINTMAX_FMTu__ "lu"
#define __UINTMAX_FMTx__ "lx"
#define __UINTMAX_MAX__ 18446744073709551615UL
#define __UINTMAX_TYPE__ long unsigned int
#define __UINTMAX_WIDTH__ 64
#define __UINTPTR_FMTX__ "lX"
#define __UINTPTR_FMTo__ "lo"
#define __UINTPTR_FMTu__ "lu"
#define __UINTPTR_FMTx__ "lx"
#define __UINTPTR_MAX__ 18446744073709551615UL
#define __UINTPTR_TYPE__ long unsigned int
#define __UINTPTR_WIDTH__ 64
#define __UINT_FAST16_FMTX__ "hX"
#define __UINT_FAST16_FMTo__ "ho"
#define __UINT_FAST16_FMTu__ "hu"
#define __UINT_FAST16_FMTx__ "hx"
#define __UINT_FAST16_MAX__ 65535
#define __UINT_FAST16_TYPE__ unsigned short
#define __UINT_FAST32_FMTX__ "X"
#define __UINT_FAST32_FMTo__ "o"
#define __UINT_FAST32_FMTu__ "u"
#define __UINT_FAST32_FMTx__ "x"
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_FAST32_TYPE__ unsigned int
#define __UINT_FAST64_FMTX__ "lX"
#define __UINT_FAST64_FMTo__ "lo"
#define __UINT_FAST64_FMTu__ "lu"
#define __UINT_FAST64_FMTx__ "lx"
#define __UINT_FAST64_MAX__ 18446744073709551615UL
#define __UINT_FAST64_TYPE__ long unsigned int
#define __UINT_FAST8_FMTX__ "hhX"
#define __UINT_FAST8_FMTo__ "hho"
#define __UINT_FAST8_FMTu__ "hhu"
#define __UINT_FAST8_FMTx__ "hhx"
#define __UINT_FAST8_MAX__ 255
#define __UINT_FAST8_TYPE__ unsigned char
#define __UINT_LEAST16_FMTX__ "hX"
#define __UINT_LEAST16_FMTo__ "ho"
#define __UINT_LEAST16_FMTu__ "hu"
#define __UINT_LEAST16_FMTx__ "hx"
#define __UINT_LEAST16_MAX__ 65535
#define __UINT_LEAST16_TYPE__ unsigned short
#define __UINT_LEAST32_FMTX__ "X"
#define __UINT_LEAST32_FMTo__ "o"
#define __UINT_LEAST32_FMTu__ "u"
#define __UINT_LEAST32_FMTx__ "x"
#define __UINT_LEAST32_MAX__ 4294967295U
#define __UINT_LEAST32_TYPE__ unsigned int
#define __UINT_LEAST64_FMTX__ "lX"
#define __UINT_LEAST64_FMTo__ "lo"
#define __UINT_LEAST64_FMTu__ "lu"
#define __UINT_LEAST64_FMTx__ "lx"
#define __UINT_LEAST64_MAX__ 18446744073709551615UL
#define __UINT_LEAST64_TYPE__ long unsigned int
#define __UINT_LEAST8_FMTX__ "hhX"
#define __UINT_LEAST8_FMTo__ "hho"
#define __UINT_LEAST8_FMTu__ "hhu"
#define __UINT_LEAST8_FMTx__ "hhx"
#define __UINT_LEAST8_MAX__ 255
#define __UINT_LEAST8_TYPE__ unsigned char
#define __USER_LABEL_PREFIX__
#define __VERSION__ "4.2.1 Compatible Clang 8.0.1 (tags/RELEASE_801/final)"
#define __WCHAR_MAX__ 65535
#define __WCHAR_TYPE__ unsigned short
#define __WCHAR_UNSIGNED__ 1
#define __WCHAR_WIDTH__ 16
#define __WINT_MAX__ 2147483647
#define __WINT_TYPE__ int
#define __WINT_WIDTH__ 32
#define __amd64 1
#define __amd64__ 1
#define __cdecl __attribute__((__cdecl__))
#define __clang__ 1
#define __clang_major__ 8
#define __clang_minor__ 0
#define __clang_patchlevel__ 1
#define __clang_version__ "8.0.1 (tags/RELEASE_801/final)"
#define __code_model_small_ 1
#define __cplusplus 201402L
#define __cpp_aggregate_nsdmi 201304L
#define __cpp_alias_templates 200704L
#define __cpp_attributes 200809L
#define __cpp_binary_literals 201304L
#define __cpp_constexpr 201304L
#define __cpp_decltype 200707L
#define __cpp_decltype_auto 201304L
#define __cpp_delegating_constructors 200604L
#define __cpp_digit_separators 201309L
#define __cpp_exceptions 199711L
#define __cpp_generic_lambdas 201304L
#define __cpp_impl_destroying_delete 201806L
#define __cpp_inheriting_constructors 201511L
#define __cpp_init_captures 201304L
#define __cpp_initializer_lists 200806L
#define __cpp_lambdas 200907L
#define __cpp_nsdmi 200809L
#define __cpp_range_based_for 200907
#define __cpp_raw_strings 200710L
#define __cpp_ref_qualifiers 200710L
#define __cpp_return_type_deduction 201304L
#define __cpp_rtti 199711L
#define __cpp_rvalue_references 200610L
#define __cpp_static_assert 200410
#define __cpp_threadsafe_static_init 200806L
#define __cpp_unicode_characters 200704L
#define __cpp_unicode_literals 200710L
#define __cpp_user_defined_literals 200809L
#define __cpp_variable_templates 201304L
#define __cpp_variadic_templates 200704L
#define __declspec(a) __attribute__((a))
#define __fastcall __attribute__((__fastcall__))
#define __k8 1
#define __k8__ 1
#define __llvm__ 1
#define __pascal __attribute__((__pascal__))
#define __pic__ 2
#define __private_extern__ extern
#define __stdcall __attribute__((__stdcall__))
#define __thiscall __attribute__((__thiscall__))
#define __tune_k8__ 1
#define __unix 1
#define __unix__ 1
#define __x86_64 1
#define __x86_64__ 1
#define _cdecl __attribute__((__cdecl__))
#define _fastcall __attribute__((__fastcall__))
#define _pascal __attribute__((__pascal__))
#define _stdcall __attribute__((__stdcall__))
#define _thiscall __attribute__((__thiscall__))
#define unix 1

C:\WINDOWS\system32>`

**Comment by Colengms** [comment]
Thanks @franneck94 and @Joshua-Jurgensmeier  .  Indeed, the issue is due to a bug in the fallback logic to try "/dev/null" instead of "nul".  We have a fix in the works, and are looking at releasing 1.2.1 early next week.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.1
