### ISSUE TITLE
Configurations for custom language based on C

### ISSUE THREAD

**Issue by julinha85** [microsoft/vscode-cpptools#6926]
Is it possible to add or change IntelliSense for C to make it work for a **custom language **that's been **developed based on C**? In my language, several macros are defined and functions have a different semantic. The code can be pre-compiled to get C code and I also have a library for this programming language.

What I'd like to have:
* New key words are recognized and replaced by what they stand for (e.g. brackets or comment start/end or something similar (some times conditional)) - instead of seen as errors. Might this work as snippets? Is it possible to add own snippets?
* Get to the definition/declaration (ctrl+click) in actual code and not in pre-compiled c code.
Right now, I get to the corresponding C file instead of my own file (other file extension).

Of course, I could implement my own extension, but as most parts are plain C or very similar, it would be great to have this extension as baseline.

PS: The template does not fit to my question, but I followed a link to this page to place a question.

**Comment by michelleangela** [comment]
The IntelliSense engine that the C++ extension is closed source and cannot be customized for a custom language that is based on C. The IntelliSense engine will usually get updates for new features of C++ or C standard language, but not custom languages.

**Comment by sean-mcmanus** [comment]
FYI, other companies have used the EDG front-end compiler (see https://www.edg.com/customers) to implement custom C/C++ language extensions, but it's a paid/licensed product (not open source). It's possible they might allow you to push language changes so that our parser is able to be configured to understand those via flags like "--enable-special-extensions" (or compile time defines in the source code). See https://github.com/microsoft/vscode-cpptools/blob/main/Extension/bin/windows.msvc.x86.json , which has flags for extensions that Microsoft added to support extensions specific to the cl.exe compiler.

**Comment by julinha85** [comment]
Thank you for your hints!
