### ISSUE TITLE
slash direction in relative include paths (MSVC intelliSenseMode on Linux)

### ISSUE THREAD

**Issue by fiendish** [microsoft/vscode-cpptools#696]
MSVC accepts both `"..\..\foo.h"` and `"../../foo.h"` as valid include paths.

But vscode only accepts the second format. For compatibility, please make it also accept the first format for finding includes.

**Comment by bobbrow** [comment]
Hmm... both ways work for me on Windows. Are you expecting this to work on Linux/Mac?

**Comment by fiendish** [comment]
Yes, Linux. A weird request, I know, but it breaks intellisense.

**Comment by bobbrow** [comment]
Since this isn't supported right now, you will need to add the `"intelliSenseEngine": "Tag Parser"` setting in your settings.json file to revert back to the original "fuzzy" IntelliSense behavior.

We are considering adding the MSVC IntelliSense mode for Linux/Mac at some future date, but unfortunately if you want to use the new IntelliSense engine on Linux/Mac now, you'll probably have to switch your slashes.  Fortunately, both MSVC and Clang support forward slashes for includes, so this wouldn't break anyone sharing the code on Windows.

**Comment by fiendish** [comment]
Upvotes? Is github reddit now? Is it common for the actions bot to close things that have already been assigned?

**Comment by sean-mcmanus** [comment]
@Colengms Any idea why this was assigned to you a year ago?

**Comment by Colengms** [comment]
We sometimes assigned things in triage for the purpose of further investigating, or validating against the latest version of the extension when we suspect an issue may already have been addressed, etc..  We also assign things when waiting for responses from the user (we now have a bot that will ping the assignee to get back to the user, if we missed their response).  Assignment doesn't necessarily mean assigned to fix.

That said, I don't think there is anything new regarding this issue.  It's by-design, in that backslash separators are not valid on Mac and Linux.  Since forward slash separaters are valids on all platforms, that is generally what most cross-platform projects use.  However, we'll leave this issue in Traige (closed Feature Requests will get re-opened if enough people vote for them, and re-considered).

**Comment by bobbrow** [comment]
We could investigate this as part of #1083 which is potentially scheduled for 1.2.0.

I think what we're calling "upvotes" may be more correctly referred to as "reactions" on GitHub.  Perhaps we should update the bot to say it needs more `:+1: reactions` (assuming it will support writing markdown)
