### ISSUE TITLE
Cannot expand macros defined in commpile_commands.json properly

### ISSUE THREAD

**Issue by AlexHYF** [microsoft/vscode-cpptools#6971]
Type: Debugger

**Describe the bug**
- OS and Version: macOS 11.2.1 (host) Ubuntu 20.04 (remote)
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.0
- The macros are not properly expand. The macros is defined in compile_commands.json as "-DBIN_PATH=\\"/usr/local/bin\\"", however when expanded by the extension, it omitted the quotation marks thus making wrong complaints. 
<img width="555" alt="Screen Shot 2021-02-16 at 12 08 15 AM" src="https://user-images.githubusercontent.com/24642991/107969787-34470780-6feb-11eb-955d-b95c305d1fe9.png">
- Related code in compile_commands.json
<img width="351" alt="Screen Shot 2021-02-16 at 12 12 52 AM" src="https://user-images.githubusercontent.com/24642991/107970202-c818d380-6feb-11eb-9e93-e4911ab131ff.png">

**Comment by Colengms** [comment]
Hi @AlexHYF .  I believe what you are seeing is by design.  When running the following command:

```
gcc -x c++ -E -dM -DAFL_PATH="/usr/local/lib/afl" /dev/null | grep AFL_PATH
```

The result is: 

```
#define AFL_PATH /usr/local/lib/afl
```

Passing a define compiler arg with a single set of unescaped quotes does not add the quotes to the define.

The JSON format requires that quotes are escaped (as they are within quoted strings), which actually results in the content being interpreted as unescaped quotes.  If you want to specify that JSON content contains escaped quotes, it's necessary to escape them twice:

```
"-DAFL_PATH=\\\"/usr/local/lib/afl\\\""
```

That will result in passing them like so, after JSON escaping is removed:

```
gcc -x c++ -E -dM -DAFL_PATH=\"/usr/local/lib/afl\" /dev/null | grep AFL_PATH
```

Which will have the desired result:

```
#define AFL_PATH "/usr/local/lib/afl"
```

If you are using another program to generate your `compile_commands.json`, there may be a bug there.
