### ISSUE TITLE
integratedTerminal not working anymore in V 1.2.1

### ISSUE THREAD

**Issue by KochC** [microsoft/vscode-cpptools#7000]
Type: Debugger

Debugging still works, but the `integratedTerminal` is not showing up again. If opening it manually, the output is not shown from the debugger. `externalConsole` and `internalConsole` still are working.

**Describe the bug**
- Version: 1.53.2 (user setup)
- Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
- Date: 2021-02-11T11:48:04.245Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19042
- VS Code Version: 1.53.2 and 1.54.0
- C/C++ Extension Version: 1.2.1

**To Reproduce**
Checkout the code from [here](https://github.com/KochC/vscode-integratedterminal-test)
Build using `nmake` or whatever compiler you like.
Start debugging using the default debugger script in the `launch.json`

**Fix**
Downgrade to `V1.2.0` still works.
**Note:** If you downgrade, make sure you also disable the `Auto Extension Update`.

**Comment by WardenGnaw** [comment]
There were no changes to vsdbg from v1.2.0 to v1.2.1

@sean-mcmanus There may be an issue either with the downloading of packages or the release setup. 
This seems very similar to how `lldb-mi` is not working properly in https://github.com/microsoft/vscode-cpptools/issues/6989
Not seeing anything in the changelog that would affect this.

**Comment by sean-mcmanus** [comment]
I don't know either. Nothing has changed with the release setup. Are we able to repro any of these regression issues? Do we know if the issue affects only the online vsix or also the offline vsix?

**Comment by Ghabry** [comment]
I actually have the same problem but in another context:

For me the ``"console": "integratedTerminal"`` works flawless but for my students they do not see any output. They use the launch.json provided by me so this cannot be the issue. Must be something in my Windows system that causes the difference?

Does this feature depend on the Windows 10 version? Is the Windows Terminal (from the Windows Store) required?

Is currently hard to diagnose because we are all digital due to COVID but I scheduled a meeting with one of them tomorrow, maybe I can figure it out...

**Comment by bobbrow** [comment]
All files will be bundled with the VSIX starting in 1.8.0.  This should be covered by #8152
