### ISSUE TITLE
Not finding namespace members

### ISSUE THREAD

**Issue by rdlaner** [microsoft/vscode-cpptools#701]
VS Code: 1.12.1
CPP Tools: 0.11.0
OS: MacOS 10.11.6

CPP tools is continually giving me an error that both "malloc" and "free" cannot be found:
![screen shot 2017-05-08 at 12 18 45 pm](https://cloud.githubusercontent.com/assets/17415937/25821154/d7042d2e-33e8-11e7-81f8-c3d21b042f39.png)

This cpp file includes a header files which contains the following includes:
```#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <string>
```
My configuration settings are set as:

```     "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}",
                "/usr/include/c++/4.2.1",
                "/usr/local/Cellar/gcc/6.3.0_1/include/c++/6.3.0/"
            ],
            "defines": [],
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "/usr/include/c++/4.2.1",
                    "/usr/local/Cellar/gcc/6.3.0_1/include/c++/6.3.0/"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/.vscode/browse.vc.db"
            }
        },
```
I can jump to 4 separate definitions of cstdlib that are found by CPPTools, but for some reason, it still thinks malloc and free are undefined.
Any ideas?

**Comment by bobbrow** [comment]
This is certainly strange.  I don't reproduce the error on my MacBook.  Do you have any other extensions installed that might be reporting this squiggle?
* `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code --list-extensions`

![osx1](https://cloud.githubusercontent.com/assets/12818240/25874234/79722bf0-34c6-11e7-9868-2f5bca7dcf72.png)

Using the default include paths (XCode is not installed on this machine):

![osx2](https://cloud.githubusercontent.com/assets/12818240/25874236/7c880f9e-34c6-11e7-9918-966605f20e51.png)

**Comment by bobbrow** [comment]
I think you need to add `/usr/include` to your **includePath**.  I see the definition of malloc in `/usr/include/stdlib.h`.

**Comment by rdlaner** [comment]
Thanks, that seemed to do the trick. Do I also need to add "/usr/include"
to the "path" list in c_cpp_properties.json?
What exactly is the difference between "includePath" and "path"?

**Comment by bobbrow** [comment]
They are very similar, and in many cases will be identical, but have a slight difference.

**includePath** is the list of (non-recursive) include paths that your compiler would use to find header files during compilation.  (e.g. the list of paths you would send to the compiler with `-I`)

**browse.path** is the list of paths that the browse engine (the old IntelliSense engine) traverses recursively to find header files and build up a database of symbols. Symbols from header files not included by any source file can end up in the IntelliSense database.

Since it might not be desirable to recursively traverse all folders in the **includePath** and due to some implementation details of how the browse engine discovers included header files that I won't delve into here, we now have two settings.

For the **browse.path** setting, adding `/usr/include/*` might be preferable since that will tell the browse engine not to do a recursive search through *everything*.
