### ISSUE TITLE
[Feature Request] gdbgui windows as the main ui for vscode debugger for c++

### ISSUE THREAD

**Issue by WWology** [microsoft/vscode-cpptools#7041]
Gdbgui is a very useful browser-based debugger to debug c++ code. Would be very nice to get this as the default ui for vscode c++ debugger

**Comment by WardenGnaw** [comment]
gdbgui looks like it own product. In order to use the extension's debugger, they would need to support DAP for debugging.

Since they are already interacting with gdb, there is no need for them to implement support for [MIEngine ](https://github.com/microsoft/MIEngine).

This extension is focused on supporting VS Code.
