### ISSUE TITLE
Ctrl+click doesn't respect my current platform

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#7176]
I work on a Linux/MacOS project which has:

`module.h`
`module.cpp`
`moduleLinux.cpp`
`moduleMac.cpp`

In `CMakeLists.txt` the respective file is added for the respective platform. When on Linux ctrl+click, *Go to Definition* always send me to the Mac version for some reason. It would be nice if VSCode can pick the platform from CMake up and send me to (prefer) the correct definition.

**Comment by sean-mcmanus** [comment]
Go to Definition will use IntelliSense when the definition exists in the TU -- can you confirm whether or not the correct Linux definition is gone to when invoking the Go to Def in the TU that has the definition (e.g. moduleMac.cpp)? I'm assuming this would work.

My guess is that you're hitting the out-of-TU case, which we query the tag parser database for global symbols. Do the Linux and Mac versions appear to have the same signatures? Can you confirm that the Linux version doesn't appear as a result at all? Assuming that's the case, it sounds like the moduleLinux.cpp file may be hitting a tag parsing error. When you set C_Cpp.loggingLevel to "Debug" and make some edit to moduleLinux.cpp do you see some tag parsing failure message in the C/C++ logging?

Assuming you get to the point where moduleLinux.cpp is correctly parsed, then I would assume you could get results from both moduleLinux.cpp and moduleMac.cpp and it would be "by design" (or "feature request") that we wouldn't be able to exclude the Mac results, because it would require "confirming" the go to definition result with the IntelliSense parser in a similar manner to invoking Find All References (e.g. using Find All References would be the potential workaround), but that would cause an unwanted delay, which is why the VS team decided not to do that. Another potential workaround would be to somehow exclude the moduleMac.cpp file from tag parsing, such as via the files.exclude and possibly C_Cpp.exclusionPolicy settings.
