### ISSUE TITLE
Support the experimentation platform

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#7275]
We want this for our "getting started" work.

**Comment by sean-mcmanus** [comment]
What is the experimentation platform? Is it fixed by https://github.com/microsoft/vscode-cpptools/pull/7512 ?

**Comment by Colengms** [comment]
The module involved is `vscode-tas-client`.  It would be a replacement for our A/B testing approach and use of cpptools.json.  

It allows retrieval of variables from 'control tower', which can be varied based on the 'treatment' of the client (whether the client is selected for an experiment or not).  

There is a TAS-Client repo in DevOps (in DivDev) that contains some documentation.  (I don't want to link it here, since it's internal).

It was suspect that this might be required for the Getting Started walkthrough work, but experiments related to who that is enabled for are handed by VS Code and not the extension itself.  Since it's relatively simple to use, I'd like to wait until we have an experiment to run (so we have a reason to actually call into it) before doing this work.  Otherwise, referencing the module and initializing it would seem have no particular use.
