### ISSUE TITLE
Too many processes randomly spawn and crash system

### ISSUE THREAD

**Issue by UwUSnek** [microsoft/vscode-cpptools#7367]
Bug type: Language Service

**Describe the bug**
- OS and Version: Fedora 33
- VS Code Version: 1.55.2
- C/C++ Extension Version: 1.3.0
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
A lot of "cpptools-srv" processes spawn for no apparent reason, using all the memory and cpu. Most of the times I can't even kill them before they make the system crash.  
I'm using a single project opened in 2 windows (> open folder, > duplicate workspace in new window)
34k files, 1.3GB. (Most of them are not parsed)

**Steps to reproduce**

I don't know. It happens without any correlation with what i'm doing.
I can't test it because it happens quite rarely.

**Code sample and logs**
- Configurations in `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Lynx",
            "includePath": [
                "${workspaceFolder}/",
                "${workspaceFolder}/Lynx/",
                "${workspaceFolder}/Lynx/deps/Shared/GLFW/include",
                "${workspaceFolder}/Lynx/deps/Shared/GLFW/deps",
                "${workspaceFolder}/Lynx/deps/Linux/Vulkan-1.2.170.0/x86_64/include"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "${default}",
            "cppStandard": "c++20",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

```
-------- Diagnostics - 4/15/2021, 4:21:06 PM
Version: 1.3.0
Current Configuration:
{
    "name": "Lynx",
    "includePath": [
        "${workspaceFolder}/",
        "${workspaceFolder}/Lynx/",
        "${workspaceFolder}/Lynx/deps/Shared/GLFW/include",
        "${workspaceFolder}/Lynx/deps/Shared/GLFW/deps",
        "${workspaceFolder}/Lynx/deps/Linux/Vulkan-1.2.170.0/x86_64/include"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "cppStandard": "c++20",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/",
            "${workspaceFolder}/Lynx/",
            "${workspaceFolder}/Lynx/deps/Shared/GLFW/include",
            "${workspaceFolder}/Lynx/deps/Shared/GLFW/deps",
            "${workspaceFolder}/Lynx/deps/Linux/Vulkan-1.2.170.0/x86_64/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/Edo/Desktop/LuxEngine-Test/main.cpp ]:
    /home/Edo/Desktop/LuxEngine-Test/main.cpp
Translation Unit Configurations:
[ /home/Edo/Desktop/LuxEngine-Test/main.cpp ]:
    Process ID: 23764
    Memory Usage: 328 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /home/Edo/Desktop/LuxEngine-Test
        /home/Edo/Desktop/LuxEngine-Test/Lynx
        /home/Edo/Desktop/LuxEngine-Test/Lynx/deps/Shared/GLFW/include
        /home/Edo/Desktop/LuxEngine-Test/Lynx/deps/Shared/GLFW/deps
        /home/Edo/Desktop/LuxEngine-Test/Lynx/deps/Linux/Vulkan-1.2.170.0/x86_64/include
        /usr/include/c++/10
        /usr/include/c++/10/x86_64-redhat-linux
        /usr/include/c++/10/backward
        /usr/lib/gcc/x86_64-redhat-linux/10/include
        /usr/local/include
        /usr/include
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100201
Total Memory Usage: 328 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 33550
Number of files parsed: 886
```

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/47669437/114889509-78e3f900-9e0a-11eb-954e-3741d02f6d66.png)
(For some reason, the system monitor reports 0% cpu, but the cpu is always at 100% when this happens.

**Comment by michelleangela** [comment]
@Edo022 
A case when it's expected to have a lot of cpptools-srv spawn at once is when doing a "Find all references" and a lot of files are searched for a symbol's references. Though after the "Find all references" process gets completed, the temporary cpptools-srv processes should shutdown, and only the cpptools-srv for the current active open sources files on VS Code should remain running (one cpptools-srv process is created to serve one TU).

From your case, it seems like the cpptools-srv just lingers and continues to use CPU? Is this correct? Version 1.3.0 of the C++ extension has some fixes related to properly shutting down cpptools-srv, so 1.3.0 may have fixed some of the issue.

Since you say this is a rare occurrence, it would be hard to investigate without a reliability repro right now. Though I see you're using some library? If so, is it available somewhere for us to try to use and maybe we can get a local repro?

Please do keep monitoring the behavior with version 1.3.0 and let us know if the issue comes up again. You could try doing a "Find all references" on a symbol that is referenced in a lot of files and see if you can get a repro that way too.

**Comment by Edo022** [comment]
I'm using GLFW 3.3.4, Vulkan 1.2.170.0 and a small library I wrote which contains ~90 files.
https://github.com/glfw/glfw/releases/download/3.3.4/glfw-3.3.4.zip
https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.2.170.0/linux/vulkansdk-linux-x86_64-1.2.170.0.tar.gz

> From your case, it seems like the cpptools-srv just lingers and continues to use CPU? Is this correct?

Yes. The processes usually run for a few seconds and than the whole system freezes and I have to reboot. When it doesn't freeze, they keep using all the cpu until I kill them manually.

> You could try doing a "Find all references" on a symbol that is referenced in a lot of files and see if you can get a repro that way too.

Find all references has a similar behavior, but the system doesn't freeze and cpptools-srv shuts down properly.
(I tried on a symbol that is  referenced in 3k files)

**Comment by sean-mcmanus** [comment]
It sounds like the cpptools-srv process is crashing repeatedly and not getting shutdown correctly when that happens.

**Comment by ellipticaldoor** [comment]
I get the same issue

**Comment by michelleangela** [comment]
@Edo022 could you verify if this is still an issue with the latest version of C++ Extension?

**Comment by michelleangela** [comment]
@ellipticaldoor could you verify if this is still an issue with the latest version of C++ Extension?

**Comment by ellipticaldoor** [comment]
> @ellipticaldoor could you verify if this is still an issue with the latest version of C++ Extension?

sorry Im not longer using vscode

**Comment by Edo022** [comment]
It still happens, but now the processes are able to shut down and the os recovers after a few minutes.
I've noticed that this happens more often when opening files quickly from the search results.
the more files you open, the longer it takes for the processes to shut down. after 4-5 files it starts freezing again.
I tested with files of ~500 lines each

**Comment by sean-mcmanus** [comment]
@Edo022 Opening a file will trigger our cpptools-srv process to launch...so it seems like you may be experiencing normal behavior? Otherwise, can you provide more info on what you believe is abnormal behavior?

**Comment by Edo022** [comment]
I mean ... opening 4 files shouldn't freeze the entire operating system for 5 minutes, right?
As I said, this only happens when the files are opened from the search results. Opening files in other ways doesn't seem to cause freezes

**Comment by sean-mcmanus** [comment]
You may want to try setting C_Cpp.intelliSenseCacheSize to 0 in case the freeze is caused by that feature using too much disk resources.

Our extension should be doing nearly identical processing whether the file is opened from the search results or the File explorer. It sounds like the difference in behavior might be a VS Code and/or OS issue, in particular, certain Linux OS's don't behave well under resource pressure compared to other Linux OS's (or Mac/Windows). The 300-500 MB usage I see in your previous message appears "normal" with certain TUs that are large. A maxIntelliSenseThreads setting might fix the issue for you if your system can't handle > 3 at a time (similar to https://github.com/microsoft/vscode-cpptools/issues/4036).
