### ISSUE TITLE
Updating to 1.3.0 crashes cpptools on macOS

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#7374]
Bug type: General

**Describe the bug**
- OS and Version: macOS Big Sur 11.2.3
- VS Code Version: 1.55.2
- C/C++ Extension Version: 1.3.0
- Other extensions you installed (and if the issue persists after disabling them): Persists with all other extensions disabled.
- A clear and concise description of what the bug is.
Extension was automatically updated to 1.3.0, now it crashes every time I open a C file. Reverting back to 1.2.2 stops the crashes.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. Install extension latest version (1.3.0)
2. Open a C file
3. Extension immediately crashes

**Expected behavior**

The extension not to crash.

**Screenshots**

N/A

**Additional context**

Happens on every C file I open. Specifically the files i am working on for my class: https://github.com/mattwilkinsonn/operatingsystems

**Comment by michelleangela** [comment]
@mattwilkinsonn 

- Is your Mac machine an Apple Intel (64 bit) or Apple Silicon (arm64)?
- Do you have sample code or does this happen with any C file or is this specific to your code?
- Could you verify that it's the cpptools-srv process that is crashing and not cpptools?
- If you're on Apple Intel, could you try getting callstacks or a dump? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by sean-mcmanus** [comment]
Also, does this repro with .cpp files? (I assume it would, but if it really is C only that would be important to know).

@michelleangela His comment "Happens on every C file I open" suggests it's for every C file.

**Comment by mattwilkinsonn** [comment]
@michelleangela 
* Is your Mac machine an Apple Intel (64 bit) or Apple Silicon (arm64)?
Intel, 15in Macbook Pro 2018.

* Do you have sample code or does this happen with any C file or is this specific to your code?
This happens with any C file I open in the repository I linked. Here is one of the [files](https://github.com/mattwilkinsonn/operatingsystems/blob/master/a4/memory.c). If you have a different file you want me to try I can do that as well.

* Could you verify that it's the cpptools-srv process that is crashing and not cpptools?
<img width="452" alt="Screen Shot 2021-04-15 at 4 37 06 PM" src="https://user-images.githubusercontent.com/28606055/114935145-d2e3bf00-9e08-11eb-83d4-b2d6365b9245.png">
Screenshot above is what I get, seems like it is the server and the client, client might just be failing because of the server failure though.

* If you're on Apple Intel, could you try getting callstacks or a dump? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90sr

I tried to do this but it crashes instantly when I open a file, so I don't have a chance to run -> select the process in time before its already gone. Is there a way to preemptively attach it?

@sean-mcmanus 

* Also, does this repro with .cpp files? (I assume it would, but if it really is C only that would be important to know).

Renamed one of my .c files to .cpp and same error occurred. If there is a particular .cpp file you want me to open I can do that.

**Comment by michelleangela** [comment]
@mattwilkinsonn 
Sorry I missed the info and link under "Additional Context".

From the screenshot, it looks like it's failing to run the cpptools process. This could be an installation issue where the cpptools binary didn't install properly after an update. Could you try uninstalling the C++ extension and also removing any folders under the `/.vscode/extensions/` path with `ms-vscode.cpptools-*` and then re-install the extension?

**Comment by mattwilkinsonn** [comment]
> @mattwilkinsonn
> Sorry I missed the info and link under "Additional Context".
> 
> From the screenshot, it looks like it's failing to run the cpptools process. This could be an installation issue where the cpptools binary didn't install properly after an update. Could you try uninstalling the C++ extension and also removing any folders under the `/.vscode/extensions/` path with `ms-vscode.cpptools-*` and then re-install the extension?

Manually deleting the extension folder seems to have fixed the issue. Thanks!
