### ISSUE TITLE
IntelliSenseMode changing from one defined in configuration to default for current platform

### ISSUE THREAD

**Issue by PookyFan** [microsoft/vscode-cpptools#7384]
Bug type: Language Service

- OS and Version: Linux Debian 10 kernel 5.10.26 (with MuQSS)
- VS Code Version: 1.55.2
- C/C++ Extension Version: 1.3.0

**Description**
IntelliSenseMode is changing on its own to match my local compiler and architecture version, even though it's explicitly configured to use different mode for my project.
This started today, I think after yesterday's update? I haven't had this problem earlier, anyway.
I believe this is a bug, since `intelliSenseMode` config key should (and used to) allow me to change how InteliSense operates (for example to show different sizes of data types, pointers etc).

> The IntelliSense mode to use that maps to a platform and architecture variant of MSVC, gcc, or Clang. If not set or if set to ${default}, the extension will choose the default for that platform. Windows defaults to windows-msvc-x64, Linux defaults to linux-gcc-x64, and macOS defaults to macos-clang-x64. IntelliSense modes that only specify - variants (e.g. gcc-x64) are legacy modes and are converted automatically to the -- variants based on the host platform.

**Steps to reproduce**
1. In c_cpp_properties.json file, have `"intelliSenseMode": "linux-gcc-arm"` defined
2. Run VSC

**Expected behavior**
IntelliSense is working in specified mode (different from default for current architecture and OS).

**Actual behavior**
The following warning is printed:
> [4/18/2021, 12:16:13 AM] For C source files, IntelliSenseMode was changed from "linux-gcc-arm" to "linux-gcc-x64" based on compiler args and querying compilerPath: "/usr/local/bin/gcc"
> [4/18/2021, 12:16:13 AM] For C++ source files, IntelliSenseMode was changed from "linux-gcc-arm" to "linux-gcc-x64" based on compiler args and querying compilerPath: "/usr/local/bin/gcc"

IntelliSense is working in default mode (ie showing `sizeof(pointer)` == 8 instead of expected 4 for 32-bit ARM architecture).

**Configurations in `c_cpp_properties.json`:**

> {
>     "configurations": [
>         {
>             "name": "Linux",
>             "includePath": [
>                 "${workspaceFolder}/Tools/googletest/googletest/include",
>                 "${default}"
>             ],
>             "defines": [],
>             "intelliSenseMode": "linux-gcc-arm"
>         }
>     ],
>     "version": 4
> }

**Logs from running `C/C++: Log Diagnostics`:**

> -------- Diagnostics - 4/18/2021, 12:30:58 AM
> Version: 1.3.0
> Current Configuration:
> {
>     "name": "Linux",
>     "includePath": [
>         "${workspaceFolder}/Tools/googletest/googletest/include"
>     ],
>     "defines": [],
>     "intelliSenseMode": "linux-gcc-arm",
>     "macFrameworkPath": [],
>     "compilerArgs": [],
>     "cStandard": "c11",
>     "cppStandard": "c++17",
>     "intelliSenseModeIsExplicit": true,
>     "cStandardIsExplicit": true,
>     "cppStandardIsExplicit": true,
>     "compilerPathIsExplicit": false,
>     "compilerPath": "/usr/local/bin/gcc",
>     "browse": {
>         "path": [
>             "${workspaceFolder}/Tools/googletest/googletest/include",
>             "${workspaceFolder}"
>         ],
>         "limitSymbolsToIncludedHeaders": true
>     }
> }
> Translation Unit Mappings:
> ...
> Translation Unit Configurations:
> ...
> Process ID: 10966
>     Memory Usage: 141 MB
>     Compiler Path: /usr/local/bin/gcc
>     Includes:
>     ...
> Standard Version: c++17
>     IntelliSense Mode: linux-gcc-x64
>     Other Flags:
>         --g++
>         --gnu_version=100200
> Total Memory Usage: 141 MB
> 
> ------- Workspace parsing diagnostics -------
> Number of files discovered (not excluded): 6748

**Comment by sean-mcmanus** [comment]
This is "by design". We're detecting that /usr/local/bin/gcc is a compiler targetting x64 Linux. Can you switch to a compiler that is targetting arm?

**Comment by PookyFan** [comment]
@sean-mcmanus I could certainly do that. But then what's the purpose of the `intelliSenseMode` configuration key? As I understand, there is a separate key for compiler that's to be used for the project. If InteliSense mode depends solely on the compiler used, then there is no point in trying to set `intelliSenseMode`, as it's going to be overridden anyway.
My point is, this is rather counterintuitive. There is no mention in `intelliSenseMode` description or in the documentation that it works this way.

**Comment by sean-mcmanus** [comment]
Changes have been made over time to change the behavior such that the compilerPath querying takes precedence over the intelliSenseMode, because people frequently have the wrong intelliSenseMode set which can lead to more problems if the wrong compilerPath is used because then you'd be in a mismatched state with system defines/includes being used for a different mode. By making the compilerPath determine the intelliSenseMode (when possible) then it's at least in a consistent mode.

There were some changes made with 1.3.0 in regards to Mac arm, so this might have changed from that.

@Colengms or @michelleangela might know more.

**Comment by michelleangela** [comment]
Yes this is by design to correct the IntelliSenseMode based on the #defines found from querying the compilerPath. Since it is assumed the compilerPath is set to the compiler that will be used to compile the code with, so if querying the compilerPath is successfully, the extension will base the IntelliSenseMode from that. If the compiler is used for cross-compiling, then the extension uses any compiler args that specifies the target architecture/platform to query the compiler and determine the IntelliSenseMode.

In the case when compilerPath is set to `""` then no compiler is queried and IntelliSense configuration is based on the values from the other set properties in c_cpp_properties.json.

There is this documentation for cross-compiling https://code.visualstudio.com/docs/cpp/configure-intellisense-crosscompilation. It may need updating though.
