### ISSUE TITLE
& signs are not correctly colored as reference signs in certain cases

### ISSUE THREAD

**Issue by yaoxinliu** [microsoft/vscode-cpptools#7387]
See also: [How to make the & sign blue if it is a reference sign?](https://stackoverflow.com/questions/67157739/how-to-make-the-sign-blue-if-it-is-a-reference-sign)

```
template<typename T>
void f(T const&& n1, T const& n2)
{
    T&& x1 = static_cast<T&&>(n1);
    T&  x2 = static_cast<T&>(n2);
}
```

The snapshot is from Visual Studio Code with C/C++ extensions. All are the latest versions as of 2021/04/19.

**Problems**

_1. In T&& n1 and T& n2, & signs are blue._

_2. In T&& x1 and T& x2, & signs are white._

_3. In <T&&> and <T&>, & signs are white._

**Questions**

_1. How to make the & sign blue if it is a reference sign?_

_2. Is it possible via modifying one of the following?_

> _editor.semanticTokenColorCustomizations_

> _editor.tokenColorCustomizations_

> _cpp.tmLanguage.json_

**Comment by sean-mcmanus** [comment]
Our extension doesn't provide colorization for && and &. It's coming from VS Code itself, which gets its behavior from https://github.com/jeff-hykin/cpp-textmate-grammar/issues  (so you should file an issue there).

You can simplify your repro with
```
void f(int const&& n1, int const& n2)
{
    int&& x1 = const_cast<int&&>(n1);
    int&  x2 = const_cast<int&>(n2);
}
```

The white &/&& are getting treated as keyword.operator.logical.cpp instead of storage.modifier.reference.cpp.

If you don't mind all your operators turning blue you could change the editor.tokenColorCustomizations for keyword.operator.logical.cpp to be blue.
