### ISSUE TITLE
Configuration warning message incorrectly appears when intelliSenseMode is set but compile_commands.json is used

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7390]
Use c_cpp_properties.json
```
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "linux-gcc-x86",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
```
with some compile_commands.json like
```
[
    {
     "directory": "<pathToTest>", 
     "arguments": [
      "C:\\msys64\\mingw64\\bin\\gcc.exe"
     ], 
     "file": "test.cpp"
    }
   ]
```

It incorrectly shows [4/19/2021, 12:57:09 PM] For C source files, IntelliSenseMode was changed from "linux-gcc-x86" to "linux-clang-x86" based on compiler args and querying compilerPath: "C:\Program Files\LLVM\bin\clang.exe"
[4/19/2021, 12:57:11 PM] For C++ source files, IntelliSenseMode was changed from "linux-gcc-x86" to "linux-clang-x86" based on compiler args and querying compilerPath: "C:\Program Files\LLVM\bin\clang.exe"

even though the compiler path from compile_commands is actually being used.

**Comment by Colengms** [comment]
@sean-mcmanus I'm not sure if this is a bug.  The same occurs when using a `configurationProvider` instead of `compileCommands`.  The base configuration can still be evaluated, as it will be used for files that are not referred to in `compile_commands.json` or files that the config provider does not handle.

The compiler query for the base configuration appears to be triggered early, as a result of: canonicalize -> support_case_sensitive_files -> is_wsl .  The decision about whether to consider the configuration to be WSL or not appears to be based on the result of resolving the base configuration.  If we didn't need to resolve the base configuration until it was actually needed, the configuration warnings would only appear when they are actually relevant.  (My vote is that we fix this by removing our old WSL support).

**Comment by sean-mcmanus** [comment]
Oh, I agree, I wasn't thinking about that scenario. I'm just going to close this, i.e. my vote is to do nothing, but feel free to remove the old WSL support if you want (might want to ask @bobbrow first).

**Comment by sean-mcmanus** [comment]
@Colengms I think removing the old WSL support would be good if it was done in conjunction with https://github.com/microsoft/vscode-cpptools/issues/1994, which has lots of upvotes.
