### ISSUE TITLE
intellisense C++ and #pragma GCC optimize

### ISSUE THREAD

**Issue by DomiKoPL** [microsoft/vscode-cpptools#7403]
So the C++ intellisense Extension isn't working, when I add to my code 

#pragma GCC optimize("O3")

I have to reset VSC to make it work again.

**Comment by Colengms** [comment]
Hi @DomiKoPL .  Are you referring specifically to the "C++ Intellisense" extension?  That is not provided by Microsoft, and it's repo is here: https://github.com/austin-----/code-gnu-global

This repro is for the "C/C++" VS Code extension, which is provided by Microsoft.  If your issue is with the "C/C++" extension, could you provide more detail on the behavior you are seeing, as well as the information requested in the new issue template?

**Comment by DomiKoPL** [comment]
Thank you.

śr., 21 kwi 2021 o 23:28 Colen Garoutte-Carson ***@***.***>
napisał(a):
