### ISSUE TITLE
Latest version can no longer find symbols correctly

### ISSUE THREAD

**Issue by byggwir** [microsoft/vscode-cpptools#743]
Maybe this is related to  #741 with the difference that it does not mark the header file but it marks the symbol to be unknown (running on Windows 8.1).

![2017-05-20 15_56_05-variable](https://cloud.githubusercontent.com/assets/5053598/26276312/2b2d2280-3d75-11e7-89a6-2a6a9f9b7e77.jpg)

At the top of the file it reads:
`#include <Arduino.h>`

But pressing F12 jumps to the correct definition of Serial.
I am using the following settings:
![settings](https://cloud.githubusercontent.com/assets/5053598/26276325/7074ba42-3d75-11e7-922e-32ac56b6f7f3.jpg)

This happened after installing the update and pressing reload for loading. Then the symbol was marked unknown.
A second pc without the update showed it correctly. I tested it on that one as well and after installing the update and reloading it showed the unknown tag on the symbol. (no other changes were made)

**Comment by bobbrow** [comment]
I took a look in the HardwareSerial.h header file and saw this:

```
#if defined(UBRRH) || defined(UBRR0H)
  extern HardwareSerial Serial;
  #define HAVE_HWSERIAL0
#endif
```

It looks like you'll need to add "UBRRH" or "UBRR0H" to the `"defines"` array in your c_cpp_properties.json to get this symbol defined.

I went ahead and downloaded the Arduino SDK and played around with it for a bit.  Try updating your c_cpp_properties.json to look like this:

```json
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "C:/Program Files (x86)/Arduino/hardware/arduino/avr/cores/arduino",
                "C:/Program Files (x86)/Arduino/hardware/tools/avr/avr/include",
                "C:/Program Files (x86)/Arduino/hardware/tools/avr/lib/gcc/avr/4.9.2/include"
            ],
            "defines": ["UBRRH"],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "",
                "path": [
                    "C:/Program Files (x86)/Arduino"
                ]
            }
        }
```

After setting it this way, the header files I opened had no more red underlines (except for `__attribute__` stuff which won't work because the IntelliSense engine is defaulting to Microsoft mode instead of clang mode on Windows).  There are likely other include paths and defines that will need to be set for your project, but this is how I got it to work for the code snippet you shared in your issue.

Just a note: The browse.path is recursive, so I set it to the root of the SDK.  That way if you find any red underlines for header files or symbols/types, you can use goto definition to search for them using the browse engine (tag parser) which is still responsible for the goto definition feature. This will allow you to easily discover what additional include paths need to be added to your project.

**Comment by ThatJCB** [comment]
See the issue reported in VSCode.
[https://github.com/Microsoft/vscode/issues/27006](https://github.com/Microsoft/vscode/issues/27006)

**Comment by ThatJCB** [comment]
**I can work round the issue by changing the setting in C/C++ for Intellisense from 'Default' to 'Tag Parser'. The 'Tag Parser' appears to correctly recognise the libraries.**

![Screenshot of settings](https://2.bp.blogspot.com/-9nTbiIEGJSE/WSB_zJAVy6I/AAAAAAABCpc/KqNqMnNg1ogk-rCtnus-Wz6uPWya8RutwCEw/s1600/TagParserIntellisenseEngine2017-05a.png)

The notes about the include path and browse path in the FAQ's is a useful read:
[https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md)

It was the upgrade to VSCode 1.12.2 that triggered the problem so it is unclear where the issue needs to be fixed. Someone who knows how the code is structured will have to decide that.

There are a couple more screenshots at the very end of one of my blog posts:
[http://blog.discoverthat.co.uk/2017/04/installing-visual-studio-code-for.html](http://blog.discoverthat.co.uk/2017/04/installing-visual-studio-code-for.html)

**Comment by jniemann66** [comment]
Hello, 
Not sure if this is related, but ...
I have noticed that the inability to follow symbols appears to be related to not tracking #include guards properly. Specifically, it is ignoring #include directives within the #ifndef ... #endif block:
eg:

~~~
#ifndef _SOME_HEADER_H
#define _SOME_HEADER_H 1

include <string>
std::string s; // namespace "std" has no member "string" (red squiggle)

#endif  // _SOME_HEADER_H 
~~~

Strangely, if you change #ifndef _SOME_HEADER_H to **#ifdef** _SOME_HEADER_H, it works ok.

*the workaround for changing the intellisense engine to "tag parser" mentioned by @ThatJCB works well for the time being. (Alternatively, you can disable red squiggles with "C_Cpp.errorSquiggles": "Disabled")*

**Comment by ThatJCB** [comment]
See all of the following, they look like the same error to me:
[https://github.com/Microsoft/vscode-cpptools/issues/741](https://github.com/Microsoft/vscode-cpptools/issues/741)
[https://github.com/Microsoft/vscode-cpptools/issues/728](https://github.com/Microsoft/vscode-cpptools/issues/728)

**Comment by jiujieti** [comment]
@ThatJCB thanks for your workaround, my problem is solved

**Comment by byggwir** [comment]
@ThatJCB Currently I am going for that workaround although I don't understand the implications.
@bobbrow I don't really like that solution to set some define as neither of the defines is used for compiling. Serial is defined in CDC.cpp. And pressing F12 jumps there. So for now the issue is somewhat solved. still having issues with the includes being squiggled.

**Comment by byggwir** [comment]
Didn't want to close. I am not used to github. sorry

**Comment by donfiguerres** [comment]
I had a similar problem which seems to have started from the last update. The "Go to Definition" and "Peek Definition" functionalities have stopped working. Click and hover over the symbol also does not show the symbol definition. 

![image](https://cloud.githubusercontent.com/assets/12525903/26291068/5f7f6736-3ede-11e7-8049-67a1b7d10117.png)

**Comment by FMLS** [comment]
I want to install the old version release， I think it's a critical bug!

**Comment by ThatJCB** [comment]
@FMLS, try the work round I posted above. It's been working fine for me and is probably easier than installing an older version. In addition you'll still get other fixes.

**Comment by FMLS** [comment]
@ThatJCB  thanks. I want to know Whether this config will bring unpredictable behavior. hoping offical fix

**Comment by bobbrow** [comment]
@byggwir, sorry, my unfamiliarity with Arduino shows with the suggestion of adding UBRRH to the `defines`.  After digging a little further, I see two possible avenues to get Serial defined.  One is via HardwareSerial.h and the other via USBAPI.h.

With HardwareSerial.h, it seems you need to include a register definition file to get UBRRH defined.  I added `#include <avr/iom161.h>` (not sure which would be the right one for you, if any) to my test file above the `#include <arduino.h>` line and then Serial was defined in my test.

To use USBAPI.h, it seems you need USBCON defined before including USBAPI,h, such as with `#include <avr/iousbxx2.h>`

Having Serial defined in CDC.cpp is not enough.  No other file is going to include CDC.cpp directly, so it needs to be defined via HardwareSerial.h or USBAPI.h as far as I can tell.

@jniemann66, can you open a new issue for what you've reported and we'll investigate?  This works for me.

@donofthenorth, that looks like a bug.  Can you open a new issue for that and we'll investigate?

@FMLS, @ThatJCB's workaround is the correct way to revert the linter back to the previous behavior.  We fully support both intelliSenseEngines.  The new engine is the direction we're trying to move in and will allow for us to provide semantic analysis of your code files similar to what you get with Visual Studio.  We appreciate your feedback and I would be more than happy to help you debug your `includePath` and `defines` in c_cpp_properties.json to get the new IntelliSense stuff working for you.  Please open a new issue if you would like some additional help.

**Comment by donfiguerres** [comment]
@bobbrow Thanks! Created #756 .

**Comment by ThatJCB** [comment]
@bobbrow thank you for the confirmations and offer of help.
I am only using the standard set of Arduino C libraries. The Arduino extension, also by Microsoft, requires the C/C++ extension installed as well.
It is not practical for you to help reconfigure thousands of Arduino developers VSCode setups as each individually finds this thread 😀 but thank you for offering. I think it makes more sense, if the Arduino libraries need to be changed, for that to be done as part of the Arduino extension.

The Tag Parser works very well for me. It feels stable and it could be my imagination but picks up the local methods and variables better than I remember from the earlier version, which I assume was set to default.
Regards

**Comment by rthier** [comment]
@ThatJCB Did you see de comment in settings?

> // Controls the IntelliSense provider. "Tag Parser" provides "fuzzy" results that are not context-aware. "Default" provides context-aware results and is in preview mode - hover and error squiggles are currently implemented. Features not yet implemented in the new default engine will use the tag parser engine instead.
>   "C_Cpp.intelliSenseEngine": "Default",

I think that the CPP team inserted an incomplete feature.

**Comment by ThatJCB** [comment]
@rthier I did see the comments which is one of the reasons I tried changing to the 'Tag Parser.'

It must be very difficult to write a reliable context aware engine. It will have to follow the exact make script otherwise it is always going to risk being badly wrong.

The "fuzzy" not context aware method is better for me because I would rather have a few false positives that are thrown out by the compiler, rather than spending ages debugging an indicated fault only to find that it compiles fine.

**Comment by bobbrow** [comment]
> I think that the CPP team inserted an incomplete feature.

@rthier the case could also be made that the Tag Parser is incomplete since it does not support all of VS Code's protocol messages (e.g. refactor, find all references, code lens). We feel that it is better to preview features as they become available rather than make everyone wait a really long time for everything to be implemented before letting anyone use it.

For example, if I was almost done with an implementation of semantic-aware auto-complete (our most requested feature) should we wait until goto definition/declaration, signature help, etc are also complete before releasing it?  Our opinion is no.

That said, the Tag Parser will continue to be supported going forward and is available to anyone who is dissatisfied with the new IntelliSense engine.

**Comment by xchen-cs** [comment]
I have a similar problem on Mac for OpenGL, F12 works. But it marks both header files and symbols.
![untitled](https://cloud.githubusercontent.com/assets/1148756/26389306/ee09ee8c-408b-11e7-9dfd-bc0f77a00d15.jpeg)
![untitled1](https://cloud.githubusercontent.com/assets/1148756/26389307/ee1acec8-408b-11e7-8cc8-735e8d07abc6.jpeg)
I guess it may due to the use of frameworks on Mac, and I've tried to add "/System/Library/Frameworks" to the include path, but it doesn't work.
Is there any way to overcome this?

**Comment by oldjinx** [comment]
Yes @TerranRush read the thread above.
Look for:
`"C_Cpp.intelliSenseEngine": "Default",`
In the settings and change "Default" to "Tag Parser", and that will fix it for now until they update the parser to fix the default setting.

**Comment by xchen-cs** [comment]
@jinx1uk Thanks a lot. That works for me too.

**Comment by sean-mcmanus** [comment]
@TerranRush The path to the OpenGL folder should be added to the includePath setting -- the setting is not recursive, but browse.path is so you might be able to use Peek Definition to locate the OpenGL path. As of now, we don't plan to make any updates to add the OpenGL folder path as a default.

**Comment by bobbrow** [comment]
@TerranRush, if you would like to open a new issue asking for framework include support in the new IntelliSense engine, that will make it easier for us to track it.  The engine supports it, but it's not wired up correctly right now.

Actually, @sean-mcmanus, framework include paths are handled slightly differently than standard include paths, so the right answer is not to add the OpenGL.framework/Headers path manually.  I'm investigating a workaround.

**Comment by xchen-cs** [comment]
@bobbrow, thanks! I've open a new one here #770.

**Comment by DuMaM** [comment]
The problem reappeared in the Arduino Nano board. @ThatJCB Workaround is also solving this.

**Comment by bobbrow** [comment]
In recent versions of the extension, you can set the `compilerPath` property in c_cpp_properties.json and it will resolve most of your issues with symbols and squiggles.  You should also set `intelliSenseMode` to `clang-x64` (or `gcc-x64` starting in 0.17.8).

This issue has meandered a bit.  I think the original issue and many of the side issues are resolved at this point.  If there are any lingering issues, please feel free to open a new issue so we can investigate.

**Comment by tomatac** [comment]
This is still an issue. Why is it closed?

**Comment by sean-mcmanus** [comment]
@tomatac Could you open a new issue with more repro details?
