### ISSUE TITLE
In an stl::unordered_map containing a huge number of elements(key,value pairs), how to check the value of a particular key of  stl::unordered_map in watch window?, Neither [] operator works nor an iterator expression

### ISSUE THREAD

**Issue by kriti-m-deepr** [microsoft/vscode-cpptools#7436]
In Visual Studio Code 2019 debugger, wherein, I am using windows msvc 2019 x86_amd64 compiler and have gotten C/C++ Extension pack installed,
While debugging my binary, when I try to check the value of a particular key of stl::unordered_map in watch window, by doing something like -
say, its stl::unordered_map<int, string> mapX;
1. mapX[6] - Operator '[]' doesn't get recognized
2. stl::unordered_map<int, string>::iterator - to fetch the memory address of the base element

Neither of this trick works. Please advise. Wonder if anyone faced this issue?

**Comment by WardenGnaw** [comment]
Looks like this is working in VS but not VS Code. 

It may be a problem in the Expression Evaluation Engine since the error `"Function %s has no address, possibly due to compiler optimizations."` occurs with `mapX.at(0)`. 

Investigating if the debugger may be invoking the EE incorrectly/different from VS.

The only work around I have found is using `$LinkedListItem(mapX._List._Mypair._Myval2._Myhead->_Next, <INDEX_HERE>, _Next)->_Myval,!` in the watch window. Downside the text is so large that its hard to see the value on the right side.
