### ISSUE TITLE
Macro at end of struct/class not expanded but treated as variable

### ISSUE THREAD

**Issue by mke-xena** [microsoft/vscode-cpptools#7514]
Issue Type: <b>Bug</b>

Consider the following code:

```
// C++
#define SOME_MACRO_THATS_NOT_A_VARIABLE

struct my_struct {
} SOME_MACRO_THATS_NOT_A_VARIABLE;

my_struct my_var;
```
then Intellisense thinks "SOME_MACRO_THATS_NOT_A_VARIABLE" is both a macro a variable, see attached acreenshot. In this example, of course, it should just expand to nothing. In the real world I use this approach for  a ton of `__attribute__((packed))` structs.

![image](https://user-images.githubusercontent.com/70580121/117936241-ebaa9c00-b304-11eb-8587-12ea5d5478b8.png)

Extension version: 1.4.0-insiders
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

**Comment by sean-mcmanus** [comment]
This is a "by design" limitation of our "tag parser" (inherited from VS, which doesn't resolve macros when parsing) and the solution is to add `#define SOME_MACRO_THATS_NOT_A_VARIABLE` to a cpp.hint file. See the screenshot:

![image](https://user-images.githubusercontent.com/19859882/118018475-b144fd00-b30c-11eb-8275-0677d2553dde.png)
