### ISSUE TITLE
Broken support for C++ functionality

### ISSUE THREAD

**Issue by psukys** [microsoft/vscode-cpptools#752]
Doesn't recognize anything at all, i.e. `std::cout`, `std::vector` or `for_each`

**Comment by bobbrow** [comment]
I'm going to need a little more information from you since we support C++14 and some partial support for C++17.

Can I assume that you have `#include <vector>` in your source file?  If you do and it has a red underline under it, you will need to update your `includePath` in c_cpp_properties.json by adding the path to your include files.

If there is no red underline under your `#include` statement, then the IntelliSense engine is likely failing to compile `vector` or some other dependent include file.  If you open the "vector" header in VS Code (leave your cpp file open too so that the extension can share the translation unit between the two files), do you see any red underlines?

**Comment by psukys** [comment]
@bobbrow `#include <vector>` isn't problematic,  although going into that source, there's plenty (couldn't find better visual representation than scrshot):
![visual expression on vector source file](http://i.imgur.com/XqluNby.png)

Compiler used:

`g++ (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)`

**Comment by bobbrow** [comment]
Thank you, that helps.  We're investigating incompatibility issues with GCC 6.3 right now.

**Comment by bobbrow** [comment]
#739 is tracking our GCC 6.3 issue.
