### ISSUE TITLE
Completion in strings and comments cannot be enabled with editor.quickSuggestions

### ISSUE THREAD

**Issue by hakonrk** [microsoft/vscode-cpptools#7572]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 (build 19042)
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0-insiders2
- Other extensions enabled: None
- Relevant settings:

```json
    "editor.quickSuggestions": {
        "comments": true
    },
    "editor.wordBasedSuggestions": true,
    "editor.wordBasedSuggestionsMode": "currentDocument"
```

**Steps to reproduce**

1. Create a minimal C/C++ file with a variable definition and a comment below it, e.g.
```c
int a_very_long_variable_name;
// A comment
```
2. Start typing the variable name inside the comment.

**Expected behavior**

Since `editor.quickSuggestions` has `"comments": true`, I expected to get the variable name as a quick suggestion. If I try to force a suggestion using <kbd>Ctrl</kbd>+<kbd>Space</kbd>, I just get _No suggestions_.

**Comment by sean-mcmanus** [comment]
This is currently "by design" because it causes the annoying bug in which unwanted completions occur when Enter is used https://github.com/microsoft/vscode-cpptools/issues/2943. Set
```
    "[cpp]": {
        "editor.wordBasedSuggestions": true
    },
    "[c]": {
        "editor.wordBasedSuggestions": true
    }
```
to re-enable wordBasedSuggestion for C/C++. And/or file an issue on VS Code to somehow stop completion on Enter or in cases where the language service believes it shouldn't occur so we could potentially re-enable it by default.

![image](https://user-images.githubusercontent.com/19859882/119196875-bce6a100-ba3b-11eb-9286-fead031d766e.png)
