### ISSUE TITLE
cpptools using 100% cpu time, never stops

### ISSUE THREAD

**Issue by zajo** [microsoft/vscode-cpptools#7592]
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.5.0

![Screen Shot 2021-05-25 at 17 42 03](https://user-images.githubusercontent.com/609498/119585924-977dce00-bd80-11eb-9e0f-369951c8898d.png)

Maybe put a watchdog in place? If cpptools takes 100% CPU for more than 5 minutes, kill it and report a bug?

**Comment by sean-mcmanus** [comment]
100% CPU for minutes may be "by design" depending on what is going on.

Are you able to provide a repro, C/C++ logging, or attach a debugger to get a call stack (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) or get performance logging (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).

**Comment by zajo** [comment]
What I said is, if it takes 100% CPU time for more than 5 minutes you guys should kill it.

The bug I'm reporting is that it never stops, I get non-stop 100% CPU time from cpptools, all the time.

Per your request, I'm attaching the Instruments output following the instructions from your link: [instrumentscli0.trace.zip](https://github.com/microsoft/vscode-cpptools/files/6543201/instrumentscli0.trace.zip)

**Comment by sean-mcmanus** [comment]
Thanks, I'll check tomorrow...

**Comment by zajo** [comment]
Thank you! Let me know if I can help further. Feel free to close when appropriate.

**Comment by zajo** [comment]
vscode just prompted me to upgrade C/C++ for Visual Studio Code to v1.4.0-insiders3, and that solved the problem. Activity Monitor showed cpptools using between 25-50% CPU time and after 10 minutes or so it disappeared.
