### ISSUE TITLE
Unable to open 'exe_common.inl' in latest Insiders

### ISSUE THREAD

**Issue by rewrking** [microsoft/vscode-cpptools#7597]
Bug type: Debugger
- OS and Version: Windows 10
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0-insiders3

![cpptools_exe_common](https://user-images.githubusercontent.com/4885461/119689283-b7f86780-be16-11eb-9d0b-c446873b4403.png)

I received a weird error popup when the program exited the debugger. Seems like something has a hard-coded path (d:\a01\etc does not reflect my system at all). I was specifically stepping through a simple hello world:

```cpp
#include <iostream>

int main(const int argc, const char* const argv[])
{
	std::cout << "Hello world!\n\n";
	std::cout << "Args:\n";

	for (int i=0; i < argc; ++i)
	{
		std::cout << "  " << argv[i] << '\n';
	}

	return 0;
}
```

launch.json
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "MSVC",
			"type": "cppvsdbg",
			"request": "launch",
			"program": "${workspaceFolder}/build/Debug/test",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"console": "integratedTerminal",
			"envFile": "${workspaceFolder}/.env.windows"
		}
	]
}
```
.env.windows is just this (but I don't think it matters):
```env
Path=%ProgramFiles%\Git\bin;%Path%

```

(Build with MSBuild/Cmake/cl - as long as it's MSVC w/ debug info)

Stepping through after `return 0;` creates the popup for me every time.

**Comment by sean-mcmanus** [comment]
That appears to be "by design" -- it's trying to step into the C runtime time code that calls into your main(). The source code path is referencing a path on the build machine on which the C runtime library code was compiled.

You shouldn't need to step past the return from main (unless maybe if you intend to step into some destructor code).

@WardenGnaw might have more info.

**Comment by WardenGnaw** [comment]
This is by design. Also occurs in 1.3.1.

**Comment by andrew-r-king** [comment]
"By design" is fine, but I think it's odd to request the creation of a file that shouldn't exist.

**Comment by WardenGnaw** [comment]
This is due to how debugging works. We are stopping at a point in code that the debugger knows the location of where it expects it to be and give it to VS Code. VS Code provides that prompt to help users create that file if they meant to have it exist. 
Related: https://github.com/microsoft/vscode-cpptools/issues/2762

If you have the source for it downloaded, you can redirect the path with `sourceFileMap`.
A feature related to use the dialog to search for the file is at https://github.com/microsoft/vscode-cpptools/issues/5361

**Comment by andrew-r-king** [comment]
Thanks for those refs. An option to disable those popups would be fine, but I'm of the opinion that the notifications should off by default. I don't know why one would want to create source files during the debugging experience at all.
