### ISSUE TITLE
Auto adding parentheses not working for template free functions

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/vscode-cpptools#7626]
Bug type: Language Service

**Describe the bug**
- C/C++ Extension Version: 1.4.0

**Steps to reproduce**
1. Type any templated free functions
```cpp
std::make_pair
           // ^ not adding ()
```

**Expected behavior**
```cpp
std::make_pair(|)
           // ^ cursor here, with added ()
```
I understand that sometimes (not very likely tho) the template parameters are not deducible so user still need to manually type `<>`. So maybe auto completing `|>()` after user typing `<` is a better idea.

For example I would imagine some solution like this:
```cpp
template<typename T>
void func() {}

func<|>()
   //^ cursor here, with added <> and ()
```

**Comment by sean-mcmanus** [comment]
Yeah, normally we disable () completion for template methods, but we can add the () for cases where we can determine template argument deduction is likely.

We don't complete with <|>() because in some cases the user may want to rely on template argument deduction instead...and our detection for that may not be 100% accurate.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders
