### ISSUE TITLE
UTF-8 sequences in char arrays are not displayed as UTF-8 on hover

### ISSUE THREAD

**Issue by robert-om** [microsoft/vscode-cpptools#7652]
Issue Type: <b>Bug</b>

In C++, when you write with Spanish letters like ñ it is set to UFT-8 (Ã¡) when it should be set to ansi c.

Extension version: 1.4.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by sean-mcmanus** [comment]
Can you give an example? Where is the character used? What is the file encoding?

**Comment by yolaws** [comment]
> Can you give an example? Where is the character used? What is the file encoding?

![vscode-bug](https://user-images.githubusercontent.com/58055757/121274024-f0c91f80-c89f-11eb-9e58-64b9eb21bee4.png)

**Comment by Colengms** [comment]
@yolaws At the bottom of the window, there is a menu with it's currently selected setting displayed as "UTF-8".

![image](https://user-images.githubusercontent.com/49173979/121275304-375b5180-c881-11eb-86ab-8d3dfdfe2bf6.png)

That is the detected encoding for the file.  Since it's set to UTF-8, the UTF-8 symbol would appear to be by-design.  You could change the encoding by clicking on that menu, selecting "Reopen with Encoding", and selecting the desired encoding.  I think "windows1252" might be the encoding you're looking for.  You can also set the default encoding used to interpret files when opened, using the following setting: 

`"files.encoding": "windows1252"`

This functionality is in VS Code, and not specific to the C/C++ Extension.

**Comment by yolaws** [comment]
@Colengms thanks for your reply, I tried but nothing changed 

https://user-images.githubusercontent.com/58055757/121277588-4bb24500-c8a7-11eb-9f20-4cdfe46ea04c.mp4

**Comment by Colengms** [comment]
Hi @yolaws I'm sorry, I missed that you were referring specifically to a hover operation.  It looks like the issue is only related to the contents of strings.  The encoding is being handled properly for occurrence outside of strings.

![image](https://user-images.githubusercontent.com/49173979/121280931-ee5cca80-c88b-11eb-9abe-656d4e65b169.png)
![image](https://user-images.githubusercontent.com/49173979/121280885-d8e7a080-c88b-11eb-9008-2b5b6222fe45.png)

Curiously, we appear to provide the same encoding to VS Code in both correct and incorrect cases.  My guess is that VS Code is not handling the encoding properly for markdown content we return that's within quotes.

**Comment by Colengms** [comment]
It looks like different compilers handle this scenario differently.  Since the character is multiple bytes in UTF-8, and is being stored in a single-byte char array, gcc will use multiple bytes to store the character in my example, leading to a string with a length of 3 (including the null termination).  MSVC/CL refuses to compile if the file is not stored as UTF-8+BOM, and if stored as UTF-8+BOM it will truncate the character value to a single-byte leading to a string with a length of 2.

The hover result is technically correct for gcc.  After converting the 2-byte UTF-8 character into 2 single-byte chars, the hover information is accurately reflecting those 2 chars.  Although `printf` or `std::cout` with gcc appears to display the expected UTF-8 string value, I'm not sure we should treat the contents of all char arrays as containing UTF-8 on hover, as we do not actually know the encoding of a char array. Not all char arrays contain UTF-8 sequences.
