### ISSUE TITLE
Opening large CPP project causes computer to hang

### ISSUE THREAD

**Issue by lukegravitt** [microsoft/vscode-cpptools#769]
Since most recent update 0.11.1 (happened with 0.11.2 also), my computer is completely unusable until the extension completes whatever work it is doing. I'm using on OSX.

**Comment by sean-mcmanus** [comment]
Is the problem too much CPU usage? What processes are using CPU and how many processes are there? Can you kill them? Is your intelliSenseEngine setting set to "Tag Parser"? How many cores does your machine have? We aren't able to repro any problem on Mac. How large is your project? How large is your .browse.vc.db file (you can change the databaseFilename property to ${workspaceRoot}/.vscode/.browse.vs.db to see how it grows in size easier).

**Comment by lukegravitt** [comment]
It's possible this was just caused by the update from 0.11.1 to 0.11.2. I was able to confirm after the update to 0.11.2 that it was the CPP extension pegging the CPU in Activity Monitor. I was not able to confirm that on the earlier update (but it occurred as I opened the same folder).

Once the process completed, my computer went back to normal. I observed 2 vscode CPP processes in Activity Monitor while the system was pegged.

Running OSX El Capitan (Version 10.11.16)
3.1 GHz Intel Core i7 (4 cores)

Project is ~12000 files.

**Comment by sean-mcmanus** [comment]
The only change in 0.11.2 was changing the default intelliSenseEngine setting from "Default" to "Tag Parser", and that setting should only affects errorSquiggles and hover.

It is "by design" for the Microsoft.VSCode.CPP.Extension.darwin to use 100% CPU on one core. It needs to do a directory search. You can reduce this via removing items from your browse.path and/or setting the addWorkspaceRootToIncludePath setting to false (when that setting is false, it won't search through your large workspace directory for symbols). And you can use "/*" at the end of a browse.path entry to make it non-recursive.

**Comment by lukegravitt** [comment]
I tried opening/closing vscode, disabling/enabling the extension and wasn't seeing it anymore. I'll reopen with more info if I see it again with any consistency.
