### ISSUE TITLE
cpp intellisense doesn't honor quick suggestions delay for struct fields

### ISSUE THREAD

**Issue by dgh1000** [microsoft/vscode-cpptools#7732]
I have set a quick suggestions delay of 2000 ms and turned off parameter hints in my VS Code settings file. Yet, when I'm editing C++ files, when I create a struct of type, say, foo, and create a foo variable, then start to type the variable name followed by a period, both a parameter hint and quick suggestion appear immediately. See attached file for an example of creating such a struct.

This has been true forever, but for reference, I'm using VS Code version 1.57.1 and C++ Intellisense 1.5.0 Insiders.

[quick_suggestions.cpp.zip](https://github.com/microsoft/vscode-cpptools/files/6689378/quick_suggestions.cpp.zip)

**Comment by sean-mcmanus** [comment]
This issue is caused by VS Code itself and repros with TypeScript as well. You should file your issue at https://github.com/microsoft/vscode/issues . It's possible it could be "by design", because the intent of the setting may only be for typing in general, and not after a "." which could be considered a separate case where a delay is unwanted, but I'm not sure.
