### ISSUE TITLE
File Extensions do not populate properly when hitting Run

### ISSUE THREAD

**Issue by Bourqu** [microsoft/vscode-cpptools#7736]
Bug type: General

**Describe the bug**
$ bash: cd: c:\Users\User\Desktop\C_C++" && gcc riddle.c -o riddle && c:UsersUserDesktopC_C++"riddle: No such file or directory

cannot use Run when coding in C.

**Comment by Colengms** [comment]
Hi @Bourqu .  Is the issue you are seeing related to the C/C++ Extension for VS Code?  The C/C++ Extension provides services such as IntelliSense, auto-completion and formatting.   Based on the command line you provided, it's unclear how the C/C++ Extension is involved.

**Comment by Bourqu** [comment]
Had reported this issue on the VScode repository and they had responded and
closed my issue by dayimg it was realated to the extension

**Comment by Colengms** [comment]
>> Because json strings use backslashes for escape sequences, you would need to escape any intentional use of backslash.  i.e.: `c:\\Users\\User\\Desktop\\C_C++`

> not sure where I would fix that? 

@Bourqu Perhaps the string issue is in `launch.json`?

https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
https://code.visualstudio.com/docs/cpp/launch-json-reference

Otherwise, I really don't have enough information here to help you.  Did you use a feature of the C/C++ Extension, such as `Build and Debug Active File`?  Any more context you could provide would help.
