### ISSUE TITLE
C_Cpp.vcFormat.newLine.beforeOpenBrace.namespace does not add newLine

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7827]
Bug type: Language Service

**Steps to reproduce**

1. Add settings:
 "C_Cpp.formatting":"vcFormat",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.namespace": "newLine"
2. Type `"namespace aa::bb::cc{}` in a cpp source file.
3. Right-click and choose "Format Document"
4. Observe the line of "namespace".
Actual:
![image](https://user-images.githubusercontent.com/38734287/125585481-6d04d23f-0bdb-4984-bbd8-c17874e5ce96.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/38734287/125585423-a60145c6-13e7-4c73-a06d-e51fa86786b6.png)

Is this a bug on shared code with Visual Studio?

**Comment by sean-mcmanus** [comment]
Can someone see if it repros in VS and file an internal bug if so?

**Comment by Colengms** [comment]
@sean-mcmanus @michelleangela  I think this is by design.

The behavior is correct when using `"editor.formatOnType": true`, after typing the open curl brace and pressing return.  Using Format Document does not modify the formatting of either form, so the issue is not that it's formatting it incorrectly.  If I set `"C_Cpp.vcFormat.wrap.preserveBlocks": "never"`, I get the expected form.  Given the description of the values for this setting, this appears to be by design.  The repro example is a 'one liner', and the default value for `C_Cpp.vcFormat.wrap.preserveBlocks` is `oneLiners`.
