### ISSUE TITLE
my c/c++ intelligence is not working even add of configuration

### ISSUE THREAD

**Issue by RSAIN0** [microsoft/vscode-cpptools#7832]
Issue Type: <b>Bug</b>

My c/c++ intelligence is not working even add of configuration. please solve ths problem its urgent

Extension version: 1.5.1
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.80GB (1.27GB free)|
|Process Argv|--crash-reporter-id 526aac28-a938-4bcd-a614-0ddcd665d5a5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by Colengms** [comment]
Hi @ROHIT9401 .  Since there is not a known issue blocking all users, could you please provide more information so we can determine what might be going wrong on your system?  Exactly what behavior are you seeing, and what are you expecting that is not occurring?  How are you configuring the extension?

Could you provide? :
 * The contents of your `c_cpp_properties.json` file.
 * After setting set the `"C_Cpp.loggingLevel": "Debug"`, the output to the C/C++ output channel leading up to the repro.
 * The output of the `Log Diagnostics` command with the file open that repro's the issue.
