### ISSUE TITLE
Regression: "workbench.editor.revealIfOpen" option does not work for command "C/C++: Switch Header/Source"

### ISSUE THREAD

**Issue by dmurph** [microsoft/vscode-cpptools#7835]
This has broken again. Original bug is here:
https://github.com/microsoft/vscode-cpptools/issues/6749

And this seems to have regressed.

Extension version v1.5.1
vscode Version: 1.57.1

**Comment by Colengms** [comment]
Hi @dmurph .  In a simple example, I'm seeing the extension choose the existing open file instead of opening a new file.  Is it possible you are seeing an issue due to the existing file having been open via a path that differs in casing?  (I believe there is a VS Code issue open on this).  Otherwise, does this repro for you with a simple example?  If not, can you determine what is different in the scenarios in which it repros?

**Comment by dmurph** [comment]
The repro that I have is that I have two window groups, and I use ctrl-p to open all files.

Put a .h file in left window group, put a .cc file in right window group. Execute the switch header/source command on one window

Expected: The existing editor pane in the other window group is focused
actual: A new editor is opened in the focused window group

**Comment by Colengms** [comment]
Hi @dmurph .  Perhaps I am misunderstanding what you mean by "window groups".  Is that a multi-window feature of VS Code I may not be aware of?  I get the expected behavior using 1.5.1, with separate file groups.  The following switches between these 2 files when I use the `Switch Header/Source` command.

![image](https://user-images.githubusercontent.com/49173979/126205518-6185b57b-f549-4ced-9edb-82b5e87d87ae.png)

Is there more info that might be needed to reproduce the issue you are seeing?

**Comment by dmurph** [comment]
Ah - it seems like there is a specific version of this command that doesn't, work - see my screenshot:
<img width="1323" alt="Screen Shot 2021-07-19 at 1 29 31 PM" src="https://user-images.githubusercontent.com/294026/126223224-ffcb2e38-2b0a-47a8-bccb-8d86bbdda3f2.png">

This seems to be broken - BUT if I trigger the same by the run-command (ctrl-shift-p), then I get an error saying that this command is disabled because intellisense is off (due to clangd plugin).

If I use the other command (not the one prefixed by "C++"), then it seems to work.

Something weird is happening here...

**Comment by dmurph** [comment]
Actually - none of them seem to be working except the clangd one. Trying to record a video now

**Comment by dmurph** [comment]
https://user-images.githubusercontent.com/294026/126223740-dda285a3-229a-44b4-9640-f59b86bb4c74.mov

See video attached above :)

**Comment by Colengms** [comment]
Hi @dmurph .  I don't have a `Switch Header/Source` command in my command palette like you do.  The command provided by the C/C++ extension is `C/C++: Switch Header/Source`.

It sounds like you have set `"C_Cpp.intelliSenseEngine": "Disabled"`, which essentially disables the entire C/C++ extension (all features that require either IntelliSense or tag parsing), so the `C/C++: Switch Header/Source` is not actually available.  I suspect you are seeing an error in another extension's implementation of Switch Headers/Source.
