### ISSUE TITLE
F12 Go to Definition doesn't work after installing C/C++ extension pack

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#7847]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 11 Insider Preview 10.0.22000.51
- VS Code Version: 1.58.2
- C/C++ Extension Version: v1.0.0
- Other extensions you installed (and if the issue persists after disabling them):
I think the only extension I've physically installed  is C/C++ extension, others shown in the list but I've never installed them personally.
![image](https://user-images.githubusercontent.com/87637077/126287675-572b7416-9ada-40f0-b3d0-90af4fd025cc.png)

- If using SSH remote, specify OS of remote machine: Linux
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
I can't use Go to Definition/F12 in VS code, I'm working on *.c project and this happens for both remote and local projects. The function in the menu just show inactive/grey and can't be used. Even if I uninstall C/C++ Extension Pack.

**Steps to reproduce**

Click F12, doesn't work, Menu=>Go=>Go to Definition (inactive)
![image](https://user-images.githubusercontent.com/87637077/126287787-cfc011a0-059b-4fb5-9b03-3a0796ea7c8c.png)

**Expected behavior**

F12 works

**Comment by michelleangela** [comment]
@judyw0906 I see that you're using the C++ extension on a remote Linux machine. Could you verify that the extension is installed on the remote machine as well? 

If the C++ extension is installed on the remote machine, could run `C/C++: Log Diagnostics` from the VS Code command palette and also get logss from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)?

**Comment by judyw0906** [comment]
here's the snapshot of my installed extensions on the remote I'm having problem with:
![image](https://user-images.githubusercontent.com/87637077/126414161-77805ca8-80a6-40da-b6ee-d1d1f3e63c46.png)

Please note that the problem is first discovered when using in remote. Uninstall the extension, or even reinstall VS code did not fix it. And then the problem is found in both remote and local projects.

When I run C/C++: Log Diagnostics in F1 command line, it showed the following:
![image](https://user-images.githubusercontent.com/87637077/126414380-3f348e55-0151-4315-a4be-52ef78e57b1b.png)

In my remote project, after setting logging to Debug, the task pull-down menu showed as below, there's no C/C++ to select?
![image](https://user-images.githubusercontent.com/87637077/126415085-bb1f07db-35f6-4254-9ea3-8602c85347ad.png)

**Comment by michelleangela** [comment]
Setting "C_Cpp.intelliSenseEngine" to "Disabled" will disable IntelliSense features and code navigation features such as "Go to Definition". It will also disable logging related to IntelliSense, which is why both the C++ Log Diagnostics and C/C++ logging output view are not available.

Could you set "C_Cpp.intelliSenseEngine" to "Default" for the remote machine or workspace folder on the remote machine, and see if IntelliSense works after changing the this setting?

This setting can also be changed using the VS Code UI settings 
![image](https://user-images.githubusercontent.com/38734287/126546095-589bd5ad-f7b7-4a6b-9f72-2c4aaa235dfc.png)

**Comment by judyw0906** [comment]
I turned it to default, but F12 still showed inactive.
![image](https://user-images.githubusercontent.com/87637077/126578899-7ea72938-8ba2-4e13-bed1-cb7b37fcbd7f.png)

I'm sure I got this extension, but looks like it's missing something?
![image](https://user-images.githubusercontent.com/87637077/126578948-dbb34c27-1b41-4797-a152-f387b240f953.png)

Background story, I disabled, reinstalled this extension before, and that's when the problem started to show.

**Comment by judyw0906** [comment]
Is there a way to install the whole thing fresh? I don't mind to uninstall my vs code and all, I'm just started to use it. Last time I was trying to do that, but looks like some configuration isn't clear, so after reinstall them problem exists.

**Comment by sean-mcmanus** [comment]
What do you mean F12 shows inactive? Do you see any C/C++ logs?

**Comment by judyw0906** [comment]
I mean Go to Definition is still inactive/grey in the menu.

**Comment by judyw0906** [comment]
-------- Diagnostics - 7/22/2021, 9:49:34 AM
Version: 1.5.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.

**Comment by sean-mcmanus** [comment]
Hmm, I also see Go to Def being gray in the Go menu -- I didn't even know those existed (not sure if that's a bug with our extension or VS Code). Does Go to Def in the right-click menu or via F12 work?

**Comment by judyw0906** [comment]
It used to work, I'm pretty sure. So are you suggesting I should uninstall the C/C++ extension, and see if Go to Defnition/F12 functions?
Attached the image for menu=>Go To Defnition
https://user-images.githubusercontent.com/87637077/126287787-cfc011a0-059b-4fb5-9b03-3a0796ea7c8c.png

**Comment by sean-mcmanus** [comment]
With the C/C++ extension installed do you see go to def in the right-click menu?

![image](https://user-images.githubusercontent.com/19859882/126581229-a2487589-29f8-44b9-9cae-41a3513681c6.png)

**Comment by judyw0906** [comment]
Now I can right clikc and see Go to Definition and use F12. Thank you.
But as I've shown before Menu->Go to Definition is still grey/inactive, which makes me think it's not fixed. Could be a bug?

**Comment by sean-mcmanus** [comment]
I filed a VS Code bug at https://github.com/microsoft/vscode/issues/129189 .
