### ISSUE TITLE
MacOS 12 Intellisense doesn't work

### ISSUE THREAD

**Issue by a-soll** [microsoft/vscode-cpptools#7901]
Bug type: Language Service

**Describe the bug**
- OS and Version: MacOS 12.0
- VS Code Version: 1.58.2
- C/C++ Extension Version: 1.5.1
- "Intellisense process crash detected" immediately upon opening any .c file.

**Steps to reproduce**
- Open any .c/.cpp file and look at output. It appears the Intellisense process either doesn't boot, or crashes immediately.

**Code sample and logs**

```
[2021-07-31 03:15:02.116] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-07-31 03:15:02.121] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/Users/adam/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:55448:25)
	at Object.dispose (/Users/adam/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:56368:35)
	at /Users/adam/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:58362:28
	at async Promise.all (index 15)
	at async u.deactivateAll (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9983)
```

```
-------- Diagnostics - 7/31/2021, 3:25:06 AM
Version: 1.5.1
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "/usr/local/include"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "cppStandard": "gnu++17",
    "intelliSenseMode": "macos-gcc-x64",
    "compilerArgs": [],
    "cStandard": "c99",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": false,
    "compilerPathIsExplicit": true,
    "compilerPath": "/usr/bin/gcc",
    "browse": {
        "path": [
            "/usr/local/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/adam/code/testing/hi.c ]:
    /Users/adam/code/testing/hi.c
Translation Unit Configurations:
[ /Users/adam/code/testing/hi.c ]: not ready
    Process ID: 52782
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/local/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c99
    IntelliSense Mode: macos-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 0 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 32254
```

**Additional context**
I understand this is a beta OS so not expecting full stability, but didn't see anything about it so figured I would make an issue for awareness.

**Comment by Colengms** [comment]
Hi @a-soll .  The `Intellisense process crash detected` suggests the IntelliSense process (`cpptools-srv`) has crashed.  Since you were able to run `Log Diagnostics`, the main process (`cpptools`) appears to have been functional, at least temporarily.  But, the `Connection got disposed` message appears to be referring to a circumstance in which the `cpptools` process crashed as well.

Since the main process seems to work somewhat, would it be possible for you to connect a debugger to that process (`cpptools`) and provide stacks for the crash that occurs there?  It might be possible to do the same with the `cpptools-srv` process, but it's likely that may be failing too quickly to attach a debugger to it.

Does the issue repro with the simplest of C or C++ files, or is there certain code necessary to reproduce the issue?

Since macOS 12 is not yet released, it's safe to say that we haven't yet gotten a chance to test our extension on it.  It's possible some dependency we need is no longer available, or there is an API we rely on that has been deprecated and disabled.  We can keep this issue open until we confirm basic functionality on macOS 12.

**Comment by a-soll** [comment]
Hey @Colengms, yes it does repro on any C/CPP file. If you open a blank workspace with one .c file and write a printf(),  it will crash. I have also tried attaching a debugger to cpptools, but that process doesn't crash. I cannot attach a debugger to cpptools-srv, however, because it doesn't boot up to be seen in the processes list.

**Comment by sean-mcmanus** [comment]
@a-soll It might also be worth filing a bug with Apple via whatever beta feedback channel they have, since ideally a new OS shouldn't cause our app to crash. They may be able to provide info on how you can get a crash call stack from cpptools-srv (assuming it's not already logged under Library/Logs/DiagnosticReports).

**Comment by a-soll** [comment]
hey @sean-mcmanus, I have unfortunately had to roll back to Big Sur due to the instability, so I won't be of much help to this issue. sorry for the quick shift.

**Comment by sean-mcmanus** [comment]
That's fine -- we'll try it out and possibly ship a fix as soon as macOS 12 is available (we don't normally try out preview/beta macOS's).
