### ISSUE TITLE
c++ theme is retrogress

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#7904]
Bug type: General

after Switch to c/c++ theme
this syntax highlight seems not good than `dark +(default)`,ex: the functionname and parameter become into   Loss of light
![image](https://user-images.githubusercontent.com/1876302/127826824-a49476a3-689e-47a7-8478-0e039517aff9.png)

**Comment by Colengms** [comment]
Hi @heartacker .  Are you referring to the `C++ Themes` extension?  Those themes were intended to match the Light and Dark themes from Visual Studio.  There are various tokens colored by Dark+ that Visual Studio does not color by default.  So, this is currently by-design.  Some colorization changes have since been made in Visual Studio 2019.  Updating the `C++ Themes` extension to match updated colors in Visual Studio 2019/2022 is being tracked by: https://github.com/microsoft/vscode-cpptools/issues/6108

**Comment by Colengms** [comment]
Closing this as a combination of by-design and duplicate.  :)
