### ISSUE TITLE
Significant slowdown in cppvsdbg debugger launch time between versions 1.1.3 and 1.2.0

### ISSUE THREAD

**Issue by callumdmay** [microsoft/vscode-cpptools#7968]
**Describe the bug**
- OS and Version: Win 10 21H1
- VS Code Version: 1.59.0
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
There is a noticeable lag in launching a debug task between versions 1.1.3 and 1.2.0. 

In 1.1.3 the measured time is ~ 4s
In 1.2.0 it's over a minute.

**This issue persists until the most recent version as well, I just bisected it to 1.2.0**

I can get a clean repro just by using the "install another version" and switching between versions.

launch.json:
```
{
      "name": "Edge",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "${workspaceFolder}/out/debug_x64/msedge",
      "args": [
        "--user-data-dir=C:/edge/profile",
      ], 
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}/out/debug_x64",
      "environment": [],
      "logging": {
        "moduleLoad": false,
      },
    },
```

**Comment by WardenGnaw** [comment]
This is due to performance regressions in the Expression Evaluator and vcruntime. 

Relevalent: https://github.com/microsoft/vscode-cpptools/issues/6913

**Comment by callumdmay** [comment]
@WardenGnaw is the only workaround here to use 1.1.3?

**Comment by WardenGnaw** [comment]
If you want to use VS Code, you will need to downgrade to v1.1.3 until both the regressions are fixed.

However, using Visual Studio is also a possible workaround. You can have the same experience in Visual Studio using [OpenFolder](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019).

See [tasks.vs.json](https://docs.microsoft.com/en-us/cpp/build/tasks-vs-json-schema-reference-cpp?view=msvc-160) and [launch.vs.json](https://docs.microsoft.com/en-us/cpp/build/tasks-vs-json-schema-reference-cpp?view=msvc-160).

This is available in both Visual Studio Community and Enterprise

**Comment by sean-mcmanus** [comment]
@WardenGnaw You're saying VS doesn't have the performance regression or it got fixed with VS and we haven't shipped the fix yet for VS Code?

**Comment by WardenGnaw** [comment]
Visual Studio does not have the performance regression. Msdia and CppEE cause the 32-bit debugger to slow down based on previous reports, perf traces and crash dumps (all were instances of Out of Memory Exceptions).

**Comment by benvanik** [comment]
Just wanted to ping this issue as my coworker and I are encountering this as well and there's been quite a few releases since this regression showed up so we wanted to make sure it didn't get lost. I confirmed that the latest Visual Studio 2019 preview can launch debugging immediately while vscode with v1.7.1 can take ages - for some binaries up to a minute or more (we have PDBs up to 2GB). Using ETW I captured the stack taking all the time:
![image](https://user-images.githubusercontent.com/75337/138388335-cbe702e9-a63e-4436-be07-cf7dd2df806d.png)

I tried being a little clever and swapping the vsdebugeng.dll from VS in for the one in the extension but it looks like the API isn't stable like that ;(

Is there any ETA on deploying the fix or how long we'll need to pin to v1.1.3? (we want all the nice features that have been added since - but also not minute long hangs on f5 :)

**Comment by benvanik** [comment]
Any update @WardenGnaw?

**Comment by WardenGnaw** [comment]
Unfortunately I do not. This is still on the folks who own `msdia140.dll` and it does not seem like they have responded or acted on it.

**Comment by benvanik** [comment]
Thanks for the update! Is there anywhere I could help poke/vote/etc or is it internal stuff?
