### ISSUE TITLE
Add auto-complete support for headers

### ISSUE THREAD

**Issue by imhuay** [microsoft/vscode-cpptools#802]
ref: https://code.visualstudio.com/docs/languages/cpp#_getting-started

Why it can't auto-complete `#include` headers or intellisense the headers in other word , even I config the `c_cpp_properties.json`.
Can it intellisense the headers of the PATH?

Thx in advence!

**Comment by bobbrow** [comment]
We don't have support for this yet.

**Comment by azydevelopment** [comment]
For the longest time I was wondering why my autocomplete wasn't working.  Makes sense now.

(PS. Hi Bob   -AY)

**Comment by azydevelopment** [comment]
Is this a planned addition?  No details in the milestone/assignee field.

**Comment by sean-mcmanus** [comment]
@azydevelopment It's not something we're planning on adding in the near term.

**Comment by bobbrow** [comment]
A preview of this feature is available in the [insiders release](https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.0-insiders)

**Comment by bobbrow** [comment]
This is implemented in 0.17.0.

**Comment by elegracer** [comment]
Intellisense is still unable to autocomplete the #include for custom includePath, e.g. "/usr/local/include".

This feature is provided by the extension "ajshort.include-autocomplete", but it can only use the includePath in "c_cpp_properties.json" instead of the "C_Cpp.default.includePath"  in the user settings.

Could you please add this feature? It would be quite convenient if Intellisense can do this.

**Comment by sean-mcmanus** [comment]
@joueurh This is supposed to work. Can you file a new issue with more repro info? You can [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to see if the "/usr/local/include" path is being added to your includePath.

![image](https://user-images.githubusercontent.com/19859882/48749977-fd2df400-ec31-11e8-943a-0d18504121a9.png)
