### ISSUE TITLE
Don't Override textmate scope    storage.type.built-in    (a.k.a  have sup for that scope as another semantic token)

### ISSUE THREAD

**Issue by REYNEP** [microsoft/vscode-cpptools#8030]
Type: Feature Request

Many (almost all) themes have different colors for **built-in** `storage.type.built-in` than other data_types

But as semantic tokens overrides **textmate scopes**    can you please make a patch to have support for built-in s too? please???🙂

**Comment by Colengms** [comment]
Hi @REYNEP .  I'd suggest opening an issue in the [VS Code repo](https://github.com/microsoft/vscode/issues).  The C/C++ Extension does not explicitly refer to the `storage.type.built-in` scope.  It provides semantic tokens as documented [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers), as well as some custom C++ specific tokens (templates, CLI types, custom literals).  We provide some fallback scopes to TextMate scopes we had used prior to VS Code implementing a semantic tokens API.  But, otherwise, (futher) fallback through the hierarchy of TextMate scopes would seem to be VS Code functionality.

**Comment by REYNEP** [comment]
Ahhh I see, I somehow forgot **Semantic Token** itself also needs to have that scope support
Thanks you @Colengms   

Closing this as this is not relevant

**Comment by REYNEP** [comment]
+1 More thing.... I was thinking like isn't there any way to like avoid giving    `entity.name.type.cpp`    to those types which already has `storage.type.built-in`     maybe hardcode the values?

**Comment by sean-mcmanus** [comment]
I don't know. @Colengms might be OOF (not sure till when).

**Comment by Colengms** [comment]
We're providing a fallback TextMate scope from the `type` semantic token to `entity.name.type.cpp` only to work around this issue: https://github.com/microsoft/vscode/issues/128565  Otherwise, the extension would not specify associated TextMate scopes for standard semantic tokens.

It's possible we could work around the issue you've identified by specifying all of the same scopes currently identified for the equivalent TextMate token, instead of just `entity.name.type.cpp`.  I think that would scan all of those scopes until it finds one associated with a theme style.  But, I think VS Code _should_ be doing this for us, and it's a bug that it currently does not.  I'd much prefer to see this fixed in VS Code, for all semantic token providers.
