### ISSUE TITLE
C/C++ extension v1.6.0-insiders3 disables `Peek/Go To` and `Format` functionality

### ISSUE THREAD

**Issue by KshitijLakhani** [microsoft/vscode-cpptools#8036]
Bug type: Language Service

**Describe the bug**
- OS and Version: Client - Mac OS Mojave (10.14.6)
- VS Code Version: 1.59.1
- C/C++ Extension Version: v1.6.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): Persists after disabling other extensions too
- If using SSH remote, specify OS of remote machine: Server - Ubuntu 18.04.5 LTS. 
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Workspace is a multi-file project that I've been working on for 2 years and have never seen this issue before upgrading to the newer C/C++ extension version. This is the error I see - 
`The language server crashed 5 times in the last 3 minutes. It will not be restarted.`
Additionally, I cannot use the `Peek/Go to` functionality for functions or variables and cannot use the `Format Document` option as neither shows up when I right-click. 

However, downgrading to the C/C++ extension to 1.5.1 allows me to at least see these two options when I right-click. But, when I use the `Peek/Go-to` option, it still does not seem to be working for some reason i.e., `No definition found for ....` shows up (tried this on multiple files where I used to be able to use this in the past but cannot now). `Format Document` does work as expected though with this version.

**Code sample and logs**

"C_Cpp.loggingLevel": "Debug"

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
None seen 

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
`Connection to server got closed. Server will not be restarted.`

**Comment by Colengms** [comment]
Hi @KshitijLakhani .  The error message, "`The language server crashed `..." indicates that our native process is crashing for some reason.  That is likely why other features then fail to work as expected.  That error message is coming from VS Code itself, but the C/C++ Extension will actually try to restart the language server process (despite that it says it will not be restarted).

Could you enable `"C_Cpp.loggingLevel": "Debug"`, and provide the output to the C/C++ channel leading up to the crash?

Could you check if this issue repro's with a simple project?  There may be something specific to your more complex project that we may need to identify in order to reproduce the issue.  It's possible there is a specific source file or snippet of code involved that leads to the issue.  Isolating that bit of code could help us a lot.
