### ISSUE TITLE
add difference highlight color to identify macro and preprocessor and enummember

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8059]
## hard to Distinguish in default 

- white+:

![image](https://user-images.githubusercontent.com/1876302/130940681-c8574ad2-607e-4ddd-b945-3835b1719f9e.png)

- dark+:

![image](https://user-images.githubusercontent.com/1876302/130941649-e3d598b3-4574-4beb-9a53-5e585b97d0e1.png)

## that will be better:
white+:
![image](https://user-images.githubusercontent.com/1876302/130942129-b8e72250-3ebc-4abb-b618-78b0465d8649.png)

- dark+:
![image](https://user-images.githubusercontent.com/1876302/130941940-10f6f523-6f4d-42c0-b7e8-274e8185d5be.png)

**Comment by Colengms** [comment]
Hi @heartacker .  Macros, keywords, and enum members each have unique scopes for colorization.  Macros and enum members use semantic scopes (i.e. `entity.name.function.preprocessor`, `variable.other.enummember`), while keywords use syntactic/TextMate scopes (various).  So, this would seem to be a theming issue.  Since you are seeing this with a default (Dark+, Light+) theme bundled with VS Code, I'd suggest opening this issue [in the VS Code repo](https://github.com/microsoft/vscode/issues) to request use of more distinct colors for these in those themes.

Closing this issue, as it doesn't seem to be something that can be addressed by the C/C++ extension.
