### ISSUE TITLE
IntelliSense sometimes stops working/loading the database [Remote-SSH]

### ISSUE THREAD

**Issue by pvelesko** [microsoft/vscode-cpptools#8079]
Bug type: Language Service

**Describe the bug**
- OS and Version: Client: MacOS M1 Catalina Server: Linux OpenSuse
- VS Code Version: version 1.54
- C/C++ Extension Version: v1.5.1

After closing and restarting a work session over remote SSH often times the the database doesn't get loaded and "outline" is stuck on "Loading document symbols for this file..."

**Steps to reproduce**
Start a remote SSH session
Work on your c++ project
disconnect & reconnect

Restarting all the clients, servers, enabling/disabling extensions does nothing. 

The only way I found to force fix this is to reset the IntelliSense database. 
Sometimes the command "Reset IntelliSense Database" doesn't do anything and I have to force it by specifying a new database file:

`"C_Cpp.default.browse.databaseFilename": "/home/pvelesko/space/.vscode/vs3.db"`
which will force start the parsing process.

**Comment by sean-mcmanus** [comment]
Is there a dangling cpptools process that has a lock on the database? Are you able to kill that process?

Or is the database somehow in some unusable state?

**Comment by pvelesko** [comment]
@sean-mcmanus I kill every vscode and cpptools processes on both sides. Something more along the lines of unstable state.

**Comment by sean-mcmanus** [comment]
Reset IntelliSense Database not working might be caused by the file being in use by another process or the threads handling that might be blocked -- when that happens do you see the "Reset" appear in the C/C++ logging (when C_Cpp.loggingLevel is "Debug") and do you see the database file get deleted and remade?

We have code that is supposed to detect potential database corruption when the cpptools process is killed while it's writing the database, and then reset the database, but there might be some problem that causes it to not work sometime (or the reset could be failing, although that's not expected).

Do you have any suggestions on a good way to reproduce this, i.e. do certain steps cause it to be triggered more often? Have you only noticed it when remoting to the Linux machine?

We do have one known random failure on our Linux build/test machines with our "database cleaning" test that we can't repro on our locally machines, so it's possible that could be related.

**Comment by pvelesko** [comment]
@sean-mcmanus 
> when that happens do you see the "Reset" appear in the C/C++ logging (when C_Cpp.loggingLevel is "Debug") and do you see the database file get deleted and remade?

Nothing happens at all don't don't budge in that case. 
I had a lot of these issues a week or two ago but then right prior to filing this bug I tried reset database and it worked. One thing that might have been an issue at one point or another was running out of disk space but I addressed that. 

> Do you have any suggestions on a good way to reproduce this, i.e. do certain steps cause it to be triggered more often?
I'll keep an eye on it for the next couple of weeks. Is there any sort of state I can capture to attach here? The logs show stuff when clicking around but nothing related to DB. 

> Have you only noticed it when remoting to the Linux machine?
MacOS -> OpenSUSE is my one use case right now.

**Comment by sean-mcmanus** [comment]
If you see Reset IntelliSense Database give no logging, then attaching a debugger to the cpptools process to get a call stack of a thread that appears to be doing some sort of database operation could help (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv)...that would seem to indicate some sort of deadlock or abnormal termination with the thread queue that handles the database operations.
