### ISSUE TITLE
Thoughts on integration with Rtags

### ISSUE THREAD

**Issue by liamwigney** [microsoft/vscode-cpptools#808]
Hey so I'm a recent ex-emacs convert and I've been spoilt by [rtags](https://github.com/Andersbakken/rtags) a Cpp/C indexer based on clang. This extension either doesn't have the features or the ones here don't work as well.

So the question is two fold, would possible integration with Rtags be something that could happen in the future? Since this extension isn't open source I obviously can't add it myself and while Rtags would have clashing functionality with this extension, it doesn't have the debugging or really any non-indexing things this does. Or are some of the more advanced Rtags features like semantic refactoring, find virtuals and find uses?

**Comment by sean-mcmanus** [comment]
We're not currently planning to support rtags. Someone could publish another VS Code extension that supports it.

**Comment by phord** [comment]
A primordial thing is here, but I haven't used it yet: https://github.com/yorver/rtags-vscode

**Comment by jomiller** [comment]
I forked that extension into a new repo: https://github.com/jomiller/vscode-rtags. I cleaned it up and added some functionality, but it still needs some work.

**Comment by artisdom** [comment]
@jomiller If you're interested in rtags, then you may also want to check out [cquery](https://github.com/cquery-project/cquery), cheers.

**Comment by jomiller** [comment]
@artisdom, I was using cquery before switching to RTags. In fact, I modelled the interface of my RTags extension on the cquery extension. I find that cquery has a better feature set than RTags, but has some major drawbacks:

- cquery consumes too much memory on a huge codebase.
- Because the server is launched by VS Code, cquery has to reload from scratch every time VS Code is started.
- cquery doesn't monitor changes to compile_commands.json after it has loaded.

**Comment by bobbrow** [comment]
I'm closing this issue because after several years we still have not decided in favor of supporting this feature.
