### ISSUE TITLE
Build Task does not find SDL2 header files

### ISSUE THREAD

**Issue by Veinhelm** [microsoft/vscode-cpptools#8105]
Bug type: Debugger

- OS and Version: Windows 10
- VS Code Version: 1.60.0
- C/C++ Extension Version: 1.6.0

Hi! Whenever I try to debug my SDL2 "game" in VSCode, it says it cannot find the SDL header file, and it ONLY shows the error after I pressed debug. I am extremely sure that I have to include path set up correctly. And, the weird part is, when I compile it from G++ on Powershell, it works.
I have no idea whats causing it, therefore I don't know how to reproduce it.
But, here are some screenshots.
![vscode-comp](https://user-images.githubusercontent.com/61033221/132248910-93a5aa05-262f-4e80-9398-d05da432efd3.png)
![gcc-comp](https://user-images.githubusercontent.com/61033221/132248923-e44770e0-bc9a-42b3-9aa1-06cf4cd231db.png)
![props](https://user-images.githubusercontent.com/61033221/132248929-69d74af3-6618-4cd0-937f-7b5082b58d63.png)
![tasks](https://user-images.githubusercontent.com/61033221/132248909-4d008a63-982a-44da-ba54-45749cab4e14.png)

**Comment by Colengms** [comment]
Hi @Veinhelm .

One thing I notice in your `tasks.json` is: `"cwd": "${fileDirname}"`.  The value you have set will cause the directory of a currently open file (if any) to be used as the current working directory when running the command.  You might consider changing this to `"cwd": "${workspaceFolder}"` (and perhaps changing the `*.cpp` arg to `src/*.cpp`, if I'm inferring your directory structure correctly).

Since you are passing relative paths for the SDL2 directories, the issue you are seeing could definitely be caused by an incorrect current working directory.

The build task invokes the specified `command` executable using the specified `args`, as if invoked from a command prompt.  I don't think the C/C++ Extension is doing anything fancy here.  There issue would seem isolated to `tasks.json`.

**Comment by Colengms** [comment]
Hi @Veinhelm .  If you open a command prompt, move to the workspace folder, and execute the command line described n the tasks.json, does it work as expected?

When you run the task, does it echo the command line it uses?  If so, could you post that here?  I'm curious if there were changes made to it, such as quoting added.  If so, you might consider breaking up the multi-part args ("-I", "-L", "-o") into separate args, as the shell would considers those separate args.

Also, you might try using full paths to SDL2.

**Comment by Veinhelm** [comment]
Yes, when I execute the command and args in the workspace folder through PowerShell, it works as expected.

But, I separated the args in tasks.json, like you said might work, and it worked! Thank you!
![Screenshot_1](https://user-images.githubusercontent.com/61033221/132576169-8c84ba88-ddab-4138-9b4f-d1911ce5e994.png)

**Comment by Colengms** [comment]
This looks like it's by-design.  Spaces are interpreted as contained within an arg, not as separating args.
