### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 2185695** [microsoft/vscode-cpptools#8141]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.60.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\PHILLI~1\AppData\Local\Temp\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Colengms** [comment]
Hi @2185695 .  Some high CPU load is expected, due to tag parsing.  But, based on the file you referenced, it looks like you might be running into a deadlock or other issue.  Could you provide that file?  Also, does this happen with a simple project?  There is not a known problem here blocking all users, so we will need to know more about your repro to investigate further.
