### ISSUE TITLE
Too many cl installations when selecting a configuration

### ISSUE THREAD

**Issue by jureid** [microsoft/vscode-cpptools#8168]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.60.1
- C/C++ Extension Version: 1.6.0

When selecting a configuration to debug the active file, the C++ extension is listing a bunch of MSVC installations and it's unclear what the difference between them is because the compiler path isn't shown:

![image](https://user-images.githubusercontent.com/44306969/133845740-fd9aa363-4951-4ad2-9f0c-dbff000a099b.png)

**Steps to reproduce**

1. Open a clean helloworld project **(no tasks.json, no launch.json)**
2. Select Run > Start debugging 
3. Select Windows as the environment

**Expected behavior**
We should use the installation from the most recent version of VS and show the compiler path

**Comment by Colengms** [comment]
I thought perhaps the right fix here might be to display full paths for each, as each entry refers to a different combination of: VS install, target and host.  But, the user is then prompted to launch VS Code from a VS Command prompt (if they haven't already done so), which would have to match the selected `cl.exe`.  It might be simpler to reduce this list to just one entry, and allow the user to choose which version of `cl.exe` based on which variation of the "Native Tools Command Prompt" they chose.

If we do list all available options, we might want to also set up the build environment properly for that selected compiler (target/host), instead of requiring the user to launch from a VS command prompt.

**Comment by sean-mcmanus** [comment]
Yeah, in order to fix https://github.com/microsoft/vscode-cpptools/issues/5271 we needed to get the full path to cl.exe in order to determine which build environment to use.
