### ISSUE TITLE
Quick suggestions work incorrect

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-cpptools#818]
_From @yurriy on June 10, 2017 1:8_

extension cpptools is installed.
VS Code toggle quick suggestions popup, after I type "i++;", but it shouldn't.

- VSCode Version: last
- OS Version: Ubuntu 16.04

Steps to Reproduce:
With cpptools enabled, type "i++;" in any cpp file.

_Copied from original issue: Microsoft/vscode#28400_

**Comment by bobbrow** [comment]
This is a VS Code bug.  We do not register for completion suggestions when semicolon is typed.  I repro this on Windows too.  I asked the VS Code team to reactivate the original issue.

**Comment by sean-mcmanus** [comment]
`_;` is an easy repro (`i++` would only repro the bug if `i` gives > 1000 results). With `_` the incomplete is intentional, because there are > 1000 results, and when the `;` is encountered, the results are still > 1000 because it's invoking autocomplete on a new empty identifier. It looks like we need to somehow force auto complete to exit (via sending an empty result) when the initial identifier is interrupted.

**Comment by bobbrow** [comment]
This is a behavior change in VS Code.  Does not repro in 1.11.2 and earlier.  I am requesting that they address it.  It would be wrong for us to suppress completion results because we don't know whether the request is a continuation of a quick suggestion or completion trigger, or if is manually invoked.

**Comment by bobbrow** [comment]
This is fixed in the latest VS Code Insiders build.
