### ISSUE TITLE
#include <bits/stdc++.h> is shown red in editor

### ISSUE THREAD

**Issue by 18ankitjha** [microsoft/vscode-cpptools#8213]
Bug type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by Colengms** [comment]
Hi @18ankitjha .  That type of error is generally due to an issue with how the C/C++ extension is configured.  We would need more information to investigate further.  

Could you provide the contents of your `c_cpp_properties.json` (if any)?  Could you enable debug logging using the setting: `"C_Cpp.loggingLevel": "Debug"`, and send us the output of the C/C++ output channel leading up to the issue?  And, could you run the `C/C++: Log Diagnostics` command after opening the file that repros the issue, and provide that output?  Those steps should give us a lot of information about how your environment is configured.

**Comment by 18ankitjha** [comment]
I have configured it actually there was not bits c++ file in vs code extension
