### ISSUE TITLE
Go To Definition completely stopped working on 1.6.0

### ISSUE THREAD

**Issue by TravisLlado** [microsoft/vscode-cpptools#8234]
Issue Type: <b>Bug</b>

C/C++ extension was auto-upgraded to 1.7.0 and instantly crashed. When I downgraded back to 1.6.0, none of the extension's features worked anymore. After completely uninstalling and reinstalling the IDE and extension on my local and remote machines and deleting all the caches I could find, Go To Definition still doesn't work on any workspace, in any file. I can type

uint32_t num = 1;
num++;

and if I right click on the second line and select Go To Definition I'll get "No references found for num".

Extension version: 1.6.0
VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-213-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.30GB free)|
|Process Argv|--crash-reporter-id 59b5e7e7-e7ff-454f-9611-dce47e33f26c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.65.110.188|
|OS|Linux x64 4.4.0-213-generic|
|CPUs|Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz (4 x 2899)|
|Memory (System)|62.92GB (0.74GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30377800
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by Colengms** [comment]
Hi @TravisLlado .  Could you try removing the extension's directories from your system, and reinstalling it?  On Mac, they would be stored in: `~/.vscode/extensions/vscode-cpptools*`.  VS Code caches those extension directories, so reinstalling is sometimes insufficient to fix corrupted installs.

Are there any squiggles present when your Go To Definition fails?  `int32_t` is not built-in, it's typedef'ed to `int` in a system header.  It could be that the file failed to parse due to a missing include.  Could you provide a full repro?

**Comment by TravisLlado** [comment]
Yes, I deleted ~/.cache/vscode-cpptools on my workstation. That had no effect. I ssh into that workstation and I don’t have C/C++ extension installed locally so there is no cache on my macbook.

No squiggles. Just a box saying “No references found for xyz”.

**Comment by Colengms** [comment]
Hi @TravisLlado .  To clarify, I'm not referring to cache directories.  I'm referring to where extensions get installed, as they can linger there.  We have seen issues with corrupted extension installations getting reused when reinstalling, even when users uninstall/install via the UI.  To ensure an extension is reinstalled cleanly, it's a good idea to delete the existing installed directories (in `~/.vscode/extensions/`) directly from the file system.  

Since this is not an issue affecting everyone, we would seem to need more information about your environment/setup to investigate further.  Could you provide the contents of your `c_cpp_properties.json`, and any other settings related to the C/C++ extension when you repro?  Could you set `"C_Cpp.loggingLevel": "Debug"` and provide the output of the C/C++ output panel leading up to the repro?  And, with the file open that repro's, could you run the command: `C/C++: Log Diagnostics` and provide that output?

**Comment by TravisLlado** [comment]
I should specify, GoToDeclaration and GoToReferences also do not work. And they don’t work on anything. It’s not specific to uint_32t … that was just a hypothetical example. It fails on variables, classes, methods, types, etc. It doesn’t work on anything anywhere.
