### ISSUE TITLE
External client that connect to the language server Microsoft.VSCode.CPP.Extension.exe

### ISSUE THREAD

**Issue by cstrike** [microsoft/vscode-cpptools#824]
I use lsp4j to implement a client to consume language server and launch the server Microsoft.VSCode.CPP.Extension.exe through command line. The client connects the server through stdin and stdout.
Although I set the root URI of the workspace, it seems that the server still cannot recognize the project and supply service based on the project. For example, when I send request like "textDocument/definition" to the server, I always get nothing in the response.  When I send the request like "textDocument/hover", I get response that says "loading". When I use my client to consume other language servers, it works well.  I don't know what else I need to do when I launch Microsoft.VSCode.CPP.Extension.exe?

**Comment by bobbrow** [comment]
What events do you send to the extension process before you start sending textDocument events?

This is going to be tricky for you to get right because our extension also defines its own custom events that are sent from the JavaScript portion of the extension.  You'll want to inspect the out/src/LanguageServer folder of the extension to see what else is going on.

**Comment by sean-mcmanus** [comment]
@cstrike What exactly is the client? Is it another VS Code or VS extension, a standalone process, or part of another IDE tool like Eclipse?

**Comment by bobbrow** [comment]
Hi @cstrike, unfortunately, using our language server outside of VS, VS Code, and Xamarin is in violation of our license agreement.

See the first item in `~/.vscode/extensions/ms-vscode.cpptools-<version>/LICENSE.txt`. We'll have to ask you not to use our extension binaries in lsp4j.
