### ISSUE TITLE
C++ Walkthrough improvements

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#8304]
There are three enhancements we want to make, then we can restart the feature experiment

1. Add a when clause for the presence of CMakeLists.txt. When we detect CMakeLists.txt:

    - Hide the steps for Edit IntelliSense Configuration and Run and Debug C++ file
    - Show step for Install CMake Tools 

    (Current behavior is to show all three of these steps always)

    - Dependent on https://github.com/microsoft/vscode/issues/121778 

2. Add a completionEvent for already having a C++ build task / debug configuration.

3. #10537. Attached to this issue:
    - https://github.com/microsoft/vscode-cpptools/issues/8470#issuecomment-1009113288

_Originally posted by @jureid in https://github.com/microsoft/vscode-cpptools/issues/7273#issuecomment-863537462_

**Comment by AlexandraKemperMS** [comment]
We also need to add this functionality: 
1. When a user clicks on the "Check for a C++ Compiler" we need to pull up the select a compiler quickpick. If they then select the "help me install a compiler" we need to redirect them back to the walkthrough rather than to docs. 
2. We need to check whether in step 1, but adding the compiler quickpick, we already configured intellisense. If this is the case, we should automatically check the "Configure C++ Intellisense" box. 

We also need to update the svgs for the new debugger step and the run/debug step. These are in progress.
