### ISSUE TITLE
Option to disable Output pane popup

### ISSUE THREAD

**Issue by gruelingpine185** [microsoft/vscode-cpptools#8366]
Type: Feature Request

This isn't necessarily a feature request or a bug, but every time I open a project (or make edits to files) in vscode the Output pane pops up. I'm not a fan of this as it gets in the way of using the integrated terminal. For instance, I may want to recompile come code, so I'd move from the editing area to the terminal area. Then, (sometimes as soon as I click or once I start typing in the terminal) it will erase all that I've typed and switch to the Output area just to write something such as

> [11/3/2021, 10:00:52 PM] For C source files, IntelliSenseMode was changed from "macos-gcc-x64" to "macos-clang-x64" based on compiler args and querying compilerPath: "/usr/bin/clang"

Other times I might not even have the terminal, problems, etc. pane open, but there is no difference in results.

All I'm asking is for an option to disable this feature(?) or for you guys to consider removing it.

**Comment by Colengms** [comment]
Hi @GruelingPine185 .  If you're referring specifically to C/C++ configuration warnings, that issue is being tracked by https://github.com/microsoft/vscode-cpptools/issues/7234 .  If you're referring in general to VS Code changing input focus when a new Output channel is displayed, I'd suggest opening that issue in the VS Code repo, here: https://github.com/microsoft/vscode/issues .
