### ISSUE TITLE
Incorrect URI casing after file rename on Windows

### ISSUE THREAD

**Issue by xiaofu-15191** [microsoft/vscode-cpptools#8398]
Issue Type: <b>Bug</b>

I am writting a C++ source file,its filename format is "Pxxxx.cpp",and there isn't any error squiggles after I write a error,but the intellsense is working,when I try to change my filename "pxxxx.cpp",the error squiggles becomes OK.Is it a bug of C/C++ extension?

Extension version: 1.7.1
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (7.56GB free)|
|Process Argv|--crash-reporter-id 42c358db-98c9-446a-8dd8-516a7bffa289 --crash-reporter-id 42c358db-98c9-446a-8dd8-516a7bffa289 --crash-reporter-id 42c358db-98c9-446a-8dd8-516a7bffa289|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by Colengms** [comment]
Hi @xiaofu-15191 .  Thanks for reporting this.  This appears to be a bug in VS Code.  I've opened an issue against VS Code here: https://github.com/microsoft/vscode/issues/137256 .  I will close this issue.  If VS Code does not address the issue on their side, I will reopen this to track implementing a work-around in the C/C++ extension.

**Comment by Colengms** [comment]
Reopening this.  It sounds like VS Code does not ensure the URIs it delivers to extensions match file system casing on Windows, after all.

This issue is tracking the need to canonicalize all URIs received from VS Code before use in a comparison.

**Comment by Colengms** [comment]
I think the issue here is that, on Windows (or any time the file system is case insensitive), we cannot assume that the URI's VS Code provides us match the case that we would independently arrive upon based on the file system (as they will preserve the existing case of URI prior to the file being renamed, for example).  Any URI comparisons need to be case insensitive.  On Windows, any compared URis need to be canonicalized (converting to all upper case, for example) before compared.  Any URIs stored as keys in a map need to be similarly canonicalized before stored in a Map.

**Comment by Colengms** [comment]
I believe this has since been addressed. The C/C+++ extension may still have some code that tries to convert from canonicalized paths to URIs, which could still cause problems. However, I've since updated canonical-to-URI conversions for currently open files to do lookups against the open files table instead, in order to preserve VS Code's casing. VS Code will consistently use the same casing in URIs regardless of the renamed casing, so the C/C+++ extension should now use that same casing as well.
