### ISSUE TITLE
Recursive include paths

### ISSUE THREAD

**Issue by Jamen1993** [microsoft/vscode-cpptools#846]
I would be very grateful if you would enable support for recursive header search. Typing every single folder from i.e. Boost into the c_cpp_properties file is really annoying.

Kepp up the good work (y)!

**Comment by sean-mcmanus** [comment]
Is this for compiling Boost or using the headers in your own project? If you add the path to the boost headers and reference stuff like "boost/math/complex.hpp", you shouldn't need the paths to be recursive. I assume this is with the "Default" intelliSenseEngine, because the browse.path is recursive already.

**Comment by Jamen1993** [comment]
Hi Sean,

thank you for your reply. I am afraid that I wasn't aware of that
problem/feature because I couldn't find it in the documentation on the VS
Code website. The folks on Stackoverflow told me that VSC doesn't support
recursive includes too and I couldn't find a related issue.

I just want to use VSC as an editor with advanced auto completion and look
up features. The browse path would probably fulfil these requirements. Can
you point me to somewhere to obtain more information about the proper setup
in the c_cpp_properties file?

BW Simon

Sean McManus <notifications@github.com> schrieb am Di., 27. Juni 2017,
17:07:

**Comment by sean-mcmanus** [comment]
We have an FAQ at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md and a blog at https://blogs.msdn.microsoft.com/vcblog/2016/03/31/cc-extension-for-visual-studio-code/ . The Tag  Parser (browse.path) supports the features in a "fuzzy" way. You just need to add the paths (they are recursive by default). We support workspace relative paths via `${workspaceRoot}/..` too. Hovering over the properties in the c_cpp_properties.json also shows tooltips. One thing to be cautious of is old docs that are no longer accurate, because things have changed since the docs were written.

**Comment by Jamen1993** [comment]
Thank you Sean, I will have a look at your suggestions.

Sean McManus <notifications@github.com> schrieb am Di., 27. Juni 2017,
20:02:

**Comment by irekeri** [comment]
Hi Sean,

I have gone over the language server faq, but am still a little confused as to what needs to be in the c_cpp_properties.json file as far as include paths go. The project I am working on has probably over 100 different folders which contain header files. Additionally, thirdparty libraries which are also being compiled alongside the main project have deep and complex folder hierarchies. Having to put each one of these folders as a specific include path is very cumbersome and prone to becoming stale as project folders evolve. 

Will the include paths become recursive to avoid having to manually populate a large c_cpp_properties.json file? I'd like to use the default intellisense engine, was just a little unclear about how to get it to work.

Thanks,

**Comment by sean-mcmanus** [comment]
You have to add to includePath every path that your build system uses. If your include paths are all referenced from a single root like <boost/subdir/file.h> then you only need to add the root path. We are not planning to make the includePath recursive, but we are planning to add better support for various build systems which set include paths. You only need to add the header files that are referenced by the currently open source file as well. You should see a message in the Problems window about the header files that can't be found yet.

**Comment by irekeri** [comment]
Hi Sean,

Is there any sort of debug mode to see how the language server is parsing the include paths? I have created a c_cpp_properties.json configuration file with a majority of the include paths, but am still seeing the error squiggles relating to all of my includes. I am not sure how to tell if the issue is a result of an bad c_cpp_properties.json configuration.

Additionally is there any way to reference include paths that are remote? All of my editing happens within VS Code on macOS, but the compilation happens on a remote linux system (along with all of the libraries needed to do the compilation).

Thanks again. I really appreciate the responses.

**Comment by sean-mcmanus** [comment]
Adding the environment variables VSCODE_CPP_LOGDIR (e.g. /Users/user/logs ) and VSCODE_CPP_LOGFILE_LEVEL (e.g. 9) will enable logging (higher log levels give more output). There are 2 different missing include path messages: "Include file not found in browse.path" for the Tag Parser and another message for the Default IntelliSense engine). The Default version will recursively search through all the child include paths and report the leaf include path that is missing, which is useful for figuring out which file is actually not being found. You should be able to reference remote include paths via doing some sort of samba server, sshfs, etc. and then just add the link/path to the remote file system and it should work.

**Comment by irekeri** [comment]
Hi Sean,

I added those env variables and am seeing quite a bit of logging. From the looks of it, I don't see anything that jumps out at me as an error (aside from a large number of error squiggles). When opening a file, I see database calls attempting to get code items as well as a parse of the path. 

That being said, at the top of my .cpp files, all of my includes are still squiggled as red and additionally I am seeing the "FE: 'Compiler exited with error - No IL available'". From looking through other issues on this site, it could be due to a lack of proper defines? To be honest I am not fully comprehending what I should put in that section of  the configuration file. Some guidance here would be much appreciated. Is there any way to see more detailed information about the compiler failure?

I have scrutinized my includePaths which has mostly everything there (currently around 114 different folders which contain header files), but defining them does not appear to make a difference.

Thanks,

**Comment by sean-mcmanus** [comment]
The No IL available message is from the IntelliSense engine. Yeah, we've seen it occur when the section of code is being excluded from compilation due to a missing #define. It's also possibly caused by the wrong .cpp file being used as the compilation unit for a header file (i.e. it chooses a .cpp file which doesn't actually use the .h file due to it being in inactive code). Are you getting the "No IL" message in a .cpp file? Are you targeting ARM or have any other unusual build settings?

**Comment by daldr-ntml** [comment]
I hope you don't mind me joining this discussion. Running VS Code Insider and cpp extension 0.12.0, I find it necessary to explicitly mention all system include paths in c_cpp_properties.json:

                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/linux",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0/tr1",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0/x86_64-wrs-linux",

Are you saying that recursive include paths are supported and that I should only need to mention the first path?

**Comment by irekeri** [comment]
I believe the only truly unusual part about my build environment is that it isn't actually building on my local machine. While I do all of my editing on macOS VS Code, all of the actual compilation is happening remotely on a 64bit CentOS machine using clang. Other than that I don't believe there is anything unusual going on. This means all relevant third party libraries needed to compile are also remote and not installed locally. 

For clarities sake, I am running:
 - VSCode Version 1.14.0-insider (1.14.0-insider) 
    - 7e2937237620501705e4a5276e76726d35a31905
    - 2017-06-30T05:03:37.538Z
 - C/C++ 0.12.0
 - Git Lens 4.2.0

Also, the "No IL" message is appearing in .cpp files. It shows up when hovering over the red squiggles that are all over my cpp files. Is there any way to get more insight into what is going wrong in the IntelliSense engine? 

And maybe a more silly question, it my specific environment a supported configuration (with so much being remote) for the new IntelliSense engine?

**Comment by bobbrow** [comment]
@DavidA2014, recursive include paths are supported for the browse.path setting, but not the includePath setting.  See: [what is the difference between includePath and browse.path](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#what-is-the-difference-between-includepath-and-browsepath-in-c_cpp_propertiesjson)?

**Comment by sean-mcmanus** [comment]
@irekeri We would like to support your scenario, but the language service doesn't actually run (out of the box) on CentOS due to its not supporting glibc > 2.18. I'm not sure if this is an issue with CentOS or not. I think we need a repro or more info. Are you able to get IntelliSense to work with a folder with just a single .cpp file that has a main function? Do things start to break after adding certain library headers?

**Comment by irekeri** [comment]
Hi Sean,

I can try a smaller project. That being said, although my compilation environment is CentOS, I am not running VS Code or this extension on that machine. VS Code and the C/C++ extension is running locally on Apple's macOS. Are there some additional libraries which I need to install locally to have the language service run successfully?

One aspect of the language service that is not clear to me is how it handles compilation of the files. What are the requirements for a successful compilation of a file? Does the language service have the same requirements as are required to do an actual build of the application I am working on? It seems like the added defines to c_cpp_properties.json is part of this, but I am unfortunately still unsure what exactly needs to go in there to help aid the compilation.

**Comment by sean-mcmanus** [comment]
The various compiler settings need to match your compilation environment. The settings for a macOS host can be found in the extension folder at `bin/msvc.64.darwin.json`. The only difference from CentOS is the --framework_include_directory. If the Microsoft.VSCode.Cpp.Extension.darwin is running then there are no additional libraries needed. Our compiler will need to have enough information to compile your translation unit or it could fail. We expose includePath and defines so far, but other missing options might cause problems. Some other hidden flags are present in `bin/msvc.json`.

**Comment by semihalf-kardach-stanislaw** [comment]
> moved to #990

**Comment by bobbrow** [comment]
@semihalf-kardach-stanislaw, I moved your question to a new issue #990

**Comment by bobbrow** [comment]
In 0.13.0, we use the recursive paths specified in the `browse.path` setting to provide suggestions for you to add to your include path so that you don't have to manually type them out anymore.  [See the release notes for more information](https://github.com/Microsoft/vscode-cpptools/releases).  Once the extension has enumerated those paths we will be able to start providing those suggestions in the light bulbs when you click on the green squiggles under your #include lines.

**Comment by Donpampa** [comment]
@bobbrow,
has anything changed since 2017? I am on Version 0.21.0 now and my project is about 5000 files with high number of include locations. I am still asked to manually update the json file. This is happening even so the first line in includePath is "${workspaceFolder}/**". Also how do I know that the "extenstion has enumerated all the paths in either section?

**Comment by bobbrow** [comment]
@Donpampa can you open a new issue with more details about your project?  If the headers are all under ${workspaceFolder} we should be able to find them.

**Comment by Donpampa** [comment]
@bobbrow, they are found by the Tag Parser since I added browser:path "${workspaceFolder}". The "Problems" tab still tags most of the includes as issues and I have to go to the "light bulb" to manually add them one bye one. From 2017 it looks like a WAD. Is it still so?

I also had ${workspaceFolder}/** in includes but it did not help so I removed it now.

**Comment by sean-mcmanus** [comment]
@Donpampa In addition to what Bob said, you can [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to see how the "${workspaceFolder}/**" gets resolved into the list of folders that actually have includes used.

**Comment by Donpampa** [comment]
Do we need new issue for this? With the below code log says it found ~10k files and added them all  to database.
{
    "configurations": [
        {
            "name": "embed code",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "forcedInclude": [
                "${workspaceFolder}/.vscode/defines_workaround.h"
            ],
            "defines": [
            ],
            "compilerPath": "",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}

Should this cover all header files in the workspaceFolder for the Tag Parser and the Intellisense?
I need the fake include file to undefine LINUX, QNX, INTEGRITY because I am not on any of those but they are still defined.

**Comment by sean-mcmanus** [comment]
@Donpampa Yeah, it's better if you create a new issue. I'm not sure what your bug is. What is your source and target OS? You should set your compilerPath also.

**Comment by Donpampa** [comment]
@sean-mcmanus,
it is embedded system with proprietary OS. I made it empty so that system files will not be used.
What I see so far is that default file above works almost always.
For a broken example - two different header files B.h and C.h both include the same header A.h - #include "A.h". In one case file is flagged as "add to your include path case" in another file - not. Sure enough debug output shows that in working case needed folders are added to the include path. In the non working case - they are not added. Also the same path can be seen as added to other source files. Unfortunately I can not share directory structure to create more usable case.

**Comment by sean-mcmanus** [comment]
@Donpampa You can try doing a Reset IntelliSense Database in case stuff got incorrectly added to our non-existent list. It sounds like you're saying that the recursive includes feature is failing to add a particular folder. This would occur if we detected that that include path was not needed. We have not received any other reports of a bug like this in the past year or so since we released the recursive includes feature. Do you know which version of our extension this broke in? We might need some sort of repro to figure out a cause.

**Comment by sean-mcmanus** [comment]
@Donpampa Oh, we fixed a bug in 0.22.0-insiders2 that caused the recursive includes feature to fail when forcedIncludes is used -- that is probably what you're hitting. You can change your C_Cpp.updateChannel to Insiders to get that fix.

**Comment by sean-mcmanus** [comment]
@Donpampa Oh, actually, that bug was fixed in 0.21.0, so it seems like you're hitting something else (https://github.com/Microsoft/vscode-cpptools/issues/2986).

**Comment by Donpampa** [comment]
@sean-McManus, yes - we can say that recursion does not work reliably. Different source files are getting different subsets of include folders to look at. One of the include folders in question is known to the system because I see it as a part of logs in several cases. Then in one case include folder list is really short and does not have the magic folder. As a result the same header file from the folder is "seen" by one header and not seen by another. Folder and files are all located under the workspaceFolder. One another detail is that the semi-findable header file is present in two different locations. May be this is the culprit. What else? Workspace has about 10 000 files found. Out of them only 4000 are C sources and headers.

**Comment by sean-mcmanus** [comment]
@Donpampa Yeah, if you have multiple header files with the same name at different paths, that can break the recursive includes feature if it chooses the wrong path and you will need to add some non-recursive paths. There is no way for us to determine which path (or the ordering) to use if there are headers with the same name at different paths. Does this sound like what you are hitting?

**Comment by Donpampa** [comment]
@sean-mcmanus, I understand that picking one of the two may be a problem. If this is happens it picks neither apparently. I this expected?
I see some errors in the log related to parsing so. Could they be the reason?
 ... Unable to finalize updates for file, error = 0x80640005: ...

**Comment by sean-mcmanus** [comment]
@Donpampa Yeah, it's supposed to add at least one valid path that contains the `#include`, otherwise it would be a new bug that we haven't seen reported before.

The finalize update error is with tag parsing for our file database. That error code seems like an access denied, possibly due to another process trying to use the database. If the error is occurring for the file that has the `#include` in it, then it's possible that we are failing to get the `#include` parsed. If the error is occurring for some unrelated file, then it's unlikely to affect the recursive includes.
