### ISSUE TITLE
how can I Specially designate the .clang-format file path

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8465]
Type: Feature Request

there are many repo of cpp.
like
```
/.
  /.vscode
  / a-folder
  / b-folder
  / c-folder
```
each of folder is a git repo (we are using **repo** tool to manage)
I want to create only one .clang-format file and place into .vscode folder
how can I do this.
![image](https://user-images.githubusercontent.com/1876302/143979568-a0eab8c7-07b0-4e9f-b871-3fac77a3988a.png)

**Comment by bobbrow** [comment]
According to [this documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html), we should be able to do it if we add a setting to override the working directory for the `clang-format` process since we use `stdin` to send the text.  We already set the path for each file that goes through formatting so that the correct `.clang-format` file can be picked up.

**Comment by sean-mcmanus** [comment]
The .clang-format and .clang-tidy files are not designed to be placed in the .vscode folder, which is only for files that are VS Code specific. Is there some reason you don't want to put the .clang-format file in your workspace root folder, which would enable usage by non-VS Code users?

**Comment by heartacker** [comment]
hi all, why I try to place to the `.vscode` is that we are using repo-tool to manage our code like android. my work space root contains git repos
```
/root 
   /.vscode ----------------this is a git repo
   /a-folder ----------------this is a git repo
   /b-folder ----------------this is a git repo
   /c-folder ----------------this is a git repo
```
including the `/.vscode` all of them are git repo. Usually we should place the `.clang-format` to the root. but the root is not a git repo so that we can't use git to trace. If we want to use git to manage the `.clang-format` file, we should place one into each of those folder. so we want to place a only one .clang-format to `.vscode` and want to make sense to other folder(git repo)

**Comment by bobbrow** [comment]
Usually the recommendation is to place a `.clang-format` file in the root of each repository so that if someone just clones `a-folder` and not the others, they will get the formatting rules.  If you don't like that approach, there could be a parent repo that includes all the other repos as submodules and you put the `.clang-format` in the parent repo (at `/root` in your example).
