### ISSUE TITLE
IntelliSense include error on Mac: cannot open source file "endian.h"

### ISSUE THREAD

**Issue by lihuanglx** [microsoft/vscode-cpptools#850]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|latex-workshop|James-Yu|2.7.0|
|python|donjayamanne|0.6.5|
|code-runner|formulahendry|0.6.24|
|cpptools|ms-vscode|0.12.0|
|java|redhat|0.6.0|;

---

I've been playing with the IntelliSense feature by setting `C_Cpp.intelliSenseEngine` as `Default`. However, I found there's a green squiggly line under my first `#include`, saying "endian.h" file cannot be opened.

Screenshot:

![perkyfarflunghippopotamus-size_restricted](https://user-images.githubusercontent.com/7406791/27622659-0607f8b8-5c0b-11e7-86ae-5e2034f31d3e.gif)

Steps to Reproduce:

1. Write a simple C++ file under an empty directory, open it in VSCode.
2. Set the engine as `Default`, then the error above appears.

**Comment by sean-mcmanus** [comment]
You need to add the path to endian.h. I believe it's at /usr/include/i386. We will consider adding the path to the default macOS includePath if it exists.

**Comment by lihuanglx** [comment]
Thanks, I also found files under `/usr/include/machine` are wrappers of files under the `i386` directory. Adding either one could resolve the problem.

**Comment by Leedehai** [comment]
Thanks for the hint.. Same problem here.
But on my Mac, neither /usr/include/i386/ nor /usr/include/machine exists. IntelliSense also complains about missing math.h and time.h
I can compile C and C++ code using clang on my Mac, though.

**Comment by sean-mcmanus** [comment]
@Leedehai Can you search for endian.h, math.h, and time.h on your machine? If you're using those to build, it has to be somewhere on your build path. You can use `clang -v -E -x c++ - < /dev/null` to find build paths used by clang internally.

**Comment by Leedehai** [comment]
@sean-mcmanus Thanks for the reply. I searched - time.h and math.h are found - they came with mac's Xcode IDE. I use clang to build small programs in command-line, but clang's default include paths contain Xcode's files.
However, endian.h is missing. Then I tried to use clang to compile a test.c that includes one header - \<endian.h\>, and it throwed an error complaining about this missing header file. So it seems endian.h is not necessary for usual compiler usage (not sure) - I didn't notice its absence until now.

Edit - I further investigated the IntelliSense's error message about missing "endian.h" - it turns out that the error originates from a "#include \<string\>" statement. But programs I've built with clang use \<string\> a lot, and I just compiled a test.cpp that includes \<string\>.

**Comment by sean-mcmanus** [comment]
@Leedehai It sound like you might be missing something in your "defines" list. I'd recommend opening up the files that are claiming to require endian.h and look for an #ifdef that is missing. You could also try creating a dummy endian.h file, but if our IntelliSense engine is actually trying to use stuff from that file, then it might complain about the endian.h declarations being missing.

**Comment by ghost** [comment]
I get the same error as @Leedehai

**Comment by Leedehai** [comment]
@AndersenTobias I created a fake "endian.h" in the include directory and problem solved. I know it is far from ideal, though.

**Comment by tcwalther** [comment]
I have the same issue. It seems to me that VSCode reads the wrong `string` file. Instead of one of the files from my `includePath` (`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string`), it seems to read `/usr/include/c++/4.2.1/string`, which is not defined in my `includePath`.

@bobbrow would it be possible to re-open this issue?

**Comment by ghost** [comment]
This disappeared for me with the latest version of VS Code.

**Comment by bobbrow** [comment]
The root cause for this is being tracked by new issue: #1005.  Add `"__LITTLE_ENDIAN__"` to your `"defines"` array in c_cpp_properties.json and you won't need to add a path to "endian.h".
