### ISSUE TITLE
Defines show as undefined even though they are defined

### ISSUE THREAD

**Issue by Ben136KBC** [microsoft/vscode-cpptools#8580]
Issue Type: <b>Bug</b>

You have a CPP file that has this line:

` (*myContainerDebugLogFile) += HTime::Now().GetODBCCanonicalDateString(HTIME_UTC, NULL);`

The problem tab shows:

[{
	"resource": "/e:/KBCDev/Client1/main/Petro-SIM/iface/session.cpp",
	"owner": "C/C++",
	"code": "20",
	"severity": 8,
	"message": "identifier \"HTIME_UTC\" is undefined",
	"source": "C/C++",
	"startLineNumber": 1716,
	"startColumn": 80,
	"endLineNumber": 1716,
	"endColumn": 89
}]

If you hover over HTIME_UTC, the tooltip even shows the define and what it expands too.

![image](https://user-images.githubusercontent.com/12629164/146416116-e9fc9bba-4436-4ce7-8d81-4755b826bf3e.png)

The symbol is defined as:

`#define HTIME_UTC            0x02`

Extension version: 1.8.0-insiders2
VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.26GB (21.85GB free)|
|Process Argv|E:\\KBCDev\\Client1\\main\\Petro-SIM --crash-reporter-id f3b61543-d7cf-4e97-b69b-eeae346935a3|
|Screen Reader|no|
|VM|36%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30405998
vscexrecpromp3t3:30407764
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by Colengms** [comment]
Hi @Ben136KBC .  Since this is not repro'ing for all defines, there would seem to be more that we would need to know about your scenario in order to reproduce the issue and investigate further.  Can you reproduce the error in a reduced example?

Some features of the C/C++ extension will work properly as long as the tag parser has parsed the contents of the file containing the definition.  Some other features, such as IntelliSense squiggles, require that the definition is available specifically in the current translation unit.

We have seen unusual issues with incorrect squiggles with defines.  Does the issue still repro if you disable PCH caching using the setting `"C_Cpp.intelliSenseCacheSize": 0` ?

**Comment by Ben136KBC** [comment]
Weird, now I cannot make it happen and I have not changed anything. If I see it again, I shall log a full reproducible problem, thanks.
