### ISSUE TITLE
Go To Definition looks up all references instead

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8650]
Bug type: General

**Describe the bug**
- OS: Ubuntu 20.04
- VS Code Version: 1.62.2
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them): vscode vim

I'm using VSCode C/C++ extension for Linux Kernel Development.

Clicking the "Go To Definition" actually looks up all references instead when using `compile_command.json`. When configuring `includePath` manually the Go To Definition actually goes to definition as expected.

**Steps to reproduce:**

`c_cpp_properties.json`:

```
{
    "configurations": [
        {
            "name": "Linux",
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "compileCommands": "${workspaceFolder}/compile_commands.json",
            "browse": {
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
```
1. Click on Go To Defenition as in the screenshot below

![Screenshot from 2022-01-11 04-54-36](https://user-images.githubusercontent.com/55092833/148868188-199c7201-d6dc-4ed9-be57-8cd2e1e5e3e2.png)

2. Notice the References lookup at the right bottom

![Screenshot from 2022-01-11 04-56-01](https://user-images.githubusercontent.com/55092833/148868321-97724a04-15f7-4c73-8a48-527c75271c42.png)

**Expected Behavior**: Navigating to the definition

**Actual Behavior**:
Reference lookup result is displayed instead of navigating to the definition which the name suggests

![Screenshot from 2022-01-11 05-02-01](https://user-images.githubusercontent.com/55092833/148868559-ffd70296-7375-4db0-a9cc-a34abc2b17ea.png)

**Comment by bobbrow** [comment]
This is actually a VS Code feature that kicks in when the definition was not found.  So the issue here is not that Go To Definition is running Find All References.  The issue is that the extension didn't find your definition.  Is that symbol `__pgprot` a macro?  A quick search online took me to a bunch of macro definitions in arch-specific files.  If we couldn't find it then it suggests that we might not have indexed the header file for some reason.  Would you be able to share the entry in your `compile_commands.json` for this source file?

For reference, you can change the VS Code behavior for this situation by changing the value of this setting:
![image](https://user-images.githubusercontent.com/12818240/148980124-e58c29d9-5809-413d-858a-0ba9076f549b.png)

**Comment by bobbrow** [comment]
One other note. You may or may not have seen that we now have an extension for Makefiles that should be able to provide IntelliSense configurations for the linux kernel without the need for compile_commands.json.  https://github.com/microsoft/vscode-makefile-tools
