### ISSUE TITLE
Error when using MACRO with VA_ARGS

### ISSUE THREAD

**Issue by FVanGenck** [microsoft/vscode-cpptools#8721]
vscode version used: 1.61.2
C/C++ version used: v1.7.1

When we use a MACRO with VA_ARGS with just the 1 argument, the IntelliSense gives an Error:
`expected an expression`

```
static void func(const char *format, ...)
{
    va_list args;
    va_start(args,format);
    vfprintf(stdout,format,args);
    va_end(args);
}

#define CUSTOM_MACRO(format,...) func(format , ##__VA_ARGS__ )

static void usage() {
    func("test"); //OK
    func("%s", "test"); //OK
    CUSTOM_MACRO("%s", "test"); //OK
    CUSTOM_MACRO("test"); // ERROR
}
```

**Comment by FVanGenck** [comment]
I think the reason is that the parser is not considering the token-pasting operator (##).
and the CUSTOM_MACRO("test") is wrongly translated to func("test", ) iso func("test")

**Comment by 0ffffffffh** [comment]
Hi, I'm having same issue for about a week. Everything was fine but strangely vscode started to mark my __VA_ARGS__ based macro usages as error due to intellisense thinks there is an "expected expression" problem. If I remember correctly, I think the problem started after I had some changes on some other macros in the same file. I'm not sure but, could it be caching issue?

for example

![Screenshot 2022-03-31 013359](https://user-images.githubusercontent.com/437161/160942117-790ecf47-9368-4d87-9ec7-0fc4c7d322bb.jpg)

I need to mention that I have no problem with actual compilation process. 

And here is my vscode setup/configuration info:

VSCode Version: 1.9.7

```
"compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
    "cStandard": "c99",
    "cppStandard": "c++17",
 "intelliSenseMode": "msvc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [
        "/DWIN32",
        "/D_WINDOWS",
        "/W3",
        "/D",
        "\"ENABLE_TRACE\"",
        "/D",
        "\"DEVLOG_LEVEL= 2\"",
        "/MDd",
        "/Zi",
        "/Ob0",
        "/Od",
        "/RTC1"
    ]
```

**Comment by 0ffffffffh** [comment]
Hi @sean-mcmanus, Yes this is absolutely same with the issue you referred. And I tried the fix by disabling the new cpp preprocessor conformance mode with setting `/Zc:preprocessor-`  and it just fixed fine.

So how come this feature has been enabled automatically by default? As far i remember i didn't update my cpp compiler toolset. Maybe vscode upgraded the cpp standard by itself for my project, i don't know. 🤔

Thank you for your assist about it.

**Comment by sean-mcmanus** [comment]
I'm not sure. I'm not able to repro the issue you're seeing. /Zc:preprocessor should be disabled by default, so I'm not sure how that was getting added (maybe by CMake Tools).
