### ISSUE TITLE
Incorrect automatic caret indentation on a new line after a statement without an opening '{'.

### ISSUE THREAD

**Issue by rdxroman** [microsoft/vscode-cpptools#878]
After writing the following line
`if (someCondition)`
and then pressing the 'enter' key, the caret position in the new line will have the same indentation as the 'if' statement, which results in incorrect indentation.

Example:
Caret position is represented by the '|' sign.
Actual Result:
```
if (someCondition)
|

```

Expected Result:
```
if (someCondition)
    |
```

Same happens for other statements such as 'for' etc.

**Comment by sean-mcmanus** [comment]
This is currently "by design". We don't add tabs after a newline is entered. Even typescript doesn't add a tab in these scenarios in VS Code. VS 2017 does add the tab though, so we'll probably support this eventually.

**Comment by rdxroman** [comment]
If I enter the following:
`if (someCondition) {`
and press the 'enter' key, the result will be:
```
if (someCondition) {
    |
```

Is it considered a different scenario due to the explicit scope opening?

**Comment by sean-mcmanus** [comment]
Ah, I see. Yeah, the tab is being added by VS Code itself and not our extension. Using Enter after { is treated as started a scope so it is able to auto-indent, but whatever code is handling this doesn't understand one-line blocks that require indentation. Since the issue repros with Typescript and both languages share the same if/for/etc. statements, maybe VS Code itself could implement a fix. Maye this VS Code issue would address it: https://github.com/Microsoft/vscode/issues/16998 .

**Comment by sean-mcmanus** [comment]
We'll track this with https://github.com/Microsoft/vscode-cpptools/issues/883
