### ISSUE TITLE
Having a toString equivalent for debugging

### ISSUE THREAD

**Issue by Mega-Wolf** [microsoft/vscode-cpptools#8793]
Type: Feature Request

So, in other languages like Java or C#, you can overwrite a toString method and you will then see that string when debugging.
While there are Natvis files, I think they are a bit clunky to use and I'd rather have an equivalent to such a toString method. Here I could basically output any string I want to. In order for it to be usable in C, those functions would have to be something like:

void toString(my_struct* value, char* buffer, size_t bufferSize);

(The identifier toString could of course be changeable with a setting).

**Comment by WardenGnaw** [comment]
This ask is unfortunately going to be a change in both the debugger and part of the C/C++ standard language.

for Java and C#, ToString exist because there is a base `object` class. The feature you are asking is very similar to C#'s [`DebuggerDisplayAttribute`](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/enhancing-debugging-with-the-debugger-display-attributes). That feature was implemented in the runtime side (dotnet), and the debugger can use an API to query / evaluate the display. 

For GDB, their visualization method is writing [pretty-printers in Python](https://sourceware.org/gdb/onlinedocs/gdb/Writing-a-Pretty_002dPrinter.html).

For MSVC, they use [Natvis](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022). 

The C/C++ extension normalized the Natvis implementation to work in both GNU, LLVM, and MSVC built C/C++.
