### ISSUE TITLE
Add support for `${workspaceFolder}` in C_Cpp.files.exclude/codeAnalysis.exlude

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8796]
It doesn't work with files.exclude because in that case all the references are in regards to the workspace folder, but for the settings we add, it might be good to add support for those variables to avoid confusion, i.e. see issues like https://github.com/microsoft/vscode-cpptools/issues/8792 and others.

**Comment by ebenali** [comment]
completed how

**Comment by Colengms** [comment]
This issue was closed by a github-action just 4 days after GitHub added support for distinct "completed" vs. "not planned" states when closing an issue.  The github-actions have since been updated to close using the "not plannel" state.

This issue is still in 'not planned' state, until/unless it gets enough up-votes.
