### ISSUE TITLE
includePath errors even though the configuration seems correct

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8797]
I also seem to be getting includePath errors even though the configuration seems correct.
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${default}",
                "${workspaceFolder}/**",
                "${workspaceFolder}/include",
                "${workspaceFolder}/../cmake-msvc/include",
                "${workspaceFolder}/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```
As per the C++ log, there is no useful information but Intellisense is restarted without the information for includePath
```
cpptools/restartIntelliSenseForFile: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
Comprobando si hay errores de sintaxis: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
Enviando argumentos de compilación para C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
  elementos include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2022\BUILDTOOLS\VC\TOOLS\MSVC\14.30.30705\INCLUDE
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UM
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UCRT
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\SHARED
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\WINRT
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\CPPWINRT
  elementos define: _MT
  elementos define: _DLL
  otros: --rtti
  stdver: ms_c++14
  intelliSenseMode: windows-msvc-x64
cpptools/getCodeActions: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc (id: 227)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
Intentando obtener los valores predeterminados del compilador de C++ en la propiedad "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe"
cpptools/getCodeActions: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc (id: 228)
Se han detectado las siguientes sugerencias de ruta de acceso de inclusión: 1.
cpptools/formatDocument: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc (id: 229)
```
(Apologies, but the language pack is in Spanish)

_Originally posted by @juanjosegarciaripoll in https://github.com/microsoft/vscode-cpptools/issues/7740#issuecomment-1031472838_

**Comment by sean-mcmanus** [comment]
@juanjosegarciaripoll Your includePath are being set by the CMake Tools extension due to `"configurationProvider": "ms-vscode.cmake-tools"`. Have you configured that extension correctly? Also, you can run the C/C++: Log Diagnostics command (with a C/C++ active) to get IntelliSense configuration info -- it should show what includePaths are being sent to us by the CMake Tools extension.

**Comment by juanjosegarciaripoll** [comment]
I have continued to investigate this. It seems that nested in the include chain (tensor/indices.h -> tensor/vector.h -> tensor/config.h) the last file, which is autogenerated by Cmake and exists, cannot be located by Intellisense. Doing the C/C++ diagnostics on tensor/vector.h I see the directory `C:\HOME\JUANJO\SRC\TENSOR\BUILD\INCLUDE` is missing (it is only present in the *.cc) files. Can this be the problem? Is it due to "ms-vscode.cmake-tools"?

**Comment by sean-mcmanus** [comment]
When you open range.cc, what file is not reported as found? tensort/indices.h or a dependency of that file?

When you open a header like tensor/vector.h with no matching source file there could be required includes missing. You should be able to see what source file is being chosen for the TU in the C/C++: Log Diagnostics output.

**Comment by juanjosegarciaripoll** [comment]
I think I have debugged what happens and it is related to how Visual Studio Code associates compiler flags to header files. Say a header X.h is used in various translation units. When that header is analyzed it seems that only the flags of one of the translation units is used. Which one is somewhat arbitrary.

If the file is included in a *.cc file that is actually not compiled (e.g. because that particular file has been deactivated due to configuration flags), the header file may end up without appropriate compiler flags. This means that the header file gets errors that propagate to all other files that include it.

In the example above, tensor/vector.h was used in a file that was not being compiled. It did not get the right include paths and thus failed to find the automatically generated tensor/config.h in the build directory. That meant that vector.h by itself had errors (false positives), but those errors appeared also in other translation units and in other headers

**Comment by sean-mcmanus** [comment]
We have code that tries to choose the best source file to use when opening a header file. The source file that gets chosen could change depending on if you've configured with a configuration provider or compile commands -- are you configured using one of those? -- otherwise it could just pick some file that includes it from querying the database -- you could potentially set C_Cpp.files.exclude to exclude the source file you didn't want to be chosen (assuming you don't need symbols parsed in that file).
