### ISSUE TITLE
header files not found during the compilation

### ISSUE THREAD

**Issue by aguerax9** [microsoft/vscode-cpptools#8813]
When the header files you include in a source file (*.cpp) are not in the same folder as the source file that `#include` them, then the compiler will need to know the path to the included header files that are located in a different folder.

You specify include paths to the g++ compiler by using the `-I` include compiler option. For example:
```
D:/MinGW/bin/g++.exe -g c:~FilePath\Server.cpp -I/SomeFolder/ProjectTP/Sensor -o c:~FileDestination\Server.exe 
```
You can also try to add the full path of the header file in a source file (`#include "/fullPath/someHeader.h"`), but that usually is not preferred.

_Originally posted by @michelleangela in https://github.com/microsoft/vscode-cpptools/issues/4417#issuecomment-540786041_

Hello @michelleangela, I'm using vscode for C coding and I face the same issue. I tried to add -I args to the command but I go the same error.
Here is my tree :
C Code
--src
  I__ functions.c
  |__ functions.h
  I__ main.c

When I include the functions.h file in the main.c file, I got no error but the compilation doesn't work.

Here is my tasks.json

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "C/C++: gcc.exe build active file",
			"command": "C:\\Users\\palew\\Desktop\\MinGW\\bin\\gcc.exe",
			"args": [
				"-g",
				"${file}",
				"-I",
				"${workspaceFolder}\\src\\**",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: C:\\Users\\palew\\Desktop\\MinGW\\bin\\gcc.exe"
		}
	]
}
```
functions.h
```
void sayHello();
```

functions.c
```
#include <stdio.h>
#include <stdlib.h>

#include "functions.h"

void sayHello() {
    printf("hello world");
}
```

main.c
```
#include <stdio.h>
#include <stdlib.h>

#include "functions.h"

int main(int argc, char const *argv[])
{
    sayHello();
    return 0;
}
```
I'm using the code runner extension.

**Comment by Colengms** [comment]
Hi @aguerax9 .  Is this issue related to the C/C++ Extension?  We do generate tasks, but I think we would have set the task type to `cppbuild` instead of `shell`.

Are you asking a general question about gcc command lines?  If so, could you provide the specific error you are seeing when you try to build?

One issue I see is: You are trying to build a project with multiple source files, but your task is for building only the "active file" into an executable.  That task is not sufficient to build both of them into a single executable.  The features which generates these "build active file" tasks assume that only that one source file is required.  For a more complex projects, you would either need to specify all of the source files involved explicitly in the task, or use a build system such as CMake or makefiles.

**Comment by aguerax9** [comment]
Here is my tree
![image](https://user-images.githubusercontent.com/57774272/153559890-5a65baa6-6d1e-46f4-be61-522bb5f3af56.png)

The error says that I need to update the includePath
![image](https://user-images.githubusercontent.com/57774272/153560124-89cca3ef-482f-45b0-9283-ab93d6bc8c3d.png)

And the here is the compilation error
![image](https://user-images.githubusercontent.com/57774272/153560241-f7d8511f-13f4-43fa-892b-3885ca571398.png)

One solution I saw, was to had argumet "-I" to the compile command but It didn't work for me.
I want to know how can I ask my compiler to assume all my files (.c and .h) ?

**Comment by sean-mcmanus** [comment]
The compilation (tasks.json) doesn't inherit from the C_Cpp.default.includePath setting. Can you set something like `"-I", "${workspaceFolder}\\headers"` in your tasks.json?
