### ISSUE TITLE
Add support for docker compilerPath

### ISSUE THREAD

**Issue by JohnBerg60** [microsoft/vscode-cpptools#8814]
Type: Feature Request

compilerPath should accept a path to a interactive docker shell.

Use case:
My team devellops embedded C/C++ firmware, for many different targets and sometimes exotic compilers. I distribute a Dockerfile and a docker-compose to start when vscode runs. We want a uniform toolchain for every target, hence docker.

this is a perfectly valid compilerPath:
```
> docker exec -it armdev arm-none-eabi-gcc --version

arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
...
```

I suspect that, implementing this feature request would involve some extra code in ```vscode-cpptools/Extension/src/LanguageServer/configurations.ts``` starting at line 1350 in function ```private resolvePath```

**Comment by Colengms** [comment]
Hi @JohnBerg60 .  Have you considered using the `Remote - Containers` extension?  I believe that would be the recommended approach for building a project targetting (or using the toolset from) a container.

In our native process, we attempt to invoke the compiler specified in `compilerPath`, assuming it's gcc-like (and not cl.exe).  This assumes the executable on the command line in `compilerPath` is the compiler itself, does some processing of any args present, and adds some arguments (to query the compiler for system includes and system defines).  So, while this may not work using the docker command line directly, you could potentially use a script as your `compilerPath`, encapsulate the needed args to docker, and pass along any received args to gcc.  However, that will not give the C/C++ extension access to the header files contained within the docker image.  For full support, I believe you would need to use the `Remove - Containers` extension.

We could use this issue as a Feature Request to track investigating the potential for built-in support of compilers within docker containers.  We do have similar built-in support for WSL, but that has since been deprecated in favor of the `Remote - WSL` extension.
