### ISSUE TITLE
Use clang-tidy only on files in the compilation database

### ISSUE THREAD

**Issue by hriekehof** [microsoft/vscode-cpptools#8845]
Type: Feature Request

Hi there,

i currently work in a quite large repo. I have a `compile_database.json` for the project and source files i am currently working with. Currently i find for code analysis `Run on Active File`, `Run on Open Files` or `Run on all Files`. I created some exclusion patterns with `C_Cpp.files.exclude` but its nearly impossible to narrow this down to the files i'm interested in.

It would be great to have forth options `Run code Analysis on Files in Compilation Database`.

**Comment by sean-mcmanus** [comment]
This should already be the case (in general, excluding potential buggy cases we may have which you may be hitting) -- we have code that skips code analysis on files for which IntelliSense falls back to the c_cpp_properties for configuration due to configuration info not being in the compile commands or configuration provider. When you open a file that is not supposed to have code analysis run on it and then run C/C++: Log Diagnostics -- what sort of IntelliSense configuration info is reported, i.e. does it appear to be configured from c_cpp_properties.json or a compile commands entry? Can you give more info on the nature of the file, such as how the folder its in is being referenced in the compile commands? Is it a source file or header file?

**Comment by sean-mcmanus** [comment]
Yes, if the compileCommands is set then the other settings in c_cpp_properties.json are only used as a fallback if the source file doesn't exist in the compile_commands.json.

The 29398 is the initial number we get initially from our database, but when it comes to processing those files, the ones without compile commands entries will be quickly skipped, i.e. it may go from 1/29398 to 101/29398 in a second after it skips a bunch of entries.

Therefore, I believe you'll find that clang-tidy is only run on the files that are in the compile_commands.json.
