### ISSUE TITLE
after updating VS code Version: 1.64.2

### ISSUE THREAD

**Issue by bonniewt** [microsoft/vscode-cpptools#8855]
Bug type: Language Service

**Describe the bug**
- OS and Version: Mac OS Monterey version 12.1
- VS Code Version: Version: 1.64.2
- C/C++ Extension Version: v1.8.4
- Other extensions you installed (and if the issue persists after disabling them): N/A
- If using SSH remote, specify OS of remote machine: 
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
After updating VS code to version 1.64.2 and updating C/C++ extension to v1.8.4, IntelliSense no longer checks the code. 

**Steps to reproduce**

1. Install update
2. Opened VS code and got "Couldn't start client cpptools" error message
3. Notice that IntelliSense is not working

**Expected behavior**
IntelliSense works as normal.

**Code sample and logs**
[Error - 8:45:09 PM] Starting client failed
Launching server using command /home/cit595/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/bin/cpptools failed.

**Comment by michelleangela** [comment]
@bonniewt 
The program `cpptools` or IntelliSense language server is failing to start or crashing, which is why IntelliSense is not working.

Could you try the pre-release version 1.9.0 of the extension? The latest pre-release version has some crash fixes that could be related to what you're seeing.

**Comment by Colengms** [comment]
Hi @bonniewt .  Could you try deleting the `/home/cit595/.vscode-server/extensions/ms-vscode.cpptools-1.8.4` folder and installing the C/C++ extension again?  That might solve the issue, if due to the wrong version of the (native binaries for the) extension being deployed to your machine.  (i.e. https://github.com/microsoft/vscode/issues/141696 ).

If that does not address the issue, could you enable `"C_Cpp.loggingLevel": "Debug"` and provide all of the output to that C/C++ output channel leading up to the repro?

**Comment by bonniewt** [comment]
Resolved: I uninstalled the C/C++ extension and the cpptools error message disappeared. Intellisense appears to have returned.

**Comment by sean-mcmanus** [comment]
Yeah, we've seen other reports like this -- there could be some VS Code bug that can randomly cause the extension to install incorrectly.
