### ISSUE TITLE
why g++ command not working in vs code

### ISSUE THREAD

**Issue by NaturalP** [microsoft/vscode-cpptools#8938]

**Comment by NaturalP** [comment]
I'm new learner of C++ language n facing this issue. I have already installed MinGw and set environment variable in path. after that also i'm going through this issue. plz help me to resolve it.
![world cpp](https://user-images.githubusercontent.com/100465444/155836956-4b8c76ee-2ddf-4a48-9684-0c72736e7c87.png)

**Comment by michelleangela** [comment]
@NaturalP 
This issue looks like a compiler issue and not related to the C++ extension.

Just to verify first that g++ is working, could you try compiling and running the g++ command in a command prompt (not in VS Code) and verify that it compiles?

If g++ works in a command prompt, could you try using "command prompt" instead of Powershell in VS Code?
![image](https://user-images.githubusercontent.com/38734287/156062192-5c6aea7e-a9f1-4678-a2c7-d9641ebb31c8.png)

If g++ still doesn't compile, then I would verify if installation of MinGw was correct and also search about the compilation error that the compiler returns to help resolve the issue.

**Comment by maaz25925** [comment]
@NaturalP 
I would like you to first save your file since there is a little icon on the top left hovering over the file icon above the search icon indicating that there is 1 unsaved file. It seems that you are in the directory of where you created your file (according to the picture), so run this command:
g++ World.cpp -o World
You need to set an executable name (I mostly keep it the same as the source file name if it is not a project).
That's all, if there is anything else, then let us know.
