### ISSUE TITLE
failed to update cpptools

### ISSUE THREAD

**Issue by MasonSu** [microsoft/vscode-cpptools#894]
![alt text](http://i.imgur.com/fIwd5vY.png)

the error code is 502 and I can't open the link in  [ #865](https://github.com/Microsoft/vscode-cpptools/issues/865), I failed to download the file manually, so what can I do?

**Comment by pieandcakes** [comment]
@MasonSu Are you behind a firewall or proxy? I clicked the link in #865 and it downloads fine for me too. The package is hosted in the Microsoft Download Center which you would need to be able to reach via the Internet.

**Comment by sean-mcmanus** [comment]
For the next release, we plan to host our binaries on a different download platform that we've been told doesn't have these issues (particularly in China), so we expect that it will get better. However, I'm seeing an unusually high 17% install blockage rate, so we'll continue to monitor and investigate to see if there's something unusual going on (compared to the "normal" download issues we've been seeing)...maybe this is due to the fact that we released 0.12.1 after most U.S. devs were done with work, while China devs were starting.

**Comment by MasonSu** [comment]
@sean-mcmanus Thanks for your reply，Waiting for your good news

**Comment by sean-mcmanus** [comment]
@MasonSu It turns out our download failure rate did not increase with the 0.12.1 update, but we still plan to improve the download availability as soon as possible. It sounds like VS Code itself started using the new CDN in April: https://code.visualstudio.com/updates/v1_12#_china-downloads .

**Comment by MasonSu** [comment]
@sean-mcmanus Thanks for your help

**Comment by sean-mcmanus** [comment]
@MasonSu We've switched our downloads to a new CDN. Can you try downloading now? We're not sure yet how much things have improved. Let us know if there is a certain download that is causing problems still.

**Comment by sean-mcmanus** [comment]
I'm not seeing any improvement yet.

**Comment by MasonSu** [comment]
Yes, I tried again and it succeed
![alt text](http://i.imgur.com/Uc8jV0S.png)
Thanks for your work
