### ISSUE TITLE
Add support for resolving commands

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8946]
See the request at https://github.com/microsoft/vscode-cpptools/issues/8740 (there have been others too, also related to CMake commands).

See CMake Tool's implementation at https://github.com/microsoft/vscode-cmake-tools/blob/f645ad5a08b8ad3168612ffba0858ee9fd73d939/src/expand.ts#L209 .

**Comment by tmaslach** [comment]
I found this issue following #8740

I have `C_Cpp.default.compileCommands` specified as: `${workspaceFolder}/build/merged/compile_commands.json`
I have also enabled `C_Cpp.codeAnalysis.clangTidy.useBuildPath`, setting it to true

This results in this being run (from C/C++ logging window with debug logging enabled):

```
clang-tidy-13
--header-filter=/home/tmaslach/git
--quiet
/home/tmaslach/git/src/myfile.cpp
-p=/home/tmaslach/git/build/merged/compile_commands.json
```

The compile_commands.json on the '-p' line directly above does not belong there.
I assume this is exactly related to what is mentioned here and was on #8740.

Is there any short-term workaround for this? If I omit the `compile_commands.json` in `C_Cpp.default.compileCommands`, I get other issues.
Specifying -p doesn't work for me because I need all the include folders after the -- removed.  Otherwise, clang-tidy simply fails on me (I'm guessing some of the -D arguments have parens and command line or clang-tidy doesn't like that?)

Thank-you!

**Comment by sean-mcmanus** [comment]
Sorry for the late response -- what do you mean by "the '-p' line directly above does not belong there"? You are not using a command in `C_Cpp.default.compileCommands` so your issue seems unrelated to this issue (#8946).

I don't know what you mean by `I need all the include folders after the -- removed`, because setting `useBuildPath` to true should not use the `--` with include folders added.

With `useBuildPath` set to false, we attempt to use manually configure clang-tidy using the results we parse ourselves from the compile_commands.json along with stuff used from querying the compiler, but with `useBuildPath` we rely on clang-tidy itself to read the compile_commmands.json, which may not work for some projects with the default clang-tidy that ships with the extension if there is a problem locating the system includes (overriding the C_Cpp.codeAnalysis.clangTidy.path may workaround that).

**Comment by tmaslach** [comment]
Reading the other ticket again, I think this is related, but I agree it's not the same thing.  I can create another ticket for it if you like.

Now, to explain the issue I see with VSCode v1.66.2 with the C++ Extension v1.10:

This is what is being generated currently (again. from C/C++ logging window):
```
clang-tidy-13
--header-filter=/home/tmaslach/git
--quiet
/home/tmaslach/git/src/myfile.cpp
-p=/home/tmaslach/git/build/merged/compile_commands.json
```

This is what it should be generating:
```
clang-tidy-13
--header-filter=/home/tmaslach/git
--quiet
/home/tmaslach/git/src/myfile.cpp
-p=/home/tmaslach/git/build/merged
```

Notice the only thing removed is `compile_commands.json` in the last line.  Clang-tidy wants the folder compile_commands.json is in, not the actual file it points to.  It fails with that.

Thanks for the explanation in the last paragraph.  I do want clang-tidy to process the compile_commands.json file as the extension is not able to handle it properly. However, now that I know that when `useBuildPath` is `false`, you are trying to do it yourself, I will create another ticket once I have time explaining that issue.  I think it may be related to the fact that I have multiple `compile_commands.json` files in my build folder and I merge them together using cmake's setting: `cmake.mergedCompileCommands`
