### ISSUE TITLE
Issue with ${workspaceRoot} escaping on launch.json's setupCommands

### ISSUE THREAD

**Issue by josesimoes** [microsoft/vscode-cpptools#908]
I'm having an issue using ${workspaceRoot} in "setupCommands".

This line doesn't work:
` {"text": "monitor flash write_image erase \"${workspaceRoot}/build/nanoBooter.hex\" "}`

It throws an error on OpenOCD:
`openocd: Error: couldn't open e:GitHub
openocd: f-interpreter/build/nanoBooter.hex`

(it should have been escaped as `e:/GitHub/nf-interpreter/build/nanoBooter.hex` but I'm guessing that because of the need to wrap the file name with `\"` on the monitor flash it makes it even worst!)

This one either:
`{"text": "file ${workspaceRoot}/build/nanoBooter.elf"}`

It throws this error:
`Unable to start debugging. Unexpected GDB output from command "-interpreter-exec console "file e:\\GitHub\\nf-interpreter/build/nanoBooter.elf"". e:GitHubnf-interpreter/build/nanoBooter.elf: No such file or di...`

This is on a Windows 10 machine.

**Comment by pieandcakes** [comment]
@josesimoes This might be a vscode issue as they own the replacement for ${workspaceRoot}. By the time the debugAdapter receives the message, it has already been replaced.

**Comment by pieandcakes** [comment]
@josesimoes Are you assuming that if you use ${workspaceRoot} on a Windows machine that the path "e:\\foo\\bar" gets escaped to "e:/foo/bar" ? We currently don't do any processing on the setup commands because we assume that what you are entering is what you want and when using ${workspaceRoot} on Windows will give you the Windows style path substitution from VSCode of "e:\\foo\\bar".

**Comment by josesimoes** [comment]
@pieandcakes I'm not assuming, just asking... I haven't looked into the implementation details. 
What I can see is that (on the same launch.json file) if I use it on this line:

`"program": "${workspaceRoot}/build/nanoCLR.elf",` the output is correct. 

Now, when used inside the setupCommands array, like in:

`{"text": "file ${workspaceRoot}/build/nanoBooter.elf"}` the output is wrong.

**Comment by UR3IQO** [comment]
@pieandcakes There is an issue with `\` characters, I found it today when collecting information about [this issue](https://github.com/Microsoft/vscode-cpptools/issues/978). Just see the following piece of the log:
```
1: (726) <-1002-interpreter-exec console "file d:\\Oleg\\!Projects\\Ctrl2\\Ctrl/Debug/Main.elf"
1: (736) ->&"d:Oleg!ProjectsCtrl2Ctrl/Debug/Main.elf: No such file or directory.\n"
1: (737) ->1002^error,msg="d:Oleg!ProjectsCtrl2Ctrl/Debug/Main.elf: No such file or directory."
```
As you see gdb skipped all `\\` symbols. The correct path should be  `d:/Oleg/!Projects/Ctrl2/Ctrl/Debug/Main.elf`.

BTW, here is Windows 8 x64

**Comment by pieandcakes** [comment]
@josesimoes We massage the `"program"` field because we know it has to contain the path to the program and depending on which we think OS is being targeted, we escape/update the directory separators. With the setupCommands, we assume that the user wants it passed exactly as specified so that is what we pass. 

@sov1178 It looks like ${workspaceRoot} is being passed with the windows paths but you are putting in the Linux paths. When looking at your output, my "assumption" is that gdb likes the Linux style directory separators but not the windows ones, even when escaped.

**Comment by pieandcakes** [comment]
I'll take a look under a debugger and see if I can figure out where the issue lies, but if its because of gdb and the directory separators like I mention above, we'd have to find a way to ask users to update the separators. The workaround would be to update the path manually right now instead of using ${workspaceRoot}

**Comment by benjamind** [comment]
I can confirm this issue. I can use `${workspaceRoot}` in `program` and `cwd` fields, but not in the `setupCommands` where I need to pass the absolute path with forward slashes.

Inspecting the debug console shows this is the backslash escaping of the path being passed to gdb:

```
(282) <-1003-interpreter-exec console "file 'd:\\Workspace\\foo/firmware/build/firmware.elf'"
```

A simple solution to this would be for vscode to provide an 'always forwardslash escaped workspaceRoot' path which could be used across different platform commands more easily? Or alternatively the plugin will need to provide its own variable substitution for workspace root?

**Comment by pieandcakes** [comment]
@benjamind We could replace the slashes but we would have to devise some sort of mechanism for the user to also specify when they want the replacement to happen which would start causing complexity.

**Comment by benjamind** [comment]
@pieandcakes not sure which solution you're referring to. If we had ${workspaceRootForwardSlashes} then you'd guarantee that the path there always had forward slashes regardless of platform, rather than having backslashes on windows as current ${workspaceRoot} evaluated to. So this would be a non-breaking change for current users of the variable, and provide a new variable that guarantees linux style separators for cases like this.

Other approach would be for the cpp plugin to automatically force all occurrances of `\\` to `/` in this one place. May break some filesystem paths that explictly use that `\\` but honestly are there any real cases where that happens?

**Comment by pieandcakes** [comment]
@benjamind I was referring to the second approach. The assumption would be we would need to parse the setupCommands, determine which parts are a file path and then replace the slashes OR replace all occurances of `\\` to `/` which could render other times where the user wants `\\` in a passed parameter to break. 

I like your first suggestion and you would probably want to propose that over at https://github.com/Microsoft/VSCode for the vscode team to implement.

**Comment by benjamind** [comment]
Agreed the second case is non-optimal, may be a viable workaround though if the vscode team are unwilling. I guess you don't know that variable substitution is occurring in this case so you would have to escape all `\\`. Is this a commonly used character sequence though? I would argue that nobody ever uses this in their paths.

Anyway, I filed https://github.com/Microsoft/vscode/issues/37438 to see if we can get some progress on this.

**Comment by benjamind** [comment]
Well it doesn't seem like the vscode team will do anything about this issue. What would it take to get this fixed in the cpp plugin?

I was about to checkout the source for this to take a stab myself before realizing the source isn't actually in this repo?

Right now I can't check in my launch.json as it has to contain absolute paths to avoid this issue which is really nasty.

**Comment by pieandcakes** [comment]
@benjamind Sorry, I've been sick. The code you want resides in MIEngine (https://github.com/microsoft/miengine) and the where it is used is here: 
https://github.com/Microsoft/MIEngine/blob/8d3f9d257a0ce9af7fc38024828968d186058e08/src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs#L557

**Comment by benjamind** [comment]
Oh wow. Been a while since I did any csharp!

**Comment by WardenGnaw** [comment]
In v1.1.0, we removed a layer that converted the launch.json to XML back to JSON which caused escaping issues in `setupCommands`. 

Please reopen the issue if you are still experiencing this problem.
