### ISSUE TITLE
C++ debugger hangs retrieving local variables at some breakpoints and not others

### ISSUE THREAD

**Issue by chris-miner** [microsoft/vscode-cpptools#9114]
Bug type: Debugger

**Describe the bug**
- OS and Version: macOS v 12.1
- VS Code Version: Version: 1.65.2
- C/C++ Extension Version: v1.9.7

- Other extensions you installed (and if the issue persists after disabling them):
CMake & CMake Tools are installed.  After disabling them the problem persists.

- A clear and concise description of what the bug is.
I launched a debug session and found that the debugger sometimes hangs getting local variables on a breakpoint.  Depending on where the breakpoint is, either the local variables show up, or I get a little spinner next to the "Locals" entry in the debug variables panel.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Create C++ project
2. build it
3. create launch config
4. set some break points
5. launch the app.  wait for a break point to be hit

found: if you are unlucky, then the breakpoint will be hit, and you'll get the spinner.  Also, stepping through the code doesn't work.  All you can do is kill the debug session.

expected: that debugging would work as it did in the standard hello world example.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
```
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (20231) ->(gdb)\n"},"seq":588}
1: (20231) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (20231) 1014: elapsed time 6\n"},"seq":590}
1: (20231) 1014: elapsed time 6
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (20255) <-1015-var-create - - \"input\" --thread 1 --frame 0\n"},"seq":592}
1: (20255) <-1015-var-create - - "input" --thread 1 --frame 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (20451) ->1015^done,name=\"var0\",numchild=\"3\",value=\"{...}\",type=\"antlr4::ANTLRInputStream\",thread-id=\"1\",has_more=\"0\"\n"},"seq":594}
1: (20451) ->1015^done,name="var0",numchild="3",value="{...}",type="antlr4::ANTLRInputStream",thread-id="1",has_more="0"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (20452) ->(gdb)\n"},"seq":596}
1: (20452) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (20452) 1015: elapsed time 196\n"},"seq":598}
1: (20452) 1015: elapsed time 196
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (20455) <-1016-var-create - - \"lexer\" --thread 1 --frame 0\n"},"seq":600}
1: (20455) <-1016-var-create - - "lexer" --thread 1 --frame 0
```

Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
- I can set other breakpoints in the file that do work as expected.
- I also tried out using CodeLLDB as an alternative C++ debugger and that "just works".  same code base, same breakpoints.

**Comment by joelspadin** [comment]
I've been having an issue with the same symptoms when remotely debugging an ARM Linux device from Windows. My launch config looks like roughly this:

```json
{
  "name": "GDB",
  "type": "cppdbg",
  "request": "launch",
  "program": "path/to/app",
  "cwd": "path/to",
  "targetArchitecture": "arm",
  "miDebuggerPath": "path/to/gdb.exe",
  "miDebuggerArgs": "--command gdbinit.py",
  "miDebuggerServerAddress": "1.2.3.4:5555",
  "externalConsole": true,
  "showDisplayString": true,
  "setupCommands": [
    { "text": "-enable-pretty-printing" },
    { "text": "-enable-frame-filters" },
  ],
  "customLaunchSetupCommands": [
    { "text": "-target-select load --target=1.2.3.4" }
  ]
}
```

where the gdbinit.py script configuration for the target hardware and two things that are explicitly referenced in the VS Code launch config:

1. A frame filter which works around an issue where stacks for pthreads were showing up as an infinite loop of garbage frames below `start_thread()`. The filter simply raises `StopIteration` after reaching this function so VS Code doesn't take forever parsing useless data.
2. A custom target command that sideloads the application, then runs `set remote exec-file` to it.

Everything usually works fine, but seemingly at random it will hang after hitting a breakpoint or when stepping through the code. There does not seem to be any consistency as to which code it is in when it hangs. The call stack window shows one thread as "paused on breakpoint", all other threads as "paused", and one of the paused threads has a spinner animation next to it. The last time I had it hang, the logs ended with

```
1: (138707) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (138707) ->&\"\\n\"\r\n"},"seq":38905}
1: (138707) ->&"\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (138707) ->^done\r\n"},"seq":38907}
1: (138707) ->^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (138707) ->(gdb)\r\n"},"seq":38909}
1: (138707) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (138707) 3671: elapsed time 59\r\n"},"seq":38911}
1: (138707) 3671: elapsed time 59
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (138707) <-3672-stack-list-arguments 0 0 9\r\n"},"seq":38913}
1: (138707) <-3672-stack-list-arguments 0 0 9
```

I am using GDB version 9.1 on Windows 10. The same issue does not occur when running GDB from the command line instead of through VS Code.

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

**Comment by TSonono** [comment]
I also have this exact issue only when using a frame filter. It's always the `stack-list-arguments` argument in the trace log that is the last request that has been sent by the cppdbg debugger. This even when happens when the frame filter just returns the frame iterator untouched (as in the first example in https://sourceware.org/gdb/current/onlinedocs/gdb.html/Writing-a-Frame-Filter.html#Writing-a-Frame-Filter).
