### ISSUE TITLE
Code Analysis reports problems in previously opened files

### ISSUE THREAD

**Issue by Nicolacarrino** [microsoft/vscode-cpptools#9130]
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.66.0
- C/C++ Extension Version: v1.9.7
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
I was using the clang tidy code analysis built into c/c++ Extension and I noticed, after working on several files, that some of the problems reported by the code analysis were related to cpp files that I had already closed. 
It is strange that the analyzer continues to report problems on files no longer opened in the editor but that were previously opened. This gets especially frustrating when I work on multiple files for a while since the problem Panel is full of rows reporting on files no longer being opened, and it gets difficult to go through all the problems searching for the current file I am working on.

I would like to know if there are some options that I have to turn on/off (I tried to search in the settings but my search was inconclusive) or if this is the desired behavior of the extension.

**Steps to reproduce**
Open some files, analyze them, then close these files. The problem Panel still reports the same issues.

**Expected behavior**

The problem Panel should report issues only on currently opened files.

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${default}"
            ],
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-clang-x64",
            "compilerPath": "/usr/bin/g++"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
The clang-tidy errors do not clear when a file is closed, because we support "Run Code Analysis On All Files", which may not be open. You can use the "C/C++: Clear Code Analysis Squiggles" command or the code action to clear the squiggles, which appears as a lightbulb on a squiggle (or potentially a quick fix code action in a future release). Does that work sufficiently or is there some reason it does not?

It's possible we could modify our behavior to auto-clear squiggles on file closing if they were created for a file that was open or whenever the file is closed, and/or add a setting for that, but I'm not convinced yet that it would be beneficial.
