### ISSUE TITLE
Intellisense doesn't parse properly with Unity/Jumbo builds

### ISSUE THREAD

**Issue by the-sushi** [microsoft/vscode-cpptools#9167]
Issue Type: <b>Bug</b>

When working with unity builds Intellisense doesnt parse any cpp file that's included in another cpp file until the file it's included in is opened. You also have to do this every time you debug the program. 

This wasn't a problem with Visual Studio 2019, so maybe it's just an option somewhere I'm missing?

To reproduce try making a new project with 2 cpp files. Make one the main cpp file and include string or some kind of library in it and then include the other cpp file below it. Then use the library you included in the cpp file that's not main. Intellisense may recognize it because you just had the file open where you included it, but if you run the debugger and look at the included file, intellisense should not recognize the library you're trying to use in it until you look at the main file again.

Hopefully there is just some option to make intellisense parse all files regardless of if you have it open.

Extension version: 1.9.7
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.96GB (25.93GB free)|
|Process Argv|--crash-reporter-id 2f740d3e-3676-49f6-b94c-94db7bfd5c95|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by michelleangela** [comment]
@e-sushi 
Could you provide your IntelliSense configuration settings by running the command "C/C++: Log Diagnostics" and also logs of the language server? See https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server for enabling logging instructions.

The extension should parse any includes or libraries that are specified in the IntelliSense configuration. The logging may show clues as what's happening when parsing.

Please note the debugger component of the extension has no context of the information from IntelliSense. Configurations for debugging in tasks.json and launch.json are only used to build and launch an executable.

**Comment by e-sushi** [comment]
<details>
<summary> Diagnostics </summary>

-------- Diagnostics - 4/21/2022, 1:03:22 PM
Version: 1.9.7
Current Configuration:
{
    "name": "Win64",
    "includePath": [
        "${workspaceFolder}/**",
        "C:\\src\\graphviz\\include\\",
        "C:\\src\\tracy-0.7.8",
        "C:/src/glfw-3.3.2.bin.WIN64/include",
        "C:/VulkanSDK/1.2.162.1/include"
    ],
    "defines": [
        "TRACY_ENABLE",
        "BUILD_SLOW=1",
        "BUILD_INTERNAL=1",
        "DESHI_WINDOWS=1",
        "DESHI_DISABLE_IMGUI",
        "DESHI_VULKAN=1",
        "SUUGU_USE_GRAPHVIZ"
    ],
    "windowsSdkVersion": "10.0.22000.0",
    "compilerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [
        "/std:c++17"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:\\src\\graphviz\\include\\",
            "C:\\src\\tracy-0.7.8",
            "C:/src/glfw-3.3.2.bin.WIN64/include",
            "C:/VulkanSDK/1.2.162.1/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\src\suugu\src\suugu.cpp ]:
    C:\src\suugu\src\suugu.cpp
    C:\src\suugu\src\ast.cpp *
    C:\src\suugu\src\canvas.cpp *
    C:\src\suugu\src\solver.cpp *
Translation Unit Configurations:
[ C:\src\suugu\src\suugu.cpp ]:
    Process ID: 27712
    Memory Usage: 187 MB
    Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
    Includes:
        C:\SRC\GRAPHVIZ\INCLUDE
        C:\SRC\TRACY-0.7.8
        C:\SRC\GLFW-3.3.2.BIN.WIN64\INCLUDE
        C:\VULKANSDK\1.2.162.1\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\CPPWINRT
        C:\SRC\SUUGU\DESHI\SRC
    Defines:
        TRACY_ENABLE
        BUILD_SLOW=1
        BUILD_INTERNAL=1
        DESHI_WINDOWS=1
        DESHI_DISABLE_IMGUI
        DESHI_VULKAN=1
        SUUGU_USE_GRAPHVIZ
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 187 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5853
Number of files parsed: 869

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt/math.h
    Alternative: "C:/src/suugu/deshi/src/math"
Using: C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt/string.h
    Alternative: "C:/src/suugu/deshi/src/kigu"
Using: C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt/time.h
    Alternative: "C:/src/suugu/deshi/src/core"

</details>

Here are my diagnostics. The below drop down will have the relevant intellisense debug logging marked with what i did when something happened and where it stops and starts working properly again. Note that canvas.cpp is a file that is included in suugu.cpp and canvas.cpp does *not* include any files on its own. 

<details>
<summary> Intellisense Log </summary>

cpptools/getCodeActions: C:\src\suugu\src\canvas.cpp (id: 460) 
> This is the last action performed before I started a debugging session, at this point intellisense in canvas.cpp was parsed correctly and no errors show in the file

cpptools/textEditorSelectionChange
cpptools/pauseCodeAnalysis
cpptools/resumeCodeAnalysis
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\src\suugu\src\canvas.cpp
cpptools/fileCreated: C:\src\suugu\data\logs\log_1650560401.txt
cpptools/fileDeleted: C:\src\suugu\data\logs\log_1649784752.txt
Checking for syntax errors: C:\src\suugu\src\canvas.cpp
Queueing IntelliSense update for files in translation unit of: C:\src\suugu\src\suugu.cpp
cpptools/fileDeleted: C:\src\suugu\data\logs\log_1650559507.txt
Checking for syntax errors: C:\src\suugu\src\canvas.cpp
Queueing IntelliSense update for files in translation unit of: C:\src\suugu\src\suugu.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Error squiggle count: 0
Error squiggle count: 0
Error squiggle count: 0
cpptools/getSemanticTokens: C:\src\suugu\src\suugu.cpp (id: 461)
cpptools/getSemanticTokens: C:\src\suugu\src\solver.cpp (id: 462)
cpptools/getSemanticTokens: C:\src\suugu\src\ast.cpp (id: 463)
cpptools/getSemanticTokens: C:\src\suugu\src\canvas.cpp (id: 464)
cpptools/getFoldingRanges: C:\src\suugu\src\canvas.cpp (id: 465)
cpptools/getFoldingRanges: C:\src\suugu\src\suugu.cpp (id: 466)
sending compilation args for C:\src\suugu\src\suugu.cpp
  include: C:\SRC\GRAPHVIZ\INCLUDE
  include: C:\SRC\TRACY-0.7.8
  include: C:\SRC\GLFW-3.3.2.BIN.WIN64\INCLUDE
  include: C:\VULKANSDK\1.2.162.1\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\WINRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\CPPWINRT
  include: C:\SRC\SUUGU\DESHI\SRC
  define: TRACY_ENABLE
  define: BUILD_SLOW=1
  define: BUILD_INTERNAL=1
  define: DESHI_WINDOWS=1
  define: DESHI_DISABLE_IMGUI
  define: DESHI_VULKAN=1
  define: SUUGU_USE_GRAPHVIZ
  stdver: ms_c++17
  intelliSenseMode: windows-msvc-x64
Shutting down IntelliSense server: C:\src\suugu\src\suugu.cpp
Checking for syntax errors: C:\src\suugu\src\canvas.cpp
sending compilation args for C:\src\suugu\src\canvas.cpp
  include: C:\SRC\GRAPHVIZ\INCLUDE
  include: C:\SRC\TRACY-0.7.8
  include: C:\SRC\GLFW-3.3.2.BIN.WIN64\INCLUDE
  include: C:\VULKANSDK\1.2.162.1\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\WINRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\CPPWINRT
  define: TRACY_ENABLE
  define: BUILD_SLOW=1
  define: BUILD_INTERNAL=1
  define: DESHI_WINDOWS=1
  define: DESHI_DISABLE_IMGUI
  define: DESHI_VULKAN=1
  define: SUUGU_USE_GRAPHVIZ
  stdver: ms_c++17
  intelliSenseMode: windows-msvc-x64
Queueing IntelliSense update for files in translation unit of: C:\src\suugu\src\canvas.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 394
Update IntelliSense time (sec): 3.478
cpptools/getSemanticTokens: C:\src\suugu\src\canvas.cpp (id: 467)

>this is where I stopped debugging and opened canvas.cpp w/o opening suugu.cpp first. Now intellisense reports a ton of errors throughout the entire file.

cpptools/getFoldingRanges: C:\src\suugu\src\canvas.cpp (id: 468)
cpptools/getFoldingRanges: C:\src\suugu\src\suugu.cpp (id: 469)
cpptools/textEditorSelectionChange
textDocument/documentHighlight: C:\src\suugu\src\canvas.cpp (id: 470)
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\src\suugu\src\canvas.cpp
cpptools/getCodeActions: C:\src\suugu\src\canvas.cpp (id: 471)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/getCodeActions: C:\src\suugu\src\canvas.cpp (id: 472)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: C:\src\suugu\src\canvas.cpp (id: 473)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: C:\src\suugu\src\canvas.cpp (id: 474)
textDocument/hover: C:\src\suugu\src\canvas.cpp (id: 475)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\src\suugu\src\suugu.cpp

> Now I've focused suugu.cpp

cpptools/getCodeActions: C:\src\suugu\src\suugu.cpp (id: 476)
idle loop: reparsing the active document
Checking for syntax errors: C:\src\suugu\src\suugu.cpp
sending compilation args for C:\src\suugu\src\suugu.cpp
  include: C:\SRC\GRAPHVIZ\INCLUDE
  include: C:\SRC\TRACY-0.7.8
  include: C:\SRC\GLFW-3.3.2.BIN.WIN64\INCLUDE
  include: C:\VULKANSDK\1.2.162.1\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\WINRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\CPPWINRT
  include: C:\SRC\SUUGU\DESHI\SRC
  define: TRACY_ENABLE
  define: BUILD_SLOW=1
  define: BUILD_INTERNAL=1
  define: DESHI_WINDOWS=1
  define: DESHI_DISABLE_IMGUI
  define: DESHI_VULKAN=1
  define: SUUGU_USE_GRAPHVIZ
  stdver: ms_c++17
  intelliSenseMode: windows-msvc-x64
Queueing IntelliSense update for files in translation unit of: C:\src\suugu\src\suugu.cpp
Shutting down IntelliSense server: C:\src\suugu\src\canvas.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.661
cpptools/getSemanticTokens: C:\src\suugu\src\suugu.cpp (id: 477)
cpptools/getFoldingRanges: C:\src\suugu\src\canvas.cpp (id: 478)
cpptools/getFoldingRanges: C:\src\suugu\src\suugu.cpp (id: 479)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\src\suugu\src\canvas.cpp

> Now I focus canvas.cpp again and everything is fine in the file

idle loop: reparsing the active document
Checking for syntax errors: C:\src\suugu\src\canvas.cpp
Queueing IntelliSense update for files in translation unit of: C:\src\suugu\src\suugu.cpp
cpptools/getCodeActions: C:\src\suugu\src\canvas.cpp (id: 480)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.283
cpptools/getSemanticTokens: C:\src\suugu\src\suugu.cpp (id: 481)
cpptools/getSemanticTokens: C:\src\suugu\src\canvas.cpp (id: 482)
cpptools/getFoldingRanges: C:\src\suugu\src\canvas.cpp (id: 483)
cpptools/getFoldingRanges: C:\src\suugu\src\suugu.cpp (id: 484)
cpptools/getCodeActions: C:\src\suugu\src\canvas.cpp (id: 485)

</details>

Note that this happens for all unity build cpp files every single time I start a debugging session in vscode. In order to get them to parse correctly again I must open the file they're included in for intellisense to recognize the context they're included in.

**Comment by sean-mcmanus** [comment]
@michelleangela Was more info still needed?
