### ISSUE TITLE
Unable to start debugging program path missing or invalid. GDB failed not in executable format

### ISSUE THREAD

**Issue by stevieA-dot** [microsoft/vscode-cpptools#9200]
### Environment

- OS and version: Windows 11
- VS Code: 1.66.2
- C/C++ extension: C/C++ microsoft
- OS and version of remote machine (if applicable): WSL
- GDB / LLDB version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2

### Bug Summary and Steps to Reproduce

I am trying to setup the debugger for C code but keep getting this error 
![Screenshot 2022-04-18 230827](https://user-images.githubusercontent.com/81679799/163829470-6f407fb6-06b7-4d1d-b759-04de0f4ed769.png)

I am trying to configure the task and launch jsons for the first time and I am wondering what I am doing incorrectly here. I have followed the instructions laid out here https://code.visualstudio.com/docs/editor/debugging 

### Debugger Configurations

```shell
"version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/scheduler.c",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description":  "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc build active file",
            "command": "/usr/bin/gcc",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
Unable to start debugging. Program path is missing or invalid.
GDB failed with message not in executable format. file format not recognised
```

**Comment by elahehrashedi** [comment]
There has been an update on debug experience that made debugging more simple (The documents will be updated soon). 
Follow these steps: 
1. Open a folder, and then open the file you are debugging (scheduler.c)
2. delete your current tasks.json and launch.json both.
3. You will see a debug button on the top right;
![image](https://user-images.githubusercontent.com/16143955/164086935-8025165d-0d61-4384-aa08-e7be8c7bd9dc.png)
if you dont see that button, you may need to go to settings and activate it:
![image](https://user-images.githubusercontent.com/16143955/164087225-5b9e0e83-5272-47a0-80dd-94e7873ecc35.png)
4. after clicking on debug button, you will see a list of debug configurations that you can choose from. Choose the config that the has "PreLaunchTask: C/C++: gcc build active file" 
5. the debug should start.
6. You will notice that a tasks.json will be created.


Please follow these instructions and update me if you still see the error.

P.S.
In the launch.json that you created the program should be changed from `${workspaceFolder}/scheduler.c` to `${workspaceFolder}/scheduler` or `${fileDirname}\\${fileBasenameNoExtension}`
but I would suggest to follow the new version so that you dont have to deal with a launch.json file in first place.

**Comment by stevieA-dot** [comment]
I got it running by replacing the program name with the compiled program that was needed but it's not stopping at the break points that I set. Do you know why this would be happening?

**Comment by elahehrashedi** [comment]
Can you please send your project code if possible, including the tasks.json file.
Also, if possible, Include logs or error messages from the Debug Console or Output windows.
