### ISSUE TITLE
Add buttons to quickly select different compilers

### ISSUE THREAD

**Issue by wcbing** [microsoft/vscode-cpptools#9209]
### Feature Request

![image](https://user-images.githubusercontent.com/63220331/164222314-f625a9f5-e724-4e5b-8005-4d78b45f4853.png)

Can you add a button like the Python extension to select the  c/c++ compiler? Instead of writing it to `tasks.json` and "only can select when you run the file for the first time".
Now I can only delete the json file and select again when I want to switch the compiler in a directory.
![image](https://user-images.githubusercontent.com/63220331/164220746-1c02fe71-a6cc-46b2-b871-2f22a9a7d4c9.png)

And as you can see, this is the only difference in their (default) `tasks.json`.

![20220420](https://user-images.githubusercontent.com/63220331/164219288-5fc72333-d209-49f1-948a-a4da1b129ccb.jpg)

**Comment by elahehrashedi** [comment]
You don't need to delete the tasks.json if you want to add new compilers.
When you create a tasks.json for the first time, the extension will choose that task (related to that compiler) as a default task. That's the reason you can not see the menu again. In order to see the menu, change the tasks.json from this:
```
            "group": {
                "kind": "test",
                "isDefault": true
            }
```
to this:
```
            "group":  "build",
```
We may change the design of this feature, so that the extension doesn't set your first task as a default. Refer to: https://github.com/microsoft/vscode-cpptools/issues/8928
P.S.
The design of the Run and Debug has been modified and simplified in the recent version of the extension, the Docs are being updated soon.

**Comment by WCBing** [comment]
Indeed, changing the isDeFault option can be solved, thank you very much. 

But you still want to have that kind of selection button, which can be easily switched, but you don't have to choose every time. You can see that Dev-cpp also has (screenshot from the Internet). 
![image](https://user-images.githubusercontent.com/63220331/164373158-17381e06-37c0-4f6d-b4d6-d0ba1bca9073.png)

Of course, it's better to have Python extensions like styles.

**Comment by elahehrashedi** [comment]
Thanks for your suggestion. we are currently in the process of simplifying the debugging experience. for quickly selecting between the compilers, in the new design (i.e. next insider version of the C/C++ extension) you can do this:

1. Click on "add debug configuration" button and add different debug configs for your different compilers. Then, a launch.json will be created that is holding all your debug configs.
![image](https://user-images.githubusercontent.com/16143955/166071747-04d519c3-490d-4d12-a1b1-81de276526fc.png)
After that, you can choose between different configs from this panel:
![image](https://user-images.githubusercontent.com/16143955/166072149-e779e696-c167-4fdc-9813-7e97a04e9292.png)

if you don't see the "Add debug configuration" button, go to user settings and activate it:
![image](https://user-images.githubusercontent.com/16143955/166072492-aa5cfa8e-8582-475d-963d-19dc519d8c6a.png)


Let me know if that is what you are looking for (make sure you are using the insider version of our extension).

**Comment by WCBing** [comment]
@elahehrashedi 

You mean I can set it in advance , and then choose from "run and debug" when using it? OK, I will experience it and give you feedback as soon as possible. 

I would like to offer additional advice: 
1. Put the selection on the bottom bar instead of the sidebar panel, because users probably just want to run it, and when I'm going to switch compilers probably because I'm going to run different files. So doesn't have to put it in debug sidebar panel, it's still not intuitive enough for convenience.
2. If I set it up, there will be a global launcher.json, which can then be configured separately in the workspace. Because many of these are generic, it is not necessary to have them in every workspace. 

I hope we can discuss whether this is feasible. Thank you😉

**Comment by elahehrashedi** [comment]
You can copy all the configurations that you added to your local launch.json and paste them into your **user** or **workspace** launch settings to be able to see them in all of your workspaces. 

example:
![image](https://user-images.githubusercontent.com/16143955/167928336-56a13264-1626-4ef2-b421-edde4d0bff12.png)
