### ISSUE TITLE
IntelliSense disable Auto Guess Encoding

### ISSUE THREAD

**Issue by mxdie** [microsoft/vscode-cpptools#9233]
Bug type: Language Service

**Describe the bug**
- OS and Version:windows10
- VS Code Version:1.67.0-insider
- C/C++ Extension Version:1.9.8
- Other extensions you installed (and if the issue persists after disabling them):no
- If using SSH remote, specify OS of remote machine:ubuntu 18
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
if i set C_Cpp: Intelli Sense Engine to default, the vscode feature Auto Guess Encoding is not work
if i open a file gb2312 encoded file, it will open as utf8 and garbled(my default encoding is utf8)
this problem will disappear when i set  C_Cpp: Intelli Sense Engine to disable

**Steps to reproduce**

1. inslall C/C++ extension 
2. set C_Cpp: Intelli Sense Engine to default
3. set Files: Encoding to utf8
4. open Files: Auto Guess Encoding
5. open a file encoded gb2312 
6. See error

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @mxdie .  Can you provide more information, such as an image showing the incorrect encoding and where/how it is incorrect?

I don't think the C/C++ extension can influence the encoding or charset VS Code uses when opening a file.  (An issue tracking adding that capability is here and has not yet been addressed: https://github.com/microsoft/vscode/issues/824 ).

However, the C/C++ extension does open headers that are not currently open in VS Code, in order to parse them for IntelliSense, and to get the text of documentation comments, etc..  The extension will use VS Code's `files.encoding` setting when parsing unopen header files ( https://github.com/microsoft/vscode-cpptools/issues/414 ).  However, the IntelliSense implementation does not have access to the same algorithm that VS Code uses when `files.autoGuessEncoding` is used ( https://github.com/microsoft/vscode-cpptools/issues/4753 ).  This can result in incorrect encoding displayed in some places, such as doc comments on hover.  If this is the issue you are seeing, consider up-voting https://github.com/microsoft/vscode-cpptools/issues/4753 .

**Comment by mxdie** [comment]
> Hi @mxdie . Can you provide more information, such as an image showing the incorrect encoding and where/how it is incorrect?
> 
> I don't think the C/C++ extension can influence the encoding or charset VS Code uses when opening a file. (An issue tracking adding that capability is here and has not yet been addressed: [microsoft/vscode#824](https://github.com/microsoft/vscode/issues/824) ).
> 
> However, the C/C++ extension does open headers that are not currently open in VS Code, in order to parse them for IntelliSense, and to get the text of documentation comments, etc.. The extension will use VS Code's `files.encoding` setting when parsing unopen header files ( #414 ). However, the IntelliSense implementation does not have access to the same algorithm that VS Code uses when `files.autoGuessEncoding` is used ( #4753 ). This can result in incorrect encoding displayed in some places, such as doc comments on hover. If this is the issue you are seeing, consider up-voting #4753 .

When you just open the file/switch the page, the automatic encoding is normal. After a short period of time, the encoding of the file is automatically converted to utf8. This problem is encountered recently.

**Comment by Colengms** [comment]
> When you just open the file/switch the page, the automatic encoding is normal. After a short period of time, the encoding of the file is automatically converted to utf8. This problem is encountered recently.

Hi @mxdie .  If I understand your issue correctly, I would suggest opening an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).  There is no API that allows an extension to modify the encoding of a document in the editor, so you would seem to be encountering an issue with VS Code itself.

I know VS Code converts documents into utf8 internally, as provides document buffers to extensions in utf8 only.  It's possible there may be a bug that incorrectly updates the encoding indicated in the UI.
