### ISSUE TITLE
With cpptools 1.10.2, use of std::shared_mutex causes crash on Mac 10.11 (El Capitan) or earlier

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9309]
It's because it calls wordexp/wordfree which aren't available on those earlier OS's. I'm not sure what the fallback behavior is in this case. IntelliSense might fail to configure correctly.

The workaround would be to downgrade to 1.9.8.

Officially, we don't support Mac 10.11, but in this case the regression can be avoided.

**Comment by sean-mcmanus** [comment]
It looks like cpptools itself may not even run on Mac 10.15 or older with 1.10.2.

**Comment by Colengms** [comment]
It looks like our processing of stack reports was failing to identify the process name correctly (as "cpptools?").  The issue appears to be with the main cpptools process and not cpptools-wordexp, as cpptools is definitely failing in dyld trying to load a library containing `std::shared_mutex`-related code.  Because we have extremely few users on macOS versions <=10.11, we're considering addressing this by increasing our minimum required macOS version (or at least enforcing that minimum, as we are currently building for 10.12).
