### ISSUE TITLE
Improve search under CTRL+T list

### ISSUE THREAD

**Issue by 0xhellord** [microsoft/vscode-cpptools#9346]
### Feature Request

I use vscode to browse linux kerenl code, but got two isssues when search in CTRL+T list:

1. slow to show search result;
2. use keyword "kvm_arch_vcpu" can got what I want, but "kvm arch vcpu" doen't;

gif:
![ctrltslow](https://user-images.githubusercontent.com/6876941/169651412-04089238-d2cd-40dc-8f2d-7871cda28b41.gif)

(The databases file is 600M+)

**Comment by sean-mcmanus** [comment]
The performance issues are already known and being tracked by https://github.com/microsoft/vscode-cpptools/issues/7908 and https://github.com/microsoft/vscode-cpptools/issues/7914 so you could upvote those issues.

The spaces not finding matches is being tracked by https://github.com/microsoft/vscode-cpptools/issues/2751 -- we don't currently implement a fuzzy symbol search due to performance reasons.
