### ISSUE TITLE
[Feature request] Faster error highlights for large projects like Unreal Engine?

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/vscode-cpptools#9405]
### Feature Request

Hi, for a while Unreal Engine have started to offer support for VS Code (they offer a built in extension dedicated towards making the engine more friendly for use with VS Code as ones primary code editor), overall I think writing the code in VS Code gives a nicer experience than VS, with the one exception that it takes a long time for this C++ extension to highlight errors and such even on more powerful machines.

I have an i9-12900K, 32gb of DDR4 (Running Windows 11). For the time being it takes about 10 seconds to pick up for a single line code change with Visual Studio Code, Microsofts C++ extension with default configuration (v.1.9.8)
https://user-images.githubusercontent.com/20190653/172000938-0facdfcd-db7b-40dd-989b-19aefa15069d.mp4

The following settings allowed me _some_ speed improvement, now takes about 4-6 seconds to parse (something Ive noticed is that some times it takes longer than other times? Or at least it feels that way):
```
    "C_Cpp.codeAnalysis.maxConcurrentThreads": 24,
    "C_Cpp.references.maxConcurrentThreads": 20,
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
      },
    "editor.quickSuggestionsDelay": 1,
```

**Comment by sean-mcmanus** [comment]
This issue should be fixed by https://github.com/microsoft/vscode-cpptools/issues/3628 .

It is currently expected that VS will give a better/faster experience for Unreal Engine than VS Code due to that issue.

The C_Cpp.codeAnalysis setting should only effect the Run Code Analysis commands when run over multiple files, and the C_Cpp.references setting should only affect Find All References or Rename, and not IntelliSense update in general.
