### ISSUE TITLE
Semantic features in multi-root workspace

### ISSUE THREAD

**Issue by geertj** [microsoft/vscode-cpptools#9473]
### Feature Request

It would be nice if Intellisense would be able to provide semantic analysis across different projects in a multi-root workspace. Currently, the tag parser supports "Go To Definition" to any project in a multi-root workspace, but the semantic features do not appear to support this. The only way I could make this work is to set `includePath` in the `c_cpp_properties.json` file to list the source directories for each project, in every project.

**Comment by sean-mcmanus** [comment]
Did you try setting the C_Cpp.default.includePath for the workspace?

**Comment by geertj** [comment]
@sean-mcmanus, yes, setting the default includePath at the root of a multi-root workspace works across all projects. It would be nice though if Intellisense could pick up the individual project preferences. In our setup, the multi-root workspace itself is not in source control, but the individual projects are. This makes setting up a new workspace more cumbersome than it needs to be.

**Comment by sean-mcmanus** [comment]
I don't fully understand what design you're asking for. A single c_cpp_properties.json that is shared by all workspace folders? i.e. https://github.com/microsoft/vscode-cpptools/issues/2060 ?

**Comment by geertj** [comment]
What I had in mind is a little different from #2060. I would like Intellisense in one project (configured by a c_cpp_properties in that project) to be able to resolve types and other semantic information defined in other projects in the same multi-root workspace (each configured by their own c_cpp_properties file).

For example, if project 1 uses a function `foo()` which is defined in project 2, then hovering over `foo()` should give me full type information and argument names from the definition of the function inside a source file in project 2, without me having to configure project 2 in the includeDirs of project 1, as long as they are in the same workspace.

Currently the tag parser works this way (using browse.path), possibly by accident because it uses a single database for all projects in a multi-root workspace. The Java is extension can similarly do this.

**Comment by sean-mcmanus** [comment]
Types and semantic information are all normally compiled into a single TU, i.e. you'd need to have some header file exported by one workspace be included by a source file in another workspace in order to get the code to compile (same as with IntelliSense). Basically, this should work if you're able to configure IntelliSense to match how you're compiling the code. You could possibly use the forcedInclude setting to force certain header files with type information to be included in the TUs.

The tag parser does not do compilation of a TU and is just a database of global symbols.
