### ISSUE TITLE
Keep getting the error "The language server crashed 5 times in the last 3 minutes. It will not be restarted."

### ISSUE THREAD

**Issue by ExceptionalHandler** [microsoft/vscode-cpptools#9494]
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 16 
- VS Code Version:
- C/C++ Extension Version: 1.68.0 Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
- Other extensions you installed (and if the issue persists after disabling them): None
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Single big project workspace, language server keeps crashing. Tried uninstalling, re installing restarting, upgrading - nothing works. 

**Steps to reproduce**

1. Instal C/C++ extension
2. Restart vscode
3. Note to see error : `Connection to server got closed. Server will not be restarted.` on console
4. Notification pops up in the side with message : "The language server crashed 5 times in the last 3 minutes. It will not be restarted."
5. Intellicense , debuggind does not work. 
6. We use clang compiler installed in a custom folder 

**Expected behavior**

Language server should not crash and intellicense should work. It worked before. 

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json` Could not find this file. 

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
What version of the C/C++ extension are you using that is crashing? Which previous version worked for you?

1.10.7 has one known crash that is fixed in 1.11.0: https://github.com/microsoft/vscode-cpptools/issues/9437

Do you know what triggers the crash? Does it crash if no files are opened? Are you able to open some different workspace to cause it to not crash? Are you able to change any settings to make it not crash? If so, then if you could attach a debugger to the cpptools process (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) and then trigger the crash you could get a crash call stack. Otherwise, there may be a way to enable core dump file creation in your OS to get a call stack when the crash occurs.
