### ISSUE TITLE
Clang-tidy auto-fix shall save the file after the fix

### ISSUE THREAD

**Issue by pramodkirchki** [microsoft/vscode-cpptools#9520]
### Feature Request

After Code analysis is run on an active cpp file, if a member variable is not initialized in constructor, the error is flagged as "Constructor does not initialize these fields: my_member_variable" thanks to [cppcoreguidelines-pro-type-member-init](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/cppcoreguidelines-pro-type-member-init.html#cppcoreguidelines-pro-type-member-init).

Fortunately, there is an auto-fix available for this clang-tidy warning and indeed clicking on the squiggle and opting to fix the problem initializes the member variable in-class.

However, if the class definition is in a header file, it is not saved by default. It would be good if VScode can save the file after fixing clang-tidy warnings.

Opting to fix the cppcoreguidelines-pro-type-member-init errors for all the files in the workspace would then save all the files automatically instead of manually saving.

**Comment by Colengms** [comment]
Hi @pramodkirchki .  Thanks for providing this suggestion.

**Comment by sean-mcmanus** [comment]
We didn't want to auto-save, because the clang-tidy fix may result in changes that are not desirable to be saved due to the creation of non-compileable code, which would typically be detected by new IntelliSense squiggles appearing in the modified, but unsaved files. If the files were to be auto-saved, it would increase the risk the incorrect code being permanent if the undo history is lost from a reload window.

However, it's possible that we or VS Code itself could have some setting that users can opt-in to auto-save -- or you can use the existing files.autoSave feature in VS Code which applies after any edit.

**Comment by pramodkirchki** [comment]
yes, I agree that you make a valid point that auto-save requires source control. If not, the fixes are not noticeable.

But, IMO most people in academia or industry or even hobbyists who use clang-tidy will have some kind of source-control. But, that is just relying on something outside your control.

Having an option to auto-save after fixing seems to be a valid solution to me since I work with source control.
