### ISSUE TITLE
Run Code Analysis on Active File should trigger code analysis only on the active file

### ISSUE THREAD

**Issue by pramodkirchki** [microsoft/vscode-cpptools#9529]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 Enterprise
- VS Code Version: 20H2
- C/C++ Extension Version: v1.10.7
- Description : Ctrl+Shift+P and run the option "C/C++: Run Code Analysis on Active File" triggers clang-tidy to run on the complete workspace instead of the active file.

**Expected behavior**
Run Code analysis on active file should trigger code analysis only on the active file

**Comment by sean-mcmanus** [comment]
This is currently "by design". The "active file" intentionally defaults to "active file and any headers included from the current workspace folder" under the assumption that those would be the preferred results for most scenarios. You can override that default by setting `"C_Cpp.codeAnalysis.clangTidy.headerFilter": ""` to get only issues for the actual file or set `"C_Cpp.codeAnalysis.exclude": { "**/subFolder": true }` to only exclude headers from certain subfolders.
