### ISSUE TITLE
Having the extension "C/C++ Themes" breaks the color highlighting for other plugins.

### ISSUE THREAD

**Issue by sergei-kashlikov** [microsoft/vscode-cpptools#9595]
### Environment

Version: 1.69.1 (user setup)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:24.514Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

### Bug Summary and Steps to Reproduce

Bug Summary:
Having the extension "C/C++ Themes" breaks the color highlighting for other plugins.

Steps to reproduce:
1. Install [C/C++ Themes](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes) extension, enable any theme.
2. Install [LinkerScript](https://marketplace.visualstudio.com/items?itemName=ZixuanWang.linkerscript) extension.
3. Open any linker script file with .ld extension.

### Other Extensions

https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes
https://marketplace.visualstudio.com/items?itemName=ZixuanWang.linkerscript

### Additional Information

With the extension "C/C++ Themes" I have this highlighting:
![image](https://user-images.githubusercontent.com/66557275/179353873-7039f442-a007-4275-bdfd-f6cc8bf40965.png)

Without (disabled) the extension "C/C++ Themes" I have this highlighting:
![image](https://user-images.githubusercontent.com/66557275/179353904-a1bd483c-ed5e-4149-8e85-26200d62465f.png)

The original issue is [here](https://github.com/TheNetAdmin/vscode-linkerscript/issues/4).

**Comment by sean-mcmanus** [comment]
Also, the issue repros without the C/C++ Themes extension, just by changing the theme to Dark (Visual studio) theme.

**Comment by sergey-kashlikov** [comment]
Why this extension can't be applied only for C/C++ files?

**Comment by Colengms** [comment]
Hi @sergey-kashlikov .   Supporting per-language theming would seem to be a great suggestion that you might consider opening an issue for in [the VS Code repo](https://github.com/microsoft/vscode/issues).  I do see an existing extension that seems to provide that capability: https://marketplace.visualstudio.com/items?itemName=jsaulou.theme-by-language 

The C/C++ Themes were released to provide colors for semantic tokens when support for semantic tokens in the C/C++ extension was initial released.  VS Code has since standardized semantic tokens APIs, and updated the default "plus" themes to include those tokens.  The C/C++ Themes are still provided, for those who want their VS Code colors to closely resemble VS 2017.  (https://github.com/microsoft/vscode-cpptools/issues/6108 is tracking updating the colors to reflect more recent versions of VS).  But, they are no longer required for colorization of semantic tokens in C/C++.  I'd suggest using one of the default "plus" themes.
