### ISSUE TITLE
Two Find All References button in right context menu of editor.

### ISSUE THREAD

**Issue by KAGEYAM4** [microsoft/vscode-cpptools#9637]
### Environment

- OS and version:  windows 11 21H2
- VS Code: 1.69.2
- C/C++ extension:  v1.11.4
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:
Steps to reproduce:
1. right click in editor and we can see two duplicate option of "Find all References".

### Additional Information

![image](https://user-images.githubusercontent.com/75798544/180840694-e30e91a1-740a-4fba-a5a2-5c7eff00094f.png)

**Comment by Colengms** [comment]
Hi @PhoenixCODE2322   I'm not able to reproduce this issue.  Also, the C/C++ Extension does not add `Find All References` to the context menu.  It's added by VS Code itself when there are extensions that have registered `ReferenceProvider`'s.  I don't see any mention of this issue in [the VS Code repo](https://github.com/microsoft/vscode/issues) after a quick search.  You might consider opening an issue there and including any details about your environment that might help explain why this is repro'ing on your system.

**Comment by michelleangela** [comment]
@PhoenixCODE2322, to double check, are there other C++ extensions installed?

**Comment by PhoenixCODE2322** [comment]
> @PhoenixCODE2322, to double check, are there other C++ extensions installed?

found the issue .. i am using portable mode .. i tried disabling every extension other than c/c++ but it was still happening and only when c/c++ was disable both two option goes away.

so i downloaded another zip of vscode copied my data over there . and problem was not there ..

So the problem was for last 5 months to upgrade my portable vscode i was just overwriting the files with the files in new vscode.zip and this caused the issue ..
