### ISSUE TITLE
Use vscode debug console for output instead of terminal when `"type": "cppdbg"`

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#9696]
### Feature Request

Debug Console is a cool feature, but it turns out that it works with program output only when `"type": "cppvsdbg"` in launch.json.
In case of `cppdbg` type, common terminal is used for output.

Or am I using something wrong or this feature should be definitely added.

UPDATE: I found that `"avoidWindowsConsoleRedirection": true` fixes the problem and output is printed to debug console. I don't quite understand what's going on, Was it intentional? But why?

**Comment by WardenGnaw** [comment]
`"avoidWindowsConsoleRedirection": true` is the correct way to force the output to show in the Debug Console. If that is not set, we determine that users want to use the integrated terminal for input and output. 

See https://code.visualstudio.com/docs/cpp/launch-json-reference#_avoidwindowsconsoleredirection 

This is the default since Debug Console does not support input.

**Comment by yhsb2k** [comment]
I found that `"avoidWindowsConsoleRedirection": true` has no effect on Linux. What is the way to output to Debug Console on Linux?

**Comment by lumotroph** [comment]
On my Mac, the way to output to Debug Console is as follows:

- In `launch.json`, set `"console": "internalConsole",` (which is now the default on VSCode) - I had been using `"console": "integratedTerminal",` by mistake.
