### ISSUE TITLE
Intellisense not working in Linux

### ISSUE THREAD

**Issue by marcofiocco** [microsoft/vscode-cpptools#975]
I can’t get Intellisense to work in Linux. I’m compiling with gcc 6.2.1 (devtoolset-6) and the project is built with cmake 3.6.3. I don’t get any wiggles under the include statements but I cannot navigate the code.

OS: Linux CentOS 7
VS Code 1.15.0
C/C++ 0.12.2

I don't have other C/C++ extensions installed. Only extensions for CMake, Debugger for Chrome, Docker, ESLint, Go, Python, TSLint, vscode-icons, vscode-proto3

Attached are VS Code json settings:
[config.zip](https://github.com/Microsoft/vscode-cpptools/files/1228037/config.zip)

**Comment by bobbrow** [comment]
Have you seen issue #19?  I believe CentOS 7 is distributed with an older version of GLIBC.

**Comment by marcofiocco** [comment]
Oh thanks, that made it mostly working. I can navigate some symbols. Although there are still a couple of puzzling things.
- When I type code the autocompletion is still fuzzy, I don't get exact functions for a class.
- I don't see any file for the database, even if I set it to "build/browse.VC.db"
- I still see wiggles for some include files, but I can navigate in those anyway, even if I didn't specify them in the includePath (I have put them in the "browse" tag though)

**Comment by bobbrow** [comment]
1. If you are not getting exact suggestions, then you need to check your settings and see if `"C_Cpp.intelliSenseEngine"` is set to `"Default"`.  If it is, then the problems window will tell you if we switched back to the inexact engine because we couldn't resolve your #includes.  In that case, click on the light bulb that appears when you highlight the green squiggle and fix up your `"includePath"`

2. If you use a relative path for the `"databaseFilename"` property, the root path is your workspace storage folder, not the ${workspaceRoot}.  Prepend your path with ${workspaceRoot} to make it an absolute path and it will show up where you expect (e.g. "${workspaceRoot}/build/browse.VC.db")

3. Navigation is currently still provided by the Tag Parser ("browse") engine and the squiggles are provided by the Default IntelliSense engine, so there is a discrepancy right now.

**Comment by marcofiocco** [comment]
1. My settings are
{
    "workbench.iconTheme": "vscode-icons",
    "cmake.cmakePath": "cmake3",
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Enabled",
    "C_Cpp.errorSquiggles": "Disabled"
}
The problems window says it cannot resolve the includes. But even if I fix the includePath I don't see any improvement. Regardless of that, I can actually navigate in the include files, so the error messages seem not real. However when I type code, the proposed completions are not restricted to the methods of my class, it shows a lot more that is not relevant.

2. That works

3. see 1

**Comment by bobbrow** [comment]
Can you share your includePath and the path to the #include that does not resolve?  If you can't share exact paths due to IP concerns, feel free to anonymize it.

As long as there are #include errors, you will continue to get inexact auto-complete suggestions.  You can force the semantic IntelliSense engine to run by choosing the "force semantic IntelliSense" option on the light bulb, but symbols from the unresolved headers will not be available in the auto-complete lists.  It is important to get the includePath configured so that you can have predictable IntelliSense.

**Comment by marcofiocco** [comment]
The properties I have are:

```
           "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "/home/administrator/Code/Aget/refs",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/build/browse.VC.db"
            }
        },
```

For example, I have #include <grpc/grpc.h>
which is in /usr/local/include/grpc/grpc.h but I see wiggles under it, even if /usr/local/include is listed in includePath.
Same for almost all the other includes.

**Comment by alanbirtles** [comment]
the default include paths are insufficient, if you look in the problems window it will show which files can't be found, on my centos 7 install I had to add /usr/include/c++/4.8.5/x86_64-redhat-linux/ to get "bits/*.h" includes to work (for devtoolset 4 I had to add "/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1", "/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/x86_64-redhat-linux", "/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/", presumably 6 is the same)

**Comment by marcofiocco** [comment]
You are right, I don't get wiggles (and problems in the window)  if I specify those last 3 paths for devtoolset 6, however the strange thing now is that I can't navigate inside those headers.
I've tried also to delete the database file and restart Code.
It seems I can navigate only files found in the path of the "browse" setting.

**Comment by sean-mcmanus** [comment]
@marcofiocco Yes, you should add paths to browse.path too (the symbol database uses that), such as  `/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1`, which will recursively find the other paths (unlike includePath, which is non-recursive.
