### ISSUE TITLE
I can't run/Debug C program when I disable c/c++ intellisense for clangd.

### ISSUE THREAD

**Issue by suyangzuo** [microsoft/vscode-cpptools#9762]
### Environment

- OS and version: Windows11 x64
- VS Code: 1.70
- C/C++ extension: 1.20
- GDB / LLDB version: 12.1

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Install clangd for intellisense, it asked me to disable c/c++ intellisense or there will be conflict.
2. Disable c/c++ intelli sense Engine.
3. Click 'Run and Debug'
4. Then a error 'Default config not found in provideDebugConfigurations()' popup on the bottom-right.

### Debugger Configurations

```shell
None.
There problem is just 'cannot generate tasks.json'.
```

### Debugger Logs

```shell
None.
```

### Additional Information

![Code_jTkyUHBcTD](https://user-images.githubusercontent.com/50766353/185726338-c4811e65-e14e-474e-b60e-58c564b3a54c.gif)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. We can look into fixing this for our next insiders release.

**Comment by sean-mcmanus** [comment]
FYI, a workaround is to generate a launch.json via some other method. You could also set C_Cpp.intelliSenseEngine to "Default" temporarily to use that mechanism to generate the launch.json. Or downgrade to 1.8.4 to create the launch.json.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.12.2 -- but FYI, if you don't have a launch.json, you'll need to click the Open launch.json button in the UI that pops up to generate a blank launch.json and then use the Add Configuration button in the bottom right to add a launch.json configuration. The ability to auto-generate the launch.json from the compilers we detect currently requires the intelliSenseEngine to be set to Default.
