### ISSUE TITLE
Header File not found but confirmed by path by developer

### ISSUE THREAD

**Issue by victoryred** [microsoft/vscode-cpptools#9877]
### Environment

- OS and version:
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:
OS:
Linux raspberrypi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

Environment: Developing an app using the Libcamera library;

In Visual Studio Code 1.71.1 using the C/C++ Extension
Code...main.cpp

#include <libcamera/camera.h>
#include <libcamera/property_ids.h>

error is that ;
#include <libcamera/camera.h> is not found
#include <libcamera/property_ids.h> IS found

Both header files and path were confirmed by bug reporter.

Full path: /home/tetra/libcamera/include/libcamera

Observation: Looks like a recursion not working issue.

Steps to reproduce:Starting build...
/usr/bin/g++ -fdiagnostics-color=always -g /home/tetra/libcamera/src/cam/main.cpp -o /home/tetra/libcamera/src/cam/main
/home/tetra/libcamera/src/cam/main.cpp:14:10: fatal error: libcamera/camera.h: No such file or directory
14 | #include <libcamera/camera.h>
| ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

Build finished with error(s).

Path is: /libcamera/include/libcamera/camera.h

c_cpp_properties.json
{
"configurations": [
{
"name": "Linux",
"includePath": [
"${workspaceFolder}/**"
],
"defines": [],
"compilerPath": "/usr/bin/gcc",
"cStandard": "gnu17",
"cppStandard": "gnu++14",
"compileCommands": "${workspaceFolder}/build/compile_commands.json"
}
],
"version": 4
}

VS Code version: Code 1.71.0 (https://github.com/microsoft/vscode/commit/784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:24:19.271Z)
OS version: Linux arm64 5.15.61-v8+
Modes:
Sandboxed: No

System Info
Extensions (9)
A/B Experiments
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

### Other Extensions

C/C++ Extension Pack

**Comment by Colengms** [comment]
Hi @victoryred .  There error you are seeing appears to be a compilation error, and not related to the C/C++ Extension (which provides language services, but not a build system - at least not beyond a simple tasks that allows a single file to be compiled).  The issue would seem to be related to your build system or the compile command line you are invoking to build.  The compiler would seem to need a `-I` argument passed to it, providing it the location of your headers.  Your source file is under `/home/tetra/libcamera/src/cam/`, but `include/libcamera` is within `/home/tetra/libcamera/`.  The compiler will need to be pointed to that directory, as it will not automatically search 'up' two directories for it.

As this issue is not related to the C/C++ Extension itself, I'll close it.
