### ISSUE TITLE
"C_Cpp.loggingLevel" - not available as folder setting when using a workspace file

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#9993]
Type: <b>Feature Request</b>

I'd like my workspace file to contain only settings that can be checking in a VSC, therefore I'd like to set     "C_Cpp.loggingLevel": "Debug" in the local folder in ".vs/settings.json".

Extension version: 1.13.2
VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:23:00.760Z)
OS version: Linux x64 5.15.0-50-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.42GB (3.20GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 20280fc3-3c6d-43d3-9eb5-55c536b003d8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
pyindex848cf:30577861
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by Colengms** [comment]
Hi @Zingam .  Currently, this is by design.  The C/C++ extension has this single setting for the log level, and a multi-root workspace involves a single instance of the extension.

Would you like to convert this to a feature request that we allow logging to be filtered on a per workspace folder basis?  (Some log messages would not be specific to a workspace folder.)

**Comment by Zingam** [comment]
> Would you like to convert this to a feature request that we allow logging to be filtered on a per workspace folder basis? (Some log messages would not be specific to a workspace folder.)

@Colengms Sure. How can I convert this to a feature request? Should I report it again as a feature request?

**Comment by sean-mcmanus** [comment]
This seems like it should be a VS Code feature request to allow setting "application" scope settings in a local settings file.

We have multiple other "application" scope settings and I don't think we want to change all of them to resource scope. You'd have the same issue with other VS Code settings or other "application" scope settings in other extensions.

**Comment by Zingam** [comment]
What would be the recommended action for this? I would like to have a way to specify common settings that are cross-platform and cross user and also that are user and platform specific.

**Comment by sean-mcmanus** [comment]
You should file a feature request on VS Code at https://github.com/microsoft/vscode/issues as this settings manipulation appears to be generic and applicable to other extensions potentially....the potential problem is how to resolve the setting if multiple folders have set it differently, since the extension is expecting a single setting for the entire workspace...i.e. it could choose the 1st setting or something else.

However, I don't understand why you can just set the C_Cpp.loggingLevel at the user or remote scope. Our extension isn't implemented to handle different logging levels with different folders.
